### ISSUE TITLE
Support for PEM encoded RSA keys

### ISSUE THREAD

**Issue by sspreitzer** [libreswan/libreswan#100]
Hi

Referring to #98 i am hereby kindly requesting to add support for PEM encoded RSA key pairs.

Thanks a lot
Sascha

**Comment by letoams** [comment]
I've asked the nss people on how we could import/export raw keys.

We are not going to support loading our own pem files. We use the nss store via their API, which gves us access to PKCS#11, and all hardware modules, etc.

**Comment by cagney** [comment]
Closing as duplicate of #98.
