### ISSUE TITLE
addconn's auto=start(add+up) slightly different to separate ipsec add+up commands

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1003]
`addconn`, for auto=start:

- add connection; this sets UP bit unconditionally
- listen; which orients connection
- up (initiate) connection

however, when this is performed as individual commands, the UP bit is only set during initiate and after a check that the connection is oriented.  Hence, for instance, an unoriented connection won't come up when the missing network is attached.

**Comment by letoams** [comment]
On Fri, 3 Feb 2023, cagney wrote:

> addconn, for auto=start:
>
>  *  add connection; this sets UP bit unconditionally
>  *  listen; which orients connection
>  *  up (initiate) connection
> 
> however, when this is performed as individual commands, the UP bit is only set during initiate and after
> a check that the connection is oriented. Hence, for instance, an unoriented connection won't come up
> when the missing network is attached.

We also do not run 'listen' when network change is detected. We should,
but rather, I would listen on ANY instead of individually found IPs,
so rerunning listen is never needed.

**Comment by cagney** [comment]
9ac34e9df148c34cbfd7ea6be2dd260daed99383
3a40cfa4d7a1350f294abec48a87cdca3d5adccb
