### ISSUE TITLE
How to use RSA_EMSA_PKCS1_SHA2_256 to authenticate the certificate

### ISSUE THREAD

**Issue by sridharkondeti** [libreswan/libreswan#1017]
Hi,

When I used strongswan the certs are authenticated with RSA_EMSA_PKCS1_SHA2_256.
`authentication of 'CN=Serv VPN' (myself) with RSA_EMSA_PKCS1_SHA2_256 successful`

But when I switched to libreswan, the authentication is being done with just "RSA"
`authentication of 'CN=Serv VPN' (myself) with RSA signature successful`

What options are available to enforce RSA_EMSA_PKCS1_SHA2_256 authentication with libreswan.

Thanks!

**Comment by cagney** [comment]
> Hi,
> 
> When I used strongswan the certs are authenticated with RSA_EMSA_PKCS1_SHA2_256.
> `authentication of 'CN=Serv VPN' (myself) with RSA_EMSA_PKCS1_SHA2_256 successful`
> 
> But when I switched to libreswan, the authentication is being done with just "RSA"
> `authentication of 'CN=Serv VPN' (myself) with RSA signature successful`

Are you sure RSASSA-PKCS1-v1_5 isn't being used?  Older versions of libreswan were a little vague on the details (RSA could mean anything), which is why the current output looks more like:
```
003 "westnet-eastnet-ikev2" #1: initiator established IKE SA; authenticated peer '3072-bit PKCS#1 1.5 RSA with SHA2_256' digital signature using preloaded certificate 'C=CA, ST=Ontario, L=Toronto, O=Libreswan, OU=Test Department, CN=east.testing.libreswan.org, E=user-east@testing.libreswan.org' issued by CA 'C=CA, ST=Ontario, L=Toronto, O=Libreswan, OU=Test Department, CN=Libreswan test CA for mainca, E=testing@libreswan.org'
```

**Comment by sridharkondeti** [comment]
Thanks for the response.

I don't see anything like that in the logs. I am setting up one end with strongswan and one end with libreswan. The libreswan side logs are like below.
`Feb 21 18:00:31 redhat5 pluto[30975]: "ipsectest" #46: local ESP/AH proposals for ipsectest (IKE SA initiator emitting ESP/AH proposals): 1:ESP:ENCR=AES_GCM_C_256;INTEG=NONE;DH=NONE;ESN=DISABLED
Feb 21 18:00:31 redhat5 pluto[30975]: "ipsectest" #47: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=aes_256 integ=sha384_192 prf=sha2_384 group=DH20}
Feb 21 18:00:31 redhat5 pluto[30975]: "ipsectest" #47: certificate verified OK: CN=Serv VPN
Feb 21 18:00:31 redhat5 pluto[30975]: "ipsectest" #47: IKEv2 mode peer ID is ID_DER_ASN1_DN: 'CN=Serv VPN'
Feb 21 18:00:31 redhat5 pluto[30975]: "ipsectest" #47: Authenticated using RSA
Feb 21 18:00:31 redhat5 pluto[30975]: "ipsectest" #47: negotiated connection [10.128.0.13-10.128.0.13:0-65535 0] -> [10.128.0.11-10.128.0.11:0-65535 0]
Feb 21 18:00:31 redhat5 pluto[30975]: "ipsectest" #47: STATE_V2_IPSEC_I: IPsec SA established tunnel mode {ESP/NAT=>0xc93d9864 <0x3831581e xfrm=AES_GCM_16_256-NONE NATOA=none NATD=10.128.0.11:4500 DPD=passive}`

**Comment by cagney** [comment]
That log is from something like v3.32.  Even though that version logged the very nondescript "RSA", underneath anything SHA2 should be forcing the RSA PSS code path, vis:
```
	if (hash_algo == 0 /* ikev1*/ ||
	    hash_algo == IKEv2_AUTH_HASH_SHA1 /* old style rsa with SHA1*/) {
...
	} else {
		/* Digital signature scheme with RSA-PSS */
...
		if (PK11_VerifyWithMechanism(publicKey, CKM_RSA_PKCS_PSS,
```
The current version is v4.9 and is structured differently.
