### ISSUE TITLE
Travis CI build

### ISSUE THREAD

**Issue by ericcurtin** [libreswan/libreswan#102]
Most major open-source projects have it these days, I'd happily contribute the changes needed to set this up so all PRs, branches go through a build using those free Travis build servers. Might make PR reviews a bit easier for the reviewers. We can at least build on the following platforms on Travis:

CentOS, Fedora, Ubuntu, Debian, Arch, OpenWrt, OSX

some of these in the form of containers

Would need a libreswan admin to set up the Travis CI account though and link to this github repo

**Comment by letoams** [comment]
On Thu, 8 Jun 2017, Eric Curtin wrote:

> Most major open-source projects have it these days, I'd happily contribute the changes needed to set this up so all
> PRs, branches go through a build using those free Travis build servers. Might make PR reviews a bit easier for the
> reviewers. We can at least build on the following platforms on Travis:
> 
> CentOS, Fedora, Ubuntu, Debian, Arch, OpenWrt, OSX
> 
> some of these in the form of containers
> 
> Would need a libreswan admin to set up the Travis CI account though and link to this github repo

That's a great idea. If you are willing to set this up and be a
maintanance contact for this, let me know. And I can do whatever
admin priv tasks need to be done.

Paul

**Comment by ericcurtin** [comment]
Yeah, that's no problem... I'll set it up with my Travis account on a fork anyway

**Comment by letoams** [comment]
so was there anything you needed from me at this point?

**Comment by ericcurtin** [comment]
Hi Paul,

I just lost a bit of focus and started working on other things. I'll get back to this and at least get a basic build going that at least compiles the code, for a start!

**Comment by cagney** [comment]
Unfortunately, Travis-CI.org has been shutdown.
(@antonyantony did have this working)

**Comment by letoams** [comment]
On Mon, 1 Nov 2021, cagney wrote:

> Unfortunately, Travis-CI.org has been shutdown.
> ***@***.*** did have this working)

Yes, because "if you offer CPU services, they will come",  with "they"
being crypto miners.

We should migrate to Github Actions, but I think we should first migrate
to move to Github as a place where the main branch lives, and have vault
feed it (and maintain backups)
