### ISSUE TITLE
All the error/warning messages are not redirected to a file from when we use ipsec auto with command line

### ISSUE THREAD

**Issue by Arankal** [libreswan/libreswan#1021]
Hi ,
Suppose I have an erroneous ipsec.conf file and when I try to add the same by using ipsec auto command and redirecting the stdout and stderr to a file, only the last entry will be printed in file.

Steps to reproduce:
/home/telcoadm# ipsec auto  --ondemand lconn-978344951
036 "lconn-978344951": failed to add connection: AEAD ESP encryption algorithm AES_GCM_16 must have 'NONE' as the integrity algorithm
025 no connection or alias 'lconn-978344951'

ipsec auto   --ondemand lconn-978344951 >nnn12.txt 2>&1

cat nnn.txt
025 no connection or alias 'lconn-978344951' 

036 error was not redirected to a file.

Thanks,
Nagaraj P Arankal

**Comment by Arankal** [comment]
Hi Experts,
Is this behavior expected?

Thanks,
Nagaraj P Arankal

**Comment by cagney** [comment]
Can you clarify what you mean with an example?

**Comment by letoams** [comment]
On Thu, 2 Mar 2023, Arankal wrote:

> Is this behavior expected?

No. But older versions are known to lose some logging/debug output, due
to the way addconn can be called by pluto (when pluto already redirected
its own output, and when it forks off addconn those stdout/stderr get
missed). We fixed that by moving the parsing/error code from addconn
to pluto, so now pluto should throw those errors back (and log it).

If you find messages being lost in the git main branch version, I'd
be interested to know more and see something we can reproduce.

**Comment by Arankal** [comment]
Hi Paul,
Thanks much. On mainline libreswan code, its working as expected. If you point me to the commit which resolved this behavior, that would be of great help, as we are using libreswab 4.3 code from Debian.

**Comment by cagney** [comment]
> If you point me to the commit which resolved this behavior, that would be of great help, as we are using libreswab 4.3 code from Debian.

This is incremental work so there isn't really a single commit.  However, if you're lucky, it is pluto and not addconn emitting the message.  Check, rcv_whack.c to see if contains the error string.  If the code looks like:
```
llog(WHACK_STREAM|RC_UNKNOWN_NAME....
```
then try dropping `WHACK_STREAM|` from the code.
