### ISSUE TITLE
Is there a way to enable ipsec.service(systemd one), by default

### ISSUE THREAD

**Issue by Arankal** [libreswan/libreswan#1025]
Hi Libreswan experts,
On my debian box, I have 4.3 bulls eye libreswan code. Some how by default ipsec.service is not enabled. From README.debian I found that deliberately they disbaled the ipsec.service. Is there a way to enable the same? As I have 30+ namespaces and I want ipsec.service to be present in each and every namespace.
If there is a quick tweak either in config files or in .mk files, please let me know.

Thanks in advance,
Nagaraj P Arankal

**Comment by paulwouters** [comment]
We just install the file, we cannot activate it. That is systemd / administrators job.When you run systemctl enable ipsec, it creates a few links in /etc that cause it to start on the next “boot”. Perhaps look at those links and manually create them ?Sent using a virtual keyboard on a phoneOn Mar 1, 2023, at 08:31, Arankal ***@***.***> wrote:﻿
Hi Libreswan experts,
On my debian box, I have 4.3 bulls eye libreswan code. Some how by default ipsec.service is not enabled. From README.debian I found that deliberately they disbaled the ipsec.service. Is there a way to enable the same? As I have 30+ namespaces and I want ipsec.service to be present in each and every namespace.
If there is a quick tweak either in config files or in .mk files, please let me know.
Thanks in advance,
Nagaraj P Arankal

**Comment by Arankal** [comment]
Hi Paul,
Thanks for your quick response. As per your suggestion plus README.debian, when I execute systemctl enable ipsec, its pointing to obsoleted sysVinit scripts, rather that systemd related .service files.

**Comment by letoams** [comment]
On Wed, 1 Mar 2023, Arankal wrote:

> Thanks for your quick response. As per your suggestion plus README.debian, when I execute systemctl
> enable ipsec, its pointing to obsoleted sysVinit scripts, rather that systemd related .service files.

then your build wasn't recognised to have systemd. You can rebuild and
add:

INITSYSTEM=systemd

in a new file Makefile.inc.local in the libreswan top dir before running "make deb".

**Comment by Arankal** [comment]
INITSYSTEM=systemd in Makefile.inc.local did the trick. I am able to see ipsec.service file now. Thanks a lot.
