### ISSUE TITLE
please push git tag for 4.10

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#1026]
i think pushing a signed git tag might have been left out of the release process, but it's really useful for those of us who build from source!

**Comment by letoams** [comment]
On Fri, 3 Mar 2023, dkg wrote:

> Subject: [libreswan/libreswan] please push git tag for 4.10 (Issue #1026)

> i think pushing a signed git tag might have been left out of the release process, but it's really useful for those of us who build from source!

The tag is there on github ? Note it is "v4.10"

But I would put higher trust in the openpgp sig on the tar ball than a release git commit tag myself :)

**Comment by dkg** [comment]
weird, when i do `git remote update` from an existing repo, I do not see the tag, but when i do a clean `git clone https://github.com/libreswan/libreswan` i *do* see the tag.

It looks like the tag is not an ancestor of any specific branch (it is a descendent of the current head of the `v4_maint` branch, afaict).  Maybe that's why `git remote update` isn't working to find it?  should `v4_maint` be moved to point to the same commit as the `v4.10` tag?

**Comment by dkg** [comment]
to demonstrate:

```
git init testing-libreswan
cd testing-libreswan
git remote add origin https://github.com/libreswan/libreswan
git remote update origin
git tag -l | grep v4.10
```

that final command shows only:

```
v4.0
v4.1
v4.2
v4.3
v4.4
v4.5
v4.6
v4.7
v4.8
v4.9
```

**Comment by letoams** [comment]
On Fri, 3 Mar 2023, dkg wrote:

> weird, when i do git remote update from an existing repo, I do not see the tag, but when i do a clean git clone https://github.com/libreswan/libreswan i
> do see the tag.
> 
> It looks like the tag is not an ancestor of any specific branch (it is a descendent of the current head of the v4_maint branch, afaict). Maybe that's why
> git remote update isn't working to find it? should v4_maint be moved to point to the same commit as the v4.10 tag?

The v4.10 tag does not exist in the main branch, only in the v4_maint
branch, which was branched from the v4.9 tag commit in main.

**Comment by bleve** [comment]
tag is now there.
