### ISSUE TITLE
upper layer protocol number support for Auto key

### ISSUE THREAD

**Issue by Arankal** [libreswan/libreswan#1031]
Hi Experts,
As per manual, for leftprotoport or rightprotoport , we can mention protocol name / protocol number from /etc/protocols file.
But if we mention protocol number, we receive error from pluto. For the same protocol name(ex: tcp/udp/icmp/sctp), it works.
Can you please check.

ipsec.conf
conn lconn-1678099542
        left=182.17.188.14
        right=182.17.188.43
        leftprotoport=6    **>>>>**
        auto=ondemand
        type=transport
        authby=secret
        ike=md5;dh14
        phase2=ah
        ah=md5-dh14
        ikev2=no
        aggressive=no

 ipsec auto --ondemand lconn-1678099542
while loading 'lconn-1678099542': Invalid protoport value
addconn, in config '/etc/ipsec.conf', ignoring: Invalid protoport value

From the code, gethostbyname() is used for protocol name, which is perfect, but for protocol number instead of getprotobynumber(), strtol is used. Do I need to append port when we use protocol number for example: 6 for tcp??

Thanks,
Nagaraj P Arankal

**Comment by letoams** [comment]
On Tue, 7 Mar 2023, Arankal wrote:

> leftprotoport=6

> 
> ipsec auto --ondemand lconn-1678099542
> while loading 'lconn-1678099542': Invalid protoport value
> addconn, in config '/etc/ipsec.conf', ignoring: Invalid protoport value

It expects leftprotoport=XXX/YYY  where XXX can be name or number of
protocol (eg "tcp" or "6") and YYY is the port number (eg "0" or "1234"
or "%any")

**Comment by Arankal** [comment]
Hi Paul,
Thanks much for the clarification.
