### ISSUE TITLE
all instantiated sec-label templates look the same

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1034]
With Labeled IPsec, things are instantiated:
```
  template(CK_TEMPLATE) -> parent(CK_INSTANCE) -> child(CK_INSTANCE)
```
when displaying parent/child instances, only the child is assigned and displays an instance number should things instead display nested instance numbers vis:
```
"labeled" -- template
"labeled"[1] - parent
"labeled"[1][1] - child
```
or, like oppotunstic groups, incorporate the label vis:
```
"labeled" -- template
"labeled"[1] - parent
"labeled"[1] access_sutuff
```

**Comment by letoams** [comment]
On Sun, 12 Mar 2023, cagney wrote:

> vis:
> 
> "labeled" -- template
> "labeled"[1] - parent
> "labeled"[1][1] - child
> 
> or, like oppotunstic groups, incorporate the label vis:
> 
> "labeled" -- template
> "labeled"[1] - parent
> "labeled"[1] access_sutuff

How about changing the conn name like in alias conns, and do "labeled/parent"[1] and
"labeled/child"[1] ?

**Comment by cagney** [comment]
> How about changing the conn name like in alias conns, and do "labeled/parent"[1] and
"labeled/child"[1] ?

So:
```
"labeled" -- template
"labeled/parent"[1]
"labeled/child"[1]
"labeled/parent"[2]
"labeled/child"[2]
```
I think it would break down when the second child is added (but using alias might make manipulating easier).

**Comment by cagney** [comment]
> I think it would break down when the second child is added (but using alias might make manipulating easier).

Yes - I think the structure needs to reflect how parents have multiple children; so while ugly:
  "labeled" "labeled"[1] "labeled"[1][1] "labeled"[1][2] ... "labeled"[2] "labeled"[2][1] ...
it at least makes telling templates, parents, and children possible
