### ISSUE TITLE
mipsel build failures with nspr 4.35 and glibc

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#1035]
NSPR version 4.35 made some choices that [changed build behavior on 32-bit mipsel](https://bugzilla.mozilla.org/show_bug.cgi?id=1815947).  The changes were motivated by getting nspr to work against musl, but they broke builds on that architecture if the C library used was glibc.

As a result, libreswan fails now to build from source on mipsel with glibc when building against nspr 4.35.

NSPR's proposed changes to address this breakage appear to only work if the NSPR header files are included after some glibc header files.  NSPR upstream has not yet made a release that includes this fix, but they appear to be OK with it generally.

In debian, which currently always targets glibc (and not musl) i'm currently [patching libreswan](https://salsa.debian.org/debian/libreswan/-/blob/debian/unstable/debian/patches/0004-Include-features.h-to-enable-NSPR-workaround-for-854.patch) to manually include a small glibc header before any nspr header is included.  The minimal header needed by glibc here is `#include <features.h>`, but that's not a standard header file, so i don't think the patch is appropriate to upstream in libreswan, as it sort of commits libreswan to only building against glibc.

I'm not sure the right way to resolve this going forward, but wanted to give y'all a heads-up that it's happening.

A few possible options:

 - advocate for a different change in NSPR to avoid needing to modify libreswan source to build on glibc on mipsel
 - bind libreswan to a particular choice of libc
 - figure out a portable way to modify libreswan source that will let it build against the current nspr fix (e.g.  `#include <stdio.h>` appears to work instead of `#include <features.h>` -- maybe the debian patch should be repurposed with stdio instead of features?
 - mark libreswan as unbuildable on 32-bit mipsel

**Comment by letoams** [comment]
On Mon, 13 Mar 2023, dkg wrote:

> NSPR version 4.35 made some choices that changed build behavior on 32-bit mipsel. The changes were motivated by
> getting nspr to work against musl, but they broke builds on that architecture if the C library used was glibc.
> 
> As a result, libreswan fails now to build from source on mipsel with glibc when building against nspr 4.35.
> 
> NSPR's proposed changes to address this breakage appear to only work if the NSPR header files are included after
> some glibc header files. NSPR upstream has not yet made a release that includes this fix, but they appear to be
> OK with it generally.

>  *  figure out a portable way to modify libreswan source that will let it build against the current nspr fix
>     (e.g. #include <stdio.h> appears to work instead of #include <features.h> -- maybe the debian patch should be
>     repurposed with stdio instead of features?

So this seems the way forward then? I can't see any harm from including
<stdio.h> anywhere, even if it is redundant.

**Comment by dkg** [comment]
that said, you're the libreswan upstream, and if you want to import that fix, that's your call.  if you'd like me to submit it (modified to use stdio.h intead of features.h) as a PR, just let me know.

**Comment by cagney** [comment]
where's the debian patch?

**Comment by dkg** [comment]
it's linked in the bug report description above, but if that doesn't work for you, here's the full URL:

  https://salsa.debian.org/debian/libreswan/-/blob/debian/unstable/debian/patches/0004-Include-features.h-to-enable-NSPR-workaround-for-854.patch

**Comment by cagney** [comment]
Thanks, and WOW!  I agree with your sentiment that this isn't good.

- sprinkling <feature.h> will break BSD builds (which, strangely, aren't glibc based :-)
- sprinkling <stdio.h> seems wrong
- libreswan builds on Alpine Linux which is musl based #880 

One hack would be to add a header that hides the mess and include that.  Somewhat like the existing include/lswnss.h

**Comment by cagney** [comment]
[Original change request to NSPR](https://bugzilla.mozilla.org/show_bug.cgi?id=1765100)
[DKG's regression bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1815947)

**Comment by cagney** [comment]
In mainline it might be possible to dump:
```
#include <prcpucfg.h>
#ifndef BITS_PER_BYTE
# define BITS_PER_BYTE  8
#endif
```
in favour of `CHAR_BIT` from `<limits.h>`.

**Comment by cagney** [comment]
this is fixed in mainline
