### ISSUE TITLE
How to delete a CA cert?

### ISSUE THREAD

**Issue by jlearman** [libreswan/libreswan#1038]
We are using the `whack` interface to control Pluto.

We add CA certs using `certutil`.  Added CAs appear in `whack --listcacerts`.  If I delete one using `certutil`, it still appears in `whack --listcacerts`.  How can I get Pluto to update its list of CAs, and remove the deleted CA?  `--rereadcerts` and `--rereadall` don't help.

**Comment by cagney** [comment]
Something must still be referencing the cert, it could be a connection, but it could also be the root_certs cache.
If pluto is idle for more than 5 minutes the cache is flushed automatically.  However, the event can also be triggered manually with:
```
ipsec whack --impair trigger:FREE_ROOT_CERTS
```
this should be made part of --rereadcerts.

**Comment by jlearman** [comment]
Thanks!
