### ISSUE TITLE
Nvidia (mellanox) ConnectX-6 Dx ipsec offload issue

### ISSUE THREAD

**Issue by AnatoliChe** [libreswan/libreswan#1043]
Hello!

I realize this issues related with hw/drivers not with Libreswan, but maybe you could know who to help.

Hardware esp offload just do not work with my mellanox cards, I even have bought new MCX623106AC-CDAT (2x100g)
So now I tried:
MCX623106AC-CDAT (MT2892)
MCX621102AC-ADAT (MT28841)
Dell 340 and Dell 350 servers
Debian with default kernel do not have compiled support of mellanox offload (and I understand why). So I tried compiled module for debian kernels, tried mlnx drivers 5.9-0.5.6.0, 5.8-2.0.3.0-LTS, 5.4-3.6.8.1-LTS, 4.9-6.0.6.0-LTS.
also Tried drivers from kernels 5.10.x 5.15.x 6.1.20 6.2.7 6.3-rc3
tried all variants of fw 22.36.1010 22.35.2302-LTS and default ones.
I even tried insert in the servers intel's cards and move ip between intel and mellanox - intel works like a charm nvidia is a glitch. (

Maybe you can know solution do not like kick nvidia to rabbish bin and buy some more reliable?

**Comment by letoams** [comment]
I should have two cards for testing soon myself.

**Comment by AnatoliChe** [comment]
Super! Is it DX6?
As I guess they spend all their effort for new DX7.
Looking forward to

**Comment by AnatoliChe** [comment]
Hi!
Maybe there any news about mellanox issue?
I hoped this [b062caf4f73b7319a81b4f7e4df4957bdc1c47ca](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.1.36&id=b062caf4f73b7319a81b4f7e4df4957bdc1c47ca) commit can help, but no (

**Comment by letoams** [comment]
On Jul 1, 2023, at 20:00, AnatoliChe ***@***.***> wrote:
> 
> ﻿
> Hi!
> Maybe there any news about mellanox issue?
> 
I am waiting on delivery of supermicro hardware to our cards in, should arrive any day now 😀
(I didn’t have PCIe 5.0 capable hardware)

Paul

**Comment by AnatoliChe** [comment]
PCIe 5.0 so it's must be ConnectX-7 
5 and 4 must be back compatible.
I tried order dx7 but it is not available to order yet.
I have
ConnectX-6 Dx EN adapter card, 100GbE, Dual-port QSFP56, PCIe 4.0 x16, Crypto and Secure Boot 
and
ConnectX-6 Dx EN adapter card, 25GbE, Dual-port SFP28, PCIe 4.0 x8, Crypto and Secure Boot 
but this one plug to x4 slot
[Mon Jul  3 10:40:38 2023] mlx5_core 0000:03:00.0: firmware version: 22.36.1010
[Mon Jul  3 10:40:38 2023] mlx5_core 0000:03:00.0: 31.504 Gb/s available PCIe bandwidth, limited by 8.0 GT/s PCIe x4 link at 0000:00:1b.0 (capable of 126.024 Gb/s with 16.0 GT/s PCIe x8 link)
[Mon Jul  3 10:40:38 2023] mlx5_core 0000:03:00.0: Rate limit: 127 rates are supported, range: 0Mbps to 24414Mbps
[Mon Jul  3 10:40:38 2023] mlx5_core 0000:03:00.0: Port module event: module 0, Cable plugged
[Mon Jul  3 10:40:38 2023] mlx5_core 0000:03:00.0: mlx5_pcie_event:301:(pid 191): PCIe slot advertised sufficient power (25W).
[Mon Jul  3 10:40:38 2023] mlx5_core 0000:03:00.0: mlx5e: IPSec ESP acceleration enabled
[Mon Jul  3 10:40:38 2023] mlx5_core 0000:03:00.0: MLX5E: StrdRq(1) RqSz(8) StrdSz(2048) RxCqeCmprss(0)
[Mon Jul  3 10:40:39 2023] mlx5_core 0000:03:00.1: firmware version: 22.36.1010
[Mon Jul  3 10:40:39 2023] mlx5_core 0000:03:00.1: 31.504 Gb/s available PCIe bandwidth, limited by 8.0 GT/s PCIe x4 link at 0000:00:1b.0 (capable of 126.024 Gb/s with 16.0 GT/s PCIe x8 link)
[Mon Jul  3 10:40:39 2023] mlx5_core 0000:03:00.1: Rate limit: 127 rates are supported, range: 0Mbps to 24414Mbps
[Mon Jul  3 10:40:39 2023] mlx5_core 0000:03:00.1: Port module event: module 1, Cable plugged
[Mon Jul  3 10:40:39 2023] mlx5_core 0000:03:00.1: mlx5_pcie_event:301:(pid 191): PCIe slot advertised sufficient power (25W).
[Mon Jul  3 10:40:39 2023] mlx5_core 0000:03:00.1: mlx5e: IPSec ESP acceleration enabled
[Mon Jul  3 10:40:39 2023] mlx5_core 0000:03:00.1: MLX5E: StrdRq(1) RqSz(8) StrdSz(2048) RxCqeCmprss(0)

Hope You will have great experience with new toys ))))

**Comment by paulwouters** [comment]
It seems packet offload _should_work on the ConnectX-6, but it seems AnatoliChe's hardware and/or software is not stable.  Nothing libreswan can do or add at this point. I would test placing the cards in another PC for testing using stock fedora kernels
