### ISSUE TITLE
[HELP] libreswan xauth

### ISSUE THREAD

**Issue by jhay06** [libreswan/libreswan#1050]
Hi , i have a problem now , 
below is my configuration 
ipsec.conf
```
conn Forcepoint
        authby=secret
       pfs=no       
        rekey=no
        left=%defaultroute
        leftid=me@InternalDomain
        leftxauthusername=me@InternalDomain
        leftcert=mycertfromnss
        leftsendcert=always
        leftxauthclient=yes
        leftmodecfgclient=yes
        right=XXX.XXX.XXX.XXX
        rightid=%fromcert
        rightxauthserver=yes
        rightmodecfgserver=yes
        xauthby=alwaysok
        fragmentation=yes
        type=tunnel
        ikev2=permit
       ike=3des-sha1;modp1024
        esp=3des-sha1;modp1024
        encapsulation=yes
        ipsec-interface=yes
        remote-peer-type=cisco
        initial-contact=yes
        cisco-unity=yes
        aggrmode=no

conn Site1
   also = Forcepoint
   auto = add
   leftsubnet= YYY.YYY.YYY.0/24
   rightsubnet= YYY.YYY.YYY.0/24


```

when using authby=secret and then i try to restart ipsec 
it restarted successfully but no connection was loaded supposedly conn Site1 should be loaded 
using sudo ipsec auto --up Site1, it replies with no connection named alias Site1

i have to use authby = secret because i have a ipsec.secrets

me@InternalDomain: XAUTH "7s$!zrn1"

but when i used rsasig , and then restart ipsec 
i saw conn Site1 was being loaded upon restart 
then running sudo ipsec auto --up Site1 gives me Xauth challenge , typing it manually doesnt work i dont know why maybe because of some special characters 

so i need to use authby=secret for this to work

can someone point me whats wrong , why changing authby=secret doesnt load my Site1 connection from configuration ? ]

Thanks

**Comment by letoams** [comment]
XAUTH is IKEv1 only, please use ikev2=noSent using a virtual keyboard on a phoneOn Mar 24, 2023, at 09:40, jhay06 ***@***.***> wrote:﻿
btw , i installed all the need certificates via NSS library , .p12 file and the 2 .ca certificate files

**Comment by jhay06** [comment]
im closing it now , i found out what causing the error  . rightxauthserver and leftxauthclient must set to no thanks
