### ISSUE TITLE
default keyingtries=1, not zero

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1061]
It seems IKEv1 defaults keyingtries to 0 aka infinity which is a bit of a disaster when the first response is a reject

**Comment by letoams** [comment]
On Mon, 27 Mar 2023, cagney wrote:

> It seems IKEv1 defaults keyingtries to 0 aka infinity which is a bit of a disaster when the first response is a reject

Why?

If you do a --up, it should keep trying forever. On the responder (eg
with auto=add) , it should reply and delete state.

This is independent of IKE versions. The only difference is with IKEv1
the responder is supposed to also retransmit, but we dont do that
for "first packets" to avoid DDOS attacks.

Paul

**Comment by cagney** [comment]
in 5.0, instead of having keying tries, revival will start with a backoff of 0

**Comment by cagney** [comment]
By default OE only tries one exchange.  Ignoring keyingtries means that can't be tuned.

**Comment by letoams** [comment]
On Mon, 10 Apr 2023, cagney wrote:

> By default OE only tries one exchange. Ignoring keyingtries means that can't be tuned.

I don't think that is an issue.

**Comment by cagney** [comment]
We'll need to reword:
```
-000 "westnet-eastnet-ikev2" #1: starting keying attempt 2 of an unlimited number, but releasing whack
+002 "westnet-eastnet-ikev2" #1: deleting IKE SA but connection is supposed to remain up; schedule CONNECTION_REVIVAL
+002 "westnet-eastnet-ikev2" #1: deleting IKE SA (PARENT_I1) and NOT sending notification
```
adding when the next revival is

**Comment by cagney** [comment]
more todo, this must be broken:
```

	if (c->kind == CK_INSTANCE && c->sa_keying_tries == 0) {
		ldbg(st->st_logger, "limiting instance revival attempts to 2 keyingtries");
		c->sa_keying_tries = 2;
	}
```
