### ISSUE TITLE
How to make VPN route packets through the created tunnel?

### ISSUE THREAD

**Issue by jacusiel** [libreswan/libreswan#107]
Hello I have a VPN setup and working that connect two sites. Hosts behind the VPN server can send packets back and forth through the tunnel, but the VPN server can't. Is this a libreswan configuration issue or a iptables issue?

Thanks for any pointer in the right direction.

**Comment by letoams** [comment]
On Tue, 27 Jun 2017, jacusiel wrote:

> Hello I have a VPN setup and working that connect two sites. Hosts behind the VPN server can send packets back and forth through the tunnel, but
> the VPN server can't. Is this a libreswan configuration issue or a iptables issue?
> 
> Thanks for any pointer in the right direction.

Your gateway uses the "nearest IP" per default, which is likely not part
of your subnet. You can add leftsourceip=<your internal subnet IP> so
a route will be created to the vpn server uses its internal interface
IP to talk to the remote end. That internal IP would presumably be
covered by your leftsubnet= definition.

If your subnet is another hop further behind the gateway, then you
might just need to add a dedicated gw-to-subnet connection to cover it.

Paul

**Comment by jacusiel** [comment]
Thank you Paul. Works as expected!
