### ISSUE TITLE
Question on DNS over TLS or HTTPS

### ISSUE THREAD

**Issue by hwdsl2** [libreswan/libreswan#1076]
Does Libreswan support DNS over TLS (or DNS over HTTPS) for a connected VPN client, when specifying the `modecfgdns` option in `ipsec.conf` to pass DNS server(s) to VPN clients? For example, if `modecfgdns=1.1.1.1`, can VPN clients connect to that DNS server using DNS over TLS/HTTPS?

If this is already supported, does it require `USE_DNSSEC=true` when compiling Libreswan, or is that unrelated?

Context: https://github.com/hwdsl2/docker-ipsec-vpn-server/issues/364

Thanks!

**Comment by letoams** [comment]
On Apr 9, 2023, at 11:32, Lin Song ***@***.***> wrote:
> 
> ﻿
> Does Libreswan support DNS over TLS (or DNS over HTTPS) for a connected VPN client, when specifying the modecfgdns option in ipsec.conf to pass DNS server(s) to VPN clients?
> 
The standard for that is still being developed and has not been implemented yet.

https://datatracker.ietf.org/doc/draft-ietf-ipsecme-add-ike/

> For example, if modecfgdns=1.1.1.1, can VPN clients connect to that DNS server using DNS over TLS/HTTPS?
> 
That depends on the DNS server only. Yes if those DNS servers support it.

> If this is already supported, does it require USE_DNSSEC=true when compiling Libreswan, or is that unrelated?
> 

That is unrelated.

Paul

**Comment by hwdsl2** [comment]
@letoams Thanks for your detailed answers.
