### ISSUE TITLE
Multiple combination of phase2 algorithms don't work without -ikev2

### ISSUE THREAD

**Issue by NagarajKoti** [libreswan/libreswan#1077]
Hi Experts,

   Trying different combination of Phase 2 algorithms on Debian provider(name space) mentioned in the Libreswan manual, getting the below error.

#climconfig ipsec -auto -add -prov test -s 192.168.42.3 -d 172.17.254.57 -a psk -protocol esp -type transport -ike aes_ctr-sha256:dh14 -phase2 3des_cbc+aes_ctr-sha256+sha384-dh15+dh16 -M main
**025 no connection or alias 'lconn-1680284920'
Error: Failed adding Auto key configuration. **

However, when -ikev2 is used in the below command, autokey configuration is added successfully.

# climconfig ipsec -auto -add -prov test -s 192.168.42.3 -d 172.17.254.53 -a psk -protocol esp -type transport -ike aes_ctr-sha256:dh14 -phase2 3des_cbc+aes_ctr-sha256+sha384-dh15+dh16 -ikev2 -M main
Auto key Configuration successfully added.

**Even the manual doesn’t mention about using -ikev2 with multiple combination of phase2 algorithms.
Please let us know what is the correct usage. and the combination of the algorithms**

Thanks
NagarajKoti

**Comment by letoams** [comment]
On Mon, 10 Apr 2023, NagarajKoti wrote:

> Trying different combination of Phase 2 algorithms on Debian provider(name space) mentioned in the Libreswan manual,
> getting the below error.
> 
> #climconfig ipsec -auto -add -prov test -s 192.168.42.3 -d 172.17.254.57 -a psk -protocol esp -type transport -ike
> aes_ctr-sha256:dh14 -phase2 3des_cbc+aes_ctr-sha256+sha384-dh15+dh16 -M main
> **025 no connection or alias 'lconn-1680284920'
> Error: Failed adding Auto key configuration. **

That does not seem to be a libreswan "ipsec auto" command?

I don't know what -auto is (libreswan has "ipsec auto", no dashes). And
I don't know "-prov"  or "-a" etc. It looks like an "ipsec whack"
command but it isn't.

**Comment by cagney** [comment]
libreswan only supports compact proposals such as:
```
3des_cbc+aes_ctr-sha256+sha384-dh15+dh16
```
with IKEv2.   With IKEv1each desired combination needs to be listed explicitly vis:
```
3des_cbc-sha256-dh15,aes_ctr-sha256-dh15,...
```
this is from [ipsec.conf(5)](https://testing.libreswan.org/latest/documentation/ipsec.conf.5.html)

_IKEv2 allows combining elements into a single proposal. These can be specified by using the + symbol. An example is: ike=aes_gcm+chacha20_poly1305;dh14+dh19,aes+3des-sha2+sha1;dh14. Note that AEAD algorithms (aes_gcm, aes_ccm, chacha20_poly1305) and non-AEAD algorithms (aes, 3des) cannot be combined into a single proposal. To support aes and aes_gcm, two proposals separated by a comma must be used._
