### ISSUE TITLE
why does initialize_new_state() re-orient the connection

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1094]
```
	/*
	 * reset our choice of interface
	 *
	 * XXX: why? suspect this has the side effect of restoring /
	 * updating connection's ends?
	 */
	struct connection *c = st->st_connection;
	pexpect(oriented(c));
	iface_endpoint_delref(&c->interface);
	orient(c, st->st_logger);
```

**Comment by cagney** [comment]
In `ikev2-revive-through-nat-01-down` the orient() has the effect of switching the connection's local interface from :500 to :4500:
```
| sending 832 bytes for STATE_V2_PARENT_I0 through eth1 from 192.1.2.23:4500 to 192.1.2.254:6666 using UDP (for #3)
```
vs:
```
| sending 828 bytes for STATE_V2_PARENT_I0 through eth1 from 192.1.2.23:500 to 192.1.2.254:6666 using UDP (for #3)
```
The revival code updates the connection.

**Comment by letoams** [comment]
On Jul 31, 2023, at 19:33, cagney ***@***.***> wrote:﻿
In ikev2-revive-through-nat-01-down the orient() has the effect of switching the connection's local interface from :500 to :4500:If the destination port is not 500, it should have started from 4500 ? Eg a nat encap capable port ?
| sending 832 bytes for STATE_V2_PARENT_I0 through eth1 from 192.1.2.23:4500 to 192.1.2.254:6666 using UDP (for #3)

vs:
| sending 828 bytes for STATE_V2_PARENT_I0 through eth1 from 192.1.2.23:500 to 192.1.2.254:6666 using UDP (for #3)

The revival code updates the connection.

**Comment by cagney** [comment]
> If the destination port is not 500, it should have started from 4500 ? Eg a nat encap capable port ?

Yes.  The orient() is having that effect:

- the connection instance starts out oriented to interface :500; just like its template
- when a packet arrives on :4500, update_ike_endpoints() switches .st_interface to :4500; but leaves the connection's interface alone
- when revival triggers for an instance, update_remote_port() fiddles with .remote.host.port and .remote.host.encap
- in new-state, the orient switches the connection instances interface from :500 to :4500, and then assigns it to .st_interface
- the new exchange then uses :4500

I suspect, like pending, more details should be saved.

(I wonder if there's a bug where a permanent connection is slow or fails to revive because it always starts the exchange with port :500)

**Comment by cagney** [comment]
The call was originally in set_state_ike_endpoints() and pre-dates history.
