### ISSUE TITLE
xmlto Build Errors - Git abd1cdf7eaebb3e02af9892fe76b073df071327c

### ISSUE THREAD

**Issue by reubenfarrelly** [libreswan/libreswan#1106]
Heads up - as of Git head as of now (abd1cdf7eaebb3e02af9892fe76b073df071327c) I'm seeing build failures with man pages.  It looks like these are triggered from some of the recent commits from @bleve ?

This is with xmlto-0.0.28 on Gentoo:

sed -e "/@linux_START@/,/@linux_END@/d" -e "s:@DOCKER_PLUTONOFORK@:--nofork:g" -e "s:@@LOGROTATEDDIR@@::g" -e "s:@INITSYSTEM@:openrc:g" -e "s:@IPSECVERSION@:v4.9-1517-gabd1cdf7ea-HEAD:g" -e "s:@MODPROBEARGS@:--quiet --use-blacklist:g" -e "s:@MODPROBEBIN@:modprobe:g" -e "s:@OSDEP@:linux:g" -e "s:@PYTHON_BINARY@:/usr/bin/python3:g" -e "s:@SD_PLUTO_OPTIONS@::g" -e "s:@SD_RESTART_TYPE@::g" -e "s:@SD_TYPE@:simple:g" -e "s:@SD_WATCHDOGSEC@:0:g" -e "s:@SHELL_BINARY@:/bin/sh:g" -e "s:@USE_DEFAULT_CONNS@::g" -e "s:@HAVE_IPTABLES@:true:g" -e "s:@HAVE_NFTABLES@:false:g"  -e 's:@@LIBEXECDIR@@:/usr/libexec/ipsec:g'  -e 's:@IPSEC_EXECDIR@:/usr/libexec/ipsec:g'  -e 's:@@SBINDIR@@:/usr/sbin:g'  -e 's:@@MANDIR@@:/usr/share/man:'  -e 's:@@SYSCONFDIR@@:/etc:g'  -e 's:@RC_D_DIR@:/etc/rc.d:g'  -e 's:@EXAMPLE_RC_D_DIR@:/usr/share/doc/libreswan/rc.d:g'  -e 's:@INIT_D_DIR@:/etc/init.d:g'  -e 's:@EXAMPLE_INIT_D_DIR@:/usr/share/doc/libreswan/init.d:g'  -e 's:@@RUNDIR@@:/run/pluto:g'  -e 's:@@IPSEC_CONF@@:/etc/ipsec.conf:g'  -e 's:@@IPSEC_SECRETS@@:/etc/ipsec.secrets:g'  -e 's:@@IPSEC_CONFDDIR@@:/etc/ipsec.d:g'  -e 's:@@EXAMPLE_IPSEC_CONFDDIR@@:/usr/share/doc/libreswan/ipsec.d:g'  -e 's:@@EXAMPLE_IPSEC_SYSCONFDIR@@:/usr/share/doc/libreswan:g'  -e 's:@@VARDIR@@:/var:g'  -e 's:@@LOGDIR@@:/var/log:g'  -e 's:@LOGROTATEDDIR@:/etc/logrotate.d:g'  -e 's:@EXAMPLE_LOGROTATEDDIR@:/usr/share/doc/libreswan/logrotate.d:g'  -e 's:@IPSEC_NSSDIR@:/var/lib/ipsec/nss:g'  -e 's:@@NSS_BINDIR@@:/usr/bin:g'  -e 's:@@PAMCONFDIR@@:/etc/pam.d:g'  -e 's:@@EXAMPLEPAMCONFDIR@@:/usr/share/doc/libreswan/pam.d:g' < ipsec.8.xml > ../../OBJ.linux.amd64/programs/ipsec/ipsec.8.tmp.tmp
mv ../../OBJ.linux.amd64/programs/ipsec/ipsec_vfychain.8.tmp.tmp ../../OBJ.linux.amd64/programs/ipsec/ipsec_vfychain.8.tmp
xmlto html-nochunks ../../OBJ.linux.amd64/programs/ipsec/ipsec_add.8.tmp -o ../../OBJ.linux.amd64/html
mv ../../OBJ.linux.amd64/programs/ipsec/ipsec.8.tmp.tmp ../../OBJ.linux.amd64/programs/ipsec/ipsec.8.tmp
xmlto html-nochunks ../../OBJ.linux.amd64/programs/ipsec/ipsec_briefstatus.8.tmp -o ../../OBJ.linux.amd64/html
xmlto: /var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/programs/ipsec/../../OBJ.linux.amd64/programs/ipsec/ipsec_add.8.tmp does not validate (status 3)
xmlto: Fix document syntax or use --skip-validation option
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.4/docbookx.dtd
/var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/programs/ipsec/../../OBJ.linux.amd64/programs/ipsec/ipsec_add.8.tmp:3: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.4/docbookx.dtd"
                   "http://www.oasis-open.org/docbook/xml/4.4/docbookx.dtd">
                                                                            ^
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.4/docbookx.dtd
warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.4/docbookx.dtd"
validity error : Could not load the external subset "http://www.oasis-open.org/docbook/xml/4.4/docbookx.dtd"
Document /var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/programs/ipsec/../../OBJ.linux.amd64/programs/ipsec/ipsec_add.8.tmp does not validate
xmlto: /var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/programs/ipsec/../../OBJ.linux.amd64/programs/ipsec/ipsec_briefstatus.8.tmp does not validate (status 3)
xmlto: Fix document syntax or use --skip-validation option
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.4/docbookx.dtd
/var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/programs/ipsec/../../OBJ.linux.amd64/programs/ipsec/ipsec_briefstatus.8.tmp:3: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.4/docbookx.dtd"
                   "http://www.oasis-open.org/docbook/xml/4.4/docbookx.dtd">
                                                                            ^
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.4/docbookx.dtd
warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.4/docbookx.dtd"
validity error : Could not load the external subset "http://www.oasis-open.org/docbook/xml/4.4/docbookx.dtd"
Document /var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/programs/ipsec/../../OBJ.linux.amd64/programs/ipsec/ipsec_briefstatus.8.tmp does not validate
make[3]: *** [../../mk/manpages.mk:96: ../../OBJ.linux.amd64/html/ipsec_add.8.html] Error 13
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [../../mk/manpages.mk:96: ../../OBJ.linux.amd64/html/ipsec_briefstatus.8.html] Error 13
make[2]: *** [../../mk/targets.mk:84: all] Error 2
make[2]: Leaving directory '/var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/programs/ipsec'
make[1]: *** [../mk/targets.mk:84: recursive-all] Error 2
make[1]: Leaving directory '/var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/programs'
make: *** [/var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/mk/targets.mk:84: recursive-all] Error 2
 * ERROR: net-vpn/libreswan-9999::reub-Local-Overlay failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=net-vpn/libreswan-9999::reub-Local-Overlay'`,
 * the complete build log and the output of `emerge -pqv '=net-vpn/libreswan-9999::reub-Local-Overlay'`.
 * The complete build log is located at '/var/tmp/portage/net-vpn/libreswan-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-vpn/libreswan-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999'
 * S: '/var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999'

>>> Failed to emerge net-vpn/libreswan-9999, Log file:

>>>  '/var/tmp/portage/net-vpn/libreswan-9999/temp/build.log'

 * Messages for package net-vpn/libreswan-9999:

 * ERROR: net-vpn/libreswan-9999::reub-Local-Overlay failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=net-vpn/libreswan-9999::reub-Local-Overlay'`,
 * the complete build log and the output of `emerge -pqv '=net-vpn/libreswan-9999::reub-Local-Overlay'`.
 * The complete build log is located at '/var/tmp/portage/net-vpn/libreswan-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-vpn/libreswan-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999'
 * S: '/var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999'
tornado ~ #

**Comment by bleve** [comment]
Are you missing version 4.4 of docbookx.dtd from your install?

**Comment by bleve** [comment]
https://packages.gentoo.org/packages/app-text/docbook-xml-dtd

According this version 4.4 should be supported.

**Comment by bleve** [comment]
Checked all old distros and found out 4.5 is already supported on rhel7 and debian so switched from V4.4 to V4.5 on git main.

Rest of the man pages will get upgrade before next major release so intention is to have all man pages in same newer docbook xml version.

**Comment by bleve** [comment]
All man pages have now been updated to docbook xml 4.5.
