### ISSUE TITLE
[question] Broadcast / Chromecast

### ISSUE THREAD

**Issue by Killertjuh** [libreswan/libreswan#112]
Is there any way to use this? I cannot find anything in the manual ?

**Comment by letoams** [comment]
I don't understand the question.

How does broadcast / chromecast related to libreswan/ipsec ?

**Comment by Killertjuh** [comment]
My mistake its use mdns en traying to use this trough ipsec tunnel

**Comment by letoams** [comment]
On Fri, 28 Jul 2017, Bram wrote:

> Subject: Re: [libreswan/libreswan] [question] Broadcast / Chromecast (#112)
> 
> My mistake its use mdns en traying to use this trough ipsec tunnel

Oh. Of course, mdns is not supposed to get "outside the local network" :P

Currently, you cannot use libreswan for tunneling multicast traffic
natively, but perhaps you can get something working using virtual
ethernet?

https://libreswan.org/wiki/EoIP_shared_ethernet_LAN_using_IPsec

Paul

**Comment by Killertjuh** [comment]
Ah thx this is what i need. Gonna try to make it work on debian :)

**Comment by mav2287** [comment]
Did you ever get this working?
