### ISSUE TITLE
revival when first child rejected

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1123]
Consider an initial responder:

- receives and responds to IKE_SA_INIT request
- receives and responds to IKE_AUTH with child

but then the initiator (seemingly) rejects the child response so this end:

- receives and responds to CHILD_SA_DELETE (first child)

but the connection is +UP, so this end reacts by:

- sending CREATE_CHILD_SA using the still established IKE SA

**is this reasonable?**

Anyway, it turns out that the initiator was tearing down the IKE family as the next thing that happens is:

- receives CHILD_SA_DELETE for IKE SA

**Comment by letoams** [comment]
On Fri, 5 May 2023, cagney wrote:

> Consider an initial responder:
>
>  *  receives and responds to IKE_SA_INIT request
>  *  receives and responds to IKE_AUTH with child
> 
> but then the initiator (seemingly) rejects the child response so this end:
>
>  *  receives and responds to CHILD_SA_DELETE (first child)
> 
> but the connection is +UP, so this end reacts by:
>
>  *  sending CREATE_CHILD_SA using the still established IKE SA
> 
> is this reasonable?

It is reasonably if unfortunate. It could wait 0.5s in case an IKE
delete follow up happens? but really that should not be happning.

> Anyway, it turns out that the initiator was tearing down the IKE family as the next thing that happens is:
>
>  *  receives CHILD_SA_DELETE for IKE SA

Why did the initiator do that if the only bad thing was the Child SA ?

Paul

**Comment by cagney** [comment]
reviving connection is reasinable; peer probably broken
