### ISSUE TITLE
expire (byte count exceeded) doesn't know about IPcomp

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1130]
I triggers:
```
May  8 19:54:05.721213: ABORT: ASSERTION FAILED: switch (ue->state.id.proto) case 108 (0x6c) unexpected (netlink_kernel_sa_expire() +2011 /programs/pluto/kernel_xfrm.c)
```

**Comment by j4Hu** [comment]
i haved this issue, and pluto/librewsan died, with debug message:

ABORT: ASSERTION FAILED: switch (ue->state.id.proto) case 108 (0x6c) unexpected (netlink_kernel_sa_expire() +2011 /programs/pluto/kernel_xfrm.c) 

i found solution, in mailing list
https://www.mail-archive.com/swan@lists.libreswan.org/msg03600.html 

disable compression, helped, pluto/libreswan and tunnel is working
