### ISSUE TITLE
How do I limit one connection per user ?

### ISSUE THREAD

**Issue by jibeex** [libreswan/libreswan#114]
I would like to avoid multiple concurrent connection with the same credential.

**Comment by letoams** [comment]
That is the default already. Multiple connections from the same phase1 ID replaces older connections from the same.

If you are using XAUTH user/passwords, then from the IKE/IPsec point of view, all users have the same phase1 credentials, so we cannot replace them.

You could use pam module instead and keep track of those users yourself and deny them via the pam module if you think they are still online.

**Comment by jibeex** [comment]
I am not sure that I understand that completely. Is there some example/simpler way to limit one connection per user ?

**Comment by letoams** [comment]
On Thu, 10 Aug 2017, Jianbin LIN wrote:

> I am not sure that I understand that completely. Is there some example/simpler way to limit one connection per user ?

Use X509 certificates with authby=rsasig and not PSK with authby=secret

Paul

**Comment by letoams** [comment]
since this is not really a bug, I'm closing this item. Please discuss this further on the swan@lists.libreswan.org mailing list if you have any more questions

**Comment by jibeex** [comment]
OK，thank you.
