### ISSUE TITLE
IKEv2 null encryption not working

### ISSUE THREAD

**Issue by Thibault-Van-Win** [libreswan/libreswan#1140]
For an experiment, I want to disable IKE encryption. The documentation specifies that this should be supported as it stated te following:  "_Null encryption is available, and should only be used for testing or benchmarking purposes_"

After adding `ike=null` to the configuration, I get the following error:

_failed to add connection: IKE encryption algorithm 'null' is not supported_

Is null encryption still supported or is there a different wat to achieve this?

Thanks in advance!

**Comment by cagney** [comment]
Interesting.

I don't see anything in the testsuite or code base for this so this must predate the switch to NSS.

You could play with https://github.com/libreswan/libreswan/compare/main...cagney:libreswan:crypto/null

**Comment by letoams** [comment]
It should never be allowed without an —impair Sent using a virtual keyboard on a phoneOn May 18, 2023, at 10:54, cagney ***@***.***> wrote:﻿
Interesting.
I don't see anything in the testsuite or code base for this so this must predate the switch to NSS.
You could play with main...cagney:libreswan:crypto/null

**Comment by Thibault-Van-Win** [comment]
> You could play with [main...cagney:libreswan:crypto/null](https://github.com/libreswan/libreswan/compare/main...cagney:libreswan:crypto/null)

Thanks! This did the trick after removing the LDBGF due to a compile error

**Comment by cagney** [comment]
added to mainline, requires --impair allow-null-none
