### ISSUE TITLE
return a shunk_t from get_ppk_by_id()?

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1150]
`get_ppk_by_id()` returns `const chunk_t *`, i.e., a pointer to a chunk in another structure.
The const tries to convey that the chunk_t is untouchable but that doesn't stop the chunk contents being scribbled on.

**Comment by vukasink** [comment]
If I remember correctly, the `get_ppk_by_id()` returned `const chunk_t *` because a similar, already existing function `get_connection_psk()` was doing the same.

I guess changing then one function would mean the others should be changed as well.

**Comment by vukasink** [comment]
Changing `ppk_id` variables throughout (e.g. in keys.c and ikev2_ike_auth.c)  to `shunk_t` seems like a better first step.
