### ISSUE TITLE
make /usr/sbin/ipsec function with nftables  (deprecate iptables)

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#116]
`/usr/sbin/ipsec` (and possibly other parts of libreswan) appears to depend on iptables.

not all linux systems have iptables installed.  netfilter upstream is [encouraging people to move from iptables to nftables](http://netfilter.org/projects/nftables/index.html) ([see also](https://wiki.nftables.org)).  it'd be great to have libreswan functional on systems that have only `nft` and no `iptables`.

**Comment by dkg** [comment]
any plans for this?  there is [a silly bug in the debian iptables package](https://bugs.debian.org/914074) that make it harder to upgrade libreswan in debian unstable, because it explicitly depends on iptables. it'd be great to make that dependency disaapear if possible.

**Comment by letoams** [comment]
I haven’t looked into the availability of nftables in most distros (esp. the embedded ones). If we know that availability, we can make a decision on whether to support both with a build option, or to just drop iptables support.

There is also the issue of admins still using iptables even if nftables is available. I would need to better understand the interaction here if the two (system and libreswan) don’t match.

Paul

**Comment by theBlbDan** [comment]
More than a year later and libreswan still **depends** on iptables.  Maybe not all admins have made the move, but continuing with libreswan forces admins to not be allowed to make that move.

The request to **make /usr/sbin/ipsec function with nftables** means, can we have support for either built in so that after setting up nftables, the install doesn't clobber us with
```
Setting up iptables (1.8.2-4) ...
update-alternatives: using /usr/sbin/iptables-legacy to provide /usr/sbin/iptables (iptables) in auto mode
update-alternatives: using /usr/sbin/ip6tables-legacy to provide /usr/sbin/ip6tables (ip6tables) in auto mode
update-alternatives: using /usr/sbin/iptables-nft to provide /usr/sbin/iptables (iptables) in auto mode
update-alternatives: using /usr/sbin/ip6tables-nft to provide /usr/sbin/ip6tables (ip6tables) in auto mode
update-alternatives: using /usr/sbin/arptables-nft to provide /usr/sbin/arptables (arptables) in auto mode
update-alternatives: using /usr/sbin/ebtables-nft to provide /usr/sbin/ebtables (ebtables) in auto mode
```

It's forcing us to live in one camp or the other.

**Comment by letoams** [comment]
On Fri, 24 Jan 2020, theBlbDan wrote:

> More than a year later and libreswan still depends on iptables. Maybe not all admins have made the move, but continuing with libreswan
> forces admins to not be allowed to make that move.
> 
> The request to make /usr/sbin/ipsec function with nftables means, can we have support for either built in so that after setting up
> nftables, the install doesn't clobber us with

It would be helpful if we knew how compatible the commands are and
whether we can have a USE_LINUX_FWCMD=iptables|ebtables method that
could easilly sed the _updown.netkey.in to generate an _updown.netkey
that calls either iptables or ebtables.

Patches would be welcome and accepted :)

Paul

**Comment by cagney** [comment]
The following invoke iptables:
```
$ ./mk/find.sh iptables | grep .in: | cut -d: -f1 | sort -u
./programs/barf/barf.in
./programs/ipsec/ipsec.in
./programs/look/look.in
./programs/_updown.xfrm/_updown.xfrm.in
./programs/verify/verify.in

```

**Comment by ueno** [comment]
In v4.8, it looks like all hose scripts support nftables. Can this issue be considered as complete, or is there anything else to be done?

**Comment by antonyantony** [comment]
On Thu, Oct 06, 2022 at 04:10:23AM -0700, Daiki Ueno wrote:
> In v4.8, it looks like all hose scripts support nftables. Can this issue be considered as complete, or is there anything else to be done?

nftables support is not complete yet! I added the basic structures to 
nftables. It is missing letf/rightcat=yes and per connection nflog.

I hope to complete it soon. If you don't need those use cases you could build
without nftables and ipables. Now the build should support disabling both.

-antony

**Comment by cagney** [comment]
fixed by @antonyantony
