### ISSUE TITLE
should terminate aka down always down the IKE SA?

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1163]
Say there are two connections sharing the same IKE SA, for instance:
```
ipsec up conn-ike+child
ipsec up conn-child
```
first establishes `conn-ike+child` creating IKE and Child SAs, and then establishes `conn-child` creating a second Child SA that uses `conn-ike+child` as the IKE SA.

next the `conn-ike+child` is terminated vis:
```
ipsec down conn-ike+child
```

Currently this terminates the Child SA as the IKE SA is a `shared_phase1_connection(c)`.  Should it instead terminate both IKE and Child SAs at which point `conn-child` will revive itself creating its own IKE SA.

**Comment by cagney** [comment]
Here's how this comes up:
```

			terminate_connections_by_name(m->name, /*quiet?*/true, logger);
			whack_delete_connections(m->name, !m->whack_add, logger);
```
Because `terminate_connections_by_name()` doesn't terminate all SAs `whack_delete_connections()` also needs to check for and terminate SAs - the first step could be skipped.

**Comment by letoams** [comment]
On Thu, 8 Jun 2023, cagney wrote:

> Here's how this comes up:
>
> 			terminate_connections_by_name(m->name, /*quiet?*/true, logger);
> 			whack_delete_connections(m->name, !m->whack_add, logger);
> 
> Because terminate_connections_by_name() doesn't terminate all SAs whack_delete_connections()
> also needs to check for and terminate SAs - the first step could be skipped.

Our current policy is, "if the IKE SA is not shared, terminating a child
SA that would leave the IKE SA childless, should also terminate the IKE
SA". Ideally though, we would do that termination early, so we can just
call for an IKE delete to get rid of both IKE and Child, instead of
sending two seperate delete packets.

**Comment by cagney** [comment]
If
```
ipsec down conn-ike+child
```
doesn't terminate the IKE SA, what command should be used?

**Comment by letoams** [comment]
On Thu, 8 Jun 2023, cagney wrote:

> If
> 
> ipsec down conn-ike+child
> 
> doesn't terminate the IKE SA, what command should be used?

We only really give admins access to "connections" to be added, upped,
downed, etc. They shouldn't even need to know about IKE states.

I suspect: ipsec replace conn-ike+child would do it though, as it would
cause a delete + add operation. But that second connection's child SA
would likely be collateral damage.

**Comment by cagney** [comment]
> We only really give admins access to "connections" to be added, upped, downed, etc. They shouldn't even need to know about IKE states.

but they do need to know about authentication which is handled by the IKE SA.  For instance, how to force re-auth.

> I suspect: ipsec replace conn-ike+child would do it though, as it would cause a delete + add operation. But that second connection's child SA would likely be collateral damage.

so `ipsec delete conn-ike+child` would result in `conn-child` being re-established
