### ISSUE TITLE
accept, or even prefer, keyexchange=ikev1|ikev2 over ikev2={no,yes}

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1168]

**Comment by cagney** [comment]
does ikev2=no mean IKEv1 or IKEv3?

**Comment by letoams** [comment]
On Jun 14, 2023, at 13:20, cagney ***@***.***> wrote:﻿
does ikev2=no mean IKEv1 or IKEv3?Or worse, what if we end up with IKEv2.1I agree we should allow and start using keyexchange= but we will need to carry IKEv2= for a while (years)

**Comment by cagney** [comment]
Bizarre,
We've already got a `keyexchange` keyword.  It pre-dates history.  It accepts but ignores keyexchange=ike.
