### ISSUE TITLE
Both ikev1 and ikev2, if different DH group is mentioned for each proposal, then it fails to load the config to Pluto Libreswan 4.3

### ISSUE THREAD

**Issue by NagarajKoti** [libreswan/libreswan#1173]
Hi Experts,

  we verified in the Libreswan  4.3 that the multiple proposal for ikev1 and ikev2 is working fine in the below format. i.e if DH group is same for all proposals 
3des_cbc-sha256-**dh15**,aes_ctr-sha256-**dh15**,...

But for both ikev1 and ikev2, if different DH group is mentioned for each proposal, then it fails to load the config to Pluto.
If the DH group is same for all proposals, then it loads the config to the Pluto. 

Can you please confirm how do we mention the Different DH groups in the proposals or different DH groups are not supported in the ikev1 and ikev2

Details of the error are different for ikev1 and ikev2. 
Config: IKEV2
conn lconn-12
        left=30.30.5.4
        right=30.30.5.8
        leftprotoport=tcp/3337
        rightprotoport=tcp/4450
[error.txt.txt](https://github.com/libreswan/libreswan/files/11797281/error.txt.txt)

        auto=ondemand
        type=transport
        authby=secret
        ike=3des-md5;dh16
        phase2=esp
        phase2alg=3des_cbc-sha256**-dh15**,aes_ctr-sha256-**dh19**
        ikev2=yes
        aggressive=no
NCLIM005(%MAINT):# climconfig ipsec -auto -add -prov ztc1 -s 30.30.5.4 -d 30.30.5.8 -a psk -protocol esp -sport 3337 -dport 4450 -u tcp -type transport -ike 3des-md5:dh16 -phase2 3des_cbc-sha256-dh15,aes_ctr-sha256-dh19 -ikev2 -M main
025 no connection or alias 'lconn-12'
Error: Failed adding Auto key configuration.
NCLIM005(%MAINT):~# prov ZTC1 ipsec auto --ctlsocket /etc/pluto/rundir/pluto.ctl --ondemand lconn-12
036 "lconn-12": failed to add connection: more than one IKEv2 ESP DH algorithm (MODP3072, DH19) requires unimplemented CHILD_SA INVALID_KE
025 no connection or alias 'lconn-12'

Config: IKEV2
conn lconn-14
        left=30.30.5.4
        right=30.30.5.8
        leftprotoport=tcp/3337
        rightprotoport=tcp/4452
        auto=ondemand
        type=transport
        authby=secret
        ike=3des-md5;dh16
        phase2=esp
        phase2alg=3des_cbc-sha256-**dh15**,aes_ctr-sha256-**dh14**
        ikev2=no
        aggressive=no
NCLIM005(%MAINT):# climconfig ipsec -auto -add -prov ztc1 -s 30.30.5.4 -d 30.30.5.8 -a psk -protocol esp -sport 3337 -dport 4452 -u tcp -type transport -ike 3des-md5:dh16 -phase2 3des_cbc-sha256-dh15,aes_ctr-sha256-dh14 -M main
025 no connection or alias 'lconn-14'
Error: Failed adding Auto key configuration.
NCLIM005(%MAINT):~# prov ZTC1 ipsec auto --ctlsocket /etc/pluto/rundir/pluto.ctl --ondemand lconn-14
036 "lconn-14": failed to add connection: more than one IKEv1 ESP DH algorithm (MODP3072, MODP2048) is not allowed in quick mode
025 no connection or alias 'lconn-14'

Thanks 
Koti

**Comment by letoams** [comment]
On Tue, 20 Jun 2023, cagney wrote:

> It is better to not specify a DH group. Libreswan will then use the DH group negotiated when establishing the IKE SA.

Yes. In fact, it makes no sense to have a different DH group for IKE and
Child SAs because the first Child SA is protected by the IKE DH group.

>  *  when the Child SA is established during the initial exchange it uses keying material created by the initial IKE SA exchange
>  *  when the Child SA is rekeyed it will use the negotiated IKE DH group to generate new keying material

I thought we were talking about multiple DH for IKE, not Child.

For IKEv2, in a way I think we should remove the option to set the DH at all.

Paul

**Comment by NagarajKoti** [comment]
Thanks Paul and Cagney,
Based on your comments specifying the same or different dh groups in the proposals for ikev1 and ikev2 will not make any sense, if i am wrong please correct me.
When we specify the same DH group as mentioned below in the proposals for ikev1 and ikev2  its works fine it should have through the same error like when we specify the different DH group.
**3des_cbc-sha256-dh15,aes_ctr-sha256-dh15,..**
please let me know why it is considered same dh groups and why it is not considered different dh groups.
Thanks
Koti

**Comment by cagney** [comment]
> Thanks Paul and Cagney,
> Based on your comments specifying the same or different dh groups in the proposals for ikev1 and ikev2 will not make any sense, if i am wrong please correct me.

Yes

(the RFC allows it but it doesn't make sense).

> When we specify the same DH group as mentioned below in the proposals for ikev1 and ikev2 its works fine it should have through the same error like when we specify the different DH group.
> **3des_cbc-sha256-dh15,aes_ctr-sha256-dh15,..**

That is a good question.  Should:
```
pfs=yes
ike=...dh16
esp=...dh15
```
attract a warning.

> please let me know why it is considered same dh groups and why it is not considered different dh groups.
> Thanks
> Koti

`3des_cbc-sha256-dh15` for instance is misleading:

- step 1: use dh15 to establish a shared secret and from that generate keys
- step 2: an IPsec tunnel is established using 3des_cbc-sha256 and keys generated in the first step

hence `aes_ctr-sha256-dh15` and `3des_cbc-sha256-dh15` the same DH (their step 1 is identical)
