### ISSUE TITLE
please remove debian/ directory from upstream sources

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#118]
Having the `debian/` directory in the upstream sources makes it more difficult for me to package libreswan for debian while staying close to the upstream development.  In particular, every time i go to merge a new release, there are edits in the upstream `debian/` directory, which end up conflicting with the git branch i've got that has packaging work for debian proper. I'd prefer that `debian/` be removed from the upstream sources to avoid these conflicts.

packaging for other distros seems to be quarantined under `packaging/` -- if you don't want to remove it, maybe you could move it under `packaging/` ?

**Comment by antonyantony** [comment]
moved to packaging/  in 3.22
