### ISSUE TITLE
«ipsec replace» and «ipsec add» are equivalent?

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1180]
«ipsec replace» runs:
```
cmd="--delete"
    ${dry_run} "${IPSEC_EXECDIR}/whack" --ctlsocket "${CTLSOCKET}" --name ${conn_name} ${cmd}
    ${dry_run} "${IPSEC_EXECDIR}/addconn" --config "${IPSEC_CONF}" --ctlsocket "${CTLSOCKET}" ${verbose} ${conn_name}
```
while «ipsec add» runs just:
```
    ${dry_run} "${IPSEC_EXECDIR}/addconn" --config "${IPSEC_CONF}" --ctlsocket "${CTLSOCKET}" ${verbose} ${conn_name}
```
the thing is that addconn always does an add/delete anyway.  The differences are:

- replace will issue an error when connection isn't present, but add will be silent but deadly

Where things diverge is with «whack ....add...connection...» which only adds (if the connection is already present it gets an error)

**Comment by bleve** [comment]
Reason for replace is use of subnets= - when replace was added, pluto couldn't handle case where number of subnets of existing tunnel got reduced. So leftsubnets=10.0.0.0/24,10.3.0.0/24,10.6.0.0/24 -> leftsubnets=10.0.0.0/24,10.3.0.0/24 was not successfull with just running add or start.

This might be fixed already now.

**Comment by cagney** [comment]
Weird:
82cef84694c959cd300aa9cd34079038253c74ac added replace in  2019-04-01
d56622eb3f71d3446e381774ef733a4a096c7904 made add also delete 2006-03-30

**Comment by bleve** [comment]
https://github.com/libreswan/libreswan/commit/d56622eb3f71d3446e381774ef733a4a096c7904 did not work with subnetS

**Comment by bleve** [comment]
Just verified. ipsec add conn still doesn't delete extra connection when number of subnets is reduced. Only ipsec replace conn removes the extra connection. This causes even more problems if you remove network in the middle of the list because then you have duplicate connection with same subnet.

**Comment by cagney** [comment]
ah, subnet**S**
yea, addconn would be trying to delete subnet/0x1 ... when it should be first deleting anything with the alias subnet

**Comment by cagney** [comment]
Ok trying <<ipsec add>> as an alias for <<ipsec replace>>

**Comment by cagney** [comment]
It also ties into #1111
Tests expect `ipsec addconn ...` to, like `ipsec add`, delete any existing connection (ignoring the subnets= bug)
