### ISSUE TITLE
does "ipsec unroute conn" delete the IKE SA

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1196]

**Comment by letoams** [comment]
On Mon, 17 Jul 2023, cagney wrote:

> Subject: [libreswan/libreswan] does "ipsec unroute conn" delete the IKE SA

unroute is an operation on the IPsec SA, not IKE SA. So I would say "no" ?

**Comment by cagney** [comment]
> unroute is an operation on the IPsec SA, not IKE SA. So I would say "no" ?

seems reasonable; leaving behaviour alone
