### ISSUE TITLE
assertion failed with 3.21

### ISSUE THREAD

**Issue by abique** [libreswan/libreswan#120]
Aug 14 06:46:59 knot pluto[3888]: NSS DB directory: sql:/etc/ipsec.d
Aug 14 06:46:59 knot pluto[3888]: Initializing NSS
Aug 14 06:46:59 knot pluto[3888]: Opening NSS database "sql:/etc/ipsec.d" read-only
Aug 14 06:46:59 knot pluto[3888]: NSS initialized
Aug 14 06:46:59 knot pluto[3888]: NSS crypto library initialized
Aug 14 06:46:59 knot pluto[3888]: FIPS HMAC integrity support [disabled]
Aug 14 06:46:59 knot pluto[3888]: libcap-ng support [enabled]
Aug 14 06:46:59 knot pluto[3888]: Linux audit support [disabled]
Aug 14 06:46:59 knot pluto[3888]: Starting Pluto (Libreswan Version 3.21 XFRM(netkey) KLIPS FORK PTHREAD_SETSCHEDPRIO NSS DNSSEC SYSTEMD_WATCHDOG LIBCAP_NG XAUTH_PAM NETWORKMANAGER CURL(non-NSS)) pid:3888
Aug 14 06:46:59 knot pluto[3888]: core dump dir: /var/run/pluto/
Aug 14 06:46:59 knot pluto[3888]: secrets file: /etc/ipsec.secrets
Aug 14 06:46:59 knot pluto[3888]: leak-detective enabled
Aug 14 06:46:59 knot pluto[3888]: NSS crypto [enabled]
Aug 14 06:46:59 knot pluto[3888]: XAUTH PAM support [enabled]
Aug 14 06:46:59 knot pluto[3888]: NAT-Traversal support  [enabled]
Aug 14 06:46:59 knot pluto[3888]: Initializing libevent in pthreads mode: headers: 2.1.8-stable (2010800); library: 2.1.8-stable (2010800)
Aug 14 06:46:59 knot pluto[3888]: ABORT: ASSERTION FAILED: algorithm '???' fails: alg->name != NULL (in check_algorithm_table() at ike_alg.c:801)
Aug 14 06:46:59 knot pluto[3888]: ABORT: ASSERTION FAILED: algorithm '???' fails: alg->name != NULL (in check_algorithm_table() at ike_alg.c:801)
Aug 14 06:46:59 knot systemd[1]: Started Process Core Dump (PID 3889/UID 0).
Aug 14 06:47:00 knot systemd[1]: ipsec.service: Main process exited, code=dumped, status=6/ABRT
Aug 14 06:47:00 knot systemd[1]: Failed to start Internet Key Exchange (IKE) Protocol Daemon for IPsec.
Aug 14 06:47:00 knot systemd[1]: ipsec.service: Unit entered failed state.
Aug 14 06:47:00 knot systemd[1]: ipsec.service: Failed with result 'core-dump'.
Aug 14 06:47:00 knot systemd-coredump[3890]: Process 3888 (pluto) of user 0 dumped core.
                                             
                                             Stack trace of thread 3888:
                                             #0  0x00007ff472d9b8c0 raise (libc.so.6)
                                             #1  0x00007ff472d9cf72 abort (libc.so.6)
                                             #2  0x000000caae5c4bd9 n/a (pluto)
                                             #3  0x000000caae54ee3d n/a (pluto)
                                             #4  0x000000caae55cf29 n/a (pluto)
                                             #5  0x000000caae5330ea n/a (pluto)
                                             #6  0x00007ff472d884ca __libc_start_main (libc.so.6)
                                             #7  0x000000caae534aba n/a (pluto)
Aug 14 06:47:00 knot systemd[1]: ipsec.service: Service hold-off time over, scheduling restart.
Aug 14 06:47:00 knot systemd[1]: Stopped Internet Key Exchange (IKE) Protocol Daemon for IPsec.
Aug 14 06:47:00 knot systemd[1]: ipsec.service: Start request repeated too quickly.
Aug 14 06:47:00 knot systemd[1]: Failed to start Internet Key Exchange (IKE) Protocol Daemon for IPsec.
Aug 14 06:47:00 knot systemd[1]: ipsec.service: Unit entered failed state.
Aug 14 06:47:00 knot systemd[1]: ipsec.service: Failed with result 'core-dump'.

**Comment by letoams** [comment]
On Mon, 14 Aug 2017, Alexandre Bique wrote:

> Subject: [libreswan/libreswan] assertion failed with 3.21 (#120)

> Aug 14 06:46:59 knot pluto[3888]: ABORT: ASSERTION FAILED: algorithm '???' fails: alg->name != NULL (in check_algorithm_table() at
> ike_alg.c:801)
> Aug 14 06:46:59 knot pluto[3888]: ABORT: ASSERTION FAILED: algorithm '???' fails: alg->name != NULL (in check_algorithm_table() at
> ike_alg.c:801)

Do you have some more information about compile options you used? Can
you also provide a gdb backtrace or more information about which
algorithm this error came from?

>
>                                          Stack trace of thread 3888:
>                                          #0  0x00007ff472d9b8c0 raise (libc.so.6)
>                                          #1  0x00007ff472d9cf72 abort (libc.so.6)
>                                          #2  0x000000caae5c4bd9 n/a (pluto)
>                                          #3  0x000000caae54ee3d n/a (pluto)
>                                          #4  0x000000caae55cf29 n/a (pluto)
>                                          #5  0x000000caae5330ea n/a (pluto)
>                                          #6  0x00007ff472d884ca __libc_start_main (libc.so.6)
>                                          #7  0x000000caae534aba n/a (pluto)

This trace is lacking symbols so we cannot tell anything from it.

Paul

**Comment by letoams** [comment]
not enough information to do anything.
