### ISSUE TITLE
PREFIX=/opt/libreswan option does not work

### ISSUE THREAD

**Issue by pestryy** [libreswan/libreswan#1200]
I run :
sudo make programs PREFIX=/opt/libreswan
then:
sudo make install
The /opt/libreswan directory exists and has write permissions.
but the installation is done in the default directory
Operating system ubuntu 20.04
I am trying to install libreswan version 4.11
There are no errors during the start of compilation, during which I see entries like:
cc -pthread -std=gnu99 -g -Wno-error=unused-result -Wall -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wmissing-declarations. Wredundant-decls -Wnested-externs -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-all -fno-strict-aliasing -fPIE -DPIE -DNSS_IPSEC_PROFILE - DUSE_IKEv1 -DKERNEL_XFRM -DUSE_XFRM_INTERFACE -DXFRM_LIFETIME_DEFAULT=30 -DLIBCURL -DUSE_SYSTEMD_WATCHDOG -DHAVE_NM -DUSE_PAM_AUTH -DUSE_3DES - DUSE_AES -DUSE_CAMELLIA -DUSE_CHACHA -DUSE_MD5 -DUSE_SHA1 -DUSE_SHA2 -DUSE_PRF_AES_XCBC -DDEFAULT_RUNDIR=\"/run/pluto\" -DIPSEC_CONF=\"/etc/ipsec. conf\" -DIPSEC_CONFDDIR=\"/etc/ipsec. d\" -DIPSEC_NSSDIR=\"/var/lib/ipsec/nss\" -DIPSEC_CONFDIR=\"/etc\" -DIPSEC_EXECDIR=\"/opt/libreswan/libexec/ipsec\" -DIPSEC_SBINDIR=\"/opt/libreswan/libexec/ipsec\ DIPSEC_SBINDIR=\"/opt/libreswan/sbin\" -DIPSEC_VARDIR=\"/var\" -DPOLICYGROUPSDIR=\"/etc/ipsec. d/policies\" -DIPSEC_SECRETS_FILE=\"/etc/ipsec.secrets\" -DFORCE_PR_ASSERT -DHAVE_IPTABLES -DUSE_FORK=0 -DUSE_VFORK=0 -DUSE_DAEMON=0 -DUSE_PTHREAD_SETSCHEDPRIO=1 -DGCC_LINT -DHAVE_LIBCAP_NG \.

**Comment by bleve** [comment]
Note: you need to give same options for make install.

**Comment by bleve** [comment]
sudo make PREFIX=/opt/libreswan install

**Comment by pestryy** [comment]
Ok, thnx! tomorrow check it.

**Comment by pestryy** [comment]
> 

And, this:
sudo make PREFIX=/opt/libreswan programs correct, or:
sudo make programs PREFIX=/opt/libreswan
?

**Comment by cagney** [comment]
> sudo make PREFIX=/opt/libreswan programs correct, or:
> sudo make programs PREFIX=/opt/libreswan

I would suggest:
```
make PREFIX=...
sudo make install PREFIX=...
```
so that everything, including documentation, is built unprivileged.

(to answer your specific question, the order doesn't matter)

**Comment by pestryy** [comment]
> 

Ok thnx, tomorrow check!
