### ISSUE TITLE
«ipsec whack add» does not default ESN

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1212]
for instance, in `addconn-08-ordering`:
```
 ipsec whack --name order-test --tunnel --encrypt --ipv4 --tunnelipv6  --host 1.2.3.4 --id foo --client fe80::1/128 --to --host 2.3.4.5 --id bar --client fe80::2/128
002 "order-test": added IKEv2 connection
west #
 ipsec whack --connectionstatus --name order-test
...
000 "order-test":   policy: IKEv2+RSASIG+ECDSA+RSASIG_v1_5+ENCRYPT+TUNNEL;
...
```
presumably it should be adding ESN_{NO,YES} unless somehow impaired.

The RFC says that ESN is manditory for ESP/AH so I wonder what the above sends across the wire.

**Comment by letoams** [comment]
On Mon, 31 Jul 2023, cagney wrote:

>  ipsec whack --name order-test --tunnel --encrypt --ipv4 --tunnelipv6  --host 1.2.3.4 --id foo --client fe80::1/128 --to --host 2.3.
> 4.5 --id bar --client fe80::2/128
> 002 "order-test": added IKEv2 connection
> west #
>  ipsec whack --connectionstatus --name order-test
> ...
> 000 "order-test":   policy: IKEv2+RSASIG+ECDSA+RSASIG_v1_5+ENCRYPT+TUNNEL;
> ...
> 
> presumably it should be adding ESN_{NO,YES} unless somehow impaired.

I thought NO and YES when added both requires support on the other end.
So for interop with older versions of ourselves, not sending ANY ESN_
is the default. At least as IKEv2 proposal elements.

> The RFC says that ESN is manditory for ESP/AH so I wonder what the above sends across the wire.

The RFC presumbly says ESN in mandatory to support in ESPv4, not mandatory to
use though.

Paul

**Comment by cagney** [comment]
whack and addconn now behave the same
