### ISSUE TITLE
deleting a cuckoo connection

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1215]
What happens with:

- connection "ike" establishes
- connection "cuckoo" establishes using connection "ike"'s IKE SA
- `ipsec delete cuckoo`

I suspect connection "ike"s IKE SA gets deleted when only connection "cuckoo" needs to be.

**Comment by letoams** [comment]
On Aug 1, 2023, at 14:39, cagney ***@***.***> wrote:﻿
What happens with:

connection "ike" establishes
connection "cuckoo" establishes using connection "ike"'s IKE SA
ipsec delete cuckoo

I suspect connection "ike"s IKE SA gets deleted when only connection "cuckoo" needs to be.I’m pretty sure it doesn’t and we have testcases for it (shared-ike or something )

**Comment by cagney** [comment]
> I’m pretty sure it doesn’t and we have testcases for it (shared-ike or something )

```
ipsec delete cuckoo
```
and
```
ipsec deletestate '#3'
```
are different beasts (the latter triggers a proper exchange, the former takes shortcuts)

**Comment by cagney** [comment]
have test; doesn't end well
