### ISSUE TITLE
ipsec whack --listen fails for IPv6 address

### ISSUE THREAD

**Issue by NagarajKoti** [libreswan/libreswan#1222]
Hi Experts,

   Trying to configure IPv6 address to one of the N/W interface and able to see the the IPv6 address configured mentioned in the below commands. after configuring the IPv6 address followed by ipsec whack command fails, this is not the case for IPv4 address. Can you please confirm why whack command is failing for ipv6 address once we delete and add the ipv6 address. 

# ip addr del 2022:172:17:254::62 dev eth3
# ip a s eth3
6: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether b4:7a:f1:88:79:48 brd ff:ff:ff:ff:ff:ff
    inet 13.13.13.1/16 brd 13.13.255.255 scope global eth3
       valid_lft forever preferred_lft forever
    **inet6 fe80::b67a:f1ff:fe88:7948/64 scope link**
       valid_lft forever preferred_lft forever
# ip addr add 2022:172:17:254::62 dev eth3
**# ipsec whack --listen --rundir /etc/pluto/rundir**
002 listening for IKE messages
002 forgetting secrets
002 loading secrets from "/etc/ipsec.secrets"
002 loading secrets from "/etc/ipsec.d/ipsec.secrets"
# ip a s eth3
6: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether b4:7a:f1:88:79:48 brd ff:ff:ff:ff:ff:ff
    inet 13.13.13.1/16 brd 13.13.255.255 scope global eth3
       valid_lft forever preferred_lft forever
    **inet6 2022:172:17:254::62/128 scope global**
       valid_lft forever preferred_lft forever
    inet6 fe80::b67a:f1ff:fe88:7948/64 scope link
       valid_lft forever preferred_lft forever

Thanks
Koti

**Comment by cagney** [comment]
Which version?
4.8 and 4.9 both fixed IPv6 and interface problems, and minline even more.

**Comment by NagarajKoti** [comment]
4.3 version.

**Comment by letoams** [comment]
On Sun, 13 Aug 2023, NagarajKoti wrote:

> 4.3 version.

Please use 4.10 or newer and re-test.

**Comment by cagney** [comment]
Please retest with mainline.
