### ISSUE TITLE
main_thread

### ISSUE THREAD

**Issue by ShorTie8** [libreswan/libreswan#123]
Trying to update Smoothwall to kernel 4.9.44 and gcc-6.4.0.
When I try to compile libreswan I errors & warnings

`/build/sources/libreswan/libreswan-3.21/programs/pluto/state.c: In function 'new_state':
/build/sources/libreswan/libreswan-3.21/programs/pluto/state.c:493:24: error: 'main_thread' undeclared (first use in this function)
  st->st_xauth_thread = main_thread;
                        ^~~~~~~~~~~
/build/sources/libreswan/libreswan-3.21/programs/pluto/state.c:493:24: note: each undeclared identifier is reported only once for each function it appears in
/build/sources/libreswan/libreswan-3.21/programs/pluto/state.c: In function 'delete_state':
/build/sources/libreswan/libreswan-3.21/programs/pluto/state.c:974:2: warning: implicit declaration of function 'xauth_cancel' [-Wimplicit-function-declaration]
  xauth_cancel(st->st_serialno, &st->st_xauth_thread);
  ^~~~~~~~~~~~
/build/sources/libreswan/libreswan-3.21/programs/pluto/state.c:974:2: warning: nested extern declaration of 'xauth_cancel' [-Wnested-externs]
make[4]: *** [../../../mk/depend.mk:34: state.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/build/sources/libreswan/libreswan-3.21/OBJ.linux.i386/programs/pluto'
make[3]: *** [../../mk/program.mk:50: local-base] Error 2
make[3]: Leaving directory '/build/sources/libreswan/libreswan-3.21/programs/pluto'
make[2]: *** [../mk/targets.mk:69: recursive-base] Error 2
make[2]: Leaving directory '/build/sources/libreswan/libreswan-3.21/programs'
make[1]: *** [mk/targets.mk:69: recursive-base] Error 2
make[1]: Leaving directory '/build/sources/libreswan/libreswan-3.21'
make: *** [Makefile:38: compile] Error 2
make: Leaving directory '/build/sources/libreswan'
`

**Comment by letoams** [comment]
Why did you close this bug? Did you find a workaround or bug?
