### ISSUE TITLE
Clients log

### ISSUE THREAD

**Issue by davisbra** [libreswan/libreswan#124]
how can I find clients(user) log?
I want users connection log and visited ip after connecting to VPN with time.
where user log file saved?
or how can I log clients activity?

**Comment by letoams** [comment]
You can find up/down logs in the audit.log and the pluto logs (which are in /var/log or wherever you set logfile= to in the config.

Libreswan is not a traffic monitoring tool, if you want to monitor all traffic a client generates, you need other tools unrelated to IPsec.
