### ISSUE TITLE
windows - linux ipsec

### ISSUE THREAD

**Issue by yargoa** [libreswan/libreswan#125]
Hello
I am trying to produce IPSEC TUNNEL between the REDHAT 7.2 machine and WINDOWS SERVER 2012 machine with certificates.
the root and the sub ca are windows servers
Between 2 REDHAT machines everything works fine
The LIBRESWAN version is 3.20
What should I set up in WINDOWS  or linux so that IPSEC will work
i have tried almost all the options ikve2=never or insist 

this log i repeating trying to connect.

Sep 11 06:33:46: "tubewin" #4: EXPECTATION FAILED: r != NULL (in ikev1_decode_pe                                     er_id at ikev1.c:2817)
Sep 11 06:33:46: "tubewin" #4: no suitable connection for peer 'C=IL, ST=il, L=i                                     l, O=il, OU=il, CN=WIN-E94TTFURM62'
Sep 11 06:33:46: "tubewin" #4: sending encrypted notification INVALID_ID_INFORMA                                     TION to 172.16.110.13:500
Sep 11 06:33:48: | processing connection "tubewin"
Sep 11 06:33:48: | processing connection "tubewin"
Sep 11 06:33:48: "tubewin" #3: ignoring informational payload NO_PROPOSAL_CHOSEN                                     , msgid=00000000, length=28
Sep 11 06:33:48: | ISAKMP Notification Payload
Sep 11 06:33:48: |   00 00 00 1c  00 00 00 01  01 10 00 0e
Sep 11 06:33:48: "tubewin" #3: received and ignored informational message
Sep 11 06:33:48: | processing connection "tubewin"
Sep 11 06:33:49: | processing connection "tubewin"
Sep 11 06:33:49: | processing connection "tubewin"
Sep 11 06:33:49: | processing connection "tubewin"
Sep 11 06:33:49: | processing connection "tubewin"
Sep 11 06:33:49: | processing connection "tubewin"
Sep 11 06:33:49: "tubewin" #4: Main mode peer ID is ID_DER_ASN1_DN: 'C=IL, ST=il                                     , L=il, O=il, OU=il, CN=WIN-E94TTFURM62'
Sep 11 06:33:49: | decoded CN=WIN-E94TTFURM62,OU=il,O=il,L=il,ST=il,C=IL
Sep 11 06:33:49: | get_issuer_crl : looking for a CRL issued by CN=dev-DEVCA-CA,                                     DC=dev,DC=local
Sep 11 06:33:49: | missing or expired CRL
Sep 11 06:33:49: | crl_strict: 0, ocsp: 0, ocsp_strict: 0
Sep 11 06:33:49: | retrying verification with the NSS serverAuth profile
Sep 11 06:33:49: | certificate is valid
Sep 11 06:33:49: "tubewin" #4: certificate CN=WIN-E94TTFURM62,OU=il,O=il,L=il,ST                                     =il,C=IL OK
Sep 11 06:33:49: | get_pluto_gn_from_nss_cert: allocated pluto_gn 0x7f0f56eff948
Sep 11 06:33:49: | CR  30 43 31 15  30 13 06 0a  09 92 26 89  93 f2 2c 64
Sep 11 06:33:49: | CR  01 19 16 05  6c 6f 63 61  6c 31 13 30  11 06 0a 09
Sep 11 06:33:49: | CR  92 26 89 93  f2 2c 64 01  19 16 03 64  65 76 31 15
Sep 11 06:33:49: | CR  30 13 06 03  55 04 03 13  0c 64 65 76  2d 44 45 56
Sep 11 06:33:49: | CR  43 41 2d 43  41
Sep 11 06:33:49: | requested CA: 'DC=local, DC=dev, CN=dev-DEVCA-CA'
Sep 11 06:33:49: | trusted_ca_nss: trustee A = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:49: | trusted_ca_nss: trustor B = '(empty)'
Sep 11 06:33:49: | trusted_ca_nss: trustee A = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:49: | trusted_ca_nss: trustor B = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:49: | trusted_ca_nss: trustee A = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:49: | trusted_ca_nss: trustor B = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:49: | trusted_ca_nss: trustee A = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:49: | trusted_ca_nss: trustor B = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:49: | trusted_ca_nss: trustee A = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:49: | trusted_ca_nss: trustor B = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:49: "tubewin" #4: EXPECTATION FAILED: r != NULL (in ikev1_decode_pe                                     er_id at ikev1.c:2817)
Sep 11 06:33:49: "tubewin" #4: no suitable connection for peer 'C=IL, ST=il, L=i                                     l, O=il, OU=il, CN=WIN-E94TTFURM62'
Sep 11 06:33:49: "tubewin" #4: sending encrypted notification INVALID_ID_INFORMA                                     TION to 172.16.110.13:500
Sep 11 06:33:52: | processing connection "tubewin"
Sep 11 06:33:56: | processing connection "tube"
Sep 11 06:33:56: "tube" #1: max number of retransmissions (8) reached STATE_PARE                                     NT_I1.  No response (or no acceptable response) to our first IKEv2 message
Sep 11 06:33:56: "tube" #1: starting keying attempt 2 of an unlimited number
Sep 11 06:33:56: | processing connection "tube"
Sep 11 06:33:56: | processing connection "tube"
Sep 11 06:33:56: "tube" #5: initiating v2 parent SA to replace #1
Sep 11 06:33:56: deleting other state #1 (STATE_PARENT_I1) "tube"
Sep 11 06:33:56: | processing connection "tube"
Sep 11 06:33:56: "tube" #5: STATE_PARENT_I1: sent v2I1, expected v2R1
Sep 11 06:33:56: | processing connection "tubewin"
Sep 11 06:33:56: | processing connection "tubewin"
Sep 11 06:33:56: | processing connection "tubewin"
Sep 11 06:33:56: | processing connection "tubewin"
Sep 11 06:33:56: | processing connection "tubewin"
Sep 11 06:33:56: "tubewin" #4: Main mode peer ID is ID_DER_ASN1_DN: 'C=IL, ST=il                                     , L=il, O=il, OU=il, CN=WIN-E94TTFURM62'
Sep 11 06:33:56: | decoded CN=WIN-E94TTFURM62,OU=il,O=il,L=il,ST=il,C=IL
Sep 11 06:33:56: | get_issuer_crl : looking for a CRL issued by CN=dev-DEVCA-CA,                                     DC=dev,DC=local
Sep 11 06:33:56: | missing or expired CRL
Sep 11 06:33:56: | crl_strict: 0, ocsp: 0, ocsp_strict: 0
Sep 11 06:33:56: | retrying verification with the NSS serverAuth profile
Sep 11 06:33:56: | certificate is valid
Sep 11 06:33:56: "tubewin" #4: certificate CN=WIN-E94TTFURM62,OU=il,O=il,L=il,ST                                     =il,C=IL OK
Sep 11 06:33:56: | get_pluto_gn_from_nss_cert: allocated pluto_gn 0x7f0f56f022a8
Sep 11 06:33:56: | CR  30 43 31 15  30 13 06 0a  09 92 26 89  93 f2 2c 64
Sep 11 06:33:56: | CR  01 19 16 05  6c 6f 63 61  6c 31 13 30  11 06 0a 09
Sep 11 06:33:56: | CR  92 26 89 93  f2 2c 64 01  19 16 03 64  65 76 31 15
Sep 11 06:33:56: | CR  30 13 06 03  55 04 03 13  0c 64 65 76  2d 44 45 56
Sep 11 06:33:56: | CR  43 41 2d 43  41
Sep 11 06:33:56: | requested CA: 'DC=local, DC=dev, CN=dev-DEVCA-CA'
Sep 11 06:33:56: | trusted_ca_nss: trustee A = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:56: | trusted_ca_nss: trustor B = '(empty)'
Sep 11 06:33:56: | trusted_ca_nss: trustee A = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:56: | trusted_ca_nss: trustor B = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:56: | trusted_ca_nss: trustee A = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:56: | trusted_ca_nss: trustor B = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:56: | trusted_ca_nss: trustee A = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:56: | trusted_ca_nss: trustor B = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:56: | trusted_ca_nss: trustee A = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:56: | trusted_ca_nss: trustor B = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:56: | trusted_ca_nss: trustee A = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:56: | trusted_ca_nss: trustor B = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:56: "tubewin" #4: EXPECTATION FAILED: r != NULL (in ikev1_decode_pe                                     er_id at ikev1.c:2817)
Sep 11 06:33:56: "tubewin" #4: no suitable connection for peer 'C=IL, ST=il, L=i                                     l, O=il, OU=il, CN=WIN-E94TTFURM62'
Sep 11 06:33:56: "tubewin" #4: sending encrypted notification INVALID_ID_INFORMA                                     TION to 172.16.110.13:500
Sep 11 06:33:56: | processing connection "tube"
Sep 11 06:33:57: | processing connection "tube"
Sep 11 06:33:58: | processing connection "tube"
^C
[root@lintest ipsec.d]# tailf logs/pluto.log
Sep 11 06:33:56: | trusted_ca_nss: trustee A = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:56: | trusted_ca_nss: trustor B = 'DC=local, DC=dev, CN=dev-DEVCA-C                                     A'
Sep 11 06:33:56: "tubewin" #4: EXPECTATION FAILED: r != NULL (in ikev1_decode_pe                                     er_id at ikev1.c:2817)
Sep 11 06:33:56: "tubewin" #4: no suitable connection for peer 'C=IL, ST=il, L=i                                     l, O=il, OU=il, CN=WIN-E94TTFURM62'
Sep 11 06:33:56: "tubewin" #4: sending encrypted notification INVALID_ID_INFORMA                                     TION to 172.16.110.13:500
Sep 11 06:33:56: | processing connection "tube"
Sep 11 06:33:57: | processing connection "tube"
Sep 11 06:33:58: | processing connection "tube"
Sep 11 06:34:00: | processing connection "tube"
Sep 11 06:34:00: | processing connection "tubewin"
Sep 11 06:34:04: | processing connection "tube"
Sep 11 06:34:04: | processing connection "tubewin"
Sep 11 06:34:04: | processing connection "tubewin"
Sep 11 06:34:04: | processing connection "tube"
^C
[root@lintest ipsec.d]# tailf logs/pluto.log
Sep 11 06:36:06: packet from 172.16.110.13:500: phase 1 message is part of an un                                     known exchange
Sep 11 06:36:06: packet from 172.16.110.13:500: phase 1 message is part of an un                                     known exchange
Sep 11 06:36:06: | processing connection "tube"
Sep 11 06:36:07: | processing connection "tubewin"
Sep 11 06:36:07: | processing connection "tubewin"
Sep 11 06:36:07: "tubewin" #11: ignoring informational payload NO_PROPOSAL_CHOSE                                     N, msgid=00000000, length=28
Sep 11 06:36:07: | ISAKMP Notification Payload
Sep 11 06:36:07: |   00 00 00 1c  00 00 00 01  01 10 00 0e
Sep 11 06:36:07: "tubewin" #11: received and ignored informational message
Sep 11 06:36:08: | processing connection "tube"
Sep 11 06:36:11: | processing connection "tubewin"
Sep 11 06:36:11: | processing connection "tubewin"
Sep 11 06:36:11: "tubewin" #11: ignoring informational payload NO_PROPOSAL_CHOSE                                     N, msgid=00000000, length=28
Sep 11 06:36:11: | ISAKMP Notification Payload
Sep 11 06:36:11: |   00 00 00 1c  00 00 00 01  01 10 00 0e
Sep 11 06:36:11: "tubewin" #11: received and ignored informational message
Sep 11 06:36:12: | processing connection "tube"
Sep 11 06:36:14: | processing connection "tubewin"
Sep 11 06:36:14: | processing connection "tube"
Sep 11 06:36:19: | processing connection "tubewin"
Sep 11 06:36:19: | processing connection "tubewin"
Sep 11 06:36:19: "tubewin" #11: ignoring informational payload NO_PROPOSAL_CHOSE                                     N, msgid=00000000, length=28
Sep 11 06:36:19: | ISAKMP Notification Payload
Sep 11 06:36:19: |   00 00 00 1c  00 00 00 01  01 10 00 0e
Sep 11 06:36:19: "tubewin" #11: received and ignored informational message
Sep 11 06:36:20: | processing connection "tube"
Sep 11 06:36:21: packet from 172.16.110.13:500: phase 1 message is part of an un                                     known exchange
Sep 11 06:36:21: packet from 172.16.110.13:500: phase 1 message is part of an un                                     known exchange
Sep 11 06:36:21: packet from 172.16.110.13:500: phase 1 message is part of an un                                     known exchange
Sep 11 06:36:21: packet from 172.16.110.13:500: phase 1 message is part of an un                                     known exchange
Sep 11 06:36:35: | processing connection "tubewin"
Sep 11 06:36:35: | processing connection "tubewin"
Sep 11 06:36:35: "tubewin" #11: ignoring informational payload NO_PROPOSAL_CHOSE                                     N, msgid=00000000, length=28
Sep 11 06:36:35: | ISAKMP Notification Payload
Sep 11 06:36:35: |   00 00 00 1c  00 00 00 01  01 10 00 0e
Sep 11 06:36:35: "tubewin" #11: received and ignored informational message
Sep 11 06:36:36: packet from 172.16.110.13:500: phase 1 message is part of an un                                     known exchange
Sep 11 06:36:36: packet from 172.16.110.13:500: phase 1 message is part of an un                                     known exchange
Sep 11 06:36:36: packet from 172.16.110.13:500: phase 1 message is part of an un                                     known exchange
Sep 11 06:36:36: packet from 172.16.110.13:500: phase 1 message is part of an un                                     known exchange
Sep 11 06:36:36: | processing connection "tube"
Sep 11 06:36:39: | processing connection "tubewin"
Sep 11 06:36:39: "tubewin": deleting non-instance connection
Sep 11 06:36:39: | processing connection "tubewin"
Sep 11 06:36:39: "tubewin" #11: deleting state (STATE_MAIN_I1)
Sep 11 06:36:39: | setting ID to ID_DER_ASN1_DN: 'CN=lintest,OU=il,O=il,L=il,ST=                                     il,C=il'
Sep 11 06:36:39: | loaded left certificate 'lintest'
Sep 11 06:36:39: | get_pluto_gn_from_nss_cert: allocated pluto_gn 0x7f0f56efba78
Sep 11 06:36:39: added connection description "tubewin"
Sep 11 06:36:39: | processing connection "tubewin"
Sep 11 06:36:39: | processing connection "tubewin"
Sep 11 06:36:39: | processing connection "tubewin"
Sep 11 06:36:39: "tubewin" #13: initiating Main Mode
Sep 11 06:36:39: | processing connection "tubewin"
Sep 11 06:36:39: "tubewin" #13: ignoring informational payload NO_PROPOSAL_CHOSE                                     N, msgid=00000000, length=28
Sep 11 06:36:39: | ISAKMP Notification Payload
Sep 11 06:36:39: |   00 00 00 1c  00 00 00 01  01 10 00 0e
Sep 11 06:36:39: "tubewin" #13: received and ignored informational message
Sep 11 06:36:40: | processing connection "tubewin"
Sep 11 06:36:40: | processing connection "tubewin"
Sep 11 06:36:40: "tubewin" #13: ignoring informational payload NO_PROPOSAL_CHOSE                                     N, msgid=00000000, length=28
Sep 11 06:36:40: | ISAKMP Notification Payload
Sep 11 06:36:40: |   00 00 00 1c  00 00 00 01  01 10 00 0e
Sep 11 06:36:40: "tubewin" #13: received and ignored informational message
Sep 11 06:36:40: | processing connection "tubewin"
Sep 11 06:36:40: | processing connection "tubewin"
Sep 11 06:36:40: "tubewin" #13: ignoring informational payload NO_PROPOSAL_CHOSE                                     N, msgid=00000000, length=28
Sep 11 06:36:40: | ISAKMP Notification Payload
Sep 11 06:36:40: |   00 00 00 1c  00 00 00 01  01 10 00 0e
Sep 11 06:36:40: "tubewin" #13: received and ignored informational message
Sep 11 06:36:41: | processing connection "tubewin"
Sep 11 06:36:41: | processing connection "tubewin"
Sep 11 06:36:41: "tubewin" #13: ignoring informational payload NO_PROPOSAL_CHOSE                                     N, msgid=00000000, length=28
Sep 11 06:36:41: | ISAKMP Notification Payload
Sep 11 06:36:41: |   00 00 00 1c  00 00 00 01  01 10 00 0e
Sep 11 06:36:41: "tubewin" #13: received and ignored informational message
Sep 11 06:36:43: | processing connection "tubewin"
Sep 11 06:36:43: | processing connection "tubewin"
Sep 11 06:36:43: "tubewin" #13: ignoring informational payload NO_PROPOSAL_CHOSE                                     N, msgid=00000000, length=28
Sep 11 06:36:43: | ISAKMP Notification Payload
Sep 11 06:36:43: |   00 00 00 1c  00 00 00 01  01 10 00 0e
Sep 11 06:36:43: "tubewin" #13: received and ignored informational message
Sep 11 06:36:47: | processing connection "tubewin"
Sep 11 06:36:47: | processing connection "tubewin"
Sep 11 06:36:47: "tubewin" #13: ignoring informational payload NO_PROPOSAL_CHOSE                                     N, msgid=00000000, length=28
Sep 11 06:36:47: | ISAKMP Notification Payload
Sep 11 06:36:47: |   00 00 00 1c  00 00 00 01  01 10 00 0e
Sep 11 06:36:47: "tubewin" #13: received and ignored informational message

**Comment by letoams** [comment]
If you still have an issue configuring libreswan, please use the mailing list for configuration questions
