### ISSUE TITLE
ikev1 can't track multiple labeled IPsec SAs

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1256]
IKEv2 instantiates a separate connection for each labeled Child SA.
IKEv1 instead shares a single connection between all the labeled IPsec SAs.

This means that the multiple children are all trying to share the single .newest_ipsec_sa field.

**Comment by letoams** [comment]
On Tue, 5 Sep 2023, Tuomo Soini wrote:

> I suggest removing ikev1 labeled IPsec support all together - nobody should use it.

Agreed. Let's remove it.
