### ISSUE TITLE
Where does the libreswan put the certs in?

### ISSUE THREAD

**Issue by bettswang** [libreswan/libreswan#1267]
Hi, maintainer

I just want to install openvswitch-ipsec with self-sign cert on centos9. After installation, I found the `ipsec.service`  did not  locate the cert file. I place the files on /ect/ipsec.d/policies/ or /var/lib/ipsec/nss/ . Both them did not work. Even I create dir `certs | private | reqs` on /etc/ipsec.d/, it also couldn't work.  

```
[root@localhost nss]# systemctl status ipsec.service
● ipsec.service - Internet Key Exchange (IKE) Protocol Daemon for IPsec
     Loaded: loaded (/usr/lib/systemd/system/ipsec.service; disabled; preset: disabled)
     Active: active (running) since Tue 2023-09-12 15:28:17 CST; 30s ago
       Docs: man:ipsec(8)
             man:pluto(8)
             man:ipsec.conf(5)
    Process: 3319 ExecStartPre=/usr/libexec/ipsec/addconn --config /etc/ipsec.conf --checkconfig (code=exited, status=0/SUCCESS)
    Process: 3320 ExecStartPre=/usr/libexec/ipsec/_stackmanager start (code=exited, status=0/SUCCESS)
    Process: 3535 ExecStartPre=/usr/sbin/ipsec --checknss (code=exited, status=0/SUCCESS)
    Process: 3536 ExecStartPre=/usr/sbin/ipsec --checknflog (code=exited, status=0/SUCCESS)
   Main PID: 3547 (pluto)
     Status: "Startup completed."
      Tasks: 8 (limit: 10820)
     Memory: 3.7M
        CPU: 271ms
     CGroup: /system.slice/ipsec.service
             └─3547 /usr/libexec/ipsec/pluto --leak-detective --config /etc/ipsec.conf --nofork

Sep 12 15:28:17 localhost.localdomain pluto[3547]: adding UDP interface lo [::1]:4500
Sep 12 15:28:17 localhost.localdomain pluto[3547]: loading secrets from "/etc/ipsec.secrets"
Sep 12 15:28:17 localhost.localdomain pluto[3547]: loading secrets from "/etc/ipsec.secrets"
Sep 12 15:28:17 localhost.localdomain pluto[3547]: "tun-1": IKE SA proposals (connection add):
Sep 12 15:28:17 localhost.localdomain pluto[3547]: "tun-1":   1:IKE=AES_GCM_C_256-HMAC_SHA2_256-NONE-MODP2048+MODP3072+MODP4096+MODP8192+ECP_256+ECP_384+ECP_521+CURVE25519
Sep 12 15:28:17 localhost.localdomain pluto[3547]: "tun-1": Child SA proposals (connection add):
Sep 12 15:28:17 localhost.localdomain pluto[3547]: "tun-1":   1:ESP=AES_GCM_C_256-NONE-NONE-ENABLED+DISABLED
Sep 12 15:28:17 localhost.localdomain pluto[3547]: "tun-1": failed to add connection: left certificate 'ovs_certkey_host_1' not found in the NSS database
Sep 12 15:28:17 localhost.localdomain pluto[3547]: initiating all conns with alias='tun-1'
Sep 12 15:28:17 localhost.localdomain pluto[3547]: no connection named "tun-1"


[root@localhost nss]# ll
total 92
-rw------- 1 root root 28672 Sep 12 15:14 cert9.db
-rw-r--r-- 1 root root  4391 Sep 12 14:04 host_1-cert.pem
-rw-r--r-- 1 root root  1704 Sep 12 14:04 host_1-privkey.pem
-rw-r--r-- 1 root root  3680 Sep 12 14:04 host_1-req.pem
-rw-r--r-- 1 root root  4391 Sep 12 14:04 host_2-cert.pem
-rw------- 1 root root 36864 Sep 12 15:14 key4.db
-rw------- 1 root root   429 Sep 11 10:46 pkcs11.txt
[root@localhost nss]# cd /etc/ipsec.d/
[root@localhost ipsec.d]# ll
total 72
-rw-------  1 root root 28672 Sep 12 15:35 cert9.db
drwxr-xr-x  2 root root    52 Sep 12 10:32 certs
-rw-------  1 root root 36864 Sep 12 15:28 key4.db
-rw-------  1 root root   423 Sep 11 17:03 pkcs11.txt
drwxr-xr-x. 2 root root  4096 Sep 12 10:57 policies
drwxr-xr-x  2 root root    32 Sep 12 10:33 private
drwxr-xr-x  2 root root    28 Sep 12 10:33 reqs
[root@localhost ipsec.d]#


```

**Comment by bettswang** [comment]
All right, I have convert the cert and private key into`.p12` file. Then I imported it into nss database. But how do I assign the cert's path to openvswitch? 

```
[root@localhost nss]# certutil  -L -d /var/lib/ipsec/nss/

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

host_1 - Open vSwitch                                        u,u,u

```

They do this on openvswitch :
```
ovs-vsctl set Open_vSwitch . \
other_config:certificate=/etc/keys/host_1-cert.pem \
other_config:private_key=/etc/keys/host_1-privkey.pem 
```

**Comment by bleve** [comment]
Your nss database is missing ca certificate. Generally you always need certificate chain for certificate checking with IPsec.

Libreswan is generic IPsec implementation and we are not developing openvswitch integration. Please check openvswitch documentation about ipsec integration there.

**Comment by bettswang** [comment]
This is a self sign cert. It doesn't need CA cert.  I would submit this to ovs group and keep track of it .

**Comment by bleve** [comment]
You absolutely want CA strucute for IPsec.

**Comment by letoams** [comment]
On Sep 13, 2023, at 05:04, bettswang ***@***.***> wrote:
> 
> ﻿
> All right, I have convert the cert and private key into.p12 file. Then I imported it into nss database. But how do I assign the cert's path to openvswitch?
> 
> ***@***.*** nss]# certutil  -L -d /var/lib/ipsec/nss/
> 
> Certificate Nickname                                         Trust Attributes
>                                                              SSL,S/MIME,JAR/XPI
> 
> host_1 - Open vSwitch                                        u,u,u
It’s uncommon to use hardcoded keys/cert without a CA. You might need to tweak the trusted bits of the cert in the db using certutil.


> They do this on openvswitch :
> 
> ovs-vsctl set Open_vSwitch . \
> other_config:certificate=/etc/keys/host_1-cert.pem \
> other_config:private_key=/etc/keys/host_1-privkey.pem 

I don’t understand what openswitch has to do with the IPsec configuration. You can use the same cert for multiple sub systems. Libreswasn itself only talks IKE to setup IPsec.

**Comment by bettswang** [comment]
I think they should only call this service and want to use customized certificates.

**Comment by bettswang** [comment]
> On Tue, 12 Sep 2023, bettswang wrote: I just want to install openvswitch-ipsec on centos9. After installation, I found the ipsec.service did not locate the cert file. I place the files on /ect/ipsec.d/policies/ or /var/lib/ipsec/nss/ . Both them did not work. Even I create dir certs | private | reqs on /etc/ipsec.d/, it also couldn't work.
> All X.509 material goes into the NSS database. Run: sudo ipsec status |grep nssdir It will show something like: 000 nssdir=/var/lib/ipsec/nss, dumpdir=/run/pluto, statsbin=unset So in my case, the NSS database is in /var/lib/ipsec/nss You can use the NSS certutil command to add/remove/list the contents Note that the easiest way is to import PKCS#12 bundles, in which case you do not need to know anything and you can just run: ipsec import yourfile.p12 Separate pem files are not supported. Everything MUST be in the NSS database (the NSS database consists of the cert9.db and key4.db files). Paul

This sloved the issue. 

```
openssl pkcs12 -export -out file.p12 -inkey private-key.pem -in cert.pem
rm -rf /var/lib/ipsec/nss
ipsec checknss
ipsec import file.p12
```
