### ISSUE TITLE
RPM .spec issues in 3.21

### ISSUE THREAD

**Issue by davidarnold** [libreswan/libreswan#127]
Commit f3ac0e6868f45d9238ae76eef59b0d6d5c5c2d36 introduced a regression with regard to #83.

The new commit comment discusses problems with not using `true` and `false` in the spec, but `false` is still truthy as far as `%if` is concerned.

This breaks the build in the `USE_SECCOMP` test.  `libseccomp-devel` is not available on RHEL/CentOS 6.

Also broken is the new requirement on `unbound-devel >= 1.5.4`.  The latest version on both 6 and 7 is 1.4.20.

**Comment by davidarnold** [comment]
Tagging @letoams for visibility.

**Comment by bleve** [comment]
Yes. That is wrong. I will fix that properly.

**Comment by letoams** [comment]
Note that unbound is being updated in rhel7 to 1.6.6. And our repositories in download.libreswan.org/binaries have updated unbound's to match these already.

Tuomo did fix the true/false items.
