### ISSUE TITLE
whack defaults to pfs=no (there's no --no-pfs option)

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1273]
ssia

**Comment by bleve** [comment]
That is bad. pfs=yes is our default in addconn so whack should default to pfs being enabled also

**Comment by paulwouters** [comment]
fixed.

**Comment by cagney** [comment]
e91dee68d4ebd9165c7038008fab3c98ce4fdb9a unfortunately restored the old behaviour; needs tweak but this time with a testsuite update
