### ISSUE TITLE
will the revival and ondemand kernel policies ever differ?

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1283]
Better explain:

When an unrouted connection is «ipsec route»ed, on-demand or trap kernel policies are installed.  From there, when it gets an acquire, it changes things to negotiation et.al.

When an UP established connection times out it replaces the established kernel policies with on-demand policies so that an acquire can trigger a re-negotiation.

Is there any reason to expect the on-demand policy after establish to be different to the on-demand policy when initially being routed?

**Comment by paulwouters** [comment]
maybe?
eg when a connection was on demand and came up due to traffic. what if the admin hits: ipsec auto --up connname ?
I think that should mean "keep it up forever" ? eg at that point "ondemand" should be replaced with "always up" and revival should kick in ?

**Comment by cagney** [comment]
>  if the admin hits: ipsec auto --up connname 

the end result would be either:
- an established connection; to be specific: routed_ondemand -> routed_negotiation -> established
- a fail, at which point, like for an initial acquire, goes into revival again: routed_ondemand -> routed_negotiation -> routed_ondemand (but with a revival event lurking)
