### ISSUE TITLE
pluto, on linux, should flush xfrm policy and states @ startup?

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1284]
from #675
@bleve

_But should pluto instead now flush xfrm policy and states @ startup? I think we relied on `_stackamanger` to do that because setup script is not used any more on startup._

@letoams 

_Yes we should. Alternatively we can change the systemd service or init script to do it.Possibly we want a config option to skip doing this ?_

@bleve 

_I'd find it better for pluto do do cleanup - then we can get rid of that hack for openstack where at stop we don't cleanup because we can handle that inside pluto._

**Comment by letoams** [comment]
On Tue, 19 Sep 2023, cagney wrote:

> @bleve
> 
> I'd find it better for pluto do do cleanup - then we can get rid of that hack for openstack where at stop we don't
> cleanup because we can handle that inside pluto.

I don't think any hack can be removed? the ipsec whack --shutdown --leave-state would still be needed?

**Comment by cagney** [comment]
If pluto does the flush then the magic exit code to stop the wrapper flushing shouldn't be needed? (from @bleve and I discussing this).

**Comment by letoams** [comment]
On Wed, 20 Sep 2023, cagney wrote:

> If pluto does the flush then the magic exit code to stop the wrapper flushing shouldn't be needed? (from @bleve and
> I discussing this).

Oh. I forgot that was done in the ipsec.service file. Yes, that could be
removed although perhaps we should keep the exit code for compatibility?

**Comment by bleve** [comment]
No need to  - it is only used in service file.
