### ISSUE TITLE
Version 3.22 hard depends on SELinux

### ISSUE THREAD

**Issue by DeX77** [libreswan/libreswan#129]
Until Version 3.21 it was possible to build libreswan without SELinux libs.

Now I get:

`libreswan-3.22/programs/pluto/security_selinux.h:18:29: fatal error: selinux/selinux.h: No such file or directory`

and I don't see any option to disable it.

To clarify: libreswan now depends on SELinux?

**Comment by bleve** [comment]
As far as we know all major distributions have selinux support on so that was switched to enabled for 3.22.

if you want to build without selinux support, you need to define USE_LABELED_IPSEC=false on build time.

Make time config variales with descriptions are in mk/config.mk.

**Comment by DeX77** [comment]
USE_LABELED_IPSEC=false worked, thx.
