### ISSUE TITLE
printf is incorrect in resolv.conf generation

### ISSUE THREAD

**Issue by afranchuk** [libreswan/libreswan#130]
2a2578b5763d027c0f5723f4c66844a801f710d4 added "%s" as the first argument to `printf` when generating resolv.conf files, however both coreutils printf and bash built-in printf ignore escape sequences in string arguments. This breaks the generated resolv.conf files, as the newlines are printed as "\n". Instead of using printf at all, `echo -e` would probably be sufficient.

**Comment by bleve** [comment]
Thank yo for your problem report. I will rewrite that part of _updown.* but we can't accept your pull request becasue we can't use echo here because of default shell on debian.

**Comment by afranchuk** [comment]
Does that shell not support escape sequences in echo?

**Comment by bleve** [comment]
echo on dash doesn't support escape sequencies.
After my rewrite I could now change to basic echo.

**Comment by letoams** [comment]
fixed differently
