### ISSUE TITLE
trim connectionstatus output when never-negotiate

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1310]
for instance:
```
000 "whack--passthrough":   liveness: passive; dpddelay:0s; retransmit-timeout:0s
000 "whack--passthrough":   nat-traversal: encaps:0??; keepalive:no
```
is meaningless (ignore the 0??, it's being changed to n/a)

**Comment by letoams** [comment]
On Thu, 5 Oct 2023, cagney wrote:

> 000 "whack--passthrough":   liveness: passive; dpddelay:0s; retransmit-timeout:0s
> 000 "whack--passthrough":   nat-traversal: encaps:0??; keepalive:no
> 
> is meaningless (ignore the 0??, it's being changed to n/a)

Not sure that's worth the trouble. AND it will bite people who are
parsing the output :P
