### ISSUE TITLE
is xauth-username IKEv1?

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1315]
In state.c, there's the nonsensical code:
```
	FOR_EACH_ITEM(spd, &c->child.spds) {
		if (spd->local->host->config->xauth.client) {
			if (spd->local->host->config->xauth.username != NULL) {
				jam_str(ike->sa.st_xauth_username,
					sizeof(ike->sa.st_xauth_username),
					spd->local->host->config->xauth.username);
				break;
			}
		}
	}
```
(why repeatedly copy c.config.xauth.username to ike.sa.st_xauth_username)

which is executed for both IKEv1 and IKEv2; but I suspect only IKEv1 needs it.

**Comment by cagney** [comment]
```
<bleve> cagney: xauth is ikev1 only.
<cagney> ah, IKEv2 pam uses the ID
```

**Comment by letoams** [comment]
I thought I renamed most to username, but maybe not. The xauthusername option was renamed username and it might come back into IKEv2 for some EAP methods. But currently we can only receive an (xauth)username in ikev1. Note that as a server you only receive usernames (so in state). As a client you get one from the config to present to the server (so in config connection)Sent using a virtual keyboard on a phoneOn Oct 6, 2023, at 14:22, cagney ***@***.***> wrote:﻿
In state.c, there's the nonsensical code:
	FOR_EACH_ITEM(spd, &c->child.spds) {
		if (spd->local->host->config->xauth.client) {
			if (spd->local->host->config->xauth.username != NULL) {
				jam_str(ike->sa.st_xauth_username,
					sizeof(ike->sa.st_xauth_username),
					spd->local->host->config->xauth.username);
				break;
			}
		}
	}

(why repeatedly copy c.config.xauth.username to ike.sa.st_xauth_username)
which is executed for both IKEv1 and IKEv2; but I suspect only IKEv1 needs it.

**Comment by cagney** [comment]
> As a client you get one from the config to present to the server (so in config connection)

Yes, that is what I'm looking at.

The client's value in .config.xauth.username is copied to .st_xauth_username once per SPD - not needed - definitely not needed by IKEv2.
