### ISSUE TITLE
merge redirect and revival code

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1319]
The redirect code establishes a connection to a non-standard [redirect] port.
The revival code establishes a connection to a non-standard [NATed] port.

**Comment by letoams** [comment]
> The redirect code establishes a connection to a non-standard [redirect] port.

Usually just a different address with a standard port ?

**Comment by cagney** [comment]
> Usually just a different address with a standard port ?

yea, my terminology is loose.  When creating the IKE SA one or both of the:

- the source address (by implication things like encap)
- the destination address/port

are set to non-defaults.  With 780688222c0f668fbdc44ff20ced95a69cf68053 revival is doing this explicitly.
Conceptually, redirect and even TCP flip-flopping, are doing the same thing.
