### ISSUE TITLE
Does the support not support custom ports?

### ISSUE THREAD

**Issue by RoseEnd** [libreswan/libreswan#132]

**Comment by letoams** [comment]
On Fri, 27 Oct 2017, RoseEnd wrote:

> Subject: [libreswan/libreswan] Does the support not support custom ports?
>     (#132)

It is supposed to support these, but it is known not to work reliably.
The upcoming TCP support does work over any (preconfigured) port
properly.

**Comment by DzasterAbz** [comment]
Guys! I'm new to this. Help me! I'm trying for GSoC. Guide me! Please

**Comment by letoams** [comment]
There are likely assumptions in the code for port 500. The only way would be to find those in the source
and fix them to use pluto_port

**Comment by letoams** [comment]
libreswan 4.0 supports leftikeport= and rightikeport=
