### ISSUE TITLE
Multiple IP / network interfaces

### ISSUE THREAD

**Issue by cjconstante** [libreswan/libreswan#133]
There is any option to listen in all interfaces?
I need to create clients that can connect to any network interface or to any specific interface. How can i do that?

I can have created tunnel for each ip but always get connected through the main ip.

**Comment by letoams** [comment]
> There is any option to listen in all interfaces?
> 

ipsec status or ipsec listen

The last one will update the daemon with the IPs on the system.
> I need to create clients that can connect to any network interface or to any specific interface. How can i do that?
> 
That works by default ? Check the road warrior config examples?

> I can have created tunnel for each ip but always get connected through the main ip.
> 

You have to explain in more detail what you are trying to do .....

 Paul

**Comment by cjconstante** [comment]
Thanks for the reply.
I need to create a vpn for remote users. I want the users can connect to several public interfaces because the sever has at least 5.
So, I need they could connect to eth0 and when browsing internet the ip showed be the one who thy connected.

--
Cristian Constante

**Comment by letoams** [comment]
On Sun, 5 Nov 2017, cjconstante wrote:

> I need to create a vpn for remote users. I want the users can connect to several public interfaces because the sever has at least 5.
> So, I need they could connect to eth0 and when browsing internet the ip showed be the one who thy connected.

You should be able to do that by specifying different conns on the
server which only differ by left=IPaddressOfServer and rightaddresspool.

then on the system, use a SNAT rule to rewrite the addresspool IPs to
the server's public IP associcated with that addresspool.

Paul
