### ISSUE TITLE
drop `msdh-downgrade=`

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1337]
it should be obsolete

**Comment by bleve** [comment]
That is not corect behaviour. Correct is:
esp=aes_gcm-dh19,aes_gcm-dh2

But that won't work by default because we have disabled dh2 on build by default.

**Comment by letoams** [comment]
On Oct 19, 2023, at 14:33, cagney ***@***.***> wrote:﻿
if v4.5's pfs= behaviour is restored, someone really wanting msdh-downgrade can specify:
esp=aesgcm-dh19,aesgcm-none
That should allow esp to be either one of these for the first child AND rekeys. It should not allow a child to switch esp proposal during rely, just like esp=aes,3des doesn’t allow you to switch from aes to 3des on rekey

**Comment by bleve** [comment]
That should allow downgrade to dh2 - but it got broken when we disabled dh2 out of the box so we should just remove it. Now it allows without pfs when dh2 support is not build in.

**Comment by bleve** [comment]
So on 5.0 we should not have that option if build with default options.

**Comment by cagney** [comment]
I'd drop the option entirely; how to specify none+initial-proposals is for #1265

**Comment by cagney** [comment]
@bleve I don't think:
> That is not correct behaviour. Correct is: esp=aes_gcm-dh19,aes_gcm-dh2
was ever implemented in pluto - the peer would have sent back invalid-ke-want-dh2 and the rekey would have failed.

**Comment by cagney** [comment]
punt to 6.0
