### ISSUE TITLE
libreswan 3.22 NOT work on CentOS

### ISSUE THREAD

**Issue by yuhaiyang** [libreswan/libreswan#134]
[root@root /]# uname -r      
2.6.32-696.13.2.el6.x86_64
[root@root /]# cat /etc/redhat-release 
CentOS release 6.9 (Final)
I try to yum install libreswan(3.22-2.el6_9) from libreswan repository, and ipsec verify result is ok, don't have any faileds.
But when I run "service ipsec start". It tips 'FAILED'. I try to trouble this issue, but not success.
So I try compile from source code, after I run "make programs",it tips 
"_cc1: warnings being treated as errors
/usr/local/src/libreswan/lib/libipsecconf/confwrite.c: In function ‘confwrite_int’:
/usr/local/src/libreswan/lib/libipsecconf/confwrite.c:156: error: ignoring return value of ‘fwrite’, declared with attribute warn_unused_result"_
I download the V3.20 source code ,complie and install ,it's work~
I think this is a bug in V3.22.

**Comment by bleve** [comment]
Known. There are two bugs which are fixed in our own packge.

Please use the rpm package we provide. https://download.libreswan.org/binaries/README.repo

**Comment by yuhaiyang** [comment]
[root@root etc]# service ipsec start    
Starting pluto IKE daemon for IPsec: .....                 [FAILED]
[root@root etc]# service ipsec version
Linux Libreswan 3.22 (netkey) on 2.6.32-696.13.2.el6.x86_64

IPSec also can not start.

**Comment by letoams** [comment]
Run ipsec addconn —checkconfig manually and see if it doesn’t like some config option ?

**Comment by bleve** [comment]
Did you also update unbound from our repository? you need that too.

**Comment by bleve** [comment]
Unfortunately you are right, our package has wrong patch. We should have 116fa1c1 as a patch there but we have other cleanup patch which won't fix pluto.

**Comment by letoams** [comment]
I pushed 3-22.3 to our rhel6 binary repository to address this issue
