### ISSUE TITLE
ExecStopPost=/bin/bash -c 'if test "$EXIT_STATUS" != "12"; then /sbin/ip xfrm policy flush; /sbin/ip xfrm state flush; fi'

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1345]
drop it?

**Comment by paulwouters** [comment]
It seems we do not clean all state, eg the ipv6 holes.

004 "vpn.nohats.ca"[1] 193.110.157.148 #2: initiator established Child SA using #1; IPsec tunnel [100.64.13.3-100.64.13.3:0-65535 0] -> [0.0.0.0-255.255.255.255:0-65535 0] {ESPinUDP=>0xde39d49a <0x7ad7aec1 xfrm=AES_GCM_16_256-NONE NATD=193.110.157.148:4500 DPD=passive}

[root@fedora libreswan]# ipsec whack --shutdown
[root@fedora libreswan]# ip xfrm policy
src ::/0 dst ::/0 proto ipv6-icmp type 135 
	dir out priority 1 ptype main 
src ::/0 dst ::/0 proto ipv6-icmp type 135 
	dir fwd priority 1 ptype main 
src ::/0 dst ::/0 proto ipv6-icmp type 135 
	dir in priority 1 ptype main 
src ::/0 dst ::/0 proto ipv6-icmp type 136 
	dir out priority 1 ptype main 
src ::/0 dst ::/0 proto ipv6-icmp type 136 
	dir fwd priority 1 ptype main 
src ::/0 dst ::/0 proto ipv6-icmp type 136 
	dir in priority 1 ptype main 
[root@fedora libreswan]# ip xfrm state
[root@fedora libreswan]# 


Perhaps ideally:

if the service is restarted, do not flush on exit but in startup
if service is stopped with --leave-state, do not flush
if service is stopped regularly, flush on exit

But these conditions might be tricky to get right. eg someone restarting a pod might use just stop and not restart

**Comment by bleve** [comment]
Nothing tricky here. We have --leave-state which leaves states on stop (which is first part of restart): On start we flush states anyway. So there is no problem.

**Comment by letoams** [comment]
On Oct 25, 2023, at 10:55, Tuomo Soini ***@***.***> wrote:﻿Nothing tricky here. We have --leave-state which leaves states on stop (which is first part of restart): I don’t think this is correct. We never do any total flush of policy and states in Pluto. The leave-state option ONLY sets the error code for Pluto and this part did the actual work.So until we add “flush states/policy on startup” we cannot remove this.On start we flush states anyway. So there is no problem.

**Comment by cagney** [comment]
#1284  #1285

**Comment by cagney** [comment]
(offline discussion) the magic line should go; and so should the exit code.
