### ISSUE TITLE
_unbound-hook should be less risky

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#136]
`programs/_unbound-hook/_unbound-hook` seems insufficiently defensive about its use of arguments.

`argv[3]` `argv[1]` in particular appear to be vulnerable to shell expansion due to the use of python's `commands` module.

it would be better to avoid use of the shell entirely, by passing these arguments as pythonic lists.

**Comment by letoams** [comment]
changed, but note that permissions can be as weak as long as the unbound user can write the /run/pluto/pluto.ctl socket
