### ISSUE TITLE
_unbound-hook uses but does not define `pubkey`

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#137]
`programs/_unbound-hook/_unbound-hook` makes use of a variable named `pubkey` but it is not declared anywhere.

There is a commented out pair of lines that show maybe where it was supposed to come from at some point:
```
#	rr = argv[4]
#	pref, gwtype, algo, gw, pubkey = rr.split(" ")
```
but even if uncommented, they don't work if `argv[4]` is not supplied, and `pubkey` is used whether or not `argv[4]` is present.

**Comment by letoams** [comment]
fixed
