### ISSUE TITLE
3DES_CBC (192), HMAC_MD5, MODP1024 refused

### ISSUE THREAD

**Issue by pipehappy1** [libreswan/libreswan#141]
Hi, there

I try to configure the L2TP client on a TL-R483G to connect to a remote vpn server with libreswam but get error saying:

```
Oakley Transform [3DES_CBC (192), HMAC_MD5, MODP1024] refused
Oakley Transform [3DES_CBC (192), HMAC_SHA1, MODP1024] refused
```

More log can be found https://github.com/hwdsl2/setup-ipsec-vpn/issues/282

Please shade some light upon this issue, thank you!

**Comment by bleve** [comment]
HMAC_MD5 and MODP1024 both are considered insecure and not enabled on default configuration. 
If you configure TL-R483G to use diffie-hellman group 5 (MODP1536) with sha1 you still get connected.

Default configuration won't allow md5 or modp1024 or any combinations using those.

**Comment by pipehappy1** [comment]
Thanks for the quick response. Probably I should have the box shipped back...

**Comment by pipehappy1** [comment]
@bleve one more question. I don't see 3DES_CBD in wiki's FAQ section. Is this also an exotic cipher?

**Comment by pipehappy1** [comment]
nvm. It seems 3DES_CBC is popular. Thank you @bleve

**Comment by letoams** [comment]
You have a mismatching configuration. One end wants 3des-md5 and the other end does not. It’s recommended to configure both ends for at least aes-sha1. This is true for Ike= and esp= lines.

**Comment by pipehappy1** [comment]
@letoams Thanks for the follow up. it seems that the temporary solution would put these weak ciphers on remote box, which runs with libreswan and later replace the dumb route...
