### ISSUE TITLE
The rpmdev-spectool used with "make git-rpm" does not exist yet on RHEL8.

### ISSUE THREAD

**Issue by bradyallenjohnson** [libreswan/libreswan#1416]
It appears that the "make git-rpm" "rpmdev-spectool" tool no longer exists, as can be seen in the following output.

```
$ make git-rpm
...
rpmdev-spectool --get-files /home/tombrady/rpmbuild/SPECS/libreswan.spec --directory /home/tombrady/rpmbuild/SOURCES;
/bin/sh: rpmdev-spectool: command not found
make: *** [Makefile:147: git-rpm] Error 127
```

This is observed on RHEL 8.8

```
$ more /etc/redhat-release 
Red Hat Enterprise Linux release 8.8 (Ootpa)
```

As a workaround for this, i simply replaced the call to "rpmdev-spectool" with "spectool" in the root-level Makefile. But, Im not sure how well this will work on all rpm-based platforms. On my Fedora-39 laptop, "/usr/bin/spectool" is a symbolic link to "/usr/bin/rpmdev-spectool".

Questions:

1. What versions of RHEL are used in the Libreswan testing lab?
2. Should I simply replace the call to "rpmdev-spectool" with "spectool" in the root-level Makefile, or add some logic to the Makefile to try to use "rpmdev-spectool" and if it does not exist use "spectool" instead?

**Comment by letoams** [comment]
Yeah just replace it. Thanks !

**Comment by bradyallenjohnson** [comment]
> rpmdev-spectool should be available there too.

Where should it also be available?

**Comment by bleve** [comment]
rhel8 - it's standard part of rpmdevtools - it is the actual command, spectool should be just an alias.

**Comment by bleve** [comment]
I'm checking history - it's possible name was changed later to rpmdevtools-spectool and old distros still use old name.

**Comment by bleve** [comment]
Yes. Name was changed at rpmdevtools-9.0 from spectool to rpmdev-spectool

**Comment by bleve** [comment]
But because there is compatibility symlink it's ok to change name for now.

**Comment by bradyallenjohnson** [comment]
Ok, here is the Pull Request:
https://github.com/libreswan/libreswan/pull/1417
