### ISSUE TITLE
Netkey manages left/rightsourceip

### ISSUE THREAD

**Issue by ensc** [libreswan/libreswan#142]
[_updown.netkey](https://github.com/libreswan/libreswan/blob/master/programs/_updown.netkey/_updown.netkey.in) implements the functions `addsource` + `delsource`.  This must be removed or be made  optionally because:

* the operation system contains much more powerful functionality to setup ip addresses than the simple `ip addr add` in `addsource`.  Effectively, `addsource` is a noop on most installation and might create some warnings only when ip already exists

* `delsource` breaks installations where the sourceip is used by other parts/daemons of the system.  E.g. when shutting down `pluto`, the sourceip is removed too rendering other daemons (sshd) unreachable.

So, please do not manage the ip address itself.  Assume that it is owned and setup by the operation system.

I do not know when this functionality has been added and how many installations rely on `addsource` (setting up the sourceip).  When added recently, it should be no problem to remove these two functions from the script.  Else, some way must be added to disable it.

https://bugzilla.redhat.com/show_bug.cgi?id=1492501 describes this issue too (the `delsource` part).  For me, libreswan-3.15 on CentOS 7.3 worked fine and libreswan-3.20 on CentOS 7.4 breaks systems because IPs are removed on restart.

**Comment by bleve** [comment]
addsource and delsource are important pieces of functionality and can't be removed.

This issue has already been resolved upstream.

**Comment by ensc** [comment]
ok thanks;  I see that recent script checks whether ip is used in some other route.  It is only a problem in RHEL 7 which ships libreswan-3.20

**Comment by letoams** [comment]
rhel-7.5 will ship libreswan 3.22+
