### ISSUE TITLE
auto=keep causes behaviour like auto=start - and it shouldn't revive more than once.

### ISSUE THREAD

**Issue by bleve** [libreswan/libreswan#1427]
auto=keep has been broken. It should only try to get tunnel up once, not forever like it does now.

auto=keep semi-roadwarrior config now continues to revive connection forever. And another problem from this is that road warrior, coming back with different ip address can't reconnect because it gets INVALID_TS response.

**Comment by cagney** [comment]
related #1003

**Comment by cagney** [comment]
> auto=keep has been broken. It should only try to get tunnel up once, not forever like it does now.

While arguably broken behaviour, I can't find code in v4.x that would cause it to back off.
More details are also needed.  Is this for an instance or permanent?

> auto=keep semi-roadwarrior config now continues to revive connection forever. And another problem from this is that road warrior, coming back with different ip address can't reconnect because it gets INVALID_TS response.

This looks like an unrelated problem?

**Comment by bleve** [comment]
This is road warrior config with permanent subnet. Network behind mobile router config. And ip is just dynamic 4G/5G. work-around for the issue is to change to auto=add on vpn-gateway. So in gateway config it is right=%any connection with permanent network and id.

**Comment by letoams** [comment]
On Tue, 28 Nov 2023, cagney wrote:

>       auto=keep has been broken. It should only try to get tunnel up once, not forever like it does now.
> 
> While arguably broken behaviour, I can't find code in v4.x that would cause it to back off.
> More details are also needed. Is this for an instance or permanent?
>
>       auto=keep semi-roadwarrior config now continues to revive connection forever. And another problem from this is that road
>       warrior, coming back with different ip address can't reconnect because it gets INVALID_TS response.

The auto=keep behaviour is intended to only be attempted for a short
(30s?) time. And is only meant to work around rekey failures and
idle timeouts of the peer behind NAT. So if the initial initiation
triggered by "keep" causes a failure for whatever reason, the
connection should go back to auto=add state.

**Comment by cagney** [comment]
No dispute about what should happen.  Is it a v4.x->v5.x regression though?

Looking at v4.3:

`delete_state() called `add_revival_if_needed()` unconditionally.  That included code to:
```
	if (c->kind == CK_INSTANCE && c->sa_keying_tries == 0) {
		dbg("limiting instance revival attempts to 2 keyingtries");
		c->sa_keying_tries = 2;
	}
```
so that `retransmit_v2_msg()` would make two aggressive attempts at `ipsecdoi_replace()` i.e., initiate.  After that it would call delete_state() which called `add_revival_if_needed()` which ...

Perhaps there was code elsewhere that deleted the connection?
