### ISSUE TITLE
load_setup: Assertion `kw->keyword.keydef->validity & kv_config' failed

### ISSUE THREAD

**Issue by PanderMusubi** [libreswan/libreswan#145]
On Ubuntu Xenial (longsleep for PINE64) there is no openswan package. So I build it manually:
    sudo su
    apt-get install xl2tpd libgmp-dev bison flex build-essential ipsec-tools
    make programs install
    # do configuration
    /etc/init.d/ipsec restart
    Aborted (core dumped)
    failed to start openswan IKE daemon - the following error occured:
    addconn: /home/ubuntu/Downloads/openswan-2.6.50/lib/libipsecconf/confread.c:276: load_setup: Assertion `kw->keyword.keydef->validity & kv_config' failed.

How do I fix this? I'm not so familiar with these packages. Do I need to install certain other packages and is rebuilding needed?

**Comment by PanderMusubi** [comment]
Apperently, I got an very old version. Didn't see that. Will try the latest and close this issue if needed.

**Comment by letoams** [comment]
Use libreswan, not openswan. Libreswan is in Debian unstable if you want to grab the package from there.

Openswan was obsoleted by libreswan in 2012: https://nohats.ca/wordpress/libreswan/
