### ISSUE TITLE
It looks like a bug where IKEv2 with multiple subnets

### ISSUE THREAD

**Issue by yuhaiyang** [libreswan/libreswan#146]
Linux Libreswan 3.23dr1 (netkey) on 2.6.32-696.10.1.el6.x86_64

The site of Santa clara: 

> conn ali_sh
                type=tunnel
                authby=secret
                encapsulation=yes
                left=%defaultroute
                leftsubnets=10.66.0.0/16,192.168.2.0/24
                leftid=@usawest.tac
                right=x.x.x.x
                rightsubnets=10.0.0.0/8,192.168.1.0/24
                rightid=@sh.tac
                ikev2=insist
                ike=3des-sha1,3des-sha2,aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024,aes256-sha2_512
                phase2alg=3des-sha1,3des-sha2,aes-sha1,aes-sha2,aes256-sha2_512;modp1024
                auto=start

The site of Shanghai:

> conn ali_usa_west
                type=tunnel 
                authby=secret 
                encapsulation=yes
                left=%defaultroute 
                leftsubnets=10.0.0.0/8,192.168.1.0/24
                leftid=@sh.tac
                right=x.x.x.x
                rightsubnets=10.66.0.0/16,192.168.2.0/24
                rightid=@usawest.tac
                ikev2=insist
                ike=3des-sha1,3des-sha2,aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024,aes256-sha2_512
                phase2alg=3des-sha1,3des-sha2,aes-sha1,aes-sha2,aes256-sha2_512;modp1024
                auto=start

When I started ipsec service, it's work fine.
But Santa crala site  ping unreachable to the network 10.0.0.0/8 of  Shanghai site after running a period of time(about 680 minutes), and Santa crala site  ping reachable to the network 192.168.1.0/8 of  Shanghai site also.
IPSec status is Ok

> ipsec status | grep ===    
000 "ali_sh/1x1": 10.66.0.0/16===192.168.2.79[@usawest.tac]---192.168.2.253...x.x.x.x<x.x.x.x>[@sh.tac]===10.0.0.0/8; erouted; eroute owner: #576
000 "ali_sh/1x2": 10.66.0.0/16===192.168.2.79[@usawest.tac]---192.168.2.253...x.x.x.x<x.x.x.x>[@sh.tac]===192.168.1.0/24; erouted; eroute owner: #573
000 "ali_sh/2x1": 192.168.2.0/24===192.168.2.79[@usawest.tac]---192.168.2.253...x.x.x.x<x.x.x.x>[@sh.tac]===10.0.0.0/8; erouted; eroute owner: #575
000 "ali_sh/2x2": 192.168.2.0/24===192.168.2.79[@usawest.tac]---192.168.2.253...x.x.x.x<x.x.x.x>[@sh.tac]===192.168.1.0/24; erouted; eroute owner: #574

And I restarted ipsec service, it's workd fine all.

**Comment by letoams** [comment]
Do you have logs to see what happened ?

**Comment by yuhaiyang** [comment]
sorry, I don't know what logs you need.

> logfile=/var/log/pluto.log
plutodebug="all private"

"all + private" is ok?

**Comment by libreswan** [comment]
never send "private" since that only contains private session keys and secrets, but "all" is good (and excludes private)

**Comment by testdev4** [comment]
I just fall into the same trap. Seems like that libreswan trying to compare left and right subnets, I mean that this configuration is incorrect:
`leftsubnets=10.176.12.0/23`
`rightsubnets={10.122.133.0/24 10.122.224.1/32}`
Also have tried to use comma and semicolon as separator without "{ }" but no luck.
Subnets must be defined like this:
`leftsubnets={10.176.12.0/24 10.176.13.0/24}`
`rightsubnets={10.122.133.0/24 10.122.224.1/32}`

**Comment by letoams** [comment]
the parser gets confused. Not the subnetS parser but the generic parser sees:

    option=value, value

and it rejects that. You can use quotes if you want to use spaces:

 rightsubnets="10.122.133.0/24 10.122.224.1/32"

I'm looking into making the parser allow this

**Comment by letoams** [comment]
hmm, it is documented in the man page:

        A value may contain white space only if the entire value is
       enclosed in double quotes ("); a value cannot itself contain a double
       quote, nor may it be continued across more than one line.

**Comment by bleve** [comment]
I don't think that's worth changing.

**Comment by letoams** [comment]
ok. I added a warning to the man page for leftsubnets=
