### ISSUE TITLE
ipsec showhostkey man pages for newhostkey and showhostkey are out of date.

### ISSUE THREAD

**Issue by rthille** [libreswan/libreswan#147]
Since 3.18, the --file option to showhostkey is no longer available.
Further, the 'newhostkey' subcommand doesn't enforce  `--output <file>` being required so it's possible to create a key which the pluto daemon can't find when it comes time to negotiate the connection.

**Comment by letoams** [comment]
fixed. thanks for pointing out. note --output is no longer needed. see ipsec showhostkey --list to find raw keys
