### ISSUE TITLE
Build failed - Linux kernel 4.14.4 / GCC 7.2.0  

### ISSUE THREAD

**Issue by Pierre-A3i** [libreswan/libreswan#148]
With linux kernel 4.14.4 ( may be since 4.11 ):
ln -s -f /usr/src/libreswan-release-3.23/linux/net/ipsec/ipsec_tunnel.c** /usr/src/libreswan-release-3.23/modobj/ipsec_tunnel.c
  CC [M]  /usr/src/libreswan-release-3.23/modobj/ipsec_tunnel.o
/usr/src/libreswan-release-3.23/modobj/ipsec_tunnel.c: In function âipsec_tunnel_initâ:
/usr/src/libreswan-release-3.23/modobj/ipsec_tunnel.c:2041:7: error: âstruct net_deviceâ has no member named âdestructorâ; did you mean âpriv_destructorâ?
  dev->destructor         = free_netdev;
       ^~~~~~~~~~
       priv_destructor
make[3]: *** [scripts/Makefile.build:315: /usr/src/libreswan-release-3.23/modobj/ipsec_tunnel.o] Error 1
make[2]: *** [Makefile:1503: _module_/usr/src/libreswan-release-3.23/modobj] Error 2
make[2]: Leaving directory '/usr/src/linux-4.14.4'
make[1]: *** [Makefile:448: module26] Error 2
make[1]: Leaving directory '/usr/src/libreswan-release-3.23'
make: *** [Makefile:339: module] Error 2

and with GCC 7.2.0:
make -C /lib/modules/4.14.4-171212/build  BUILDDIR=/usr/src/libreswan-release-3.23/modobj SUBDIRS=/usr/src/libreswan-release-3.23/modobj
INITSYSTEM=sysvinit MODULE_DEF_INCLUDE=/usr/src/libreswan-release-3.23/packaging/linus/config-all.h
MODULE_DEFCONFIG=/usr/src/libreswan-release-3.23/linux/net/ipsec/defconfig  MODULE_EXTRA_INCLUDE= ARCH=i386 V= modules
make[2]: Entering directory '/usr/src/linux-4.14.4'
  CC [M]  /usr/src/libreswan-release-3.23/modobj/sysctl_net_ipsec.o
/usr/src/libreswan-release-3.23/modobj/sysctl_net_ipsec.c:291:4: error: positional initialization of field in â structâ  declared with
â designated_initâ  attribute [-Werror=designated-init]
  { 0 }
    ^
/usr/src/libreswan-release-3.23/modobj/sysctl_net_ipsec.c:291:4: note: (near initialization for â ipsec_table[17]â<96> )
/usr/src/libreswan-release-3.23/modobj/sysctl_net_ipsec.c:313:4: error: positional initialization of field in â structâ  declared with
â designated_initâ  attribute [-Werror=designated-init]
  { 0 }
    ^
/usr/src/libreswan-release-3.23/modobj/sysctl_net_ipsec.c:313:4: note: (near initialization for â ipsec_net_table[1]â )
/usr/src/libreswan-release-3.23/modobj/sysctl_net_ipsec.c:329:4: error: positional initialization of field in â structâ  declared with
â designated_initâ  attribute [-Werror=designated-init]
  { 0 }
    ^

Files modified ( for my system ) in diff file.
[libreswan-3.23.diff.zip](https://github.com/libreswan/libreswan/files/1547716/libreswan-3.23.diff.zip)

**Comment by libreswan** [comment]
merged a patch based on this that uses ipsec_kversion.h
Thanks!
