### ISSUE TITLE
"USE_LABELED_IPSEC?=true" in "mk/defaults/linux.mk"

### ISSUE THREAD

**Issue by Pierre-A3i** [libreswan/libreswan#149]
"USE_LABELED_IPSEC?=true" in "mk/defaults/linux.mk" overwrite "USE_LABELED_IPSEC" value in "mk/config.mk" and should be remove.

"USE_LABELED_IPSEC" must be "false" on Slackware ( no SElinux )  and config file now unusable.

About config file, with the "LDNS" new requirement, "mk/config.mk" should be updated:

"# Enable support for DNSSEC. This requires the unbound library"
USE_DNSSEC?=true

"# Enable support for DNSSEC. This requires the unbound and ldns libraries"
USE_DNSSEC?=true

**Comment by bleve** [comment]
That is intentional. On linux, USE_LABELED_IPSEC=true is default.

To override on build time, use

make USE_LABELED_IPSEC=false programs

**Comment by Pierre-A3i** [comment]
Ok, thanks, but "mk/config.mk" with:

# Enable Labeled IPsec Functionality (requires SElinux)
ifeq ($(OSDEP),linux)
USE_LABELED_IPSEC?=true
else
USE_LABELED_IPSEC?=false
endif

... could be better, because not all Linux have "SElinux" ( such as Slackware distrib ), and  "config.mk" should be the config file for any Linux.
You don't think so ?

**Comment by letoams** [comment]
On Wed, 13 Dec 2017, Pierre-A3i wrote:

> ifeq ($(OSDEP),linux)
> USE_LABELED_IPSEC?=true
> else
> USE_LABELED_IPSEC?=false
> endif
> 
> ... could be better, because not all Linux have "SElinux" ( such as Slackware distrib ), and "config.mk" should be the config
> file for any Linux.
> You don't think so ?

We try to make config files that suit most linux distributions. If yours
is different, you will have to make small tweaks in your build
environment. For example with rpm, there are conditionals in the spec
file that can be enabled/disabled.

Paul

**Comment by Pierre-A3i** [comment]
Not a problem for me now. It was just confuse at the begging, before I see the default "linux.mk" file.
May be a comment about this could be great for others, because this changed since release 3.20.
For me, it's solved, thanks.
