### ISSUE TITLE
IKEv2 liveness does not work with IP change

### ISSUE THREAD

**Issue by wofferl** [libreswan/libreswan#1492]
If the peers ip address changes, the ip address for ikev2 liveness is updated, but no new connection is established.

`Dec 18 15:44:57.980424: | NAT: MOBKIE: updating remote sender from 10.0.11.249:4500 -> 10.0.11.250:4500 as non-MOBIKE or non-INFORMATIONAL`

Data packets are discarded because they now came from the new ip address and the policies stay with the old address.

```
#4: "fedora2"[2] 10.0.11.249 esp.83ffd321@10.0.11.249 esp.c7b1b6dd@10.0.12.63 tun.0@10.0.11.249 tun.0@10.0.12.63 Traffic: ESPin=0B ESPout=0B ESPmax=2^63B
```

ip xfrm policy
```
src 192.168.151.0/24 dst 192.168.152.0/24
        dir out priority 1757392 ptype main
        tmpl src 10.0.12.63 dst 10.0.11.249
                proto esp reqid 16397 mode tunnel
        if_id 0x1
src 192.168.152.0/24 dst 192.168.151.0/24
        dir fwd priority 1757392 ptype main
        tmpl src 10.0.11.249 dst 10.0.12.63
                proto esp reqid 16397 mode tunnel
        if_id 0x1
src 192.168.152.0/24 dst 192.168.151.0/24
        dir in priority 1757392 ptype main
        tmpl src 10.0.11.249 dst 10.0.12.63
                proto esp reqid 16397 mode tunnel
        if_id 0x1
```

traffic dump with the ip change at No. 19 and ongoing liveness checks with the new ip address.
```
No.     Time    Source  Destination     Protocol        Length  Info
1       2023-12-18 15:44:39,698839      10.0.11.249     10.0.12.63      ISAKMP  758     IKE_SA_INIT MID=00 Initiator Request
2       2023-12-18 15:44:39,743127      10.0.12.63      10.0.11.249     ISAKMP  290     IKE_SA_INIT MID=00 Responder Response
3       2023-12-18 15:44:39,760559      10.0.11.249     10.0.12.63      ISAKMP  475     IKE_AUTH MID=01 Initiator Request
4       2023-12-18 15:44:39,946227      10.0.12.63      10.0.11.249     ISAKMP  271     IKE_AUTH MID=01 Responder Response
5       2023-12-18 15:44:42,955927      10.0.11.249     10.0.12.63      ISAKMP  103     INFORMATIONAL MID=02 Initiator Request
6       2023-12-18 15:44:42,959212      10.0.12.63      10.0.11.249     ISAKMP  103     INFORMATIONAL MID=02 Responder Response
11      2023-12-18 15:44:45,961261      10.0.11.249     10.0.12.63      ISAKMP  103     INFORMATIONAL MID=03 Initiator Request
12      2023-12-18 15:44:45,968626      10.0.12.63      10.0.11.249     ISAKMP  103     INFORMATIONAL MID=03 Responder Response
13      2023-12-18 15:44:48,966134      10.0.11.249     10.0.12.63      ISAKMP  103     INFORMATIONAL MID=04 Initiator Request
14      2023-12-18 15:44:48,970123      10.0.12.63      10.0.11.249     ISAKMP  103     INFORMATIONAL MID=04 Responder Response
15      2023-12-18 15:44:51,971835      10.0.11.249     10.0.12.63      ISAKMP  103     INFORMATIONAL MID=05 Initiator Request
16      2023-12-18 15:44:51,980072      10.0.12.63      10.0.11.249     ISAKMP  103     INFORMATIONAL MID=05 Responder Response
17      2023-12-18 15:44:54,976347      10.0.11.249     10.0.12.63      ISAKMP  103     INFORMATIONAL MID=06 Initiator Request
18      2023-12-18 15:44:54,981896      10.0.12.63      10.0.11.249     ISAKMP  103     INFORMATIONAL MID=06 Responder Response
19      2023-12-18 15:44:57,977702      10.0.11.250     10.0.12.63      ISAKMP  103     INFORMATIONAL MID=07 Initiator Request
20      2023-12-18 15:44:57,980678      10.0.12.63      10.0.11.250     ISAKMP  103     INFORMATIONAL MID=07 Responder Response
21      2023-12-18 15:45:00,983469      10.0.11.250     10.0.12.63      ISAKMP  103     INFORMATIONAL MID=08 Initiator Request
22      2023-12-18 15:45:00,986656      10.0.12.63      10.0.11.250     ISAKMP  103     INFORMATIONAL MID=08 Responder Response
23      2023-12-18 15:45:03,988876      10.0.11.250     10.0.12.63      ISAKMP  103     INFORMATIONAL MID=09 Initiator Request
24      2023-12-18 15:45:03,992705      10.0.12.63      10.0.11.250     ISAKMP  103     INFORMATIONAL MID=09 Responder Response
27      2023-12-18 15:45:06,993540      10.0.11.250     10.0.12.63      ISAKMP  103     INFORMATIONAL MID=10 Initiator Request
28      2023-12-18 15:45:06,996676      10.0.12.63      10.0.11.250     ISAKMP  103     INFORMATIONAL MID=10 Responder Response
```

Is this intended, or should there be an exception for updating the ip addresses for the INFORMATIONAL liveness packets?

**Comment by cagney** [comment]
Which version?
I suspect it should only update the port.

**Comment by cagney** [comment]
Looking at v3.13's `nat_traversal_change_port_lookup()`, it has:
```
		/*
		 * If source port/address has changed, update (including other
		 * states and established kernel SA)
		 */
		if (st->st_remoteport != md->sender_port ||
			!sameaddr(&st->st_remoteaddr, &md->sender)) {

			nat_traversal_new_mapping(st, &md->sender,
						md->sender_port);
		}
```
it's always been updating the address; hmm

**Comment by wofferl** [comment]
> Which version? I suspect it should only update the port.

Actual git version:
Libreswan v5.0rc1-main

**Comment by wofferl** [comment]
```
          /*
             * Only when the local IKE SA isn't behind NAT but the
             * remote IKE SA is ...
             */
            !LHAS(ike->sa.hidden_variables.st_nat_traversal, NATED_HOST) &&
            LHAS(ike->sa.hidden_variables.st_nat_traversal, NATED_PEER)) {
                /*
                 * Things are looking plausible.
                 */
                if (ike->sa.st_ike_sent_v2n_mobike_supported &&
                    ike->sa.st_ike_seen_v2n_mobike_supported &&
                    md->hdr.isa_xchg == ISAKMP_v2_INFORMATIONAL) {
                        /*
                         * Only when MOBIKE has not been negotiated ...
                         */
                        endpoint_buf sb, mb;
                        dbg("NAT: MOBIKE: skipping remote sender from %s -> %s as MOBIKE delt with it in informational code(?)",
                            str_endpoint(&ike->sa.st_remote_endpoint, &sb),
                            str_endpoint(&md->sender, &mb));
                } else {
                        endpoint_buf sb, mb;
                        dbg("NAT: MOBKIE: updating remote sender from %s -> %s as non-MOBIKE or non-INFORMATIONAL",
                            str_endpoint(&ike->sa.st_remote_endpoint, &sb),
                            str_endpoint(&md->sender, &mb));
                        ike->sa.st_remote_endpoint = md->sender;
                }
```
From this code I think it's ok for "normal" INFORMATIONAL packets to change the ip and answer it, but for the liveness it seems contrapoductive.

**Comment by cagney** [comment]
> From this code I think it's ok for "normal" INFORMATIONAL packets to change the ip and answer it, but for the liveness it seems contrapoductive.

Right.  And some variation on this code has been there for a long long time - at least as far back as v3.13.

Without mobike, or some address fiddling, I'm struggling to see when updating the address is ever valid after IKE_AUTH.

**Comment by cagney** [comment]
b773fdb807939eda94e7baa353f66f8b4696124f looks to have copied IKEv1 code

**Comment by wofferl** [comment]
Could ignoring incoming liveness requests from different ip be a solution.

This works for me: 
```
diff --git a/programs/pluto/ikev2_informational.c b/programs/pluto/ikev2_informational.c
index 9361c7f066..df8fba1b11 100644
--- a/programs/pluto/ikev2_informational.c
+++ b/programs/pluto/ikev2_informational.c
@@ -220,8 +220,13 @@ stf_status process_v2_INFORMATIONAL_request(struct ike_sa *ike,
         * Only count empty requests as liveness probes.
         */
        if (md->chain[ISAKMP_NEXT_v2SK]->payload.v2gen.isag_np == ISAKMP_NEXT_NONE) {
-               dbg("received an INFORMATIONAL liveness check request");
-               pstats_ike_dpd_replied++;
+               if(!endpoint_eq_endpoint(ike->sa.st_remote_endpoint, md->sender)) {
+                       dbg("ignoring INFORMATIONAL liveness check request");
+                       return STF_IGNORE;
+               } else {
+                       dbg("received an INFORMATIONAL liveness check request");
+                       pstats_ike_dpd_replied++;
+               }
        }
 
        return STF_OK;

```

**Comment by letoams** [comment]
On Mon, 18 Dec 2023, Wolfgang wrote:

> Could ignoring incoming liveness requests from different ip be a solution.

Note that liveness is an INFORMATIONAL exchange, and MOBIKE needs to be
able to send INFORMATIONAL messages over different IPs to test the path.
There is an exception in the code to allow for this traffic from the
non-real IKE IP address. Perhaps this feature is related to the bug with
liveness?

> This works for me:
> 
> diff --git a/programs/pluto/ikev2_informational.c b/programs/pluto/ikev2_informational.c
> index 9361c7f066..df8fba1b11 100644
> --- a/programs/pluto/ikev2_informational.c
> +++ b/programs/pluto/ikev2_informational.c
> @@ -220,8 +220,13 @@ stf_status process_v2_INFORMATIONAL_request(struct ike_sa *ike,
>          * Only count empty requests as liveness probes.
>          */
>         if (md->chain[ISAKMP_NEXT_v2SK]->payload.v2gen.isag_np == ISAKMP_NEXT_NONE) {
> -               dbg("received an INFORMATIONAL liveness check request");
> -               pstats_ike_dpd_replied++;
> +               if(!endpoint_eq_endpoint(ike->sa.st_remote_endpoint, md->sender)) {
> +                       dbg("ignoring INFORMATIONAL liveness check request");
> +                       return STF_IGNORE;

So this would break the above mentioned MOBIKE probes.

**Comment by wofferl** [comment]
That was my first working attempt, to exclude the liveness packet where the IP change is made. Than mobike will not be touched. 
But here I'm not sure if the query md->chain[ISAKMP_NEXT_v2SK]->payload.v2gen.isag_np is valid for all packets, and if md->chain[ISAKMP_NEXT_v2SK] can also be NULL.

```
diff --git a/programs/pluto/ikev2.c b/programs/pluto/ikev2.c
index d61b92ccff..f253b598cf 100644
--- a/programs/pluto/ikev2.c
+++ b/programs/pluto/ikev2.c
@@ -2476,7 +2476,11 @@ static void success_v2_state_transition(struct ike_sa *ike,
                        dbg("NAT: MOBIKE: skipping remote sender from %s -> %s as MOBIKE delt with it in informational code(?)",
                            str_endpoint(&ike->sa.st_remote_endpoint, &sb),
                            str_endpoint(&md->sender, &mb));
-               } else {
+               } else if (!(md->hdr.isa_xchg == ISAKMP_v2_INFORMATIONAL &&
+                            md->chain[ISAKMP_NEXT_v2SK]->payload.v2gen.isag_np == ISAKMP_NEXT_NONE)) {
+                       /*
+                        * ignore IKEv2 liveness packets
+                        */
                        endpoint_buf sb, mb;
                        dbg("NAT: MOBKIE: updating remote sender from %s -> %s as non-MOBIKE or non-INFORMATIONAL",
                            str_endpoint(&ike->sa.st_remote_endpoint, &sb),
```

**Comment by wofferl** [comment]
> So this would break the above mentioned MOBIKE probes.

I have tested both patches with mobike. There seems no problem with that.

The mobike part is already done in process_v2_INFORMATIONAL_request before doing the check at the end of this function. 
Therefore with mobike the connection is already update to the new ip and ike->sa.st_remote_endpoint is already set to md->sender before the check at the end of the function.

Here the log from an incoming mobike change request, with the patch
[ipsec-mobike.log](https://github.com/libreswan/libreswan/files/13714300/ipsec-mobike.log)

**Comment by cagney** [comment]
```
Date:   Thu Jul 26 01:05:13 2007 -0500

    revisions to NAT-T processing to deal with IP address changes
    (as detected by pluto) and implement them properly.
    Test case nat-pluto-07 attempts to test this, but does not perform
    the proper NAT functions.
```

**Comment by cagney** [comment]
https://community.cisco.com/t5/security-knowledge-base/how-does-nat-t-work-with-ipsec/ta-p/3119442

As best I can tell, the original code should have checked the addresses matched.  And then only updated the port.

**Comment by cagney** [comment]
I think this:
```
	    /*
	     * Only when the request changes the remote's endpoint ...
	     */
	    !endpoint_eq_endpoint(ike->sa.st_remote_endpoint, md->sender) &&
```
should be changed to check for same address but different port

**Comment by cagney** [comment]
@wofferl just FYI

> But here I'm not sure if the query md->chain[ISAKMP_NEXT_v2SK]->payload.v2gen.isag_np is valid for all packets

further back there's:

```
	    ike->sa.hidden_variables.st_skeyid_calculated &&
	    md->encrypted_payloads.parsed &&
	    md->encrypted_payloads.n == v2N_NOTHING_WRONG &&
```

which only holds when SK is present; but a NULL check never hurts.

**Comment by cagney** [comment]
Just an aside.  There's nothing special about IKEv2 liveness probes.  If there's going to be an update it should be triggered by any packet.

**Comment by cagney** [comment]
Try https://github.com/cagney/libreswan/tree/wip/1492

**Comment by wofferl** [comment]
> Try https://github.com/cagney/libreswan/tree/wip/1492

Shouldn't it be:
```
diff --git a/programs/pluto/ikev2.c b/programs/pluto/ikev2.c
index 34da062084..d344462c2c 100644
--- a/programs/pluto/ikev2.c
+++ b/programs/pluto/ikev2.c
@@ -2446,7 +2446,7 @@ static void success_v2_state_transition(struct ike_sa *ike,
            address_eq_address(endpoint_address(ike->sa.st_remote_endpoint),
                               endpoint_address(md->sender)) &&
            endpoint_protocol(ike->sa.st_remote_endpoint) == endpoint_protocol(md->sender) &&
-           port_eq(endpoint_port(ike->sa.st_remote_endpoint), endpoint_port(md->sender)) &&
+           !port_eq(endpoint_port(ike->sa.st_remote_endpoint), endpoint_port(md->sender)) &&
            /*
             * Only when the request was protected and passes
             * integrity ...
```

This fixed the problem on ip change, but you still have the same problem when you have an unexpected change of the NAT port, however likely that is, that the liveness packets are successful sent to the new port, but the data packets still sent to the old one and is therefore not working.


IKEv2 liveness:
```
10:49:07.470110 IP (tos 0x0, ttl 63, id 26592, offset 0, flags [DF], proto UDP (17), length 89)
    10.0.11.237.1027 > 10.0.12.63.4500: NONESP-encap: isakmp 2.0 msgid 00000014: child_sa  inf2[I]:
    (v2e: len=25)
10:49:07.472936 IP (tos 0x0, ttl 64, id 59256, offset 0, flags [DF], proto UDP (17), length 89)
    10.0.12.63.4500 > 10.0.11.237.1027: NONESP-encap: isakmp 2.0 msgid 00000014: child_sa  inf2[R]:
    (v2e: len=25)
```

Data packet:
```
10:49:12.818300 IP (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto UDP (17), length 148)
    10.0.11.237.1027 > 10.0.12.63.4500: UDP-encap: ESP(spi=0xa1a149ee,seq=0x3b), length 120
10:49:12.818707 IP (tos 0x0, ttl 64, id 21386, offset 0, flags [none], proto UDP (17), length 148)
    10.0.12.63.4500 > 10.0.11.237.4500: UDP-encap: ESP(spi=0x4265dd4f,seq=0x3b), length 120
```

**Comment by cagney** [comment]
Reading https://datatracker.ietf.org/doc/html/rfc7296#section-2.23

**Comment by cagney** [comment]
My take is that libreswan should:

- also check that "replay protection" is enabled (what ever that means)
- also check it's a tunnel
- update the SA like for mobike

**Comment by letoams** [comment]
MOn Dec 21, 2023, at 15:43, cagney ***@***.***> wrote:﻿
My take is that libreswan should:

also check that "replay protection" is enabled (what ever that means)
also check it's a tunnel
update the SA like for mobike


I thought there kernel automatically updated the NAT mapping if it got changed on us? It might even send a netlink msg. If we don’t have a testcase we should make one.I don’t understand the replay protection part.I think technically transport mode in UDP should also work but if it doesn’t we shouldn’t put effort in to fix it. But the above check for tunnel mode prob should not be added—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by cagney** [comment]
Marking this 5.1.
To me, for 5.0, the only practical option is to disable the code.

**Comment by cagney** [comment]
FYI,
I pushed a change to disable the feature entirely.

**Comment by cagney** [comment]
5.0 shipped with feature disabled.  Just note there's fallout:

- [ ] #1728
- [ ] #1759
