### ISSUE TITLE
pass: 753 fails: 239 from `libipsecconf: change nic-offload= defaults` missing test update?

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1517]
For instance:
```
-"modecfg-road-eastnet-psk":   nflog-group: unset; mark: unset; vti-iface:unset; vti-routing:no; vti-shared:no; nic-offload:auto;
+"modecfg-road-eastnet-psk":   nflog-group: unset; mark: unset; vti-iface:unset; vti-routing:no; vti-shared:no; nic-offload:no;
```

3be6424fb35ade0f587c1998119c967613513f3d

**Comment by cagney** [comment]
Still problems:
```
-"order-test":   nflog-group: unset; mark: unset; vti-iface:unset; vti-routing:no; vti-shared:no; nic-offload:no;
+"order-test":   nflog-group: unset; mark: unset; vti-iface:unset; vti-routing:no; vti-shared:no; nic-offload:auto;
```

**Comment by letoams** [comment]
On Mon, 8 Jan 2024, cagney wrote:

> Still problems:
> 
> -"order-test":   nflog-group: unset; mark: unset; vti-iface:unset; vti-routing:no; vti-shared:no; nic-offload:no;
> +"order-test":   nflog-group: unset; mark: unset; vti-iface:unset; vti-routing:no; vti-shared:no; nic-offload:auto;

Fixed. it was the whack default that also needed an update.
