### ISSUE TITLE
hardware packet doesn't fall back to software

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1520]
This code:
```
		bool ret = kernel_ops_add_sa(said_next, replace, st->logger);

		if (!ret && nic_offload_fallback &&
			said_next->nic_offload.dev != NULL) {
			/* Fallback to crypto offload from packet offload */
			if (said_next->nic_offload.type == OFFLOAD_PACKET) {
				said_next->nic_offload.type = OFFLOAD_CRYPTO;
				ret = kernel_ops_add_sa(said_next, replace, st->logger);
			}

			if (!ret) {
				/* Fallback to non-nic-offload crypto */
				said_next->nic_offload.dev = NULL;
				ret = kernel_ops_add_sa(said_next, replace, st->logger);
			}
		}
```
performs the fallbacks:

- CRYPTO->software
- PACKET->CRYPTO

but not PACKET->...->software; should it?

**Comment by cagney** [comment]
Nope, I'm wrong.

**Comment by letoams** [comment]
On Tue, 9 Jan 2024, cagney wrote:

> performs the fallbacks:
>
>  *  CRYPTO->software
>  *  PACKET->CRYPTO
> 
> but not PACKET->...->software; should it?

Yes. I have test cases and code I'm finishing up to fix this and
add proper whack/logging.

That is, nic-offload=auto should do fallbacks, setting packet or
crypto specifically should cause no fallback and failure.

Once we get a little more confidence and experience, hopefully
we can enable auto by default.

**Comment by cagney** [comment]
The problem's actually in `setup_esp_nic_offload()`:
```
	if (c->config->nic_offload == NIC_OFFLOAD_AUTO) {
             ...
	}
	nic_offload->dev = c->iface->real_device_name;
	nic_offload->type = (c->config->nic_offload == NIC_OFFLOAD_PACKET) ?
				KERNEL_OFFLOAD_PACKET : KERNEL_OFFLOAD_CRYPTO;
```
notice how NIC_OFFLOAD_AUTO implies KERNEL_OFFLOAD_CRYPTO; so packet is never tried.

**Comment by letoams** [comment]
> On Jan 9, 2024, at 14:43, cagney ***@***.***> wrote:
> 
> ﻿
> The problem's actually in setup_esp_nic_offload():
> 
> 
> notice how NIC_OFFLOAD_AUTO implies KERNEL_OFFLOAD_CRYPTO; so packet is never tried.
> 

Yes which is why I had changed it to a switch() in by pending patch.

But I think it was done this way because the first failure would be for packet, so the second failure is for crypto which internally seems to fall back to software.

See the added ikev2-26-* test cases

Paul

**Comment by paulwouters** [comment]
auto or fallback is no longer supported due to complexities
