### ISSUE TITLE
conflicting offload kernel policy and state

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1522]
Pluto enables offload when adding both kernel state and kernel policy.  However, only the state path contains logic to fallback.

Prior to a7b6806930f7a2c49e6a2eeb36f3d922ce130494 AUTO starts with CRYPTO.  Since Linux ignores that when adding policy the setting shouldn't fail.  And the CRYPTO->SOFTWARE fallback when adding states can work.

Now, with AUTO starting with POLICY that is no longer true.  The kernel will try to add packet offload to the policy, fail, and presumably abort the operation.

**Comment by paulwouters** [comment]
We no longer support auto, so this issue is no longer present
