### ISSUE TITLE
a failing offload bypasses code zeroing key

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1523]
a7b6806930f7a2c49e6a2eeb36f3d922ce130494 added
```
		if (!ret && !cno)
			goto fail;
```
it has the effect of bypassing:
```
		/* scrub keys from memory */
		memset(esp_keymat.ptr, 0, esp_keymat.len);
```
hopefully the key gets scrubbed when the memory is freeed.

**Comment by letoams** [comment]
On Wed, 10 Jan 2024, cagney wrote:

> a7b6806 added
>
> 		if (!ret && !cno)
> 			goto fail;
> 
> it has the effect of bypassing:
>
> 		/* scrub keys from memory */
> 		memset(esp_keymat.ptr, 0, esp_keymat.len);

Maybe that should go into the fail: path then?

> hopefully the key gets scrubbed when the memory is freeed.

Well, it was also never used by either end to encrypt packets,
but I agree it would be better to clear it anyway.

**Comment by cagney** [comment]
7db75995d0b24edf320fcca0a99c5d9522f14f67 removed the code
