### ISSUE TITLE
archlinux; cant install/compile libreswan

### ISSUE THREAD

**Issue by fiercebrake** [libreswan/libreswan#1539]
Hey guys!

When I try to install via AUR, i get the following error:

`a - libreswan_exit.o
/home/fierce_brake/.cache/pikaur/build/libreswan/src/libreswan-4.12/programs/pluto/plutomain.c: In function ‘main’:
/home/fierce_brake/.cache/pikaur/build/libreswan/src/libreswan-4.12/programs/pluto/plutomain.c:1724:9: error: ignoring return value of ‘capng_apply’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
 1724 |         capng_apply(CAPNG_SELECT_BOTH);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [../../mk/rules.mk:63: plutomain.o] Error 1
make[2]: *** [../../mk/targets.mk:82: all] Error 2
make[1]: *** [../mk/targets.mk:82: recursive-all] Error 2
make: *** [/home/fierce_brake/.cache/pikaur/build/libreswan/src/libreswan-4.12/mk/targets.mk:82: recursive-all] Error 2
==> ERROR: A failure occurred in build().
/usr/share/makepkg/util/message.sh: line 51: QUIET: unbound variable
/usr/bin/makepkg: line 131: logpipe: unbound variable
`

And when I try to compile myself, I get the following one
`SE_VFORK=0 -DUSE_DAEMON=0 -DUSE_PTHREAD_SETSCHEDPRIO=1 -DGCC_LINT -DHAVE_LIBCAP_NG \
	-I../../OBJ.linux.x86_64.yugen/lib/libswan -I../../include -I/usr/include/nss -I/usr/include/nspr \
	-DHERE_FILENAME=\"/lib/libswan/unbound.c\" \
	 \
	-MF ../../OBJ.linux.x86_64.yugen/lib/libswan/unbound.d \
	-MP -MMD -MT unbound.o \
	-o ../../OBJ.linux.x86_64.yugen/lib/libswan/unbound.o \
	-c /home/fierce_brake/Downloads/libreswan-4.12/lib/libswan/unbound.c
/home/fierce_brake/Downloads/libreswan-4.12/lib/libswan/unbound.c:34:10: fatal error: unbound-event.h: No such file or directory
   34 | #include <unbound-event.h>      /* see USE_UNBOUND_EVENT_H_COPY */
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [../../mk/rules.mk:63: unbound.o] Error 1
make[2]: *** [../../mk/targets.mk:82: all] Error 2
make[2]: Leaving directory '/home/fierce_brake/Downloads/libreswan-4.12/lib/libswan'
make[1]: *** [../mk/targets.mk:82: recursive-all] Error 2
make[1]: Leaving directory '/home/fierce_brake/Downloads/libreswan-4.12/lib'
make: *** [/home/fierce_brake/Downloads/libreswan-4.12/mk/targets.mk:82: recursive-all] Error 2
`

any ideas as to what I should be doing in this one?

**Comment by letoams** [comment]
On Mon, 15 Jan 2024, David Valiente wrote:

> When I try to install via AUR, i get the following error:
> 
> [../mk/targets.mk:82: recursive-all] Error 2 make: *** [/home/fierce_brake/.cache/pikaur/build/libreswan/src/libreswan-4.12/mk/targets.mk:82:
> recursive-all] Error 2 ==> ERROR: A failure occurred in build(). /usr/share/makepkg/util/message.sh: line 51: QUIET: unbound variable /usr/bin/makepkg:
> line 131: logpipe: unbound variable

We will have to fix this.

> And when I try to compile myself, I get the following one

> /home/fierce_brake/Downloads/libreswan-4.12/lib/libswan/unbound.c:34:10: fatal error: unbound-event.h: No such file or directory 34 | #include

Your unbound dev(el) package is not installed or missing this essential
include file. Older versions of unbound on fedora/debian mistakenly
did not install this file (because upstream make install didn't install it)

Paul

**Comment by fiercebrake** [comment]
> Make sure libunbound is build with --enable-libevent-api and --with-libevent

@bleve 
Thanks for the tip.
I did manually build libonbound using './configure --enable-event-api --with-libevent'
I am now getting a different error

`/home/fierce_brake/Downloads/libreswan-4.12/programs/pluto/plutomain.c: In function ‘main’:
/home/fierce_brake/Downloads/libreswan-4.12/programs/pluto/plutomain.c:1724:9: error: ignoring return value of ‘capng_apply’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
 1724 |         capng_apply(CAPNG_SELECT_BOTH);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [../../mk/rules.mk:63: plutomain.o] Error 1
make[2]: *** [../../mk/targets.mk:88: install] Error 2
make[2]: Leaving directory '/home/fierce_brake/Downloads/libreswan-4.12/programs/pluto'
make[1]: *** [../mk/targets.mk:88: recursive-install] Error 2
make[1]: Leaving directory '/home/fierce_brake/Downloads/libreswan-4.12/programs'
make: *** [/home/fierce_brake/Downloads/libreswan-4.12/mk/targets.mk:88: recursive-install] Error 2`


Any ideas as to how should I go about that?

**Comment by letoams** [comment]
On Mon, 15 Jan 2024, David Valiente wrote:

> Thanks for the tip.
> I did manually build libonbound using './configure --enable-event-api --with-libevent'
> I am now getting a different error
> 
> /home/fierce_brake/Downloads/libreswan-4.12/programs/pluto/plutomain.c: In function ‘main’:
> /home/fierce_brake/Downloads/libreswan-4.12/programs/pluto/plutomain.c:1724:9: error: ignoring return value of ‘capng_apply’ declared with attribute
> ‘warn_unused_result’ [-Werror=unused-result] 1724 | capng_apply(CAPNG_SELECT_BOTH); | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ cc1: all warnings being treated as

commit ba5bad09f55959872022fa506d5ac06eafe3a314
Author: Paul Wouters ***@***.***>
Date:   Tue Sep 5 22:49:28 2023 -0400

     pluto: check return code of libcap-ng functions

     Avoids "error: ignoring return value of ‘capng_apply’ ..."

Either apply this commit or grab the latest 5.0 Release Candidate from https://download.libreswan.org/development/

**Comment by fiercebrake** [comment]
@letoams 

Thank you! that worked!

closing incident now

Thank you for your time and guidance! hope you have a great one ahead!
