### ISSUE TITLE
confirm current default proposal set for IKEv2 is what we want to ship for 5.0

### ISSUE THREAD

**Issue by paulwouters** [libreswan/libreswan#1558]
Specifically also which DH we prefer. MODP2048 or ECP256 ?

**Comment by paulwouters** [comment]
Make ECP_256 the default DH
Add ChachaPoly to ESP and IKE

**Comment by paulwouters** [comment]
reverse order of MODP group to prefer stronger ones first

**Comment by cagney** [comment]
currently it is:
```
$ ./OBJ.linux.x86_64/programs/algparse/algparse ike esp ah
algparse -v2 'ike'
	AES_GCM_16_256-HMAC_SHA2_512+HMAC_SHA2_256-MODP2048+MODP3072+MODP4096+MODP8192+DH19+DH20+DH21+DH31
	AES_GCM_16_128-HMAC_SHA2_512+HMAC_SHA2_256-MODP2048+MODP3072+MODP4096+MODP8192+DH19+DH20+DH21+DH31
	AES_CBC_256-HMAC_SHA2_512+HMAC_SHA2_256-MODP2048+MODP3072+MODP4096+MODP8192+DH19+DH20+DH21+DH31
	AES_CBC_128-HMAC_SHA2_512+HMAC_SHA2_256-MODP2048+MODP3072+MODP4096+MODP8192+DH19+DH20+DH21+DH31
algparse -v2 'esp'
	AES_GCM_16_256-NONE
	AES_GCM_16_128-NONE
	AES_CBC_256-HMAC_SHA2_512_256+HMAC_SHA2_256_128
	AES_CBC_128-HMAC_SHA2_512_256+HMAC_SHA2_256_128
algparse -v2 'ah'
	HMAC_SHA2_512_256
	HMAC_SHA2_256_128
	HMAC_SHA1_96
```
for ike, this is built from ike_info.c vis:
```
static const char default_v2_ike_proposals[] =
	"AES_GCM_16_256"
	","
	"AES_GCM_16_128"
	","
	"AES_CBC_256"
	","
	"AES_CBC_128"
	;

static const struct ike_alg *default_v2_ike_prfs[] = {
#ifdef USE_SHA2
	&ike_alg_prf_sha2_512.common,
	&ike_alg_prf_sha2_256.common,
#endif
	NULL,
};

static const struct ike_alg *default_v2_groups[] = {
	&ike_alg_dh_modp2048.common,
	&ike_alg_dh_modp3072.common,
	&ike_alg_dh_modp4096.common,
	&ike_alg_dh_modp8192.common,
	&ike_alg_dh_secp256r1.common,
	&ike_alg_dh_secp384r1.common,
	&ike_alg_dh_secp521r1.common,
#ifdef USE_DH31
	&ike_alg_dh_curve25519.common,
#endif
	NULL,
};
```

**Comment by cagney** [comment]
> Make ECP_256 the default DH
> reverse order of MODP group to prefer stronger ones first

stronger is unfortunately vague; the current list is above

> Add ChachaPoly to ESP and IKE

where, relative to AES_GCM?

**Comment by letoams** [comment]
On Wed, 7 Feb 2024, cagney wrote:

>       Make ECP_256 the default DH
>       reverse order of MODP group to prefer stronger ones first

It was meant as ECP_256, ECP_384, ECP_512, MODP4096, MODP3172, MODP2048, MODP8192

> stronger is unfortunately vague; the current list is above
>
>       Add ChachaPoly to ESP and IKE
> 
> where, relative to AES_GCM?

After AES_GCM-256 and after AES_GCM-128

**Comment by bleve** [comment]
Should we even include MODP8192 - I have never seen it used.

**Comment by bleve** [comment]
Hmh. Actually  suggested order looks good - we leave dh18 as last one.

**Comment by letoams** [comment]
On Wed, 7 Feb 2024, cagney wrote:

> $ ./OBJ.linux.x86_64/programs/algparse/algparse ike esp ah
> algparse -v2 'ike'
> 	AES_GCM_16_256-HMAC_SHA2_512+HMAC_SHA2_256-MODP2048+MODP3072+MODP4096+MODP8192+DH19+DH20+DH21+DH31

My proposal to move DH's moved to DH19+DH20+DH21+DH31+MODP4096+MODP3072+MODP2048+MODP8192
I personally have no strong preference of DH19 (ECP_256) over DH31
(Curve25519) but I suspect a LOT more systems support DH19 than DH31, so
this choice seems more likely to avoid INVALID_KE responses for picking
the wrong KE guess.

> 	AES_GCM_16_128-HMAC_SHA2_512+HMAC_SHA2_256-MODP2048+MODP3072+MODP4096+MODP8192+DH19+DH20+DH21+DH31
> 	AES_CBC_256-HMAC_SHA2_512+HMAC_SHA2_256-MODP2048+MODP3072+MODP4096+MODP8192+DH19+DH20+DH21+DH31
> 	AES_CBC_128-HMAC_SHA2_512+HMAC_SHA2_256-MODP2048+MODP3072+MODP4096+MODP8192+DH19+DH20+DH21+DH31

Same for tehse.

> algparse -v2 'esp'
> 	AES_GCM_16_256-NONE
> 	AES_GCM_16_128-NONE
> 	AES_CBC_256-HMAC_SHA2_512_256+HMAC_SHA2_256_128
> 	AES_CBC_128-HMAC_SHA2_512_256+HMAC_SHA2_256_128

Add ChaChaPoly after GCM but before CBC

> algparse -v2 'ah'
> 	HMAC_SHA2_512_256
> 	HMAC_SHA2_256_128
> 	HMAC_SHA1_96

Remove SHA1.

**Comment by letoams** [comment]
On Wed, 7 Feb 2024, Tuomo Soini wrote:

> Should we even include MODP8192 - I have never seen it used.

I think some governments do, which is why I proposed it, but at the very very end.
I could be convinced to drop it from the defaults.

**Comment by cagney** [comment]
```
$ ./OBJ.linux.x86_64/programs/algparse/algparse ike esp ah
algparse -v2 'ike'
	AES_GCM_16_256-HMAC_SHA2_512+HMAC_SHA2_256-DH19+DH20+DH21+MODP4096+MODP3072+MODP2048+MODP8192+DH31
	AES_GCM_16_128-HMAC_SHA2_512+HMAC_SHA2_256-DH19+DH20+DH21+MODP4096+MODP3072+MODP2048+MODP8192+DH31
	CHACHA20_POLY1305-HMAC_SHA2_512+HMAC_SHA2_256-DH19+DH20+DH21+MODP4096+MODP3072+MODP2048+MODP8192+DH31
	AES_CBC_256-HMAC_SHA2_512+HMAC_SHA2_256-DH19+DH20+DH21+MODP4096+MODP3072+MODP2048+MODP8192+DH31
	AES_CBC_128-HMAC_SHA2_512+HMAC_SHA2_256-DH19+DH20+DH21+MODP4096+MODP3072+MODP2048+MODP8192+DH31
algparse -v2 'esp'
	AES_GCM_16_256-NONE
	AES_GCM_16_128-NONE
	CHACHA20_POLY1305-NONE
	AES_CBC_256-HMAC_SHA2_512_256+HMAC_SHA2_256_128
	AES_CBC_128-HMAC_SHA2_512_256+HMAC_SHA2_256_128
algparse -v2 'ah'
	HMAC_SHA2_512_256
	HMAC_SHA2_256_128
```

**Comment by cagney** [comment]
```
$ ./OBJ.linux.x86_64/programs/algparse/algparse ike esp ah
algparse -v2 'ike'
	AES_GCM_16_256-HMAC_SHA2_512+HMAC_SHA2_256-DH19+DH20+DH21+DH31+MODP4096+MODP3072+MODP2048+MODP8192
	AES_GCM_16_128-HMAC_SHA2_512+HMAC_SHA2_256-DH19+DH20+DH21+DH31+MODP4096+MODP3072+MODP2048+MODP8192
	CHACHA20_POLY1305-HMAC_SHA2_512+HMAC_SHA2_256-DH19+DH20+DH21+DH31+MODP4096+MODP3072+MODP2048+MODP8192
	AES_CBC_256-HMAC_SHA2_512+HMAC_SHA2_256-DH19+DH20+DH21+DH31+MODP4096+MODP3072+MODP2048+MODP8192
	AES_CBC_128-HMAC_SHA2_512+HMAC_SHA2_256-DH19+DH20+DH21+DH31+MODP4096+MODP3072+MODP2048+MODP8192
algparse -v2 'esp'
	AES_GCM_16_256-NONE
	AES_GCM_16_128-NONE
	CHACHA20_POLY1305-NONE
	AES_CBC_256-HMAC_SHA2_512_256+HMAC_SHA2_256_128
	AES_CBC_128-HMAC_SHA2_512_256+HMAC_SHA2_256_128
algparse -v2 'ah'
	HMAC_SHA2_512_256
	HMAC_SHA2_256_128
```

**Comment by cagney** [comment]
b378b6da5e3b58fce112165c2b0687ec6b5c8390
59105aa3b55e29cada8b044e18008059b832b55b
768a6b99d6fa9f87a589837d63aac582a0e90e7d
