### ISSUE TITLE
debug log shows clashing vendor id's

### ISSUE THREAD

**Issue by paulwouters** [libreswan/libreswan#1559]
eg:

| Vendor ID 'Openswan(project)' and 'Openswan 2.2.0' clash

**Comment by cagney** [comment]
The message is misleading, it should say "share a prefix", for instance in:
```
| Vendor IDs 'Openswan(project)' and 'Libreswan (3.6+)' have a common prefix
|   64 Openswan(project)  substring
|      4f 45 [OE]
|   68 Libreswan (3.6+)  substring
|      4f 45 2d 4c  69 62 72 65  73 77 61 6e  2d [OE-Libreswan-]
```
notice how both of these Vendor IDs start with `4f 45`.  The Vendor ID `OE-10` would match the first while `OE-Libreswan-10` matches the second.
