### ISSUE TITLE
nsrun should return non-zero for failing test

### ISSUE THREAD

**Issue by paulwouters** [libreswan/libreswan#1561]
that will help automate git bisects

**Comment by cagney** [comment]
best practice is:
```
git bisect ./kvm install check result tesing/pluto/basic-pluto-01
```
it's documented here https://libreswan.org/wiki/Test_Suite_-_KVM#Tracking_down_regressions_.28using_git_bisect.29

A test script failure indicates that the test framework failed, not the result of individual tests.
