### ISSUE TITLE
Please fix the man page(s) on https://libreswan.org/man/

### ISSUE THREAD

**Issue by systemcrash** [libreswan/libreswan#158]
Might include others, but many words include unformatted junk:

https://libreswan.org/man/pluto.8.html

IKE\*(Aqs Job
->
IKE's Job

We call this situation (lqRoad Warrior(rq

should be:

We call this situation 'Road Warrior'

When the responder doesn*(Aqt recognize
...
When the responder doesn't recognize

if it has %any for the peer*(Aqs IP address)
...
if it has %any for the peer's IP address)

**Comment by systemcrash** [comment]
other strings:

and and the connection specified no identity
->
and the connection specified no identity


pluto will be receive an Identity Payload
->
pluto will receive an Identity Payload

 which would use the same keys so-far used
->
 which would use the same keys so far used

using this better connection (or a temporary derived from this
->
using this better connection (or a temporary one derived from this

RSA Signature authentications does not require that the responder know how 
->
RSA Signature authentication does not require that the responders know how

**Comment by systemcrash** [comment]
Here's [PR](https://github.com/libreswan/libreswan/pull/159) with above fixes

**Comment by letoams** [comment]
weird. the PR also does not fix these *(Aqs strings. For some reason the conversion tool changes "'s" to "*(Aqs".....

**Comment by cagney** [comment]
This issue's been obsoleted by #685
