### ISSUE TITLE
fix documentation; `pluto --config` has no defaults

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1592]
The documentation for ipsec-pluto(8) claims:

_The following option overide the location of configuration files:_
_`--config filename` the configuration file
Default is <filename>@@IPSEC_CONF@@</filename>._

except, pluto instead only reads the config file when --config is specified (or at least appears to).  Instead init scripts give the appearance of this behaviour by explicitly and always specifying --config.

(addconn since this is ipsec.conf)

**Comment by letoams** [comment]
On Wed, 31 Jan 2024, cagney wrote:

> Subject: [libreswan/libreswan] add `pluto --no-config`, really read config file by default (Issue #1592)

> The following option overide the location of configuration files:
> --config filename the configuration file
> Default is @@IPSEC_CONF@@.

The design was that pluto can be started without configuration file.
What are the arguments for changing this now?

I guess the argument is most distros ship with /etc/ipsec.conf and use
it. It is rare to see pluto started without configuration file.

Note that it needs to take into account to not require --no-config when
we run pluto with --selftest or --version.

I think it should also continue to start if the default config file is
not present and not abort starting up.

**Comment by cagney** [comment]
On IRC we've decided the bug is in the documentation:

- ipsec-pluto(8) should describe above mechanism
- libreswan(7) should describe how distros configure things, that is start pluto with --config

another hangover from the old ipsec-pluto(8) trying to document too much
