### ISSUE TITLE
drop `glob(GLOB_BRACE)`

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1593]
To follow up a986f9676f5b58a908610d2b483be2faa7139f22, 3bcc0de0d62a707cf8c7453e5b2124baa82fe66b, ebffa1ddc232741d1f081e1ca37aed7d7f3b3b76 I think the thing to do is drp GLOB_BRACE support.

In v4.x, ipsec.conf allows brace expansion which means that both:
```
include /etc/ipsec.d/*.conf
include /etc/ipsec.d/{a,b,c}.conf
```
are valid.  But ipsec.secrets the unbound trust anchors only allow the simple form:
```
include ipsec.*.secrets
```
I think we should pick one, and my suggestion is to ignore braces.  This would break any existing ipsec.conf that used braces (but to be honest, does anyone do anything other than the supplied `include /etc/ipsec.d/*.conf`?

**Comment by letoams** [comment]
On Thu, 1 Feb 2024, cagney wrote:

> I think we should pick one, and my suggestion is to ignore braces. This would break any existing ipsec.conf
> that used braces (but to be honest, does anyone do anything other than the supplied include
> /etc/ipsec.d/*.conf?

Fine with me. I don't know anyone ever used anything else but *.conf or customer*.conf

**Comment by cagney** [comment]
Pushed
