### ISSUE TITLE
ESN in proposal line is unclear.

### ISSUE THREAD

**Issue by paulwouters** [libreswan/libreswan#1601]
currently shows:

 1:ESP=AES_GCM_C_128+AES_GCM_C_256-NONE-MODP2048-ENABLED+DISABLED

better would be:

 1:ESP=AES_GCM_C_128+AES_GCM_C_256-NONE-MODP2048-ESN_YES+ESN_NO

change ikev2_trans_type_esn_name[] = {
        "ESN_DISABLED",
        "ESN_ENABLED",
};

Maybe change to ESN_YES/ESN_NO there ?

**Comment by cagney** [comment]
pushed
