### ISSUE TITLE
"passthrough": route-client output: need at least a destination address

### ISSUE THREAD

**Issue by paulwouters** [libreswan/libreswan#1607]
passthrough should work without needing a destination address. Seems a bug in updown?

eg:

```
conn passthrough
    left=127.0.0.1
    right=%any
    leftsubnet=10.0.1.0/24
    rightsubnet=10.0.1.0/24
    authby=never
    type=passthrough
    auto=route

```

**Comment by bleve** [comment]
That has nothing to do with updown - actually updown is not used at all by default for this.

left=127.0.0.1
right=0.0.0.0

works just fine.

**Comment by paulwouters** [comment]
root@fedora:/etc/ipsec.d# cat p.conf 
conn passthrough
    left=127.0.0.1
    #right=%any
    right=0.0.0.0
    leftsubnet=10.0.1.0/24
    rightsubnet=10.0.1.0/24
    authby=never
    type=passthrough
    auto=route

root@fedora:/etc/ipsec.d# ipsec add passthrough
"passthrough": unroute-client output: need at least a destination address
"passthrough": added passthrough connection
root@fedora:/etc/ipsec.d# ipsec route passthrough
"passthrough": route-client output: need at least a destination address
"passthrough": route-client output: need at least a destination address

**Comment by paulwouters** [comment]
note to clarify, the passthrough works. the spd policies are added to the kernel.
It is just the warning that should not happen

**Comment by bleve** [comment]
Fix for warning is to add leftupdown=%disabled - updown can't fix this issue.

**Comment by paulwouters** [comment]
fixed by 81fa930d8935ed

**Comment by cagney** [comment]
```
	if (never_negotiate(c)) {
		ldbg(logger, "kernel: skipped updown %s command - not needed for never_negotiate connections", verb);
		return true;
	}
```
Why does a never_negotiate() connection have an updown script?

**Comment by bleve** [comment]
Because we have default to have leftupdown="ipsec _updown" and rightupdown="ipsec _updown"

**Comment by cagney** [comment]
only because addconn hardwires it; that isn't needed
