### ISSUE TITLE
suppress `no secrets filename matched "/etc/ipsec.d/*.secrets"`?

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1627]
There's code for ipsec.conf to supress the warning about `/etc/ipsec.d/*.conf` not finding anything.  Should secrets be the same?

**Comment by letoams** [comment]
On Fri, 23 Feb 2024, cagney wrote:

> There's code for ipsec.conf to supress the warning about /etc/ipsec.d/*.conf not finding anything. Should
> secrets be the same?

Fine with me.

**Comment by cagney** [comment]
pushed
