### ISSUE TITLE
3.23 build failure w/ glibc 2.25 and kernel 4.9.76

### ISSUE THREAD

**Issue by doctaweeks** [libreswan/libreswan#165]
This appears similar to issue #121 but with a longterm kernel. I have not had time to dig into it yet.

>-c /var/tmp/portage/net-vpn/libreswan-3.23/work/libreswan-3.23/programs/pluto/pluto_seccomp.c
> In file included from /var/tmp/portage/net-vpn/libreswan-3.23/work/libreswan-3.23/programs/pluto/linux-copy/linux/xfrm.h:4:0,
>                  from /var/tmp/portage/net-vpn/libreswan-3.23/work/libreswan-3.23/programs/pluto/kernel_netlink.c:55:
> /usr/include/linux/in6.h:33:8: error: redefinition of ‘struct in6_addr’
>  struct in6_addr {
>         ^~~~~~~~
> In file included from /var/tmp/portage/net-vpn/libreswan-3.23/work/libreswan-3.23/linux/include/libreswan.h:76:0,
>                  from /var/tmp/portage/net-vpn/libreswan-3.23/work/libreswan-3.23/programs/pluto/kernel_netlink.c:54:
> /usr/include/netinet/in.h:211:8: note: originally defined here
>  struct in6_addr
>         ^~~~~~~~
> In file included from /var/tmp/portage/net-vpn/libreswan-3.23/work/libreswan-3.23/programs/pluto/linux-copy/linux/xfrm.h:4:0,
>                  from /var/tmp/portage/net-vpn/libreswan-3.23/work/libreswan-3.23/programs/pluto/kernel_netlink.c:55:
> /usr/include/linux/in6.h:50:8: error: redefinition of ‘struct sockaddr_in6’
>  struct sockaddr_in6 {
>         ^~~~~~~~~~~~
> In file included from /var/tmp/portage/net-vpn/libreswan-3.23/work/libreswan-3.23/linux/include/libreswan.h:76:0,
>                  from /var/tmp/portage/net-vpn/libreswan-3.23/work/libreswan-3.23/programs/pluto/kernel_netlink.c:54:
> /usr/include/netinet/in.h:252:8: note: originally defined here
>  struct sockaddr_in6
>         ^~~~~~~~~~~~
> In file included from /var/tmp/portage/net-vpn/libreswan-3.23/work/libreswan-3.23/programs/pluto/linux-copy/linux/xfrm.h:4:0,
>                  from /var/tmp/portage/net-vpn/libreswan-3.23/work/libreswan-3.23/programs/pluto/kernel_netlink.c:55:
> /usr/include/linux/in6.h:60:8: error: redefinition of ‘struct ipv6_mreq’
>  struct ipv6_mreq {
>         ^~~~~~~~~
> In file included from /var/tmp/portage/net-vpn/libreswan-3.23/work/libreswan-3.23/linux/include/libreswan.h:76:0,
>                  from /var/tmp/portage/net-vpn/libreswan-3.23/work/libreswan-3.23/programs/pluto/kernel_netlink.c:54:
> /usr/include/netinet/in.h:288:8: note: originally defined here
>  struct ipv6_mreq

**Comment by letoams** [comment]
On Wed, 7 Feb 2018, Daniel M. Weeks wrote:

> This appears similar to issue #121 but with a longterm kernel. I have not had time to dig into it yet.

You can fix this using:

diff --git a/programs/pluto/kernel_netlink.c
b/programs/pluto/kernel_netlink.c
index 8cec3a2..a2500f4 100644
--- a/programs/pluto/kernel_netlink.c
+++ b/programs/pluto/kernel_netlink.c
@@ -51,8 +51,8 @@
  #include <linux/if_addr.h>
  #include <linux/if_link.h>

-#include "libreswan.h" /* before xfrm.h otherwise break on F22 */
  #include "linux/xfrm.h" /* local (if configured) or system copy */
+#include "libreswan.h" /* before xfrm.h otherwise break on F22 */

  #include "libreswan/pfkeyv2.h"
  #include "libreswan/pfkey.h"


our problem is, doing this will break it for older glibc/kernels :(

Paul

**Comment by doctaweeks** [comment]
Thanks. Interestingly this is not a problem with Linux kernel 4.12 (dead branch) or 4.14 (longterm).

**Comment by letoams** [comment]
We have an option you can set in Makefile.inc (or Makefile.inc.local) to tweak this:

USE_GLIBC_KERN_FLIP_HEADERS=true  (or false, but that's the default)
