### ISSUE TITLE
Executing 'ipsec whack --listen' every five minutes, the Linux system hangs up, showing no response 

### ISSUE THREAD

**Issue by z1006409356** [libreswan/libreswan#1650]
Executing 'ipsec whack --listen' every five minutes causes the Linux system to hang up with no response, including an unresponsive keyboard.
 The reason for executing 'ipsec whack --listen' every five minutes is to establish access between two nodes if the configuration time of the public IP is later than the time of the IPsec listening IP.

When the node hangs up, the Pluto logs are as follows: 
![image](https://github.com/libreswan/libreswan/assets/43293221/6ccd6132-ec5a-416b-ad26-e994a070d248)
the normal logging every 5 minutes can no longer be observed

Before the system hang-up, the stack trace information captured a few times is as follows:
![image](https://github.com/libreswan/libreswan/assets/43293221/181e9e80-5aa0-4210-93b0-ec4703a1e86d)

**Comment by letoams** [comment]
> On Mar 15, 2024, at 12:52, z1006409356 ***@***.***> wrote:
> 
> Executing 'ipsec whack --listen' every five minutes causes the Linux system to hang up with no response, including an unresponsive keyboard.
> The reason for executing 'ipsec whack --listen' every five minutes is to establish access between two nodes if the configuration time of the public IP is later than the time of the IPsec listening IP.
> 

I am not sure executing whack is causing your issue, as your issue shows a kernel crash in the IPsec subsystem.

I suggest you try to email ***@***.*** list and ask there.
