### ISSUE TITLE
Reduce dependencies from libsystemd when only using sd_notify

### ISSUE THREAD

**Issue by paulwouters** [libreswan/libreswan#1673]
Similar to this patch https://src.fedoraproject.org/rpms/openssh/pull-request/72

This avoids linking to badly maintained libraries like xz / liblzma.so

**Comment by cagney** [comment]
The stub contains `sd_notify()` but not ` sd_watchdog_enabled()`?

**Comment by cagney** [comment]
pushed everywhere
