### ISSUE TITLE
Bug - Libreswan 3.2x/master with Linux kernel 4.14.x

### ISSUE THREAD

**Issue by Pierre-A3i** [libreswan/libreswan#170]
![kp-4 14 34](https://user-images.githubusercontent.com/34443850/38893737-7db3c196-428b-11e8-9f40-5915296c905e.jpg)

Hi, 
Libreswan 3.2x/master are not working with Linux kernel 4.14.x and KLIPS.
Tunnel is build fine but there is no communication. The cryptographic lookup seems failed.
With  "ipsec stop / restart" I get kernel panic above.

KLIPS Debug Log ( Kernel 4.14.x):  

May  5 11:52:57 Blackbox-CRE kernel: [  583.449883] klips_info:ipsec_init: KLIPS startup, Libreswan KLIPS IPsec stack version: 3.20
May  5 11:52:57 Blackbox-CRE kernel: [  583.450081] NET: Registered protocol family 15
May  5 11:52:57 Blackbox-CRE kernel: [  583.450630] klips_info:ipsec_alg_init: KLIPS alg v=0.8.1-0 (EALG_MAX=255, AALG_MAX=255)
May  5 11:52:57 Blackbox-CRE kernel: [  583.450632] klips_info:ipsec_alg_init: calling ipsec_alg_static_init()
May  5 11:52:57 Blackbox-CRE kernel: [  583.456616] KLIPS: lookup for ciphername=cbc(aes): not found
May  5 11:52:57 Blackbox-CRE kernel: [  583.461761] KLIPS: lookup for ciphername=cbc(twofish): not found
May  5 11:52:57 Blackbox-CRE kernel: [  583.466707] KLIPS: lookup for ciphername=cbc(serpent): not found
May  5 11:52:57 Blackbox-CRE kernel: [  583.469024] KLIPS: lookup for ciphername=cbc(cast5): not found
May  5 11:52:57 Blackbox-CRE kernel: [  583.471425] KLIPS: lookup for ciphername=cbc(des3_ede): not found
May  5 11:52:57 Blackbox-CRE kernel: [  583.473854] KLIPS: lookup for ciphername=cipher_null: not found
May  5 11:52:57 Blackbox-CRE kernel: [  583.476595] KLIPS cryptoapi interface: alg_type=14 alg_id=2 name=hmac(md5) ctx_size=40 keyminbits=128 keymaxbits=128, found(0)
May  5 11:52:57 Blackbox-CRE kernel: [  583.479058] KLIPS cryptoapi interface: alg_type=14 alg_id=3 name=hmac(sha1) ctx_size=40 keyminbits=160 keymaxbits=160, found(0)
May  5 11:52:57 Blackbox-CRE kernel: [  583.481593] KLIPS cryptoapi interface: alg_type=14 alg_id=5 name=hmac(sha256) ctx_size=40 keyminbits=256 keymaxbits=256, found(0)
May  5 11:52:57 Blackbox-CRE kernel: [  583.484623] KLIPS cryptoapi interface: alg_type=14 alg_id=6 name=hmac(sha384) ctx_size=40 keyminbits=384 keymaxbits=384, found(0)
May  5 11:52:57 Blackbox-CRE kernel: [  583.487385] KLIPS cryptoapi interface: alg_type=14 alg_id=7 name=hmac(sha512) ctx_size=40 keyminbits=512 keymaxbits=512, found(0)
May  5 11:52:57 Blackbox-CRE kernel: [  583.487390] KLIPS cryptoapi interface: alg_type=14 alg_id=252 name=hmac(sha256) ctx_size=40 keyminbits=256 keymaxbits=256, found(0)

-----------------------
KLIPS Debug Log for other side ( Kernel 4.4.88 )

May  5 09:20:41 Blackbox-LYO kernel: [380105.771148] NET: Unregistered protocol family 15
May  5 09:20:41 Blackbox-LYO kernel: [380106.053760] klips_info:ipsec_init: KLIPS startup, Libreswan KLIPS IPsec stack version: 3.20
May  5 09:20:41 Blackbox-LYO kernel: [380106.053863] NET: Registered protocol family 15
May  5 09:20:41 Blackbox-LYO kernel: [380106.054568] klips_info:ipsec_alg_init: KLIPS alg v=0.8.1-0 (EALG_MAX=255, AALG_MAX=255)
May  5 09:20:41 Blackbox-LYO kernel: [380106.054570] klips_info:ipsec_alg_init: calling ipsec_alg_static_init()
May  5 09:20:41 Blackbox-LYO kernel: [380106.054587] KLIPS cryptoapi interface: alg_type=15 alg_id=12 name=cbc(aes) keyminbits=128 keymaxbits=256, found(0)
May  5 09:20:41 Blackbox-LYO kernel: [380106.054591] KLIPS cryptoapi interface: alg_type=15 alg_id=253 name=cbc(twofish) keyminbits=128 keymaxbits=256, found(0)
May  5 09:20:41 Blackbox-LYO kernel: [380106.054593] KLIPS cryptoapi interface: alg_type=15 alg_id=252 name=cbc(serpent) keyminbits=128 keymaxbits=256, found(0)
May  5 09:20:41 Blackbox-LYO kernel: [380106.054596] KLIPS cryptoapi interface: alg_type=15 alg_id=6 name=cbc(cast5) keyminbits=128 keymaxbits=128, found(0)
May  5 09:20:41 Blackbox-LYO kernel: [380106.054599] KLIPS cryptoapi interface: alg_type=15 alg_id=3 name=cbc(des3_ede) keyminbits=192 keymaxbits=192, found(0)
May  5 09:20:41 Blackbox-LYO kernel: [380106.058155] KLIPS: lookup for ciphername=cipher_null: not found
May  5 09:20:41 Blackbox-LYO kernel: [380106.058164] KLIPS cryptoapi interface: alg_type=14 alg_id=2 name=hmac(md5) ctx_size=48 keyminbits=128 keymaxbits=128, found(0)
May  5 09:20:41 Blackbox-LYO kernel: [380106.058168] KLIPS cryptoapi interface: alg_type=14 alg_id=3 name=hmac(sha1) ctx_size=48 keyminbits=160 keymaxbits=160, found(0)
May  5 09:20:41 Blackbox-LYO kernel: [380106.058171] KLIPS cryptoapi interface: alg_type=14 alg_id=5 name=hmac(sha256) ctx_size=48 keyminbits=256 keymaxbits=256, found(0)
May  5 09:20:41 Blackbox-LYO kernel: [380106.058174] KLIPS cryptoapi interface: alg_type=14 alg_id=6 name=hmac(sha384) ctx_size=48 keyminbits=384 keymaxbits=384, found(0)
May  5 09:20:41 Blackbox-LYO kernel: [380106.058177] KLIPS cryptoapi interface: alg_type=14 alg_id=7 name=hmac(sha512) ctx_size=48 keyminbits=512 keymaxbits=512, found(0)
May  5 09:20:41 Blackbox-LYO kernel: [380106.058180] KLIPS cryptoapi interface: alg_type=14 alg_id=252 name=hmac(sha256) ctx_size=48 keyminbits=256 keymaxbits=256, found(0)

-----------------------
For side with Linux 4.4.x / LS-3.22, I have this (ipsec whack --trafficstatus) : 
003 ERROR: pfkey write() of K_SADB_GET message 24 for Get SA esp.6038eeeb@81.x.x.x failed. Errno 3: No such process
003 ERROR: pfkey write() of K_SADB_GET message 25 for Get SA esp.93894083@88.x.x.x failed. Errno 3: No such process
006 #5: "a3icre", type=ESP, add_time=0, id='88.x.x.x'
003 ERROR: pfkey write() of K_SADB_GET message 26 for Get SA esp.6038eeec@81.x.x.x failed. Errno 3: No such process
003 ERROR: pfkey write() of K_SADB_GET message 27 for Get SA esp.93894084@88.x.x.x failed. Errno 3: No such process
006 #6: "a3icre", type=ESP, add_time=0, id='88.x.x.x'

-------------------------------

All build-in Cryptographic API are same in the kernels 4.4.x and 4.14.x but in the 4.14.x some seems not found. 

If anybody can help me, it's will be great, thanks.

---------------------------------

Last thing, even if "PAM=false", "/etc/pam.d/pluto" is build and installed.

**Comment by letoams** [comment]
fix for this has been merged in and will be in 3.24

**Comment by Pierre-A3i** [comment]
Thank you very much tisj.
