### ISSUE TITLE
Internet access not working when I use 10.0.100.10-10.0.100.250 as rightaddresspool

### ISSUE THREAD

**Issue by Off-TheXovius** [libreswan/libreswan#1706]
Hello, I have a problem, I cant access internet when I want to use different addresses in rightaddresspool can you please help me?
Also it is possible to set static address for each client?

Here is the configuration:

```
conn ikev2-cp
  left=%defaultroute
  leftcert=--.75.2-.-3
  leftsendcert=always
  leftsubnet=0.0.0.0/0
  leftrsasigkey=%cert
  right=%any
  rightid=%fromcert
  rightaddresspool=10.0.100.10-10.0.100.250
  rightca=%same
  rightrsasigkey=%cert
  narrowing=yes
  dpddelay=30
  retransmit-timeout=300s
  dpdaction=clear
  auto=add
  ikev2=insist
  rekey=no
  pfs=no
  ike=aes_gcm_c_256-hmac_sha2_256-ecp_256,aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
  ikelifetime=24h
  salifetime=24h
  encapsulation=yes
  leftid=--.75.2-.-3
  modecfgdns="1.1.1.1 1.0.0.1"
  mobike=yes

```

**Comment by letoams** [comment]
On Wed, 8 May 2024, x0vv0.off wrote:

> Hello, I have a problem, I cant access internet when I want to use different
> addresses in rightaddresspool can you please help me?

Can you more precisely describe the problem? How is "different
address" related to using the VPN?

> Also it is possible to set static address for each client?

Not yet.

Paul

**Comment by Off-TheXovius** [comment]
> On Wed, 8 May 2024, x0vv0.off wrote: Hello, I have a problem, I cant access internet when I want to use different addresses in rightaddresspool can you please help me?
> Can you more precisely describe the problem? How is "different address" related to using the VPN?

Well, when rightaddresspool=192.168.43.10-192.168.43.250 I can access internet when I connect but when I set rightaddresspool=10.0.100.10-10.0.100.250 I can access only clients ( 10.0.100.10-10.0.100.250 ) but I cant access internet - public services...

**Comment by letoams** [comment]
On Wed, 8 May 2024, x0vv0.off wrote:

> Well, when rightaddresspool=192.168.43.10-192.168.43.250 I can access
> internet when I connect but when I set
> rightaddresspool=10.0.100.10-10.0.100.250 I can access only clients (
> 10.0.100.10-10.0.100.250 ) but I cant access internet - public services...

You need to update/add your NAT rules to include 10.0.100.10-10.0.100.250
Libreswan does not own the NATing rules.

**Comment by Off-TheXovius** [comment]
> You need to update/add your NAT rules to include 10.0.100.10-10.0.100.250
> Libreswan does not own the NATing rules.

On Server-side or on Client-side?

**Comment by letoams** [comment]
On Wed, 8 May 2024, x0vv0.off wrote:

>       You need to update/add your NAT rules to include
>       10.0.100.10-10.0.100.250
>       Libreswan does not own the NATing rules.
> 
> On Server-side or on Client-side?

On the server side. Your client IP, eg 10.0.100.11/32 gets transported
via IPsec to the server, then send out via your server. What happens
to those packets depends on the routing tables and the NAT tables. It
has nothing to do with libreswan or IPsec.

**Comment by Off-TheXovius** [comment]
> On Wed, 8 May 2024, x0vv0.off wrote: You need to update/add your NAT rules to include 10.0.100.10-10.0.100.250 Libreswan does not own the NATing rules. On Server-side or on Client-side?
> On the server side. Your client IP, eg 10.0.100.11/32 gets transported via IPsec to the server, then send out via your server. What happens to those packets depends on the routing tables and the NAT tables. It has nothing to do with libreswan or IPsec.

Thank you very much for the help, I will setup NAT rules via IPTables on debian server, I will let you know if it works now.

**Comment by Off-TheXovius** [comment]
After `iptables -t nat -A POSTROUTING -s 10.0.100.0/24 -j MASQUERADE` it is working. Thank you.
