### ISSUE TITLE
branch 5.1 with `release-5.1`; was: tag mainline with `5.1~pre0` or ...

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1717]
this will result in the versions:
```
v5.1pre0-1-gHASH
v5.1pre0-2-gHASH
```

**Comment by cagney** [comment]
Using a hardwired 5.0 in main won't work.  Someone taking a snapshot outside of git will end up with what claims to be 5.0 when it isn't.

**Comment by cagney** [comment]
`5.1pre0` also doesn't work.  For instance:
```
$ printf '5.1\n5.1pre1\n5.1pre0\n' | sort -V
5.1
5.1pre0
5.1pre1
```
but the annoying `~` does:
```
$ printf '5.1\n5.1~1\n5.1~0\n' | sort -V
5.1~0
5.1~1
5.1
```

**Comment by bleve** [comment]
I was about to suggest 5.0~pre0

**Comment by bleve** [comment]
There is no need to have v in version tag.
