### ISSUE TITLE
ipsec multiple restarts and exits with libreswan v4.x and ikev2 on Amazon Linux 2023

### ISSUE THREAD

**Issue by Slapy06** [libreswan/libreswan#1737]
Hi,
I experience an issue when using ikev2 on an Amazon Linux 2023 with libreswan v4.12.3 and the latest v4.15 (no issue with Amazon Linux 2 with Libreswan v3.25). ipsec.service performs multiple restarts and sometimes exit suddently which cause lot of cut with my VPN tunnels. Both endpoints are libreswan.
I don't get issue with ikev1 just with ikev2. So I've rollback to ikev1 to temporary fix.

algo used are for both ikev1 & ikev2 aes256-sha256;modp2048

**Example of messages of shutting got from journalctl -u ipsec.service command:**

_Jun 11 02:17:15 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: Stopping ipsec.service - Internet Key Exchange (IKE) Protocol Daemon for IPsec...
Jun 11 02:17:15 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx whack[2402042]: 002 shutting down
Jun 11 02:17:16 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: ipsec.service: Deactivated successfully.
Jun 11 02:17:16 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: Stopped ipsec.service - Internet Key Exchange (IKE) Protocol Daemon for IPsec.
Jun 11 02:17:16 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: ipsec.service: Consumed 27min 16.650s CPU time.
Jun 11 02:17:16 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: Starting ipsec.service - Internet Key Exchange (IKE) Protocol Daemon for IPsec..._

**Example of messages of exited got from journalctl -u ipsec.service command:**

_Jun 15 16:26:29 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: ipsec.service: Main process exited, code=dumped, status=6/ABRT
Jun 15 16:26:29 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: ipsec.service: Failed with result 'core-dump'.
Jun 15 16:26:29 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: ipsec.service: Consumed 1.402s CPU time.
Jun 15 16:26:29 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: ipsec.service: Scheduled restart job, restart counter is at 2.
Jun 15 16:26:29 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: Stopped ipsec.service - Internet Key Exchange (IKE) Protocol Daemon for IPsec.
Jun 15 16:26:29 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: ipsec.service: Consumed 1.402s CPU time.
Jun 15 16:26:29 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: Starting ipsec.service - Internet Key Exchange (IKE) Protocol Daemon for IPsec...
Jun 15 16:26:29 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ipsec[1272506]: nflog ipsec capture disabled
Jun 15 16:26:29 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: Started ipsec.service - Internet Key Exchange (IKE) Protocol Daemon for IPsec._

**Example of message seen from /var/log/pluto/pluto.log:**

_Jun 10 15:06:07.080370: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" #23817: initiating IKEv2 connection
Jun 10 15:06:07.082410: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" #23817: sent IKE_SA_INIT request to xx.xx.xx.xx:500
Jun 10 15:06:07.161910: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": assign_holdpass() delete_bare_shunt() failed
Jun 10 15:06:07.161933: initiate_ondemand_body() failed to install negotiation_shunt,
Jun 10 15:06:07.161941: initiate on-demand for packet xx.xx.xx.xx:53832-TCP->xx.xx.xx.xx:9115
Jun 10 15:06:07.228803: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": assign_holdpass() delete_bare_shunt() failed
Jun 10 15:06:07.228827: initiate_ondemand_body() failed to install negotiation_shunt,
Jun 10 15:06:07.228835: initiate on-demand for packet xx.xx.xx.xx:59726-TCP->xx.xx.xx.xx:9080
Jun 10 15:06:07.574561: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" #23817: STATE_V2_PARENT_I1: retransmission; will wait 0.5 seconds for response
Jun 10 15:06:07.575361: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" #23817: ERROR: asynchronous network error report on ens5 (xx.xx.xx.xx:500), complainant xx.xx.xx.xx: Connection refused [errno 111, origin ICMP type 3 code 3 (not authenticated)]
Jun 10 15:06:07.598716: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": assign_holdpass() delete_bare_shunt() failed
Jun 10 15:06:07.598730: initiate_ondemand_body() failed to install negotiation_shunt,
Jun 10 15:06:07.598737: initiate on-demand for packet xx.xx.xx.xx:46832-TCP->xx.xx.xx.xx:9115
Jun 10 15:06:08.073699: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" #23817: STATE_V2_PARENT_I1: retransmission; will wait 1 seconds for response
Jun 10 15:06:08.074516: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" #23817: ERROR: asynchronous network error report on ens5 (xx.xx.xx.xx:500), complainant xx.xx.xx.xx: Connection refused [errno 111, origin ICMP type 3 code 3 (not authenticated)]
Jun 10 15:06:09.083130: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" #23817: STATE_V2_PARENT_I1: retransmission; will wait 2 seconds for response
Jun 10 15:06:09.083929: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" #23817: ERROR: asynchronous network error report on ens5 (xx.xx.xx.xx:500), complainant xx.xx.xx.xx: Connection refused [errno 111, origin ICMP type 3 code 3 (not authenticated)]
Jun 10 15:06:11.100995: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" #23817: STATE_V2_PARENT_I1: retransmission; will wait 4 seconds for response
Jun 10 15:06:11.101793: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" #23817: ERROR: asynchronous network error report on ens5 (xx.xx.xx.xx:500), complainant xx.xx.xx.xx: Connection refused [errno 111, origin ICMP type 3 code 3 (not authenticated)]
Jun 10 15:06:12.923976: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": assign_holdpass() delete_bare_shunt() failed
Jun 10 15:06:12.924003: initiate_ondemand_body() failed to install negotiation_shunt,
Jun 10 15:06:12.924011: initiate on-demand for packet xx.xx.xx.xx:45120-TCP->xx.xx.xx.xx:9092
Jun 10 15:06:13.206383: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": assign_holdpass() delete_bare_shunt() failed
Jun 10 15:06:13.206406: initiate_ondemand_body() failed to install negotiation_shunt,
Jun 10 15:06:13.206414: initiate on-demand for packet xx.xx.xx.xx:34474-TCP->xx.xx.xx.xx:9100
Jun 10 15:06:13.797061: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": assign_holdpass() delete_bare_shunt() failed
Jun 10 15:06:13.797087: initiate_ondemand_body() failed to install negotiation_shunt,_

Thanks in advance for your advices.
Regards,
Bernard

**Comment by cagney** [comment]
There seems to be at least two problems:

- the other end doesn't seem to be accepting packets
```
#23817: ERROR: asynchronous network error report on ens5 (xx.xx.xx.xx:500), complainant xx.xx.xx.xx: Connection refused [errno 111, origin ICMP type 3 code 3 (not authenticated)]
```

- there's a crash
```
Jun 15 16:26:29 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: ipsec.service: Main process exited, code=dumped, status=6/ABRT
Jun 15 16:26:29 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx systemd[1]: ipsec.service: Failed with result 'core-dump'.
```

Would you have a backtrace?
Would it be possible to try 5.0?

**Comment by Slapy06** [comment]
Hi,
I've tried the Libreswan v5.0 and it seems I don't get issues with this version using ikev2. I will update you next Monday.
Thanks.
Bernard

**Comment by Slapy06** [comment]
Hi @cagney ,
On my test instance, with Libreswan v5.0, I don't get ipsec.service crashes anymore using ikev2 ("systemd[1]: IPsec.service: Control process exited, code=exited, status=203/EXEC" in the pluto log, I mean). I get sometimes the following error message but it doesn't seem to generate impact:
_ERROR: asynchronous network error report on ens5 (x.x.x.x:500), complainant x.x.x.x: Connection refused [errno 111, origin ICMP type 3 code 3 (not authenticated)]_
But the remote endpoint is always up, so I don't understand why I get this...
I've created in parallel a case to AWS but they don't want to provide this Libreswan version in the Amazon Linux 2023 updates...
Regards,
Bernard

**Comment by cagney** [comment]
> ERROR: asynchronous network error report on ens5 (x.x.x.x:500), complainant x.x.x.x: Connection refused [errno 111, origin ICMP type 3 code 3 (not authenticated)]

Most likely an intermittent problem with the network.  A packet was sent to x.x.x.x:500 but the other end refused it sending back an ICMP packet.  Presumably the re-transmit of the same packet was accepted.

**Comment by cagney** [comment]
> By the way, I notice a new message in logs with Libreswan v5.0, "adding INFORMATIONAL request to IKE SA message queue". Is it a normal behavior?

It isn't unusual (in 4.x this couldn't be seen).  It can be a sign of packet loss, or an overloaded peer.  The code is trying to initiate an information exchange when there's already an exchange in flight.  Once the in-flight exchange completes things will move along.

**Comment by cagney** [comment]
We've no fixed-in-... so I guess adding it to the milestone works.

**Comment by cagney** [comment]
> I've created in parallel a case to AWS but they don't want to provide this Libreswan version in the Amazon Linux 2023 updates...

sigh, they might move when 5.1 comes out

**Comment by Slapy06** [comment]
Hi @cagney ,
Thank you very much for your support; it is really appreciated !
I'm going to get some news in my AWS case about the possible implementation of the Libreswan v5.x version. Do you know the approximate date of the availability of the v5.1? I want to test it and check the logs afterward.
