### ISSUE TITLE
Build Failure - libreswan HEAD (As of commit ID: 1f203d4cd057769d8175280b1fbcdf096175d727)

### ISSUE THREAD

**Issue by reubenfarrelly** [libreswan/libreswan#1739]
On x86_64 Gentoo Linux.  I'm guessing some commits around June 15 may have caused this:

x86_64-pc-linux-gnu-gcc -pthread -std=gnu99   -Wall -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wmissing-declarations -Wredundant-decls -Wnested-externs  -O2 -pipe -march=native -mtune=native -ggdb3 -DIPSEC_EXECDIR=\"/usr/libexec/ipsec\" -DIPSEC_SBINDIR=\"/usr/sbin\" -DIPSEC_RUNDIR=\"/run/pluto\" -DIPSEC_CONF=\"/etc/ipsec.conf\" -DIPSEC_SECRETS=\"/etc/ipsec.secrets\" -DIPSEC_CONFDDIR=\"/etc/ipsec.d\" -DIPSEC_VARDIR=\"/var\" -DIPSEC_NSSDIR=\"/var/lib/ipsec/nss\" -DNSS_BINDIR=\"/usr/bin\" -DNSS_IPSEC_PROFILE -DUSE_IKEv1 -DKERNEL_XFRM -DUSE_XFRM_INTERFACE -DXFRM_LIFETIME_DEFAULT=30 -DUSE_SECCOMP -DLIBCURL -DUSE_CAT -DUSE_NFLOG -DUSE_NFTABLES -DUSE_PAM_AUTH -DUSE_3DES -DUSE_AES -DUSE_CAMELLIA -DUSE_CHACHA -DUSE_DH31 -DUSE_MD5 -DUSE_SHA1 -DUSE_SHA2 -DUSE_PRF_AES_XCBC -DUSE_NSS_KDF -DIPSEC_SYSCONFDIR=\"/etc\" -DPOLICYGROUPSDIR=\"/etc/ipsec.d/policies\" -DFORCE_PR_ASSERT -DUSE_FORK=1 -DUSE_VFORK=0 -DUSE_DAEMON=0 -DUSE_PTHREAD_SETSCHEDPRIO=1 -DGCC_LINT -DHAVE_LIBCAP_NG \
        -I../../OBJ.linux.amd64/lib/libswan -I../../include -I/usr/include/nss -I/usr/include/nspr \
        -DHERE_FILENAME='"lib/libswan/resolve_default_route_linux.c"' \
        -O2 -pipe -march=native -mtune=native -ggdb3 \
        -MF ../../OBJ.linux.amd64/lib/libswan/resolve_default_route_linux.d \
        -MP -MMD -MT resolve_default_route_linux.o \
        -o ../../OBJ.linux.amd64/lib/libswan/resolve_default_route_linux.o \
        -c /var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/lib/libswan/resolve_default_route_linux.c
x86_64-pc-linux-gnu-gcc -pthread -std=gnu99   -Wall -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wmissing-declarations -Wredundant-decls -Wnested-externs  -O2 -pipe -march=native -mtune=native -ggdb3 -DIPSEC_EXECDIR=\"/usr/libexec/ipsec\" -DIPSEC_SBINDIR=\"/usr/sbin\" -DIPSEC_RUNDIR=\"/run/pluto\" -DIPSEC_CONF=\"/etc/ipsec.conf\" -DIPSEC_SECRETS=\"/etc/ipsec.secrets\" -DIPSEC_CONFDDIR=\"/etc/ipsec.d\" -DIPSEC_VARDIR=\"/var\" -DIPSEC_NSSDIR=\"/var/lib/ipsec/nss\" -DNSS_BINDIR=\"/usr/bin\" -DNSS_IPSEC_PROFILE -DUSE_IKEv1 -DKERNEL_XFRM -DUSE_XFRM_INTERFACE -DXFRM_LIFETIME_DEFAULT=30 -DUSE_SECCOMP -DLIBCURL -DUSE_CAT -DUSE_NFLOG -DUSE_NFTABLES -DUSE_PAM_AUTH -DUSE_3DES -DUSE_AES -DUSE_CAMELLIA -DUSE_CHACHA -DUSE_DH31 -DUSE_MD5 -DUSE_SHA1 -DUSE_SHA2 -DUSE_PRF_AES_XCBC -DUSE_NSS_KDF -DIPSEC_SYSCONFDIR=\"/etc\" -DPOLICYGROUPSDIR=\"/etc/ipsec.d/policies\" -DFORCE_PR_ASSERT -DUSE_FORK=1 -DUSE_VFORK=0 -DUSE_DAEMON=0 -DUSE_PTHREAD_SETSCHEDPRIO=1 -DGCC_LINT -DHAVE_LIBCAP_NG \
        -I../../OBJ.linux.amd64/lib/libswan -I../../include -I/usr/include/nss -I/usr/include/nspr \
        -DHERE_FILENAME='"lib/libswan/log_ip.c"' \
        -O2 -pipe -march=native -mtune=native -ggdb3 \
        -MF ../../OBJ.linux.amd64/lib/libswan/log_ip.d \
        -MP -MMD -MT log_ip.o \
        -o ../../OBJ.linux.amd64/lib/libswan/log_ip.o \
        -c /var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/lib/libswan/log_ip.c
x86_64-pc-linux-gnu-gcc -pthread -std=gnu99   -Wall -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wmissing-declarations -Wredundant-decls -Wnested-externs  -O2 -pipe -march=native -mtune=native -ggdb3 -DIPSEC_EXECDIR=\"/usr/libexec/ipsec\" -DIPSEC_SBINDIR=\"/usr/sbin\" -DIPSEC_RUNDIR=\"/run/pluto\" -DIPSEC_CONF=\"/etc/ipsec.conf\" -DIPSEC_SECRETS=\"/etc/ipsec.secrets\" -DIPSEC_CONFDDIR=\"/etc/ipsec.d\" -DIPSEC_VARDIR=\"/var\" -DIPSEC_NSSDIR=\"/var/lib/ipsec/nss\" -DNSS_BINDIR=\"/usr/bin\" -DNSS_IPSEC_PROFILE -DUSE_IKEv1 -DKERNEL_XFRM -DUSE_XFRM_INTERFACE -DXFRM_LIFETIME_DEFAULT=30 -DUSE_SECCOMP -DLIBCURL -DUSE_CAT -DUSE_NFLOG -DUSE_NFTABLES -DUSE_PAM_AUTH -DUSE_3DES -DUSE_AES -DUSE_CAMELLIA -DUSE_CHACHA -DUSE_DH31 -DUSE_MD5 -DUSE_SHA1 -DUSE_SHA2 -DUSE_PRF_AES_XCBC -DUSE_NSS_KDF -DIPSEC_SYSCONFDIR=\"/etc\" -DPOLICYGROUPSDIR=\"/etc/ipsec.d/policies\" -DFORCE_PR_ASSERT -DUSE_FORK=1 -DUSE_VFORK=0 -DUSE_DAEMON=0 -DUSE_PTHREAD_SETSCHEDPRIO=1 -DGCC_LINT -DHAVE_LIBCAP_NG \
        -I../../OBJ.linux.amd64/lib/libswan -I../../include -I/usr/include/nss -I/usr/include/nspr \
        -DHERE_FILENAME='"lib/libswan/fd.c"' \
        -O2 -pipe -march=native -mtune=native -ggdb3 \
        -MF ../../OBJ.linux.amd64/lib/libswan/fd.d \
        -MP -MMD -MT fd.o \
        -o ../../OBJ.linux.amd64/lib/libswan/fd.o \
        -c /var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/lib/libswan/fd.c
/var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/lib/libswan/resolve_default_route_linux.c: In function ‘resolve_defaultroute_one’:
/var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/lib/libswan/resolve_default_route_linux.c:532:72: error: ‘KSCF_IP’ undeclared (first use in this function); did you mean ‘KSCF_ID’?
  532 |               err_t er = ttoaddress_dns(shunk1(peer->strings[KSCF_IP]),
      |                                                              ^~~~~~~
      |                                                              KSCF_ID
/var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/lib/libswan/resolve_default_route_linux.c:532:72: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [../../mk/rules.mk:63: resolve_default_route_linux.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [../../mk/targets.mk:84: all] Error 2
make[2]: Leaving directory '/var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/lib/libswan'
make[1]: *** [../mk/targets.mk:84: recursive-all] Error 2
make[1]: Leaving directory '/var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/lib'
make: *** [/var/tmp/portage/net-vpn/libreswan-9999/work/libreswan-9999/mk/targets.mk:84: recursive-all] Error 2

**Comment by cagney** [comment]
Ah, `USE_DNSSEC` isn't enabled.
