### ISSUE TITLE
IPv4-in-IPv6 tunnel is not working after v3.18

### ISSUE THREAD

**Issue by huntxu** [libreswan/libreswan#175]
Hi, I'm trying to setup IPv4-in-IPv6 tunnel between two subnets with libreswan in OpenStack. Below is the configuration on one side:
```
# Configuration for vpn_east
config setup
    nat_traversal=yes
    virtual_private=%v4:10.0.0.128/26,%v4:10.0.0.64/26
conn %default
    keylife=60m
    keyingtries=%forever
conn b1ec98bc-d941-4ebe-86cd-874a21ba8d00
    leftnexthop=%defaultroute
    rightnexthop=%defaultroute
    left=2001:db8::d
    leftid=2001:db8::d
    auto=start
    leftsubnet=10.0.0.64/26
    leftupdown="ipsec _updown --route yes"
    right=2001:db8::4
    rightid=2001:db8::4
    rightsubnets={ 10.0.0.128/26 }
    mtu=1500
    dpdaction=hold
    dpddelay=30
    dpdtimeout=120
    authby=secret
    ikev2=never
    ike=aes128-sha1;modp1536
    ikelifetime=3600s
    phase2=esp
    phase2alg=aes128-sha1;modp1536
    type=tunnel
    lifetime=3600s
```

With libreswan v3.17, the tunnel is working correctly, two subnets can be connected. However, with libreswan>=v3.18 (I've tested all the versions from https://download.libreswan.org/binaries on CentOS 7.4), the tunnel is not working anymore with the same configurations. From the logs, the following messages are noticed:
```
Apr 28 15:26:43 hosts pluto[17403]: failed to convert '2001:db8::d' at load time: IPv4 address may not contain `:'
Apr 28 15:26:43 hosts pluto[17403]: failed to convert '2001:db8::4' at load time: IPv4 address may not contain `:'
```

I checked the changes between v3.17 and v3.18, then I found it might be related to the commit fbca7e1f8a7a11b1ebbe5359671d89edaedf5561. I then download libreswan v3.23 and compiled pluto manually with the following patch, the tunnel got back to normal again:
```diff
diff --git a/programs/pluto/connections.c b/programs/pluto/connections.c
index e32293f35..caf23e369 100644
--- a/programs/pluto/connections.c
+++ b/programs/pluto/connections.c
@@ -992,7 +992,7 @@ static bool extract_end(struct end *dst, const struct whack_end *src,
 
                switch (dst->host_type) {
                case KH_IPHOSTNAME:
-                       er = ttoaddr(dst->host_addr_name, 0, addrtypeof(&dst->host_addr),
+                       er = ttoaddr(dst->host_addr_name, 0, AF_UNSPEC,
                                &dst->host_addr);
 
                        /* The above call wipes out the port, put it again */
```

I'm wondering whether the above patch is the right way to go. Should commit fbca7e1f8a7a11b1ebbe5359671d89edaedf5561 be reverted, or some other changes should be done to make IPv4-in-IPv6 tunnel work, or the configuration files should be updated with libreswan newer than v3.18?

Thanks in advance.

**Comment by letoams** [comment]
applied. Will be in 3.24. Thanks for the detailed report!

**Comment by huntxu** [comment]
@letoams Thank you! I've tested with the commit 52820f5dff3b299f843bcb2ef4cab1c0f598bbad, it worked well with only one subnet specified (`rightsubnet=192.168.3.0/24`). However with multiple subnets(using left/rightsubnets), an error occurred:

```
rightsubnets={ 192.168.3.0/24 192.168.4.0/24 }
```

```
libipsecconf[19709]: conn: "7ab6a95d-a5ae-4edf-b9ae-32da918f1786" warning '192.168.3.0/24 ' is not a subnet declaration. (rightsubnets)
```

This error comes from https://github.com/libreswan/libreswan/blob/76e9bc56f17447a7d34eeff09459e0c265b172f3/lib/libipsecconf/starterwhack.c#L756

Looks like pluto is using HOSTADDRFAMILY to parse the subnets in this case, that causes the problem.

**Comment by letoams** [comment]
On Tue, 12 Jun 2018, huntxu wrote:

> @letoams Thank you! I've tested with the commit 52820f5, it worked well with only one subnet specified (rightsubnet=192.168.3.0/24). However
> with multiple subnets(using left/rightsubnets), an error occurred:
> 
> rightsubnets={ 192.168.3.0/24 192.168.4.0/24 }
> 
> libipsecconf[19709]: conn: "7ab6a95d-a5ae-4edf-b9ae-32da918f1786" warning '192.168.3.0/24 ' is not a subnet declaration. (rightsubnets)
> 
> This error comes from https://github.com/libreswan/libreswan/blob/76e9bc56f17447a7d34eeff09459e0c265b172f3/lib/libipsecconf/starterwhack.c#L756
> 
> Looks like pluto is using HOSTADDRFAMILY to parse the subnets in this case, that causes the problem.

try: rightsubnets={192.168.3.0/24,192.168.4.0/24}

(that is, without any spaces)

Paul

**Comment by huntxu** [comment]
> try: rightsubnets={192.168.3.0/24,192.168.4.0/24}

> (that is, without any spaces)

@letoams Thanks you. But I got no luck. I use the commit a22ccdd(testing: add JSON/ACVP 'make check' tests).

With `rightsubnets={ 192.168.3.0/24 }`, the message is 
```
Jun 19 01:33:26 hosts libipsecconf[15929]: conn: "005ab433-0a9b-4c6e-be99-0faa1f3cd280" warning '192.168.3.0/24 ' is not a subnet declaration. (rightsubnets)
```

With `rightsubnets={192.168.3.0/24,192.168.4.0/24}`(your suggestion in the comment above), the warning message is
```
Jun 19 02:06:22 hosts libipsecconf[31066]: conn: "05c4961c-f009-4639-8bf4-d84af783ac15" warning '192.168.3.0/24,192.168.4.0/24' is not a subnet declaration. (rightsubnets)
```
