### ISSUE TITLE
running "ipsec up/down/delete/etc." gives wrong hint

### ISSUE THREAD

**Issue by vukasink** [libreswan/libreswan#1757]
If I run, e.g. `ipsec up` I get a hint `whack error: missing --name <connection_name>`. Running `ipsec up --name conn1` gives me `Unknown option "--name"`.

However, e.g., `ipsec whack --initiate --name conn1` works.

It seems like whack returns the same hints for `ipsec *` and `ipsec whack *`, but since `ipsec *` commands were reworked (i.e. you don't need to provide `--name` argument), the hint(s) are not correct anymore for `ipsec *` (but are correct for `ipsec whack *`).

**Comment by cagney** [comment]
fixed in mainline:
```
[root@east ~]# ipsec up
Usage: ipsec up [--asynchronous] connectionname \
		[--remote-host ipaddr] [--ctlsocket /run/pluto/pluto.ctl]
```
