### ISSUE TITLE
Error with nm-configured=yes

### ISSUE THREAD

**Issue by wowpetr** [libreswan/libreswan#176]
When I try setting 'nm-configured=yes' in a conf-file, I got this:

May  2 15:53:22 lalala pluto[6224]: "xauth-psk" #2: up-client output: sending connect signal to NetworkManager
May  2 15:53:22 lalala pluto[6224]: "xauth-psk" #2: up-client output: nm-libreswan-helper[???,6416]: <warn>  Could not call the plugin: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager.libreswan was not provided by any .service files

I'm on Gentoo with OpenRC, KDE Plasma and NetworkManager. 
The Installed packages that might be related to it:
net-vpn/libreswan-3.23-r1
net-misc/networkmanager-1.10.6
net-misc/networkmanager-libreswan-1.2.6

**Comment by letoams** [comment]
I'm not sure how that is possible if you have NetworkManager-libreswan ?

**Comment by letoams** [comment]
closing for lack of data
