### ISSUE TITLE
`xfrmi support found existing ipsec1@^E xfrm if_id 0x1` - note the ^E

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1769]
It's from (slightly tweaked):
```
	if (ifi_rsp.result) {
		char if_name_buf[IF_NAMESIZE];
		const char *p = if_indextoname(ifi_rsp.result_if.dev_if_id, if_name_buf);
		ldbg(logger,
		     "xfrmi support found existing %s@%s;%s xfrm if_id 0x%x",
		     ifi_rsp.result_if.name, if_name_buf, p, ifi_rsp.result_if.if_id);
		pfreeany(ifi_rsp.result_if.name);
		return XFRMI_SUCCESS;
	}
```
notice how the return value is `NULL`!
```
| xfrmi support found existing ipsec1@^E;(null) xfrm if_id 0x1
```

**Comment by cagney** [comment]
The plot thickens.  The call to if_indextoname() is failing with:
```
| xfrmi support found existing ipsec1@^E;(null) xfrm if_id 0x1 No such device or address (errno 6)
```

**Comment by cagney** [comment]
Note:
- [ ] #1741
- [ ] #1765

**Comment by cagney** [comment]
```
| opening non-blocking netlink socket
| sent 32 byte netlink message
| reading into 32768 byte buffer
| processing 2948 byte response
| reading into 32768 byte buffer
| processing 2972 byte response
| parse_xfrm_linkinfo_data() setting .result = true; .dev_if_id=0; .matched.dev_if_id=yes; .if_id=1 .matched.xfrm_if_id=yes
| reading into 32768 byte buffer
| processing 20 byte response
|   DONE
| xfrmi support found existing ipsec1@^E;(null) xfrm if_id 0x1 No such device or address (errno 6)
| get_xfrmi_ipaddr_from_conn() taking IP from ifaceip param for xfrmi IF [ipsec1] id [1]
```

**Comment by cagney** [comment]
first west adds ipec1 with ID 1 manually:
```
ip link add dev ipsec1 type xfrm if_id 0x1
ip addr add 192.0.1.251/24 dev ipsec1
ip addr add 2001:db8:0:1::251/64 dev ipsec1
```
then:
```
| find_xfrmi_interface() start
|   opening non-blocking netlink socket
|   sent 32 byte netlink message
|   reading into 32768 byte buffer
|   processing 2948 byte response
|     parse_nl_newlink_msg() start
|     parse_nl_newlink_msg() start
|   reading into 32768 byte buffer
|   processing 2992 byte response
|     parse_nl_newlink_msg() start
|     parse_nl_newlink_msg() start
|       parse_link_info_xfrm() start
|         parse_xfrm_linkinfo_data() start
|           parse_xfrm_linkinfo_data() found IFLA_XFRM_LINK aka dev_if_id_attr
|           parse_xfrm_linkinfo_data() found IFLA_XFRM_IF_ID aka if_id_attr
```
it matches the unset (i.e., 0) `.filter_data.dev_if_id` (I suspect it shouldn't):
```
|           parse_xfrm_linkinfo_data() setting .result_if.dev_if_id to 0
|           parse_xfrm_linkinfo_data() dev_if_id 0 matched .filter_data.dev_if_id 0; setting .matched.dev_if_id
```
it also matches the set ` .filter_data.xfrm_if_id` (I suspect it should):
```
|           parse_xfrm_linkinfo_data() xfrm_if_id 1 matched .filter_data.xfrm_if_id 1; setting .matched.xfrm_if_id and .result_if.if_id
|           parse_xfrm_linkinfo_data() succeeded; setting .result
|     DONE
```
and then calls `if_indextoname(ifi_rsp.result_if.dev_if_id, if_name_buf);` which barfs as `.result_if.dev_if_id` should be greater than 0.
```
|   find_xfrmi_interface() support found existing ipsec1@^E (xfrm) .result_if.if_id yes 1 .result_if.dev_if_id yes 0
| get_xfrmi_ipaddr_from_conn() taking IP from ifaceip param for xfrmi IF [ipsec1] id [1]
```

**Comment by cagney** [comment]
I don't think it is 670dbbdfc71.  Prior to that commit the code would only match `.match.dev_if_id` when it was non-zero, and when the non-zero match failed it would fail the function.  But here the value found is zero; which both the old and new code stored in `.result_if.dev_if_id`.  The only difference is that `.matched.dev_if_id` isn't set but the value is never read anyway.oo

**Comment by wofferl** [comment]
@cagney the problem is in the test , the device is created without pyhsical device -> ipsec1@NONE.

In 03-west-run.sh

`ip link add dev ipsec1 type xfrm if_id 0x1`

should be

`ip link add dev ipsec1 type xfrm dev eth1 if_id 0x1`

**Comment by cagney** [comment]
@wofferl ah, thanks.
Although that means we've now got two bugs :-)  Pluto should detect this and not try to print the uninitialised buffer.

**Comment by cagney** [comment]
#1771 three bugs

**Comment by antonyantony** [comment]
On Fri, Jul 26, 2024 at 11:29:03AM -0700, Wolfgang wrote:
> @cagney the problem is in the test , the device is created without pyhsical device -> ***@***.***
> 
> In 03-west-run.sh
> 
> `ip link add dev ipsec1 type xfrm if_id 0x1`

I think this is the newer syntax.
> 
> should be
> 
> `ip link add dev ipsec1 type xfrm dev eth1 if_id 0x1`

dev eth1 is optional for a long time in the kernel. So I wonder, why "dev 
eth1" is necessary. Is it an older kernel?

-antony

**Comment by cagney** [comment]
[root@fedora ~]# uname -a
Linux fedora 6.8.5-301.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr 11 20:00:10 UTC 2024 x86_64 GNU/Linux

**Comment by antonyantony** [comment]
I wonder why 6.8 kernel need "dev eth1"  It was made optional earlier likely in 5.6 or so.
