### ISSUE TITLE
need way for `ikev2-mobike-08-{no,yes}-nat-expire` to really flush NAT

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1774]
trying
```
iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain
# NAT to NIC's address
iptables -t nat -A POSTROUTING -s 192.1.3.0/24 -p udp --sport 4500  -j SNAT --to-source 192.1.2.254:451111
iptables -t nat -A POSTROUTING -s 192.1.3.0/24 -j SNAT --to-source 192.1.2.254
```
doesn't seem to stop established connection using port 45000

**Comment by letoams** [comment]
You need conntrack -fSee certoe-08-nat-packet-cop-restart PaulSent using a virtual keyboard on a phoneOn Jul 31, 2024, at 13:13, cagney ***@***.***> wrote:﻿
trying
iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain
# NAT to NIC's address
iptables -t nat -A POSTROUTING -s 192.1.3.0/24 -p udp --sport 4500  -j SNAT --to-source 192.1.2.254:451111
iptables -t nat -A POSTROUTING -s 192.1.3.0/24 -j SNAT --to-source 192.1.2.254

doesn't seem to stop established connection using port 45000

**Comment by cagney** [comment]
contrack tools worked, see 7b76d4ed64d45355338fed998d1bb6b75303a2be

**Comment by cagney** [comment]
i.e., nic-nat.sh does this always
