### ISSUE TITLE
`-DAUTH_HAVE_PAM` doesn't compile?

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1787]
In `whack.c`:
```
#define PS(o, p)	{ o, no_argument, NULL, CDP_SINGLETON + POLICY_##p##_IX }
#ifdef AUTH_HAVE_PAM
	PS("ikev2-pam-authorize", IKEV2_PAM_AUTHORIZE),
#endif
```
but the enum value IKEV2_PAM_AUTHORIZE isn't defined.

option should be setting `wm->pam_authorize`

**Comment by bleve** [comment]
-DUSE_PAM_AUTH is only one we set on build. There is nothing setting -DAUTH_HAVE_PAM

**Comment by cagney** [comment]
gone
