### ISSUE TITLE
AUTHENTICATION_FAILED with authby=secret

### ISSUE THREAD

**Issue by elijah0kello** [libreswan/libreswan#1794]
Hello @letoams 

I've configured a tunnel and setup a secrets file but I get this error when I try to bring the tunnel up
```
181 "TestConn" #1029: initiating IKEv2 IKE SA
181 "TestConn" #1029: STATE_PARENT_I1: sent v2I1, expected v2R1
182 "TestConn" #1030: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=AES_CBC_256 integ=HMAC_SHA2_256_128 prf=HMAC_SHA2_256 group=MODP1536}
002 "TestConn" #1030: IKE SA authentication request rejected by peer: AUTHENTICATION_FAILED
000 "TestConn" #1030: scheduling retry attempt 1 of an unlimited number, but releasing whack
```

What could be the issue?

**Comment by cagney** [comment]
You'll need to look at the logs on the other end.  Presumably the passwords don't match (different formats perhaps) but it could be some other configuration issue.  All AUTHENTICATION_FAILED tells us is that the other end said "no".

I'd also note that this is a v3 series libreswan, which is very very old.  I'd upgrade ASAP.

**Comment by elijah0kello** [comment]
I have upgraded. Thanks for the heads up
