### ISSUE TITLE
ipsec tunnel error

### ISSUE THREAD

**Issue by 15923218307** [libreswan/libreswan#1817]
![Uploading image.png…]()
kernel: xfrm XFRM_MSG_DELPOLICY delete(UNUSED) response for flow (in): No such file or directe
kernel: teardown_kernel_policies() outbound failed replace

**Comment by 15923218307** [comment]
libreswan 4.9

**Comment by cagney** [comment]
Please try 5.0 or mainline.
The message is most likely coming from code being overly conservative and deleting kernel policies that weren't added, or were deleted earlier.
