### ISSUE TITLE
ignoring unknown Vendor ID payload [4f 70 65 6e  49 4b 45 44  2d 37 2e 34]

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1825]
I suspect it is "OpenBSD ..."

**Comment by letoams** [comment]
It’s ascii: OpenIKED-7.4PaulSent using a virtual keyboard on a phoneOn Sep 28, 2024, at 11:39, cagney ***@***.***> wrote:﻿
I suspect it is "OpenBSD ..."
