### ISSUE TITLE
libreswan with multiple interfaces does not allow for unencrypted traffic

### ISSUE THREAD

**Issue by akamensky** [libreswan/libreswan#186]
I am running libreswan on a server with multiple NICs (therefore two interfaces - eth0 and eth1). The configuration is site-to-site and encrypted traffic works just fine. But in this situation it is necessary that only one interface uses encrypted connection and another uses direct connection (no ipsec). And this is where it breaks.

If I specify `listen=eth0_ip_address` and/or `interfaces="ipsec0=eth0"`, I can see that pluto process listens only on eth0, but any unencrypted packets arriving to any of interfaces are completely ignored.

Running tcpdump on libreswan host I can actually see packets arriving, but no further processing happens at all (i.e. if it is ICMP packet destined to the host itself and arrives on either eth0 or eth1, no response packet sent).

**I am seriously puzzled as to why it just rejects the plain traffic on BOTH interfaces?** And either way my gut feeling says that it should not be simply dropping unencrypted packets. Even if server has one interface it still should be able to process unencrypted connections.

The configuration as below:

```
conn myconn
	type=tunnel
	authby=secret
	auto=start
	compress=no

	# Actual visible IP as connection is within private network over MPLS
	left=10.10.10.10
	leftid=10.10.10.10
	# Well, that is for routing all Internet traffic over IPSEC, which is what needed in this case
	leftsubnets={0.0.0.0/0}

	# Actual visible IP as connection is within private network over MPLS
	right=10.9.10.10
	rightid=10.9.10.10
	rightsubnets={10.9.0.0/16}

	keyexchange=ike
	esp=aes128-sha1
	ike=aes128-sha1;modp1024

	pfs=no
	salifetime=3600s

```

**Comment by bleve** [comment]
There is nothin we can do. IPsec is policy based. If you have defined IPsec policy for encryption - no clear text traffic is allowed.

IPsec is all about security and you shouldn't ever see clear text traffic, both ends shouldn't send such traffic out if there is IPsec tunnel defined.

**Comment by letoams** [comment]
On Wed, 13 Jun 2018, Alexey Kamenskiy wrote:

> I am running libreswan on a server with multiple NICs (therefore two interfaces - eth0 and eth1). The configuration is
> site-to-site and encrypted traffic works just fine. But in this situation it is necessary that only one interface uses
> encrypted connection and another uses direct connection (no ipsec). And this is where it breaks.

As Tuomo said, the architecture of IPsec is not related to the
interface. IPsec policies are based on src-dst entries. So if you
have an IPsec SA for 10.1.2.0/24 to 192.168.1.0/24 then only encrypted
packets for those src-dst is accepted, and all plaintext is dropped.

This is irrespective of the interface the packet arrives from.

You might mean that some ranges are to be encrypted and come from one
interface and some other ranges are not encrypted and come from the
other interface?

> 	left=10.10.10.10
> 	leftsubnets={0.0.0.0/0}
>
> 	right=10.9.10.10
> 	rightsubnets={10.9.0.0/16}

This means that you will never accept any unencrypted traffic that has
either source or destination 10.9.0.0/16

Paul
