### ISSUE TITLE
tunnel not connecting, proceeds to phase 2 and disconnects

### ISSUE THREAD

**Issue by dinukasal** [libreswan/libreswan#187]
I configured openswan with following config details.

It establishes SA and dicsonnects. After diconnecting it again connects from Main mode.
Repeats this process. What could be the issue.

ipsec verify is ok. Enabled ip forwarding. Os is CentOS 7.
vps is in gcloud. Enabled firewall rules for udp:500,udp:4500, tcp:4500

My config file is,

``
conn ez-cash
authby=secret
auto=start
#ike=aes128-sha128
keyexchange=ike
ikelifetime=86400s
phase2=esp
#phase2alg=aes128-sha256
pfs=yes
type=tunnel
leftsourceip=35.229.xx.xx
left=10.142.0.4
leftsubnet=10.142.0.0/24
#leftnexthop=%defaultroute
leftid=35.229.xx.xx
right=125.214.xx.xx
rightsubnets={172.26.67.20/32, 172.26.67.21/32, 172.26.67.22/32, 172.26.30.23/32}
salifetime=28800s
#rightnexthop=%defaultroute

**Comment by dinukasal** [comment]
This is the output of "watch -n0.5 ipsec status"
https://dinukasthoughts.wordpress.com/2018/06/16/libreswan-log/

**Comment by letoams** [comment]
On Sat, 16 Jun 2018, Dinuka Salwathura wrote:

> I configured openswan with following config details.
> 
> It establishes SA and dicsonnects. After diconnecting it again connects from Main mode.
> Repeats this process. What could be the issue.

Sounds like a misconfiguration. Check both ends to ensure they match. We
might be able to say more when we see some logs.

Paul

**Comment by letoams** [comment]
On Sat, 16 Jun 2018, Dinuka Salwathura wrote:

> 
> This is the output of "watch -n0.5 ipsec status"
> https://dinukasthoughts.wordpress.com/2018/06/16/libreswan-log/

I can't read anything from that animation. Just publish the pluto
messages from the logs somewhere as text.

Paul

**Comment by dinukasal** [comment]
Here is the pluto.log,

Jun 18 04:06:49.008942:   HMAC_SHA1_96        IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (sha sha1 sha1_96 hmac_sha1)
Jun 18 04:06:49.008946:   HMAC_SHA2_512_256   IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (sha512 sha2_512 hmac_sha2_512)
Jun 18 04:06:49.008949:   HMAC_SHA2_384_192   IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (sha384 sha2_384 hmac_sha2_384)
Jun 18 04:06:49.008952:   HMAC_SHA2_256_128   IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (sha2 sha256 sha2_256 hmac_sha2_256)
Jun 18 04:06:49.008955:   AES_XCBC_96         IKEv1:     ESP AH  IKEv2:     ESP AH  FIPS  (aes_xcbc)
Jun 18 04:06:49.008958:   AES_CMAC_96         IKEv1:     ESP AH  IKEv2:     ESP AH  FIPS  (aes_cmac)
Jun 18 04:06:49.008961:   NONE                IKEv1:     ESP     IKEv2:     ESP     FIPS  (null)
Jun 18 04:06:49.008972: DH algorithms:
Jun 18 04:06:49.008974:   MODP1024            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH        (dh2)
Jun 18 04:06:49.008977:   MODP1536            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH        (dh5)
Jun 18 04:06:49.008980:   MODP2048            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (dh14)
Jun 18 04:06:49.008983:   MODP3072            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (dh15)
Jun 18 04:06:49.008986:   MODP4096            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (dh16)
Jun 18 04:06:49.008988:   MODP6144            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (dh17)
Jun 18 04:06:49.008991:   MODP8192            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (dh18)
Jun 18 04:06:49.008994:   DH19                IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  (ecp_256)
Jun 18 04:06:49.008997:   DH20                IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  (ecp_384)
Jun 18 04:06:49.009000:   DH21                IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  (ecp_521)
Jun 18 04:06:49.009003:   DH22                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH      
Jun 18 04:06:49.009005:   DH23                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS
Jun 18 04:06:49.009008:   DH24                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS
Jun 18 04:06:49.009714: starting up 2 crypto helpers
Jun 18 04:06:49.009769: started thread for crypto helper 0
Jun 18 04:06:49.009788: started thread for crypto helper 1
Jun 18 04:06:49.009822: Using Linux XFRM/NETKEY IPsec interface code on 3.10.0-862.3.2.el7.x86_64
Jun 18 04:06:49.020817: | selinux support is NOT enabled.
Jun 18 04:06:49.020847: systemd watchdog for ipsec service configured with timeout of 200000000 usecs
Jun 18 04:06:49.020851: watchdog: sending probes every 100 secs
Jun 18 04:06:50.031262: added connection description "ez-cash/0x1"
Jun 18 04:06:50.031346: added connection description "ez-cash/0x2"
Jun 18 04:06:50.031406: added connection description "ez-cash/0x3"
Jun 18 04:06:50.031450: added connection description "ez-cash/0x4"
Jun 18 04:06:50.031499: listening for IKE messages
Jun 18 04:06:50.031554: adding interface eth0/eth0 10.142.0.4:500
Jun 18 04:06:50.031572: adding interface eth0/eth0 10.142.0.4:4500
Jun 18 04:06:50.031585: adding interface lo/lo 127.0.0.1:500
Jun 18 04:06:50.031599: adding interface lo/lo 127.0.0.1:4500
Jun 18 04:06:50.031701: adding interface lo/lo ::1:500
Jun 18 04:06:50.031718: | setup callback for interface lo:500 fd 20
Jun 18 04:06:50.031723: | setup callback for interface lo:4500 fd 19
Jun 18 04:06:50.031727: | setup callback for interface lo:500 fd 18
Jun 18 04:06:50.031732: | setup callback for interface eth0:4500 fd 17
Jun 18 04:06:50.031736: | setup callback for interface eth0:500 fd 16
Jun 18 04:06:50.031845: loading secrets from "/etc/ipsec.secrets"
Jun 18 04:06:50.031904: no secrets filename matched "/etc/ipsec.d/*.secrets"
Jun 18 04:06:50.032604: initiating all conns with alias='ez-cash'
Jun 18 04:06:50.032665: "ez-cash/0x4" #1: initiating Main Mode
Jun 18 04:06:50.319660: "ez-cash/0x4" #1: STATE_MAIN_I2: sent MI2, expecting MR2
Jun 18 04:06:50.606001: "ez-cash/0x4" #1: ignoring unknown Vendor ID payload [44e60a1736cc3d433edc594deec779cd]
Jun 18 04:06:50.607000: "ez-cash/0x4" #1: STATE_MAIN_I3: sent MI3, expecting MR3
Jun 18 04:06:50.891871: | protocol/port in Phase 1 ID Payload is 17/0. accepted with port_floating NAT-T
Jun 18 04:06:50.891913: "ez-cash/0x4" #1: Peer ID is ID_IPV4_ADDR: '125.214.160.110'
Jun 18 04:06:50.892132: "ez-cash/0x4" #1: STATE_MAIN_I4: ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha group=MODP1536}
Jun 18 04:06:50.892159: "ez-cash/0x1" #2: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO {using isakmp#1 msgid:16fa7c50 proposal=defaults pfsgroup=MODP1536}
Jun 18 04:06:50.892182: "ez-cash/0x2" #3: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO {using isakmp#1 msgid:a897f160 proposal=defaults pfsgroup=MODP1536}
Jun 18 04:06:50.892198: "ez-cash/0x3" #4: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO {using isakmp#1 msgid:5a09c158 proposal=defaults pfsgroup=MODP1536}
Jun 18 04:06:50.892215: "ez-cash/0x4" #5: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO {using isakmp#1 msgid:509d1c07 proposal=defaults pfsgroup=MODP1536}
Jun 18 04:06:51.183692: "ez-cash/0x4" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=32
Jun 18 04:06:51.183732: | ISAKMP Notification Payload
Jun 18 04:06:51.183735: |   00 00 00 20  00 00 00 01  03 10 00 0e
Jun 18 04:06:51.183738: "ez-cash/0x4" #1: received and ignored informational message
Jun 18 04:06:51.183776: "ez-cash/0x4" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=32
Jun 18 04:06:51.183779: | ISAKMP Notification Payload
Jun 18 04:06:51.183782: |   00 00 00 20  00 00 00 01  03 10 00 0e
Jun 18 04:06:51.183785: "ez-cash/0x4" #1: received and ignored informational message
Jun 18 04:06:51.188199: "ez-cash/0x4" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=32
Jun 18 04:06:51.188228: | ISAKMP Notification Payload
Jun 18 04:06:51.188231: |   00 00 00 20  00 00 00 01  03 10 00 0e
Jun 18 04:06:51.188235: "ez-cash/0x4" #1: received and ignored informational message
Jun 18 04:06:51.188480: "ez-cash/0x4" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=32
Jun 18 04:06:51.188485: | ISAKMP Notification Payload
Jun 18 04:06:51.188487: |   00 00 00 20  00 00 00 01  03 10 00 0e
Jun 18 04:06:51.188490: "ez-cash/0x4" #1: received and ignored informational message
Jun 18 04:06:51.188846: "ez-cash/0x4" #1: received Delete SA payload: self-deleting ISAKMP State #1
Jun 18 04:06:51.188852: "ez-cash/0x4" #1: deleting state (STATE_MAIN_I4) and sending notification
Jun 18 04:06:51.188993: "ez-cash/0x4" #1: reschedule pending Phase 2 of connection"ez-cash/0x4" state #5: - the parent is going away
Jun 18 04:06:51.189003: "ez-cash/0x4" #1: reschedule pending Phase 2 of connection"ez-cash/0x3" state #4: - the parent is going away
Jun 18 04:06:51.189008: "ez-cash/0x4" #1: reschedule pending Phase 2 of connection"ez-cash/0x2" state #3: - the parent is going away
Jun 18 04:06:51.189013: "ez-cash/0x4" #1: reschedule pending Phase 2 of connection"ez-cash/0x1" state #2: - the parent is going away
Jun 18 04:06:51.189056: packet from 125.214.160.110:4500: received and ignored empty informational notification payload
Jun 18 04:06:51.189077: "ez-cash/0x4" #6: initiating Main Mode
Jun 18 04:06:51.189125: "ez-cash/0x4" #5: deleting state (STATE_QUICK_I1)
Jun 18 04:06:51.189187: "ez-cash/0x2" #3: deleting state (STATE_QUICK_I1)
Jun 18 04:06:51.189245: "ez-cash/0x1" #2: deleting state (STATE_QUICK_I1)
Jun 18 04:06:51.189281: "ez-cash/0x3" #4: deleting state (STATE_QUICK_I1)
Jun 18 04:06:51.475201: "ez-cash/0x4" #6: STATE_MAIN_I2: sent MI2, expecting MR2
Jun 18 04:06:51.761585: "ez-cash/0x4" #6: ignoring unknown Vendor ID payload [9871d58e202c344d2b8185015ececeb7]
Jun 18 04:06:51.762420: "ez-cash/0x4" #6: STATE_MAIN_I3: sent MI3, expecting MR3
Jun 18 04:06:52.047364: | protocol/port in Phase 1 ID Payload is 17/0. accepted with port_floating NAT-T
Jun 18 04:06:52.047408: "ez-cash/0x4" #6: Peer ID is ID_IPV4_ADDR: '125.214.160.110'
Jun 18 04:06:52.047553: "ez-cash/0x4" #6: STATE_MAIN_I4: ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha group=MODP1536}
Jun 18 04:06:52.047577: "ez-cash/0x2" #7: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO to replace #3 {using isakmp#6 msgid:c1cea724 proposal=defaults pfsgroup=MODP1536}
Jun 18 04:06:52.047595: "ez-cash/0x3" #8: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO to replace #4 {using isakmp#6 msgid:d0be2b52 proposal=defaults pfsgroup=MODP1536}
Jun 18 04:06:52.047608: "ez-cash/0x1" #9: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO to replace #2 {using isakmp#6 msgid:73802578 proposal=defaults pfsgroup=MODP1536}
Jun 18 04:06:52.047629: "ez-cash/0x4" #10: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO {using isakmp#6 msgid:c8858720 proposal=defaults pfsgroup=MODP1536}
Jun 18 04:06:52.336571: "ez-cash/0x4" #6: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=32
Jun 18 04:06:52.336613: | ISAKMP Notification Payload
Jun 18 04:06:52.336617: |   00 00 00 20  00 00 00 01  03 10 00 0e
Jun 18 04:06:52.336623: "ez-cash/0x4" #6: received and ignored informational message
Jun 18 04:06:52.340875: "ez-cash/0x4" #6: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=32
Jun 18 04:06:52.340899: | ISAKMP Notification Payload
Jun 18 04:06:52.340901: |   00 00 00 20  00 00 00 01  03 10 00 0e
Jun 18 04:06:52.340905: "ez-cash/0x4" #6: received and ignored informational message
Jun 18 04:06:52.342853: "ez-cash/0x4" #6: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=32
Jun 18 04:06:52.342866: | ISAKMP Notification Payload
Jun 18 04:06:52.342868: |   00 00 00 20  00 00 00 01  03 10 00 0e
Jun 18 04:06:52.342871: "ez-cash/0x4" #6: received and ignored informational message
Jun 18 04:06:52.343105: "ez-cash/0x4" #6: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=32
Jun 18 04:06:52.343109: | ISAKMP Notification Payload
Jun 18 04:06:52.343111: |   00 00 00 20  00 00 00 01  03 10 00 0e
Jun 18 04:06:52.343114: "ez-cash/0x4" #6: received and ignored informational message
Jun 18 04:06:52.343497: "ez-cash/0x4" #6: received Delete SA payload: self-deleting ISAKMP State #6
Jun 18 04:06:52.343505: "ez-cash/0x4" #6: deleting state (STATE_MAIN_I4) and sending notification
Jun 18 04:06:52.343643: "ez-cash/0x4" #6: reschedule pending Phase 2 of connection"ez-cash/0x4" state #10: - the parent is going away
Jun 18 04:06:52.343652: "ez-cash/0x4" #6: reschedule pending Phase 2 of connection"ez-cash/0x1" state #9: - the parent is going away
Jun 18 04:06:52.343658: "ez-cash/0x4" #6: reschedule pending Phase 2 of connection"ez-cash/0x3" state #8: - the parent is going away
Jun 18 04:06:52.343663: "ez-cash/0x4" #6: reschedule pending Phase 2 of connection"ez-cash/0x2" state #7: - the parent is going away
Jun 18 04:06:52.343690: packet from 125.214.160.110:4500: received and ignored empty informational notification payload
Jun 18 04:06:52.343706: "ez-cash/0x4" #11: initiating Main Mode
Jun 18 04:06:52.343752: "ez-cash/0x4" #10: deleting state (STATE_QUICK_I1)
Jun 18 04:06:52.343814: "ez-cash/0x3" #8: deleting state (STATE_QUICK_I1)
Jun 18 04:06:52.343852: "ez-cash/0x2" #7: deleting state (STATE_QUICK_I1)
Jun 18 04:06:52.343900: "ez-cash/0x1" #9: deleting state (STATE_QUICK_I1)
Jun 18 04:06:52.629727: "ez-cash/0x4" #11: STATE_MAIN_I2: sent MI2, expecting MR2
Jun 18 04:06:52.916028: "ez-cash/0x4" #11: ignoring unknown Vendor ID payload [d192d9c858a366569c1cd57cf253f9a8]
Jun 18 04:06:52.916881: "ez-cash/0x4" #11: STATE_MAIN_I3: sent MI3, expecting MR3
Jun 18 04:06:53.201786: | protocol/port in Phase 1 ID Payload is 17/0. accepted with port_floating NAT-T
Jun 18 04:06:53.201828: "ez-cash/0x4" #11: Peer ID is ID_IPV4_ADDR: '125.214.160.110'
Jun 18 04:06:53.201937: "ez-cash/0x4" #11: STATE_MAIN_I4: ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha group=MODP1536}
Jun 18 04:06:53.201961: "ez-cash/0x3" #12: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO to replace #8 {using isakmp#11 msgid:da90015c proposal=defaults pfsgroup=MODP1536}
Jun 18 04:06:53.201979: "ez-cash/0x1" #13: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO to replace #9 {using isakmp#11 msgid:50c431c9 proposal=defaults pfsgroup=MODP1536}
Jun 18 04:06:53.201991: "ez-cash/0x2" #14: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO to replace #7 {using isakmp#11 msgid:acaf36ca proposal=defaults pfsgroup=MODP1536}
Jun 18 04:06:53.202004: "ez-cash/0x4" #15: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO {using isakmp#11 msgid:210d4d28 proposal=defaults pfsgroup=MODP1536}
Jun 18 04:06:53.491257: "ez-cash/0x4" #11: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=32
Jun 18 04:06:53.491297: | ISAKMP Notification Payload
Jun 18 04:06:53.491301: |   00 00 00 20  00 00 00 01  03 10 00 0e
Jun 18 04:06:53.491305: "ez-cash/0x4" #11: received and ignored informational message
Jun 18 04:06:53.495672: "ez-cash/0x4" #11: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=32
Jun 18 04:06:53.495700: | ISAKMP Notification Payload
Jun 18 04:06:53.495703: |   00 00 00 20  00 00 00 01  03 10 00 0e
Jun 18 04:06:53.495708: "ez-cash/0x4" #11: received and ignored informational message
Jun 18 04:06:53.497595: "ez-cash/0x4" #11: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=32
Jun 18 04:06:53.497604: | ISAKMP Notification Payload
Jun 18 04:06:53.497607: |   00 00 00 20  00 00 00 01  03 10 00 0e
Jun 18 04:06:53.497610: "ez-cash/0x4" #11: received and ignored informational message
Jun 18 04:06:53.497921: "ez-cash/0x4" #11: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=32
Jun 18 04:06:53.497925: | ISAKMP Notification Payload
Jun 18 04:06:53.497928: |   00 00 00 20  00 00 00 01  03 10 00 0e
Jun 18 04:06:53.497931: "ez-cash/0x4" #11: received and ignored informational message
Jun 18 04:06:53.498384: "ez-cash/0x4" #11: received Delete SA payload: self-deleting ISAKMP State #11
Jun 18 04:06:53.498392: "ez-cash/0x4" #11: deleting state (STATE_MAIN_I4) and sending notification
Jun 18 04:06:53.498515: "ez-cash/0x4" #11: reschedule pending Phase 2 of connection"ez-cash/0x4" state #15: - the parent is going away
Jun 18 04:06:53.498525: "ez-cash/0x4" #11: reschedule pending Phase 2 of connection"ez-cash/0x2" state #14: - the parent is going away
Jun 18 04:06:53.498530: "ez-cash/0x4" #11: reschedule pending Phase 2 of connection"ez-cash/0x1" state #13: - the parent is going away
Jun 18 04:06:53.498535: "ez-cash/0x4" #11: reschedule pending Phase 2 of connection"ez-cash/0x3" state #12: - the parent is going away
Jun 18 04:06:53.498560: packet from 125.214.160.110:4500: received and ignored empty informational notification payload
Jun 18 04:06:53.498582: "ez-cash/0x4" #16: initiating Main Mode
Jun 18 04:06:53.498655: "ez-cash/0x4" #15: deleting state (STATE_QUICK_I1)
Jun 18 04:06:53.498713: "ez-cash/0x1" #13: deleting state (STATE_QUICK_I1)
Jun 18 04:06:53.498754: "ez-cash/0x3" #12: deleting state (STATE_QUICK_I1)
Jun 18 04:06:53.498787: "ez-cash/0x2" #14: deleting state (STATE_QUICK_I1)
Jun 18 04:06:53.784846: "ez-cash/0x4" #16: STATE_MAIN_I2: sent MI2, expecting MR2
Jun 18 04:06:54.070917: "ez-cash/0x4" #16: ignoring unknown Vendor ID payload [0cd9460f3c569083142615b0218c0900]
Jun 18 04:06:54.071748: "ez-cash/0x4" #16: STATE_MAIN_I3: sent MI3, expecting MR3
Jun 18 04:06:54.356665: | protocol/port in Phase 1 ID Payload is 17/0. accepted with port_floating NAT-T
Jun 18 04:06:54.356708: "ez-cash/0x4" #16: Peer ID is ID_IPV4_ADDR: '125.214.160.110'
Jun 18 04:06:54.356821: "ez-cash/0x4" #16: STATE_MAIN_I4: ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha group=MODP1536}
Jun 18 04:06:54.356845: "ez-cash/0x1" #17: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO to replace #13 {using isakmp#16 msgid:c66a233b proposal=defaults pfsgroup=MODP1536}
Jun 18 04:06:54.356862: "ez-cash/0x2" #18: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO to replace #14 {using isakmp#16 msgid:aa0f1080 proposal=defaults pfsgroup=MODP1536}
Jun 18 04:06:54.356874: "ez-cash/0x3" #19: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO to replace #12 {using isakmp#16 msgid:8f24d70b proposal=defaults pfsgroup=MODP1536}
Jun 18 04:06:54.356888: "ez-cash/0x4" #20: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO {using isakmp#16 msgid:ce4892a1 proposal=defaults pfsgroup=MODP1536}
Jun 18 04:06:54.645721: "ez-cash/0x4" #16: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=32
Jun 18 04:06:54.645766: | ISAKMP Notification Payload
Jun 18 04:06:54.645770: |   00 00 00 20  00 00 00 01  03 10 00 0e
Jun 18 04:06:54.645773: "ez-cash/0x4" #16: received and ignored informational message
Jun 18 04:06:54.650117: "ez-cash/0x4" #16: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=32
Jun 18 04:06:54.650142: | ISAKMP Notification Payload
Jun 18 04:06:54.650146: |   00 00 00 20  00 00 00 01  03 10 00 0e
Jun 18 04:06:54.650149: "ez-cash/0x4" #16: received and ignored informational message
Jun 18 04:06:54.652204: "ez-cash/0x4" #16: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=32
Jun 18 04:06:54.652223: | ISAKMP Notification Payload
Jun 18 04:06:54.652226: |   00 00 00 20  00 00 00 01  03 10 00 0e
Jun 18 04:06:54.652229: "ez-cash/0x4" #16: received and ignored informational message
Jun 18 04:06:54.652523: "ez-cash/0x4" #16: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=32
Jun 18 04:06:54.652528: | ISAKMP Notification Payload
Jun 18 04:06:54.652530: |   00 00 00 20  00 00 00 01  03 10 00 0e
Jun 18 04:06:54.652533: "ez-cash/0x4" #16: received and ignored informational message
Jun 18 04:06:54.653003: "ez-cash/0x4" #16: received Delete SA payload: self-deleting ISAKMP State #16
Jun 18 04:06:54.653009: "ez-cash/0x4" #16: deleting state (STATE_MAIN_I4) and sending notification
Jun 18 04:06:54.653137: "ez-cash/0x4" #16: reschedule pending Phase 2 of connection"ez-cash/0x4" state #20: - the parent is going away
Jun 18 04:06:54.653146: "ez-cash/0x4" #16: reschedule pending Phase 2 of connection"ez-cash/0x3" state #19: - the parent is going away
Jun 18 04:06:54.653151: "ez-cash/0x4" #16: reschedule pending Phase 2 of connection"ez-cash/0x2" state #18: - the parent is going away
Jun 18 04:06:54.653156: "ez-cash/0x4" #16: reschedule pending Phase 2 of connection"ez-cash/0x1" state #17: - the parent is going away
Jun 18 04:06:54.653182: packet from 125.214.160.110:4500: received and ignored empty informational notification payload
Jun 18 04:06:54.653199: "ez-cash/0x4" #21: initiating Main Mode
Jun 18 04:06:54.653242: "ez-cash/0x4" #20: deleting state (STATE_QUICK_I1)
Jun 18 04:06:54.653300: "ez-cash/0x2" #18: deleting state (STATE_QUICK_I1)
Jun 18 04:06:54.653374: "ez-cash/0x1" #17: deleting state (STATE_QUICK_I1)
Jun 18 04:06:54.653433: "ez-cash/0x3" #19: deleting state (STATE_QUICK_I1)
Jun 18 04:06:54.939274: "ez-cash/0x4" #21: STATE_MAIN_I2: sent MI2, expecting MR2


Appreciate your help. Thanks

**Comment by dinukasal** [comment]
@letoams When the other party initiate some traffic the tunnel gets up. 
Is there a way to make the libreswan the initiator?

**Comment by letoams** [comment]
Read the man page for ipsec.conf

auto=start

**Comment by libreswan** [comment]
regardless, the NO_PROPOSAL_CHOSEN shows there is some configuration mismatch between the two peers. Since connecting works from one peer but not the other, it seems one peer is more forgiving then the other. But since you never know who will exactly initiate a rekeying, this configuration is dangerous and should be fixed to exactly match on both peers
