### ISSUE TITLE
comp state missing marks in `ikev2-xfrmi-17-ipcomp`

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1879]
For instance:
```
--- MAIN/testing/pluto/ikev2-xfrmi-17-ipcomp/north.console.txt
+++ OUTPUT/testing/pluto/ikev2-xfrmi-17-ipcomp/north.console.txt
@@ -58,7 +58,6 @@
 src 192.1.3.33 dst 192.1.2.23
 	proto comp spi 0xSPISPI reqid REQID mode tunnel
 	replay-window 0 flag af-unspec
-	output-mark 0x1/0xffffffff
 	comp deflate 
 	if_id 0x1
 src 192.1.3.33 dst 192.1.2.23
@@ -79,7 +78,6 @@
 src 192.1.2.23 dst 192.1.3.33
 	proto comp spi 0xSPISPI reqid REQID mode tunnel
 	replay-window 0 flag af-unspec
-	output-mark 0x1/0xffffffff
 	comp deflate 
 	if_id 0x1
 src 192.1.2.23 dst 192.1.3.33
```
they disappeared around:
  c74d56e6e kernel: update struct kernel_state
  2922f1e45 kernel: drop struct kernel_state .natt_oa; never read

**Comment by paulwouters** [comment]
But is it a bug?

I would not think the inner SA for compress does anything related to whole packets? eg they prob didn't belong there to begin with.

The test is broken as it does not actually test a large ping packet for proper use of the compress SA

**Comment by cagney** [comment]
AH is missing marks as well

**Comment by cagney** [comment]
The test's config file does not specify marks, instead that is left to the kernel.

Prior to c74d56e6e636dce5389c7e9c0aaba80873a659da the code, for both ESP and IPCOMP, omitted marks in the XFRMI message:
```
nl_addattr32(&req.n, sizeof(req.data), XFRMA_SET_MARK, sa->xfrm_if_id);
```
Since marks were missing, the kernel got to add them.

Currently, ESP behaves the same way, but IPCOMP is instead forcing the marks. to 0/0x0 with:
```
			nl_addattr32(&req.n, sizeof(req.data), XFRMA_SET_MARK,
				     sa->sa_mark_out->val);
			nl_addattr32(&req.n, sizeof(req.data), XFRMA_SET_MARK_MASK,
				     sa->sa_mark_out->mask);
```
while this works.  I consider it wrong as pluto shouldn't be assuming that when no marks were specified, 0/0x0 is safe.

(that the kernel needlessly puts marks on an IPCOMP state when they aren't specified isn't our problem)

**Comment by cagney** [comment]
Test are back to where it was, Needing marks is a new issue.
