### ISSUE TITLE
VPN tunnel occasionally disconnected

### ISSUE THREAD

**Issue by 15923218307** [libreswan/libreswan#1882]
### What happened?

libreswan 4.9
![image](https://github.com/user-attachments/assets/f2954ceb-af68-482c-ad6d-8808e681959d)

log:
"IPsec SA established" two time, i see other tunnel only one time
bug:
`ipsec show` , i can see spd rule, bug network is disconnect, if i do `systemctl restart ipsec`, network is connect

### Your configuration
```
conn vpnt-822a6dfpo8k8czss27vpnspd-cfx8a234p6spu08tcgi
  authby=secret
  type=tunnel
  left=xx.xx.xx.xx
  leftsubnet=10.8.106.0/23
  leftid=xx.xx.xx.xx
  leftnexthop=%defaultroute
  right=xx.xx.xx.xx
  rightsubnets={10.208.0.0/12}
  rightid=xx.xx.xx.xx
  rightnexthop=%defaultroute
  auto=start
  dpddelay=30
  dpdtimeout=30
  dpdaction=restart
  ikev2=never
  ike=aes256-sha256;modp2048
  aggrmode=no
  ikelifetime=86400
  phase2alg=aes128-sha256;modp2048
  pfs=yes
  salifetime=3600
````
### Relevant log output

```
Oct 30 15:25:13.822033: "vpnt-822a6dfpo8k8czss27ypnspól-cfx8a234p6spu08tgi/0x1" #88: IPsec SA established tunnel mode {ESPinUDP=
0xc5b09783 <0x8dec0cb5_xfrm=AES_CBC_128-HMAC_SHAZี_256_128 NATD=xx.xx.xx.xx:4500 DPD=active}
Oct 30 15:25:13.868356: "vpnt-822a6dfpo8k8czss27vpnspd-cfx8a234p6spu08tgi/0x1" #87: IPsec SA established tumneI mode {ESPinUDP=
0x3e0a4076 <0x567eff12_xfrm=AES_CBC_128-HMAC_SHAZ_256_128 NATD=xx.xx.xx.xx:4500_DPD=active)
````

**Comment by cagney** [comment]
Can you provide a log starting from where the IKE SA starts to negotiate?
`rightsubnets={10.208.0.0/12}` can be simplified to `rightsubnet=10.208.0.0/12`.  If that is changed, what happens?
Could the other end have simultaneously initiated the Child SA?
Have you tried 5.1?

**Comment by 15923218307** [comment]
> Can you provide a log starting from where the IKE SA starts to negotiate? `rightsubnets={10.208.0.0/12}` can be simplified to `rightsubnet=10.208.0.0/12`. If that is changed, what happens? Could the other end have simultaneously initiated the Child SA? Have you tried 5.1?

(1) local end use "leftsubnet=xx.xx.xx.xx  rightsubnets={10.208.0.0/12}"other end use "leftsubnet=xx.xx.xx.xx rightsubnet=xx.xx.xx.xx", I also suspect it's due to rightsubnets，i will test it
(2)5.1 version，i will test it

**Comment by 15923218307** [comment]
> Can you provide a log starting from where the IKE SA starts to negotiate?

![image](https://github.com/user-attachments/assets/4566391b-0597-4fa0-8fb5-3eddf0963112)

**Comment by cagney** [comment]
Hi, what solved the problem?

**Comment by 15923218307** [comment]
> Hi, what solved the problem?

It hasn't been resolved yet. I accidentally closed it，This issue is related to the production environment, so I need to wait until it is replicated before attempting to modify and verify it，I have the result and will reply to you

**Comment by 15923218307** [comment]
> Can you provide a log starting from where the IKE SA starts to negotiate?

![image](https://github.com/user-attachments/assets/fbe94562-542f-43de-b175-7f8a1022fc0c)
![image](https://github.com/user-attachments/assets/8b32156d-ae8b-40d1-b809-15faaff248f7)
![image](https://github.com/user-attachments/assets/d59aa0f3-264f-4077-b637-fa1468b4d01d)
![image](https://github.com/user-attachments/assets/15db0916-2d31-4194-8dca-b38a2ad377e1)

I can see error message:"assign_holdpass() delete_bare_shunt() failed"

**Comment by 15923218307** [comment]
> Can you provide a log starting from where the IKE SA starts to negotiate? `rightsubnets={10.208.0.0/12}` can be simplified to `rightsubnet=10.208.0.0/12`. If that is changed, what happens? Could the other end have simultaneously initiated the Child SA? Have you tried 5.1?

![image](https://github.com/user-attachments/assets/ff112880-6026-484b-87a0-9d16856f8680)
![image](https://github.com/user-attachments/assets/8643b456-bb11-4e9f-82ab-fd61301bd671)
