### ISSUE TITLE
Internal DNS server not visible/used in /etc/resolv.conf for macOS when operating in split mode IKEv2

### ISSUE THREAD

**Issue by johanneshiry** [libreswan/libreswan#1885]
### What happened?

Hi guys - I am struggling since two days setting up an IKEv2 split tunnel for a road warrior (macOS) w/ an internal DNS. Would be great if somebody could let me know if this is a bug o. point me into the right direction how to fix my setup. 

Libreswan version: 5.1
Host OS: Ubuntu 
Client OS: macOS 14.7 Sonoma

**Goal:** 
Setup a split tunnel (e.g., `leftsubnet=XXX.XXX.XXX.XXX/24`) between VPN server and road warrior client running macOS that use an internal DNS server for resolving selected domains (e.g., foo.com). DNS server and VPN server are running on the same host. 

**Issue:** 
DNS server is pushed to clients and visible using `scutil --dns | grep 'nameserver\[[0-9]*\]'`, however not pushed into `/etc/resolv.conf`, which leads to the situation, that it us not used by macOS. 
However, **_works if not in split mode_** (e.g., if all traffic is routed through the vpn with `leftsubnet=0.0.0.0/0`) - then `/etc/resolv.conf` only contains the custom namserver defined in `modecfgdns=`)

### Your configuration

```shell
conn split_dns
  left=%defaultroute
  leftcert=XXX.YYY.com
  leftsendcert=always
  leftsubnet=<VPN.DNS.IP.XXX>
  leftrsasigkey=%cert
  right=%any
  rightid=@ID
  rightaddresspool=192.168.60.10-192.168.60.15
  rightca=%same
  rightrsasigkey=%cert
  narrowing=yes
  dpddelay=30
  retransmit-timeout=300s
  dpdaction=clear
  auto=add
  ikev2=insist
  rekey=no
  pfs=no
  ike=aes_gcm_c_256-hmac_sha2_256-ecp_256,aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
  ikelifetime=24h
  salifetime=24h
  encapsulation=yes
  leftid=@XXXX
  modecfgdns=<VPN.DNS.IP.XXX>
  mobike=no
```

### Relevant log output

**Local client dns configuration w/o split mode (vpn enabled)**

`scutil --dns | grep 'nameserver\[[0-9]*\]'` 

```
  nameserver[0] : <VPN.DNS.IP.XXX>
  nameserver[0] : fe80::ac49:dbff:fe34:89eu%6d
  nameserver[1] : 172.20.XX.XX
  nameserver[0] : <VPN.DNS.IP.XXX>
```

`/etc/resolv.conf` 

```
nameserver <VPN.DNS.IP.XXX>
```

--------- 

**Local client dns configuration w/ split mode (vpn enabled)**

`scutil --dns | grep 'nameserver\[[0-9]*\]'` 

```
  nameserver[0] : fe80::ac49:dbff:fe34:89eu%6d
  nameserver[1] : 172.20.XX.XX
  nameserver[0] : fe80::ac49:dbff:fe34:89eu%6d
  nameserver[1] : 172.20.XX.XX
  nameserver[0] : <VPN.DNS.IP.XXX>
```

`/etc/resolv.conf` 
```
nameserver fe80::ac49:dbff:fe34:89eu%6d
nameserver 172.20.XX.XX
```

**Comment by letoams** [comment]
On Thu, 31 Oct 2024, Johannes Hiry wrote:

> Issue:
> DNS server is pushed to clients and visible using scutil --dns | grep 'nameserver\[[0-9]*\]', however not pushed into
> /etc/resolv.conf, which leads to the situation, that it us not used by macOS.
> However, works if not in split mode (e.g., if leftsubnet=0.0.0.0/0, then /etc/resolv.conf only contains the custom
> namserver defined in modecfgdns=)

Unfortunately that is completely out of our control.
Note that I am not sure all macos apps actually use /etc/resolv.conf,
as OSX/iOS have their own DNS layer and applications open "named
sockets" mostly, so the resolving happens "within the system".


>   modecfgdns=<VPN.DNS.IP.XXX>

What happens when you add a list of domains? eg:

    modecfgdomains=internal.domain,another.internal.domain

It might have some kind of security restrictions as specified in
RFC 8598 https://datatracker.ietf.org/doc/html/rfc8598

Paul

**Comment by johanneshiry** [comment]
Thanks for the super fast and helpful response, @letoams - this solved the issue! 

Tried with `hostname.domain.tld` and `domain.tld`. While in both cases, the nameserver order from `scutil --dns | grep 'nameserver\[[0-9]*\]'` is still as before (w/o the internal DNS being used in the first place), `resolv.conf` now looks like this: 

```
search hostname.domain.tld
nameserver fe80::ac49:dbff:fe34:89eu%6d
nameserver 172.20.XX.XX
```

Thanks again!
