### ISSUE TITLE
Supported features link leads to blank page

### ISSUE THREAD

**Issue by tomato42** [libreswan/libreswan#19]
On the main site (https://libreswan.org/) the link to "Supported Features" leads to wiki page (https://libreswan.org/wiki/Features) that is empty

**Comment by Hoverbear** [comment]
@letoams The "Interop" page is also empty! Let me know if you need any help.

**Comment by letoams** [comment]
On Wed, 25 Feb 2015, Andrew Hobden wrote:

> @letoams The "Interop" page is also empty! Let me know if you need any help.

It is located at https://libreswan.org/wiki/Interoperability

We could use help with our wiki. Please contact me via regular email so
I can give you access :)

Paul

**Comment by letoams** [comment]
I moved the supported features link to the main page of the wiki for now
