### ISSUE TITLE
Ver 3.25 compile error

### ISSUE THREAD

**Issue by sudanking** [libreswan/libreswan#192]
I tried to compile latest ver 3.25 and I get the following error.... any Idea??
[https://pastebin.com/NJEN6a1F](https://pastebin.com/NJEN6a1F)

I use (Linux Debian-84-jessie-64-minimal 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux) as a VPS

**Comment by vukasink** [comment]
Hi,

I think you can see the problem description and find the solution on the following link:
[https://libreswan.org/wiki/3.21_on_Debian_Wheezy](https://libreswan.org/wiki/3.21_on_Debian_Wheezy)
