### ISSUE TITLE
parse `iptfs-init-delay` and `iptfs-drop-time` as time values

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1922]
so that
```
iptfs-init-delay=10s
```
works; also consider making the default unit seconds, or just require the unit; especially given one defaults to 1s.

**Comment by letoams** [comment]
> On Nov 15, 2024, at 03:08, cagney ***@***.***> wrote:
> 
> ﻿
> so that
> 
> iptfs-init-delay=10s
> works; also consider making the default unit seconds
> 
These units should be in ms scale, not second scale.

**Comment by cagney** [comment]
> These units should be in ms scale, not second scale.

Is MS milliseconds (ms, 1/1000) or microseconds (us, 1/1.000.000) here.  I suspect milliseconds (there's a tradition that networks specify things in that time scale), but the documentation says microseconds, and the internal value fed into the kernel is uintmax_t.

My suggestion, here, is to default to seconds (given the default is 1s), but accept any unit.  That's what we do for:
```
  { "shuntlifetime",  kv_config,  kt_time,  KBF_SHUNTLIFETIME_MS, NULL, NULL, },
  { "crlcheckinterval",  kv_config,  kt_time,  KBF_CRL_CHECKINTERVAL_MS, NULL, NULL, },
  { "ipsec-lifetime",  kv_conn,  kt_time,  KNCF_IPSEC_LIFETIME_MS, NULL, NULL, },
  { "keylife",  kv_conn | kv_alias,  kt_time,  KNCF_IPSEC_LIFETIME_MS, NULL, NULL, }, /* old name */
  { "lifetime",  kv_conn | kv_alias,  kt_time,  KNCF_IPSEC_LIFETIME_MS, NULL, NULL, }, /* old name */
  { "salifetime",  kv_conn,  kt_time,  KNCF_IPSEC_LIFETIME_MS, NULL, NULL, }, /* old name */
  { "retransmit-timeout",  kv_conn,  kt_time,  KNCF_RETRANSMIT_TIMEOUT_MS, NULL, NULL, },
  { "rekeymargin",  kv_conn,  kt_time,  KNCF_REKEYMARGIN_MS, NULL, NULL, },
  { "ikelifetime",  kv_conn,  kt_time,  KNCF_IKELIFETIME_MS, NULL, NULL, },
```
and strongly encourage the use of time units vis:
```
iptfs-init-delay=500ms
```
I consider this far more usable than:
```
iptfs-init-delay=500000
```

(the parser should directly convert the time to deltatime_t, it currently does it in two steps, but I digress)

**Comment by paulwouters** [comment]
ok, you convinced me.
