### ISSUE TITLE
remove `#ifdef SOFTREMOTE_CLIENT_WORKAROUND`

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1927]
```
        /* see: http://popoludnica.pl/?id=10100110 */
        /* should become a conn option */
        /* client-side is not yet implemented for this - only works with SoftRemote clients */
        /* SoftRemote takes the IV for XAUTH from phase2, where Libreswan takes it from phase1 */
```
the page http://popoludnica.pl/?id=10100110 is still live!

**Comment by letoams** [comment]
Why remove it ? You mean turn into option or just remove support for softremote ?

**Comment by cagney** [comment]
Remove "support".  Enabling it requires a custom build using:
```
make CFLAGS+=-DSOFTREMOTE_CLIENT_WORKAROUND
```
as there's no USE_ option.

**Comment by cagney** [comment]
It seems that [SafeNet](https://en.wikipedia.org/wiki/SafeNet) was assimilated starting in 2014.
