### ISSUE TITLE
Require either ldap or curl

### ISSUE THREAD

**Issue by doctaweeks** [libreswan/libreswan#196]
Beginning with 3.25 (8a70fd389ccb29f51a0221a7833f12d1404611f0), fetch.o must contain the check_crls symbol, however, fetch.c begins with `#if defined(LIBCURL) || defined(LIBLDAP)`. The build system does not require one of those to be defined so it is possible to turn them both off and break the build:

timer.o: In function `timer_event_cb':
timer.c:(.text+0x11a1): undefined reference to `check_crls'
collect2: error: ld returned 1 exit status
make[3]: *** [../../mk/program.mk:121: pluto] Error 1

**Comment by letoams** [comment]
On Sun, 22 Jul 2018, Daniel M. Weeks wrote:

> Beginning with 3.25 (8a70fd3), fetch.o must contain the check_crls symbol,
> however, fetch.c begins with #if defined(LIBCURL) || defined(LIBLDAP). The
> build system does not require one of those to be defined so it is possible
> to turn them both off and break the build:

I pushed a fix. Thanks for the report.

Paul
