### ISSUE TITLE
in `connection_check_ddns1()` why are connections with `c->remote->config->child.protoport.has_port_wildcard` skipped

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1967]
As in:
```
	if (c->remote->config->child.protoport.has_port_wildcard) {
		pdbg(c->logger, "pending ddns: skipping connection, remote has wildcard protoport");
		return;
	}

	if (id_has_wildcards(&c->remote->host.id)) {
		pdbg(c->logger, "pending ddns: skipping connection, remote has wildcard ID");
		return;
	}
```

ref  dc5b5351378e2e5baadc97a54e0883b3cefa774b

```
    DYNAMICDNS was not working for tunnels that failed an initial lookup.
    Make sure this is dealt with appropriately and that the tunnels come up
    once their DNS name resolves.
```

- selectors can include wild cards implicitly
- connection add merges protoport and subnets
- perhaps something to do with IKEv1?

**Comment by cagney** [comment]
> Probably because you can’t initiate to rightprotoport

No, protoports are used by the Child SA, not the IKE SA.

One thing that can't initiate is a template, and `c->remote->config->child.protoport.has_port_wildcard` implies either a template or instance.  Perhaps ddns should only try to initiate permanent connections.

The next one is `id_has_wildcards(&c->remote->host.id)`.  Should that also imply a template?

**Comment by letoams** [comment]
Yes,

the above comment of mine ate characters.
I meant to write rightprotoport=any   (With percentage before the any)

**Comment by cagney** [comment]
test replaced
