### ISSUE TITLE
journalctl is not always in /usr/bin/journalctl

### ISSUE THREAD

**Issue by jobevers** [libreswan/libreswan#197]
journalctl is not always in /usr/bin/journalctl.  On my system, its /bin/journalctl.

This causes the barf script to not call journalctl to get logs:
https://github.com/libreswan/libreswan/blob/master/programs/barf/barf.in#L412

```
jobevers@test-vpn:~$ uname -a
Linux test-vpn 4.15.0-1014-azure #14~16.04.1-Ubuntu SMP Thu Jun 14 15:42:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
jobevers@test-vpn:~$ which journalctl
/bin/journalctl
```

**Comment by letoams** [comment]
Fixed, will be in 3.26. thanks for the report
