### ISSUE TITLE
allow `subnet=1.2.3.4` and perhaps `subnet=%defaultroute`

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1977]
Currently, subnet requires a `/` as in `1.2.3.4/32` but I don't see the benefit of being so strict.

**Comment by cagney** [comment]
oh, `subnet=%defaultroute` is so that subnet==host can be specified explicitly.

**Comment by cagney** [comment]
it turns out selectors already accept addresses which means that:
   leftsubnet=1::2,1.2.3.4
is accepted, but:
   keyexchange=ikev1
   leftsubnet=1::2
is not

**Comment by cagney** [comment]
leave %defaultroute for later

**Comment by letoams** [comment]
I don’t understand what subnet=%defaultroute would mean. Defaultroute points to the gateway which per definition cannot be the subnet ?

**Comment by cagney** [comment]
left=%defaultroute sets it to the interface pointing at the gateway (I find the name strange)
subnet= should have some equivalent so that subnet=${host} can be made explicit while being set automatically

**Comment by letoams** [comment]
On Wed, 18 Dec 2024, cagney wrote:

> left=%defaultroute sets it to the interface pointing at the gateway (I find the name strange)
> subnet= should have some equivalent so that subnet=${host} can be made explicit while being set automatically

You mean like the current subnet=${host} default? :P
