### ISSUE TITLE
Ikev2  issue

### ISSUE THREAD

**Issue by amebrahimi** [libreswan/libreswan#198]
Hello guys. I have a problem Connecting to my IKEV2 on the server and this is the error

```
"l2tp-psk"[2] 5.119.230.123 #2: sending unencrypted notification v2N_AUTHENTICATION_FAILED to 5.119.230.123:47313
Jul 31 11:48:45 Family pluto[5090]: "l2tp-psk"[2] 5.119.230.123 #2: certificate verified OK: O=Amir,CN=myClient
Jul 31 11:48:45 Family pluto[5090]: "l2tp-psk"[2] 5.119.230.123 #2: No matching subjectAltName found
Jul 31 11:48:45 Family pluto[5090]: "l2tp-psk"[2] 5.119.230.123 #2: certificate does not contain ID_IP subjectAltName=5.119.230.123
Jul 31 11:48:45 Family pluto[5090]: "l2tp-psk"[2] 5.119.230.123 #2: Peer public key SubjectAltName does not match peer ID for this connection
Jul 31 11:48:45 Family pluto[5090]: "l2tp-psk"[2] 5.119.230.123 #2: Peer ID 'CN=myClient, O=Amir' mismatched on first found connection and no better connection found
Jul 31 11:48:45 Family pluto[5090]: | ikev2_parent_inI2outR2_tail returned STF_FAIL with v2N_AUTHENTICATION_FAILED
```

I have submitted an issue in this [page](https://github.com/hwdsl2/setup-ipsec-vpn/issues/429) to which is using liberswan.

Could anyone please help me to solve my problem

Thank you

**Comment by letoams** [comment]
On Sun, 5 Aug 2018, Amir Mahmoud wrote:

> Hello guys. I have a problem Connecting to my IKEV2 on the server and this is the error
> 
> "l2tp-psk"[2] 5.119.230.123 #2: sending unencrypted notification v2N_AUTHENTICATION_FAILED to 5.119.230.123:47313
> Jul 31 11:48:45 Family pluto[5090]: "l2tp-psk"[2] 5.119.230.123 #2: certificate verified OK: O=Amir,CN=myClient
> Jul 31 11:48:45 Family pluto[5090]: "l2tp-psk"[2] 5.119.230.123 #2: No matching subjectAltName found
> Jul 31 11:48:45 Family pluto[5090]: "l2tp-psk"[2] 5.119.230.123 #2: certificate does not contain ID_IP subjectAltName=5.
> 119.230.123
> Jul 31 11:48:45 Family pluto[5090]: "l2tp-psk"[2] 5.119.230.123 #2: Peer public key SubjectAltName does not match peer I
> D for this connection
> Jul 31 11:48:45 Family pluto[5090]: "l2tp-psk"[2] 5.119.230.123 #2: Peer ID 'CN=myClient, O=Amir' mismatched on first fo
> und connection and no better connection found
> Jul 31 11:48:45 Family pluto[5090]: | ikev2_parent_inI2outR2_tail returned STF_FAIL with v2N_AUTHENTICATION_FAILED

If you use an ID based on IP, you must add a SubjectAltName (SAN) of IP:a.b.c.d to your
certificate. But usually people use FQDN's which are already a SAN in
the certificate of type DNS:www.example.com.

Paul

**Comment by amebrahimi** [comment]
Hi,
If you mean by SubjectAltName I have tried these two methods both didn't work
```
certutil -S -c "Example CA" -n "$PUBLIC_IP" -s "O=Example,CN=$PUBLIC_IP" -k rsa -g 4096 -v 36 -d sql:/etc/ipsec.d -t ",," --keyUsage digitalSignature,keyEncipherment --extKeyUsage serverAuth --extSAN "ip:1.2.3.4,dns:me.example.com"
```
```
certutil -S -c "Example CA" -n "$PUBLIC_IP" -s "O=Example,CN=$PUBLIC_IP" -k rsa -g 4096 -v 36 -d sql:/etc/ipsec.d -t ",," --keyUsage digitalSignature,keyEncipherment --extKeyUsage serverAuth --extSAN "dns:me.example.com"
```

**Comment by letoams** [comment]
Then please provide updated logs to show the new problem

**Comment by amebrahimi** [comment]
```
Aug 08 19:14:04 Family pluto[1559]: "l2tp-psk"[6] 5.119.116.154 #16: Peer ID 'CN=myVpn, O=Prince' mismatched on first found connection and no better connection found
Aug 08 19:14:04 Family pluto[1559]: | ikev2_parent_inI2outR2_tail returned STF_FAIL with v2N_AUTHENTICATION_FAILED
Aug 08 19:14:04 Family pluto[1559]: "l2tp-psk"[6] 5.119.116.154 #16: sending unencrypted notification v2N_AUTHENTICATION_FAILED to 5.119.116.154:61247
Aug 08 19:14:05 Family pluto[1559]: "l2tp-psk"[6] 5.119.116.154 #16: certificate verified OK: O=Prince,CN=myVpn
Aug 08 19:14:05 Family pluto[1559]: "l2tp-psk"[6] 5.119.116.154 #16: No matching subjectAltName found
Aug 08 19:14:05 Family pluto[1559]: "l2tp-psk"[6] 5.119.116.154 #16: certificate does not contain ID_IP subjectAltName=5.119.116.154
Aug 08 19:14:05 Family pluto[1559]: "l2tp-psk"[6] 5.119.116.154 #16: Peer public key SubjectAltName does not match peer ID for this connection
Aug 08 19:14:05 Family pluto[1559]: "l2tp-psk"[6] 5.119.116.154 #16: Peer ID 'CN=myVpn, O=Prince' mismatched on first found connection and no better connection found
Aug 08 19:14:05 Family pluto[1559]: | ikev2_parent_inI2outR2_tail returned STF_FAIL with v2N_AUTHENTICATION_FAILED
Aug 08 19:14:05 Family pluto[1559]: "l2tp-psk"[6] 5.119.116.154 #16: sending unencrypted notification v2N_AUTHENTICATION_FAILED to 5.119.116.154:61247
```
these are the logs

**Comment by letoams** [comment]
Configure the peer with leftid=@fwdn and not with %fromcert

**Comment by amebrahimi** [comment]
Changed it to

```
conn ikev2-cp
  left=%defaultroute
  leftcert=$PUBLIC_IP
  leftid=@$PUBLIC_IP
  leftsendcert=always
  leftsubnet=0.0.0.0/0
  leftrsasigkey=%cert
  right=%any
  rightid=@fwdn
  rightaddresspool=192.168.43.10-192.168.43.250
  rightca=%same
  rightrsasigkey=%cert
  narrowing=yes
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
  auto=add
  ikev2=insist
  rekey=no
  fragmentation=yes
  ike=3des-sha1,3des-sha2,aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024
  phase2alg=3des-sha1,3des-sha2,aes-sha1,aes-sha2
  modecfgdns1=8.8.8.8
  modecfgdns2=8.8.4.4
  encapsulation=yes
```

still get this error 

```
Aug 08 19:38:03 Family pluto[9327]: "l2tp-psk"[1] 5.119.116.154 #1: Peer ID 'CN=myVpn, O=Prince' mismatched on first found connection and no better connection found
Aug 08 19:38:03 Family pluto[9327]: | ikev2_parent_inI2outR2_tail returned STF_FAIL with v2N_AUTHENTICATION_FAILED
Aug 08 19:38:03 Family pluto[9327]: "l2tp-psk"[1] 5.119.116.154 #1: sending unencrypted notification v2N_AUTHENTICATION_FAILED to 5.119.116.154:61251
Aug 08 19:38:04 Family pluto[9327]: "l2tp-psk"[1] 5.119.116.154 #1: certificate verified OK: O=Prince,CN=myVpn
Aug 08 19:38:04 Family pluto[9327]: "l2tp-psk"[1] 5.119.116.154 #1: No matching subjectAltName found
Aug 08 19:38:04 Family pluto[9327]: "l2tp-psk"[1] 5.119.116.154 #1: certificate does not contain ID_IP subjectAltName=5.119.116.154
Aug 08 19:38:04 Family pluto[9327]: "l2tp-psk"[1] 5.119.116.154 #1: Peer public key SubjectAltName does not match peer ID for this connection
Aug 08 19:38:04 Family pluto[9327]: "l2tp-psk"[1] 5.119.116.154 #1: Peer ID 'CN=myVpn, O=Prince' mismatched on first found connection and no better connection found
Aug 08 19:38:04 Family pluto[9327]: | ikev2_parent_inI2outR2_tail returned STF_FAIL with v2N_AUTHENTICATION_FAILED
Aug 08 19:38:04 Family pluto[9327]: "l2tp-psk"[1] 5.119.116.154 #1: sending unencrypted notification v2N_AUTHENTICATION_FAILED to 5.119.116.154:61251
```

**Comment by letoams** [comment]
On Wed, 8 Aug 2018, Amir Mahmoud wrote:

> 
> Changed it to
> 
> conn ikev2-cp
>   left=%defaultroute
>   leftcert=$PUBLIC_IP
>   leftid=@$PUBLIC_IP

That should be leftif@FQDN

>   leftsendcert=always
>   leftsubnet=0.0.0.0/0
>   leftrsasigkey=%cert
>   right=%any
>   rightid=@fwdn

That should be rightid=%fromcert

Paul

**Comment by amebrahimi** [comment]
Thank you for your patient response and sorry for my dumbness I have changed them to my FQDN.
But still, I can't connect to the server. And it is not connecting to the server and it is not creating log in the systemctl status ipsec.service. Where else can I find the logs of the program?

**Comment by letoams** [comment]
On Wed, 8 Aug 2018, Amir Mahmoud wrote:

> Thank you for your patient response and sorry for my dumbness I have changed them to my FQDN.
> But still, I can't connect to the server. And it is not connecting to the server and it is not creating log in the systemctl status
> ipsec.service. Where else can I find the logs of the program?

Does the FQDN actually point to the hostname of your vpn server?

Just to re-clarify,

If my vpn server is vpn.nohats.ca
Then the vpn server cert must have a SAN of DNS:vpn.nohats.ca
The vpn.nohats.ca must use leftid=@vpn.nohats.ca (and not an IP address!)
The vpn clients must configure the remote as "vpn.nohats.ca"
   (of vpn client is libreswan that means right=vpn.nohats.ca with rightid=@vpn.nohats.ca)

You should not specify the remote vpn server by IP address.

Paul

**Comment by amebrahimi** [comment]
Yes, my domain is pointing to my server.
With your help, I have configured the server. now I am getting this error:
```
Aug 09 16:34:42 Family pluto[10977]: packet from 5.119.80.221:7265: received and ignored empty informational notification payload
```

**Comment by letoams** [comment]
On Thu, 9 Aug 2018, Amir Mahmoud wrote:

> Yes, my domain is pointing to my server.
> With your help, I have configured the server. now I am getting this error:
> 
> Aug 09 16:34:42 Family pluto[10977]: packet from 5.119.80.221:7265: received and ignored empty informational notification payload

That is not enough context for me to say anything.

Paul

**Comment by amebrahimi** [comment]
What more do you need?

**Comment by letoams** [comment]
On Thu, 9 Aug 2018, Amir Mahmoud wrote:

> What more do you need?

The regular logs on the server of the entire handshake attempt from the clients?

**Comment by amebrahimi** [comment]
Ok where can I get them from?

**Comment by amebrahimi** [comment]
Thank you for Your time my problem is solved. I solved my problem using this [site](https://blog.techinline.com/2018/06/01/vpn-stuck-on-connecting-windows-10/). Thank you for your patient answers. Wish you luck and all the best.

Amir Mahmoud

**Comment by gjie680** [comment]
https://github.com/libreswan/libreswan/issues/198
