### ISSUE TITLE
Received the Delete SA right after Quick_R2 IPsec SA established

### ISSUE THREAD

**Issue by ochbob** [libreswan/libreswan#199]
Hello,

I can't figure out this issue

> Aug  4 11:14:30 LINOLOGY pluto[15154]: "l2tp-psk"[15] 176.XXX #16: STATE_QUICK_R2: IPsec SA established transport mode {ESP/NAT=>0xf7e25034 <0xfde2d90a xfrm=AES_CBC_128-HMAC_SHA1_96 NATOA=192.168.1.34 NATD=176.XXX:4500 DPD=active}
> Aug  4 11:14:30 LINOLOGY pluto[15154]: "l2tp-psk"[15] 176.XXX #15: received Delete SA(0xf7e25034) payload: deleting IPSEC State #16

I'm behind NAT router, is that maybe the issue ?

I can reproduce from iOS/Android or windows client with registery key changed.

Any ideas ? 

Thank you !

ipsec.conf

````
version 2.0

config setup
  virtual-private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!192.168.42.0/24,%v4:!192.168.43.0/24
  protostack=netkey
  interfaces=%defaultroute
  uniqueids=no

conn shared
  left=192.168.1.100
  leftid=public_IP
  right=%any
  encapsulation=yes
  authby=secret
  pfs=no
  rekey=no
  keyingtries=5
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
  ike=3des-sha1,3des-sha2,aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024
  phase2alg=3des-sha1,3des-sha2,aes-sha1,aes-sha2,aes256-sha2_512
  sha2-truncbug=yes

conn l2tp-psk
  auto=add
  leftprotoport=17/1701
  rightprotoport=17/%any
  type=transport
  phase2=esp
  also=shared

conn xauth-psk
  auto=add
  leftsubnet=0.0.0.0/0
  rightaddresspool=192.168.43.10-192.168.43.250
  modecfgdns1=192.168.1.100
  modecfgdns2=
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=file
  ike-frag=yes
  ikev2=never
  cisco-unity=yes
  also=shared
```

**Comment by letoams** [comment]
On Mon, 13 Aug 2018, ochbob wrote:

> I can't figure out this issue
>
>       Aug 4 11:14:30 LINOLOGY pluto[15154]: "l2tp-psk"[15] 176.XXX #16: STATE_QUICK_R2: IPsec SA established
>       transport mode {ESP/NAT=>0xf7e25034 <0xfde2d90a xfrm=AES_CBC_128-HMAC_SHA1_96 NATOA=192.168.1.34
>       NATD=176.XXX:4500 DPD=active}
>       Aug 4 11:14:30 LINOLOGY pluto[15154]: "l2tp-psk"[15] 176.XXX #15: received Delete SA(0xf7e25034) payload:
>       deleting IPSEC State #16

The other end is hanging up. It should tell you why.

Note when setting up a modern remote access VPN, you should be using
IKEv2, not IKEv1-XAUTH.

Paul

**Comment by ochbob** [comment]
Thank you for your answer, sorry but is english is non native for me, what do you mean by:

> The other end is hanging up. It should tell you why.

?

**Comment by ochbob** [comment]
I think, I understand what you mean.

When I try to connect from my iPhone client, I got this:

https://discussions.apple.com/servlet/JiveServlet/downloadImage/2-31255022-799119/VPN+Connection+Error.jpg

**Comment by letoams** [comment]
On Tue, 14 Aug 2018, ochbob wrote:

> 
> I think, I understand what you mean.
> 
> When I try to connect from my iPhone client, I got this:
> 
> https://discussions.apple.com/servlet/JiveServlet/downloadImage/2-31255022-799119/VPN+Connection+Error.jpg

If you got disconnected by libreswan, there should be a log entry
telling you why. These two problems are not neccessarilly the same
problem.

Paul

**Comment by ochbob** [comment]
It was a DNS issue and no related to libreswan.

`Aug 14 23:23:36 LINOLOGY pppd[24973]: invalid address parameter 'noccp' for ms-dns option`

I can't use my own local DNS server ?

Any way, thank you :)

**Comment by ochbob** [comment]
Issue can be closed :)

We can't leave blank 'ms-dns' option into pppd option (xl2tpd)

After that, my local DNS and VPN works great.

Thank you  !
