### ISSUE TITLE
ESP DH algorithm DH21 is invalid as PFS policy is disabled

### ISSUE THREAD

**Issue by stvortiz** [libreswan/libreswan#200]
Hello, 

I recently upgraded to version 3.25, however I'm having a bit of a problem with some connections. 

In particular the connections that have pfs disabled don't work I always have the same error: 

Failed to add connection "xxxxxxxxxxxx", esp="aes256-sha2_512;dh21" is invalid: ESP DH algorithm DH21 is invalid as PFS policy is disabled

This is my configuration:

```
conn xxxxxxxxxxxx
        authby=rsasig
        type=tunnel
        ikev2=insist
        ike=aes256-sha2_512;dh21
        phase2alg=aes256-sha2_512;dh21
        pfs=no
        left=xxxxxxxxxxxx
        leftid=@xxxxxxxxxxxx
        leftnexthop=%defaultroute
        leftupdown="ipsec _updown --route yes"
        leftrsasigkey=XXXXXXXXX
        right=xxxxxxxxxxxx
        rightnexthop=%defaultroute
        rightrsasigkey=XXXXXXXXX

conn xxxxxxxxxxxx
        also=xxxxxxxxxxxx
        leftsubnet=xxxxxxxxxxxx
        rightsubnet=xxxxxxxxxxxx
        auto=start

```
When I change to pfs=yes, it works perfectly.  However I have connections where I don't control both ends. 

I have the same problem no matter the cipher that I use.  I have seen the following errors: 

ESP DH algorithm DH21 is invalid as PFS policy is disabled
ESP DH algorithm DH20 is invalid as PFS policy is disabled
ESP DH algorithm MODP2048 is invalid as PFS policy is disabled
ESP DH algorithm MODP1536 is invalid as PFS policy is disabled
ESP DH algorithm MODP1024 is invalid as PFS policy is disabled

For the connections that cannot have pfs on both ends I had to downgrade to 3.21 which is working fine. 

Is there any documentation about this change or a workaround. 

Thanks

**Comment by bleve** [comment]
pfs=no ivnalidates dh group for esp/phase2alg. So there is no "valid combinations".

**Comment by stvortiz** [comment]
Thanks a lot, 

That makes total sense.  I will proceed to update my configurations.

**Comment by letoams** [comment]
fixed. will be in 3.26 where the DH will be ignored if pfs=no
