### ISSUE TITLE
IKEv1 does not support DH algorithm DH19/20/21 - PFS = yes failed.

### ISSUE THREAD

**Issue by qiuhez** [libreswan/libreswan#201]
Hello,

I'm using Libreswan of version 3.23(Linux Libreswan 3.23 (netkey) on 4.15.0-29-generic). And I'm having a bit of a problem with some connections when using DH19/20/21 for pfs.
 pfs=yes is kept.

ike = aes256-sha512;dh21 
phase2alg = aes192-sha384          // it works well

but if it was changed to 
ike = aes256-sha512;dh21 
phase2alg = aes192-sha384;dh21          // connections can not setup. No communications sent out.

Is there any documentation about usage?

**Comment by letoams** [comment]
On Mon, 20 Aug 2018, qiuhez wrote:

> 
> I'm using Libreswan of version 3.23(Linux Libreswan 3.23 (netkey) on 4.15.0-29-generic). And I'm having a bit of a problem with some
> connections when using DH19/20/21 for pfs.
> pfs=yes is kept.
> 
> ike = aes256-sha512;dh21
> phase2alg = aes192-sha384 // it works well
> 
> but if it was changed to
> ike = aes256-sha512;dh21
> phase2alg = aes192-sha384;dh21 // connections can not setup.

Can you please try if the problem is solved with 3.25 ? I know the pfs
handling changed a little bit.

Paul

**Comment by qiuhez** [comment]
Thank you so much for your reply.I will install 3.25 and try again.Best regardsqiuhez-------- 原始邮件 --------主题：Re: [libreswan/libreswan] ESP DH algorithm DH19/20/21 as PFS = yes failed. (#201)发件人："Paul Wouters (libreswan)" 收件人：libreswan/libreswan 抄送：qiuhez ,Author On Mon, 20 Aug 2018, qiuhez wrote:

> 
> I'm using Libreswan of version 3.23(Linux Libreswan 3.23 (netkey) on 4.15.0-29-generic). And I'm having a bit of a problem with some
> connections when using DH19/20/21 for pfs.
> pfs=yes is kept.
> 
> ike = aes256-sha512;dh21
> phase2alg = aes192-sha384 // it works well
> 
> but if it was changed to
> ike = aes256-sha512;dh21
> phase2alg = aes192-sha384;dh21 // connections can not setup.

Can you please try if the problem is solved with 3.25 ? I know the pfs
handling changed a little bit.

Paul


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/libreswan/libreswan","title":"libreswan/libreswan","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/libreswan/libreswan"}},"updates":{"snippets":[{"icon":"PERSON","message":"@letoams in #201: On Mon, 20 Aug 2018, qiuhez wrote:\n\n\u003e \n\u003e I'm using Libreswan of version 3.23(Linux Libreswan 3.23 (netkey) on 4.15.0-29-generic). And I'm having a bit of a problem with some\n\u003e connections when using DH19/20/21 for pfs.\n\u003e pfs=yes is kept.\n\u003e \n\u003e ike = aes256-sha512;dh21\n\u003e phase2alg = aes192-sha384 // it works well\n\u003e \n\u003e but if it was changed to\n\u003e ike = aes256-sha512;dh21\n\u003e phase2alg = aes192-sha384;dh21 // connections can not setup.\n\nCan you please try if the problem is solved with 3.25 ? I know the pfs\nhandling changed a little bit.\n\nPaul\n"}],"action":{"name":"View Issue","url":"https://github.com/libreswan/libreswan/issues/201#issuecomment-414739434"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/libreswan/libreswan/issues/201#issuecomment-414739434",
"url": "https://github.com/libreswan/libreswan/issues/201#issuecomment-414739434",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [libreswan/libreswan] ESP DH algorithm DH19/20/21 as PFS = yes failed. (#201)",
"sections": [
{
"text": "",
"activityTitle": "**Paul Wouters (libreswan)**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@letoams",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"libreswan/libreswan\",\n\"issueId\": 201,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"libreswan/libreswan\",\n\"issueId\": 201\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/libreswan/libreswan/issues/201#issuecomment-414739434"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 370451920\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by qiuhez** [comment]
I tried the libreswan3.25, andthe result is the same.Then I added "ikev2 = insist"，IKE_SA_INIT request can be sent out.Does that mean dh19/20/21 for PFS is only supported on ikev2？But what can we do if the remote only support ikev1？Thanks and regards,qiuhez

**Comment by letoams** [comment]
On Tue, 28 Aug 2018, qiuhez wrote:

> Subject: Re: [libreswan/libreswan] ESP DH algorithm DH19/20/21 as PFS = yes
>     failed. (#201)
> 
> I tried the libreswan3.25, andthe result is the same.Then I added "ikev2 = insist"，IKE_SA_INIT request can be sent out.Does that mean
> dh19/20/21 for PFS is only supported on ikev2？But what can we do if the remote only support ikev1？Thanks and regards,qiuhez

Oh yes. That has only been implemented for IKEv2.

It is not very commonly used for IKEv1, so we haven't put the effort in
to also add it to IKEv1. When using IKEv1 I would recommend DH14.

Paul

**Comment by qiuhez** [comment]
All right. Thank you so much for your clarification.
