### ISSUE TITLE
Libreswan 3.26 build errors

### ISSUE THREAD

**Issue by hwdsl2** [libreswan/libreswan#202]
First, thank you for releasing Libreswan 3.26. I tested it on Ubuntu 18.04, 16.04 and 14.04, Debian 9 and 8, CentOS 7 and 6, and encountered compilation errors on all the Ubuntu and Debian versions above. It compiled OK on CentOS 7 and 6.

Ubuntu 18.04:
```
/opt/src/libreswan-3.26/programs/pluto/keys.c:75:10: fatal error: blapi.h: No such file or directory
 #include <blapi.h>
          ^~~~~~~~~
compilation terminated.
../../mk/depend.mk:34: recipe for target 'keys.o' failed
make[3]: *** [keys.o] Error 1
```

Ubuntu 16.04:
```
/usr/bin/ld: cannot find -lfreebl
collect2: error: ld returned 1 exit status
../../mk/program.mk:121: recipe for target 'pluto' failed
make[3]: *** [pluto] Error 1
```

Ubuntu 14.04:
```
/opt/src/libreswan-3.26/programs/pluto/keys.c:75:19: fatal error: blapi.h: No such file or directory
 #include <blapi.h>
                   ^
compilation terminated.
make[3]: *** [keys.o] Error 1
```

Debian 9 AND Debian 8:
```
/opt/src/libreswan-3.26/lib/libswan/ike_alg_dh.c:323:13: error: ‘SEC_OID_CURVE25519’ undeclared here (not in a function)
  .nss_oid = SEC_OID_CURVE25519,
             ^~~~~~~~~~~~~~~~~~
../../mk/depend.mk:34: recipe for target 'ike_alg_dh.o' failed
make[3]: *** [ike_alg_dh.o] Error 1
```

Please look into this. I noticed that Ubuntu 18.04 (Bionic) and 14.04 (Trusty) has a `libnss3-dev` package that does not contain `blapi.h`. See [1] [2]. Ubuntu 16.04 (Xenial) contains this file [3] in the package but still throws an error.

[1] https://packages.ubuntu.com/bionic/amd64/libnss3-dev/filelist
[2] https://packages.ubuntu.com/trusty/amd64/libnss3-dev/filelist
[3] https://packages.ubuntu.com/xenial/amd64/libnss3-dev/filelist

**Comment by letoams** [comment]
On Mon, 17 Sep 2018, Lin Song wrote:

> First, thank you for releasing Libreswan 3.26. I tested it on Ubuntu 18.04, 16.04 and 14.04, Debian 9 and 8, CentOS
> 7 and 6, and encountered compilation errors on all the Ubuntu and Debian versions above. It compiled OK on CentOS 7
> and 6.
> 
> Ubuntu 18.04:
> 
> /opt/src/libreswan-3.26/programs/pluto/keys.c:75:10: fatal error: blapi.h: No such file or directory
>  #include <blapi.h>
>           ^~~~~~~~~

You should be able to just delete that include line.

> /usr/bin/ld: cannot find -lfreebl

And you can delete linking against that too, just run:

 	sed -i "s/-lfreebl //" mk/config.mk

> Debian 9 AND Debian 8:
> 
> /opt/src/libreswan-3.26/lib/libswan/ike_alg_dh.c:323:13: error: ‘SEC_OID_CURVE25519’ undeclared here (not in a funct
> ion)
>   .nss_oid = SEC_OID_CURVE25519,
>              ^~~~~~~~~~~~~~~~~~
> ../../mk/depend.mk:34: recipe for target 'ike_alg_dh.o' failed
> make[3]: *** [ike_alg_dh.o] Error 1

Your nss/nspr might be too old there? You can compile with
USE_DH31=false on those systems.

Paul

**Comment by hwdsl2** [comment]
Thanks, will use the workarounds above (I see that they have been fixed in master).

**Comment by lljgithub** [comment]
i also meet this issue, and use "make all USE_DH31=false " to workarounds.
first i make clean,then do below cmd ,then it build succeed.
