### ISSUE TITLE
Vendor ID payload in logs

### ISSUE THREAD

**Issue by gizu** [libreswan/libreswan#204]
i found that after upgrade from  libreswan 3.16 to 3.23 from logs disapeared details about vendor id payloads, i.e.:

```
 received Vendor ID payload [Cisco-Unity]
 received Vendor ID payload [XAUTH]
 ignoring Vendor ID payload [Cisco VPN 3000 Series]
 received Vendor ID payload [Dead Peer Detection]
 received Vendor ID payload [FRAGMENTATION]
```

since upgrade to 3.23  i've got only logged: 

` ignoring unknown Vendor ID payload [... ]`

it's something wrong with package, or I missed some configuration change?

**Comment by letoams** [comment]
I’m not aware of such problems, maybe try 3.25 or 3.26 ?

**Comment by gizu** [comment]
on second server after upgrade from 3.15 to 3.26 result is exactly the same

both centos6


logs after update
# grep Vendor.ID /var/log/secure | cut -f 6- -d :   | sort | uniq
 ignoring unknown Vendor ID payload [699369228741c6d4ca094c93e242c9de19e7b7c60000000500000500]

before update

# grep Vendor.ID /var/log/secure-20180916 | cut -f 6- -d :   | sort | uniq

 ignoring unknown Vendor ID payload [699369228741c6d4ca094c93e242c9de19e7b7c60000000500000500]
 ignoring Vendor ID payload [draft-ietf-ipsec-nat-t-ike-02]
 ignoring Vendor ID payload [draft-ietf-ipsec-nat-t-ike-02_n]
 ignoring Vendor ID payload [draft-ietf-ipsec-nat-t-ike-03]
 ignoring Vendor ID payload [Openswan(project)]
 received Vendor ID payload [Dead Peer Detection]
 received Vendor ID payload [FRAGMENTATION]
 received Vendor ID payload [RFC 3947]

**Comment by letoams** [comment]
I see some of these have been changed from regular logs to debug only logs. eg:

| received Vendor ID payload [FRAGMENTATION]
| received Vendor ID payload [Dead Peer Detection]
| received Vendor ID payload [RFC 3947]
| Ignoring older NAT-T Vendor ID payload [draft-ietf-ipsec-nat-t-ike-03]
| ignoring Vendor ID payload [draft-ietf-ipsec-nat-t-ike-03]
| Ignoring older NAT-T Vendor ID payload [draft-ietf-ipsec-nat-t-ike-02_n]
| ignoring Vendor ID payload [draft-ietf-ipsec-nat-t-ike-02_n]
| Ignoring older NAT-T Vendor ID payload [draft-ietf-ipsec-nat-t-ike-02]
| ignoring Vendor ID payload [draft-ietf-ipsec-nat-t-ike-02]

You can add plutodebug=all to see them.

**Comment by gizu** [comment]
ok, thanks
