### ISSUE TITLE
What is the max measured network throughput we can achieve with Libreswan?

### ISSUE THREAD

**Issue by newnovice01** [libreswan/libreswan#207]
What is the max measured network throughput we can achieve with Libreswan?

Let's say we have 2 hosts with 100G NIC's connected to the same switch and can achieve 100G without any encryption. What are the limiting factors and when do we hit the limits of IPsec?

**Comment by letoams** [comment]
On Thu, 4 Oct 2018, newnovice01 wrote:

> What is the max measured network throughput we can achieve with Libreswan?
> 
> Let's say we have 2 hosts with 100G NIC's connected to the same switch and can achieve 100G without any encryption. What are
> the limiting factors and when do we hit the limits of IPsec?

It all depends on:

- Algorithms and key size (hint: use AES_GCM)
- How many CPUs and RAM
- NIC cards and config
- Number of IPsec SA's (1 SA is harder to distribute over CPUs, but also
   having 10s of thousands of SA's makes the lookup per packet slower)

If you are in 100G range, it might be worth looking at a dedicated IPsec
acceleration card, such as the Mellanox Innova or one of the Intel cards.

Paul

**Comment by newnovice01** [comment]
@letoams Thanks for the response. 

I don't have access to any Hardware accelerators, or the ability to do packet processing in user space with things like DPDK. 

Going off the example: https://libreswan.org/wiki/Benchmarking_and_Performance_testing 
result: 5.25 Gbits/sec IPsec AES_GCM128 (esp=aes_gcm128-null)
In the above example I assume we had 1 SA. If we have 3 SA's - can we get 15 Gbits/sec? 

CPU: 64 vCPU of Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz 
RAM: 480G 
NIC: 100G

What is the max range of throughput we know we can push with Libreswan? 20Gbit? 40Gbit?

**Comment by letoams** [comment]
It really depends on the hardware and the number of tunnels. It should be able to do 400gbps with the right hardware
