### ISSUE TITLE
What limits IPsec performnce in the wiki: Benchmarking_and_Performance_testing ?

### ISSUE THREAD

**Issue by newnovice01** [libreswan/libreswan#208]
https://libreswan.org/wiki/Benchmarking_and_Performance_testing

What are the factors that limit throughput in the iperf3 tests that are demonstrated in the wiki that reduce throughput from '9.78 Gbits/sec unencrypted without IPsec' to '5.25 Gbits/sec IPsec AES_GCM128 (esp=aes_gcm128-null)' ? 

Please can you help me understand and analyze this problem in depth?

**Comment by letoams** [comment]
On Thu, 4 Oct 2018, newnovice01 wrote:

> https://libreswan.org/wiki/Benchmarking_and_Performance_testing
> 
> What are the factors that limit throughput in the iperf3 tests that are demonstrated in the wiki that reduce throughput from
> '9.78 Gbits/sec unencrypted without IPsec' to '5.25 Gbits/sec IPsec AES_GCM128 (esp=aes_gcm128-null)' ?

Note those tests are old and newer kernels and hardware these days don't
neccessarilly disable GSO/GRO which is a large chunk of the speed
difference.

A lot of work has gone into IPsec acceleration in the last two years,
to support both crypto offload and whole packet offload.

Paul

**Comment by newnovice01** [comment]
If it is easy enough please can I get a guide to generate a valid benchmark with the latest Xeon CPU & 4.14 kernel? (any ballpark number we know how it can do in today's hardware & 4.14 kernel?)

Also more details on setting up this extra test:  
"We did some additional tests, but those are less accurate. using protoport= we could use multiple IPsec SA's (in the hope that it would distribute better) or have encrypted and unencrypted streams going.

two streams, one plaintext 8.64 Gbits/sec plaintext plus 1.24 Gbits/sec AES256-SHA1
two streams AES256-SHA1: 819 Mbits/sec plus 615 Mbits/sec (possibly was aes128)"

**Comment by newnovice01** [comment]
When does the kernel pretty much slow down with the encap/decap or encryption/packet switching at 4.14 or newer kernels? We should be able to establish some baselines, with some base configs?

I see transport mode is slower than tunnel mode by at-least 1-2Gbits/sec. 
Good: 
    type=tunnel
    esp=aes_gcm_b-null

No impact: 
    nhelpers=248
    keep-alive=12000

**Comment by letoams** [comment]
On Thu, 4 Oct 2018, newnovice01 wrote:

> When does the kernel pretty much slow down with the encap/decap or encryption/packet switching at 4.14 or newer kernels? We
> should be able to establish some baselines, with some base configs?

From what I understood from the IPsec kernel pepole, the slowdown with a
large number of IPsec tunnels is that the SPD lookup is linear instead
of like a radix tree or similar.

The other thing I mentioned was the crypto queue:

https://lore.kernel.org/patchwork/patch/853642/

That patch changed it from 100 to 1000 but that might still not be
enough for extra large servers. You can increase it by changing
the cryptd module parameter:

rmmod cryptd
modprobe cryptd cryptd_max_cpu_qlen=2048

> I see transport mode is slower than tunnel mode by at-least 1-2Gbits/sec.

That is odd. transport mode has a few less bytes over the wire, and
should be easier to create then a tunnel mode ip-in-ip packet. So I
wouldn't expect it to be slower.

> Good:
> type=tunnel
> esp=aes_gcm_b-null

Use esp=aes_gcm-null. The _a/_b/_c modifiers are for different
ICV lengths and even the original RFC author does not
recommend using the smaller ones. So stick to the default (which
is the same as _c). Also RFC 8221 promoted the 16 byte ICV (_c)
version to MUST while the others are left at MAY.

> No impact:
> nhelpers=248

nhelpers will only help if you have multiple cores and will only really
help for the DiffieHellman part of IKE. It will have zero impact on
kernel level ESP/IPsec packets.

> keep-alive=12000

This is also an IKE level configuration and has no impact since its goal
is to send a keepalive for idle links, which seems the opposite of what
you are doing :)

**Comment by letoams** [comment]
On Fri, 5 Oct 2018, newnovice01 wrote:

> That is useful. Would you assume that there is some throughput limitation per SA or per conn section config? I added 5 different IP's to the
> server host and added new configs (started 5 iperf3 servers), hit it with iperf from 1 client machine to 5 different ip's & unique ports -
> all on same server machine. Seems like per SA I can get 5 Gbits/sec. (if only 1 client is running i can get 6-7 Gbits/sec sometimes)

Using subnets= causes the conn to instantiate in multiple conns,
resulting in multiple IPsec SA's. You can see this quickly using

 	ipsec whack --trafficstatus

Also check /proc/net/xfrm_stat for any non-zero counters, which
would indicate some kind of problem resulting in packet drops
and reduced speed.

> That seems to be the ceiling.

Ensure using threads with iperf or that process becomes the limiting
factor.

Paul

**Comment by newnovice01** [comment]
To make my config file handling easier i was going to use: https://libreswan.org/wiki/Subnet_to_subnet_VPN_with_PSK with just the same subnet on left & right. Thanks for confirming this will still launch "resulting in multiple IPsec SA's" - this can confirm my doubt on limitation per SA.

ipsec.conf: 
config setup
     logfile=/var/log/pluto.log

conn mysubnet
     type=tunnel
     leftsubnet=192.0.1.0/24
     rightsubnet=192.0.1.0/24
     authby=secret
     replay-window=0
     esp=aes_gcm-null
     auto=start

That should work right? I will circle back with results.

**Comment by letoams** [comment]
On Fri, 5 Oct 2018, newnovice01 wrote:

> To make my config file handling easier i was going to use: https://libreswan.org/wiki/Subnet_to_subnet_VPN_with_PSK with just the same subnet
> on left & right. Thanks for confirming this will still launch "resulting in multiple IPsec SA's" - this can confirm my doubt on limitation
> per SA.

you cannot do that. A subnet cannot be at both ends!

> leftsubnet=192.0.1.0/24
> rightsubnet=192.0.1.0/24

Instead use:

leftsubnets=192.0.1.0/24,192.0.2.0/24
rightsubnets=10.0.1.0/24,10.0.2.0/24

to get 4 IPsec SA's

**Comment by newnovice01** [comment]
What is the expected latency to send 1 packet (RTT) with IPsec between 2 hosts that are on the same switch? How much overhead should we expect with IPSec? 

config: 
config setup
    logfile=/var/log/pluto.log

conn mytester1
    type=tunnel
    left=192.168.28.116
    right=192.168.26.50
    authby=secret
    auto=start
    replay-window=0
    esp=aes_gcm-null

I had no luck with the cryptd_max_cpu_qlen. I cannot unload it: 
rmmod: ERROR: Module cryptd is in use by: crypto_simd ablk_helper ghash_clmulni_intel aesni_intel

I am not sure how to check the current size since nothing shows up in dmesg. I just set it to: sudo modprobe cryptd && sudo modprobe cryptd cryptd_max_cpu_qlen=20480 - I did not see any speed up. The added latency is reducing my throughput on the link. 
 
https://libreswan.org/wiki/Cryptographic_Acceleration

Also how do ensure between the regular TCP application sending packets and the ESP layer encapsulating it - we are not going over the MTU & then getting into fragmentation of packets?

**Comment by letoams** [comment]
On Fri, 12 Oct 2018, newnovice01 wrote:

> What is the expected latency to send 1 packet (RTT) with IPsec between 2 hosts that are on the same switch? How much overhead should we expect with IPSec?

I don't have an answer for that.

> I had no luck with the cryptd_max_cpu_qlen. I cannot unload it:
> rmmod: ERROR: Module cryptd is in use by: crypto_simd ablk_helper ghash_clmulni_intel aesni_intel

It depends on your linux flavour on how to set a higher value, for
example it might be done by adding the module plus parameter to
something like /etc/modprobe.conf or /etc/modprobe.d/

Or maybe it is needed in the initrd/ramdisk already, so perhaps you
should pass it as kernel parameter?

> I am not sure how to check the current size since nothing shows up in dmesg.

If it does not report the size, it means you have an old kernel and the
value is set and hardcoded to 100 or 1000 depending on the version. The
version that can set the parameter for the module always prints the
value when the module is loaded. So you for sure have a small enough
queue as either 100 or 1000.

> Also how do ensure between the regular TCP application sending packets and the ESP layer encapsulating it - we are not going over the MTU & then getting into fragmentation of packets?

https://libreswan.org/wiki/FAQ#My_ssh_sessions_hang_or_connectivity_is_very_slow

Paul

**Comment by newnovice01** [comment]
kernel being used here is: 4.14.67 

4.9 onwards seems like it is 1000 from -> https://github.com/intel/linux-intel-4.9/blob/master/crypto/cryptd.c#L35 

Knowing how IPtables sucks at performance I would stay away from setting MSS in IPTables. Especially when trying to do a lot of packets or a lot of throughput. 

I tried with ip route command, had some other issue with that: 
ip route add 172.31.16.0/20 via 172.31.16.1 dev eth0 advmss 8941 

Thanks for all the replies. This is useful.

**Comment by letoams** [comment]
On Sun, 14 Oct 2018, newnovice01 wrote:

> kernel being used here is: 4.14.67
> 
> 4.9 onwards seems like it is 1000 from -> https://github.com/intel/linux-intel-4.9/blob/master/crypto/cryptd.c#L35

1000 is not enough for 10gbps. You still need to increase it, and also
increase or disable the replay-window.

> Knowing how IPtables sucks at performance I would stay away from setting MSS in IPTables. Especially when trying to do a lot of packets or a
> lot of throughput.

setting an MTU on interface or route might not help you, if machines are
in the same LAN.

Paul

**Comment by letoams** [comment]
work is happening to speed things up in upstream kernel. We will update our docs on the wiki once we have some updated numbers with the latest (100gbps hardware)
