### ISSUE TITLE
3.26 build from source fails on: "‘ub_ctx_add_ta_file’ discards ‘const’ qualifier from pointer target type [-Werror]    ugh = ub_ctx_add_ta_file(dns_ctx, rootfile);"

### ISSUE THREAD

**Issue by newnovice01** [libreswan/libreswan#209]
Linux 4.14.62-65.117.x86_64

[login libreswan-3.26]$ make all 
make[1]: Entering directory `/home/user/libreswan-3.26/lib'
make[2]: Entering directory `/home/user/libreswan-3.26/lib/libswan'
cc -I../../lib/libcrypto -I/home/user/libreswan-3.26/include/unbound -DKLIPS -DPFKEYV2  -I. -I/home/user/libreswan-3.26/linux/include -I/home/user/libreswan-3.26 -I/usr/include/nss3 -I/usr/include/nspr4   -I/home/user/libreswan-3.26/include  -DTimeZoneOffset=timezone -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -Dlinux -DHAVE_UDPFROMTO=1 -DHAVE_IP_PKTINFO=1 -std=gnu99 -g -Werror -Wall -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wmissing-declarations -Wredundant-decls -Wnested-externs -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-all -fno-strict-aliasing -fPIE -DPIE -DKLIPS -DNETKEY_SUPPORT -DPFKEY -DUSE_DNSSEC -DDEFAULT_DNSSEC_ROOTKEY_FILE=\""/var/lib/unbound/root.key"\" -DUSE_NIC_OFFLOAD -DHAVE_LABELED_IPSEC -DLIBCURL -DHAVE_NM -DXAUTH_HAVE_PAM -DUSE_3DES -DUSE_AES -DUSE_CAMELLIA -DUSE_CHACHA -DUSE_DH2 -DUSE_DH31 -DUSE_MD5 -DUSE_SERPENT -DUSE_SHA1 -DUSE_SHA2 -DUSE_TWOFISH -DUSE_XCBC -DDEFAULT_RUNDIR=\"/run/pluto\" -DFIPSPRODUCTCHECK=\"/etc/system-fips\" -DIPSEC_CONF=\"/etc/ipsec.conf\" -DIPSEC_CONFDDIR=\"/etc/ipsec.d\" -DIPSEC_NSSDIR=\"/etc/ipsec.d\" -DIPSEC_CONFDIR=\"/etc\" -DIPSEC_EXECDIR=\"/usr/local/libexec/ipsec\" -DIPSEC_SBINDIR=\"/usr/local/sbin\" -DIPSEC_VARDIR=\"/var\" -DPOLICYGROUPSDIR=\"/etc/ipsec.d/policies\" -DIPSEC_SECRETS_FILE=\"/etc/ipsec.secrets\" -DFORCE_PR_ASSERT -DUSE_FORK=1 -DUSE_VFORK=0 -DUSE_DAEMON=0 -DUSE_PTHREAD_SETSCHEDPRIO=1 -DGCC_LINT -DALLOW_MICROSOFT_BAD_PROPOSAL -DHAVE_LIBCAP_NG  -DNSS_REQ_AVA_COPY  -I/home/user/libreswan-3.26/linux/include -I/home/user/libreswan-3.26/include -I/usr/include/nss3 -I/usr/include/nspr4    -pthread -DTimeZoneOffset=timezone -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -Dlinux -DHAVE_UDPFROMTO=1 -DHAVE_IP_PKTINFO=1 -std=gnu99 -g -Werror -Wall -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wmissing-declarations -Wredundant-decls -Wnested-externs -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-all -fno-strict-aliasing -fPIE -DPIE -DKLIPS -DNETKEY_SUPPORT -DPFKEY -DUSE_DNSSEC -DDEFAULT_DNSSEC_ROOTKEY_FILE=\""/var/lib/unbound/root.key"\" -DUSE_NIC_OFFLOAD -DHAVE_LABELED_IPSEC -DLIBCURL -DHAVE_NM -DXAUTH_HAVE_PAM -DUSE_3DES -DUSE_AES -DUSE_CAMELLIA -DUSE_CHACHA -DUSE_DH2 -DUSE_DH31 -DUSE_MD5 -DUSE_SERPENT -DUSE_SHA1 -DUSE_SHA2 -DUSE_TWOFISH -DUSE_XCBC -DDEFAULT_RUNDIR=\"/run/pluto\" -DFIPSPRODUCTCHECK=\"/etc/system-fips\" -DIPSEC_CONF=\"/etc/ipsec.conf\" -DIPSEC_CONFDDIR=\"/etc/ipsec.d\" -DIPSEC_NSSDIR=\"/etc/ipsec.d\" -DIPSEC_CONFDIR=\"/etc\" -DIPSEC_EXECDIR=\"/usr/local/libexec/ipsec\" -DIPSEC_SBINDIR=\"/usr/local/sbin\" -DIPSEC_VARDIR=\"/var\" -DPOLICYGROUPSDIR=\"/etc/ipsec.d/policies\" -DIPSEC_SECRETS_FILE=\"/etc/ipsec.secrets\" -DFORCE_PR_ASSERT -DUSE_FORK=1 -DUSE_VFORK=0 -DUSE_DAEMON=0 -DUSE_PTHREAD_SETSCHEDPRIO=1 -DGCC_LINT -DALLOW_MICROSOFT_BAD_PROPOSAL -DHAVE_LIBCAP_NG \
	-MF ../../OBJ.linux.x86_64/lib/libswan/unbound.d \
	-MP -MMD -MT unbound.o \
	-o ../../OBJ.linux.x86_64/lib/libswan/unbound.o \
	-c /home/user/libreswan-3.26/lib/libswan/unbound.c
/home/user/libreswan-3.26/lib/libswan/unbound.c: In function ‘unbound_ctx_config’:
/home/user/libreswan-3.26/lib/libswan/unbound.c:111:3: error: passing argument 2 of ‘ub_ctx_add_ta_file’ discards ‘const’ qualifier from pointer target type [-Werror]
   ugh = ub_ctx_add_ta_file(dns_ctx, rootfile);
   ^
In file included from /home/user/libreswan-3.26/lib/libswan/unbound.c:34:0:
/usr/include/unbound.h:348:5: note: expected ‘char *’ but argument is of type ‘const char *’
 int ub_ctx_add_ta_file(struct ub_ctx* ctx, char* fname);
     ^
cc1: all warnings being treated as errors
make[3]: *** [unbound.o] Error 1
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/user/libreswan-3.26/lib/libswan'
make[1]: *** [recursive-all] Error 2
make[1]: Leaving directory `/home/user/libreswan-3.26/lib'
make: *** [recursive-all] Error 2
[login libreswan-3.26]$ 

installed: 
ldns.x86_64                          1.6.16-7.3
ldns-devel.x86_64                    1.6.16-7.3
unbound.x86_64                       1.4.20-23.3        
unbound-devel.x86_64                 1.4.20-23.3        
unbound-libs.x86_64                  1.4.20-23.3        
unbound-python.x86_64                1.4.20-23.3        
automake16.noarch                    1.6.3-18.6                 
bison.x86_64                         2.7-4.11                   
flex.x86_64                          2.5.37-3.13                
gcc.noarch                           4.8.5-1.22                 
gcc48.x86_64                         4.8.5-28.142            
libcap-ng-devel.x86_64               0.7.5-4.15                 
libcurl-devel.x86_64                 7.53.1-16.84               
libevent-devel.x86_64                2.0.21-4.19                
libgcc48.x86_64                      4.8.5-28.142            
libgcc72.x86_64                      7.2.1-2.59              
make.x86_64                          1:3.82-21.10            
nspr-devel.x86_64                    4.13.1-1.0.39              
nss-devel.x86_64                     3.28.4-12.80               
pam-devel.x86_64                     1.1.8-12.33                
pkgconfig.x86_64                     1:0.27.1-2.7            
xmlto.x86_64                         0.0.25-7.9               

wget https://download.libreswan.org/libreswan-3.26.tar.gz
-rw-rw-r-- 1 user user 3706205 Sep 17 02:53 libreswan-3.26.tar.gz

**Comment by letoams** [comment]
On Thu, 4 Oct 2018, newnovice01 wrote:

> Subject: [libreswan/libreswan] 3.26 build from source fails on:
>     "‘ub_ctx_add_ta_file’ discards ‘const’ qualifier from pointer target type
>     [-Werror]    ugh = ub_ctx_add_ta_file(dns_ctx, rootfile);" (#209)

Use git master or wait a few days for 3.27. Use compile with USE_DNSSEC=false

Paul

**Comment by newnovice01** [comment]
Thank you! that worked. 

in file: ./libreswan/mk/config.mk  - if anybody needs it.

**Comment by letoams** [comment]
On Thu, 4 Oct 2018, newnovice01 wrote:

> Thank you! that worked.
> 
> in file: ./libreswan/mk/config.mk - if anybody needs it.

You can place overrides in libreswan/Makefile.inc.local
So you can just use:

 	echo "USE_DNSSEC=false" > Makefile.inc.local

Then when you git pull you wouldn't ever get any conflicts because
we will never ship Makefile.inc.local.
