### ISSUE TITLE
http://www.freeswan.org (hosted by libreswan) does not offer https:// 

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#211]
It looks like http://www.freeswan.org/ is currently hosted by the libreswan project.

however, going to https://www.freeswan.org/ gives a certificate error, because an https://www.libreswan.org certificate is used.

Please enable https for https://www.freeswan.org/ as well!

**Comment by bleve** [comment]
Thank you, fixed.

**Comment by dkg** [comment]
fix confirmed.  thanks for the prompt action!
