### ISSUE TITLE
Help on this Pending Phase2 for site 2 site vpn [AWS ec2 (Linux Libreswan 3.23 (netey)) - cisco ASA] 

### ISSUE THREAD

**Issue by sekayasin** [libreswan/libreswan#219]
Hello there, any help with this
000 #9: "MyConnection/0x2":500 STATE_MAIN_I1 (sent MI1, expecting MR1); EVENT_v1_RETRANSMIT in 23s; nodpd; idle; import:admin initiate
000 #9: pending Phase 2 for "MyConnection/0x1" replacing #0
000 #9: pending Phase 2 for "MyConnection/0x2" replacing #0

**Comment by sekayasin** [comment]
@letoams here is my ipsec verify screenshot

Verifying installed system and configuration files

Version check and ipsec on-path                   	[OK]
Libreswan 3.23 (netkey) on 3.10.0-862.3.2.el7.x86_64
Checking for IPsec support in kernel              	[OK]
 NETKEY: Testing XFRM related proc values
         ICMP default/send_redirects              	[OK]
         ICMP default/accept_redirects            	[OK]
         XFRM larval drop                         	[OK]
Pluto ipsec.conf syntax                           	[OK]
Two or more interfaces found, checking IP forwarding	[OK]
Checking rp_filter                                	[OK]
Checking that pluto is running                    	[OK]
 Pluto listening for IKE on udp 500               	[OK]
 Pluto listening for IKE/NAT-T on udp 4500        	[OK]
 Pluto ipsec.secret syntax                        	[OK]
Checking 'ip' command                             	[OK]
Checking 'iptables' command                       	[OK]
Checking 'prelink' command does not interfere with FIPS	[OK]
Checking for obsolete ipsec.conf options          	[OK]

And my firewalld - firewall-cmd --list-all

public
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: ssh dhcpv6-client ipsec
  ports: 500/udp 4500/udp
  protocols:
  masquerade: yes
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
	rule protocol value="esp" accept
	rule protocol value="ah" accept


and here my configs ipsec.conf

         protostack=netkey
        # oe=off
        # exclude networks used on server side by adding %v4:!a.b.c.0/24
        # It seems that T-Mobile in the US and Rogers/Fido in Canada are
        # using 25/8 as "private" address space on their wireless networks.
        # This range has never been announced via BGP (at least up to 2015)
        virtual_private=%v4:M.N.O.P/32,%v4:Q.R.S.T/32 #are encryption Domain of my peer

conn  MyConnection
        authby=secret
        auto=start
        type=tunnel
        ## phase1 ##
        ike=aes256-sha1;modp2048
        keyexchange=ike
        ## phase2 ##
        phase2=esp
        phase2alg=aes256-sha1;modp2048
        compress=no
        pfs=yes
        left=%defaultroute
        leftid=A.B.C.D  #MyPublic Ip on AWS EC2
        leftsourceip=E.F.G.H .  #My private ip of my ec2 centos7 instance
        leftsubnet=E.F.G.H/32
        leftnexthop=%defaultroute
        ## MyPeer ##
        right=I.J.K.L #Public ip of the peer - cisco asa device
        rightsubnets={M.N.O.P/32,Q.R.S.T/32}
        ikelifetime=28800s
        salifetime=3600s
        aggrmode=no

my ipsec.secrets
A.B.C.D I.J.K.L: PSK "*&^%$3434"

Any pointer, ipsec auto --status 
pending phase2

thanks

**Comment by sekayasin** [comment]
@bleve the encryption domain are the LAN hosts behind the firewall i need access to.. i think they are the virtual private.. i have same setup which works on linode, surprisingly on aws its failling.. must be something with the firewall/or something.. @letoams @bleve any pointer in my configs above..

**Comment by bleve** [comment]
https://libreswan.org/man/ipsec.conf.5.html - search for virtual-private. It's all about alllowed networks for natted road warriors..

**Comment by sekayasin** [comment]
##Help No Traffic - Tunnel is finally up-- but no traffic - cannot ping my peer LAN Subnets
@bleve @letoams Finally i have managed to establish the connection with cisco asa, its dh group5 used at the cisco asa..., changed my side like this 

## phase1 ##
ike=aes256-sha1;dh5
phase2alg=aes256-sha1;dh5

Now the Tunnel is up, but no traffic.. i cannot ping my peer LAN

000 "MyConnection/0x2":   IKE algorithms: AES_CBC_256-HMAC_SHA1-MODP1536
000 "MyConnection/0x2":   IKE algorithm newest: AES_CBC_256-HMAC_SHA1-MODP1536
000 "MyConnection/0x2":   ESP algorithms: AES_CBC_256-HMAC_SHA1_96-MODP1536
000 "MyConnection/0x2":   ESP algorithm newest: AES_CBC_256-HMAC_SHA1_96; pfsgroup=MODP1536
000
000 Total IPsec connections: loaded 2, active 2
000
000 State Information: DDoS cookies not required, Accepting new IKE connections
000 IKE SAs: total(1), half-open(0), open(0), authenticated(1), anonymous(0)
000 IPsec SAs: total(2), authenticated(2), anonymous(0)
000
000 #2: "MyConnection/0x1":4500 STATE_QUICK_I2 (sent QI2, IPsec SA established); EVENT_SA_REPLACE in 734s; newest IPSEC; eroute owner; isakmp#1; idle; import:admin initiate
000 #2: "MyConnection/0x1" esp.bd6f5d5@I.J.K.L esp.e6e75a6@A.B.C.D tun.0@I.J.K.L tun.0@A.B.C.D ref=0 refhim=0 Traffic: ESPin=0B ESPout=4KB! ESPmax=4194303B
000 #1: "MyConnection/0x2":4500 STATE_MAIN_I4 (ISAKMP SA established); EVENT_SA_REPLACE in 25692s; newest ISAKMP; lastdpd=0s(seq in:0 out:0); idle; import:admin initiate
000 #3: "MyConnection/0x2":4500 STATE_QUICK_I2 (sent QI2, IPsec SA established); EVENT_SA_REPLACE in 524s; newest IPSEC; eroute owner; isakmp#1; idle; import:admin initiate
000 #3: "MyConnection/0x2" esp.be78561f@I.J.K.L esp.21e1d536@A.B.C.D tun.0@I.J.K.L tun.0@A.B.C.D ref=0 refhim=0 Traffic: ESPin=0B ESPout=1KB! ESPmax=4194303B
000
000 Bare Shunt list:
000
[root@ip-E-F-G-H  ~]# route -n
Kernel IP routing table
Destination     Gateway         Genmask              Flags Metric Ref    Use Iface
0.0.0.0             E.F.0.1             0.0.0.0                   UG     0      0        0 eth0
M.N.O.P           E.F.0.1             255.255.255.255 UGH  0      0        0 eth0
Q.R.S.T            E.F.0.1             255.255.255.255 UGH   0      0        0 eth0
E.F.0.0             0.0.0.0              255.255.240.0     U       0      0        0 eth0

[root@ip-E-F-G-H ~]#ping M.N.O.P
no reply

[root@ip-E-F-G-H ~]#ping Q.R.S.T
no reply

**Comment by letoams** [comment]
On Mon, 29 Oct 2018, sekayasin wrote:

> ##Help No Traffic - Tunnel is finally up-- but no traffic - cannot ping my peer LAN Subnets
> @bleve @letoams Finally i have managed to establish the connection with cisco asa, its dh group5 used at the cisco asa..., changed my side like this

> 000 #2: "MyConnection/0x1":4500 STATE_QUICK_I2 (sent QI2, IPsec SA established); EVENT_SA_REPLACE in 734s; newest IPSEC; eroute owner; isakmp#1; idle; import:admin initiate
> 000 #2: "MyConnection/0x1" esp.bd6f5d5@I.J.K.L esp.e6e75a6@A.B.C.D tun.0@I.J.K.L tun.0@A.B.C.D ref=0 refhim=0 Traffic: ESPin=0B ESPout=4KB! ESPmax=4194303B
> 000 #1: "MyConnection/0x2":4500 STATE_MAIN_I4 (ISAKMP SA established); EVENT_SA_REPLACE in 25692s; newest ISAKMP; lastdpd=0s(seq in:0 out:0); idle; import:admin initiate
> 000 #3: "MyConnection/0x2":4500 STATE_QUICK_I2 (sent QI2, IPsec SA established); EVENT_SA_REPLACE in 524s; newest IPSEC; eroute owner; isakmp#1; idle; import:admin initiate
> 000 #3: "MyConnection/0x2" esp.be78561f@I.J.K.L esp.21e1d536@A.B.C.D tun.0@I.J.K.L tun.0@A.B.C.D ref=0 refhim=0 Traffic: ESPin=0B ESPout=1KB! ESPmax=4194303B

Note you have ESPout counters of non-zero, and incoming byte counters of
zero. So it looks like either a firewall is blocking your outgoing
packets, or they are dropping packets or your incoming packets are
getting dropped.

Paul

**Comment by sekayasin** [comment]
@letoams thanks, any points on how i can finally have it working.. 

Now i disabled firewalld.. so im using iptables.. here is my iptables -L

[root@ip-E-F-G-H ~]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     udp  --  anywhere             anywhere             udp dpt:isakmp
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ipsec-nat-t
ACCEPT     udp  --  anywhere             anywhere             udp dpt:ipsec-nat-t

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by letoams** [comment]
On Mon, 29 Oct 2018, sekayasin wrote:

> @letoams thanks, any points on how i can finally have it working..
> 
> Now i disabled firewalld.. so im using iptables.. here is my iptables -L
> 
> [root@ip-E-F-G-H ~]# iptables -L
> Chain INPUT (policy ACCEPT)
> target prot opt source destination
> ACCEPT udp -- anywhere anywhere udp dpt:isakmp
> ACCEPT tcp -- anywhere anywhere tcp dpt:ipsec-nat-t
> ACCEPT udp -- anywhere anywhere udp dpt:ipsec-nat-t
> 
> Chain FORWARD (policy ACCEPT)
> target prot opt source destination
> ACCEPT all -- anywhere anywhere
> ACCEPT all -- anywhere anywhere
> 
> Chain OUTPUT (policy ACCEPT)
> target prot opt source destination

Looks okay but it could also be another machine dropping the packets

**Comment by sekayasin** [comment]
@letoams the machine is aws ec2 instance..
E.F.G.H is the private ip on the instance and A.B.C.D is the public ip of the ec2 instance.

is there is anything i have to tweak at the ec2 instance...  or any experience with libreswan on aws ec2 instance to connect to cisco asa.. any pointer.. thanks

**Comment by letoams** [comment]
Ec2 console / management interface has a firewall too. Enable protocol 50 and udp port 500 and 4500

**Comment by sekayasin** [comment]
Yes @letoams those were enabled, and also disabled the source/dest in networking.. now checking on the vpc region.. to update the routing table there ..

**Comment by sekayasin** [comment]
hello @letoams @bleve i have updated this Question here https://serverfault.com/questions/937855/aws-ec2-centos-7-with-libreswan-ipsec-tunnel-up-established-no-traffic-flow 
Kindly check on it, any pointers is highly appreciated.. thanks

**Comment by letoams** [comment]
this seems like configuration issues. if this is still an issue, please use the mailing list but stop anonimising as that leads to unreadable logs
