### ISSUE TITLE
Make fails on Linux: error: missing initializer for field ‘len’ of ‘chunk_t’ [-Werror=missing-field-initializers]

### ISSUE THREAD

**Issue by newnovice01** [libreswan/libreswan#223]
cc -I /home/ec2-user/libreswan/programs/pluto/linux-copy -I/home/ec2-user/libreswan/include/unbound -DTimeZoneOffset=timezone -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -Dlinux -DHAVE_UDPFROMTO=1 -DHAVE_IP_PKTINFO=1 -std=gnu99 -g -Werror -Wall -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wmissing-declarations -Wredundant-decls -Wnested-externs -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-all -fno-strict-aliasing -fPIE -DPIE -DNETKEY_SUPPORT -DPFKEY -DUSE_NIC_OFFLOAD -DHAVE_LABELED_IPSEC -DLIBCURL -DHAVE_NM -DXAUTH_HAVE_PAM -DUSE_3DES -DUSE_AES -DUSE_CAMELLIA -DUSE_CHACHA -DUSE_DH2 -DUSE_DH31 -DUSE_MD5 -DUSE_SERPENT -DUSE_SHA1 -DUSE_SHA2 -DUSE_TWOFISH -DUSE_XCBC -DDEFAULT_RUNDIR=\"/run/pluto\" -DFIPSPRODUCTCHECK=\"/etc/system-fips\" -DIPSEC_CONF=\"/etc/ipsec.conf\" -DIPSEC_CONFDDIR=\"/etc/ipsec.d\" -DIPSEC_NSSDIR=\"/etc/ipsec.d\" -DIPSEC_CONFDIR=\"/etc\" -DIPSEC_EXECDIR=\"/usr/local/libexec/ipsec\" -DIPSEC_SBINDIR=\"/usr/local/sbin\" -DIPSEC_VARDIR=\"/var\" -DPOLICYGROUPSDIR=\"/etc/ipsec.d/policies\" -DIPSEC_SECRETS_FILE=\"/etc/ipsec.secrets\" -DFORCE_PR_ASSERT -DUSE_FORK=1 -DUSE_VFORK=0 -DUSE_DAEMON=0 -DUSE_PTHREAD_SETSCHEDPRIO=1 -DGCC_LINT -DALLOW_MICROSOFT_BAD_PROPOSAL -DHAVE_LIBCAP_NG   -I/home/ec2-user/libreswan/include -I/home/ec2-user/libreswan/lib/libcrypto -I/usr/include/nss3 -I/usr/include/nspr4   -DNSS_REQ_AVA_COPY         -pthread -DTimeZoneOffset=timezone -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -Dlinux -DHAVE_UDPFROMTO=1 -DHAVE_IP_PKTINFO=1 -std=gnu99 -g -Werror -Wall -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wmissing-declarations -Wredundant-decls -Wnested-externs -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-all -fno-strict-aliasing -fPIE -DPIE -DNETKEY_SUPPORT -DPFKEY -DUSE_NIC_OFFLOAD -DHAVE_LABELED_IPSEC -DLIBCURL -DHAVE_NM -DXAUTH_HAVE_PAM -DUSE_3DES -DUSE_AES -DUSE_CAMELLIA -DUSE_CHACHA -DUSE_DH2 -DUSE_DH31 -DUSE_MD5 -DUSE_SERPENT -DUSE_SHA1 -DUSE_SHA2 -DUSE_TWOFISH -DUSE_XCBC -DDEFAULT_RUNDIR=\"/run/pluto\" -DFIPSPRODUCTCHECK=\"/etc/system-fips\" -DIPSEC_CONF=\"/etc/ipsec.conf\" -DIPSEC_CONFDDIR=\"/etc/ipsec.d\" -DIPSEC_NSSDIR=\"/etc/ipsec.d\" -DIPSEC_CONFDIR=\"/etc\" -DIPSEC_EXECDIR=\"/usr/local/libexec/ipsec\" -DIPSEC_SBINDIR=\"/usr/local/sbin\" -DIPSEC_VARDIR=\"/var\" -DPOLICYGROUPSDIR=\"/etc/ipsec.d/policies\" -DIPSEC_SECRETS_FILE=\"/etc/ipsec.secrets\" -DFORCE_PR_ASSERT -DUSE_FORK=1 -DUSE_VFORK=0 -DUSE_DAEMON=0 -DUSE_PTHREAD_SETSCHEDPRIO=1 -DGCC_LINT -DALLOW_MICROSOFT_BAD_PROPOSAL -DHAVE_LIBCAP_NG  -I../../include -I/usr/include/nss3 -I/usr/include/nspr4   -DNSS_REQ_AVA_COPY  \
	-MF ../../OBJ.linux.x86_64/programs/pluto/ikev2_message.d \
	-MP -MMD -MT ikev2_message.o \
	-o ../../OBJ.linux.x86_64/programs/pluto/ikev2_message.o \
	-c /home/ec2-user/libreswan/programs/pluto/ikev2_message.c
/home/ec2-user/libreswan/programs/pluto/ikev2_message.c: In function ‘open_v2SK_payload’:
/home/ec2-user/libreswan/programs/pluto/ikev2_message.c:231:3: error: missing initializer for field ‘len’ of ‘chunk_t’ [-Werror=missing-field-initializers]
   .payload.len = 0, /* computed at end; set here to silence GCC 6.10 */
   ^
In file included from /home/ec2-user/libreswan/programs/pluto/ikev2_message.h:19:0,
                 from /home/ec2-user/libreswan/programs/pluto/ikev2_message.c:32:
/home/ec2-user/libreswan/include/chunk.h:40:9: note: ‘len’ declared here
  size_t len;
         ^
/home/ec2-user/libreswan/programs/pluto/ikev2_message.c: In function ‘v2_record_outbound_fragment’:
/home/ec2-user/libreswan/programs/pluto/ikev2_message.c:853:2: error: missing initializer for field ‘len’ of ‘chunk_t’ [-Werror=missing-field-initializers]
  };
  ^
In file included from /home/ec2-user/libreswan/programs/pluto/ikev2_message.h:19:0,
                 from /home/ec2-user/libreswan/programs/pluto/ikev2_message.c:32:
/home/ec2-user/libreswan/include/chunk.h:40:9: note: ‘len’ declared here
  size_t len;
         ^
cc1: all warnings being treated as errors
make[3]: *** [ikev2_message.o] Error 1
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/ec2-user/libreswan/programs/pluto'
make[1]: *** [recursive-all] Error 2
make[1]: Leaving directory `/home/ec2-user/libreswan/programs'
make: *** [recursive-all] Error 2
[ec2-user@ip-172-31-26-229 libreswan]$ 

[ec2-user@ip-172-31-26-229 libreswan]$ echo $? 
2
[ec2-user@ip-172-31-26-229 libreswan]$

**Comment by bleve** [comment]
make WERROR_CFLAGS="-Werror -Wno-missing-field-initializers" programs

will solve the issue if you have gcc < 6.0

Older gcc versions have problems with missing-field-initialization checks.

**Comment by newnovice01** [comment]
This worked. Thanks!

WERROR_CFLAGS="-Werror -Wno-missing-field-initializers" make all
