### ISSUE TITLE
Cannot complie master : missing initalizer

### ISSUE THREAD

**Issue by csszep** [libreswan/libreswan#225]
Hi!

OS: Ubuntu 14.04 
Compiler gcc 4.8.4

                -c /home/szepcs/work/master/libreswan/programs/pluto/ikev2_message.c
/home/szepcs/work/master/libreswan/programs/pluto/ikev2_message.c: In function ‘open_v2SK_payload’:
/home/szepcs/work/master/libreswan/programs/pluto/ikev2_message.c:230:3: error: missing initializer for field ‘len’ of ‘chunk_t’ [-Werror=missing-field-initializers]
   .payload.len = 0, /* computed at end; set here to silence GCC 6.10 */
   ^
In file included from /home/szepcs/work/master/libreswan/programs/pluto/ikev2_message.h:19:0,
                 from /home/szepcs/work/master/libreswan/programs/pluto/ikev2_message.c:32:
/home/szepcs/work/master/libreswan/include/chunk.h:40:9: note: ‘len’ declared here
  size_t len;
         ^
/home/szepcs/work/master/libreswan/programs/pluto/ikev2_message.c: In function ‘v2_record_outbound_fragment’:
/home/szepcs/work/master/libreswan/programs/pluto/ikev2_message.c:852:2: error: missing initializer for field ‘len’ of ‘chunk_t’ [-Werror=missing-field-initializers]
  };
  ^
In file included from /home/szepcs/work/master/libreswan/programs/pluto/ikev2_message.h:19:0,
                 from /home/szepcs/work/master/libreswan/programs/pluto/ikev2_message.c:32:
/home/szepcs/work/master/libreswan/include/chunk.h:40:9: note: ‘len’ declared here
  size_t len;
         ^
cc1: all warnings being treated as errors

**Comment by bleve** [comment]
Older gcc versions have problems with these. Later versions of gcc work. On older systems you can add WERROR_CFLAGS="-Werror -Wno-missing-field-initializers" to make command line.
