### ISSUE TITLE
vti any-any iptables fwmark not causing traffic to enter vti interface

### ISSUE THREAD

**Issue by willawork** [libreswan/libreswan#226]
I have a lab set up with the following:

client <-> ipsec_left <-lab network-> ipsec_right <-> server

For testing connectivity I have a constant ping running from client to server.

client <-> ipsec_left subnet is 198.19.128.0/29.  Client is .1, ipsec_left interface is .6
svr <-> ipsec_right subnet is 198.19.128.128/29.  Server is .129, ipsec_right int is .134

Left config:
```
conn allroute
    left=10.16.20.220
    leftsubnet=0.0.0.0/0
    right=10.16.20.221
    rightsubnet=0.0.0.0/0
    authby=secret
    keyexchange=ike
    compress=no
    phase2=esp
    pfs=yes
    dpddelay=30
    dpdtimeout=90
    dpdaction=restart
    ike=aes256-sha1-modp1536
    esp=aes256-sha1
    ikelifetime=86400s
    auto=add
    keyingtries=0
    vti-interface=vti42
    vti-routing=no
    leftvti=198.19.128.6/29
    mark=5/0xffffffff
    leftupdown="/etc/ipsec.d/updown"
```
Right config is essentially the same with left/right switched.
Using Libreswan 3.27 on 4.4.39 (custom build) I can create an any-any tunnel with VTI and pass traffic if there is a route in place for the rightsubnet (198.19.128.128/29 via dev vti42)

But dropping the route and trying to use iptables FWMARKs doesn't seem to be working.
`iptables -t mangle -A PREROUTING -d 198.19.128.128/29 -j MARK --set-mark 0x5`

I can see in conntrack that the mark is being applied:
`icmp     1 22 src=198.19.128.1 dst=198.19.128.129 type=8 code=0 id=3185 [UNREPLIED] src=198.19.128.129 dst=10.16.20.220 type=0 code=0 id=3185 mark=5 use=1`
and the iptables counters are rising:
```
Chain PREROUTING (policy ACCEPT 9811 packets, 826K bytes)
 pkts bytes target     prot opt in     out     source               destination         
 2596  218K MARK       all  --  *      *       0.0.0.0/0            198.19.128.128/29   MARK set 0x5 

```
but I don't see traffic entering vti42 when I packet dump it.

ipsec auto --status:
```
000 "allroute": 0.0.0.0/0===10.16.20.220<10.16.20.220>...10.16.20.221<10.16.20.221>===0.0.0.0/0; erouted; eroute owner: #6
000 "allroute":     oriented; my_ip=unset; their_ip=unset; my_updown=/etc/ipsec.d/updown;
000 "allroute":   xauth us:none, xauth them:none,  my_username=[any]; their_username=[any]
000 "allroute":   our auth:secret, their auth:secret
000 "allroute":   modecfg info: us:none, them:none, modecfg policy:push, dns:unset, domains:unset, banner:unset, cat:unset;
000 "allroute":   labeled_ipsec:no;
000 "allroute":   policy_label:unset;
000 "allroute":   ike_life: 86400s; ipsec_life: 28800s; replay_window: 32; rekey_margin: 540s; rekey_fuzz: 100%; keyingtries: 0;
000 "allroute":   retransmit-interval: 500ms; retransmit-timeout: 60s;
000 "allroute":   initial-contact:no; cisco-unity:no; fake-strongswan:no; send-vendorid:no; send-no-esp-tfc:no;
000 "allroute":   policy: PSK+ENCRYPT+TUNNEL+PFS+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO;
000 "allroute":   conn_prio: 0,0; interface: eth0; metric: 0; mtu: unset; sa_prio:auto; sa_tfc:none;
000 "allroute":   nflog-group: unset; mark: 5/0xffffffff, 5/0xffffffff; vti-iface:vti42; vti-routing:yes; vti-shared:no; nic-offload:auto;
000 "allroute":   our idtype: ID_IPV4_ADDR; our id=10.16.20.220; their idtype: ID_IPV4_ADDR; their id=10.16.20.221
000 "allroute":   dpd: action:restart; delay:30; timeout:90; nat-t: encaps:auto; nat_keepalive:yes; ikev1_natt:both
000 "allroute":   newest ISAKMP SA: #5; newest IPsec SA: #6;
000 "allroute":   IKE algorithms: AES_CBC_256-HMAC_SHA1-MODP1536
000 "allroute":   IKE algorithm newest: AES_CBC_256-HMAC_SHA1-MODP1536
000 "allroute":   ESP algorithms: AES_CBC_256-HMAC_SHA1_96
000 "allroute":   ESP algorithm newest: AES_CBC_256-HMAC_SHA1_96; pfsgroup=<Phase1>
...
000 #5: "allroute":500 STATE_MAIN_R3 (sent MR3, ISAKMP SA established); EVENT_SA_REPLACE in 86093s; newest ISAKMP; lastdpd=6s(seq in:0 out:0); idle;
000 #6: "allroute":500 STATE_QUICK_R2 (IPsec SA established); EVENT_SA_REPLACE in 28493s; newest IPSEC; eroute owner; isakmp#5; idle;
000 #6: "allroute" esp.5412e149@10.16.20.221 esp.e2a01c0b@10.16.20.220 tun.0@10.16.20.221 tun.0@10.16.20.220 ref=0 refhim=0 Traffic: ESPin=0B ESPout=0B! ESPmax=4194303B 
```
vti interface stats:
```
# ip -s tunnel show vti42
vti42: ip/ip  remote 10.16.20.221  local 10.16.20.220  ttl inherit  key 0.0.0.5
RX: Packets    Bytes        Errors CsumErrs OutOfSeq Mcasts
    85         5232         0      0        0        0       
TX: Packets    Bytes        Errors DeadLoop NoRoute  NoBufs
    117        15742        0      0        0        0     
```
Packets are from earlier testing with routes in place.

ip xfrm policy:
```
src 0.0.0.0/0 dst 0.0.0.0/0 
        dir out priority 1048575 
        tmpl src 10.16.20.220 dst 10.16.20.221
                proto esp reqid 16389 mode tunnel
src 0.0.0.0/0 dst 0.0.0.0/0 
        dir fwd priority 1048575 
        tmpl src 10.16.20.221 dst 10.16.20.220
                proto esp reqid 16389 mode tunnel
src 0.0.0.0/0 dst 0.0.0.0/0 
        dir in priority 1048575 
        tmpl src 10.16.20.221 dst 10.16.20.220
                proto esp reqid 16389 mode tunnel
```

The firewall marks work if I add routing rules pointing at a separate routing table, but I thought the idea was to be able to make use of them without the routes?

I think I've covered everything, please let me know if there's more info needed.

Thanks

**Comment by willawork** [comment]
For what it is worth, I have also tried setting both fwmark and connmark, copying between the two but still no joy.

**Comment by willawork** [comment]
Also having the fwmark being set stops routes from functioning.  Delete the iptables mangle rule and traffic starts flowing.

**Comment by letoams** [comment]
On Thu, 6 Dec 2018, willawork wrote:

>     vti-interface=vti42
>     vti-routing=no
>     leftvti=198.19.128.6/29
>     mark=5/0xffffffff

Most likely you want vti-routing=yes

> Right config is essentially the same with left/right switched.
> Using Libreswan 3.27 on 4.4.39 (custom build) I can create an any-any tunnel with VTI and pass traffic if there
> is a route in place for the rightsubnet (198.19.128.128/29 via dev vti42)

Well, for an any-any tunnel, you do want vti-routing=no and then
manually route the stuff you want to go through IPsec via routes.

> But dropping the route and trying to use iptables FWMARKs doesn't seem to be working.
> iptables -t mangle -A PREROUTING -d 198.19.128.128/29 -j MARK --set-mark 0x5

When you create the VTI interface, the XFRM subsystem is linked to the
interface, so I am not sure if you can use your own marking to get the
same result. VTI devices are weird (and being replaced by XFRMi
interfaces)

>  2596  218K MARK       all  --  *      *       0.0.0.0/0            198.19.128.128/29   MARK set 0x5 
> 
> but I don't see traffic entering vti42 when I packet dump it.

Traffic enters the device only via routes, Once routed into, the VTI
code causes the mark which causes the XFRM to trigger.

Paul

**Comment by willawork** [comment]
Hi Paul,
That's what I was thinking, but the documentation ([ipsec.conf(5)](https://libreswan.org/man/ipsec.conf.5.html)) lists this:

> **mark**
> 
> If set, the MARK to set for the IPsec SA of this connection. The format of a CONNMARK is mark/mask. If the mask is left out, a default mask of 0xffffffff is used. A mark value of -1 means to assign a new global unique mark number for each instance of the connection. Global marks start at 1001. This option is only available on linux NETKEY/XFRM kernels. It can be used with iptables to create custom iptables rules using CONNMARK. It can also be used with Virtual Tunnel Interfaces ("VTI") to direct marked traffic to specific vtiXX devices. 

I'm guessing that last statement is only when using policy routing (routing rules and extra tables)?

It's nice having the "separation" of traffic flow caused by the VTI in the same manner as KLIPS, I was just hoping that we could also still use the marks to utilise alternative methods of getting traffic into the tunnel, but it seems these are mutually exclusive in that sense.

Might go reading on the new xfrm interface and see what they're planning there.

Thanks for your time :)

William
