### ISSUE TITLE
Ip address Assignment

### ISSUE THREAD

**Issue by lncan** [libreswan/libreswan#227]
Hello guys. I've successfully configured and established an ipsec tunnel using XAUTH plus PSK to a fortigate endpoint from my linux notebook. I get an ip assigned but that ip gets assinged to my lo device. Can someone point me to the right direction to debug that? Is libreswan supposed to configure my network settings?

My client config file:

![screen shot 2018-12-10 at 11 39 57](https://user-images.githubusercontent.com/40355589/49711153-5e187d00-fc70-11e8-90c8-0cbf2d0ba6cf.png)

My client secret file:

![screen shot 2018-12-10 at 11 40 58](https://user-images.githubusercontent.com/40355589/49711174-8011ff80-fc70-11e8-9b54-23e2b6b7bab1.png)

Ip addr show in client:

![screen shot 2018-12-10 at 11 41 27](https://user-images.githubusercontent.com/40355589/49711192-98821a00-fc70-11e8-8549-7c324f2363ba.png)

Connection status in vpn server:

![screen shot 2018-12-10 at 11 42 40](https://user-images.githubusercontent.com/40355589/49711217-b9e30600-fc70-11e8-923b-e46fa0399063.png)

But when i ping from Server IP to client Ip, No packet success:

![screen shot 2018-12-10 at 11 44 34](https://user-images.githubusercontent.com/40355589/49711268-fe6ea180-fc70-11e8-8a4c-067c6f6122fe.png)

**Comment by bleve** [comment]
That is exactly how it is supposed to work.

Check results of ip route list to see how dev lo assigned ip is used.

**Comment by lncan** [comment]
> That is exactly how it is supposed to work.
> 
> Check results of ip route list to see how dev lo assigned ip is used.

After i checked, here is the result

![screen shot 2018-12-10 at 15 00 56](https://user-images.githubusercontent.com/40355589/49718403-8c0bba80-fc8c-11e8-9aa2-02ae7896e6de.png)

No route for lo interface, only for ethernet subnet. Any problem here? What can i do to fix this?

**Comment by lncan** [comment]
> You need muct later version. 3.23 is too old and doesn't have full client support.

After reinstall newest verion, 3.27, no progress. There is still old issue.

**Comment by bleve** [comment]
Try adding rightsubnet=0.0.0.0/0 to your config.

**Comment by lncan** [comment]
> Try adding rightsubnet=0.0.0.0/0 to your config.

Yes. It worked. Thank you very much. And Can you please let me know about client in window? I follow the instruction of following link https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md#windows but no connection established. 

![48277810_2099262406784157_21906476398280704_n](https://user-images.githubusercontent.com/40355589/49725405-2fb19680-fc9e-11e8-9ed4-013c101e12fb.png)

**Comment by bleve** [comment]
For windows, best option is to use certifciates (you generally need to create your own CA) and use our ikev2 windows installation instructions from https://libreswan.org/wiki/

**Comment by lncan** [comment]
Thank you very much.
