### ISSUE TITLE
VPN client for Xauth + PSK on Windows 

### ISSUE THREAD

**Issue by lncan** [libreswan/libreswan#228]
Hi guys, I follow the instruction via link https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md to connect vpn server on window. But no successful. Here is error picture. 

![48277810_2099262406784157_21906476398280704_n](https://user-images.githubusercontent.com/40355589/49730333-9fc61980-fcaa-11e8-8ff9-af02e1df9da1.png)

Can you please tell me the detail solution to fix this or any solution to connect vpn on window? Thanks all.

**Comment by letoams** [comment]
this is not enough information to help. if you have more information such as the libreswan logs, you can re-open this issue
