### ISSUE TITLE
Can't create /proc/sys/net/core/xfrm_acq_expires: Read-only file system in a EC2 docker container (ECS)

### ISSUE THREAD

**Issue by typeless** [libreswan/libreswan#229]
I logged into the root account and run:

`/usr/sbin/ipsec start`

I got 
```` 
/usr/libexec/ipsec/_stackmanager: line 475: can't create /proc/sys/net/core/xfrm_acq_expires: Read-only file system
````

Version:
```
~ # ipsec --version
Linux Libreswan 3.21 (netkey) on 4.14.77-80.57.amzn2.x86_64
``` 

Distro/OS:
```
~ # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.1
PRETTY_NAME="Alpine Linux v3.8"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

Do I miss any step or configuration?

**Comment by typeless** [comment]
Thanks for your quick response.

I'll proceed to set it up given that it is harmless  :)
I'll leave the issue open in case other people have the same question.

**Comment by letoams** [comment]
We now only write when it would be a change. hopefully that suppresses most errors.
