### ISSUE TITLE
IKEv2 Original Initiator

### ISSUE THREAD

**Issue by fahedhijazi** [libreswan/libreswan#231]
Not sure if this is an issue, as I haven't fully read through the code.

According to RFC7296 (Section 2.2), the "original initiator" always refers to the party who initiated the exchange that resulted in the current IKE SA.

https://github.com/libreswan/libreswan/blob/master/programs/pluto/ikev2_parent.c#L5720

It seems that this should only be set when sa_type == IKE_SA, otherwise my understanding is that the new state should inherit the value from the current parent (IKE SA) when rekeying an IPSEC_SA.

Let me know if this is correct.

**Comment by letoams** [comment]
On Wed, 2 Jan 2019, Fahed Hijazi wrote:

> 
> According to RFC7296 (Section 2.2), the "original initiator" always refers to the party who initiated the exchange
> that resulted in the current IKE SA.
> 
> https://github.com/libreswan/libreswan/blob/master/programs/pluto/ikev2_parent.c#L5720
> 
> It seems that this should only be set when sa_type == IKE_SA, otherwise my understanding is that the new state should
> inherit the value from the current parent (IKE SA) when rekeying an IPSEC_SA.

You are correct, but :)

We are working on separating the ike and ipsec states. So far, we have
already isolated the Original Initiator flag and its use, to only happen
on IKE states. So while it is (for now) still duplicates to the IPsec
state, it is not actually used there.

Paul

**Comment by fahedhijazi** [comment]
Got it, thanks for the follow up. I also noticed that when I reviewed the code after. The overlap of st_sa_role and st_original_role is a bit clunky.

**Comment by letoams** [comment]
A lot of mistakes kept being introduced and fixed by people mixing up the two roles, so hence the additional checks and protection.

But patches to make it less clunky always appreciated :)

**Comment by letoams** [comment]
(work has happened to cleanup the IKE header flags usage)
