### ISSUE TITLE
Need Help in Phase 2 Error - Received and ignored informational message

### ISSUE THREAD

**Issue by informraees** [libreswan/libreswan#232]
Hello,

I need help in identifying the issue with my device. I have configured IPSec from **libreswan 3.18** device  to Fortigate FD90.
Topology is simple  Libreswan -------- Fortigate-FD90

I have configured everything same on both sides. The tunnel is up and active on both sides. The ping works fine but it starts initiates quick method again with the peer.

This problem we didn't face when we were using Openswan with Fortigate. But now with libreswan and Fortigate, we are facing this issue which causes high memory utilization.

### **===> This is the start of IPSec which is fine.**
Jan  8 17:04:03 R2-1500 ipsec__plutorun: Starting Pluto
Jan  8 17:04:03 R2-1500 pluto[26867]: NSS DB directory: sql:/tmp/ipsec.d
Jan  8 17:04:03 R2-1500 pluto[26867]: Initializing NSS
Jan  8 17:04:03 R2-1500 pluto[26867]: Opening NSS database "sql:/tmp/ipsec.d" read-only
Jan  8 17:04:04 R2-1500 pluto[26867]: NSS initialized
Jan  8 17:04:04 R2-1500 pluto[26867]: NSS crypto library initialized
Jan  8 17:04:04 R2-1500 pluto[26867]: libcap-ng support [enabled]
Jan  8 17:04:04 R2-1500 pluto[26867]: FIPS HMAC integrity support [enabled]
Jan  8 17:04:04 R2-1500 pluto[26867]: FIPS Product: NO
Jan  8 17:04:04 R2-1500 pluto[26867]: FIPS Kernel: NO
Jan  8 17:04:04 R2-1500 pluto[26867]: FIPS Mode: NO
Jan  8 17:04:04 R2-1500 pluto[26867]: FIPS mode disabled for pluto daemon
Jan  8 17:04:04 R2-1500 pluto[26867]: FIPS HMAC integrity verification self-test FAILED
Jan  8 17:04:04 R2-1500 pluto[26867]: Linux audit support [disabled]
Jan  8 17:04:04 R2-1500 pluto[26867]: Starting Pluto (Libreswan Version 3.18 XFRM(netkey) USE_FORK USE_PTHREAD_SETSCHEDPRIO NSS DNSSEC FIPS_CHECK LIBCAP_NG XAUTH_PAM NETWORKMANAGER CURL(non-NSS) LDAP(non-NSS)) pid:26867
Jan  8 17:04:04 R2-1500 pluto[26867]: core dump dir: /var/run/pluto
Jan  8 17:04:04 R2-1500 pluto[26867]: secrets file: /tmp/ipsec.secrets
Jan  8 17:04:04 R2-1500 pluto[26867]: leak-detective disabled
Jan  8 17:04:04 R2-1500 pluto[26867]: NSS crypto [enabled]
Jan  8 17:04:04 R2-1500 pluto[26867]: XAUTH PAM support [enabled]
Jan  8 17:04:04 R2-1500 pluto[26867]: NAT-Traversal support  [enabled]
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_enc(): Activating OAKLEY_TWOFISH_CBC_SSH: Ok
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_enc(): Activating OAKLEY_TWOFISH_CBC: Ok
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_enc(): Activating OAKLEY_SERPENT_CBC: Ok
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_enc(): Activating OAKLEY_AES_CBC: Ok
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_enc(): Activating OAKLEY_AES_CTR: Ok
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_enc(): Activating OAKLEY_AES_GCM_A: Ok
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_enc(): Activating OAKLEY_AES_GCM_B: Ok
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_enc(): Activating OAKLEY_AES_GCM_C: Ok
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_hash(): Activating DISABLED-OAKLEY_AES_XCBC: Ok
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_enc(): Activating OAKLEY_CAMELLIA_CBC: Ok
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_enc(): Activating OAKLEY_CAMELLIA_CTR: Ok
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_hash(): Activating OAKLEY_SHA2_512: Ok
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_hash(): Activating OAKLEY_SHA2_384: Ok
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_hash(): Activating OAKLEY_SHA2_256: Ok
Jan  8 17:04:04 R2-1500 pluto[26867]: no crypto helpers will be started; all cryptographic operations will be done inline
Jan  8 17:04:04 R2-1500 pluto[26867]: Using Linux XFRM/NETKEY IPsec interface code on 3.14-2-8360e
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_enc(): Activating aes_ccm_8: Ok
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_enc(): Activating aes_ccm_12: Ok
Jan  8 17:04:04 R2-1500 pluto[26867]: ike_alg_register_enc(): Activating aes_ccm_16: Ok
Jan  8 17:04:05 R2-1500 pluto[26867]: added connection description "Link1"
Jan  8 17:04:05 R2-1500 pluto[26867]: listening for IKE messages
Jan  8 17:04:05 R2-1500 pluto[26867]: adding interface fe-3-4/fe-3-4 10.102.0.48:500
Jan  8 17:04:05 R2-1500 pluto[26867]: adding interface fe-3-4/fe-3-4 10.102.0.48:4500
Jan  8 17:04:05 R2-1500 pluto[26867]: adding interface vrf_gw0/vrf_gw0 169.254.0.1:500
Jan  8 17:04:05 R2-1500 pluto[26867]: adding interface vrf_gw0/vrf_gw0 169.254.0.1:4500
Jan  8 17:04:05 R2-1500 pluto[26867]: adding interface dummy0/dummy0 55.5.5.5:500
Jan  8 17:04:05 R2-1500 pluto[26867]: adding interface dummy0/dummy0 55.5.5.5:4500
Jan  8 17:04:05 R2-1500 pluto[26867]: adding interface fe-cm-1/fe-cm-1 10.1.1.2:500
Jan  8 17:04:05 R2-1500 pluto[26867]: adding interface fe-cm-1/fe-cm-1 10.1.1.2:4500
Jan  8 17:04:05 R2-1500 pluto[26867]: adding interface lo/lo 127.0.0.1:500
Jan  8 17:04:05 R2-1500 pluto[26867]: adding interface lo/lo 127.0.0.1:4500
Jan  8 17:04:05 R2-1500 pluto[26867]: adding interface lo/lo ::1:500
Jan  8 17:04:05 R2-1500 pluto[26867]: | setup callback for interface lo:500 fd 25
Jan  8 17:04:05 R2-1500 pluto[26867]: | setup callback for interface lo:4500 fd 24
Jan  8 17:04:05 R2-1500 pluto[26867]: | setup callback for interface lo:500 fd 23
Jan  8 17:04:05 R2-1500 pluto[26867]: | setup callback for interface fe-cm-1:4500 fd 22
Jan  8 17:04:05 R2-1500 pluto[26867]: | setup callback for interface fe-cm-1:500 fd 21
Jan  8 17:04:05 R2-1500 pluto[26867]: | setup callback for interface dummy0:4500 fd 20
Jan  8 17:04:05 R2-1500 pluto[26867]: | setup callback for interface dummy0:500 fd 19
Jan  8 17:04:05 R2-1500 pluto[26867]: | setup callback for interface vrf_gw0:4500 fd 18
Jan  8 17:04:05 R2-1500 pluto[26867]: | setup callback for interface vrf_gw0:500 fd 17
Jan  8 17:04:05 R2-1500 pluto[26867]: | setup callback for interface fe-3-4:4500 fd 16
Jan  8 17:04:05 R2-1500 pluto[26867]: | setup callback for interface fe-3-4:500 fd 15
Jan  8 17:04:05 R2-1500 pluto[26867]: loading secrets from "/tmp/ipsec.secrets"
Jan  8 17:04:06 R2-1500 pluto[26867]: "Link1": route-client output: /usr/lib/quagga/routeset_client add 77.7.7.0/24 dev fe-3-4.
Jan  8 17:04:06 R2-1500 pluto[26867]: "Link1" #1: initiating Main Mode
Jan  8 17:04:06 R2-1500 pluto[26867]: "Link1" #1: ignoring unknown Vendor ID payload [8299031757a36082c6a621de00050457]
Jan  8 17:04:06 R2-1500 pluto[26867]: "Link1" #1: transition from state STATE_MAIN_I1 to state STATE_MAIN_I2
Jan  8 17:04:06 R2-1500 pluto[26867]: "Link1" #1: STATE_MAIN_I2: sent MI2, expecting MR2
Jan  8 17:04:06 R2-1500 pluto[26867]: reapchild failed with errno=10 No child processes
Jan  8 17:04:06 R2-1500 pluto[26867]: "Link1" #1: transition from state STATE_MAIN_I2 to state STATE_MAIN_I3
Jan  8 17:04:06 R2-1500 pluto[26867]: "Link1" #1: STATE_MAIN_I3: sent MI3, expecting MR3
Jan  8 17:04:06 R2-1500 pluto[26867]: "Link1" #1: Main mode peer ID is ID_IPV4_ADDR: '10.102.100.1'
Jan  8 17:04:06 R2-1500 pluto[26867]: "Link1" #1: transition from state STATE_MAIN_I3 to state STATE_MAIN_I4
Jan  8 17:04:06 R2-1500 pluto[26867]: "Link1" #1: STATE_MAIN_I4: ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha group=MODP1536}

### **---->>>> The tunnel is established here but It again starts initiating Quick Mode.**

Jan  8 17:04:06 R2-1500 pluto[26867]: "Link1" #2: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO {using isakmp#1 msgid:d7bcc824 proposal=AES(12)_256-SHA1(2) pfsgroup=OAKLEY_GROUP_MODP1536}
Jan  8 17:04:06 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:04:06 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:04:06 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:04:06 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:04:06 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:04:06 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:04:06 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:04:06 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:04:07 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:04:07 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:04:07 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:04:07 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:04:08 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:04:08 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:04:08 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:04:08 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:04:10 R2-1500 pluto[26867]: "Link1" #1: the peer proposed: 55.5.5.0/24:0/0 -> 77.7.7.0/24:0/0
Jan  8 17:04:10 R2-1500 pluto[26867]: "Link1" #3: responding to Quick Mode proposal {msgid:3e7816ca}
Jan  8 17:04:10 R2-1500 pluto[26867]: "Link1" #3:     us: 55.5.5.0/24===10.102.0.48<10.102.0.48>
Jan  8 17:04:10 R2-1500 pluto[26867]: "Link1" #3:   them: 10.102.100.1<10.102.100.1>===77.7.7.0/24
Jan  8 17:04:10 R2-1500 pluto[26867]: "Link1" #3: soft_use_expires_seconds: 28800 soft_byte_limit: 0MB
Jan  8 17:04:10 R2-1500 pluto[26867]: "Link1" #3: soft_use_expires_seconds: 28800 soft_byte_limit: 0MB
Jan  8 17:04:10 R2-1500 pluto[26867]: "Link1" #3: transition from state STATE_QUICK_R0 to state STATE_QUICK_R1
Jan  8 17:04:10 R2-1500 pluto[26867]: "Link1" #3: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP=>0xcd6139b1 <0x82765f0f xfrm=AES_256-HMAC_SHA1 NATOA=none NATD=none DPD=passive}
Jan  8 17:04:10 R2-1500 pluto[26867]: "Link1" #3: transition from state STATE_QUICK_R1 to state STATE_QUICK_R2
Jan  8 17:04:10 R2-1500 pluto[26867]: "Link1" #3: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP=>0xcd6139b1 <0x82765f0f xfrm=AES_256-HMAC_SHA1 NATOA=none NATD=none DPD=passive}
Jan  8 17:04:10 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:04:10 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:04:10 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:04:10 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:04:14 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:04:14 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:04:14 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:04:14 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:04:22 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:04:22 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:04:22 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:04:22 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:04:38 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:04:38 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:04:38 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:04:38 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:05:01 R2-1500 CRON[27317]: pam_unix(cron:session): session opened for user root by (uid=0)
Jan  8 17:05:03 R2-1500 CRON[27317]: pam_unix(cron:session): session closed for user root
Jan  8 17:05:10 R2-1500 pluto[26867]: "Link1" #2: max number of retransmissions (8) reached STATE_QUICK_I1
Jan  8 17:05:10 R2-1500 pluto[26867]: "Link1" #2: starting keying attempt 2 of an unlimited number
Jan  8 17:05:10 R2-1500 pluto[26867]: "Link1" #4: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO to replace #2 {using isakmp#1 msgid:cec19495 proposal=AES(12)_256-SHA1(2) pfsgroup=OAKLEY_GROUP_MODP1536}
Jan  8 17:05:10 R2-1500 pluto[26867]: deleting other state #2 (STATE_QUICK_I1) "Link1"
Jan  8 17:05:10 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:05:10 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:05:10 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:05:10 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:05:10 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:05:10 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:05:10 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:05:10 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:05:11 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:05:11 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:05:11 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:05:11 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:05:12 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:05:12 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:05:12 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:05:12 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:05:14 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:05:14 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:05:14 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:05:14 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:05:18 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:05:18 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:05:18 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:05:18 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:05:26 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:05:26 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:05:26 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:05:26 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:05:42 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:05:42 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:05:42 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:05:42 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:06:14 R2-1500 pluto[26867]: "Link1" #4: max number of retransmissions (8) reached STATE_QUICK_I1
Jan  8 17:06:14 R2-1500 pluto[26867]: "Link1" #4: starting keying attempt 3 of an unlimited number
Jan  8 17:06:14 R2-1500 pluto[26867]: "Link1" #5: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO to replace #4 {using isakmp#1 msgid:dafcff7d proposal=AES(12)_256-SHA1(2) pfsgroup=OAKLEY_GROUP_MODP1536}
Jan  8 17:06:14 R2-1500 pluto[26867]: deleting other state #4 (STATE_QUICK_I1) "Link1"
Jan  8 17:06:14 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:06:14 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:06:14 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:06:14 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:06:14 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:06:14 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:06:14 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:06:14 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:06:15 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:06:15 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:06:15 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:06:15 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:06:16 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:06:16 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:06:16 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:06:16 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:06:18 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:06:18 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:06:18 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:06:18 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:06:22 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:06:22 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:06:22 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:06:22 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:06:30 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:06:30 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:06:30 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:06:30 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:06:46 R2-1500 pluto[26867]: "Link1" #1: ignoring informational payload NO_PROPOSAL_CHOSEN, msgid=00000000, length=16
Jan  8 17:06:46 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan  8 17:06:46 R2-1500 pluto[26867]: |   00 00 00 10  00 00 00 01  03 04 00 0e
Jan  8 17:06:46 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan  8 17:07:18 R2-1500 pluto[26867]: "Link1" #5: max number of retransmissions (8) reached STATE_QUICK_I1
Jan  8 17:07:18 R2-1500 pluto[26867]: "Link1" #5: starting keying attempt 4 of an unlimited number
Jan  8 17:07:18 R2-1500 pluto[26867]: "Link1" #6: initiating Quick Mode PSK+ENCRYPT+TUNNEL+PFS+UP+IKEV1_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO to replace #5 {using isakmp#1 msgid:c8f87ff6 proposal=AES(12)_256-SHA1(2) pfsgroup=OAKLEY_GROUP_MODP1536}

These messages consumes a significant amount of memory.

### **_===== IPSEC Configs on Libreswan ==========_**
conn Link1
        connaddrfamily=ipv4
        authby=secret
        auto=start
        phase2=esp
        phase2alg=aes256-sha1;modp1536
        ike=aes256-sha1;modp1536
        ikelifetime=3600s
        salifetraffic=0
        ikev2=never
        left=10.102.0.48
        leftid=10.102.0.48
        leftsubnet=55.5.5.0/24
        leftupdown="/usr/bin/rmf_ipsec_updown --route yes"
        pfs=yes
        dpddelay=30
        dpdtimeout=120
        dpdaction=restart
        right=10.102.100.1
        rightid=10.102.100.1
        rightsubnet=77.7.7.0/24
        rightupdown="/usr/bin/rmf_ipsec_updown --route yes"
        type=tunnel

**Comment by letoams** [comment]
It is not "starting again". You successfully setup phase1 (main mode) and start to negotiate a phase 2 (quick mode) which the other ends rejects with NO_PROPOSAL_CHOSEN.
Check the logs on the other side why it is rejecting your proposal. Clearly something has changed :)

**Comment by informraees** [comment]
![fortigate-configs](https://user-images.githubusercontent.com/41979338/50916859-38ff6180-140a-11e9-919b-cd0874dc2046.png)
![fortigate-logs](https://user-images.githubusercontent.com/41979338/50916860-38ff6180-140a-11e9-99bc-2c36f92c1e97.PNG)

This is Foritgate Side. It brings my tunnel up. The status is UP on both sides and the Ping is working fine. But in **### /var/log/auth.log**, it shows aforementioned logs which causes high memory utilization by pluto.

Any help would highly be appreciated.

Thanks.

**Comment by letoams** [comment]
I see no indication that the tunnel's phase2 is up. I see errors saying it is _not_ up.
You didn't include the full logs on the libreswan end, so i cannot see if there was a successful negotiation between the phase1 setup and the failing phase2setup. if the pings works and it would not work unencrypted, then it would suggest it did come up first, but then it is a mystery why it would fail on rekey

**Comment by informraees** [comment]
These logs are from start of the tunnel. and then it keeps on showing these messages. I disabled the IPSec tunnel and then enabled it again.

The Capture file is attached can be seen in wireshark.

[rox1501-fd90-capture.zip](https://github.com/libreswan/libreswan/files/2742429/rox1501-fd90-capture.zip)

**Comment by informraees** [comment]
Hi letoams, in my first post, I was referring to these messages that tunnel is established.

Jan 8 17:04:08 R2-1500 pluto[26867]: | ISAKMP Notification Payload
Jan 8 17:04:08 R2-1500 pluto[26867]: | 00 00 00 10 00 00 00 01 03 04 00 0e
Jan 8 17:04:08 R2-1500 pluto[26867]: "Link1" #1: received and ignored informational message
Jan 8 17:04:10 R2-1500 pluto[26867]: "Link1" #1: the peer proposed: 55.5.5.0/24:0/0 -> 77.7.7.0/24:0/0
Jan 8 17:04:10 R2-1500 pluto[26867]: "Link1" #3: responding to Quick Mode proposal {msgid:3e7816ca}
Jan 8 17:04:10 R2-1500 pluto[26867]: "Link1" #3: us: 55.5.5.0/24===10.102.0.48<10.102.0.48>
Jan 8 17:04:10 R2-1500 pluto[26867]: "Link1" #3: them: 10.102.100.1<10.102.100.1>===77.7.7.0/24
Jan 8 17:04:10 R2-1500 pluto[26867]: "Link1" #3: soft_use_expires_seconds: 28800 soft_byte_limit: 0MB
Jan 8 17:04:10 R2-1500 pluto[26867]: "Link1" #3: soft_use_expires_seconds: 28800 soft_byte_limit: 0MB
Jan 8 17:04:10 R2-1500 pluto[26867]: "Link1" #3: transition from state STATE_QUICK_R0 to state STATE_QUICK_R1
Jan 8 17:04:10 R2-1500 pluto[26867]: "Link1" #3: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP=>0xcd6139b1 <0x82765f0f xfrm=AES_256-HMAC_SHA1 NATOA=none NATD=none DPD=passive}
Jan 8 17:04:10 R2-1500 pluto[26867]: "Link1" #3: transition from state STATE_QUICK_R1 to state STATE_QUICK_R2
Jan 8 17:04:10 R2-1500 pluto[26867]: "Link1" #3: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP=>0xcd6139b1 <0x82765f0f xfrm=AES_256-HMAC_SHA1 NATOA=none NATD=none DPD=passive}

**Comment by letoams** [comment]
possibly disagreement only happens on rekey because of different PFS settings?
We would need more info to see what is happening. the tunnel comes up. does it go down and then end in a bad retry loop or is one instance up and why is there is a second one trying?

You are also using a really old version from 2016, so please reproduce with an upgraded versions first
