### ISSUE TITLE
Hand out LAN IP addresses in the address pool

### ISSUE THREAD

**Issue by MyOzCam** [libreswan/libreswan#238]
Background:
- Server A: Libreswan 3.27, Fedora 29 on RPi, NATed home LAN.
- Port forwarded UDP 500,4500 from boarder router to Server A.
- Configured with IKEv2 to allow Road Warrior clients (MacOS/IOS) to access LAN and Internet by VPN
- rightaddresspool assigned ip(s) in subnet same home LAN 
- currently enabled masquerade in firewalld.
- Worked perfectly except all traffic from Road Worrier are spoofed, which i feel uncomfortable
  
Issue:
Is there any way I don't need to turn masquerade on and have those road warrior to access everything (both local LAN and Internet) with its own assigned IP?

I have tried set net.ipv4.conf.eth0.proxy_arp=1 and turned off entire firewalld but seems it just not work without firewall's masquerade.

**Comment by brozs** [comment]
I am not sure what is the purpose of "masquerade in firewalld", what does it do?

When you assign IPs from the home subnet to the road warrior, there will be no way of returning packets back to the road warrior from local resources on LAN (except, possibly, for the IPsec gateway). The road warrior would appear as it is on the directly attached network, while it actually is behind the IPsec gateway. You would need L2TP for that, I believe. Is that what you are solving by "masquerade in firewalld"? 

Create a dedicated road warrior subnet, use it in the addresspool, and route the traffic to that subnet to your IPsec gateway (Server A) in your LAN (e.g. on the hosts and on your router, depending on your topology).
