### ISSUE TITLE
Build instructions for OSX

### ISSUE THREAD

**Issue by logotype** [libreswan/libreswan#24]
Hi

Sorry if I have missed some docs, but I really couldn't find any instructions on how to build libreswan on OSX. I've tried to install the missing header files via brew (nss, pkg-config, nspr, unbound, gmp). As well as manually copy tcpd.h to /usr/include. However, I'm stuck on the error "pfkey.c:38:10: fatal error: 'netkey/key_var.h' file not found". I'm running OSX 10.10.2 (14C94b).

Thanks for the great work on openswan/libreswan. It's working great! But would llike to get this running on OSX too :)

**Comment by letoams** [comment]
On Tue, 13 Jan 2015, Victor Norgren wrote:

> Sorry if I have missed some docs, but I really couldn't find any instructions on how to build libreswan on OSX. I've tried to install the
> missing header files via brew (nss, pkg-config, nspr, unbound, gmp). As well as manually copy tcpd.h to /usr/include. However, I'm stuck
> on the error "pfkey.c:38:10: fatal error: 'netkey/key_var.h' file not found". I'm running OSX 10.10.2 (14C94b).

We have not build for OSX in a while. That file used to come with bsd it
seems. I'm not sure what it needs in there. I assume you tried
commenting it out to see what defines are missing? Perhaps those can be
found elsewhere now?

Paul

**Comment by logotype** [comment]
Closing this one for now, I didn't have time to retry.
