### ISSUE TITLE
BUG - Libreswan drops all connection

### ISSUE THREAD

**Issue by leslie2050** [libreswan/libreswan#241]
**hi guys:**

i got big problem with libreswan-3.27
i used libreswan + xl2tpd for  L2TP/IPsec server
**when some clients(more than 10) behind same NAT** ,sometimes libreswan will stop working and all clients be dropped.

client:IOS-12
![webwxgetmsgimg (1)](https://user-images.githubusercontent.com/14960084/55554299-03ba9500-5715-11e9-8090-16b8114ed50e.jpeg)

crypto:PSK

LOG:
```
19:36:19 localhost.localdomain xl2tpd[9701]: network_thread: unable to find call or tunnel to handle packet. call = 58561, tunnel = 21864 Dumping.
19:36:19 localhost.localdomain pluto[706]: recvmsg(,, MSG_ERRQUEUE): given up reading socket after 32 EAGAIN errors
19:36:19 localhost.localdomain pluto[706]: recvmsg(,, MSG_ERRQUEUE): given up reading socket after 32 EAGAIN errors
19:36:19 localhost.localdomain pluto[706]: recvmsg(,, MSG_ERRQUEUE): given up reading socket after 32 EAGAIN errors
19:36:19 localhost.localdomain pluto[706]: recvmsg(,, MSG_ERRQUEUE): given up reading socket after 32 EAGAIN errors
19:36:19 localhost.localdomain pluto[706]: recvmsg(,, MSG_ERRQUEUE): given up reading socket after 32 EAGAIN errors
19:36:19 localhost.localdomain pluto[706]: recvmsg(,, MSG_ERRQUEUE): given up reading socket after 32 EAGAIN errors
19:36:19 localhost.localdomain pluto[706]: recvmsg(,, MSG_ERRQUEUE): given up reading socket after 32 EAGAIN errors
19:36:19 localhost.localdomain pluto[706]: recvmsg(,, MSG_ERRQUEUE): given up reading socket after 32 EAGAIN errors
.....
```
ipsec.conf：
``` 
version 2.0 

config setup
  virtual-private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!,%v4:!
  protostack=netkey不
  interfaces=%defaultroute
  uniqueids=no

conn shared
  left=%defaultroute
  leftid=183.136.221.200
  right=%any
  encapsulation=yes
  authby=secret
  pfs=no
  rekey=no
  keyingtries=5
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
  ike=3des-sha1,3des-sha2,aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024
  phase2alg=3des-sha1,3des-sha2,aes-sha1,aes-sha2,aes256-sha2_512
  sha2-truncbug=yes

conn l2tp-psk
  auto=add
  leftprotoport=17/1701
  rightprotoport=17/%any
  type=transport
  phase2=esp
  also=shared
```
ipsec.secrets
```
 %any %any : PSK "xxxx
```

**Comment by letoams** [comment]
Interesting, I will try to reproduce that

**Comment by Leslie-V** [comment]
> Interesting, I will try to reproduce that Sent from mobile device
> […](#)
> On Apr 4, 2019, at 14:11, Leslie ***@***.***> wrote: hi guys: i got big problem with libreswan-3.27 i used libreswan + xl2tpd for L2TP/IPsec server when some clients(more than 10) behind same NAT ,sometimes libreswan will stop working and all clients be dropped. client:IOS-12 crypto:PSK LOG: 19:36:19 localhost.localdomain xl2tpd[9701]: network_thread: unable to find call or tunnel to handle packet. call = 58561, tunnel = 21864 Dumping. 19:36:19 localhost.localdomain pluto[706]: recvmsg(,, MSG_ERRQUEUE): given up reading socket after 32 EAGAIN errors 19:36:19 localhost.localdomain pluto[706]: recvmsg(,, MSG_ERRQUEUE): given up reading socket after 32 EAGAIN errors 19:36:19 localhost.localdomain pluto[706]: recvmsg(,, MSG_ERRQUEUE): given up reading socket after 32 EAGAIN errors 19:36:19 localhost.localdomain pluto[706]: recvmsg(,, MSG_ERRQUEUE): given up reading socket after 32 EAGAIN errors 19:36:19 localhost.localdomain pluto[706]: recvmsg(,, MSG_ERRQUEUE): given up reading socket after 32 EAGAIN errors 19:36:19 localhost.localdomain pluto[706]: recvmsg(,, MSG_ERRQUEUE): given up reading socket after 32 EAGAIN errors 19:36:19 localhost.localdomain pluto[706]: recvmsg(,, MSG_ERRQUEUE): given up reading socket after 32 EAGAIN errors 19:36:19 localhost.localdomain pluto[706]: recvmsg(,, MSG_ERRQUEUE): given up reading socket after 32 EAGAIN errors ..... ipsec.conf： version 2.0 config setup virtual-private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!,%v4:! protostack=netkey不 interfaces=%defaultroute uniqueids=no conn shared left=%defaultroute leftid=183.136.221.200 right=%any encapsulation=yes authby=secret pfs=no rekey=no keyingtries=5 dpddelay=30 dpdtimeout=120 dpdaction=clear ike=3des-sha1,3des-sha2,aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024 phase2alg=3des-sha1,3des-sha2,aes-sha1,aes-sha2,aes256-sha2_512 sha2-truncbug=yes conn l2tp-psk auto=add leftprotoport=17/1701 rightprotoport=17/%any type=transport phase2=esp also=shared ipsec.secrets %any %any : PSK "xxxx — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

how is the result ?

**Comment by felangga** [comment]
Getting the same error, still no solution?

**Comment by cagney** [comment]
Which (linux) kernel?

**Comment by cagney** [comment]
Assuming this is a linux kernel issue.

**Comment by ashwani20** [comment]
@leslie2050 Were u able to repro this issues? If yes, how did u fix it?

**Comment by paulwouters** [comment]
Is this still an issue with recent kernels? We were under the impression this was fixed.

**Comment by ashwani20** [comment]
@paulwouters Kernel: Linux 4.14.35-2047.518.4.1.el7uek.x86_64 is running on my host. Could u pls tell what recent kernel version had a fix for it?

**Comment by letoams** [comment]
I don’t know exactly when this was fixed. 4.14 feels a bit old. Try a 6.x kernel ?
