### ISSUE TITLE
Issue IKEV1 for Libreswan 3.27 : no connection has been authorized with policy PSK+IKEV1_ALLOW

### ISSUE THREAD

**Issue by srugano** [libreswan/libreswan#242]
Hi all,
I'm trying to connect to a Cisco ASA 5520. I have been provided credentials :

**Phase1**

VPN IP address (Public IP)     | **XXX.XXX.XXX.XXX**
Authentication Method            | Pre-Shared Secret
Encryption Schema                 | IKE
Perfect Forward Secrecy- IKE | DH Group-2
Encryption Algorithm                | 3DES
Hashing Algorithm                    | SHA-1
Renegotiate IKE SA every        | 86400 Sec

**Phase2**

IPSec                                           | ESP
Perfect Forward Secrecy-IPSEC | NO PFS
Encryption Algorithm IPSec         | 3DES
Hashing Algorithm IPSec             | SHA-1
Renegotiate IPSec SA every       | 3600 Sec  
Private Network                           | 192.168.XXX.XXX/32

On my side, I compiled and installed Libreswan (3.27) on a DigitalOcean droplet, with the public IP : **YYY.YYY.YYY.YYY** and a private IP: 10.YYY.YYY.YYY/32. I tried to implement the IPSec VPN with this config: 

conn the_vpn
  ike=3des-sha1;modp1024,aes128-sha1;modp1024
  auto=start
  authby=secret
  keyexchange=ike
  phase2=esp
  phase2alg=3des-sha1
  left=XXX.XXX.XXX.XXX
  leftsubnet=192.168.XXX.XXX/32
  right=YYY.YYY.YYY.YYY
  rightsubnet=10.YYY.YYY.YYY/32
  ikelifetime=3600
  type=tunnel
  ikev2=never

And I did allow `udp` on port `500` and `4500` in my server (Ubuntu 16.04). I also wrote down the secrekey in `/etc/ipsec.secrets`. But through the logs; it seems that the handshake is initialized by the CISCO, but my side has this error:

` **packet from _XXX.XXX.XXX.XXX:500_: initial Main Mode message received on _YYY.YYY.YYY.YYY:500_  but no connection has been authorized with policy PSK+IKEV1_ALLOW**`

My question are these: 
1) does Libreswan still allow IKEV1 with shared PSK and DH 2 group or it has been deprecated and removed ?
2) does my configurations reflect the other side ? Because, as usual, It's me who has to conform to their setup, they can't change anything. 

Thank you.

**Comment by letoams** [comment]
On Thu, 4 Apr 2019, Allan Stockman RUGANO wrote:

> I'm trying to connect to a Cisco ASA 5520. I have been provided credentials :
> 
> Phase1
> 
> VPN IP address (Public IP) | XXX.XXX.XXX.XXX
> Authentication Method | Pre-Shared Secret
> Encryption Schema | IKE
> Perfect Forward Secrecy- IKE | DH Group-2
> Encryption Algorithm | 3DES
> Hashing Algorithm | SHA-1
> Renegotiate IKE SA every | 86400 Sec

These are settings from the 1990s......

> IPSec | ESP
> Perfect Forward Secrecy-IPSEC | NO PFS
> Encryption Algorithm IPSec | 3DES
> Hashing Algorithm IPSec | SHA-1

These too. And I am confused about the pfs being on and off at the same
time ?

> Renegotiate IPSec SA every | 3600 Sec  
> Private Network | 192.168.XXX.XXX/32
> 
> On my side, I compiled and installed Libreswan (3.27) on a DigitalOcean droplet, with the public IP : YYY.YYY.YYY.YYY and a
> private IP: 10.YYY.YYY.YYY/32. I tried to implement the IPSec VPN with this config:
> 
> conn the_vpn
> ike=3des-sha1;modp1024,aes128-sha1;modp1024
> auto=start
> authby=secret
> keyexchange=ike
> phase2=esp
> phase2alg=3des-sha1
> left=XXX.XXX.XXX.XXX
> leftsubnet=192.168.XXX.XXX/32
> right=YYY.YYY.YYY.YYY
> rightsubnet=10.YYY.YYY.YYY/32
> ikelifetime=3600
> type=tunnel
> ikev2=never
> 
> And I did allow udp on port 500 and 4500 in my server (Ubuntu 16.04). I also wrote down the secrekey in /etc/ipsec.secrets. But
> through the logs; it seems that the handshake is initialized by the CISCO, but my side has this error:
> 
> **packet from _XXX.XXX.XXX.XXX:500_: initial Main Mode message received on _YYY.YYY.YYY.YYY:500_ but no connection has been
> authorized with policy PSK+IKEV1_ALLOW**

Did your connection load at all? Run ipsec auto --add the_vpn to see any
errors.

> My question are these:
>
>  1. does Libreswan still allow IKEV1 with shared PSK and DH 2 group or it has been deprecated and removed ?

It allows it for now, but RFC 8247 gives implementers the advise of
SHOULD NOT implement for DH2 so it will go away in a few years.

>  2. does my configurations reflect the other side ? Because, as usual, It's me who has to conform to their setup, they can't
>     change anything.

Other then that anonimized ID/IP parts that I cannot check it looks
fine. But try the above command because i think it might fail for
some reason to load your connection.

Paul

**Comment by srugano** [comment]
I'm connecting to an old ISP, ... their techs aren't up to date,... since there is no insensitive to change that. 
The command `ipsec auto --add the_vpn` shows no error, but the command `ipsec auto --up ecocash_vpn` yield this:

    022 "ecocash_vpn": We cannot identify ourselves with either end of this connection.  196.13.223.200 or 40.101.150.72 are not usable
    036 failed to initiate ecocash_vpn

When I look into pluto, I get this :

> Apr  5 15:43:15.181225: added connection description "the_vpn"
> Apr  5 15:43:15.181253: | 192.168.XXX.XXX/32===XXX.XXX.XXX.XXX<XXX.XXX.XXX.XXX>...YYY.YYY.YYY.YYY<YYY.YYY.YYY.YYY>===10.YYY.YYY.YYY/32
> Apr  5 15:43:15.181270: | ike_life: 3600s; ipsec_life: 28800s; rekey_margin: 540s; rekey_fuzz: 100%; keyingtries: 0; replay_window: 32; policy: PSK+ENCRYPT+TUNNEL+PFS+IKEV1_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO
> Apr  5 15:43:15.181289: | close_any(fd@14) (in whack_process() at rcv_whack.c:661)
> Apr  5 15:43:15.181376: | accept(whackctlfd, (struct sockaddr *)&whackaddr, &whackaddrlen) -> fd@14 (in whack_handle() at rcv_whack.c:681)
> Apr  5 15:43:15.181423: | pluto_sd: executing action action: reloading(4), status 0
> Apr  5 15:43:15.182231: listening for IKE messages
> Apr  5 15:43:15.182298: | Inspecting interface lo 
> Apr  5 15:43:15.182319: | found lo with address 127.0.0.1
> Apr  5 15:43:15.182329: | Inspecting interface eth0 
> Apr  5 15:43:15.182339: | found eth0 with address 46.101.150.72
> Apr  5 15:43:15.182348: | Inspecting interface eth0 
> Apr  5 15:43:15.182357: | found eth0 with address 10.19.YYY.YYY
> Apr  5 15:43:15.182365: | Inspecting interface eth1 
> Apr  5 15:43:15.182374: | found eth1 with address 10.YYY.YYY.YYY
> Apr  5 15:43:15.182431: adding interface eth1/eth1 10.YYY.YYY.YYY:500
> Apr  5 15:43:15.182474: | NAT-Traversal: Trying sockopt style NAT-T
> Apr  5 15:43:15.182488: | NAT-Traversal: ESPINUDP(2) setup succeeded for sockopt style NAT-T family IPv4
> Apr  5 15:43:15.182498: adding interface eth1/eth1 10.YYY.YYY.YYY:4500
> Apr  5 15:43:15.182532: adding interface eth0/eth0 10.19.YYY.YYY:500
> Apr  5 15:43:15.182568: | NAT-Traversal: Trying sockopt style NAT-T
> Apr  5 15:43:15.182581: | NAT-Traversal: ESPINUDP(2) setup succeeded for sockopt style NAT-T family IPv4
> Apr  5 15:43:15.182590: adding interface eth0/eth0 10.19.YYY.YYY:4500
> Apr  5 15:43:15.182624: adding interface eth0/eth0 46.101.150.72:500
> Apr  5 15:43:15.182656: | NAT-Traversal: Trying sockopt style NAT-T
> Apr  5 15:43:15.182670: | NAT-Traversal: ESPINUDP(2) setup succeeded for sockopt style NAT-T family IPv4
> Apr  5 15:43:15.182679: adding interface eth0/eth0 46.101.150.72:4500
> Apr  5 15:43:15.182714: adding interface lo/lo 127.0.0.1:500
> Apr  5 15:43:15.182748: | NAT-Traversal: Trying sockopt style NAT-T
> Apr  5 15:43:15.182761: | NAT-Traversal: ESPINUDP(2) setup succeeded for sockopt style NAT-T family IPv4
> Apr  5 15:43:15.182769: adding interface lo/lo 127.0.0.1:4500
> Apr  5 15:43:15.182851: | found lo with address 0000:0000:0000:0000:0000:0000:0000:0001
> Apr  5 15:43:15.182874: | found eth0 with address 2a03:b0c0:0003:00d0:0000:0000:0122:4001
> Apr  5 15:43:15.182928: adding interface eth0/eth0 2a03:b0c0:3:d0::122:4001:500
> Apr  5 15:43:15.182969: adding interface lo/lo ::1:500
> Apr  5 15:43:15.183003: | setup callback for interface lo:500 fd 24
> Apr  5 15:43:15.183018: | setup callback for interface eth0:500 fd 23
> Apr  5 15:43:15.183030: | setup callback for interface lo:4500 fd 22
> Apr  5 15:43:15.183041: | setup callback for interface lo:500 fd 21
> Apr  5 15:43:15.183052: | setup callback for interface eth0:4500 fd 20
> Apr  5 15:43:15.183067: | setup callback for interface eth0:500 fd 19
> Apr  5 15:43:15.183078: | setup callback for interface eth0:4500 fd 18
> Apr  5 15:43:15.183101: | setup callback for interface eth0:500 fd 17
> Apr  5 15:43:15.183113: | setup callback for interface eth1:4500 fd 16
> Apr  5 15:43:15.183124: | setup callback for interface eth1:500 fd 15
> Apr  5 15:43:15.183136: | certs and keys locked by 'free_preshared_secrets'
> Apr  5 15:43:15.183145: | certs and keys unlocked by 'free_preshared_secrets'
> Apr  5 15:43:15.183187: loading secrets from "/etc/ipsec.secrets"
> Apr  5 15:43:15.183269: loading secrets from "/etc/ipsec.d/ecocash.secrets"
> Apr  5 15:43:15.183297: | id type added to secret(0x56101c1466b8) PKK_PSK: XXX.XXX.XXX.XXX
> Apr  5 15:43:15.183310: | id type added to secret(0x56101c1466b8) PKK_PSK: YYY.YYY.YYY.YYY
> Apr  5 15:43:15.183322: | Processing PSK at line 1: passed
> Apr  5 15:43:15.183330: | certs and keys locked by 'process_secret'
> Apr  5 15:43:15.183338: | certs and keys unlocked by 'process_secret'
> Apr  5 15:43:15.183354: | pluto_sd: executing action action: ready(5), status 0
> Apr  5 15:43:15.183928: | close_any(fd@14) (in whack_process() at rcv_whack.c:661)
> Apr  5 15:43:15.184061: | accept(whackctlfd, (struct sockaddr *)&whackaddr, &whackaddrlen) -> fd@14 (in whack_handle() at rcv_whack.c:681)
> Apr  5 15:43:15.184119: | processing: start connection "the_vpn" (in initiate_a_connection() at initiate.c:187)
> Apr  5 15:43:15.184140: "the_vpn": We cannot identify ourselves with either end of this connection.  XXX.XXX.XXX.XXX or YYY.YYY.YYY.YYY are not usable
> Apr  5 15:43:15.184155: | processing: stop connection "the_vpn" (in initiate_a_connection() at initiate.c:219)

**Comment by letoams** [comment]
On Fri, 5 Apr 2019, Allan Stockman RUGANO wrote:

> I'm connecting to an old ISP, ... their techs aren't up to date,... since there is no insensitive to change that.
> The command ipsec auto --add the_vpn shows no error, but the command ipsec auto --up ecocash_vpn yield this:
> 
> 022 "ecocash_vpn": We cannot identify ourselves with either end of this connection.  196.13.223.200 or 40.101.150.72 are not usable
> 036 failed to initiate ecocash_vpn
> 
> When I look into pluto, I get this :
>
>       Apr 5 15:43:15.182231: listening for IKE messages
>       Apr 5 15:43:15.182298: | Inspecting interface lo
>       Apr 5 15:43:15.182319: | found lo with address 127.0.0.1
>       Apr 5 15:43:15.182329: | Inspecting interface eth0
>       Apr 5 15:43:15.182339: | found eth0 with address 46.101.150.72
>       Apr 5 15:43:15.182348: | Inspecting interface eth0
>       Apr 5 15:43:15.182357: | found eth0 with address 10.19.YYY.YYY
>       Apr 5 15:43:15.182365: | Inspecting interface eth1
>       Apr 5 15:43:15.182374: | found eth1 with address 10.YYY.YYY.YYY
>       Apr 5 15:43:15.182431: adding interface eth1/eth1 10.YYY.YYY.YYY:500
>       Apr 5 15:43:15.182498: adding interface eth1/eth1 10.YYY.YYY.YYY:4500
>       Apr 5 15:43:15.182532: adding interface eth0/eth0 10.19.YYY.YYY:500
>       Apr 5 15:43:15.182590: adding interface eth0/eth0 10.19.YYY.YYY:4500
>       Apr 5 15:43:15.182624: adding interface eth0/eth0 46.101.150.72:500
>       Apr 5 15:43:15.182679: adding interface eth0/eth0 46.101.150.72:4500
>       Apr 5 15:43:15.182714: adding interface lo/lo 127.0.0.1:500
>       Apr 5 15:43:15.182769: adding interface lo/lo 127.0.0.1:4500

>       Apr 5 15:43:15.184140: "the_vpn": We cannot identify ourselves with either end of this connection. XXX.XXX.XXX.XXX or YYY.YYY.YYY.YYY are not usable

The configuration for your tunnel contains a left= and right= that has
an IP address that is not present on the system. As such, the connection
cannot be loaded because it cannot be determined if this host is
supposed to be "left" or "right".

Presumably some IP address on the host changed and the ipsec
configuration file was not updated. If you want the system
to pick up the IP dynamically, you can use the magic value
"%defaultroute" to give is the default IP address based on
the routing table.

Paul

**Comment by srugano** [comment]
Thanks @letoams . The VPN is up. Just the remaining routing for traffic to pass through.

**Comment by mendesbarretto** [comment]
@srugano 

Hello how are you.

I have the same error, how did you solve your error?

**Comment by letoams** [comment]
Match IKE version protocol between the two endpoints. Either use ikev2=no or better yet tell the other peer to use IKEv2 instead of IKEv1
