### ISSUE TITLE
Support for multiple leftsubnets as server

### ISSUE THREAD

**Issue by rysi3k** [libreswan/libreswan#243]
Hello,
I posted a issue to script using libreswan as dependency and I get response that leftsubnets are not possible when working as server.
Any chances to implement this?
https://github.com/hwdsl2/setup-ipsec-vpn/issues/530

Thanks in advance.

Regards

**Comment by letoams** [comment]
we just fixed a bug for this, fix is in git main and will be in 4.4. As long as you don't use right=%any but a remote peer IP/hostname, it will work now. We are looking at the %any issue now

**Comment by cagney** [comment]
mainline supports leftsubnet=a,b,c ...
