### ISSUE TITLE
avoid linking everything against libnssutil3.so

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#248]
On standard debian builds, the following libreswan utilities link against against libnssutil3.so even though they don't use any symbols from it:

- usr/lib/ipsec/showhostkey
- usr/lib/ipsec/_import_crl
- usr/lib/ipsec/cavp
- usr/lib/ipsec/pluto
- usr/lib/ipsec/readwriteconf
- usr/lib/ipsec/rsasigkey
- usr/lib/ipsec/algparse

this seems to be due to `pkg-config --libs nss` emitting `-lnssutil3`.  should i be sending `-Wl,--as-needed` during compilation to avoid this unnecessary linkage?

Or, is there some reason i should make sure i do *not* use `-Wl,--as-needed` ?

**Comment by letoams** [comment]
Seems we already do this:
[paul@thinkpad libreswan]$ grep as-needed mk/*
grep: mk/defaults: Is a directory
mk/userland.mk:USERLAND_LDFLAGS+=-Wl,--as-needed

the resulting pluto, rsasigkey still links against nssutil3 though ?

How did you determine they don't actually use smybols from it?
