### ISSUE TITLE
Please make it FreeBSD-compatible

### ISSUE THREAD

**Issue by yurivict** [libreswan/libreswan#250]
It currently doesn't build on FreeBSD.

**Comment by libreswan** [comment]
We'd **really** like to make this happen, but it is not a high priority for now. We should have more time in about three months

**Comment by libreswan** [comment]
if anyone is willing to help work on this, we can assist.

**Comment by cagney** [comment]
Libreswan runs on NetBSD, so it should be buildable on FreeBSD (with a few config tweaks).

**Comment by yurivict** [comment]
There's no need to support system by system.

With modern tools packages build on a variety of systems with minimal effort.

**Comment by cagney** [comment]
> There's no need to support system by system.
> 
> With modern tools packages build on a variety of systems with minimal effort.

FYI, the FreeBSD and NetBSD pfkey v2 libraries have diverged significantly.

**Comment by cagney** [comment]
https://www.freshports.org/security/libreswan/
