### ISSUE TITLE
Authentication Failed when certificates are used

### ISSUE THREAD

**Issue by Yatish04** [libreswan/libreswan#251]
I have been trying to establish IPSec connections between two Local VMs (installed on my Mac) using certificates.
 
I followed the steps mentioned in this link (https://libreswan.org/wiki/HOWTO:_Using_NSS_with_libreswan#Configuring_certificates_in_ipsec.conf_and_ipsec.secrets)
I created a Certificate Authority on one of the machine and created a user certificate signed with this CA.
 
certutil -S -k rsa -n "MyCA" -s "CN=localhost.localdomain" -v 12 \
      -t "CT,C,C" -x -d sql:/etc/ipsec.d
 
 
certutil -S -k rsa -c "MyCA" -n "user1" -s "CN=localhost.localdomain" \
          -v 12 -t "u,u,u" -d sql:/etc/ipsec.d
 
To load the CA to the other machine, I exported the CA using
 
pk12util -o CACert.p12 -n MyCA -d sql:/etc/ipsec.d
 
Copied this CACert.p12 file to another machine. Imported it into NSS DB.
ipsec import CACert.p12
 certutil -M -n MyCA -t "CT,," -d sql:/etc/ipsec.d
 
Created another user certificate signed by the same CA 
 
certutil -S -k rsa -c "MyCA" -n "user2" -s "CN=localhost.localdomain" \
        -v 12 -t "u,u,u" -d sql:/etc/ipsec.d
 
 
Now, when I restart IPSec service and try to bring up the connection, I get the following error.
 

[root@localhost ipsec.d]# ipsec auto --up  mytunnel24
002 "mytunnel24" #5: initiating v2 parent SA
133 "mytunnel24" #5: initiate
133 "mytunnel24" #5: STATE_PARENT_I1: sent v2I1, expected v2R1
002 | constructed local ESP/AH proposals for mytunnel24 (IKE SA initiator emitting ESP/AH proposals): 1:ESP:ENCR=AES_GCM_C_256;INTEG=NONE;DH=NONE;ESN=DISABLED 2:ESP:ENCR=CHACHA20_POLY1305;INTEG=NONE;DH=NONE;ESN=DISABLED 3:ESP:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_512_256,HMAC_SHA1_96,HMAC_SHA2_256_128;DH=NONE;ESN=DISABLED 4:ESP:ENCR=AES_GCM_C_128;INTEG=NONE;DH=NONE;ESN=DISABLED 5:ESP:ENCR=AES_CBC_128;INTEG=HMAC_SHA1_96,HMAC_SHA2_256_128;DH=NONE;ESN=DISABLED
134 "mytunnel24" #6: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_512 group=DH19}
002 "mytunnel24" #6: IKE SA authentication request rejected: AUTHENTICATION_FAILED
000 "mytunnel24" #6: scheduling retry attempt 1 of an unlimited number, but releasing whack
 
 
This is the IPSec config file I used.
 
Machine 1:
conn mytunnel24
    type=transport
    left=192.168.244.132
    leftrsasigkey=%cert
    leftcert=user1
    right=192.168.244.130
    rightrsasigkey=%cert
    # load and initiate automatically
    auto=start
 
Machine 2:
 
conn mytunnel24
    type=transport
    left=192.168.244.130
    leftrsasigkey=%cert
    leftcert=user2
    right=192.168.244.132
    rightrsasigkey=%cert
    # load and initiate automatically
    auto=start

**Comment by libreswan** [comment]
what does the logs say on the side that returns AUTHENTICATION_FAILED ?

**Comment by Yatish04** [comment]
I used pluto logs
`ipsec pluto --stderrlog --config /etc/ipsec.conf --nofork & (starts the daemon)
ipsec auto --up mytunnel24`

The following log is on the other machine- 

`Jun 26 21:28:38.009135: packet from 192.168.244.132:500: proposal 1:IKE:ENCR=AES_GCM_C_256;PRF=HMAC_SHA2_512;DH=ECP_256 chosen from remote proposals 1:IKE:ENCR=AES_GCM_C_256;PRF=HMAC_SHA2_512;PRF=HMAC_SHA2_256;DH=ECP_256;DH=ECP_384;DH=ECP_521;DH=MODP2048;DH=MODP3072;DH=MODP4096;DH=MODP8192[first-match] 2:IKE:ENCR=CHACHA20_POLY1305;PRF=HMAC_SHA2_512;PRF=HMAC_SHA2_256;DH=ECP_256;DH=ECP_384;DH=ECP_521;DH=MODP2048;DH=MODP3072;DH=MODP4096;DH=MODP8192 3:IKE:ENCR=AES_CBC_256;PRF=HMAC_SHA2_512;PRF=HMAC_SHA2_256;INTEG=HMAC_SHA2_512_256;INTEG=HMAC_SHA2_256_128;DH=ECP_256;DH=ECP_384;DH=ECP_521;DH=MODP2048;DH=MODP3072;DH=MODP4096;DH=MODP8192 4:IKE:ENCR=AES_GCM_C_128;PRF=HMAC_SHA2_512;PRF=HMAC_SHA2_256;DH=ECP_256;DH=ECP_384;DH=ECP_521;DH=MODP2048;DH=MODP3072;DH=MODP4096;DH=MODP8192 5:IKE:ENCR=AES_CBC_128;PRF=HMAC_SHA2_256;INTEG=HMAC_SHA2_256_128;DH=ECP_256;DH=ECP_384;DH=ECP_521;DH=MODP2048;DH=MODP3072;DH=MODP4096;DH=MODP8192
Jun 26 21:28:38.010188: "mytunnel24" #5: STATE_PARENT_R1: received v2I1, sent v2R1 {auth=IKEv2 cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_512 group=DH19}
Jun 26 21:28:38.018449: "mytunnel24" #5: Certificate CN=Cisco INC failed verification
Jun 26 21:28:38.018468: "mytunnel24" #5: ERROR: Certificate type not approved for application.
Jun 26 21:28:38.018472: "mytunnel24" #5: X509: Certificate rejected for this connection
Jun 26 21:28:38.018530: "mytunnel24" #5: IKEv2 mode peer ID is ID_IPV4_ADDR: '192.168.244.132'
Jun 26 21:28:38.018572: "mytunnel24" #5: no RSA public key known for '192.168.244.132'
Jun 26 21:28:38.018576: "mytunnel24" #5: RSA authentication failed
Jun 26 21:28:38.018580: "mytunnel24" #5: responding to AUTH message (ID 1) from 192.168.244.132:500 with encrypted notification AUTHENTICATION_FAILED
Jun 26 21:28:38.018698: "mytunnel24" #5: deleting state (STATE_PARENT_R1) and NOT sending notification`

The main error on the side where I do(up the tunnel) -
ipsect auto --up mytunnel24 is - 

`002 "mytunnel24" #7: initiating v2 parent SA
133 "mytunnel24" #7: initiate
002 | constructed local IKE proposals for mytunnel24 (IKE SA initiator selecting KE): 1:IKE:ENCR=AES_GCM_C_256;PRF=HMAC_SHA2_512,HMAC_SHA2_256;INTEG=NONE;DH=ECP_256,ECP_384,ECP_521,MODP2048,MODP3072,MODP4096,MODP8192 2:IKE:ENCR=CHACHA20_POLY1305;PRF=HMAC_SHA2_512,HMAC_SHA2_256;INTEG=NONE;DH=ECP_256,ECP_384,ECP_521,MODP2048,MODP3072,MODP4096,MODP8192 3:IKE:ENCR=AES_CBC_256;PRF=HMAC_SHA2_512,HMAC_SHA2_256;INTEG=HMAC_SHA2_512_256,HMAC_SHA2_256_128;DH=ECP_256,ECP_384,ECP_521,MODP2048,MODP3072,MODP4096,MODP8192 4:IKE:ENCR=AES_GCM_C_128;PRF=HMAC_SHA2_512,HMAC_SHA2_256;INTEG=NONE;DH=ECP_256,ECP_384,ECP_521,MODP2048,MODP3072,MODP4096,MODP8192 5:IKE:ENCR=AES_CBC_128;PRF=HMAC_SHA2_256;INTEG=HMAC_SHA2_256_128;DH=ECP_256,ECP_384,ECP_521,MODP2048,MODP3072,MODP4096,MODP8192
133 "mytunnel24" #7: STATE_PARENT_I1: sent v2I1, expected v2R1
002 | constructed local ESP/AH proposals for mytunnel24 (IKE SA initiator emitting ESP/AH proposals): 1:ESP:ENCR=AES_GCM_C_256;INTEG=NONE;DH=NONE;ESN=DISABLED 2:ESP:ENCR=CHACHA20_POLY1305;INTEG=NONE;DH=NONE;ESN=DISABLED 3:ESP:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_512_256,HMAC_SHA1_96,HMAC_SHA2_256_128;DH=NONE;ESN=DISABLED 4:ESP:ENCR=AES_GCM_C_128;INTEG=NONE;DH=NONE;ESN=DISABLED 5:ESP:ENCR=AES_CBC_128;INTEG=HMAC_SHA1_96,HMAC_SHA2_256_128;DH=NONE;ESN=DISABLED
134 "mytunnel24" #8: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_512 group=DH19}
002 "mytunnel24" #8: IKE SA authentication request rejected: AUTHENTICATION_FAILED
000 "mytunnel24" #8: scheduling retry attempt 1 of an unlimited number, but releasing whack`

**Comment by letoams** [comment]
On Wed, 26 Jun 2019, Yatishhr wrote:

> Jun 26 21:28:38.018449: "mytunnel24" #5: Certificate CN=Cisco INC failed verification
> Jun 26 21:28:38.018468: "mytunnel24" #5: ERROR: Certificate type not approved for application.

You seem to have a bad combination of Key Usage (KU) or Extended Key
Usage (EKU). Your certificates should have a KU with digitalSignature,

See https://tools.ietf.org/html/rfc4945#section-5.1.3.2

And could have an empty EKU or some custom EKU's

See https://tools.ietf.org/html/rfc4945#section-5.1.3.12

You can use certificates generated as if it was for a TLS server, eg
having the EKU serverAuth or clientAuth.

Paul

**Comment by Yatish04** [comment]
Here is what I did- 
1. Generated a CA with the EKU . Here is my  CA - 

>Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            00:b1:88:b7:e1
        Signature Algorithm: PKCS #1 SHA-256 With RSA Encryption
        Issuer: "CN=Cisco INC"
        Validity:
            Not Before: Thu Jun 27 03:27:58 2019
            Not After : Sat Jun 27 03:27:58 2020
        Subject: "CN=Cisco INC"
        Subject Public Key Info:
            Public Key Algorithm: PKCS #1 RSA Encryption
            RSA Public Key:
                Modulus:
                    b7:70:cc:a6:4f:c9:9b:53:73:d4:55:4b:3b:1a:1e:4f:
                    89:ef:02:ca:c7:9c:6b:b5:f4:00:ea:ab:b0:17:2f:9d:
                    a2:b9:b5:35:e6:1e:64:c7:70:f5:f5:96:49:7a:e3:42:
                    bc:f3:2e:78:33:41:a0:1f:2e:78:21:51:93:1c:3f:57:
                    54:14:47:1f:44:34:35:63:02:86:b3:c8:ad:a3:29:87:
                    74:71:af:f8:5a:cc:3d:a4:4a:e0:ff:3b:ca:63:84:54:
                    9d:55:06:00:40:1d:02:c0:03:8c:1c:09:5c:bb:df:68:
                    05:7b:85:fb:bb:af:5b:7d:aa:d6:82:80:5e:eb:ff:58:
                    3e:cc:39:8d:00:0c:d6:92:a0:42:2f:55:7e:dc:bf:9a:
                    97:fc:ea:94:fc:5c:de:73:22:e3:8a:9b:32:07:ec:8e:
                    e0:d7:e8:ed:19:35:72:34:48:bd:9c:6b:79:51:41:c5:
                    c2:ae:1d:f6:67:8c:4f:e4:c2:4e:0d:87:7e:ec:b3:47:
                    b8:e1:1a:37:89:25:87:c9:66:47:a6:8a:59:1f:04:23:
                    5d:c2:b8:4b:4c:f0:52:8a:ad:38:5d:87:6c:e5:99:f9:
                    3d:af:67:73:3d:5a:62:3b:b8:7e:56:53:a0:e0:12:cb:
                    52:77:31:8d:aa:09:d0:d7:7a:01:2f:43:a3:38:8c:8d
                Exponent: 65537 (0x10001)
        Signed Extensions:
            Name: Extended Key Usage
            Critical: True
                TLS Web Server Authentication Certificate
                TLS Web Client Authentication Certificate
                Code Signing Certificate
                OCSP Responder Certificate
            Name: Certificate Key Usage
            Critical: True
            Usages: Digital Signature
                    Non-Repudiation
                    Certificate Signing
                    CRL Signing
 
     

Signature Algorithm: PKCS #1 SHA-256 With RSA Encryption

     

 Signature:

        ad:25:2c:0a:9d:7f:ed:9d:7c:87:48:7e:a0:1d:59:91:

        08:ad:ed:c4:47:5d:e5:6c:08:56:16:a7:ff:06:1d:fd:
        68:35:47:19:ed:4f:26:a8:59:c2:a4:e3:a7:e9:c4:67:
        5f:df:10:db:f1:52:99:cc:90:0c:8f:63:5b:07:d7:eb:
        13:b6:8e:0d:68:72:4a:43:37:d7:0f:97:28:17:4e:2e:
        35:12:76:9d:c8:7a:07:7c:42:1d:10:32:71:cb:52:2f:
        bd:63:4a:7e:41:63:23:38:17:01:5f:ec:00:4f:69:5b:
        40:47:8a:e3:da:9f:37:04:9e:f1:10:d4:33:4f:d5:99:
        0a:00:c1:34:f3:b3:75:49:62:6f:ed:2f:68:41:9e:18:
        a7:ba:c1:0e:cd:e0:8c:e5:7d:88:40:8b:2e:55:73:d9:
        e8:c6:03:46:77:2c:68:cc:2e:92:4f:cc:4f:0b:ce:b8:
        50:c2:1f:65:68:ab:6b:c7:54:f3:33:65:0c:79:b3:62:
        f7:47:ac:e6:2e:16:3b:f5:f0:0b:14:49:9c:5d:c3:3a:
        58:4e:53:f7:20:7f:d0:71:83:dc:52:ef:1f:96:6c:36:
        3a:54:3d:45:b5:82:3b:a0:e1:bc:53:a0:18:72:8d:92:
        7f:01:73:1b:55:d9:c6:b7:7f:b2:0b:be:ef:ed:7e:9a
    Fingerprint (SHA-256):
        3C:97:DC:80:D4:1A:16:CE:52:15:41:50:CF:13:D8:D4:40:DC:D7:05:54:78:CD:10:D5:40:1D:15:12:82:19:24
    Fingerprint (SHA1):
        8C:6C:EB:55:65:0F:B0:8D:D1:9C:C7:9F:03:AD:3C:F0:F7:EA:46:57
 
    Mozilla-CA-Policy: false (attribute missing)
    Certificate Trust Flags:
        SSL Flags:
            Valid CA
            Trusted CA
            User
            Trusted Client CA
        Email Flags:
            Valid CA
            Trusted CA
            User
        Object Signing Flags:
            Valid CA
            Trusted CA
            User

I also tried signing cert without above EKU and I am getting the same error.

**Comment by brozs** [comment]
Can you try adding the following to conn config on both machines?

```
leftid=%fromcert
rightid=%fromcert

```
If it does not help, the (extended) key usage of the certificate might be inadequate. Inspect the certificates and also check logs with plutodebug=all on the responder.

**Comment by Yatish04** [comment]
Thanks it worked !!
I also added -

> narrowing=yes
> ikev2=insist
> rekey=yes
> fragmentation=yes
> mobike=yes

to my conn. Connection was established

**Comment by Yatish04** [comment]
Thanks it worked !!
