### ISSUE TITLE
ipsec verify not implemented

### ISSUE THREAD

**Issue by HRockT** [libreswan/libreswan#257]
Hi,
i have this problem when launch ipsec verify:

```
Checking if IPsec got installed and started correctly:

Version check and ipsec on-path                         [OK]
Openswan U2.6.51.5/K4.19.50-v7+ (netkey)
See `ipsec --copyright' for copyright information.
Checking for IPsec support in kernel                    [OK]
 NETKEY: Testing XFRM related proc values
         ICMP default/send_redirects                    [OK]
         ICMP default/accept_redirects                  [OK]
         XFRM larval drop                               [OK]
Hardware random device check                            [N/A]
Two or more interfaces found, checking IP forwarding    [OK]
Checking rp_filter                                      [OK]
Checking that pluto is running                          [OK]
 Pluto listening for IKE on udp 500                     [OK]
 Pluto listening for IKE on tcp 500                     [NOT IMPLEMENTED]
 Pluto listening for IKE/NAT-T on udp 4500              [OK]
 Pluto listening for IKE/NAT-T on tcp 4500              [NOT IMPLEMENTED]
 Pluto listening for IKE on tcp 10000 (cisco)           [NOT IMPLEMENTED]
Checking NAT and MASQUERADEing                          [TEST INCOMPLETE]
Checking 'ip' command                                   [OK]
Checking 'iptables' command                             [OK]

```

my ipsec.conf

```
version 2.0
config setup

        nat_traversal=yes
        protostack=netkey
        virtual_private=%v4:192.168.0.0/16,%v4:10.0.0.0/8,%v4:172.16.0.0/12,%v4:25.0.0.0/8,$
        oe=off

conn L2TP-PSK-NAT
    rightsubnet=vhost:%priv,%no
    also=L2TP-PSK-noNAT

conn L2TP-PSK-noNAT
        authby=secret
        pfs=no
        auto=add
        keyingtries=3
        # we cannot rekey for %any, let client rekey
        rekey=no
        # Apple iOS doesn't send delete notify so we need dead peer detection
        # to detect vanishing clients
        dpddelay=30
        dpdtimeout=120
        dpdaction=clear
        # Set ikelifetime and keylife to same defaults windows has
        ikelifetime=8h
        keylife=1h
        # l2tp-over-ipsec is transport mode
        type=transport
        #
        left=192.168.1.218
        #
        # For updated Windows 2000/XP clients,
        # to support old clients as well, use leftprotoport=17/%any
        leftprotoport=17/%any
right=%any
        # Using the magic port of "%any" means "any one single port". This is
        # a work around required for Apple OSX clients that use a randomly
        # high port.
        rightprotoport=17/%any
        #force all to be nat'ed. because of ios
        forceencaps=yes
# Normally, KLIPS drops all plaintext traffic from IP's it has a crypted
# connection with. With L2TP clients behind NAT, that's not really what
# you want. The connection below allows both l2tp/ipsec and plaintext
# connections from behind the same NAT router.
# The l2tpd use a leftprotoport, so they are more specific and will be used
# first. Then, packets for the host on different ports and protocols (eg ssh)
# will match this passthrough conn.
conn passthrough-for-non-l2tp
        type=passthrough
        left=192.168.1.218
leftnexthop=192.168.1.1
        right=0.0.0.0
        rightsubnet=vhost:%no,%priv
        auto=route

```

i haven't found a guide for configure it, can you help me ?

**Comment by letoams** [comment]
This is documented at https://libreswan.org/wiki/VPN_server_for_remote_clients_using_IKEv1_with_L2TP

You can ignore the "not implemented" warnings.

**Comment by letoams** [comment]
you can confirm loading the connections manually:
ipsec auto --add L2TP-PSK-noNAT
ipsec auto --add L2TP-PSK-NAT

if that works, you will have to check the logs

**Comment by HRockT** [comment]
> This is documented at https://libreswan.org/wiki/VPN_server_for_remote_clients_using_IKEv1_with_L2TP
> 
> You can ignore the "not implemented" warnings.

@letoams 

I changed the files as the guide asked me and now as soon as I restart the service it comes out like this:


root@raspberrypi:/home/pi# /etc/init.d/xl2tpd restart

```
[....] Restarting xl2tpd (via systemctl): xl2tpd.serviceJob for xl2tpd.service failed because the control process exited with error code.
See "systemctl status xl2tpd.service" and "journalctl -xe" for details.
 failed!
```

root@raspberrypi:/home/pi# /etc/init.d/ipsec restart

```
<27>Jul 10 16:14:59 ipsec_setup: Stopping Openswan IPsec...
<27>Jul 10 16:15:02 ipsec_setup: Starting Openswan IPsec 2.6.51.5...
<27>Jul 10 16:15:03 ipsec_setup: No KLIPS support found while requested, desperately falling back to netkey
<27>Jul 10 16:15:03 ipsec_setup: NETKEY support found. Use protostack=netkey in /etc/ipsec.conf to avoid attempts to use KLIPS. Attempting to continue with NETKEY
root@raspberrypi:/home/pi#

```

**Comment by letoams** [comment]
It shows you are trying to start openswan.
You need to fully delete openswan from your system and then install libreswan ?

**Comment by HRockT** [comment]
> It shows you are trying to start openswan.
> You need to fully delete openswan from your system and then install libreswan ?

i try to remove "apt-get remove openswan", but it isn't installed

**Comment by HRockT** [comment]
> you can confirm loading the connections manually:
> ipsec auto --add L2TP-PSK-noNAT
> ipsec auto --add L2TP-PSK-NAT
> 
> if that works, you will have to check the logs

root@raspberrypi:/etc# ipsec auto --add L2TP-PSK-noNAT
`conn 'L2TP-PSK-noNAT': not found (tried aliases)
`root@raspberrypi:/etc# ipsec auto --add L2TP-PSK-NAT
`conn 'L2TP-PSK-NAT': not found (tried aliases)
`

i try, but this are the results. (i remove all openswan) @letoams

**Comment by HRockT** [comment]
/etc/ipsec.conf
```

config setup
    # needed when using PSK only. Not needed for X.509 based servers
    uniqueids=no
    virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:25.0.0.0/8,%v4:$

conn ikev1
        authby=secret
        pfs=no
        auto=add
        rekey=no
        left=%defaultroute
        right=%any
        ikev2=never
        type=transport
        leftprotoport=17/1701
        rightprotoport=17/%any
        dpddelay=15
        dpdtimeout=30
        dpdaction=clear

```
/etc/ipsec.secrets

`: PSK "passwordcreate"`

/etc/xl2tpd/xl2tpd.conf

```
;
; Sample l2tpd configuration file
;
; This example file should give you some idea of how the options for l2tpd
; should work.  The best place to look for a list of all options is in
; the source code itself, until I have the time to write better documentation :)
; Specifically, the file "file.c" contains a list of commands at the end.
;
; You most definitely don't have to spell out everything as it is done here
;
; [global]                                                              ; Global parameters:
; port = 1701                                                   ; * Bind to port 1701
; auth file = /etc/l2tpd/l2tp-secrets   ; * Where our challenge secrets are
; access control = yes                                  ; * Refuse connections without IP m$
; rand source = dev                     ; Source for entropy for random
;                                       ; numbers, options are:
;                                       ; dev - reads of /dev/urandom
;                                       ; sys - uses rand()
;                                       ; egd - reads from egd socket
;                                       ; egd is not yet implemented
;
; [lns default]                                                 ; Our fallthrough LNS defin$
; exclusive = no                                                ; * Only permit one tunnel $
; ip range = 192.168.0.1-192.168.0.20   ; * Allocate from this IP range
; no ip range = 192.168.0.3-192.168.0.9 ; * Except these hosts
; ip range = 192.168.0.5                                ; * But this one is okay
; ip range = lac1-lac2                                  ; * And anything from lac1 to lac2'$
; lac = 192.168.1.4 - 192.168.1.8               ; * These can connect as LAC's
; no lac = untrusted.marko.net                  ; * This guy can't connect
; hidden bit = no                                               ; * Use hidden AVP's?
; local ip = 192.168.1.2                                ; * Our local IP to use
; local ip range = 192.168.200.0-192.168.200.20   ; Alternatively, use a range for local ad$
; length bit = yes                                              ; * Use length bit in paylo$
; require chap = yes                                    ; * Require CHAP auth. by peer
; refuse pap = yes                                              ; * Refuse PAP authenticati$
; refuse chap = no                                              ; * Refuse CHAP authenticat$
; refuse authentication = no                    ; * Refuse authentication altogether
; require authentication = yes                  ; * Require peer to authenticate
; unix authentication = no                              ; * Use /etc/passwd for auth.
; name = myhostname                                             ; * Report this as our host$
; ppp debug = no                                                ; * Turn on PPP debugging
; pppoptfile = /etc/ppp/options.l2tpd.lns       ; * ppp options file
; call rws = 10                                                 ; * RWS for call (-1 is val$
; tunnel rws = 4                                                ; * RWS for tunnel (must be$
; flow bit = yes                                                ; * Include sequence numbers
; challenge = yes                                               ; * Challenge authenticate $
; rx bps = 10000000                             ; Receive tunnel speed
; tx bps = 10000000                             ; Transmit tunnel speed
; bps = 100000                                  ; Define both receive and transmit speed in$

; [lac marko]                                                   ; Example VPN LAC definition
; lns = lns.marko.net                                   ; * Who is our LNS?
; lns = lns2.marko.net                                  ; * A backup LNS (not yet used)
; redial = yes                                                  ; * Redial if disconnected?
; redial timeout = 15                                   ; * Wait n seconds between redials
; max redials = 5                                               ; * Give up after n consecu$
; hidden bit = yes                                              ; * User hidden AVP's?
; local ip = 192.168.1.1                                ; * Force peer to use this IP for us
; remote ip = 192.168.1.2                               ; * Force peer to use this as their$
; length bit = no                                               ; * Use length bit in paylo$
; require pap = no                                              ; * Require PAP auth. by pe$
; require chap = yes                                    ; * Require CHAP auth. by peer
; refuse pap = yes                                              ; * Refuse PAP authenticati$
; refuse chap = no                                              ; * Refuse CHAP authenticat$
; refuse authentication = no                    ; * Refuse authentication altogether
; require authentication = yes                  ; * Require peer to authenticate
; name = marko                                                  ; * Report this as our host$
; ppp debug = no                                                ; * Turn on PPP debugging
; pppoptfile = /etc/ppp/options.l2tpd.marko     ; * ppp options file for this lac
; call rws = 10                                                 ; * RWS for call (-1 is val$
; tunnel rws = 4                                                ; * RWS for tunnel (must be$
; flow bit = yes                                                ; * Include sequence numbers
; challenge = yes                                               ; * Challenge authenticate $
;
; [lac cisco]                                                   ; Another quick LAC
; lns = cisco.marko.net                                 ; * Required, but can take from def$
; require authentication = yes
[global]
 listen-addr = here public ip but if restart the service this is failed, if ins private ip work
    ipsec saref = no
    force userspace = no
    ; debug tunnel = yes

[lns default]
    ip range = 192.168.1.219-192.168.1.230
    local ip = 192.168.1.218
    require chap = yes
 refuse pap = yes
    require authentication = yes
    name = LinuxVPNserver
    ppp debug = yes
    pppoptfile = /etc/ppp/options.xl2tpd
    length bit = yes
```

/etc/ppp/options.xl2tpd


```
ipcp-accept-local
ipcp-accept-remote
# use an internal server for DNS if you need to reach local-only zones or if
# you want DNS to be encrypted through the tunnel.
ms-dns  192.168.1.1
# ms-dns  8.8.8.8
# ms-dns
noccp
auth
crtscts
idle 1800
# when having MTU issues, can be decreased to about 1200
mtu 1410
mru 1410
nodefaultroute
debug
lock
proxyarp
connect-delay 5000
```

/etc/ppp/chap-secrets

```
# /etc/ppp/chap-secrets
# Secrets for authentication using CHAP
# client    server     secret          IP addresses
ras1       *          "password123"     *
#
```

@letoams

**Comment by Bross19** [comment]
hi, i have too this problem with port udp 4500.
Pluto listening for IKE/NAT-T on udp 4500        	[DISABLED].
iptables -I INPUT -p tcp --dport 4500 -j ACCEPT but the command not go.
another problem:
systemctl enable ipsec.service
Synchronizing state of ipsec.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ipsec
update-rc.d: error: ipsec Default-Start contains no runlevels, aborting.

**Comment by letoams** [comment]
You renamed the conn, so try: ipsec auto — add ikev1

**Comment by HRockT** [comment]
> You renamed the conn, so try: ipsec auto — add ikev1 Sent from mobile device
> […](#)
> On Jul 10, 2019, at 11:27, HRockT ***@***.***> wrote: /etc/ipsec.conf config setup # needed when using PSK only. Not needed for X.509 based servers uniqueids=no virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:25.0.0.0/8,%v4:$ conn ikev1 authby=secret pfs=no auto=add rekey=no left=%defaultroute right=%any ikev2=never type=transport leftprotoport=17/1701 rightprotoport=17/%any dpddelay=15 dpdtimeout=30 dpdaction=clear /etc/ipsec.secrets : PSK "passwordcreate" /etc/xl2tpd/xl2tpd.conf ; ; Sample l2tpd configuration file ; ; This example file should give you some idea of how the options for l2tpd ; should work. The best place to look for a list of all options is in ; the source code itself, until I have the time to write better documentation :) ; Specifically, the file "file.c" contains a list of commands at the end. ; ; You most definitely don't have to spell out everything as it is done here ; ; [global] ; Global parameters: ; port = 1701 ; * Bind to port 1701 ; auth file = /etc/l2tpd/l2tp-secrets ; * Where our challenge secrets are ; access control = yes ; * Refuse connections without IP m$ ; rand source = dev ; Source for entropy for random ; ; numbers, options are: ; ; dev - reads of /dev/urandom ; ; sys - uses rand() ; ; egd - reads from egd socket ; ; egd is not yet implemented ; ; [lns default] ; Our fallthrough LNS defin$ ; exclusive = no ; * Only permit one tunnel $ ; ip range = 192.168.0.1-192.168.0.20 ; * Allocate from this IP range ; no ip range = 192.168.0.3-192.168.0.9 ; * Except these hosts ; ip range = 192.168.0.5 ; * But this one is okay ; ip range = lac1-lac2 ; * And anything from lac1 to lac2'$ ; lac = 192.168.1.4 - 192.168.1.8 ; * These can connect as LAC's ; no lac = untrusted.marko.net ; * This guy can't connect ; hidden bit = no ; * Use hidden AVP's? ; local ip = 192.168.1.2 ; * Our local IP to use ; local ip range = 192.168.200.0-192.168.200.20 ; Alternatively, use a range for local ad$ ; length bit = yes ; * Use length bit in paylo$ ; require chap = yes ; * Require CHAP auth. by peer ; refuse pap = yes ; * Refuse PAP authenticati$ ; refuse chap = no ; * Refuse CHAP authenticat$ ; refuse authentication = no ; * Refuse authentication altogether ; require authentication = yes ; * Require peer to authenticate ; unix authentication = no ; * Use /etc/passwd for auth. ; name = myhostname ; * Report this as our host$ ; ppp debug = no ; * Turn on PPP debugging ; pppoptfile = /etc/ppp/options.l2tpd.lns ; * ppp options file ; call rws = 10 ; * RWS for call (-1 is val$ ; tunnel rws = 4 ; * RWS for tunnel (must be$ ; flow bit = yes ; * Include sequence numbers ; challenge = yes ; * Challenge authenticate $ ; rx bps = 10000000 ; Receive tunnel speed ; tx bps = 10000000 ; Transmit tunnel speed ; bps = 100000 ; Define both receive and transmit speed in$ ; [lac marko] ; Example VPN LAC definition ; lns = lns.marko.net ; * Who is our LNS? ; lns = lns2.marko.net ; * A backup LNS (not yet used) ; redial = yes ; * Redial if disconnected? ; redial timeout = 15 ; * Wait n seconds between redials ; max redials = 5 ; * Give up after n consecu$ ; hidden bit = yes ; * User hidden AVP's? ; local ip = 192.168.1.1 ; * Force peer to use this IP for us ; remote ip = 192.168.1.2 ; * Force peer to use this as their$ ; length bit = no ; * Use length bit in paylo$ ; require pap = no ; * Require PAP auth. by pe$ ; require chap = yes ; * Require CHAP auth. by peer ; refuse pap = yes ; * Refuse PAP authenticati$ ; refuse chap = no ; * Refuse CHAP authenticat$ ; refuse authentication = no ; * Refuse authentication altogether ; require authentication = yes ; * Require peer to authenticate ; name = marko ; * Report this as our host$ ; ppp debug = no ; * Turn on PPP debugging ; pppoptfile = /etc/ppp/options.l2tpd.marko ; * ppp options file for this lac ; call rws = 10 ; * RWS for call (-1 is val$ ; tunnel rws = 4 ; * RWS for tunnel (must be$ ; flow bit = yes ; * Include sequence numbers ; challenge = yes ; * Challenge authenticate $ ; ; [lac cisco] ; Another quick LAC ; lns = cisco.marko.net ; * Required, but can take from def$ ; require authentication = yes [global] listen-addr = here public ip but if restart the service this is failed, if ins private ip work ipsec saref = no force userspace = no ; debug tunnel = yes [lns default] ip range = 192.168.1.219-192.168.1.230 local ip = 192.168.1.218 require chap = yes refuse pap = yes require authentication = yes name = LinuxVPNserver ppp debug = yes pppoptfile = /etc/ppp/options.xl2tpd length bit = yes /etc/ppp/options.xl2tpd ipcp-accept-local ipcp-accept-remote # use an internal server for DNS if you need to reach local-only zones or if # you want DNS to be encrypted through the tunnel. ms-dns 192.168.1.1 # ms-dns 8.8.8.8 # ms-dns noccp auth crtscts idle 1800 # when having MTU issues, can be decreased to about 1200 mtu 1410 mru 1410 nodefaultroute debug lock proxyarp connect-delay 5000 /etc/ppp/chap-secrets # /etc/ppp/chap-secrets # Secrets for authentication using CHAP # client server secret IP addresses ras1 * "password123" * # @letoams — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

now i have other error, I'm losing my mind, there's too much online confusion about it.

```
Verifying installed system and configuration files

Version check and ipsec on-path                         [OK]
Libreswan 3.29 (netkey) on 4.19.50-v7+
Checking for IPsec support in kernel                    [OK]
 NETKEY: Testing XFRM related proc values
         ICMP default/send_redirects                    [OK]
         ICMP default/accept_redirects                  [OK]
         XFRM larval drop                               [OK]
Pluto ipsec.conf syntax                                 [OK]
Checking rp_filter                                      [OK]
Checking that pluto is running                          [FAILED]
Checking 'ip' command                                   [OK]
Checking 'iptables' command                             [OK]
Checking 'prelink' command does not interfere with FIPS [OK]
Checking for obsolete ipsec.conf options                [OK]

ipsec verify: encountered 2 errors - see 'man ipsec_verify' for help

```

**Comment by letoams** [comment]
Can you start the ipsec service and then run ipsec verify ?

**Comment by HRockT** [comment]
> Can you start the ipsec service and then run ipsec verify ? @letoams 

if start with:

```
root@raspberrypi:/home/pi# systemctl enable ipsec.service


Synchronizing state of ipsec.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ipsec
update-rc.d: error: ipsec Default-Start contains no runlevels, aborting.
```
if start with:
```
root@raspberrypi:/home/pi# ipsec start

Redirecting to: systemctl start ipsec.service
Job for ipsec.service failed because a fatal signal was delivered to the control process.
See "systemctl status ipsec.service" and "journalctl -xe" for details.
root@raspberrypi:/home/pi#
```

**Comment by letoams** [comment]
On Wed, 10 Jul 2019, HRockT wrote:

>       Can you start the ipsec service and then run ipsec verify ? @letoams
> 
> if start with:
> 
> root@raspberrypi:/home/pi# systemctl enable ipsec.service
> 
> Synchronizing state of ipsec.service with SysV service script with /lib/systemd/systemd-sysv-install.
> Executing: /lib/systemd/systemd-sysv-install enable ipsec
> update-rc.d: error: ipsec Default-Start contains no runlevels, aborting.

That looks weird.

> if start with:
> 
> root@raspberrypi:/home/pi# ipsec start
> 
> Redirecting to: systemctl start ipsec.service
> Job for ipsec.service failed because a fatal signal was delivered to the control process.
> See "systemctl status ipsec.service" and "journalctl -xe" for details.

this looks better. Possibly caused by a syntax error in your
configuration. Try running the service precheck manually:

ipsec addconn --checkconfig

Paul

**Comment by HRockT** [comment]
> On Wed, 10 Jul 2019, HRockT wrote: Can you start the ipsec service and then run ipsec verify ? @letoams if start with: ***@***.***:/home/pi# systemctl enable ipsec.service Synchronizing state of ipsec.service with SysV service script with /lib/systemd/systemd-sysv-install. Executing: /lib/systemd/systemd-sysv-install enable ipsec update-rc.d: error: ipsec Default-Start contains no runlevels, aborting.
> That looks weird.
> if start with: ***@***.***:/home/pi# ipsec start Redirecting to: systemctl start ipsec.service Job for ipsec.service failed because a fatal signal was delivered to the control process. See "systemctl status ipsec.service" and "journalctl -xe" for details.
> this looks better. Possibly caused by a syntax error in your configuration. Try running the service precheck manually: ipsec addconn --checkconfig Paul

if launch: ipsec addconn --checkconfig

```
Warning: obsolete keyword 'forceencaps' ignored
Warning: obsolete keyword 'forceencaps' ignored

```

```
sudo systemctl status ipsec.service
● ipsec.service - Internet Key Exchange (IKE) Protocol Daemon for IPsec
   Loaded: loaded (/lib/systemd/system/ipsec.service; disabled; vendor preset: enabled)
   Active: failed (Result: signal) since Wed 2019-07-10 21:43:51 CEST; 5min ago
     Docs: man:ipsec(8)
           man:pluto(8)
           man:ipsec.conf(5)
  Process: 31106 ExecStartPre=/usr/local/libexec/ipsec/addconn --config /etc/ipsec.conf --checkconfig (code=exited, status=0/SUCCESS)
  Process: 31107 ExecStartPre=/usr/local/libexec/ipsec/_stackmanager start (code=exited, status=0/SUCCESS)
  Process: 31272 ExecStartPre=/usr/local/sbin/ipsec --checknss (code=exited, status=0/SUCCESS)
  Process: 31273 ExecStartPre=/usr/local/sbin/ipsec --checknflog (code=exited, status=0/SUCCESS)
  Process: 31284 ExecStart=/usr/local/libexec/ipsec/pluto --leak-detective --config /etc/ipsec.conf --nofork (code=killed, signal=ABRT)
  Process: 31285 ExecStopPost=/sbin/ip xfrm policy flush (code=exited, status=0/SUCCESS)
  Process: 31286 ExecStopPost=/sbin/ip xfrm state flush (code=exited, status=0/SUCCESS)
  Process: 31287 ExecStopPost=/usr/local/sbin/ipsec --stopnflog (code=exited, status=0/SUCCESS)
 Main PID: 31284 (code=killed, signal=ABRT)
   Status: "PLUTO_EXIT=6"

lug 10 21:43:51 raspberrypi systemd[1]: ipsec.service: Service RestartSec=100ms expired, scheduling restart.
lug 10 21:43:51 raspberrypi systemd[1]: ipsec.service: Scheduled restart job, restart counter is at 5.
lug 10 21:43:51 raspberrypi systemd[1]: Stopped Internet Key Exchange (IKE) Protocol Daemon for IPsec.
lug 10 21:43:51 raspberrypi systemd[1]: ipsec.service: Start request repeated too quickly.
lug 10 21:43:51 raspberrypi systemd[1]: ipsec.service: Failed with result 'signal'.
lug 10 21:43:51 raspberrypi systemd[1]: Failed to start Internet Key Exchange (IKE) Protocol Daemon for IPsec.
```

```
sudo /usr/local/libexec/ipsec/pluto --leak-detective --config /etc/ipsec.conf --stderrlog
Jul 10 21:46:53.506526: NSS DB directory: sql:/etc/ipsec.d
Jul 10 21:46:53.508500: Initializing NSS
Jul 10 21:46:53.508560: Opening NSS database "sql:/etc/ipsec.d" read-only
Jul 10 21:46:53.522388: authentication of "NSS Certificate DB" failed
Jul 10 21:46:53.522454: FATAL: NSS initialization failure
Jul 10 21:46:53.525681: ABORT: ASSERTION FAILED: event_initialized(&se->ev) (in free_signal_handlers() at server.c:615)
```

After launching ipsec service i figured out it was pluto fault. Launching that command with —stderrlog option it says NSS database is read-only. Any advice?

update:

I figured out the problem, was a corrupted database so i launched that command and remove all db files

```
sudo ipsec initnss
NSS database already initialised - aborted
To wipe the old NSS database, issue: rm /etc/ipsec.d/*.db
```

now all ipsec verify are OK, but i have alone problem, if launch: 

`systemctl enable ipsec.service`

have this

```
Synchronizing state of ipsec.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ipsec
update-rc.d: error: ipsec Default-Start contains no runlevels, aborting.
```

@letoams

**Comment by letoams** [comment]
I have never seen this runlevel thing.
When libreswan is compiled with systemd support it doesn’t do anything with sysvinit run levels.

You can start pluto manually using: ipsec pluto —config /etc/ipsec.conf

Paul

**Comment by HRockT** [comment]
thanks you so much for your support @letoams
