### ISSUE TITLE
interface kernel route is removed when ipsec shutdown with passthrough

### ISSUE THREAD

**Issue by siuswat** [libreswan/libreswan#259]
I have libreswan 3.28 installed. When ipsec shutdown with a passthrough connection defined. Its Interface route will removed. Same config is running fine on libreswan 3.20

This is the passthrough conn, and this is the single IPSec conn I have.
```
conn passthrough-TEST
  authby=never
  left=127.0.0.1
  leftsubnet=192.168.2.0/24
  right=127.0.0.2
  rightsubnet=192.168.2.0/24
  rekey=no
  type=passthrough
  auto=route
```

The 192.168.2.0/24 network and its kernel route when IPSec service is actived
```
ifconfig enp6s0
enp6s0    Link encap:Ethernet  HWaddr 00:90:0B:31:1D:EB
          inet addr:192.168.2.1  Bcast:192.168.2.255  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)
          Interrupt:17 Memory:febe0000-fec00000

ip route
default via 192.168.3.1 dev enp2s0
192.168.2.0/24 dev enp6s0  proto kernel  scope link  src 192.168.2.1
192.168.3.0/24 dev enp2s0  proto kernel  scope link  src 192.168.3.38

```

Shutdown IPSec
```
# /usr/libexec/ipsec/whack --shutdown
002 shutting down
```

Kernel route of 192.168.2.0/24 is removed
```
ip route
default via 192.168.3.1 dev enp2s0
192.168.3.0/24 dev enp2s0  proto kernel  scope link  src 192.168.3.38
```

**Comment by bleve** [comment]
Does that mean you have static route there before starting libreswan or what's the issue?

**Comment by bleve** [comment]
Thta looks like a misconfiguration to me. I'd guess you need 192.168.2.0/23 for your passthrough connection because both 192.168.2.0/24 and 192.168.3.0/24 are local subnets.

**Comment by siuswat** [comment]
It’s the interface route that added when an interface is up.

This is the interface config of enp6s0

DEVICE=enp6s0
BOOTPROTO=none
ONBOOT=yes
TYPE=Ethernet
IPADDR=192.168.2.1
NETWORK=192.168.2.0
BROADCAST=192.168.2.255
NETMASK=255.255.255.0
IPV6INIT=no
USERCTL=no

When I ifup enp6s0. Kernel will add following route into routing table

192.168.2.0/24 dev enp6s0  proto kernel  scope link  src 192.168.2.1

When I start the IPSec service, this route is still exists. However, when I stop IPSec service. This route "192.168.2.0/24 dev enp6s0  proto kernel  scope link  src 192.168.2.1” is removed.

Regards,
Raymond

**Comment by siuswat** [comment]
The example is just to demonstrate how the interface route is removed when IPSec service stopped which happens on 3.28 libreswan but not on 3.20. The actual config is more complex.

**Comment by bleve** [comment]
How could we leave that route behind? Your config causes same route to be applied. Think again why I suggested netmask /23.

**Comment by bleve** [comment]
Work-around for this issue is to use leftupdown=%disabled. If your version is too old for that, you can use leftupdown=/bin/true.

**Comment by siuswat** [comment]
> Work-around for this issue is to use leftupdown=%disabled. If your version is too old for that, you can use leftupdown=/bin/true.

Thanks. Your work-around works as expected
