### ISSUE TITLE
Some compiler issues have arisen

### ISSUE THREAD

**Issue by missionceo** [libreswan/libreswan#269]
/disk2/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/sys/cdefs.h:296:6: error: "__USE_FORTIFY_LEVEL" is not defined, evaluates to 0 [-Werror=undef]
 # if __USE_FORTIFY_LEVEL > 0
      ^~~~~~~~~~~~~~~~~~~
In file included from /disk2/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/features.h:46:0,
                 from /disk2/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/stdlib.h:8,
                 from /disk2sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/fortify/stdlib.h:20,
                 from /disk2/sdk-20190820/mt7621/openwrt.17/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/libreswan-3.29/lib/libswan/x509dn.c:26:
/disk2/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/sys/glibc-types.h:19:5: error: "__WORDSIZE" is not defined, evaluates to 0 [-Werror=undef]
 #if __WORDSIZE == 64
     ^~~~~~~~~~
In file included from /disk2/sdk-20190820/mt7621/openwrt.17/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/libreswan-3.29/lib/libswan/x509dn.c:27:0:
/disk2/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/fortify/stdio.h: In function 'snprintf':
/disk2/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/fortify/stdio.h:99:2: error: format not a string literal, argument types not checked [-Werror=format-nonliteral]
  return __orig_snprintf(__s, __n, __f, __builtin_va_arg_pack());
  ^~~~~~
/disk2/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/fortify/stdio.h: In function 'sprintf':
/disk2/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/fortify/stdio.h:108:3: error: format not a string literal, argument types not checked [-Werror=format-nonliteral]
   __r = __orig_snprintf(__s, __b, __f, __builtin_va_arg_pack());
   ^~~
/disk2/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/fortify/stdio.h:112:3: error: format not a string literal, argument types not checked [-Werror=format-nonliteral]
   __r = __orig_sprintf(__s, __f, __builtin_va_arg_pack());
   ^~~
In file included from /disk2/sdk-20190820/mt7621/openwrt.17/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/libreswan-3.29/include/constants.h:28:0,
                 from /disk2/sdk-20190820/mt7621/openwrt.17/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/libreswan-3.29/lib/libswan/x509dn.c:29:
/disk2/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/stddef.h: At top level:
/disk2/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/stddef.h:13:36: error: "__cplusplus" is not defined, evaluates to 0 [-Werror=undef]
 #if __STDC_VERSION__ >= 201112L || __cplusplus >= 201103L
                                    ^~~~~~~~~~~
In file included from /disk/sdk-20190820/mt7621/openwrt.17/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/libreswan-3.29/lib/libswan/x509dn.c:29:0:
/disk2sdk-20190820/mt7621/openwrt.17/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/libreswan-3.29/include/constants.h:110:10: fatal error: prcpucfg.h: No such file or directory
 #include <prcpucfg.h> /* from nspr4 devel */
          ^~~~~~~~~~~~
cc1: all warnings being treated as errors
compilation terminated.

That's a strange question

**Comment by lucize** [comment]
I see no errors in master branch https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/packages/ do you also have nss and nspr packages ?

**Comment by letoams** [comment]
You are missing the cross compiled version of nspr and nss, or the NSSFLAGS in libreswan-3.xx/mk/ are set to the wrong directories that point to the cross compiled header files

**Comment by missionceo** [comment]
> I see no errors in master branch https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/packages/ do you also have nss and nspr packages ?

how to see

**Comment by missionceo** [comment]
> You are missing the cross compiled version of nspr and nss, or the NSSFLAGS in libreswan-3.xx/mk/ are set to the wrong directories that point to the cross compiled header files Sent from mobile device
> […](#)
> On Aug 21, 2019, at 22:16, missionceo ***@***.***> wrote: /disk2/zong.yu/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/sys/cdefs.h:296:6: error: "__USE_FORTIFY_LEVEL" is not defined, evaluates to 0 [-Werror=undef] if __USE_FORTIFY_LEVEL > 0 ^~~~~~~~~~~~~~~~~~~ In file included from /disk2/zong.yu/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/features.h:46:0, from /disk2/zong.yu/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/stdlib.h:8, from /disk2/zong.yu/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/fortify/stdlib.h:20, from /disk2/zong.yu/sdk-20190820/mt7621/openwrt.17/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/libreswan-3.29/lib/libswan/x509dn.c:26: /disk2/zong.yu/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/sys/glibc-types.h:19:5: error: "__WORDSIZE" is not defined, evaluates to 0 [-Werror=undef] #if __WORDSIZE == 64 ^~~~~~~~~~ In file included from /disk2/zong.yu/sdk-20190820/mt7621/openwrt.17/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/libreswan-3.29/lib/libswan/x509dn.c:27:0: /disk2/zong.yu/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/fortify/stdio.h: In function 'snprintf': /disk2/zong.yu/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/fortify/stdio.h:99:2: error: format not a string literal, argument types not checked [-Werror=format-nonliteral] return __orig_snprintf(__s, __n, __f, __builtin_va_arg_pack()); ^~~~~~ /disk2/zong.yu/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/fortify/stdio.h: In function 'sprintf': /disk2/zong.yu/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/fortify/stdio.h:108:3: error: format not a string literal, argument types not checked [-Werror=format-nonliteral] __r = __orig_snprintf(__s, __b, __f, __builtin_va_arg_pack()); ^~~ /disk2/zong.yu/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/fortify/stdio.h:112:3: error: format not a string literal, argument types not checked [-Werror=format-nonliteral] __r = __orig_sprintf(__s, __f, __builtin_va_arg_pack()); ^~~ In file included from /disk2/zong.yu/sdk-20190820/mt7621/openwrt.17/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/libreswan-3.29/include/constants.h:28:0, from /disk2/zong.yu/sdk-20190820/mt7621/openwrt.17/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/libreswan-3.29/lib/libswan/x509dn.c:29: /disk2/zong.yu/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/stddef.h: At top level: /disk2/zong.yu/sdk-20190729/mt7621/openwrt.17/staging_dir/toolchain-mipsel_24kc_gcc-7.3.0_musl/include/stddef.h:13:36: error: "__cplusplus" is not defined, evaluates to 0 [-Werror=undef] #if STDC_VERSION >= 201112L || __cplusplus >= 201103L ^~~~~~~~~~~ In file included from /disk2/zong.yu/sdk-20190820/mt7621/openwrt.17/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/libreswan-3.29/lib/libswan/x509dn.c:29:0: /disk2/zong.yu/sdk-20190820/mt7621/openwrt.17/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7621/libreswan-3.29/include/constants.h:110:10: fatal error: prcpucfg.h: No such file or directory #include <prcpucfg.h> /* from nspr4 devel */ ^~~~~~~~~~~~ cc1: all warnings being treated as errors compilation terminated. That's a strange question — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

It looks like my compiler version doesn't have NSS and NSPR,how to get the correct version?

**Comment by letoams** [comment]
I selected libreswan, nss and nspr via “make menuconfig”

**Comment by missionceo** [comment]
> I selected libreswan, nss and nspr via “make menuconfig” Sent from mobile device
> […](#)
> On Aug 22, 2019, at 22:05, missionceo ***@***.***> wrote: I see no errors in master branch https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/packages/ do you also have nss and nspr packages ? how to see — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

![image](https://user-images.githubusercontent.com/44191645/63563307-3580ab00-c593-11e9-95b8-395ee6788793.png)

**Comment by letoams** [comment]
![nspr](https://user-images.githubusercontent.com/3003897/63601516-95775180-c593-11e9-85f3-02cb9925691f.png)

It's available for me.

**Comment by lucize** [comment]
but also you could just install the precompiled packages  from openwrt, is your sdk de master branch or is a vendor provided one ?
you can download the packages sdk from https://github.com/openwrt/packages and add the libs/nspr and libs/nss from there (it should be compatible with your sdk if is not the official one) for more information on adding packages see the openwrt wiki

**Comment by missionceo** [comment]
> ![nspr](https://user-images.githubusercontent.com/3003897/63601516-95775180-c593-11e9-85f3-02cb9925691f.png)
> 
> It's available for me.

can you give Cross compile tool chain of mt7621?

**Comment by missionceo** [comment]
> I see no errors in master branch https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/packages/ do you also have nss and nspr packages ?
no,i have no nss and nspr packages,how should i do ?

**Comment by lucize** [comment]
> can you give Cross compile tool chain of mt7621?

please read https://oldwiki.archive.openwrt.org/about/toolchain or visit https://forum.openwrt.org/ to ask for help on how to do it
wiki is a copy paste example, but read it !
