### ISSUE TITLE
Barf error output in findlog()

### ISSUE THREAD

**Issue by briantuchten** [libreswan/libreswan#272]
Fixes error output from "ipsec barf", at least in bash 3.2 (sorry could not find a way to attach a patch, and no PR submit access to the repo)
/usr/libexec/ipsec/barf: line 55: [: too many arguments
/usr/libexec/ipsec/barf: line 55: [: too many arguments
/usr/libexec/ipsec/barf: line 55: [: too many arguments
/usr/libexec/ipsec/barf: line 55: [: too many arguments
/usr/libexec/ipsec/barf: line 68: [: too many arguments
/usr/libexec/ipsec/barf: line 68: [: too many arguments
/usr/libexec/ipsec/barf: line 68: [: too many arguments
/usr/libexec/ipsec/barf: line 68: [: too many arguments
/usr/libexec/ipsec/barf: line 82: [: too many arguments
/usr/libexec/ipsec/barf: line 82: [: too many arguments
/usr/libexec/ipsec/barf: line 82: [: too many arguments
/usr/libexec/ipsec/barf: line 82: [: too many arguments
/usr/libexec/ipsec/barf: line 82: [: too many arguments
/usr/libexec/ipsec/barf: line 82: [: too many arguments
/usr/libexec/ipsec/barf: line 82: [: too many arguments
/usr/libexec/ipsec/barf: line 82: [: too many arguments

```
diff --git a/programs/barf/barf.in b/programs/barf/barf.in
index 2182da8e21..1344221626 100755
--- a/programs/barf/barf.in
+++ b/programs/barf/barf.in
@@ -54,7 +54,7 @@ findlog() {   # findlog string fallbackstring possiblefile ...
     do
        if [ -s ${LOGS}/${f} -a \
            -f ${LOGS}/${f} -a \
-           grep -E -q "$s" ${LOGS}/${f} ]
+           grep -E -q "$s" ${LOGS}/${f} 2>/dev/null ]
        then
            # aha, this one has it
            findlog_file=${LOGS}/${f}
@@ -81,7 +81,7 @@ findlog() {   # findlog string fallbackstring possiblefile ...
        do
        if [ -f ${LOGS}/${f} -a \
            ! -d ${LOGS}/${f} -a \
-           grep -E -q "$s" ${LOGS}/${f} ]
+           grep -E -q "$s" ${LOGS}/${f} 2>/dev/null ]
        then
            # found it
            findlog_file=${LOGS}/${f}
@@ -94,7 +94,7 @@ findlog() {   # findlog string fallbackstring possiblefile ...
     do
        if [ -s ${LOGS}/${f} -a \
            -f ${LOGS}/${f} -a \
-           grep -E -q "$t" ${LOGS}/${f} ]
+           grep -E -q "$t" ${LOGS}/${f} 2>/dev/null ]
        then
            # found it
            findlog_file=${LOGS}/${f}
```

**Comment by bleve** [comment]
Thank you, fixed with 96d143473dd2cdba8b5783a08bf762e76178dceb
