### ISSUE TITLE
AUTHENTICATION_FAILED

### ISSUE THREAD

**Issue by ZTzha** [libreswan/libreswan#274]
Log：
Sep 11 01:58:54.077402: "greA" #1: initiating Main Mode
Sep 11 01:58:54.079096: "greA" #1: STATE_MAIN_I2: sent MI2, expecting MR2
Sep 11 01:58:54.082359: "greA" #1: Can't find the certificate or private key from the NSS CKA_ID
Sep 11 01:58:54.083528: "greA" #1: unable to locate my private key for RSA Signature
Sep 11 01:58:54.083811: "greA" #1: sending notification AUTHENTICATION_FAILED to 172.16.10.1:500
Sep 11 01:58:54.577996: "greA" #1: Can't find the certificate or private key from the NSS CKA_ID
Sep 11 01:58:54.578241: "greA" #1: unable to locate my private key for RSA Signature
Sep 11 01:58:54.578410: "greA" #1: sending notification AUTHENTICATION_FAILED to 172.16.10.1:500
Sep 11 01:58:55.080969: "greA" #1: Can't find the certificate or private key from the NSS CKA_ID
Sep 11 01:58:55.081187: "greA" #1: unable to locate my private key for RSA Signature
Sep 11 01:58:55.081467: "greA" #1: sending notification AUTHENTICATION_FAILED to 172.16.10.1:500
Sep 11 01:58:56.085058: "greA" #1: Can't find the certificate or private key from the NSS CKA_ID
Sep 11 01:58:56.085305: "greA" #1: unable to locate my private key for RSA Signature
Sep 11 01:58:56.085585: "greA" #1: sending notification AUTHENTICATION_FAILED to 172.16.10.1:500
Sep 11 01:58:58.089185: "greA" #1: Can't find the certificate or private key from the NSS CKA_ID
Sep 11 01:58:58.089416: "greA" #1: unable to locate my private key for RSA Signature
Sep 11 01:58:58.089630: "greA" #1: sending notification AUTHENTICATION_FAILED to 172.16.10.1:500
Sep 11 01:58:59.080397: "greA" #2: responding to Main Mode
Sep 11 01:58:59.081413: "greA" #2: STATE_MAIN_R1: sent MR1, expecting MI2
Sep 11 01:58:59.083701: "greA" #2: STATE_MAIN_R2: sent MR2, expecting MI3
Sep 11 01:58:59.084925: "greA" #2: ignoring informational payload AUTHENTICATION_FAILED, msgid=00000000, length=12
Sep 11 01:58:59.085229: | ISAKMP Notification Payload
Sep 11 01:58:59.085382: |   00 00 00 0c  00 00 00 01  01 00 00 18
Sep 11 01:58:59.085526: "greA" #2: received and ignored informational message
Sep 11 01:58:59.586464: "greA" #2: STATE_MAIN_R2: retransmission; will wait 0.5 seconds for response
Sep 11 01:58:59.588177: "greA" #2: ignoring informational payload AUTHENTICATION_FAILED, msgid=00000000, length=12
Sep 11 01:58:59.588403: | ISAKMP Notification Payload
Sep 11 01:58:59.588530: |   00 00 00 0c  00 00 00 01  01 00 00 18
Sep 11 01:58:59.588654: "greA" #2: received and ignored informational message
Sep 11 01:59:00.089827: "greA" #2: STATE_MAIN_R2: retransmission; will wait 1 seconds for response
Sep 11 01:59:00.091523: "greA" #2: ignoring informational payload AUTHENTICATION_FAILED, msgid=00000000, length=12
Sep 11 01:59:00.091732: | ISAKMP Notification Payload
Sep 11 01:59:00.091873: |   00 00 00 0c  00 00 00 01  01 00 00 18
Sep 11 01:59:00.092009: "greA" #2: received and ignored informational message
Sep 11 01:59:01.089869: "greA" #2: STATE_MAIN_R2: retransmission; will wait 2 seconds for response
Sep 11 01:59:01.092081: "greA" #2: ignoring informational payload AUTHENTICATION_FAILED, msgid=00000000, length=12
Sep 11 01:59:01.092427: | ISAKMP Notification Payload
Sep 11 01:59:01.092642: |   00 00 00 0c  00 00 00 01  01 00 00 18
Sep 11 01:59:01.092764: "greA" #2: received and ignored informational message
Sep 11 01:59:02.090558: "greA" #1: Can't find the certificate or private key from the NSS CKA_ID
Sep 11 01:59:02.090786: "greA" #1: unable to locate my private key for RSA Signature
Sep 11 01:59:02.090986: "greA" #1: sending notification AUTHENTICATION_FAILED to 172.16.10.1:500
Sep 11 01:59:03.093047: "greA" #2: STATE_MAIN_R2: retransmission; will wait 4 seconds for response
Sep 11 01:59:03.094914: "greA" #2: ignoring informational payload AUTHENTICATION_FAILED, msgid=00000000, length=12

config：
conn greA
        ike = aes256-sha256;modp1024
        phase2=esp
        phase2alg = aes256-sha256;modp1024
        type=transport
        left=172.16.10.2
        leftrsasigkey=0sAwEAAdC+AbrAqUvOABeMjVPTx5c78HW3+TQnephqvwxukNjlcO44iDK9NgOhRyww8N1lkTc5JO6VSfJH1ptWFS03BQVaJf98Wu4ncjjYhZMHMchl/iSPiPUWZqi8HVwAMm7xm6qzntk87oauHR1qTFhrkr8KApcPpc/LqPCycHJ2LHTO2mb83DjIYG9IzOa+IDG1NCtXCzeY8viej1J/V
BqBC7+nzzJRRhuT1sfhrGGx0eo8ZXWICqAHtYW7CBirdqyQCYUerMmfRijJ+n4hT9j7FTjogNt3duVcPbtgEW1yDBV+/scgFBN6VT/10HDpj/FZ4tD000cadQbxCDklWSCYMMZqkbHDq/69yu35NyK8Z7XZf9iOcdhOkk4uSFMDZl/JJ9Q7VTUdIofY2xJote7Nu+9PMktcZmvFuI1pnARKYKGs9HYQp3shwhfphQZj0g
zoMvz7rBCFp6ScB8+Wg0mI38tldwN6ba1g28/n48oT1tiuS2fO9dISRfyqmxWFEUkTAjBidr+TvSZiyUh8CvuhGG75L8BHL50sclVca+w5DgTHcOP0rf1dfm0lCDonHVhvYEasYxyHAAFVB+A30f5jJvgy8tm1mhFc3F5ZOqoiWAxnDdUPaxuxPsU3wASdNh8=
        right=172.16.10.1
        rightrsasigkey=0sAwEAAcmSjtRrU6eD3ceHyTs9Y5iLWmMar+lXbQ87OatE3HZXIIV0W7Dm0xq7YPvb+2QQSpnRMgMdH8iSfOjSI58uv0yEnE+Mw4jp/nQrscRR91GYEkcSXNIBJriCNu7d8LFUpAYrgMwvp6yJPIHqc0e5LBiW8pEb5HvMbZOmh7n6z8Iql6Xqce65gDTC6Ku40LCf1da+fGSKOiWe8cY4
y4oVmzsLHw7VhLTH4HRCp5B1zm4+cBz27jEqkSNrWZVy/OtlglOifxfzMIYEEie/Zq0hRrYBz6k88fflVKP76YwoG3viAlHgDc30BjT+xJGSEzztPvNwOr/bUQH+FTSDXi8m+g3papBfsEc/ykgARev0HbCbY1fwA/aLXeF2S/X9oSErdykbj9hINkoxnZovi9e6KeGTinerWcyPN653yFWVWhGkpqs1/3tp/D2AEMTAn
StDc2RfxJI2LC3FOJBxq9nZxNYaw/CWMqT8MtFgBf2QWen8neg6NiXV7zTcmU15U5BQl2/SQGtrCJmc3k9+IHKpP7GuL5upH5BoZwE+eDFSp3Z2wBR6JrX9/evPHsTgKA4SeKvKdzq8J8mcezk/7P3YOnLFAeyhFACscuDvv8jYCIXUXaOHe1+mUbi1CNwrjMnIwRBSsG4W5TNhPK9fwKMILxa9Gtsezi5oCEScB1M=
        leftprotoport=gre
        rightprotoport=gre
        authby=rsasig 
        auto=start

step：
① rm -rf /etc/ipsec.d/*db;
② ipsec initnss --nssdir /etc/ipsec.d
③ ipsec newhostkey \
--nssdir /etc/ipsec.d \
--seeddev /dev/urandom \
--output /etc/ipsec.d/GWA.secrets \
--verbose;
④ ipsec showhostkey --ckaid xxxxx --nssdir /etc/ipsec.d --left
⑤ ipsec showhostkey --ckaid xxxxx --nssdir /etc/ipsec.d --right
⑥ ipsec start
⑦ ipsec auto --up greA

libreswan version 3.23  Ubuntu18.04 
it cant work on my GRE tunnel，I dont know how to slove it，please help！

**Comment by letoams** [comment]
On Tue, 10 Sep 2019, ZTzha wrote:

> Sep 11 01:58:54.077402: "greA" #1: initiating Main Mode
> Sep 11 01:58:54.079096: "greA" #1: STATE_MAIN_I2: sent MI2, expecting MR2
> Sep 11 01:58:54.082359: "greA" #1: Can't find the certificate or private key from the NSS CKA_ID

Your private key cannot be found.

> config：
> conn greA
> ike = aes256-sha256;modp1024
> phase2=esp
> phase2alg = aes256-sha256;modp1024
> type=transport
> left=172.16.10.2
> leftrsasigkey=0sAwEAAdC+AbrAqUvOABeMjVPTx5c78HW3+TQnephqvwxukNjlcO44iDK9NgOhRyww8N1lkTc5JO6VSfJH1ptWFS03BQVaJf98Wu4ncjjYhZMHMchl/iS
> PiPUWZqi8HVwAMm7xm6qzntk87oauHR1qTFhrkr8KApcPpc/LqPCycHJ2LHTO2mb83DjIYG9IzOa+IDG1NCtXCzeY8viej1J/V
> BqBC7+nzzJRRhuT1sfhrGGx0eo8ZXWICqAHtYW7CBirdqyQCYUerMmfRijJ+n4hT9j7FTjogNt3duVcPbtgEW1yDBV+/scgFBN6VT/10HDpj/FZ4tD000cadQbxCDklWSCY
> MMZqkbHDq/69yu35NyK8Z7XZf9iOcdhOkk4uSFMDZl/JJ9Q7VTUdIofY2xJote7Nu+9PMktcZmvFuI1pnARKYKGs9HYQp3shwhfphQZj0g
> zoMvz7rBCFp6ScB8+Wg0mI38tldwN6ba1g28/n48oT1tiuS2fO9dISRfyqmxWFEUkTAjBidr+TvSZiyUh8CvuhGG75L8BHL50sclVca+w5DgTHcOP0rf1dfm0lCDonHVhvY
> EasYxyHAAFVB+A30f5jJvgy8tm1mhFc3F5ZOqoiWAxnDdUPaxuxPsU3wASdNh8=
> right=172.16.10.1
> rightrsasigkey=0sAwEAAcmSjtRrU6eD3ceHyTs9Y5iLWmMar+lXbQ87OatE3HZXIIV0W7Dm0xq7YPvb+2QQSpnRMgMdH8iSfOjSI58uv0yEnE+Mw4jp/nQrscRR91GYEk
> cSXNIBJriCNu7d8LFUpAYrgMwvp6yJPIHqc0e5LBiW8pEb5HvMbZOmh7n6z8Iql6Xqce65gDTC6Ku40LCf1da+fGSKOiWe8cY4
> y4oVmzsLHw7VhLTH4HRCp5B1zm4+cBz27jEqkSNrWZVy/OtlglOifxfzMIYEEie/Zq0hRrYBz6k88fflVKP76YwoG3viAlHgDc30BjT+xJGSEzztPvNwOr/bUQH+FTSDXi8
> m+g3papBfsEc/ykgARev0HbCbY1fwA/aLXeF2S/X9oSErdykbj9hINkoxnZovi9e6KeGTinerWcyPN653yFWVWhGkpqs1/3tp/D2AEMTAn
> StDc2RfxJI2LC3FOJBxq9nZxNYaw/CWMqT8MtFgBf2QWen8neg6NiXV7zTcmU15U5BQl2/SQGtrCJmc3k9+IHKpP7GuL5upH5BoZwE+eDFSp3Z2wBR6JrX9/evPHsTgKA4S
> eKvKdzq8J8mcezk/7P3YOnLFAeyhFACscuDvv8jYCIXUXaOHe1+mUbi1CNwrjMnIwRBSsG4W5TNhPK9fwKMILxa9Gtsezi5oCEScB1M=

Do you have a secrets file with the right entries ?

> ① rm -rf /etc/ipsec.d/*db;
> ② ipsec initnss --nssdir /etc/ipsec.d
> ③ ipsec newhostkey
> --nssdir /etc/ipsec.d
> --seeddev /dev/urandom
> --output /etc/ipsec.d/GWA.secrets
> --verbose;
> ④ ipsec showhostkey --ckaid xxxxx --nssdir /etc/ipsec.d --left
> ⑤ ipsec showhostkey --ckaid xxxxx --nssdir /etc/ipsec.d --right
> ⑥ ipsec start
> ⑦ ipsec auto --up greA

That should work.

> libreswan version 3.23 Ubuntu18.04

Oh on debian/ubuntu you need to use /var/lib/ipsec/nss and not /etc/ipsec.d

Paul

**Comment by letoams** [comment]
On Wed, 11 Sep 2019, ZTzha wrote:

> the same config in centos7 is work ， but ubuntu18.04 does not work

Because centos uses /etc/ipsec.d for the nssdb directory and
debian/ubuntu uses /var/lib/ipsec/nss

For RHEL9/CentOS 9 we will also move it to /var/lib/ipsec/nss

Paul

**Comment by ZTzha** [comment]
@letoams thanks a lot！it is work now
