### ISSUE TITLE
V3.29: mismatch between CHANGES and implementation

### ISSUE THREAD

**Issue by mzhan0170** [libreswan/libreswan#276]
Version, 3.29;
Just confirm with team, which one should we rely on. Thanks a lot.

- From CHANGE file, I saw the statement (v3.28): 
           "* IKEv2: ikev2= keyword changed to only accept "yes" or "no" [Paul]"

- But, from the file /lib/libipsecconf/keywords.c, it still support "insist".

     { "ikev2",  kv_conn | kv_processed,  kt_enum,  KNCF_IKEv2,  &kw_fourvalued_list, NULL, },

      static const struct keyword_enum_value kw_fourvalued_values[] = {
	   { "never",     fo_never  },
	   { "permit",    fo_permit },
	   { "propose",   fo_propose },
	   { "insist",    fo_insist },
	   { "yes",       fo_propose },
	   { "always",    fo_insist },
	   { "no",        fo_never  }

       static const struct keyword_enum_values kw_fourvalued_list =   
                                                 VALUES_INITIALIZER(kw_fourvalued_values);

Thanks,
Mark

**Comment by letoams** [comment]
The old values are there for backwards compatibility, so on purpose not documented.

A little complication is that for RHEL, they decided to keep insist and no/never, but not allow permit or yes :(

Paul

**Comment by mzhan0170** [comment]
Paul,
Thanks a lot for your clarification. 
I understood.
You can close the issue.

Thanks,
Mark
