### ISSUE TITLE
Undeclared symbolic const while executing "make programs".

### ISSUE THREAD

**Issue by refrog2000** [libreswan/libreswan#279]
I am installing your software and this error forced me to stop building your program. The core error message reported by gcc is:
/root/libreswan-3.28/lib/libswan/ike_alg_dh.c:323:13: error: ‘SEC_OID_CURVE25519’ undeclared here (not in a function)
  .nss_oid = SEC_OID_CURVE25519,
Since I have installed all required software listed on your list, the problem cannot be a problem of dependency.
By the way, your software seemed not listed in the repository of software of Debian.
I am looking forward to see this problem to be solved.
Thank you.

**Comment by bleve** [comment]
That is a dependency issue, you have too old a version of nss crypto library.

make USE_DH31=false prorams

But you propably need to disabl other new options too.
