### ISSUE TITLE
hw offload and bonding

### ISSUE THREAD

**Issue by AnatoliChe** [libreswan/libreswan#285]
Hi!
I have next case:
Xeon(R) E-2186G CPU @ 3.80GHz
NIC XL710 for 40GbE QSFP+ (DA2)
ethtool -k eth5 | grep esp
tx-esp-segmentation: off [fixed]
esp-hw-offload: off [fixed]
esp-tx-csum-hw-offload: off [fixed]

Without encryption it's 40Gbps.
With aes128-null 10Gbps
With aes128-sha1 5Gbps

but as only I make bonding I got 
Without encryption it's 40Gbps.
and With aes128-null 3Gbps

Could anybody explain why I lose performance?

**Comment by letoams** [comment]
We are working with the Linux kernel people on improving this. The core problem is that one IPsec SA is limited to one CPU/network receive queue.
By the way, you should get better performance using aes_gcm than when using a CBC + INTEG algorithm, even if the INTEG algorithm is null.

**Comment by AnatoliChe** [comment]
Ok thank you.
But I what about bonding?
Is it possible to use hw offload with bonding on the cards which support hw offload?
Or if I have bonding I cannot have hw offload?

without bonding 10Gbps 
with bonding 3Gbps

Or I do not understand root of the problem?

**Comment by bleve** [comment]
It has also been reported that HW offload can cause bad performance with some hardware. Plase try to disable hw offload.
