### ISSUE TITLE
CREATE_CHILD_SA child rekey message may contain CP but is not accepted

### ISSUE THREAD

**Issue by letoams** [libreswan/libreswan#293]
See RFC 7296 Appendix C.4: https://tools.ietf.org/html/rfc7296#appendix-C.4

request             --> [N(REKEY_SA),]
                           [CP(CFG_REQUEST),]
                           [N(IPCOMP_SUPPORTED)+,]
                           [N(USE_TRANSPORT_MODE),]
                           [N(ESP_TFC_PADDING_NOT_SUPPORTED),]
                           [N(NON_FIRST_FRAGMENTS_ALSO),]
                           SA, Ni, [KEi,] TSi, TSr,
                           [V+][N+]

libreswan refuses the CP payload

**Comment by letoams** [comment]
fixed in commit https://github.com/libreswan/libreswan/commit/cd993436a1c8ba51bf5078c7ae21fdd8626e526b

will be in the 3.30 release

**Comment by mithos99** [comment]
Thank you.
