### ISSUE TITLE
Can't setup opportunistic group among hosts on same network

### ISSUE THREAD

**Issue by ism93** [libreswan/libreswan#295]
Hello team, 
I want to do a tunnel vpn to do opportunistic communication between hosts (debian 10)in the same vlan. 
My configuration files are: 
/etc/ipsec.conf

config setup
        protostack=netkey
        dumpdir=/var/run/pluto/
        virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:25.0.0.0/8,%v4:100.64.0.0/10,%v6:fd00::/8,%v6:fe80::/10
include /etc/ipsec.d/*.conf

My connection file is: 
root@XXX:/etc/ipsec.d# less /etc/ipsec.d/private_ipsec.conf 
conn private
        type=tunnel
        left=%defaultroute
        leftid=%fromcert
        leftcert=usercer2
        right=%opportunisticgroup
        rightid=%fromcert
        rightca=%same
        ikev2=insist
        authby=rsasig
        failureshunt=drop
        negotiationshunt=hold
        dpdaction=restart
        auto=ondemand
        dpddelay=1
        dpdtimeout=3

conn clear
        left=%defaultroute
        right=%group
        type=passthrough
        auto=route

my /etc/ipsec.d/policies/private file is: 
10.0.0.0/8

After restarting ipsec, the service failed: 
ipsec auto --up private
029 "private": cannot initiate connection without knowing peer IP address (kind=CK_GROUP)
036 failed to initiate private

For information, this certificate work and it's in NSS DB: 
 root@XXX:/etc/ipsec.d# ipsec look
rmm-p2100293pl Fri Nov 29 17:11:58 CET 2019
XFRM state:
XFRM policy:
src ::/0 dst ::/0 proto ipv6-icmp type 135
	dir fwd priority 1
src ::/0 dst ::/0 proto ipv6-icmp type 135
	dir in priority 1
src ::/0 dst ::/0 proto ipv6-icmp type 135
	dir out priority 1
src ::/0 dst ::/0 proto ipv6-icmp type 136
	dir fwd priority 1
src ::/0 dst ::/0 proto ipv6-icmp type 136
	dir in priority 1
src ::/0 dst ::/0 proto ipv6-icmp type 136
	dir out priority 1
XFRM done
IPSEC mangle TABLES
NEW_IPSEC_CONN mangle TABLES
ROUTING TABLES
default via 10.66.176.1 dev eth1 proto dhcp metric 100
10.66.176.0/23 dev eth1 proto kernel scope link src 10.66.176.73 metric 100
::1 dev lo proto kernel metric 256 pref medium
fe80::/64 dev eth1 proto kernel metric 100 pref medium
NSS_CERTIFICATES

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

cacert1                                                      Cu,Cu,Cu
usercert2                                                    u,u,u

Have you some ideas?

**Comment by letoams** [comment]
You cannot —up those connections. Use ping to trigger them.

**Comment by bleve** [comment]
Also dpddelay=1 and dpdtimeout=3 are insane settings. Use at least 60 seconds for dpdtimeout and at least 15 secodns for dpddelay.

**Comment by ism93** [comment]
hi @bleve, i did the modification but no changes
hi @letoams 
Why we can't up the connections? 
when I restart ipsec, i ping the other machine with the same configuration but no ESP packets between the two machines.
