### ISSUE TITLE
libreswan can communicate with racoon(ikev1)? 

### ISSUE THREAD

**Issue by ism93** [libreswan/libreswan#296]
Hello Libreswan Team, 
I hope to use ipsec connection with  opportunistic mode, with racoon(which is only on ikev1) on ubuntu and on other side I have debian buster with libreswan. 
It's possible to configure libreswan in ikev1 mode? 
I try this in my libreswan configuration, but it's not working: 
        ikev2=never 
        ike=aes128-sha256-modp3072
        keyexchange=ike
        esp=aes128-sha1
        ike=aes128-sha1;modp1024
        pfs=no

Have you some ideas? 
Thank you so much

**Comment by letoams** [comment]
Sorry, Opportunistic Mode is not and will not be supported with IKEv1.

But racoon is anyway not really maintained for over 10 years or so, so anything using racoon has a number of IKEv1 issues to deal with as well possible unfixed security vulnerabilities. Please replace racoon with something that is still maintained.
