### ISSUE TITLE
Connection Error between Libswan and CISCO ASA

### ISSUE THREAD

**Issue by abobakrahmed** [libreswan/libreswan#301]
Hello Everybody,
any support for this error 

000 #1: "hello":4500 STATE_MAIN_I3 (sent MI3, expecting MR3); EVENT_v1_RETRANSMIT in 15s; nodpd; idle; import:admin initiate
000 #1: pending Phase 2 for "hello"

**Comment by abobakrahmed** [comment]
any support please

**Comment by letoams** [comment]
libreswan is retransmitting. check the cisco logs for errors why it is not receiving or liking the received packet
