### ISSUE TITLE
Telnet not working 

### ISSUE THREAD

**Issue by abobakrahmed** [libreswan/libreswan#302]
Hello All,

Telnet not working , how solve it ?

**Comment by bleve** [comment]
How is this related to Libreswan?

**Comment by abobakrahmed** [comment]
if tyoing there parameters related with leftroute or rightroute

**Comment by bleve** [comment]
There are no parameters leftroute or rightroute.

**Comment by abobakrahmed** [comment]
until now try tcpdump -i eth0 icmp but cannot seen any packets , sorry if bother you but very important

**Comment by bleve** [comment]
You must provide at least some info about your problem for us to be able to help. Read your problem description again: There is absolute no information at all.

**Comment by abobakrahmed** [comment]
ok now have problem i think not related with libreswan 
cannot ping on my machine & try stop ipsec but still exist & try do changes in /etc/ipsec.d/ddddd.conf

that's my conf 


conn home
      type=tunnel
      authby=secret
      auto=start
      dpddelay=20
      dpdtimeout=40
      dpdaction=restart
      rekey=yes
      keyingtries=%forever
      #My-HostSide#
      left=%defaultroute
      leftid=my_public_ip
      leftsourceip=my_private_ip
      leftsubnet=#mysubnet
      #Remote-HostSide#
      right=#remote_Public_ip
      rightsubnet=#remote_private_ip
      #rightnexthop=%defaultroute
      #Phase1#
      keyexchange=ike
      ike=aes256-sha1;modp1024
      ikelifetime=28800s
      #Phase2#
      ikev2=no
      esp=aes256-sha1
      pfs=no
      compress=no
      keylife=28800s
      vti-interface=eth0
      vti-routing=yes

**Comment by letoams** [comment]
Modp1024 is rejected as too weak by modern libreswans.

Paul
