### ISSUE TITLE
Libreswan will transmission

### ISSUE THREAD

**Issue by abobakrahmed** [libreswan/libreswan#304]
Hello guys,
I had to change my public IP and change my configuration with new ip but now tunnel not up showing will transmission wait 4 seconds

**Comment by letoams** [comment]
did you reload and restart the connection  or restart libreswan so the connection picks up the new IP ?

**Comment by abobakrahmed** [comment]
Sure by using ipsec restart

**Comment by letoams** [comment]
then it is not a libreswan issue

**Comment by abobakrahmed** [comment]
Your opinion what's the problem?
