### ISSUE TITLE
Enabling KLIPS with SAref patch on Ubuntu 14.04

### ISSUE THREAD

**Issue by kdmarich** [libreswan/libreswan#31]
Title.
I am trying to set up a VPN server behind a NAT and have clients connect to it. Clients with public IP's can connect just fine, however, when multiple clients behind a NAT attempt to connect they are unable to. I've applied the fixes to windows and verified that this isnt a problem native to windows, though windows gives me a 789 error. I've done research on the topic concerning NAT'd clients and connection issues and the idea i got was to install libreswan and enable KLIPS with the SAref patch. I can give more details upon request such as the log files and error messages.

**Comment by letoams** [comment]
You can try SAref but we are no longer active supporting it.'instead, the reqid with iptables connection tracking with netkey/xfrm should be used. This needs a little bit of development to complete

**Comment by letoams** [comment]
Please use NETKEY with MARKing (see mark= keywords in ipsec.conf man page) and optionally use VTI to get ipsecX interfacaes.
