### ISSUE TITLE
Null ESP

### ISSUE THREAD

**Issue by TestFryS** [libreswan/libreswan#312]
What is the proper edit in my ipsec.conf file to turn on null ESP for testing?

I've tried esp=null with no luck.

**Comment by letoams** [comment]
On Fri, 6 Mar 2020, TestFryS wrote:

> 
> What is the proper edit in my ipsec.conf file to turn on null ESP for testing?
> 
> I've tried esp=null with no luck.

We have a few test cases for this you can look at the configs for,
depending what you really mean. esp=null isn't a complete specification,
as you need to specify encryption+integrity and if encryption is null,
then you MUST have an integrity function, eg esp=null-sha1. That likely
covers what you need if this is trying to do the same as AH but using
ESP.

If for some test/benchmark non-real life use case you want null
authentication as well as null encryption - which means your VPN is
not a secure VPN anymore and just as insecure as plaintext - you can
use esp=null-none but you also need to impair pluto to allow this
bogus/invalid setup. See:
https://github.com/libreswan/libreswan/tree/master/testing/pluto/ikev2-algo-15-esp-null-none

Note that esp=null-none should not be used for actual real VPNs, only
for benchmarking or testing.

Paul
