### ISSUE TITLE
unable to reach to host after libreswan connected - 

### ISSUE THREAD

**Issue by jainmnsh** [libreswan/libreswan#315]
Hello,

I built the IPSec tunnel between AWS to Oracle cloud using libreswan using below IPSec.conf and secret file. I can see my status as below but i try to ping /telnet/ traceroute to ip address in oracle cloud then its not reachable. I appreciate your help. I verified that the host is active and running.

Here is the error when i do trace route and as you can its not reachable.

root@ip-10-147-227-24:/etc# traceroute 132.240.224.165
traceroute to 132.240.224.165 (132.240.224.165), 30 hops max, 60 byte packets
 1  ip-10-147-227-24.ec2.internal (10.147.227.24)  3048.370 ms !H  3048.344 ms !H  3048.325 ms !H
root@ip-10-147-227-24:/etc# 

Here is my route information :
root@ip-10-147-227-24:/etc# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.147.227.1    0.0.0.0         UG    100    0        0 eth0
10.147.227.0    0.0.0.0         255.255.255.192 U     0      0        0 eth0
10.147.227.1    0.0.0.0         255.255.255.255 UH    100    0        0 eth0
132.240.224.0   0.0.0.0         255.255.254.0   U     0      0        0 eth0

root@ip-10-147-227-24:/etc# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  132.240.224.0/23     ip-10-147-227-0.ec2.internal/26  policy match dir in pol ipsec reqid 1 proto esp
ACCEPT     all  --  ip-10-147-227-0.ec2.internal/26  132.240.224.0/23     policy match dir out pol ipsec reqid 1 proto esp

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

IPSec status
000 State Information: DDoS cookies not required, Accepting new IKE connections
000 IKE SAs: total(2), half-open(0), open(1), authenticated(1), anonymous(0)
000 IPsec SAs: total(1), authenticated(1), anonymous(0)
000  
000 #1891: "oracle-tunnel-1":500 STATE_MAIN_I4 (ISAKMP SA established); EVENT_SA_REPLACE in 20400s; newest ISAKMP; lastdpd=2s(seq in:0 out:0); idle;
000 #2037: "oracle-tunnel-1":500 STATE_QUICK_I2 (sent QI2, IPsec SA established); EVENT_SA_REPLACE in 1472s; newest IPSEC; eroute owner; isakmp#1891; idle;
000 #2037: "oracle-tunnel-1" esp.db07583e@129.213.6.35 esp.ad42fde9@10.147.227.24 tun.0@129.213.6.35 tun.0@10.147.227.24 ref=0 refhim=0 Traffic: ESPin=0B ESPout=0B! ESPmax=4194303B 
000 #2065: "oracle-tunnel-2":4500 STATE_MAIN_I3 (sent MI3, expecting MR3); EVENT_RETRANSMIT in 7s; lastdpd=-1s(seq in:0 out:0); idle;
000 #2065: pending Phase 2 for "oracle-tunnel-2"
000 

IPSec.conf
conn oracle-tunnel-1
     left=10.147.227.24
     leftid=xxxx
     right=xxxx
     authby=secret
     leftsubnet=0.0.0.0/0
     rightsubnet=0.0.0.0/0
     auto=start
     mark=5/0xffffffff # Needs to be unique across all tunnels
     #vti-interface=ip_vti0
     #vti-routing=no
     ikev2=no # To use IKEv2, change to ikev2=insist 
     ike=aes_cbc256-sha2_384;modp1536
     phase2alg=aes_gcm256;modp1536
     encapsulation=no # See preceding note about NAT-T support
     ikelifetime=28800s
     salifetime=3600s

conn oracle-tunnel-2
     left=xxxx
     # leftid=18.211.62.236
     right=xxxx
     authby=secret
     leftsubnet=0.0.0.0/0
     rightsubnet=0.0.0.0/0
     auto=start
     mark=6/0xffffffff # Needs to be unique across all tunnels
     #vti-interface=ip_vti1
     #vti-routing=no
     ikev2=no # To use IKEv2, change to ikev2=insist
     ike=aes_cbc256-sha2_384;modp1536
     phase2alg=aes_gcm256;modp1536
     encapsulation=yes # See preceding note about NAT-T support
     ikelifetime=28800s
     salifetime=120s

**Comment by letoams** [comment]
On Wed, 18 Mar 2020, Manish Jain wrote:

> I built the IPSec tunnel between AWS to Oracle cloud using libreswan using below IPSec.conf and secret file. I can see my status as below but i try to ping
> /telnet/ traceroute to ip address in oracle cloud then its not reachable. I appreciate your help. I verified that the host is active and running.
> 
> Here is the error when i do trace route and as you can its not reachable.
> 
> root@ip-10-147-227-24:/etc# traceroute 132.240.224.165
> traceroute to 132.240.224.165 (132.240.224.165), 30 hops max, 60 byte packets
> 1 ip-10-147-227-24.ec2.internal (10.147.227.24) 3048.370 ms !H 3048.344 ms !H 3048.325 ms !H
> root@ip-10-147-227-24:/etc#

do not use traceroute, it does not work well for IPsec because hops in
between cannot send you data.

> 000 #1891: "oracle-tunnel-1":500 STATE_MAIN_I4 (ISAKMP SA established); EVENT_SA_REPLACE in 20400s; newest ISAKMP; lastdpd=2s(seq in:0 out:0); idle;
> 000 #2037: "oracle-tunnel-1":500 STATE_QUICK_I2 (sent QI2, IPsec SA established); EVENT_SA_REPLACE in 1472s; newest IPSEC; eroute owner; isakmp#1891; idle;
> 000 #2037: "oracle-tunnel-1" esp.db07583e@129.213.6.35 esp.ad42fde9@10.147.227.24 tun.0@129.213.6.35 tun.0@10.147.227.24 ref=0 refhim=0 Traffic: ESPin=0B
> ESPout=0B! ESPmax=4194303B
> 000 #2065: "oracle-tunnel-2":4500 STATE_MAIN_I3 (sent MI3, expecting MR3); EVENT_RETRANSMIT in 7s; lastdpd=-1s(seq in:0 out:0); idle;
> 000 #2065: pending Phase 2 for "oracle-tunnel-2"

So you have an IKEv1 tunnel up.

> IPSec.conf
> conn oracle-tunnel-1
> left=10.147.227.24
> leftid=xxxx
> right=xxxx
> authby=secret
> leftsubnet=0.0.0.0/0
> rightsubnet=0.0.0.0/0
> auto=start
> mark=5/0xffffffff # Needs to be unique across all tunnels
> #vti-interface=ip_vti0
> #vti-routing=no


You do need the last two options but dont use ip_vti0 because that is
the interface that is created when loading the module. Use something
like "vti1". You must set vti-routing=no because it is a tunnel from
0/0 to 0/0. It requires you manually (or via bgp etc) set routes.

> left=xxxx
> # leftid=18.211.62.236
> right=xxxx
> authby=secret
> leftsubnet=0.0.0.0/0
> rightsubnet=0.0.0.0/0
> auto=start
> mark=6/0xffffffff # Needs to be unique across all tunnels
> #vti-interface=ip_vti1
> #vti-routing=no

same here.

Check with ipsec trafficstatus for traffic counters. Check
/proc/net/xfrm_stat to see if you are accidentally dropping
packets.

Check rp_filter and forwarding settings, and iptables rules
(both with and without -t nat)

Paul

**Comment by letoams** [comment]
please let us know if you still have issues

**Comment by yygyqkhh** [comment]
> 如果您仍然有问题，请告诉我们

Hello, how to connect multiple clients with multiple certificates? I applied for two certificates with different names and I couldn't connect to the server at the same time.

certutil -z <(head -c 1024 /dev/urandom) \
  -S -c "IKEv2 VPN CA" -n "vpnclient" \
  -s "O=IKEv2 VPN,CN=vpnclient" \
  -k rsa -g 4096 -v 120 \
  -d sql:/etc/ipsec.d -t ",," \
  --keyUsage digitalSignature,keyEncipherment \
  --extKeyUsage serverAuth,clientAuth -8 "vpnclient"

certutil -z <(head -c 1024 /dev/urandom) \
  -S -c "IKEv2 VPN CA" -n "vpnclient2" \
  -s "O=IKEv2 VPN,CN=vpnclient2" \
  -k rsa -g 4096 -v 120 \
  -d sql:/etc/ipsec.d -t ",," \
  --keyUsage digitalSignature,keyEncipherment \
  --extKeyUsage serverAuth,clientAuth -8 "vpnclient2"
