### ISSUE TITLE
Libreswan with Cisco CSR1000v in IKEv2 - Issue when using asymmetric PSK

### ISSUE THREAD

**Issue by gtg625n** [libreswan/libreswan#316]
Good afternoon, 

I would like to submit to you the following issue. 

Description of the Context: 
Network diagram: 
VM Yocto with Libreswan -----OFFICE SWITCH ---- CSR1000v Cisco 

Version: Linux Libreswan 3.27 (netkey) on 4.19.99-yocto-standard

The error message is: 
Mar 19 12:56:03.545592: "IPsec_TUN_1" #5: IKEv2 mode peer ID is ID_IPV4_ADDR: '10.10.10.14'
Mar 19 12:56:03.546371: "IPsec_TUN_1" #5: Authenticated using authby=secret
Mar 19 12:56:03.547047: "IPsec_TUN_1" #5: responding to AUTH message (ID 1) from 10.10.10.14:500 with encrypted notification **TS_UNACCEPTABLE**
Mar 19 12:56:03.551082: "IPsec_TUN_1" #5: responding to AUTH message (ID 1) from 10.10.10.14:500 with encrypted notification INVALID_IKE_SPI
[...] 
Mar 19 12:56:31.714062: "IPsec_TUN_1" #5: responding to AUTH message (ID 1) from 10.10.10.14:500 with encrypted notification INVALID_IKE_SPI
Mar 19 12:57:00.388429: "IPsec_TUN_1" #4: deleting other state #4 (STATE_PARENT_I2) and NOT sending notification
Mar 19 12:57:00.388546: "IPsec_TUN_1" #3: deleting state (STATE_PARENT_I2) and NOT sending notification
Mar 19 12:57:01.259121: "IPsec_TUN_1" #5: responding to AUTH message (ID 1) from 10.10.10.14:500 with encrypted notification INVALID_IKE_SPI

The IPsec tunnel is UP and running when I modify both configurations (Libreswan and Cisco) so that they use SYMETRIC PSK instead.

I have played around the various permutations in the *.secrets file but with the same result: the Cisco would not authenticate the message from the Yocto machine, during the IKEv2 phase. 

The configurations Libreswan (*.conf and *.secrets)  and CSR1k are attached. 
[Config Libreswan Bold (conf and secrets) - 1803 7-30pm.txt](https://github.com/libreswan/libreswan/files/4354662/Config.Libreswan.Bold.conf.and.secrets.-.1803.7-30pm.txt)
[Config Cisco CSR-Linkt backbone - 1803 7-30pm.txt](https://github.com/libreswan/libreswan/files/4354663/Config.Cisco.CSR-Linkt.backbone.-.1803.7-30pm.txt)

Would you have any idea ? Also, please find attached the log files from the Cisco and from Libreswan, when the error occurs.
[Debug crypto Ikev2 packet -1903.txt](https://github.com/libreswan/libreswan/files/4354673/Debug.crypto.Ikev2.packet.-1903.txt)
[Pluto log -1903.txt](https://github.com/libreswan/libreswan/files/4354674/Pluto.log.-1903.txt)

Thank you in advance, GFR.

**Comment by gtg625n** [comment]
I would like to close this issue. Please disregard. Apparently, it is not currently supported.

**Comment by sebspion** [comment]
ehtcg
