### ISSUE TITLE
How to get active connections list with username?

### ISSUE THREAD

**Issue by hassaan-dev** [libreswan/libreswan#320]
Hi,

Is it possible to get list of active connections along with user name via any terminal command or way?

**Comment by sebspion** [comment]
@hassaan-dev 

_Envoyé depuis mon Galaxy A8(2018) en utilisant [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sebspion** [comment]
~~~~

**Comment by letoams** [comment]
ipsec trafficstatus can be used for connections using XAUTH usernames and/or X509 certificate identities.
If L2TP/IPsec is used, you have to look at pppd options to query things.
