### ISSUE TITLE
Site to Site interconnect devices 

### ISSUE THREAD

**Issue by PedroPCardoso** [libreswan/libreswan#327]
I would like to create a site to site connection my settings are:

THE:
conn mytunnel2
    ike = aes256-sha256; modp1536
    phase2alg = aes256-sha256; modp1536
    left =% defaultroute
    leftid = 172.107.45.245
    leftsubnet = 192.168.44.0 / 24
    right = 172.107.46.211
    rightsubnet = 192.168.42.0 / 24
    authby = secret
    # use auto = start when done testing the tunnel
    auto = start

B:
conn mytunnel2
    ike = aes256-sha256; modp1536
    phase2alg = aes256-sha256; modp1536
    left =% defaultroute
    leftid = 172.107.46.211
    leftsubnet = 192.168.42.0 / 24
    right = 172.107.45.245
    rightsubnet = 192.168.44.0 / 24
    authby = secret
    # use auto = start when done testing the tunnel
    auto = start

Secrets A

172.107.46.211 172.107.45.245: PSK "*****"

% any% any: PSK "*****"

Secrets B
172.107.45.245 172.107.46.211: PSK "*****"

% any% any: PSK "*****"

I connected a device to each of the servers, and the connections were created, I would like to ping / connect the device from the other server, for example:
Server A 192.168.42.1
server device A 192.168.42.10

Server B ping 192.168.42.10

another problem was that when running the script I changed the one on server B the ip range to 192.168.44. instead of 42, but when I put this configuration in ipsec.conf I can't even ping .1, when I comment:

leftsubnet = 192.168.44.0 / 24
and

rightsubnet = 192.168.44.0 / 24
I can ping 192.168.42.1, using Server B

**Comment by letoams** [comment]
I am not sure I understand what you are saying. I think you are saying the site-to-site tunnel works for devices behind the servers, but not for the servers itself ? If so, you want to add leftsourceip=192.168.42.X and rightsourceip=92.168.44.Y where these IPs are the LAN IP's configured on the respective servers' internal interface.

As for your second problem, if you make the remote subnet the same as your LAN subnet, you wont be able to reach your LAN devices without ipsec. If there is no exception for your LAN gateway, then you wont be able to reach the gateway and so everything goes down. Don't do that :)

**Comment by PedroPCardoso** [comment]
No, on the contrary, I can ping the .1 that would be the server, but not the devices connected to it.

I don't know how to connect a server A device from server B or a device connected to B

**Comment by PedroPCardoso** [comment]
`
root@cloud:~# ifconfig
ens18: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.107.45.245  netmask 255.255.255.192  broadcast 172.107.45.255
        inet6 2604:6600:2000:3a:250:56ff:fe2a:a6a5  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::250:56ff:fe2a:a6a5  prefixlen 64  scopeid 0x20<link>
        ether 00:50:56:2a:a6:a5  txqueuelen 1000  (Ethernet)
        RX packets 1254019  bytes 467798362 (467.7 MB)
        RX errors 0  dropped 65033  overruns 0  frame 0
        TX packets 521947  bytes 334631327 (334.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens19: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::250:56ff:fea7:e503  prefixlen 64  scopeid 0x20<link>
        ether 00:50:56:a7:e5:03  txqueuelen 1000  (Ethernet)
        RX packets 40  bytes 2572 (2.5 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 72  bytes 11936 (11.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=195<UP,BROADCAST,RUNNING,NOARP>  mtu 1500
        inet 192.168.42.1  netmask 255.255.255.0  broadcast 192.168.42.255
        inet6 fe80::d8b6:11ff:fe3f:1dea  prefixlen 64  scopeid 0x20<link>
        ether da:b6:11:3f:1d:ea  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2  bytes 140 (140.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ppp0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1280
        inet 192.168.44.1  netmask 255.255.255.255  destination 192.168.44.10
        ppp  txqueuelen 3  (Protocolo Ponto-a-Ponto)
        RX packets 194  bytes 39971 (39.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 160  bytes 52727 (52.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

`
I created eth0 with ip .1 and also for another network at 192.168.42.1

But I can't reach the network.

Inside B I can reach 192.168.44.10, but on server A I cannot reach devices in B.


I even added the source ip but I still can't reach it.

`
# /etc/ipsec.conf
conn mytunnel3
    ike=aes256-sha256;modp1536
    phase2alg=aes256-sha256;modp1536
    left=%defaultroute
    leftid=172.107.45.245
    leftsubnet=192.168.44.0/24
    leftsourceip=192.168.44.1
    right=167.99.235.54
    rightsubnet=10.116.0.0/24
    authby=secret
    # use auto=start when done testing the tunnel
    auto=start
`
