### ISSUE TITLE
Bogus dependencies for debian

### ISSUE THREAD

**Issue by phaoost** [libreswan/libreswan#328]
Hello,

I am getting bogus dependencies for debian. It shows build depends on systemd and I use another init system (sysvinit)

These dependencies aren't needed for libreswan to run.

**Comment by bleve** [comment]
Debian defaults to systemd and we are just following debian package.

**Comment by phaoost** [comment]
Debian does not deny sysvinit and libreswan can run without systemd, this dependency is wrong. It's rather recommends then depends. Furthermore is should not be a build dependency as libreswan builds fine without systemd

**Comment by phaoost** [comment]
The quick workaround to remove bogus systemd dependency is:

`sed -i '/systemd/d' packaging/debian/control`

This dependency inserted voluntary and does not affect anything in build process

**Comment by antonyantony** [comment]
what is a clean way to add optional systemd dependency in Debian control file? 
I guess we would require changes "rules" 
%:
        dh $@ --with systemd

Just deleting is not a great option. It would break. 
such as running  "mk-build-deps --install  && make "
I would love fix it properly make systemd dependency conditional.
Downstream has a feature request for sysinit support. And Note Debian maintainer @dkg also requested for clean patch.  Patches welcome.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855653

I would also love to add  other conditional dependencies, such as  no unbound  when USE_DNSSEC=false 

@phaoost if you know any other package with control and rule files which has optional systemd dependency please point out.

**Comment by antonyantony** [comment]
> The quick workaround to remove bogus systemd dependency is:
> 
> `sed -i '/systemd/d' packaging/debian/control`
> 
> This dependency inserted voluntarily and does not affect anything in build process

there were some issues compiling without those lines
https://github.com/libreswan/libreswan/commit/36d8270131c8e28bdf26a25229d80dc36a333d48

**Comment by antonyantony** [comment]
> The quick workaround to remove bogus systemd dependency is:
> 
> `sed -i '/systemd/d' packaging/debian/control`
> 
> This dependency inserted voluntarily and does not affect anything in build process

oh here is the reason for this patch I dug it out of archives https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=875639
