### ISSUE TITLE
IKEv2 no connect after 3.29->3.31 upgrade (hwdsl2/setup-ipsec-vpn script used)

### ISSUE THREAD

**Issue by mithos99** [libreswan/libreswan#333]
Hello.
Upgraded Libreswan with hwdsl2's script from 3.29 to 3.31 and connection from Mikrotik router broke.
Tried to install back 3.29 with all same settings - works fine.
Attaching logs:
[auth.log](https://github.com/libreswan/libreswan/files/4534019/auth.log)
[client.log](https://github.com/libreswan/libreswan/files/4534020/client.log)

Mikrotik router: client.log (local time) around line
Apr/25/2020 23:55:17 ipsec unknown payload seen: 53

and Libreswan's Auth.log (server time = client-3h) around line
Apr 25 20:55:18  51: STATE_V2_IPSEC_R: IPsec SA established tunnel mode
and then right after new request from client
Apr 25 20:55:19 52: proposal 1:IKE=AES_CBC_256-HMAC_SHA2_256-HMAC_SHA2_256_128-MODP2048 chosen from remote proposals

I reported
* IKEv2: Allow CP payload in CREATE_CHILD_SA (RFC 7296 Appendix C.4) [Paul]
error and have this new problem.

Thank you.

@hwdsl2

**Comment by kamakuba** [comment]
Yep, see my report #329 
Being fixed in 3.32 version

**Comment by mithos99** [comment]
Thanx! For both #329 and logging tip.
Looking forward to 3.32

**Comment by hwdsl2** [comment]
@mithos99 @kamakuba I've manually added the fix from https://github.com/libreswan/libreswan/commit/90f8a09 to the VPN setup and upgrade scripts [1]. You can give it a try.

[1] https://github.com/hwdsl2/setup-ipsec-vpn

**Comment by mithos99** [comment]
Now it connects. Thank you!
