### ISSUE TITLE
Runtime breakage with Libreswan and nss-3.52

### ISSUE THREAD

**Issue by reubenfarrelly** [libreswan/libreswan#334]
In the last couple of days my system has updated to nss-3.52 which is newly released.  Libreswan continued to work fine until I rebuilt it yesterday, at which point it failed to start.  I am tracking libreswan -master in git.

This is only a runtime issue.  Libreswan builds fine with 3.52 but the issue is when it is started up and it crashes with an assertion failure:

May  3 14:06:20.330836: FIPS Mode: NO
May  3 14:06:20.331380: NSS DB directory: sql:/etc/ipsec.d
May  3 14:06:20.331464: Initializing NSS
May  3 14:06:20.331472: Opening NSS database "sql:/etc/ipsec.d" read-only
May  3 14:06:20.347971: NSS initialized
May  3 14:06:20.347986: NSS crypto library initialized
May  3 14:06:20.347990: FIPS mode disabled for pluto daemon
May  3 14:06:20.347994: FIPS HMAC integrity support [disabled]
May  3 14:06:20.348071: libcap-ng support [enabled]
May  3 14:06:20.348076: Linux audit support [disabled]
May  3 14:06:20.348085: Starting Pluto (Libreswan Version v3.30-617-g23bc423bc0-HEAD XFRM(netkey) XFRMI esp-hw-offload FORK PTHREAD_SETSCHEDPRIO NSS (IPsec profile) (native-PRF) SECCOMP LIBCAP_NG XAUTH_PAM NETWORKMANAGER CURL(non-NSS)) pid:3193
May  3 14:06:20.348088: core dump dir: /run/pluto
May  3 14:06:20.348092: secrets file: /etc/ipsec.secrets
May  3 14:06:20.348095: leak-detective disabled
May  3 14:06:20.348098: NSS crypto [enabled]
May  3 14:06:20.348101: XAUTH PAM support [enabled]
May  3 14:06:20.348409: Initializing libevent in pthreads mode: headers: 2.1.11-stable (2010b00); library: 2.1.11-stable (2010b00)
May  3 14:06:20.348500: NAT-Traversal support  [enabled]
May  3 14:06:20.348967: Encryption algorithms:
May  3 14:06:20.348978:   AES_CCM_16              IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  aes_ccm, aes_ccm_c
May  3 14:06:20.348983:   AES_CCM_12              IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  aes_ccm_b
May  3 14:06:20.348988:   AES_CCM_8               IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  aes_ccm_a
May  3 14:06:20.348993:   3DES_CBC                IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  [*192]  3des
May  3 14:06:20.348997:   CAMELLIA_CTR            IKEv1:     ESP     IKEv2:     ESP           {256,192,*128}
May  3 14:06:20.349002:   CAMELLIA_CBC            IKEv1: IKE ESP     IKEv2: IKE ESP           {256,192,*128}  camellia
May  3 14:06:20.349006:   AES_GCM_16              IKEv1:     ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  aes_gcm, aes_gcm_c
May  3 14:06:20.349011:   AES_GCM_12              IKEv1:     ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  aes_gcm_b
May  3 14:06:20.349015:   AES_GCM_8               IKEv1:     ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  aes_gcm_a
May  3 14:06:20.349028:   AES_CTR                 IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  aesctr
May  3 14:06:20.349032:   AES_CBC                 IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  aes
May  3 14:06:20.349036:   NULL_AUTH_AES_GMAC      IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  aes_gmac
May  3 14:06:20.349040:   NULL                    IKEv1:     ESP     IKEv2:     ESP           []
May  3 14:06:20.349044:   CHACHA20_POLY1305       IKEv1:             IKEv2: IKE ESP           [*256]  chacha20poly1305
May  3 14:06:20.349054: Hash algorithms:
May  3 14:06:20.349057:   MD5                     IKEv1: IKE         IKEv2:                 
May  3 14:06:20.349061:   SHA1                    IKEv1: IKE         IKEv2: IKE         FIPS  sha
May  3 14:06:20.349064:   SHA2_256                IKEv1: IKE         IKEv2: IKE         FIPS  sha2, sha256
May  3 14:06:20.349068:   SHA2_384                IKEv1: IKE         IKEv2: IKE         FIPS  sha384
May  3 14:06:20.349071:   SHA2_512                IKEv1: IKE         IKEv2: IKE         FIPS  sha512
May  3 14:06:20.349086: PRF algorithms:
May  3 14:06:20.349090:   HMAC_MD5                IKEv1: IKE         IKEv2: IKE               md5
May  3 14:06:20.349094:   HMAC_SHA1               IKEv1: IKE         IKEv2: IKE         FIPS  sha, sha1
May  3 14:06:20.349098:   HMAC_SHA2_256           IKEv1: IKE         IKEv2: IKE         FIPS  sha2, sha256, sha2_256
May  3 14:06:20.349101:   HMAC_SHA2_384           IKEv1: IKE         IKEv2: IKE         FIPS  sha384, sha2_384
May  3 14:06:20.349105:   HMAC_SHA2_512           IKEv1: IKE         IKEv2: IKE         FIPS  sha512, sha2_512
May  3 14:06:20.349109:   AES_XCBC                IKEv1:             IKEv2: IKE               aes128_xcbc
May  3 14:06:20.349138: Integrity algorithms:
May  3 14:06:20.349142:   HMAC_MD5_96             IKEv1: IKE ESP AH  IKEv2: IKE ESP AH        md5, hmac_md5
May  3 14:06:20.349146:   HMAC_SHA1_96            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  sha, sha1, sha1_96, hmac_sha1
May  3 14:06:20.349150:   HMAC_SHA2_512_256       IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  sha512, sha2_512, sha2_512_256, hmac_sha2_512
May  3 14:06:20.349155:   HMAC_SHA2_384_192       IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  sha384, sha2_384, sha2_384_192, hmac_sha2_384
May  3 14:06:20.349159:   HMAC_SHA2_256_128       IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  sha2, sha256, sha2_256, sha2_256_128, hmac_sha2_256
May  3 14:06:20.349163:   HMAC_SHA2_256_TRUNCBUG  IKEv1:     ESP AH  IKEv2:         AH      
May  3 14:06:20.349167:   AES_XCBC_96             IKEv1:     ESP AH  IKEv2: IKE ESP AH        aes_xcbc, aes128_xcbc, aes128_xcbc_96
May  3 14:06:20.349170:   AES_CMAC_96             IKEv1:     ESP AH  IKEv2:     ESP AH  FIPS  aes_cmac
May  3 14:06:20.349174:   NONE                    IKEv1:     ESP     IKEv2: IKE ESP     FIPS  null
May  3 14:06:20.349190: DH algorithms:
May  3 14:06:20.349194:   NONE                    IKEv1:             IKEv2: IKE ESP AH  FIPS  null, dh0
May  3 14:06:20.349197:   MODP1536                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH        dh5
May  3 14:06:20.349201:   MODP2048                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  dh14
May  3 14:06:20.349204:   MODP3072                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  dh15
May  3 14:06:20.349208:   MODP4096                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  dh16
May  3 14:06:20.349211:   MODP6144                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  dh17
May  3 14:06:20.349215:   MODP8192                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  dh18
May  3 14:06:20.349218:   DH19                    IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  ecp_256, ecp256
May  3 14:06:20.349222:   DH20                    IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  ecp_384, ecp384
May  3 14:06:20.349226:   DH21                    IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  ecp_521, ecp521
May  3 14:06:20.349229:   DH31                    IKEv1: IKE         IKEv2: IKE ESP AH        curve25519
May  3 14:06:20.349235: testing CAMELLIA_CBC:
May  3 14:06:20.349238:   Camellia: 16 bytes with 128-bit key
May  3 14:06:20.349319:   Camellia: 16 bytes with 128-bit key
May  3 14:06:20.349350:   Camellia: 16 bytes with 256-bit key
May  3 14:06:20.349381:   Camellia: 16 bytes with 256-bit key
May  3 14:06:20.349410: testing AES_GCM_16:
May  3 14:06:20.349413:   empty string
May  3 14:06:20.349441: NSS: AEAD decryption using AES_GCM_16_128 and PK11_Decrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
May  3 14:06:20.349447: NSS: AEAD encryption using AES_GCM_16_128 and PK11_Encrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
May  3 14:06:20.349452:   one block
May  3 14:06:20.349475: NSS: AEAD decryption using AES_GCM_16_128 and PK11_Decrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
May  3 14:06:20.349480: NSS: AEAD encryption using AES_GCM_16_128 and PK11_Encrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
May  3 14:06:20.349484:   two blocks
May  3 14:06:20.349507: NSS: AEAD decryption using AES_GCM_16_128 and PK11_Decrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
May  3 14:06:20.349513: NSS: AEAD encryption using AES_GCM_16_128 and PK11_Encrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
May  3 14:06:20.349517:   two blocks with associated data
May  3 14:06:20.349540: NSS: AEAD decryption using AES_GCM_16_128 and PK11_Decrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
May  3 14:06:20.349546: NSS: AEAD encryption using AES_GCM_16_128 and PK11_Encrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
May  3 14:06:20.349550: ABORT: ASSERTION FAILED: test_gcm_vectors(&ike_alg_encrypt_aes_gcm_16, aes_gcm_tests) (in test_ike_alg() at ike_alg_test.c:41)

Rebuilding against nss-3.51.1 and starting up avoids the error.

**Comment by letoams** [comment]
On Sun, 3 May 2020, Reuben Farrelly wrote:

> In the last couple of days my system has updated to nss-3.52 which is newly released. Libreswan continued to work fine until I rebuilt it
> yesterday, at which point it failed to start. I am tracking libreswan -master in git.
> 
> This is only a runtime issue. Libreswan builds fine with 3.52 but the issue is when it is started up and it crashes with an assertion
> failure:

> May 3 14:06:20.349441: NSS: AEAD decryption using AES_GCM_16_128 and PK11_Decrypt() failed (SECERR: 2 (0x2): security library: received bad
> data.)

For now please compile with USE_NSS_PRF=false

There is some confusion about code present in RHEL branches vs upstream
with the respect for some functionality.

Paul

**Comment by letoams** [comment]
On Sun, 3 May 2020, Reuben Farrelly wrote:

> In the last couple of days my system has updated to nss-3.52 which is newly released. Libreswan continued to work fine until
> I rebuilt it yesterday, at which point it failed to start. I am tracking libreswan -master in git.
> 
> This is only a runtime issue. Libreswan builds fine with 3.52 but the issue is when it is started up and it crashes with an
> assertion failure:

Note git master should work again, if you have nss 3.52, with or without USE_NSS_PRF

And with it set, you now no longer need to have libreswan FIPS certified
as all FIPS functionality is now done by NSS. We will update our FIPS
documentation over the next few weeks.

Paul

**Comment by reubenfarrelly** [comment]
Sorry Paul - still the same error on startup, even after updating nss again to 3.52 and updating to -libreswan -git master:

lightning ~ # nss-config --version
3.52.0

lightning ~ # ipsec --version
Linux Libreswan v3.30-660-ga33a77992c-HEAD (netkey) on 5.6.9-gentoo
lightning ~ #

May  7 15:35:24.101505: testing CAMELLIA_CBC:
May  7 15:35:24.101508:   Camellia: 16 bytes with 128-bit key
May  7 15:35:24.101599:   Camellia: 16 bytes with 128-bit key
May  7 15:35:24.101636:   Camellia: 16 bytes with 256-bit key
May  7 15:35:24.101670:   Camellia: 16 bytes with 256-bit key
May  7 15:35:24.101701: testing AES_GCM_16:
May  7 15:35:24.101705:   empty string
May  7 15:35:24.101735: NSS: AEAD decryption using AES_GCM_16_128 and PK11_Decrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
May  7 15:35:24.101742: NSS: AEAD encryption using AES_GCM_16_128 and PK11_Encrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
May  7 15:35:24.101747:   one block
May  7 15:35:24.101771: NSS: AEAD decryption using AES_GCM_16_128 and PK11_Decrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
May  7 15:35:24.101776: NSS: AEAD encryption using AES_GCM_16_128 and PK11_Encrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
May  7 15:35:24.101781:   two blocks
May  7 15:35:24.101806: NSS: AEAD decryption using AES_GCM_16_128 and PK11_Decrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
May  7 15:35:24.101812: NSS: AEAD encryption using AES_GCM_16_128 and PK11_Encrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
May  7 15:35:24.101816:   two blocks with associated data
May  7 15:35:24.101841: NSS: AEAD decryption using AES_GCM_16_128 and PK11_Decrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
May  7 15:35:24.101847: NSS: AEAD encryption using AES_GCM_16_128 and PK11_Encrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
May  7 15:35:24.101852: ABORT: ASSERTION FAILED: test_gcm_vectors(&ike_alg_encrypt_aes_gcm_16, aes_gcm_tests) (in test_ike_alg() at ike_alg_test.c:41)

**Comment by letoams** [comment]
On Wed, 6 May 2020, Reuben Farrelly wrote:

> Sorry Paul - still the same error on startup, even after updating nss again to 3.52 and updating to -libreswan -git master:

> lightning ~ # nss-config --version
> 3.52.0
> 
> lightning ~ # ipsec --version
> Linux Libreswan v3.30-660-ga33a77992c-HEAD (netkey) on 5.6.9-gentoo


> May 7 15:35:24.101735: NSS: AEAD decryption using AES_GCM_16_128 and PK11_Decrypt() failed (SECERR: 2 (0x2): security
> library: received bad data.)

That's weird. is this on a non-standard architecture? Is this with
USE_FIPSCHECK=false and USE_NSS_KDF=true ?

Paul

**Comment by reubenfarrelly** [comment]
This is x86_64 architecture box however it is a KVM on Linode - possibly relevant?  There's nothing odd or unusual about it at all.

USE_FIPSCHECK and USE_NSS_KDF are not defined in the build.

**Comment by mikken** [comment]
I also experience this: libreswan 3.31, running Gentoo.
After setting `USE_NSS_KDF=false` in the ebuild, it still persists.

**Comment by letoams** [comment]
Apparently, this can happen when you build against nss 3.51 but then run against 3.52

Try rebuilding libreswan when the -dev headers of 3.52 are installed?

**Comment by letoams** [comment]
Try the above patch (or just compile current git master) and let me know if that addresses your issues?

**Comment by reubenfarrelly** [comment]
Still not working as of v3.30-689-g65a497959a-HEAD.  And yes I'm upgrading nss to 3.52 prior to building Libreswan (git).  If I build with nss 3.51 installed and then subsequently upgrade to nss 3.52 things work, it's only if Libreswan is built against 3.52 that there is a problem.

**Comment by bleve** [comment]
Note: on master that is still USE_NSS_PRF=true|false, not USE_NSS_KDF, we were just talking about renaming that option. And that is disabled by default.

**Comment by letoams** [comment]
The define has to be done before any nss include. I've moved the define to a better location. Can you try again now using at least git master db7715407efa43cd2a6

**Comment by letoams** [comment]
(you should be able to set USE_NSS_KDF=true since you use ns s3.52)

**Comment by reubenfarrelly** [comment]
Confirming commit db7715407efa43cd2a66caed67c02d8f7bb90b35 has fixed it.  Now with nss-3.52 and -git we're back in action and loading and running fine now.

**Comment by letoams** [comment]
Thanks for letting us know!
