### ISSUE TITLE
Error installing to custom directory

### ISSUE THREAD

**Issue by tutianzi** [libreswan/libreswan#339]
INC_USRLOCAL="${INSTALL_DIR}" \
make base \
&& \
INC_USRLOCAL="${INSTALL_DIR}" \
make install-base

grep pluto /var/log/secure
May 16 07:11:40 mycentos7-4 pluto[7409]: "l2tp-psk"[1] *.*.77.244 #1: responding to Main Mode from unknown peer *.*.77.244:500
May 16 07:11:40 mycentos7-4 pluto[7409]: "l2tp-psk"[1] *.*.77.244 #1: WARNING: connection l2tp-psk PSK length of 8 bytes is too short for sha PRF in FIPS mode (10 bytes required)
May 16 07:11:40 mycentos7-4 pluto[7409]: "l2tp-psk"[1] *.*.77.244 #1: Oakley Transform [AES_CBC (256), HMAC_SHA1, DH20] refused
May 16 07:11:40 mycentos7-4 pluto[7409]: "l2tp-psk"[1] *.*.77.244 #1: WARNING: connection l2tp-psk PSK length of 8 bytes is too short for sha PRF in FIPS mode (10 bytes required)
May 16 07:11:40 mycentos7-4 pluto[7409]: "l2tp-psk"[1] *.*.77.244 #1: Oakley Transform [AES_CBC (128), HMAC_SHA1, DH19] refused
May 16 07:11:40 mycentos7-4 pluto[7409]: "l2tp-psk"[1] *.*.77.244 #1: WARNING: connection l2tp-psk PSK length of 8 bytes is too short for sha PRF in FIPS mode (10 bytes required)
May 16 07:11:40 mycentos7-4 pluto[7409]: "l2tp-psk"[1] *.*.77.244 #1: STATE_MAIN_R1: sent MR1, expecting MI2
May 16 07:11:40 mycentos7-4 pluto[7409]: "l2tp-psk"[1] *.*.77.244 #1: STATE_MAIN_R2: sent MR2, expecting MI3
May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[1] *.*.77.244 #1: Peer ID is ID_IPV4_ADDR: '192.168.1.8'
May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[1] *.*.77.244 #1: switched from "l2tp-psk"[1] *.*.77.244 to "l2tp-psk"
May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #1: deleting connection "l2tp-psk"[1] *.*.77.244 instance with peer *.*.77.244 {isakmp=#0/ipsec=#0}
May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #1: Peer ID is ID_IPV4_ADDR: '192.168.1.8'
May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #1: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA1 group=MODP2048}
May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #1: Configured DPD (RFC 3706) support not enabled because remote peer did not advertise DPD support
May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #1: the peer proposed: *.241.68.255/32:17/1701 -> 192.168.1.8/32:17/0
May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #1: NAT-Traversal: received 2 NAT-OA. Using first; ignoring others
May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #2: responding to Quick Mode proposal {msgid:00000001}
May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #2:     us: 10.0.2.18[*.241.68.255]:17/1701
May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #2:   them: *.*.77.244[192.168.1.8]:17/1701
May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #2: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 transport mode {ESP/NAT=>0x3abcae52 <0x1a8f691d xfrm=AES_CBC_128-HMAC_SHA1_96 NATOA=192.168.1.8 NATD=*.*.77.244:4500 DPD=unsupported}
May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #2: up-host output: sh: ipsec: command not found
May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #2: up-host command exited with status 127
May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #2: state transition function for STATE_QUICK_R1 had internal error
May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #2: STATE_QUICK_R1: retransmission; will wait 0.5 seconds for response
May 16 07:11:42 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #2: STATE_QUICK_R1: retransmission; will wait 1 seconds for response
May 16 07:11:43 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #2: STATE_QUICK_R1: retransmission; will wait 2 seconds for response
May 16 07:11:45 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #2: STATE_QUICK_R1: retransmission; will wait 4 seconds for response
May 16 07:11:49 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #2: STATE_QUICK_R1: retransmission; will wait 8 seconds for response
May 16 07:11:57 mycentos7-4 pluto[7409]: "l2tp-psk"[2] *.*.77.244 #2: STATE_QUICK_R1: retransmission; will wait 16 seconds for response

ipsec whack --trafficstatus
003 ERROR: netlink response for Get SA esp.deb486e1@10.0.2.17 included errno 3: No such process
003 ERROR: netlink response for Get SA esp.6bdab988@*.*.77.244 included errno 3: No such process
006 #6: "l2tp-psk"[6] *.*.77.244, type=ESP, add_time=0, id='192.168.1.8'

Installed to the default directory everything is normal

**Comment by letoams** [comment]
Interesting. You should ensure the ipsec command is in the PATH of using a custom directory.

We should probably warn on that sooner though.

And perhaps also fix our updown to take the full path.

Paul

**Comment by tutianzi** [comment]
> 有趣。您应该确保ipsec命令在使用自定义目录的PATH中。我们或许应该早些警告。也许还可以解决我们的颠覆问题，以走完整的道路。保罗
> […](#)
> Sent from my iPhone
> On May 16, 2020, at 03:27, tutianzi ***@***.***> wrote: ﻿ INC_USRLOCAL="${INSTALL_DIR}" make base && INC_USRLOCAL="${INSTALL_DIR}" make install-base grep pluto /var/log/secure May 16 07:11:40 mycentos7-4 pluto[7409]: "l2tp-psk"[1] ..77.244 #1: responding to Main Mode from unknown peer ..77.244:500 May 16 07:11:40 mycentos7-4 pluto[7409]: "l2tp-psk"[1] ..77.244 #1: WARNING: connection l2tp-psk PSK length of 8 bytes is too short for sha PRF in FIPS mode (10 bytes required) May 16 07:11:40 mycentos7-4 pluto[7409]: "l2tp-psk"[1] ..77.244 #1: Oakley Transform [AES_CBC (256), HMAC_SHA1, DH20] refused May 16 07:11:40 mycentos7-4 pluto[7409]: "l2tp-psk"[1] ..77.244 #1: WARNING: connection l2tp-psk PSK length of 8 bytes is too short for sha PRF in FIPS mode (10 bytes required) May 16 07:11:40 mycentos7-4 pluto[7409]: "l2tp-psk"[1] ..77.244 #1: Oakley Transform [AES_CBC (128), HMAC_SHA1, DH19] refused May 16 07:11:40 mycentos7-4 pluto[7409]: "l2tp-psk"[1] ..77.244 #1: WARNING: connection l2tp-psk PSK length of 8 bytes is too short for sha PRF in FIPS mode (10 bytes required) May 16 07:11:40 mycentos7-4 pluto[7409]: "l2tp-psk"[1] ..77.244 #1: STATE_MAIN_R1: sent MR1, expecting MI2 May 16 07:11:40 mycentos7-4 pluto[7409]: "l2tp-psk"[1] ..77.244 #1: STATE_MAIN_R2: sent MR2, expecting MI3 May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[1] ..77.244 #1: Peer ID is ID_IPV4_ADDR: '192.168.1.8' May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[1] ..77.244 #1: switched from "l2tp-psk"[1] ..77.244 to "l2tp-psk" May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #1: deleting connection "l2tp-psk"[1] ..77.244 instance with peer ..77.244 {isakmp=#0/ipsec=#0} May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #1: Peer ID is ID_IPV4_ADDR: '192.168.1.8' May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #1: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA1 group=MODP2048} May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #1: Configured DPD (RFC 3706) support not enabled because remote peer did not advertise DPD support May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #1: the peer proposed: .241.68.255/32:17/1701 -> 192.168.1.8/32:17/0 May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #1: NAT-Traversal: received 2 NAT-OA. Using first; ignoring others May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #2: responding to Quick Mode proposal {msgid:00000001} May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #2: us: 10.0.2.18[.241.68.255]:17/1701 May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #2: them: ..77.244[192.168.1.8]:17/1701 May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #2: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 transport mode {ESP/NAT=>0x3abcae52 <0x1a8f691d xfrm=AES_CBC_128-HMAC_SHA1_96 NATOA=192.168.1.8 NATD=..77.244:4500 DPD=unsupported} May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #2: up-host output: sh: ipsec: command not found May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #2: up-host command exited with status 127 May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #2: state transition function for STATE_QUICK_R1 had internal error May 16 07:11:41 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #2: STATE_QUICK_R1: retransmission; will wait 0.5 seconds for response May 16 07:11:42 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #2: STATE_QUICK_R1: retransmission; will wait 1 seconds for response May 16 07:11:43 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #2: STATE_QUICK_R1: retransmission; will wait 2 seconds for response May 16 07:11:45 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #2: STATE_QUICK_R1: retransmission; will wait 4 seconds for response May 16 07:11:49 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #2: STATE_QUICK_R1: retransmission; will wait 8 seconds for response May 16 07:11:57 mycentos7-4 pluto[7409]: "l2tp-psk"[2] ..77.244 #2: STATE_QUICK_R1: retransmission; will wait 16 seconds for response ipsec whack --trafficstatus 003 ERROR: netlink response for Get SA ***@***.*** included errno 3: No such process 003 ERROR: netlink response for Get SA ***@***.*** included errno 3: No such process 006 #6: "l2tp-psk"[6] ..77.244, type=ESP, add_time=0, id='192.168.1.8' Installed to the default directory everything is normal — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you
I have ruled out this problem, he seems to be the absolute path
PATH=".../libexec/ipsec:.../sbin:${PATH}"

**Comment by tutianzi** [comment]
grep pluto /var/log/secure
pluto[6367]: "l2tp-psk"[2] *.*.77.244 #2: up-host output: sh: ipsec: command not found
pluto[6367]: "l2tp-psk"[2] *.*.77.244 #2: up-host command exited with status 127
pluto[6367]: "l2tp-psk"[2] *.*.77.244 #2: state transition function for STATE_QUICK_R1 had internal error
pluto[6367]: "l2tp-psk"[2] *.*.77.244 #2: STATE_QUICK_R1: retransmission; will wait 0.5 seconds for response
pluto[6367]: "l2tp-psk"[2] *.*.77.244 #2: STATE_QUICK_R1: retransmission; will wait 1 seconds for response
pluto[6367]: "l2tp-psk"[2] *.*.77.244 #2: STATE_QUICK_R1: retransmission; will wait 2 seconds for response
pluto[6367]: "l2tp-psk"[2] *.*.77.244 #2: STATE_QUICK_R1: retransmission; will wait 4 seconds for response

ipsec whack --trafficstatus
003 ERROR: netlink response for Get SA esp.deb486e1@10.0.2.17 included errno 3: No such process
003 ERROR: netlink response for Get SA esp.6bdab988@*.*.77.244 included errno 3: No such process

PATH=".../libexec/ipsec:.../sbin:${PATH}"
Using environment variables does not solve the problem, it seems that he uses an absolute path internally

**Comment by bleve** [comment]
The build is done wrong. INC_USRLOCAL must be the prefix in system. if you want to install to other system location, like packaging, you must use DESTDIR to give path to remote system mount for example.

INC_USRLOCAL MUST match the final system real path, libreswan is not using PATH environment variable  to find it's own commands.

**Comment by tutianzi** [comment]
INC_USRLOCAL='/usr/local/libreswan' make base
INC_USRLOCAL='/usr/local/libreswan' make install-base

And don't install libreswan in the default directory
And don't install libreswan in the default directory
And don't install libreswan in the default directory

**Comment by bleve** [comment]
That's not at all how install is designed to work. Btw. INC_USRLOCAL is now removed from git version and replaced with PREFIX= which is generally either /usr, /usr/local, /opt or whatever location PREFIX you want. Command ipsec must be found from path to use it - if you do your own directory structure like you do you must add directory with ipsec command into your sytem path.

**Comment by tutianzi** [comment]
I use GIT version of libreswan, same error
PREFIX=‘/usr/local/libreswan’
And don't install libreswan in the default directory

**Comment by bleve** [comment]
If you want to install to non-standard directory like you do you MUST add /usr/local/libreswan/sbin directory to your path. Or you set (with older version) PUBDIR=/usr/local/sbin so that ipsec command is in your path. On git master that is SBINDIR which you set for ipsec command.
