### ISSUE TITLE
Can't make a connection with PSK

### ISSUE THREAD

**Issue by TaloniumSW** [libreswan/libreswan#343]
Hi, i'm trying to setup a RHEL 8.2 Server running Libreswan 3.29 (netkey) to talk with a Windows 10 1909 Client. 

I want them to be able to talk by PSK, so i set up the PSK in both Windows and RHEL

/etc/ipsec.secret

![Screenshot_60](https://user-images.githubusercontent.com/19256593/82523998-b9080200-9afb-11ea-950e-ebd1a5a43b11.png)

Windows SecPol IPSec Config

![Screenshot_61](https://user-images.githubusercontent.com/19256593/82524030-d89f2a80-9afb-11ea-8c1d-3e12ae6ceb0a.png)

I have the IPs (Just testing on local VMs) 192.168.1.12 for the RHEL Server and 192.168.1.9 for the Windows 10 Client and i have the Policy Assigned on the Windows 10 Client but when i start up the "mytunnel" ipsec config it just times out (i've tried pinging and other things but nothing seems to work)

![Screenshot_63](https://user-images.githubusercontent.com/19256593/82524533-35e7ab80-9afd-11ea-911a-8f141b5de30e.png)

I did some googling and found the IKE settings i needed for Windows, and i also added the reg key i needed for it to work with 

![Screenshot_64](https://user-images.githubusercontent.com/19256593/82524604-64fe1d00-9afd-11ea-9e5c-bf988e5f6d0b.png)

/etc/ipsec.d/mytunnel.conf
![Screenshot_65](https://user-images.githubusercontent.com/19256593/82524736-aee70300-9afd-11ea-9601-eeff20f84c7a.png)

/etc/ipsec.conf
![Screenshot_66](https://user-images.githubusercontent.com/19256593/82524741-b3abb700-9afd-11ea-86a6-10cf5d60763b.png)

If i am missing something, please let me know cause i've been scratching my head trying to figure it out haha

**Comment by letoams** [comment]
the logs show that your first IKE packet does not get a response.
Most likely a firewall is blocking things

**Comment by letoams** [comment]
please confirm you still have an issue

**Comment by TaloniumSW** [comment]
I'll try to drop the tables, forgot this post even existed

**Comment by cagney** [comment]
Assuming resolved.  If not, please re-open.
