### ISSUE TITLE
does "DNE" mean "does not exist" or "DONE"?

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#346]
in `show_addresspool_status()`, in `programs/pluto/addresspool.c`, it says:

```C
			show_comment(s, "    %s %u %s #%lu %s%s%s",
				     str_address(&lease_ip, &ipb),
				     lease->lease_refcount,
				     IS_INSERTED(lease, free_entry) ? "free" : "in-use",
				     lease->assigned_to,
				     (lease->assigned_to == SOS_NOBODY ? "unassigned" :
				      st != NULL ? st->st_state->short_name : "DNE"),
				     lease->reusable_name != NULL ? " " : "",
				     lease->reusable_name != NULL ? lease->reusable_name : ""
				);
```

I understand what `free` and `in-use` and `unassigned` means, but i don't know what `DNE` means.  It looks like it's related to the `.short_name` member of `struct finite_state`, as defined in `state.c`, which includes `UNDEFINED`, `IKEv1_ROOF`, `IKEv2_ROOF`.  Given the size of these labels, maybe `DNE` could be written out as `DOES_NOT_EXIST` instead?  or is it a typo for `DONE` ?

**Comment by letoams** [comment]
this code has changed and "DNE" is no longer present.
