### ISSUE TITLE
unclear comment in `could_route`

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#347]
in `could_route` in `programs/pluto/kernel.c`, there is a comment:

```c
			/*
			 * Another connection is already using the eroute.
			 * TODO: NETKEY can do this? For now excempt OE only
			 */
```

I don't know what `excempt` is supposed to mean.  it sounds like it could be either "accept" or "exempt".  If it is "exempt", it's not clear to me what condition is being exempted from what overall policy.

A clearer comment would be useful here.

**Comment by letoams** [comment]
clarified
