### ISSUE TITLE
TS_UNACCEPTABLE with multiple subnets

### ISSUE THREAD

**Issue by programmingphil** [libreswan/libreswan#349]
**Context**

Using Libreswan 3.27-6 as per the Debian release Buster for both client and host.

I have a connection which is between two hosts at fixed IP addresses on a local network (for an experiment). I am intending to set up a vpn between the two hosts. One, (herein `left`) has multiple subnets behind it which `right` requires access to.

I can define a single subnet behind one of the hosts, and address pool for `right` with a single IP range, and connect successfully. 

When I attempt to change from `leftsubnet` to `leftsubnets`, I get an error from the logs which tells me the definition is incomplete (i.e. I must specify a `rightsubnet`, which I specify as being the 'right' fixed IP address within the tunnel, with a bitmask of 32.

When I add the `rightsubnet`, I remove any address pool that I was previously using.

**Bug**

At the attempt to connect, the `left` rejects `right` with a TS_UNACCEPTABLE error.

Pseudonymised config is as follows:

```
    left=192.168.x.x
    leftid=@fqdn.example.com
    leftsourceip = 192.168.y.z
    leftsubnets = { 192.168.a.b/30, 192.168.c.d/30 }
    leftrsasigkey=%cert
    right=%any #error bug also occurs with a fixed IP address 192.168.e.f
    rightid=%fromcert
    rightsourceip=192.168.y.x
    rightsubnet=192.168.y.x/32 #error also occurs with IP address 192.168.e.f/32
    rightrsasigkey=%cert
    rightcert=a-cert-nickname
    rightca=a-ca-cert-nickname
    auto=start
    narrowing=no
    dpddelay=30
    dpdtimeout=120
    dpdaction=clear
    ikev2=insist
    rekey=yes
    fragmentation=no
```

Any guidance as to what is going wrong would be appreciated.

**Comment by programmingphil** [comment]
Switching to ikev1 (`ikev2=no`) yields messages in the logs:

`Cannot respond to IPSec SA request because no connection is known...` for every subnet except the first in the list.

**Comment by letoams** [comment]
On Sat, 6 Jun 2020, programmingphil wrote:

> Switching to ikev1 (ikev2=no) yields messages in the logs:
> 
> Cannot respond to IPSec SA request because no connection is known... for every subnet except the first in the list.

Multiple subnets on one side with addresspool on the other side is
unfortunately not yet supported as you have found out. For IKEv1,
it is supported with XAUTH on the client side to interop with cisco,
but not on the server side.

You might be able on the client to split this into three seperate
connections of one subnet. I am not sure how that will work out
though.

Paul

**Comment by programmingphil** [comment]
Ah right I see. Would it be possible to add a note to the ipsec.conf documentation to indicate that?

What I'll probably do instead is set up a route-based vpn and route the pertinent traffic over the connection manually.

**Comment by programmingphil** [comment]
I will compare my configurations with those tests and get back to you.

**Comment by programmingphil** [comment]
Sorry for the long pause - had a few upsets on the way to retesting.

I can confirm I am still seeing this issue. For completeness, here is the config with IP addresses changed, but representative.

```
conn admin
    left=192.168.1.33
    leftid=@admin.my.fqdn.tld
    leftsourceip=192.168.2.37
    leftsubnets={192.168.2.37/32, 192.168.2.4/30, 192.168.2.12/30}
    leftcert=my-cert-alias
    leftrsasigkey=%cert
    leftca=my-cert-ca-alias
    leftmodecfgserver=yes
    rightid=%fromcert
    rightrsasigkey=%cert
    right=192.168.2.34
    rightsourceip=192.168.2.38
    rightsubnet=192.168.2.38/32
    auto=add
    narrowing=no
    dpddelay=30
    dpdtimeout=120
    dpdaction=clear
    ikev2=insist
    rekey=yes
    fragmentation=no
```

Note: no address pools.

At the attempt to connect, the left rejects right with a TS_UNACCEPTABLE error.

If you can see a problem with the above config, then I can make adjustments and retest.

**Comment by letoams** [comment]
On Tue, 11 Aug 2020, programmingphil wrote:

> Subject: Re: [libreswan/libreswan] TS_UNACCEPTABLE with multiple subnets >     (#349)

> I can confirm I am still seeing this issue.

I have seen it too, and think I can create the appropriate test case
now.

> At the attempt to connect, the left rejects right with a TS_UNACCEPTABLE error.

I think if you happen to hit the instance before the template this
happens. This also seems to be hit during rekeying.

Paul

**Comment by letoams** [comment]
this _should_ be addressed with libreswan 4.4 released today. Please let us know if you still see this issue

**Comment by programmingphil** [comment]
Thankyou, I'm afraid it will take that some time to work it's way downstream to a stable Debian version.

In the meantime, I'm afraid I had to move to one of your competitors to get our VPN solution running, my apologies, but this also means that I am unlikely to be able to check this fix anytime soon.

**Comment by letoams** [comment]
On Mon, 3 May 2021, programmingphil wrote:

> Thankyou, I'm afraid it will take that some time to work it's way downstream to a stable Debian version.

We support running "make deb" from the source to build a debian package.

> In the meantime, I'm afraid I had to move to one of your competitors to get our VPN solution running, my apologies, but this also means that I am unlikely to be able to check this fix anytime soon.

Understood. Glad you got something working, and thanks for reporting the
bug.

Paul
