### ISSUE TITLE
`make rpm` in FIPS mode on Fedora 32 fails

### ISSUE THREAD

**Issue by kavinda-forcepoint** [libreswan/libreswan#351]
### Summary

Running `make rpm` in FIPS mode on Fedora 32 (64-bit) fails during the `check` stage.

The same `make rpm` succeeds when _not_ in FIPS mode.

### Details

Here's the tail end of the `make rpm` command output:
```
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.gcWkZk
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd libreswan-3.30rc1091_gd00b8d028a_peer_dn_wildcard_support
+ cp /root/rpmbuild/SOURCES/ikev1_dsa.fax.bz2 /root/rpmbuild/SOURCES/ikev1_psk.fax.bz2 /root/rpmbuild/SOURCES/ikev2.fax.bz2 .
+ bunzip2 ikev1_dsa.fax.bz2 ikev1_psk.fax.bz2 ikev2.fax.bz2
+ export NSS_DISABLE_HW_GCM=1
+ NSS_DISABLE_HW_GCM=1
+ : starting CAVS test for IKEv2
+ /root/rpmbuild/BUILDROOT/libreswan-3.30-0.rc1091_gd00b8d028a_peer_dn_wildcard_support.x86_64/usr/libexec/ipsec/cavp -v2 ikev2.fax
+ diff -u ikev2.fax -
test: IKE v2
Reading from ikev2.fax
error: Bad exit status from /var/tmp/rpm-tmp.gcWkZk (%check)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.gcWkZk (%check)
make: *** [Makefile:136: rpm] Error 1
```

Running the failed `cavp` command manually results in the following output:

```
# /root/rpmbuild/BUILDROOT/libreswan-3.30-0.rc1091_gd00b8d028a_peer_dn_wildcard_support.x86_64/usr/libexec/ipsec/cavp -v2 ikev2.fax
<...Output truncated...>
DKM(Child SA D-H) = 3e29f420002132a7424067420f9e8c90ba9d9492a8d637f05a3696a815e05d1406ac68db18579c6e561db88573220a163f2c72c2e71bb830cea759575859e14a825622904f034eee6341b82da35330da858a1ac3f78e06f6feffe6468c8eccc304d0e331ec8d820b9f7a61e374f2478b7558220c7790fed40321cb93f5f37992dac2fcf7d8b7974715d96a88db6d5ecbe569a0f9b4f9df075a10644f062db722cb244fcb5b82cf1fbd9868464fd0ffa76fe54c356c28dadb9db101bec49d23d7e47891d1af798f6c8e1f280a66764af57adb3870934a8a3327bd812a16b8dc622f9029af905ea2068bf7056ed3952158fcdd2b5f91a1550a927b1066494930c2dd10cf8602870b19281397720d138ae583b10235af2f90710e6eff7991c4041ff6facc1a34f16e4d4e0e13d1f31875ed4f4dc199b762e4f5e16136bffeae03e4be9a418da3a598e864021372de4256d79d40002ecf0d8c1e5c08ceaa4720c669d10babc2406fb5bc64bc962d6e9b039c940621e7951b2dee5b96f01f6919ad63
SKEYSEED(Rekey) = 7fa980970fd72be66f8f14a99ee8c38023668c14666e9c02405673733a16caa1


[g^ir length = 256]
[SHA-384]
[Ni length = 64]
[Nr length = 64]
[DKM length = 1056]
[Child SA DKM length = 1056]

COUNT = 0
Ni = fd1b572a8e735591
Nr = 6013b0ef88dacd3d
g^ir = d3288cd87565101e88fe3bad918f31939d8dd26ff1071f8b2d7f447524e58d7c
g^ir (new) = 3358f620539473aee8d07e779764c4c6a9aabddc79a28e136b3bac021dbde44a
SPIi = 2116ad07ce61f749
SPIr = 24880e55f11a65b7
SKEYSEED = 
failure in SKEYSEED = prf(Ni | Nr, g^ir)
```

**Comment by letoams** [comment]
So those two nonces together are 128 bits, which is not enough for a SHA2_384 or SHA2_512 PRF, which requires half the keysize, so 384/2 = 192 bits of nonces and 512/2 = 256 bits of nonces.

So you should remove the tests for SHA2_384 and SHA2_512 that have:

[Ni length = 64]
[Nr length = 64]

**Comment by kavinda-forcepoint** [comment]
Thanks for the quick answer. How do I remove tests that you have suggested?

**Comment by letoams** [comment]
On Tue, 7 Jul 2020, kavinda-forcepoint wrote:

> Thanks for the quick answer. How do I remove tests that you have suggested?

I have removed the tests that are not FIPS compliant from the IKEv2 CAVS
list and updated the files upstream:

https://download.libreswan.org/cavs/ikev2.fax.bz2
https://download.libreswan.org/cavs/ikev2.fax.bz2.asc

However, there is also an issue with the IKEv1 test vectors. I suspect
it is similar (the PSK is too short for the PRF), but I haven't verified
nor updated those yet.

Paul

**Comment by kavinda-forcepoint** [comment]
Hi Paul,

Thank you for the IKEv2 files update.

You are right that there is an issue with IKEv1; here's the output I see for `cavp -v1dsa ikev1_dsa.fax`:
```
COUNT = 99
CKY_I = 99992c22ee06dd34
CKY_R = 6b76fbd1959849cc
Ni = fbabc6663fc0ccd0f0c0468949f098ef90af1f4cbca3b62fde6bbbdbfab7847d23f42961907b42bba19ce6e10f3b535973af60824956ed553d0d8d1a5e5632ae615d22f319ddef18f1fd2bc83988a6e983bf5ab3ffffe942e8ba66f35c77ecc3e7efbbd4edef7f89f63386d1d132b1fd77a6c5abf392408227c6ff196e1d5ce9df44e16e5af9a24343f28e692244097037cde7e290c3069e15b3a0e3d9e4bd870b3cad774bf71139bb4b7ffbbbbd1b32e581f3dd8bed71998601c6960d15d0b13f9a47ec2378b583c360240b415da1b831e1bd868c2d9a70756d74bf37544864b300742036a645f321f12db4a6fb1a1a0bab9b1fd965bf164f734351c060740f
Nr = 634a316a2306b65b9b9b0474514bbe826d7d0306b7150cb3ebf609350c92942ca6e5347955fb0bb10ab8cf845cc421685797f26ff2e5b2e567b7fa119b5849265764f345418cb1fe709381c7ac62bfe49a55e4babdcfcc613519f0b6052cfe7aba0abadff88d58e4f4212947237f46741c7c76022c8812c9fa3c7623d7786375d48e46ccccd13da135e118867a20bf087c9dce0becdb78a022156912fcb112e688644f50d269cb200e0ae6748b83815d7a01493eeff7caac299f1f2b8d5b3bc6a492d8663793725fc04c0a759238fdac989bb1d1d1b453e39d75a807df8e44c44adeacffa0abe379f005ae13c5eb7403d2cb42b435d7b361a114fe2dd4db1d82
g^xy = 4eb7f7e95111ba060ebdcce449279566f8b123beb3ed3f47c243a4fa78e01205
SKEYID = 31c0c7b422c2afb26dc54d4f5eb4e50f019c8bf33b078725e9376d3f922e3010
SKEYID_d = 3ff08e5a4e79c0ebad57124ee7a1d1ae9881fe3c7f73565ced8936730196659b
SKEYID_a = 1e350d32816854a907023bb37aa0375943de7328a57673d870895e1110a7b34c
SKEYID_e = 68a09989c5eeaca71833885cb719796a5decd96fbfdcb355f454ee58cd657680


[g^xy length = 256]
[SHA-384]
[Ni length = 64]
[Nr length = 64]

COUNT = 0
CKY_I = 1c8aba986a00af0f
CKY_R = b049d9672f73c920
Ni = cec89d845add83ef
Nr = cebd43ab71d17db9
g^xy = 1724dbd893523764bfef8c6fa927856fccfb77ae254358cce29c2769a32915c1
Segmentation fault (core dumped)
```

Please let me know if there is any other information I can provide.

-Kavinda

**Comment by letoams** [comment]
On Thu, 16 Jul 2020, kavinda-forcepoint wrote:

> Thank you for the IKEv2 files update.
> 
> You are right that there is an issue with IKEv1; here's the output I see for cavp -v1dsa ikev1_dsa.fax:

> [g^xy length = 256]
> [SHA-384]
> [Ni length = 64]
> [Nr length = 64]

So this also has 64*2 = 128   which is < 384/2 = 192 so this one also
fails and should be removed. I think I removed a few of days, and than
ran into another issue that was different.

Paul

**Comment by cThrice** [comment]
Just ran into this building for RHEL7.  Did anyone happen to update the other files for ikev1_dsa?

**Comment by letoams** [comment]
On Mon, 8 Feb 2021, Carl wrote:

> Just ran into this building for RHEL7. Did anyone happen to update the other files for ikev1_dsa?

Not yet.

I am contemplating changing libreswan to no longer allow these "too
small" nonces even when not running in FIPS mode. I think it is good for
security to stick with a lower band of 112 bits security, and then we
can also just permanently removes these test vectors and testing with
and without FIPS mode can remain the same process.

**Comment by cagney** [comment]
these systems are too old
