### ISSUE TITLE
compile error: kernel_xfrm_interface.c:147:30: error: ‘IFLA_XFRM_IF_ID’ undeclared 

### ISSUE THREAD

**Issue by werton13** [libreswan/libreswan#358]
Hello I'm trying to compile the 3.31 version according to the readme instructions for Ubuntu.
I'm on Ubuntu 18.04 
4.15.0-112-generic
when I try to make programs or make base - I receiving a set of errors:
````bash
/home/webadmin/libreswan/programs/pluto/kernel_xfrm_interface.c: In function ‘link_add_nl_msg’:
/home/webadmin/libreswan/programs/pluto/kernel_xfrm_interface.c:147:30: error: ‘IFLA_XFRM_IF_ID’ undeclared (first use in this function); did you mean ‘IPSEC1_XFRM_IF_ID’?
  nl_addattr32(&req->n, 1024, IFLA_XFRM_IF_ID, if_id);
                              ^~~~~~~~~~~~~~~
                              IPSEC1_XFRM_IF_ID
/home/webadmin/libreswan/programs/pluto/kernel_xfrm_interface.c:147:30: note: each undeclared identifier is reported only once for each function it appears in
/home/webadmin/libreswan/programs/pluto/kernel_xfrm_interface.c:153:32: error: ‘IFLA_XFRM_LINK’ undeclared (first use in this function); did you mean ‘IFLA_VXLAN_LINK’?
    nl_addattr32(&req->n, 1024, IFLA_XFRM_LINK, dev_link_id);
                                ^~~~~~~~~~~~~~
                                IFLA_VXLAN_LINK
/home/webadmin/libreswan/programs/pluto/kernel_xfrm_interface.c: In function ‘parse_xfrm_linkinfo_data’:
/home/webadmin/libreswan/programs/pluto/kernel_xfrm_interface.c:277:34: error: ‘IFLA_XFRM_LINK’ undeclared (first use in this function); did you mean ‘IFLA_VXLAN_LINK’?
   if (nested_attrib->rta_type == IFLA_XFRM_LINK)
                                  ^~~~~~~~~~~~~~
                                  IFLA_VXLAN_LINK
/home/webadmin/libreswan/programs/pluto/kernel_xfrm_interface.c:280:34: error: ‘IFLA_XFRM_IF_ID’ undeclared (first use in this function); did you mean ‘IFLA_XFRM_LINK’?
   if (nested_attrib->rta_type == IFLA_XFRM_IF_ID)
                                  ^~~~~~~~~~~~~~~
                                  IFLA_XFRM_LINK
../../mk/depend.mk:32: recipe for target 'kernel_xfrm_interface.o' failed

````
I tried pre-built version 1.23, but  faced another error then connecting with user certificate from Win 10, so i decide to try most fresh version from here. Please, can you advise why I see these compile errors?

**Comment by letoams** [comment]
On Mon, 10 Aug 2020, werton13 wrote:

> Subject: [libreswan/libreswan] compile error: kernel_xfrm_interface.c:147:30:
>     error: ‘IFLA_XFRM_IF_ID’ undeclared  (#358)
> 
> 
> Hello I'm trying to compile the 3.31 version according to the readme instructions for Ubuntu.
> I'm on Ubuntu 18.04
> 4.15.0-112-generic
> when I try to make programs or make base - I receiving a set of errors:

try using: make deb

That sets up some options required for debian/ubuntu. If compiling
manually, see below.

> /home/webadmin/libreswan/programs/pluto/kernel_xfrm_interface.c: In function ‘link_add_nl_msg’:
> /home/webadmin/libreswan/programs/pluto/kernel_xfrm_interface.c:147:30: error: ‘IFLA_XFRM_IF_ID’ undeclared (first
>  use in this function); did you mean ‘IPSEC1_XFRM_IF_ID’?

In you case, you need to set USE_XFRM_INTERFACE_IFLA_HEADER=true

> /home/webadmin/libreswan/programs/pluto/kernel_xfrm_interface.c:153:32: error: ‘IFLA_XFRM_LINK’ undeclared (first

and USE_XFRM_HEADER_COPY=true

Paul
