### ISSUE TITLE
Build KLIPS for linux-4.1

### ISSUE THREAD

**Issue by MiRacLe-RPZ** [libreswan/libreswan#37]
$make module
<pre> Building module for a 2.6 kernel
make[1]: Entering directory `/usr/src/slapt-src/libreswan/libreswan'
make[2]: Entering directory `/usr/src/slapt-src/libreswan/libreswan'
make[2]: `/usr/src/slapt-src/libreswan/libreswan/modobj/Makefile' is up to date.
make[2]: Leaving directory `/usr/src/slapt-src/libreswan/libreswan'
make -C /lib/modules/4.1.6/build  BUILDDIR=/usr/src/slapt-src/libreswan/libreswan/modobj SUBDIRS=/usr/src/slapt-src/libreswan/libreswan/modobj MODULE_DEF_INCLUDE=/usr/src/slapt-src/libreswan/libreswan/packaging/linus/config-all.h MODULE_DEFCONFIG=/usr/src/slapt-src/libreswan/libreswan/linux/net/ipsec/defconfig  MODULE_EXTRA_INCLUDE= ARCH=x86_64 V= modules
make[2]: Entering directory `/usr/src/linux-4.1.6'
  CC [M]  /usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.o
/usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.c: In function ‘klips_rebuild_header’:
/usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.c:354:26: error: ‘const struct header_ops’ has no member named ‘rebuild’
      prv->dev->header_ops->rebuild == NULL) {
                          ^
In file included from /usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.c:36:0:
/usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.c:360:28: error: ‘const struct header_ops’ has no member named ‘rebuild’
        prv->dev->header_ops->rebuild : 0);
                            ^
/usr/src/slapt-src/libreswan/libreswan/linux/include/libreswan/ipsec_param.h:164:40: note: in definition of macro ‘KLIPS_PRINT’
  ((flag) ? printk(KERN_INFO format, ## args) : 0)
                                        ^
/usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.c:376:28: error: ‘const struct header_ops’ has no member named ‘rebuild’
  ret = prv->dev->header_ops->rebuild(skb);
                            ^
/usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.c: At top level:
/usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.c:479:2: error: unknown field ‘rebuild’ specified in initializer
  .rebuild        = klips_rebuild_header,
  ^
/usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.c:479:2: warning: initialization from incompatible pointer type
/usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.c:479:2: warning: (near initialization for ‘klips_header_ops.cache’)
/usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.c: In function ‘ipsec_tunnel_rebuild_header’:
/usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.c:1226:22: error: ‘const struct header_ops’ has no member named ‘rebuild’
  if (!prv->header_ops->rebuild)
                      ^
/usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.c:1255:23: error: ‘const struct header_ops’ has no member named ‘rebuild’
  ret = prv->header_ops->rebuild(skb);
                       ^
/usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.c: At top level:
/usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.c:1374:2: error: unknown field ‘rebuild’ specified in initializer
  .rebuild        = ipsec_tunnel_rebuild_header,
  ^
/usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.c:1374:2: warning: initialization from incompatible pointer type
/usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.c:1374:2: warning: (near initialization for ‘ipsec_tunnel_header_ops.parse’)
make[3]: *** [/usr/src/slapt-src/libreswan/libreswan/modobj/ipsec_tunnel.o] Error 1
make[2]: *** [_module_/usr/src/slapt-src/libreswan/libreswan/modobj] Error 2
make[2]: Leaving directory `/usr/src/linux-4.1.6'
make[1]: *** [module26] Error 2
make[1]: Leaving directory `/usr/src/slapt-src/libreswan/libreswan'
make: *** [module] Error 2
</pre>

**Comment by wofferl** [comment]
I have added patches for kernel 4.1 to the bug tracker: https://bugs.libreswan.org/show_bug.cgi?id=246

**Comment by letoams** [comment]
On Tue, 3 Nov 2015, Wolfgang wrote:

> I have added patches for kernel 4.1 to the bug tracker: https://bugs.libreswan.org/show_bug.cgi?id=246

merged, thanks!

Paul
