### ISSUE TITLE
Pluto hangs on start up with large open file ulimit (ulimit -n)

### ISSUE THREAD

**Issue by markdgray** [libreswan/libreswan#373]
## Description
When starting pluto on a machine with a large "open file" ulimit (e.g ulimit -n 1073741816), pluto is unresponsive for a long time (~30 minutes). This is due to it iterating over potentially open file descriptors at https://github.com/libreswan/libreswan/blob/fcddd2602368639a5fdec67cc740b1b624467fca/programs/pluto/plutomain.c#L1548.
## Reproduce
This can be reproduced by running the following commands:
```
# Shell 1:
$ ulimit -n 1073741816
$ /usr/libexec/ipsec/pluto --leak-detective --config /etc/ipsec.conf --logfile /var/log/libreswan.log --nofork &
# Shell 2:
$ ipsec status
```
### Expected Output
```
000 using kernel interface: netkey
..
..
..
000 IPsec SAs: total(0), authenticated(0), anonymous(0)
000  
000 Bare Shunt list:
000  
```
### Actual Output
N/A (`ipsec status` command hangs)

**Comment by cagney** [comment]
I'm assuming you've confirmed it is in the above by pulling a backtrace say?

The pertinent part is the comment:
	/*
	 * Close everything but ctl_fd and (if needed) stderr.
	 * There is some danger that a library that we don't know
	 * about is using some fd that we don't know about.
	 * I guess we'll soon find out.
	 */
It's 2020 so it should no longer be true.   Perhaps replace the code with something that, when in debug mode, probes to FDs to see what is open and dbg() that.

We'll also need to audit any code opening file descriptors (open, accept, socket, pipe, ...) and change them to specify *CLOEXEC.  Both the BSDs and Linux support SOCK_CLOEXEC (and SOCK_NONBLOCK) for instance.

**Comment by markdgray** [comment]
Yes, I did some tracing to confirm.
