### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [libreswan/libreswan#374]
It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://help.github.com/en/enterprise/2.13/user/articles/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by Neustradamus** [comment]
@libreswan, @cagney, @tbaederr, @letoams, @HughR: I think that the best solution is (in few minutes):
- Change your username to libreswanaccount (or other): https://github.com/settings/admin
- Create libreswan organization: https://github.com/organizations/new

And:
- Transfer libreswan into libreswan org: https://github.com/NEWACCOUNTUSERNAME/libreswan/settings

No lost, you can see, for examples:
- https://github.com/nerzhul/ocsms
- https://github.com/tigaseinc/tigase-server

Linked to:
- https://github.com/libreswan/libreswan/issues/297

**Comment by letoams** [comment]
finally done :)
