### ISSUE TITLE
IPv6 over IPv4 and IPv4/IPv6 over IPv4 tunnel support

### ISSUE THREAD

**Issue by chenwng** [libreswan/libreswan#375]
Hi,

Does libreswan support IPv6 over IPv4 and IPv4/IPv6 over IPv4 tunnel types?

I tried leftsubnets="0.0.0.0/0,::/0" and leftsubnets="::/0" with IPv4 left. whack gave me error messages in both cases.  It looks these lines below check the subnets with the left/right's address family. So I assume these are not supported. Can anyone please confirm this or point me the right direction if I am wrong?

https://github.com/libreswan/libreswan/blob/aeb9f2581ad4e5e69fb2f93709e1b8be34b6c2a2/lib/libipsecconf/starterwhack.c#L777-L779
https://github.com/libreswan/libreswan/blob/aeb9f2581ad4e5e69fb2f93709e1b8be34b6c2a2/lib/libipsecconf/starterwhack.c#L787-L789

Thanks!

**Comment by letoams** [comment]
On Thu, 22 Oct 2020, chenwng wrote:

> Does libreswan support IPv6 over IPv4 and IPv4/IPv6 over IPv4 tunnel types?
> 
> I tried leftsubnets="0.0.0.0/0,::/0" and leftsubnets="::/0" with IPv4 left. whack gave me error messages in both
> cases. It looks these lines below check the subnets with the left/right's address family. So I assume these are not
> supported. Can anyone please confirm this or point me the right direction if I am wrong?

It works, but you cannot mix address family per conn.

So use:

conn stuff-v4
 	[...]
 	leftsubnets="10.0.1.024,192.168.0.0/16"
 	rightsubnets="0.0.0.0"

conn stuff-v6
 	[...]
 	leftsubnets="2001:db8::/32"
 	rightsubnets="::0"

where [...] is the same for both to identify the endpoints and
authentication etc.

For libreswan 4.2, we are working on allowing to combine these into one
conn, and also to combine them as traffic selectors on a single IPsec SA.

Paul

**Comment by chenwng** [comment]
Hi Paul,

Thanks a lot for your reply!

I tried with following configuration for IPv6 over IPv4. addconn still gave me error message.

```
conn ipv6
    left=10.67.24.125
    leftsubnets="::"
    right=10.67.24.96
    rightsubnets="::"
    authby=secret
    ipsec-interface=100
    interface-ip=192.168.1.2/24
    type=tunnel
    failureshunt=passthrough
```
```
addconn ipv6
conn: "ipv6" warning '::' is not a subnet declaration. (leftsubnets). no / in subnet specification
conn: "ipv6" warning '::' is not a subnet declaration. (rightsubnets). no / in subnet specification
connect(pluto_ctl) failed: No such file or directory
```
And with "::/0"
```
addconn ipv6
conn: "ipv6" warning '::/' is not a subnet declaration. (leftsubnets). IPv4 address may not contain `:'
conn: "ipv6" warning '::/' is not a subnet declaration. (rightsubnets). IPv4 address may not contain `:'
connect(pluto_ctl) failed: No such file or directory
```
Btw, the last sentences of error messages are because I modified the code and printed out err_t e returned by ttosubnet.
https://github.com/libreswan/libreswan/blob/078a64164df1ab16de71ffd40d13e1033750217f/lib/libipsecconf/starterwhack.c#L716-L722

I am using 
```
ipsec version
Linux Libreswan 3.32 (netkey) on 4.18.0-147.3.1.el8_1.x86_64
```

**Comment by letoams** [comment]
What happens when you use subnet (singular) instead of subnets (plural)

This looks like a bug though

**Comment by chenwng** [comment]
I got the same error with subnet (singular).

```
conn ipv6
    left=10.67.24.125
    leftsubnet="::/64"
    right=10.67.24.96
    rightsubnet="::/0"
    authby=secret
    ipsec-interface=100
    interface-ip=192.168.2.2/24
    type=tunnel
    failureshunt=passthrough
```

```
./addconn password
conn: "password" warning '2001:db8:0:1::/64' is not a subnet declaration. (leftsubnets). IPv4 address may not contain `:'
conn: "password" warning '::/0' is not a subnet declaration. (rightsubnets). IPv4 address may not contain `:'
```

**Comment by bleve** [comment]
This is more stupid issue than one would think. "::/64" is not a valid ipv6 address. Neither is "::/0"
::/64 is (completely wrong, you don't ever really want 0::/64.  but it is valid) and so is ::/0.

Quotes change address to string and IP address fields don't take strings.

**Comment by bleve** [comment]
No this is more complex. But your testing is not correct. You print conn ipv6 but you test conn password.

**Comment by bleve** [comment]
Just tested your conn ipv6 - it loads nice when I replace "::/64" with "2001:db8:0:1::/64". But tested with git version, not 3.32.

**Comment by chenwng** [comment]
My bad. Sorry for the confusion. I tried with wrong connection.

I tested again. It looks like with singular, it does work. And with plural, addconn returns the error.

```
conn ipv6
    left=10.67.24.125
    leftsubnet="::/0"
    right=10.67.24.96
    rightsubnet="::/0"
    authby=secret
    ipsec-interface=100
    interface-ip=192.168.2.2/24
    type=tunnel
    failureshunt=passthrough

ipsec addconn ipv6
002 added connection description "ipv6"
```
conn ipv6
    left=10.67.24.125
    leftsubnets="::/0"
    right=10.67.24.96
    rightsubnets="::/0"
    authby=secret
    ipsec-interface=100
    interface-ip=192.168.2.2/24
    type=tunnel
    failureshunt=passthrough

ipsec addconn ipv6
conn: "ipv6" warning '::/0' is not a subnet declaration. (leftsubnets)
conn: "ipv6" warning '::/0' is not a subnet declaration. (rightsubnets)
003 ABORT: ASSERTION FAILED: version < elemsof(ip_types) (in ip_version_info() at ip_info.c:124)
```


Thanks for your support. We can close this.

**Comment by paulwouters** [comment]
Have a look at https://testing.libreswan.org/v4.4-291-g8c14ccb7e3-main/ipv6-6in4-02-ikev2/west.console.txt 
That's from our daily test suite that passes ipv6 inside ipv4 tunnel. It works fine.

**Comment by sanjaytiwari2293** [comment]
Hi Paul,

Thanks for your quick response. I saw your test suite and it is using xfrm interface. I am using vti interface for my testing. Does it support the same with vti interfaces?

Thanks,
Sanjay

**Comment by bleve** [comment]
No. VTI is broken by design and can only do ipv4 over ipv4.

**Comment by paulwouters** [comment]
We should fail to load 6in4 and 4in6 with  VTI then
