### ISSUE TITLE
libreswan-3.20 compile error

### ISSUE THREAD

**Issue by Ribo01** [libreswan/libreswan#376]
Hi Guys, 

thanks for the libreswan support, a lot of cant do with it.

So, I recently installed libreswan and when i tried to compile it, i get the below error 

> ../../../mk/depend.mk:28: recipe for target 'addrtypeof.o' failed
make[3]: *** [addrtypeof.o] Error 1
make[3]: Leaving directory '/root/libreswan-3.20/OBJ.linux.x86_64/lib/libswan'
Makefile:106: recipe for target 'local-base' failed
make[2]: *** [local-base] Error 2
make[2]: Leaving directory '/root/libreswan-3.20/lib/libswan'
../mk/targets.mk:82: recipe for target 'recursive-all' failed
make[1]: *** [recursive-all] Error 2
make[1]: Leaving directory '/root/libreswan-3.20/lib'
mk/targets.mk:82: recipe for target 'recursive-all' failed
make: *** [recursive-all] Error 2

I don't have a clue on how to fix the error. i really need to get the libreswan installed. below is my Linux information

> Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
x86_64

link to my installation below
**https://download.libreswan.org/libreswan-3.20.tar.gz**

I really would appreciate if I can get the needed help

**Comment by letoams** [comment]
Did you run: make deb

That’s how to compile libreswan from source for Debian abs Ubuntu

**Comment by Ribo01** [comment]
Yes I did, I can share the result for that too if you want?

**Comment by bleve** [comment]
I'd give an advice - don't even try to build 3.20 - that is all too old version and should not be used because it has unfixed security issues. Use latest releases.

**Comment by Ribo01** [comment]
Oh wow… Thanks for the tip

**Comment by letoams** [comment]
Yes, use 3.32 or 4.1

**Comment by Ribo01** [comment]
I just tried to compile 3.32 but had a different error below :

 

../../mk/depend.mk:34: recipe for target 'kernel_xfrm_interface.o' failed

make[3]: *** [kernel_xfrm_interface.o] Error 1

make[3]: *** Waiting for unfinished jobs....

../../mk/targets.mk:69: recipe for target 'base' failed

make[2]: *** [base] Error 2

../mk/targets.mk:69: recipe for target 'recursive-base' failed

make[1]: *** [recursive-base] Error 2

mk/targets.mk:69: recipe for target 'recursive-base' failed

make: *** [recursive-base] Error 2

 

any ideas?

**Comment by letoams** [comment]
On Thu, 29 Oct 2020, Ribo01 wrote:

> 
> I just tried to compile 3.32 but had a different error below :
> 
> 
> 
> ../../mk/depend.mk:34: recipe for target 'kernel_xfrm_interface.o' failed

edit config.mk and set USE_XFRM_INTERFACE to false

Paul

**Comment by Ribo01** [comment]
So when I checked the config file it was already set to “false” changed it to true and ran again. 

I don’t know how you guy do this, but it worked. I appreciate everyone that contributed and helped. Very grateful 

Cheers
