### ISSUE TITLE
About Ipsec IPAddresspool

### ISSUE THREAD

**Issue by kamalsust** [libreswan/libreswan#377]
Describe the issue
I have installed ipsec successfully at my ubuntu server. After running couple of hour I can't connect ot VPN Server from iOS client.
It's seems to be an issue of ip_addresspool. I have found following comments from libreswan addrespool implementation

/*

A lease is an assignment of a single address from a particular pool.
Leases are shared between appropriate connections.
Because leases are shared, they are reference-counted.
(Since we don't (yet?) free leases that could be shared,
we don't actually need reference counting.)
When a lease ends, if it could not be shared, it is freed.
Otherwise it "lingers" so that the same client (based on ID) can later
be assigned the same address from the pool.
In the future we may implement code to delete a lingering lease to free
the address if there is no free address in the pool.
Life cycle:
created by lease_an_address if an existing or lingering lease for the
same thatid isn't found.
released (to linger or freed) by rel_lease_addr.
current code never frees a lease that could be shared.
??? This constitutes a leak.
*/
which means when addresspool would be full then it wouldn't clear it's unused pool.
How do i solve the problem or how do i increase the addresspool also.
To Reproduce
I am serving multipool user using same username and password. After running sometimes the addresspool goes to be full.

Expected behavior
Then client couldn't connect to server.

Logs
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 inte>
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: XAUTH: Sending Username/Password request (MAIN_R3->XAUTH_R0)
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: XAUTH: password file authentication method requested to authenticate user 'vpnuser'
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: XAUTH: password file (/etc/ipsec.d/passwd) open.
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: XAUTH: success user(vpnuser:xauth-psk)
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: XAUTH: User vpnuser: Authentication Successful
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: XAUTH: xauth_inR1(STF_OK)
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 inte>
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: lease_an_address failure no free address in addresspool
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: state transition function for STATE_MAIN_R3 had internal error
lines 1-23/23 (END)

Server

OS: Ubuntu 20.04/18.04
**Client **

VPN mode: [IPsec]
Additional context
Here is my ipsec.conf file details
conn shared
left=%defaultroute
leftid=103.230.173.152
right=%any
encapsulation=yes
authby=secret
pfs=no
rekey=no
keyingtries=5
dpddelay=30
dpdtimeout=120
dpdaction=clear
ikev2=never
ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1,aes256-sha2;modp1024,aes128-sha1;modp1024
phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes256-sha2_512,aes128-sha2,aes256-sha2
sha2-truncbug=no

conn l2tp-psk
auto=add
leftprotoport=17/1701
rightprotoport=17/%any
type=transport
phase2=esp
also=shared

conn xauth-psk
auto=add
leftsubnet=0.0.0.0/0
rightaddresspool=192.168.43.10-192.168.43.250
modecfgdns="8.8.8.8 8.8.4.4"
leftxauthserver=yes
rightxauthclient=yes
leftmodecfgserver=yes
rightmodecfgclient=yes
modecfgpull=yes
xauthby=file
ike-frag=yes
cisco-unity=yes
also=shared

include /etc/ipsec.d/*.conf

If I increse the rightaddresspool like 192.168.43.250 to 192.168.83.250 then client can connect to server but no internet access.
Some times I get following as Ipsec Service log:

pluto[1040425]: "xauth-psk"[15838] 213.205.241.87 #16522: them: 213.205.241.87[%any,+MC+XC+S=C]===192.168.43.145/32
pluto[1040425]: "xauth-psk"[15838] 213.205.241.87 #16522: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP/NAT=>>
pluto[1040425]: "xauth-psk"[15838] 213.205.241.87 #16522: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP/NAT=>0x03f948ad <0x00b16fc5 xfrm=AES>
pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: STATE_XAUTH_R0: retransmission; will wait 16 seconds for response
pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: XAUTH: Sending Username/Password request (XAUTH_R0->XAUTH_R0)
pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: STATE_XAUTH_R0: retransmission; will wait 32 seconds for response
pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: XAUTH: Sending Username/Password request (XAUTH_R0->XAUTH_R0)
pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: STATE_XAUTH_R0: 60 second timeout exceeded after 7 retransmits. No response (or no accept>
pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: deleting state (STATE_XAUTH_R0) aged 66.530s and sending notification
pluto[1040425]: #16520: deleting connection "xauth-psk"[15836] 89.189.188.111 instance with peer 89.189.188.111 {isakmp=#0/ipsec=#0}
lines 1-23/23 (END)

and sometimes I get like as follows:
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16523: STATE_MODE_CFG_R1: ModeCfg Set sent, expecting Ack {auth=PRESHARED_KEY cipher=AES_CBC_256 >
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16523: the peer proposed: 0.0.0.0/0:0/0 -> 192.168.43.145/32:0/0
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: responding to Quick Mode proposal {msgid:81106fcb}
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: us: 0.0.0.0/0===167.71.116.96[MS+XS+S=C]
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: them: 202.134.14.134[10.236.154.244,+MC+XC+S=C]===192.168.43.145/32
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP/NAT=>>
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: STATE_QUICK_R1: retransmission; will wait 0.5 seconds for response
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: STATE_QUICK_R1: retransmission; will wait 1 seconds for response
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: STATE_QUICK_R1: retransmission; will wait 2 seconds for response
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP/NAT=>0x0c97eb1f <0xbb9c66f8 xfrm=AES>

**Comment by letoams** [comment]
On Fri, 30 Oct 2020, kamalsust wrote:

> Describe the issue
> I have installed this script successfully. After running couple of hour I can't connect ot VPN Server from iOS client.
> It's seems to be an issue of ip_addresspool. I have found following comments from libreswan addrespool implementation

> created by lease_an_address if an existing or lingering lease for the
> same thatid isn't found.
> released (to linger or freed) by rel_lease_addr.
> current code never frees a lease that could be shared.
> ??? This constitutes a leak.
> */
> which means when addresspool would be full then it wouldn't clear it's unused pool.

That is only when two conns share an addresspool and one conn has it in
use, the other one cannot free it. I don't think this is your issue.

> How do i solve the problem or how do i increase the addresspool also.
> To Reproduce
> I am serving multipool user using same username and password. After running sometimes the addresspool goes to be full.

It is likely related to you using the PSK. It means for each connection
from the same user we cannot (in time) determine this is a re-connect,
so a new IP is assigned. Then it will take an hour for unused, idle
connections to go away and release the lease.

What version of libreswan are you using?

> rightaddresspool=192.168.43.10-192.168.43.250

How many real users are connecting? 150 would be a lot for a few users
reconnecting?

> If I increse the rightaddresspool like 192.168.43.250 to 192.168.83.250 then client can connect to server but no internet access.

That is a _very_ large addresspool. Still wonder why that makes your
router fail?

> Some times I get following as Ipsec Service log:
> 
> pluto[1040425]: "xauth-psk"[15838] 213.205.241.87 #16522: them: 213.205.241.87[%any,+MC+XC+S=C]===192.168.43.145/32
> pluto[1040425]: "xauth-psk"[15838] 213.205.241.87 #16522: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP/NAT=>>
> pluto[1040425]: "xauth-psk"[15838] 213.205.241.87 #16522: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP/NAT=>0x03f948ad <0x00b16fc5 xfrm=AES>
> pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: STATE_XAUTH_R0: retransmission; will wait 16 seconds for response
> pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: XAUTH: Sending Username/Password request (XAUTH_R0->XAUTH_R0)
> pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: STATE_XAUTH_R0: retransmission; will wait 32 seconds for response
> pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: XAUTH: Sending Username/Password request (XAUTH_R0->XAUTH_R0)
> pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: STATE_XAUTH_R0: 60 second timeout exceeded after 7 retransmits. No response (or no accept>
> pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: deleting state (STATE_XAUTH_R0) aged 66.530s and sending notification
> pluto[1040425]: #16520: deleting connection "xauth-psk"[15836] 89.189.188.111 instance with peer 89.189.188.111 {isakmp=#0/ipsec=#0}
> lines 1-23/23 (END)

It seems that the client went away after some failing. The IKEv1 XAUTH
protocol is a little flaky because both ends retransmit on packet drops.
It would be better to move your clients to IKEv2. So this would take up
a lease, but it should only take it up for 60 seconds and then free.
Can you see in the logs if that is happening?

> and sometimes I get like as follows:
> pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16523: STATE_MODE_CFG_R1: ModeCfg Set sent, expecting Ack {auth=PRESHARED_KEY cipher=AES_CBC_256 >
> pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16523: the peer proposed: 0.0.0.0/0:0/0 -> 192.168.43.145/32:0/0
> pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: responding to Quick Mode proposal {msgid:81106fcb}
> pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: us: 0.0.0.0/0===167.71.116.96[MS+XS+S=C]
> pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: them: 202.134.14.134[10.236.154.244,+MC+XC+S=C]===192.168.43.145/32
> pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP/NAT=>>
> pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: STATE_QUICK_R1: retransmission; will wait 0.5 seconds for response
> pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: STATE_QUICK_R1: retransmission; will wait 1 seconds for response
> pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: STATE_QUICK_R1: retransmission; will wait 2 seconds for response
> pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP/NAT=>0x0c97eb1f <0xbb9c66f8 xfrm=AES>

So this is fine, but it does show there is some packet loss happening
causing retransmits. But in this case it established fine.

Paul

**Comment by kamalsust** [comment]
Hi,

Thank you for quick reply.

I am using libreswan version 3.32.
I am using same username, password & psk for all of my users. 

> That is only when two conns share an addresspool and one conn has it in use, the other one cannot free it. I don't think this is your issue.
> It is likely related to you using the PSK. It means for each connection from the same user we cannot (in time) determine this is a re-connect, so a new IP is assigned. Then it will take an hour for unused, idle connections to go away and release the lease. What version of libreswan are you using?

May be that's why After a couple of hour new user can't connect to server. Though at that time my active users are 40-50 only but new user can't connect to server. Log shows follows: 

lease_an_address failure no free address in addresspool
state transition function for STATE_MAIN_R3 had internal error

> How many real users are connecting? 150 would be a lot for a few users reconnecting?

I would like to support more & more user at a time it may be 1000/2000 or more. My server configuration and Bandwidth are  good. 
"If I increse the rightaddresspool like 192.168.43.250 to 192.168.83.250 then client can connect to server but no internet access." 
I have modified the following line at 
**conn xauth-psk**
**rightaddresspool=192.168.43.10-192.168.83.250**
Is there anything that I have missed to increase the pool size? Should I need to add it anywhere else also? 
Note: I am using Ipsec protocol
> That is a _very_ large addresspool. Still wonder why that makes your router fail?

After increasing the righaddresspool if active pool size goes more than 240 then client/user can connect to server easily but can't access internet.
Following is the auth.log:

Oct 30 18:25:36  pluto[1240125]: "xauth-psk"[5672] 223.167.21.244 #7765: responding to Main Mode from unknown peer 223.167.21.244:42056
Oct 30 18:25:36  pluto[1240125]: "xauth-psk"[5672] 223.167.21.244 #7765: STATE_MAIN_R1: sent MR1, expecting MI2
Oct 30 18:25:37  pluto[1240125]: "xauth-psk"[5672] 223.167.21.244 #7765: STATE_MAIN_R2: sent MR2, expecting MI3
Oct 30 18:25:37  pluto[1240125]: "xauth-psk"[5672] 223.167.21.244 #7765: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Oct 30 18:25:37  pluto[1240125]: | ISAKMP Notification Payload
Oct 30 18:25:37  pluto[1240125]: |   00 00 00 1c  00 00 00 01  01 10 60 02
Oct 30 18:25:37  pluto[1240125]: "xauth-psk"[5672] 223.167.21.244 #7765: Peer ID is ID_IPV4_ADDR: '192.168.0.106'
Oct 30 18:25:37  pluto[1240125]: "xauth-psk"[5672] 223.167.21.244 #7765: switched from "xauth-psk"[5672] 223.167.21.244 to "xauth-psk"
Oct 30 18:25:37  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7765: deleting connection "xauth-psk"[5672] 223.167.21.244 instance with peer 223.167.21.244 {isakmp=#0/ipsec=#0}
Oct 30 18:25:37  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7765: Peer ID is ID_IPV4_ADDR: '192.168.0.106'
Oct 30 18:25:37  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7765: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Oct 30 18:25:37  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7765: XAUTH: Sending Username/Password request (MAIN_R3->XAUTH_R0)
Oct 30 18:25:37  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7765: XAUTH: password file authentication method requested to authenticate user 'vpnuser'
Oct 30 18:25:37  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7765: XAUTH: password file (/etc/ipsec.d/passwd) open.
Oct 30 18:25:37  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7765: XAUTH: success user(vpnuser:xauth-psk)
Oct 30 18:25:37  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7765: XAUTH: User vpnuser: Authentication Successful
Oct 30 18:25:38  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7765: XAUTH: xauth_inR1(STF_OK)
Oct 30 18:25:38  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7765: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Oct 30 18:25:38  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7765: modecfg_inR0(STF_OK)
Oct 30 18:25:38  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7765: STATE_MODE_CFG_R1: ModeCfg Set sent, expecting Ack {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Oct 30 18:25:38  sshd[1350417]: Failed password for root from 138.197.66.68 port 33441 ssh2
Oct 30 18:25:38  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7765: the peer proposed: 0.0.0.0/0:0/0 -> 192.168.43.144/32:0/0
Oct 30 18:25:38  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7766: responding to Quick Mode proposal {msgid:273ff941}
Oct 30 18:25:38  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7766:     us: 0.0.0.0/0===64.227.60.211[MS+XS+S=C]
Oct 30 18:25:38  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7766:   them: 223.167.21.244[192.168.0.106,+MC+XC+S=C]===192.168.43.144/32
Oct 30 18:25:38  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7766: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP/NAT=>0x06e2ab90 <0xfee4da36 xfrm=AES_CBC_256-HMAC_SHA2_256_128 NATOA=none NATD=223.167.21.244:43383 DPD=active username=vpnuser}
Oct 30 18:25:38  pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7766: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP/NAT=>0x06e2ab90 <0xfee4da36 xfrm=AES_CBC_256-HMAC_SHA2_256_128 NATOA=none NATD=223.167.21.244:43383 DPD=active username=vpnuser}
Oct 30 18:25:38  sshd[1350417]: Received disconnect from 138.197.66.68 port 33441:11: Bye Bye [preauth]
Oct 30 18:25:38  sshd[1350417]: Disconnected from authenticating user root 138.197.66.68 port 33441 [preauth]
Oct 30 18:26:12  pluto[1240125]: "xauth-psk"[5647] 80.195.100.226 #7731: DPD action - clearing connection kind CK_INSTANCE
Oct 30 18:26:12  pluto[1240125]: "xauth-psk"[5647] 80.195.100.226 #7732: deleting state (STATE_QUICK_R2) aged 337.829s and sending notification
Oct 30 18:26:12  pluto[1240125]: "xauth-psk"[5647] 80.195.100.226 #7732: ESP traffic information: in=34KB out=0B XAUTHuser=vpnuser
Oct 30 18:26:12  pluto[1240125]: "xauth-psk"[5647] 80.195.100.226 #7731: deleting state (STATE_MODE_CFG_R1) aged 338.966s and sending notification
Oct 30 18:26:12  pluto[1240125]: "xauth-psk"[5647] 80.195.100.226: deleting connection "xauth-psk"[5647] 80.195.100.226 instance with peer 80.195.100.226 {isakmp=#0/ipsec=#0}

Please assist

**Comment by letoams** [comment]
On Fri, 30 Oct 2020, kamalsust wrote:

> I am using libreswan version 3.32.
> I am using same username, password & psk for all of my users.

> I would like to support more & more user at a time it may be 1000/2000 or more. My server configuration and Bandwidth are good.

Why would you use the same PSK and user/password shared with 2000 users?
That is the same as publishing your PSK/user/password on a public web site.

If a single one of those devices is compromised, all of them have their
security compromised.

> "If I increse the rightaddresspool like 192.168.43.250 to 192.168.83.250 then client can connect to server but no internet access."
> I have modified the following line at
> conn xauth-psk
> rightaddresspool=192.168.43.10-192.168.83.250
> Is there anything that I have missed to increase the pool size? Should I need to add it anywhere else also?

I am not sure why increasing the addresspool leads to "no internet
access". the two are not related, unless for some reason your
server is running out of memory due to the large addresspool.

A feature we have not yet implemented, which would be useful in this
case is to send DPD/liveness probes to older IKE SA's with the exact
same IDs/username, so that disconnected older clients would time out
more quickly instead of accumulating over time. But again, this is
an artifact of using ancient IKEv1 XAUTH with 1 identity for many
users. IKEv1 is particularly bad for this because of the bad protocol
specification of XAUTH. This leads to both ends retransmitting and
confusion. Is there any reason why you cannot use IKEv2 instead?
(that also saves you like 4 round trips compared to IKEv1 XAUTH)

> Oct 30 18:25:38 pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7766: responding to Quick Mode proposal {msgid:273ff941}
> Oct 30 18:25:38 pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7766: us: 0.0.0.0/0===64.227.60.211[MS+XS+S=C]
> Oct 30 18:25:38 pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7766: them: 223.167.21.244[192.168.0.106,+MC+XC+S=C]===192.168.43.144/32
> Oct 30 18:25:38 pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7766: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP/NAT=>0x06e2ab90
> <0xfee4da36 xfrm=AES_CBC_256-HMAC_SHA2_256_128 NATOA=none NATD=223.167.21.244:43383 DPD=active username=vpnuser}
> Oct 30 18:25:38 pluto[1240125]: "xauth-psk"[5673] 223.167.21.244 #7766: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP/NAT=>0x06e2ab90 <0xfee4da36
> xfrm=AES_CBC_256-HMAC_SHA2_256_128 NATOA=none NATD=223.167.21.244:43383 DPD=active username=vpnuser}
> Oct 30 18:25:38 sshd[1350417]: Received disconnect from 138.197.66.68 port 33441:11: Bye Bye [preauth]
> Oct 30 18:25:38 sshd[1350417]: Disconnected from authenticating user root 138.197.66.68 port 33441 [preauth]

> Oct 30 18:26:12 pluto[1240125]: "xauth-psk"[5647] 80.195.100.226 #7731: DPD action - clearing connection kind CK_INSTANCE
> Oct 30 18:26:12 pluto[1240125]: "xauth-psk"[5647] 80.195.100.226 #7732: deleting state (STATE_QUICK_R2) aged 337.829s and sending notification
> Oct 30 18:26:12 pluto[1240125]: "xauth-psk"[5647] 80.195.100.226 #7732: ESP traffic information: in=34KB out=0B XAUTHuser=vpnuser
> Oct 30 18:26:12 pluto[1240125]: "xauth-psk"[5647] 80.195.100.226 #7731: deleting state (STATE_MODE_CFG_R1) aged 338.966s and sending notification
> Oct 30 18:26:12 pluto[1240125]: "xauth-psk"[5647] 80.195.100.226: deleting connection "xauth-psk"[5647] 80.195.100.226 instance with peer 80.195.100.226 {isakmp=#0/ipsec=#0}

Nothing bad shows up here. Just connections coming and going ?

Paul
