### ISSUE TITLE
Authentication parameter

### ISSUE THREAD

**Issue by Ribo01** [libreswan/libreswan#379]
hey guys, 

I will be glad if someone can help check my configuration and possibly advise if I am doing something wrong. 

So basically, I am trying to connect to another site, below are the connection info supplied to me.

> Authentication: ESP/MD5/HMAC-256 , Encryption : AES-256, IKE proposal : IKE-SHA2-256, Diffie-hellman Group: 5

my own config 

> ike = aes256-sha2; modp4096

I tried to add the authentication using "md5" to my IKE string, but I get an error. if I do the below, 

> ike = aes256-sha2; modp4096; md5

I  have 2 questions 
1) how do I add the authentication string
2) the only thing missing in my connection is the authentication right?

**Comment by letoams** [comment]
DiffieHellman group 5 is modp1536, not modp4096

so you want:
ike=aes256-sha2;modp1536
esp=aes256-md5
likely also: ikev2=no

It's a dubious configuration by the way. There is no gain in using MD5 for ESP
