### ISSUE TITLE
ipsec service fails to start --checknss failure

### ISSUE THREAD

**Issue by StuTheBearded** [libreswan/libreswan#380]
I'm using Fedora 32 and the ipsec service fails to start, this is from the their provided package fresh install. Fedora 33 also has the same problem, hence the down grade. I have the directory /var/lib/ipsec/nss and it contains *.db files, i've even deleted them and initialised new ones.

    ExecStartPre=/usr/sbin/ipsec --checknss (code=exited, status=1/FAILURE)

If I run sudo ipsec --checknss in terminal I don't get any errors. Below is the output from systemd

    ● ipsec.service - Internet Key Exchange (IKE) Protocol Daemon for IPsec
         Loaded: loaded (/usr/lib/systemd/system/ipsec.service; disabled; vendor preset: disabled)
         Active: failed (Result: exit-code) since Fri 2020-11-06 10:00:51 GMT; 4s ago
           Docs: man:ipsec(8)
                 man:pluto(8)
                 man:ipsec.conf(5)
        Process: 7298 ExecStartPre=/usr/libexec/ipsec/addconn --config /etc/ipsec.conf --checkconfig (code=exited, status=0/SUCCESS)
        Process: 7299 ExecStartPre=/usr/libexec/ipsec/_stackmanager start (code=exited, status=0/SUCCESS)
        Process: 7538 ExecStartPre=/usr/sbin/ipsec --checknss (code=exited, status=1/FAILURE)
        Process: 7539 ExecStopPost=/sbin/ip xfrm policy flush (code=exited, status=0/SUCCESS)
        Process: 7540 ExecStopPost=/sbin/ip xfrm state flush (code=exited, status=0/SUCCESS)
        Process: 7541 ExecStopPost=/usr/sbin/ipsec --stopnflog (code=exited, status=0/SUCCESS)
            CPU: 235ms

    Nov 06 10:00:51 localhost-live.lan systemd[1]: ipsec.service: Scheduled restart job, restart counter is at 5.
    Nov 06 10:00:51 localhost-live.lan systemd[1]: Stopped Internet Key Exchange (IKE) Protocol Daemon for IPsec.
    Nov 06 10:00:51 localhost-live.lan systemd[1]: ipsec.service: Start request repeated too quickly.
    Nov 06 10:00:51 localhost-live.lan systemd[1]: ipsec.service: Failed with result 'exit-code'.
    Nov 06 10:00:51 localhost-live.lan systemd[1]: Failed to start Internet Key Exchange (IKE) Protocol Daemon for IPsec.

**Comment by bleve** [comment]
Check selinux context of /var/lib/ipsec/nss with ls -Z

Should be system_u:object_r:ipsec_key_file_t:s0

If it is some other type, please add your comment to https://bugzilla.redhat.com/show_bug.cgi?id=1883666

As a temporary work-around you can

semanage fcontext --add --type ipsec_key_file_t '/var/lib/ipsec(/.*)?'
restorecon -rv /var/lib/ipsec

**Comment by StuTheBearded** [comment]
Mine are showing as:

unconfined_u:object_r:var_lib_t:s0 cert9.db  
unconfined_u:object_r:var_lib_t:s0 key4.db  
unconfined_u:object_r:var_lib_t:s0 pkcs11.txt

What does your workaround do and when fedora solve the problem will need to undo this? 
Sorry SELinux is an overly abstruse mystery i've never fancied unravelling.

**Comment by bleve** [comment]
After fedora fixes selinux policy you need to delete your work-around:

semanage fcontext --delete --type ipsec_key_file_t '/var/lib/ipsec(/.*)?'

**Comment by StuTheBearded** [comment]
Thanks, I've used the work around and I'm able to use my VPN connection again.

**Comment by letoams** [comment]
On Fri, 6 Nov 2020, StuTheBearded wrote:

> Subject: [libreswan/libreswan] ipsec service fails to start --checknss failure
>      (#380)

Another workaround is adding nssdir=/etc/ipsec.d into /etc/ipsec.conf in "config setup"

Paul

**Comment by bleve** [comment]
Sorry. That won't help because checknss will still fail.

**Comment by ostiwe** [comment]
> Sorry. That won't help because checknss will still fail.
> 
> You'd also need to add --nssdir /etc/ipsec.d to ipsec --checknss command line in ipsec.service so override that line in ipsec.service.

Adding --ns dir /etc/ipsec. d to ipsec. service helped me, thank you

**Comment by letoams** [comment]
this issue should be resolved in current releases

**Comment by vaknin** [comment]
The issue is closed, yet I have just ran into it again, ran the following as a workaround according to [this](https://bugzilla.redhat.com/show_bug.cgi?id=1889538):
mkdir -p /var/lib/ipsec/nss
