### ISSUE TITLE
VPN connection error libreswan

### ISSUE THREAD

**Issue by Ribo01** [libreswan/libreswan#381]
Hi Guys can anyone be so kind to explaining the errors below to me when  try to initiate a VPN connection ? particularly the second line 

> esp-hw-offload not supported by kernel 

> 
 adding interface eth0/eth0 178.***.***.***:4500
Nov 06 18:10:52 abc pluto[10936]: adding interface lo/lo (esp-hw-offload not supported by kernel) 127.0.0.1:500
Nov 06 18:10:52 abc pluto[10936]: adding interface lo/lo 127.0.0.1:4500
Nov 06 18:10:52 abc pluto[10936]: adding interface lo/lo (esp-hw-offload not supported by kernel) [::1]:500
Nov 06 18:10:52 abc pluto[10936]: loading secrets from "/etc/ipsec.secrets"
Nov 06 18:10:52 abc pluto[10936]: "abc-conn" #1: initiating Main Mode
Nov 06 18:10:52 abc pluto[10936]: "abc-conn" #1: STATE_MAIN_I1: sent MI1, expecting MR1
Nov 06 18:10:53 abc pluto[10936]: "abc-conn" #1: STATE_MAIN_I1: retransmission; will wait 0.5 seconds for response
Nov 06 18:10:53 abc pluto[10936]: "abc-conn" #1: STATE_MAIN_I1: retransmission; will wait 1 seconds for response

can this be a reason for my in-ability to connect?

I would appreciate all guide i can get

Thanks in advance

**Comment by letoams** [comment]
Your first packet is sent and receives no answer. Either there is a local firewall, a firewall on the network, or the remote peer does not like your initial packet and refuses to sent an error. Usually it means a firewall is blocking UDP port 500 and/or 4500 though
