### ISSUE TITLE
[QUESTION] - How DH is handled in esp/ah= proposals

### ISSUE THREAD

**Issue by vardias** [libreswan/libreswan#384]
Hello,

I am confused regarding on how DH is handled in esp/ah= proposals and the documentation.

I can see in the changelog (https://download.libreswan.org/CHANGES) for version 3.25 that: "No longer allow contradicting esp= and pfs= options".
After a lot of digging, I found that: before libreswan 3.25 version when you specify the DH in an ESP/AH proposal with the pfs enabled then you could put at the end of a list of ESP/AH proposals and that was interpreted as applying to all the proposals.No errors reported.
After the libreswan version 3.25 you get the error: "either all or none of the ESP/AH proposal explicitly specify DH"
(https://lists.libreswan.org/pipermail/swan-dev/2018-April/002364.html)

I tried it myself:

EXAMPLES:
**Version 3.25**
sh-4.2# ipsec version
Linux Libreswan 3.25 (netkey) on 3.10.0-862.14.4.el7.x86_64
sh-4.2# cat foo.conf 
conn foo                                                                                                                          
    left=XXX                                                                                                                                          
    right=XXX                                                                                                                                  
    ikev2=no
    ike=aes_cbc256-sha2_512,aes_cbc256-sha2_512;dh24
    phase2=esp
    **phase2alg=3des-md5,aes256-sha1;modp2048**
    type=tunnel
    authby=secret
    pfs=yes
sh-4.2# ipsec auto --add foo
036 Failed to add connection "foo", esp="3des-md5,aes256-sha1;modp2048" is invalid: either all or no ESP proposals should specify DH

**Version 3.23**
sh-4.2# ipsec version
Linux Libreswan 3.23 (netkey) on 3.10.0-862.14.4.el7.x86_64
sh-4.2# cat foo.conf 
conn foo
    left=XXX
    right=XXX
    ikev2=no
    ike=aes_cbc256-sha2_512;dh23,aes_cbc256-sha2_512;dh24
    phase2=esp
    **phase2alg=3des-md5,aes256-sha1;modp2048**
    type=tunnel
    authby=secret
    pfs=yes
sh-4.2# ipsec auto --add foo
002 added connection description "foo"

But in the documentation (https://libreswan.org/man/ipsec.conf.5.html) it says:
'The format for ESP is ENC-AUTH followed by one optional PFSgroup. For instance, "3des-md5" or "aes256-sha1;modp2048" or "aes-sha1,aes-md5". **When specifying multiple algorithms, specify the PFSgroup last**, e.g. "**3des-md5,aes256-sha1;modp2048**"'

Which clearly doesn't work in 3.25 release.
Is the documentation wrong? Am I missing something?

Regards,
Marc

**Comment by cagney** [comment]
Try:
  phase2alg=3des-md5;modp2048,aes256-sha1;modp2048
I see the documentation was updated:

           The format for ESP is ENC-AUTH followed by one optional PFSgroup.
           For instance, "aes_gcm256" or "aes256-sha2_512-dh14" or
           "aes-sha2_512+sha2_256". When specifying multiple algorithms,
           specify the PFSgroup last, e.g.
           "aes128+aes256-sha2_512+sha2_256-dh14+dh19".

As an aside, it is generally better to not specify the DH algorithm and instead let the DH algorithm negotiated during IKE be reused:
- the first child uses keys derived from the IKE DH exchange anyway
- the other end is known to support the algorithm
- no problems with changing key strength during a re-key

**Comment by vardias** [comment]
Hello,
Thank you for your reply.
Yes, you are correct, I tried the combination you mentioned and it is working just fine.
I also understand the recommendation not to specify the DH algorithm.
My question was about the phrase in the documentation where the PFSgroup should be specified last when specifying multiple algorithms which I think it is not true.
Regards,
Marc
