### ISSUE TITLE
[Question] Safe way to kill pluto and maintain SAs

### ISSUE THREAD

**Issue by markdgray** [libreswan/libreswan#385]
Is there a "safe" way to stop pluto but maintain SAs so that encrypted traffic can continue flowing until pluto is started again? I seem to be able to kill pluto and this works but not sure how safe this is?

**Comment by letoams** [comment]
Not yet, but we are adding a function to do that. Note there will always be a race condition if you do this so it’s worth considering why you are restarting pluto abd perhaps not doing that :)

Paul

**Comment by markdgray** [comment]
What is the race condition? Perhaps I can avoid it. 

Currently libreswan is containerized so maybe we need to move it to the host but if there was a temporary workaround, that would be ideal.

**Comment by letoams** [comment]
On Tue, 1 Dec 2020, Mark Gray wrote:

> What is the race condition? Perhaps I can avoid it.

When the IKE daemon starts, the init system file will wipe all the
IPsec SA's from the kernel to ensure that pluto's view of
the kernel IPsec state matches reality.

The original request was for when the machine is rebooted. During
shutdown, pluto could then leave the kernel policies in place for
a bit longer, until the kernel itself reboots.

If you are doing it when only restarting pluto, then the window
of this gain is smaller. Between the pluto daemon stopping and
starting is only like a second of time - maybe a few seconds
when you have many tunnels.

> Currently libreswan is containerized so maybe we need to move it to the host but if there was a temporary workaround, that would be
> ideal.

Perhaps start with explaining why you think you need to restart
libreswan?

Paul

**Comment by markdgray** [comment]
I'll need to restart pluto during upgrades as the container will restart. Perhaps I could also move it to the host.

However this may not be a problem as, in my case, I have a daemon in OVS that recreates the correct state - it is the only entity configuring libreswan. In that case, if I kill pluto, when I restart, the OVS daemon should restablish the connections. Also, it should be noted that it is highly like any of the connections will actually ever change.

**Comment by letoams** [comment]
On Tue, 1 Dec 2020, Mark Gray wrote:

This is now implemented in https://github.com/libreswan/libreswan/commit/2a293444d18f4098b302a731bb18aee62f6a7217

Note that it will still need support from systemd's ipsec.service file
so that ExecStopPost won't still wipe the state anyway.

**Comment by letoams** [comment]
systemd support implemented in https://github.com/libreswan/libreswan/commit/bd028fdd7b78ff976c1b415ee14859c8b281dd2d

will be released in libreswan 4.2
