### ISSUE TITLE
EXPECTATION_FAILED during rekeying event

### ISSUE THREAD

**Issue by markdgray** [libreswan/libreswan#386]
Hi,

I am getting an "EXPECTATION FAILED" message when rekeying is taking place between two pluto instances.
```
ec  8 09:55:52.656092: "ovn-5c0af8-0-in-1" #110: IKEv2 mode peer ID is ID_FQDN: '@5c0af8c8-3baa-4401-93c2-b0a0bea3b2b4'
Dec  8 09:55:52.656191: "ovn-5c0af8-0-in-1" #110: Authenticated using RSA with IKEv2_AUTH_HASH_SHA2_512
Dec  8 09:55:52.666725: "ovn-5c0af8-0-in-1" #110: negotiated connection [10.0.158.77-10.0.158.77:6081-6081 17] -> [10.0.249.185-10.0.249.185:0-65535 17]
Dec  8 09:55:52.666745: "ovn-5c0af8-0-in-1" #110: STATE_V2_IPSEC_I: IPsec SA established transport mode {ESP=>0xfbf96ff2 <0x860b26a6 xfrm=AES_GCM_16_256-NONE NATOA=none NATD=none DPD=passive}
Dec  8 10:45:42.658681: "ovn-5c0af8-0-in-1" #108: initiate rekey of IKEv2 CREATE_CHILD_SA IKE Rekey
Dec  8 10:45:42.660158: "ovn-5c0af8-0-in-1" #159: STATE_V2_REKEY_IKE_I: STATE_V2_REKEY_IKE_I
Dec  8 10:45:42.664813: "ovn-5c0af8-0-in-1" #159: rekeyed #108 STATE_V2_REKEY_IKE_I and expire it remaining life 608s
Dec  8 10:45:42.664906: "ovn-5c0af8-0-in-1" #159: STATE_PARENT_I3: PARENT SA established
Dec  8 10:45:43.665840: "ovn-5c0af8-0-in-1" #108: deleting state (STATE_PARENT_I3) aged 2991.052s and sending notification
Dec  8 10:55:52.685197: "ovn-5c0af8-0-in-1" #173: proposal 1:IKE=AES_GCM_C_256-HMAC_SHA2_256-MODP2048 chosen from remote proposals 1:IKE:ENCR=AES_GCM_C_256;PRF=HMAC_SHA2_256;DH=MODP2048;DH=MODP3072;DH=MODP4096;DH=MODP8192;DH=ECP_256;DH=ECP_384;DH=ECP_521;DH=CURVE25519[first-match]
Dec  8 10:55:52.687221: "ovn-5c0af8-0-in-1" #173: STATE_PARENT_R1: received v2I1, sent v2R1 {auth=IKEv2 cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_256 group=MODP2048}
Dec  8 10:55:52.694011: "ovn-5c0af8-0-in-1" #173: processing decrypted IKE_AUTH request: SK{IDi,CERT,CERTREQ,IDr,AUTH,SA,TSi,TSr,N}
Dec  8 10:55:52.694911: "ovn-5c0af8-0-in-1" #173: certificate verified OK: CN=5c0af8c8-3baa-4401-93c2-b0a0bea3b2b4,OU=kind,O=ovnkubernetes,C=US
Dec  8 10:55:52.695105: "ovn-5c0af8-0-in-1" #173: IKEv2 mode peer ID is ID_FQDN: '@5c0af8c8-3baa-4401-93c2-b0a0bea3b2b4'
Dec  8 10:55:52.695200: "ovn-5c0af8-0-in-1" #173: Authenticated using RSA with IKEv2_AUTH_HASH_SHA2_512
Dec  8 10:55:52.698000: "ovn-5c0af8-0-in-1" #173: proposal 1:ESP=AES_GCM_C_256-DISABLED SPI=c9f5d926 chosen from remote proposals 1:ESP:ENCR=AES_GCM_C_256;ESN=DISABLED[first-match]
Dec  8 11:30:58.680691: "ovn-5c0af8-0-in-1" #159: EXPECTATION FAILED: not replacing stale IKE SA #159; as already got a newer #173 (in v2_event_sa_rekey() at ikev2_parent.c:6377)
Dec  8 11:30:58.680737: "ovn-5c0af8-0-in-1" #110: deleting other state #110 (STATE_V2_IPSEC_I) aged 5706.047s and sending notification
Dec  8 11:30:58.680768: "ovn-5c0af8-0-in-1" #110: ESP traffic information: in=9MB out=0B
Dec  8 11:30:58.691910: "ovn-5c0af8-0-in-1" #159: deleting state (STATE_PARENT_I3) aged 2716.033s and sending notification
Dec  8 11:51:22.693787: "ovn-5c0af8-0-in-1" #173: initiate rekey of IKEv2 CREATE_CHILD_SA IKE Rekey
Dec  8 11:51:22.695279: "ovn-5c0af8-0-in-1" #193: STATE_V2_REKEY_IKE_I: STATE_V2_REKEY_IKE_I
Dec  8 11:51:22.702607: "ovn-5c0af8-0-in-1" #193: rekeyed #173 STATE_V2_REKEY_IKE_I and expire it remaining life 269s
Dec  8 11:51:22.702722: "ovn-5c0af8-0-in-1" #193: STATE_PARENT_I3: PARENT SA established
```

On the remote side, I see multiple retransmissions:

```1;DH=CURVE25519[first-match]
Dec  8 09:55:52.631990: "ovn-7e368c-0-out-1" #116: STATE_PARENT_R1: received v2I1, sent v2R1 {auth=IKEv2 cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_256 group=MODP2048}
Dec  8 09:55:52.637690: "ovn-7e368c-0-out-1" #116: processing decrypted IKE_AUTH request: SK{IDi,CERT,CERTREQ,IDr,AUTH,SA,TSi,TSr,N}
Dec  8 09:55:52.638460: "ovn-7e368c-0-out-1" #116: certificate verified OK: CN=7e368cd5-4b6a-4a1d-a3b0-2bbb340179f8,OU=kind,O=ovnkubernetes,C=US
Dec  8 09:55:52.638650: "ovn-7e368c-0-out-1" #116: IKEv2 mode peer ID is ID_FQDN: '@7e368cd5-4b6a-4a1d-a3b0-2bbb340179f8'
Dec  8 09:55:52.638754: "ovn-7e368c-0-out-1" #116: Authenticated using RSA with IKEv2_AUTH_HASH_SHA2_512
Dec  8 09:55:52.641700: "ovn-7e368c-0-out-1" #116: proposal 1:ESP=AES_GCM_C_256-DISABLED SPI=860b26a6 chosen from remote proposals 1:ESP:ENCR=AES_GCM_C_256;ESN=DISABLED[first-match]
Dec  8 09:55:52.654597: "ovn-7e368c-0-out-1" #118: negotiated connection [10.0.249.185-10.0.249.185:0-65535 17] -> [10.0.158.77-10.0.158.77:6081-6081 17]
Dec  8 09:55:52.654614: "ovn-7e368c-0-out-1" #118: STATE_V2_IPSEC_R: IPsec SA established transport mode {ESP=>0x860b26a6 <0xfbf96ff2 xfrm=AES_GCM_16_256-NONE NATOA=none NATD=none DPD=passive}
Dec  8 10:45:42.660800: "ovn-7e368c-0-out-1" #116: proposal 1:IKE=AES_GCM_C_256-HMAC_SHA2_256-MODP2048 SPI=7dd04d55a72c40ed chosen from remote proposals 1:IKE:ENCR=AES_GCM_C_256;PRF=HMAC_SHA2_256;DH=MODP2048;DH=MODP3072;DH=MODP4096;DH=MODP8192;DH=ECP_256
;DH=ECP_384;DH=ECP_521;DH=CURVE25519[first-match]
Dec  8 10:45:42.663410: "ovn-7e368c-0-out-1" #130: STATE_PARENT_R2: received v2I2, PARENT SA established
Dec  8 10:45:43.666629: "ovn-7e368c-0-out-1" #116: deleting state (STATE_IKESA_DEL) aged 2991.036s and NOT sending notification
Dec  8 10:55:53.163419: "ovn-7e368c-0-out-1" #148: proposal 1:IKE=AES_GCM_C_256-HMAC_SHA2_256-MODP2048 chosen from remote proposals 1:IKE:ENCR=AES_GCM_C_256;PRF=HMAC_SHA2_256;DH=MODP2048;DH=MODP3072;DH=MODP4096;DH=MODP8192;DH=ECP_256;DH=ECP_384;DH=ECP_52
1;DH=CURVE25519[first-match]
Dec  8 10:55:53.165513: "ovn-7e368c-0-out-1" #148: STATE_PARENT_R1: received v2I1, sent v2R1 {auth=IKEv2 cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_256 group=MODP2048}
Dec  8 10:59:13.179380: "ovn-7e368c-0-out-1" #148: deleting incomplete state after 200.000 seconds
Dec  8 10:59:13.179413: "ovn-7e368c-0-out-1" #148: deleting state (STATE_PARENT_R1) aged 200.016s and NOT sending notification
Dec  8 10:59:13.179420: "ovn-7e368c-0-out-1" #148: deleting IKE SA but connection is supposed to remain up; schedule EVENT_REVIVE_CONNS
Dec  8 10:59:13.179465: "ovn-7e368c-0-out-1": initiating connection which received a Delete/Notify but must remain up per local policy
Dec  8 10:59:13.179494: "ovn-7e368c-0-out-1": local ESP/AH proposals (ESP/AH initiator emitting proposals): 
Dec  8 10:59:13.179501: "ovn-7e368c-0-out-1":   1:ESP=AES_GCM_C_256-NONE-MODP2048-DISABLED
Dec  8 10:59:13.181026: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: sent IPsec Child req wait response
Dec  8 10:59:13.681379: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 0.5 seconds for response
Dec  8 10:59:14.181743: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 1 seconds for response
Dec  8 10:59:15.182397: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 2 seconds for response
Dec  8 10:59:17.183477: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 4 seconds for response
Dec  8 10:59:21.186392: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 8 seconds for response
Dec  8 10:59:29.194386: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 16 seconds for response
Dec  8 10:59:45.196962: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 32 seconds for response
Dec  8 11:00:17.215379: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: 60 second timeout exceeded after 7 retransmits.  No response (or no acceptable response) to our IKEv2 message
Dec  8 11:00:17.215410: "ovn-7e368c-0-out-1" #150: starting keying attempt 2 of an unlimited number
Dec  8 11:00:17.215437: "ovn-7e368c-0-out-1" #150: deleting state (STATE_V2_CREATE_I) aged 64.035s and NOT sending notification
Dec  8 11:41:12.667700: "ovn-7e368c-0-out-1" #130: initiate rekey of IKEv2 CREATE_CHILD_SA IKE Rekey
Dec  8 11:41:12.669247: "ovn-7e368c-0-out-1" #157: STATE_V2_REKEY_IKE_I: STATE_V2_REKEY_IKE_I
Dec  8 11:41:13.169405: "ovn-7e368c-0-out-1" #157: STATE_V2_REKEY_IKE_I: retransmission; will wait 0.5 seconds for response
Dec  8 11:41:13.669658: "ovn-7e368c-0-out-1" #157: STATE_V2_REKEY_IKE_I: retransmission; will wait 1 seconds for response
Dec  8 11:41:14.670391: "ovn-7e368c-0-out-1" #157: STATE_V2_REKEY_IKE_I: retransmission; will wait 2 seconds for response
...
...
...
```

Do you have any idea what could cause this?

**Comment by letoams** [comment]
On Tue, 8 Dec 2020, Mark Gray wrote:

> I am getting an "EXPECTATION_FAILED" message when rekeying is taking place between two pluto instances.

> Dec  8 10:55:52.698000: "ovn-5c0af8-0-in-1" #173: proposal 1:ESP=AES_GCM_C_256-DISABLED SPI=c9f5d926 chosen from remote proposals 1:ESP:ENCR=AES_GCM_C_2
> 56;ESN=DISABLED[first-match]
> Dec  8 11:30:58.680691: "ovn-5c0af8-0-in-1" #159: EXPECTATION FAILED: not replacing stale IKE SA #159; as already got a newer #173 (in v2_event_sa_rekey
> () at ikev2_parent.c:6377)

Looks like some unexpected simultanious rekeying is happening. It
_should_ be harmless. But....

> Dec  8 11:51:22.693787: "ovn-5c0af8-0-in-1" #173: initiate rekey of IKEv2 CREATE_CHILD_SA IKE Rekey
> Dec  8 11:51:22.695279: "ovn-5c0af8-0-in-1" #193: STATE_V2_REKEY_IKE_I: STATE_V2_REKEY_IKE_I
> Dec  8 11:51:22.702607: "ovn-5c0af8-0-in-1" #193: rekeyed #173 STATE_V2_REKEY_IKE_I and expire it remaining life 269s
> Dec  8 11:51:22.702722: "ovn-5c0af8-0-in-1" #193: STATE_PARENT_I3: PARENT SA established

Looks like an okay IKE SA rekey.

> On the remote side, I see multiple retransmissions:

> Dec  8 10:59:13.181026: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: sent IPsec Child req wait response
> Dec  8 10:59:13.681379: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 0.5 seconds for response
> Dec  8 10:59:14.181743: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 1 seconds for response
> Dec  8 10:59:15.182397: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 2 seconds for response
> Dec  8 10:59:17.183477: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 4 seconds for response
> Dec  8 10:59:21.186392: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 8 seconds for response
> Dec  8 10:59:29.194386: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 16 seconds for response
> Dec  8 10:59:45.196962: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 32 seconds for response
> Dec  8 11:00:17.215379: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: 60 second timeout exceeded after 7 retransmits.  No response (or no acceptable res
> ponse) to our IKEv2 message
> Dec  8 11:00:17.215410: "ovn-7e368c-0-out-1" #150: starting keying attempt 2 of an unlimited number
> Dec  8 11:00:17.215437: "ovn-7e368c-0-out-1" #150: deleting state (STATE_V2_CREATE_I) aged 64.035s and NOT sending notification
> Dec  8 11:41:12.667700: "ovn-7e368c-0-out-1" #130: initiate rekey of IKEv2 CREATE_CHILD_SA IKE Rekey
> Dec  8 11:41:12.669247: "ovn-7e368c-0-out-1" #157: STATE_V2_REKEY_IKE_I: STATE_V2_REKEY_IKE_I
> Dec  8 11:41:13.169405: "ovn-7e368c-0-out-1" #157: STATE_V2_REKEY_IKE_I: retransmission; will wait 0.5 seconds for response
> Dec  8 11:41:13.669658: "ovn-7e368c-0-out-1" #157: STATE_V2_REKEY_IKE_I: retransmission; will wait 1 seconds for response
> Dec  8 11:41:14.670391: "ovn-7e368c-0-out-1" #157: STATE_V2_REKEY_IKE_I: retransmission; will wait 2 seconds for response

This seems to have failed. Did another state manage to bring that
connection up? Or did you have a connectivity issue now?

Paul

**Comment by markdgray** [comment]
On 10/12/2020 03:55, Paul Wouters wrote:
> On Tue, 8 Dec 2020, Mark Gray wrote:
> 
>> I am getting an "EXPECTATION_FAILED" message when rekeying is taking place between two pluto instances.
> 
>> Dec  8 10:55:52.698000: "ovn-5c0af8-0-in-1" #173: proposal 1:ESP=AES_GCM_C_256-DISABLED SPI=c9f5d926 chosen from remote proposals 1:ESP:ENCR=AES_GCM_C_2
>> 56;ESN=DISABLED[first-match]
>> Dec  8 11:30:58.680691: "ovn-5c0af8-0-in-1" #159: EXPECTATION FAILED: not replacing stale IKE SA #159; as already got a newer #173 (in v2_event_sa_rekey
>> () at ikev2_parent.c:6377)
> 
> Looks like some unexpected simultanious rekeying is happening. It
> _should_ be harmless. But....


What would cause that? Is it just a timing thing (i.e. they happen to
rekey at the same time). All of these pluto instances start at roughly
the same time.
> 
>> Dec  8 11:51:22.693787: "ovn-5c0af8-0-in-1" #173: initiate rekey of IKEv2 CREATE_CHILD_SA IKE Rekey
>> Dec  8 11:51:22.695279: "ovn-5c0af8-0-in-1" #193: STATE_V2_REKEY_IKE_I: STATE_V2_REKEY_IKE_I
>> Dec  8 11:51:22.702607: "ovn-5c0af8-0-in-1" #193: rekeyed #173 STATE_V2_REKEY_IKE_I and expire it remaining life 269s
>> Dec  8 11:51:22.702722: "ovn-5c0af8-0-in-1" #193: STATE_PARENT_I3: PARENT SA established
> 
> Looks like an okay IKE SA rekey.

Is there a good document for understanding each of these states?
> 
>> On the remote side, I see multiple retransmissions:
> 
>> Dec  8 10:59:13.181026: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: sent IPsec Child req wait response
>> Dec  8 10:59:13.681379: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 0.5 seconds for response
>> Dec  8 10:59:14.181743: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 1 seconds for response
>> Dec  8 10:59:15.182397: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 2 seconds for response
>> Dec  8 10:59:17.183477: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 4 seconds for response
>> Dec  8 10:59:21.186392: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 8 seconds for response
>> Dec  8 10:59:29.194386: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 16 seconds for response
>> Dec  8 10:59:45.196962: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: retransmission; will wait 32 seconds for response
>> Dec  8 11:00:17.215379: "ovn-7e368c-0-out-1" #150: STATE_V2_CREATE_I: 60 second timeout exceeded after 7 retransmits.  No response (or no acceptable res
>> ponse) to our IKEv2 message
>> Dec  8 11:00:17.215410: "ovn-7e368c-0-out-1" #150: starting keying attempt 2 of an unlimited number
>> Dec  8 11:00:17.215437: "ovn-7e368c-0-out-1" #150: deleting state (STATE_V2_CREATE_I) aged 64.035s and NOT sending notification
>> Dec  8 11:41:12.667700: "ovn-7e368c-0-out-1" #130: initiate rekey of IKEv2 CREATE_CHILD_SA IKE Rekey
>> Dec  8 11:41:12.669247: "ovn-7e368c-0-out-1" #157: STATE_V2_REKEY_IKE_I: STATE_V2_REKEY_IKE_I
>> Dec  8 11:41:13.169405: "ovn-7e368c-0-out-1" #157: STATE_V2_REKEY_IKE_I: retransmission; will wait 0.5 seconds for response
>> Dec  8 11:41:13.669658: "ovn-7e368c-0-out-1" #157: STATE_V2_REKEY_IKE_I: retransmission; will wait 1 seconds for response
>> Dec  8 11:41:14.670391: "ovn-7e368c-0-out-1" #157: STATE_V2_REKEY_IKE_I: retransmission; will wait 2 seconds for response
> 
> This seems to have failed. Did another state manage to bring that
> connection up? Or did you have a connectivity issue now?

My gut feeling is connectivity at the moment but I am not 100% sure.

Another thing I am seeing on a different host is

```Dec  8 08:53:53.001116: "ovn-c5ae5a-0-in-1" #67: deleting state
(STATE_V2_CREATE_I) aged 0.165s and NOT sending notification
Dec  8 08:53:53.001380: "ovn-c5ae5a-0-in-1" #67: ERROR: netlink response
for Del SA [esp.d3a942f2@10.0.175.190](mailto:esp.d3a942f2@10.0.175.190)
included errno 3: No such process
Dec  8 08:53:53.001511: packet from 10.0.175.190:500:
ISAKMP_v2_INFORMATIONAL message response has no matching IKE SA
Dec  8 08:53:53.001533: packet from 10.0.175.190:500:
ISAKMP_v2_INFORMATIONAL message response has no matching IKE SA
Dec  8 08:53:53.004614: "ovn-b03cff-0-out-1" #69: STATE_```

This looks like the xfrm state has been removed from underneath me but I
am unsure what could cause this. I thought that if the IP address was
deleted from an interface it may cause the state to be removed but this
is not the case (I tried to do that myself)
> 
> Paul
> 
>

**Comment by letoams** [comment]
On Thu, 10 Dec 2020, Mark Gray wrote:

> > Looks like some unexpected simultanious rekeying is happening. It
> > _should_ be harmless. But....
> 
> 
> What would cause that? Is it just a timing thing (i.e. they happen to
> rekey at the same time). All of these pluto instances start at roughly
> the same time.

Yes that could be the reason. If it all starts up at once, and all ends
initiate to all ends, there will be some overlapping exchanges, that
need to fizzle out. Normally you have:

Host A			Host B
 	--> IKE_INIT req
 	<-- IKE_INIT reply
 	--> IKE_AUTH req
 	<-- IKE_AUTH reply

and then one connection is up. If both ends start at once you can get:

Host A			Host B
 	--> IKE_INIT req
 	<-- IKE_INIT req
 	--> IKE_INIT reply
 	<-- IKE_INIT reply
 	--> IKE_AUTH req
 	<-- IKE_AUTH req
 	--> IKE_AUTH reply

one connection is now up

 	<-- IKE_AUTH reply

second connection is now up (should cause first one to be deleted)

Something similar can happen during rekeys. We add some fuzz to the
timings to prevent this, but it can still happen.

> Is there a good document for understanding each of these states?

Not really. See RFC 7296. The I states are initiator states, the R
states are responder states. PARENT refers to IKE, and Child refers
to IPsec. CREATE refers to CREATE_CHILD_SA exchange (used for rekeying)

But in recent versions we removed naming the STATE_ completely in user
output. So you wouldn't see those in libreswan 4.x anymore.

> > This seems to have failed. Did another state manage to bring that
> > connection up? Or did you have a connectivity issue now?
> 
> My gut feeling is connectivity at the moment but I am not 100% sure.

My only concern is that routing changes due to VPN tunnels might be
responsible for this. Perhaps check "ip route" before and after the
tunnels are up to see if there is a wrong route somehow ?

> Another thing I am seeing on a different host is
> 
> ```Dec 8 08:53:53.001116: "ovn-c5ae5a-0-in-1" #67: deleting state
> (STATE_V2_CREATE_I) aged 0.165s and NOT sending notification
> Dec 8 08:53:53.001380: "ovn-c5ae5a-0-in-1" #67: ERROR: netlink response
> for Del SA [esp.d3a942f2@10.0.175.190](mailto:esp.d3a942f2@10.0.175.190)
> included errno 3: No such process
> Dec 8 08:53:53.001511: packet from 10.0.175.190:500:
> ISAKMP_v2_INFORMATIONAL message response has no matching IKE SA
> Dec 8 08:53:53.001533: packet from 10.0.175.190:500:
> ISAKMP_v2_INFORMATIONAL message response has no matching IKE SA
> Dec 8 08:53:53.004614: "ovn-b03cff-0-out-1" #69: STATE_```

This means that the IKE SA is no longer there. It can be that a delete
happened that caused us to delete the IKE SA and the reply to that
delete message cannot be read because it is already deleted. But that
should be visible as just above these messages you should see a delete
for that connection happening.

> This looks like the xfrm state has been removed from underneath me but I
> am unsure what could cause this. I thought that if the IP address was
> deleted from an interface it may cause the state to be removed but this
> is not the case (I tried to do that myself)

The error you quote does not relate to IPsec states or ip xfrm
state/policy. It specifically refers to an IKE informational message
coming in for which no established IKE SA is found to decrypt it.
It has nothing to do with IPsec (ESP, packet) encryption.

Paul

**Comment by markdgray** [comment]
I resolved this. We were unexpectedly (due to a bug in our code) deleting connections on one side of the connection. This was probably causing the unexpected rekeying. I haven't seen this message since this was fixed.
