### ISSUE TITLE
Radius 

### ISSUE THREAD

**Issue by masoudcom** [libreswan/libreswan#387]
I wanna connect to Radius Server.
Please help me

**Comment by letoams** [comment]
On Sun, 20 Dec 2020, masoudcom wrote:

> Subject: [libreswan/libreswan] Radius  (#387)

> I wanna connect to Radius Server.

We only support radius via the IKEv1 XAUTH/L2TP methods. We do not
support Radius via EAP as required for IKEv2.

Paul

**Comment by cagney** [comment]
Libreswan v4.7 supports EAPTLS.
