### ISSUE TITLE
VPN no longer works after upgrade to 4.1

### ISSUE THREAD

**Issue by sirex** [libreswan/libreswan#388]
Hi, I'm using Manjaro and have following packages installed:

> libreswan: 4.1-1
> networkmanager-libreswan: 1.2.12-2

And VPN no longer works. But with older libreswan 3.32 version, VPN works again.

So, something must have changed, that broke it.

My VPN configuration looks like this (`leftxauthusername` and `right` are changed):

    $ nmcli connection show ivpk
    [...]
    vpn.data:
        esp = aes128-sha1\,aes256-sha1,
        ike = aes128-sha1-modp1536\,aes256-sha256-modp1536,
        leftid = @none,
        leftxauthusername = name.surname,
        pskinputmodes = save,
        pskvalue-flags = 0,
        right = 0.0.0.0,
        xauthpassword-flags = 0,
        xauthpasswordinputmodes = save
    [...]

When I try to connect via NetworkManager, I get this:

    $ nmcli connection up ivpk
    Error: Connection activation failed: Unknown reason

    $ journalctl -xe
    [...]
    NetworkManager[84513]: cannot load config '-': -:13: syntax error [leftxauthusername]
    [...]

I'm using `leftid = @none` in order to enable IKEv1 in Aggressive Mode, because that is required by VPN server and VPN only starts to work if `leftid` is filled. Because as I understand, that how it is done by NetworkManager:

> So, when IKEv1 aggressive mode ('leftid' specified) is configured [...]
> https://github.com/NetworkManager/NetworkManager-libreswan/blob/479f640ebf980b434c570d12af68722748633367/shared/utils.c#L235

So I'm I doing something wrong, or something got broken in 4.1 version?

Link to AUR package, which mentions removal of `-DALLOW_MICROSOFT_BAD_PROPOSAL` (not sure if that is related): https://aur.archlinux.org/packages/libreswan/

**Comment by sirex** [comment]
By the way, the serve user FortiNet VPN: https://www.forticlient.com/

**Comment by letoams** [comment]
On Tue, 22 Dec 2020, Mantas Zimnickas wrote:

> Hi, I'm using Manjaro and have following packages installed:
>
>       libreswan: 4.1-1
>       networkmanager-libreswan: 1.2.12-2
> 
> And VPN no longer works. But with older libreswan 3.32 version, VPN works again.

This is an nss bug. 4.2rc1 was pushed into fedora to work around this.

Paul

**Comment by kmh14** [comment]
Unfortunately still not working for me
I tried with following versions:
> libreswan 4.2rc1-1
> networkmanager-libreswan 1.2.14-3

Unfortunatelly also not working with libreswan 4.2rc1

`mars pluto[3466]: loading secrets from "/etc/ipsec.d/ipsec-e9b9b92f-fe41-460b-a443-e4b5b5298ef4.secrets"`
`mars pluto[3466]: "e9b9b92f-fe41-460b-a443-e4b5b5298ef4": bad right --id: illegal (non-DNS-name) character in name (ignored)`
`mars pluto[3466]: "e9b9b92f-fe41-460b-a443-e4b5b5298ef4": added IKEv1 connection`
`mars NetworkManager[431]: <warn>  [1612278456.2545] vpn-connection[0x560df08462f0,e9b9b92f-fe41-460b-a443-e4b5b5298ef4,"VPN-Verbindung 1",0]: VPN plugin: failed: connect-failed`

Version libreswan-3.32 is working with the same connection-configuration

**Comment by letoams** [comment]
can you tell me what version of NetworkManager-libreswan you were using ?

**Comment by kmh14** [comment]
networkmanager-libreswan 1.2.14-3

**Comment by letoams** [comment]
This should be fixed with the libreswan-4.2 release. It's making its way into fedora now

**Comment by kmh14** [comment]
Thank you very much for the release. Working great now!
