### ISSUE TITLE
doc/nss-howto.txt still refers to /etc/ipsec.d as the NSS directory location -- should use /var/lib/ipsec/nss

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#391]
I think this is just a bit of cleanup that wasn't done when libreswan transitioned to using /var/lib/ipsec/nss as the default directory for NSS.

**Comment by letoams** [comment]
Thanks for the note. It also had some other obsoletes info in it , like secrets file entries for certificates which are not needed.
