### ISSUE TITLE
installation process of 4.1 (on debian at least) results in backup file newhostkey~ being installed in libexec

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#396]
I'm working around this in the debian packaging by -- after `make install` -- doing:

```
find $(CURDIR)/debian/libreswan -iname '*~' -ls -delete
```

and you can see the results in the build:

```
find /home/dkg/src/libreswan/libreswan/debian/libreswan -iname '*~' -ls -delete
  4815061      4 -rwxr-xr-x   1 dkg      dkg          2119 Jan 12 09:35 /home/dkg/src/libreswan/libreswan/debian/libreswan/usr/libexec/ipsec/newhostkey~
```

I don't see exactly what is creating this backup file, but you might want to check that it doesn't happen on other platforms (i'm happy to drop the cleanup workaround from debian once i'm sure it isn't recurring).

**Comment by cagney** [comment]
Funny.  Just got an e-mail about the same issue on NetBSD (only the suffix is .old).
The file is likely a backup from «install -b», I suspect the file was installed twice?

**Comment by letoams** [comment]
On Tue, 12 Jan 2021, cagney wrote:

> Funny. Just got an e-mail about the same issue on NetBSD (only the suffix is .old).
> The file is likely a backup from «install -b», I suspect the file was installed twice?

I'm very sure that is the case. I also have been seeing this for a long
time when running "make install" in /usr/local on my machines. I also
get the ~ files.

Paul

**Comment by cagney** [comment]
Wow, putting Fix ... in the commit, closes the bug ...

**Comment by letoams** [comment]
On Wed, 13 Jan 2021, cagney wrote:

> Wow, putting Fix ... in the commit, closes the bug ...

I use Resolves: but yes :)
