### ISSUE TITLE
use feature tests to determine defaults for USE_DH31, USE_NSS_KDF, and USE_NSS_IPSEC_PROFILE

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#399]
libreswan can use a bunch of different possible features of NSS.  The current implementation doesn't use `autoconf` or any other craziness like that, but it does a bunch of OS sniffing to try to guess whether to enable the different features.

This kind of sniffing (e.g. `$(shell grep -qE 'jessie' /etc/os-release)` or `ifeq ($(VERSION_CODENAME),jessie)`) can be kind of brittle -- not every installation of debian jessie actually has the same version of NSS -- particularly when it's under development, or handling backports, unusual architectures where a given version of NSS isn't supported yet, etc.

It would be better to have the default choice of whether to enable the feature be derived from an actual feature test.  You can use something like the following for `USE_DH31`, `USE_NSS_KDF`, and `USE_NSS_IPSEC_PROFILE` defaults:

```
USE_DH31 ?= $(shell if printf '#include <secoidt.h>\nint main() { return SEC_OID_CURVE25519; }' | $(CC) $(NSS_CFLAGS) -x c - -o /dev/null 2> /dev/null; then echo true; else echo false; fi)
USE_NSS_KDF ?= $(shell if printf '#include <pkcs11t.h>\n#include <pkcs11n.h>\nint main() { return sizeof(CK_NSS_IKE_PRF_DERIVE_PARAMS) > sizeof(CK_NSS_IKE1_APP_B_PRF_DERIVE_PARAMS); }' | $(CC) $(NSS_CFLAGS) -x c - -o /dev/null 2> /dev/null; then echo true; else echo false; fi)
USE_NSS_IPSEC_PROFILE = $(shell if printf '#include <certt.h>\nint main() { return certificateUsageIPsec; }' | $(CC) $(NSS_CFLAGS) -x c - -o /dev/null 2> /dev/null; then echo true; else echo false; fi)
```

with these changes to the defaults, you could probably strip a lot of other brittle guesswork (and i could drop these feature tests from the debian packaging, which would be a nice simplification).

**Comment by letoams** [comment]
You suggested something like this earlier that we also did not take in because it breaks cross compiling.

Paul

**Comment by dkg** [comment]
sorry for the repeated confusion, i don't remember the first time around: why does this test break cross-compiling? the test proposed above uses `$(CC)` and `$(NSS_CONFIG)` -- shouldn't those variables be appropriately set for cross-compilation?

**Comment by cagney** [comment]
> sorry for the repeated confusion, i don't remember the first time around: why does this test break cross-compiling? the test proposed above uses `$(CC)` and `$(NSS_CFLAGS)` -- shouldn't those variables be appropriately set for cross-compilation?

Better to spell out the desired configuration.  That way any mismatch between pluto's build requirements and the build environment result in a failed build rather than a a dysfunctional executable.

**Comment by dkg** [comment]
@cagney wrote:
> Better to spell out the desired configuration. That way any mismatch between pluto's build requirements and the build environment result in a failed build rather than a a dysfunctional executable.

This argument doesn't make sense to me.  My proposed changes don't in any way change the behavior when the builder explicitly specifies a build requirement.  They just auto-detect defaults that match the currently-available build environment.

For a user that wants to declare a build requirement, you'll still get a build-time failure.  For a user that doesn't care, and just wants whatever features they happen to have available, these patches will help them pick the right options without their having to do any extra work (or having to hard-code things that they might forget about later).

the libreswan source *already* tries to do such guessing for the defaults, but it does it in a more fragile/brittle way: by looking at the operating system/distro and version, and making guesses about what features might or might not be available in the version of nss that we expect to be on that version of that OS.  This can be simply wrong, for people building on an uncommon platform for that version, or for people who are running mixed systems, or for rolling distributions like debian unstable, or in versions of OSes that you don't know about (including versions that don't exist yet).

You can remove a lot of fiddly code that is boring to maintain by just using a feature test directly to choose the defaults.  The feature tests i've proposed run in less than a second, produce no side effects, and appear to be appropriately configured for cross-compilation.

**Comment by letoams** [comment]
On Mon, 1 Feb 2021, dkg wrote:

> This argument doesn't make sense to me. My proposed changes don't in any way change the behavior when the builder explicitly specifies a
> build requirement. They just auto-detect defaults that match the currently-available build environment.

Let's say you forgot to install a dev package. Now your include is
missing and your test compile fails. And you disable the feature.
While the OS/distro in fact does have the feature.

Or maybe you would have wanted the feature, and our current system
fails to compile and you look into it and you realise you should
upgrade your nss library to get this new cool feature too.

When doing auto-detection all of this goes way. You get a minimum set
instead of a maximum set.

> the libreswan source already tries to do such guessing for the defaults, but it does it in a more fragile/brittle way: by looking at the
> operating system/distro and version, and making guesses about what features might or might not be available in the version of nss that we
> expect to be on that version of that OS. This can be simply wrong, for people building on an uncommon platform for that version, or for
> people who are running mixed systems, or for rolling distributions like debian unstable, or in versions of OSes that you don't know about
> (including versions that don't exist yet).

I think we do this because it is the best we can do. Most inexperienced
users should not build things themselves. they use the distribution
version of libreswan. Those who are building themselves are given, where
possible, the latest options so they have a chance of figuring out what
they can or cannot change in their environment to get the latest feature
sets.

> You can remove a lot of fiddly code that is boring to maintain by just using a feature test directly to choose the defaults. The feature
> tests i've proposed run in less than a second, produce no side effects, and appear to be appropriately configured for cross-compilation.

You make it sound like it comes with a pony too :)
See the above example I give. Often people have old headers or old
libraries, and they gain a lot by upgrading those.

Perhaps there is a way to do both. Eg pick based on compiling
test programs, but give a very clear overview of what is
disabled because you seemed to not have the latest OS, kernel or
library. But I'm not in favour of mostly silently disabling things
just to make an unwise compile work.

Paul

**Comment by dkg** [comment]
On Mon 2021-02-01 13:06:03 -0800, Paul Wouters wrote:
> Perhaps there is a way to do both. Eg pick based on compiling
> test programs, but give a very clear overview of what is
> disabled because you seemed to not have the latest OS, kernel or
> library.

I like this suggestion.  Each autodetection test that i described has a
positive outcome (generally expected), and a negative outcome
(library/dependency/kernel headers too old, or oddly configured).

We could just attach a clear complaint to each negative outcome
prominently in the build long.

> But I'm not in favour of mostly silently disabling things just to make
> an unwise compile work.

agreed.

**Comment by cagney** [comment]
> I like this suggestion. Each autodetection test that i described has a positive outcome (generally expected), and a negative outcome (library/dependency/kernel headers too old, or oddly configured).

It will be ignored.

**Comment by dkg** [comment]
i'm just going to restate what i'm hearing here, so that my perspective
is clear, and then i'll stop bothering you about it:

 - libreswan currently has a way of choosing a default set of features,
   based on a brittle, incomplete, potentially-stale, labor-intensive
   catalog of distro/vendor versioning information.

 - Users who rely on those defaults may or may not be able to make a
   successful build in their environment.  The goal of the defaults is
   apparently *not* to achieve a successful build in as wide a range of
   situations as possible.

 - In some cases, the defaults may be over-pessimistic (e.g. building on
   system that runs an older distro but already has a backported NSS).
   If the developer relies on these defaults, they could end up with
   desired, available features being disabled.

 - In other cases, those defaults are over-optimistic (e.g. a niche
   architecture of a known distro release that ships an older version of
   NSS than a mainstream architecture ships in that same release).  If
   the developer relies on these defaults, the build will fail, rather
   than use the available version of NSS while dropping the unavailable
   feature.

If this is considered the preferred state of affairs, please close this
ticket, it's good to have it documented ☺

Perhaps the desire is just to force developers to explicitly disable
desirable features in situations where the feature is not available?  In
that case, you could drop the vendor catalog entirely, and use the
feature test to determine that a feature needs to have been disabled,
aborting early with a warning like:

    NSS IPsec profiles are not available.  Either set
    USE_NSS_IPSEC_PROFILE=false, update NSS to version 3.xx or later.

(with appropriate NSS version number of course)

Even this outcome seems likely to lead to libreswan packagers
hard-coding explicit feature-disabling directives in their distro's
build directives (at least while updated packages are unavailable),
which they then need to remember to remove when updated dependencies
become available.
