### ISSUE TITLE
Installation error on kali linux 

### ISSUE THREAD

**Issue by vivekvardhanadepu** [libreswan/libreswan#408]
Os details:
--------------
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.4"
VERSION_ID="2020.4"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian

While running "make deb", the following error occurs
~~~
fakeroot debian/rules binary
dh binary --with systemd
   dh_testroot
   dh_prep
   dh_installdirs
/media/vivek/4B6AE0131AB3ED1E1/FOSS/Libreswan/debian/libreswan.dirs: 1: /var/lib/ipsec/nss: not found
dh_installdirs: warning: debian/libreswan.dirs is marked executable but does not appear to an executable config.
dh_installdirs: warning: 
dh_installdirs: warning: If debian/libreswan.dirs is intended to be an executable config file, please ensure it can
dh_installdirs: warning: be run as a stand-alone script/program (e.g. "./debian/libreswan.dirs")
dh_installdirs: warning: Otherwise, please remove the executable bit from the file (e.g. chmod -x "debian/libreswan.dirs")
dh_installdirs: warning: 
dh_installdirs: warning: Please see "Executable debhelper config files" in debhelper(7) for more information.
dh_installdirs: warning: 
dh_installdirs: error: debian/libreswan.dirs (executable config) returned exit code 127
make: *** [debian/rules:6: binary] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -b failed
make[1]: *** [Makefile:7: deb] Error 29
make[1]: Leaving directory '/media/vivek/4B6AE0131AB3ED1E1/FOSS/Libreswan/packaging/debian'
make: *** [Makefile:184: deb] Error 2
~~~

**Comment by dkg** [comment]
This is pretty weird, but it looks like it's a permission error on the source code tree.  in particular `debian/libreswan.dirs` shouldn't have executable permissions.  I notice that you're building from within `/media/vivek/4B6AE0131AB3ED1E1/FOSS/Libreswan`.  that looks like it might be on a removable hard drive.  Any chance that the filesystem is something like FAT32?  FAT32 filesystems are typically mounted on linux such that all files are executable, which could confuse `dh_installdirs` like this.

if it's fat32, can you retry the build from a more sophisticated filesystem?  note that if you just do a straight copy from a fat32 volume, it'll probably copy the bad permissions.  so either re-clone the git repo, or unpack an upstream tarball directly into the better filesystem.

PS in the future, it helps to copy/paste the text from your terminal into the issue report, typically with a `~~~` line above and below to indicate it's "verbatim" -- that'll make the text searchable for other folks who encounter the same problem, and also keep it from getting accidentally wrapped.

**Comment by dkg** [comment]
also, on kali-rolling these days, you ought to be be able to just "apt install libreswan" to get version 4.1-4 installed, if i'm reading the `Packages` index at [the kali repo](https://http.kali.org/kali/dists/kali-rolling/main/binary-amd64/) correctly.  So maybe you don't have to build it at all, if you're just looking for a released installation, and not building from source?

**Comment by vivekvardhanadepu** [comment]
> This is pretty weird, but it looks like it's a permission error on the source code tree. in particular `debian/libreswan.dirs` shouldn't have executable permissions. I notice that you're building from within `/media/vivek/4B6AE0131AB3ED1E1/FOSS/Libreswan`. that looks like it might be on a removable hard drive. Any chance that the filesystem is something like FAT32? FAT32 filesystems are typically mounted on linux such that all files are executable, which could confuse `dh_installdirs` like this.
> 
> if it's fat32, can you retry the build from a more sophisticated filesystem? note that if you just do a straight copy from a fat32 volume, it'll probably copy the bad permissions. so either re-clone the git repo, or unpack an upstream tarball directly into the better filesystem.
> 
> PS in the future, it helps to copy/paste the text from your terminal into the issue report, typically with a `~~~` line above and below to indicate it's "verbatim" -- that'll make the text searchable for other folks who encounter the same problem, and also keep it from getting accidentally wrapped.

Really Sorry for the putting it as a screenshot. I was a bit tired and drowsy[It was around 1 AM here in India :disappointed: :disappointed:]

Yes it is removable hard drive[Windows]. Precisely, NTFS. I'll try with linux's root drive and let you know

**Comment by vivekvardhanadepu** [comment]
> also, on kali-rolling these days, you ought to be be able to just "apt install libreswan" to get version 4.1-4 installed, if i'm reading the `Packages` index at [the kali repo](https://http.kali.org/kali/dists/kali-rolling/main/binary-amd64/) correctly. So maybe you don't have to build it at all, if you're just looking for a released installation, and not building from source?

I wanted to contribute. So, I was building from source :grin: :grin:
Also, can you tell me if https://libreswan.org/wiki/ is a good way to start with?

**Comment by vivekvardhanadepu** [comment]
@dkg Thanks a lot!! It worked :grinning: :grinning:

**Comment by dkg** [comment]
Glad it worked for you, @vivekvardhanadepu !  I've followed up over on #411, highlighting some awkwardness about the potential changes there.
