### ISSUE TITLE
ipv6 support (address family inconsistency in this connection=2 host=10/nexthop=10)

### ISSUE THREAD

**Issue by markdgray** [libreswan/libreswan#416]
Hi,

For

```
sh-4.4# ipsec version
Linux Libreswan 3.32 (netkey) on 4.18.0-240.10.1.el8_3.x86_64
```

and `ipsec.conf`:

```
...
config setup
    uniqueids=yes

conn %default
    keyingtries=%forever
    type=transport
    auto=route
    ike=aes_gcm256-sha2_256
    esp=aes_gcm256
    ikev2=insist

conn ovn-ce80b9-0-in-1
    left=%defaultroute
    right=fd2e:6f44:5dd8:c956::14
    leftid=@1bcd67a8-8ce0-4d31-8e77-2ed00df16c3c
    rightid=@ce80b90f-f337-4cec-96ef-40cc535bb5e0
    leftcert="ovs_certkey_1bcd67a8-8ce0-4d31-8e77-2ed00df16c3c"
    leftrsasigkey=%cert
    rightca=%same
    leftprotoport=udp/6081
    rightprotoport=udp
...
```

I get the following error:
```
Feb  9 18:00:49.583888: address family inconsistency in this connection=2 host=10/nexthop=10
Feb  9 18:00:49.583917: Failed to load connection "ovn-ce80b9-0-in-1": attempt to load incomplete connection
Feb  9 18:00:49.590499: initiating all conns with alias='ovn-ce80b9-0-in-1'
```

It looks like it is not detecting an IPv6 connection. I am able to resolve this by using

```
hostaddrfamily=ipv6
clientaddrfamily=ipv6
```
but, from the documentation, I would have expected this to be automatically be picked up as this is an IPv6 only node?

Thanks,
Mark

**Comment by letoams** [comment]
On Tue, 9 Feb 2021, Mark Gray wrote:

> 
> conn ovn-ce80b9-0-in-1
>     left=%defaultroute
>     right=fd2e:6f44:5dd8:c956::14

We do provide: left=%defaultroute6

But I agree that if right= is IPv6, we know that left= should be IPv6 as
well.

> I get the following error:
> 
> Feb  9 18:00:49.583888: address family inconsistency in this connection=2 host=10/nexthop=10
> Feb  9 18:00:49.583917: Failed to load connection "ovn-ce80b9-0-in-1": attempt to load incomplete connection
> Feb  9 18:00:49.590499: initiating all conns with alias='ovn-ce80b9-0-in-1'
> 
> It looks like it is not detecting an IPv6 connection. I am able to resolve this by using
> 
> hostaddrfamily=ipv6
> clientaddrfamily=ipv6
> 
> but, from the documentation, I would have expected this to be automatically be picked up as this is an IPv6 only node?

Yeah, we should.

Paul

**Comment by cagney** [comment]
Tweaking testing/pluto/addconn-07-defaultroute gives this:
```
+road #
+ ipsec addconn --verbose ipv6-default 2>&1 | grep -e '^resolving ' -e '^  [^ ]'
+resolving src = <defaultroute> gateway = <defaultroute> peer 2001:db8:1:2::23
+  seeking gateway
+  query getroute +REQUEST +ROOT +MATCH
+  add dst 2001:db8:1:2::23 (peer->addr)
+  src <unset-address> prefsrc <unset-address> gateway 192.1.3.254 dst <unset-address> dev eth0 priority -1 pref -1 table 254
+  found gateway (host_nexthop): 192.1.3.254
+  please-call-again: src = <defaultroute> gateway = 192.1.3.254
+resolving src = <defaultroute> gateway = 192.1.3.254 peer 2001:db8:1:2::23
+  seeking prefsrc
+  query getroute +REQUEST
+  add dst 192.1.3.254 (host->nexthop)
+  src <unset-address> prefsrc 192.1.3.209 gateway <unset-address> dst 192.1.3.254 dev eth0 priority -1 pref -1 table 254 +cacheinfo +uid
+  found prefsrc (host_addr): 192.1.3.209
+  success: src = 192.1.3.209 gateway = 192.1.3.254
+resolving src = 2001:db8:1:2::23 gateway = <not-set> peer 192.1.3.209
+  seeking nothing
+road #
```
