### ISSUE TITLE
[Question] - Incompatibility between libreswan versions when using IKEv2 and RSA authentication method?

### ISSUE THREAD

**Issue by vardias** [libreswan/libreswan#422]
Hello,

I  am trying to create an IPSec connection between libreswan-3.23 version and libreswan-3.32 version and I am getting the following output:

ipsec auto --up rsa                                                                                                
181 "rsa" : initiating IKEv2 IKE SA                                                                                                                        
181 "rsa" : STATE_PARENT_I1: sent v2I1, expected v2R1                                                                                                      
003 "rsa" : **DigSig: no compatible DigSig hash algo**                                                                                                         
002 "rsa" : deleting other state (STATE_CHILDSA_DEL) aged 0.000s and NOT sending notification                                                          
214 "rsa" : state transition 'Initiator: process IKE_SA_INIT reply, initiate IKE_AUTH' failed with v2N_NO_PROPOSAL_CHOSEN

The configuration in each host are the followings:
_libreswan-3.32_
conn rsa
    left=xxx.xxx.xxx.xxx
    leftrsasigkey=0sXXX
    right=xxx.xxx.xxx.xxx
    ikev2=insist
    ike=aes_cbc256-sha2_512;dh21
    phase2=esp
    phase2alg=aes_cbc256-sha2_512,aes_ctr256-sha2_512,aes_ctr256-sha2_512,aes_gcm_c256-null,aes_gcm_c256-null
    rightrsasigkey=0sXXX
    type=tunnel
    authby=rsasig

_libreswan-3.23_
conn rsa-connection
    left=xxx.xxx.xxx.xxx
    leftrsasigkey=0sXXX
    right=xxx.xxx.xxx.xxx
    ikev2=insist
    ike=aes_cbc256-sha2_512;dh21
    phase2=esp
    phase2alg=aes_cbc256-sha2_512,aes_ctr256-sha2_512,aes_ctr256-sha2_512,aes_gcm_c256-null,aes_gcm_c256-null
    rightrsasigkey=0sXXX
    type=tunnel
    authby=rsasig

The problem exists only when I am using IKEv2 and not IKEv1.
Also the strange is that when I tried this configuration between libreswan-3.29 and libreswan-3.32 it worked just fine.
So do you think that there is an incompatibility between libreswan-3.23 and libreswan-3.32 regarding the RSA authentication method and the IKEv2?
Or it is a configuration problem? I tried a lot of different algorithms with no luck.

Thank you in advance.
Regards,
Marc

**Comment by letoams** [comment]
On Wed, 3 Mar 2021, Markos Vardias wrote:

> I am trying to create an IPSec connection between libreswan-3.23 version and libreswan-3.32 version and I am getting the following output:
>
>                                                                      ipsec auto --up rsa
> 
> 181 "rsa" #30: initiating IKEv2 IKE SA
> 181 "rsa" #30: STATE_PARENT_I1: sent v2I1, expected v2R1
> 003 "rsa" #30: DigSig: no compatible DigSig hash algo
> 002 "rsa" #31: deleting other state #31 (STATE_CHILDSA_DEL) aged 0.000s and NOT sending notification
> 214 "rsa" #30: state transition 'Initiator: process IKE_SA_INIT reply, initiate IKE_AUTH' failed with v2N_NO_PROPOSAL_CHOSEN

On the 3.32, can you see if setting authby=rsa-sha1 makes a difference?

> So do you think that there is an incompatibility between libreswan-3.23 and libreswan-3.32 regarding the RSA authentication method and the IKEv2?
> Or it is a configuration problem? I tried a lot of different algorithms with no luck.

It might be confusion between RSA vs RFC7427 RSA ?

If you can mail me plutodebug=all logs of both ends, I can confirm what
the issue is.

Paul

**Comment by vardias** [comment]
It makes a difference yes. Actually the IPSec connection established successfully:

ipsec auto --up rsa
181 "rsa" : initiating IKEv2 IKE SA
181 "rsa" : STATE_PARENT_I1: sent v2I1, expected v2R1
182 "rsa" : STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=AES_CBC_256 integ=HMAC_SHA2_512_256 prf=HMAC_SHA2_512 group=DH21}
002 "rsa" : IKEv2 mode peer ID is ID_FQDN: ''
003 "rsa" : Authenticated using RSA with IKEv2_AUTH_HASH_SHA1
002 "rsa" : negotiated connection [xxx.xxx.xxx.xxx-xxx.xxx.xxx.xxx:0-65535 0] -> [xxx.xxx.xxx.xxx-xxx.xxx.xxx.xxx-65535 0]
004 "rsa" : STATE_V2_IPSEC_I: IPsec SA established tunnel mode {ESP=>0x1803af81 <0x52972842 xfrm=AES_CBC_256-HMAC_SHA2_512_256 NATOA=none NATD=none DPD=passive}

I tried to use the other available options: rsa-sha2, rsa-sha2_384 but nothing happened.
I didn't know that there was an option to force SHA1 hash except for the rsasig option.

The truth is I noticed in the changelog some changes regarding the IKEv2 and the RSA method: 

**for v.3.30**
_"IKEv2: Refuse SHA1 for RFC 7427 Digital Signatures as per RFC 8247"
"IKEv2: Prefer RFC 7427 Digital Signatures for default authby=rsasig"_
**for v.3.28**
_"IKEv2: Remove SHA1 from default IKEv2 proposal"_

I will prepare the logs and I will send them to you via email.
Thank you very much

Regards,
Marc

**Comment by letoams** [comment]
Ah, no need for the logs then.

I’ll see if this can be fixed somehow

**Comment by vardias** [comment]
OK good, so the option "rsa-sha1" is valid then?

**Comment by vardias** [comment]
Because it is not documented anywhere I think. Anyway thanks for the help!

**Comment by bleve** [comment]
It is valid to force same algoritm as old libreswan authby=rsasig

**Comment by vardias** [comment]
Yes correct, thank you

**Comment by cagney** [comment]
> ipsec auto --up rsa
> 181 "rsa" : initiating IKEv2 IKE SA
> 181 "rsa" : STATE_PARENT_I1: sent v2I1, expected v2R1
> 003 "rsa" : **DigSig: no compatible DigSig hash algo**
> 002 "rsa" : deleting other state (STATE_CHILDSA_DEL) aged 0.000s and NOT sending notification
> 214 "rsa" : state transition 'Initiator: process IKE_SA_INIT reply, initiate IKE_AUTH' failed with v2N_NO_PROPOSAL_CHOSEN

FYI, the (trimmed) output now looks more like:

```
#1: initiating IKEv2 connection
#1: sent IKE_SA_INIT request
#1: sent IKE_AUTH request {cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_512 group=MODP2048}
#1: initiator established IKE SA; authenticated using RSA with SHA2_512 and preloaded certificate '@east'
#2: IKE_AUTH response rejected Child SA with TS_UNACCEPTABLE
```

- the outcome of the IKE SA and Child SA are logged separately
- the rsa digsig code was overhauled
- the line "no compatible DigSig hash algo" is no longer logged

you might be interested in these bugs  #665 #664

**Comment by prohto** [comment]
I'm having the same issue, but with libreswan 3.25,  and I have no access to the other end. Tried adding authby=rsasig but it didn't make any difference.

**Comment by letoams** [comment]
Try authby=rsa-sha1 ?

Sent using a virtual keyboard on a phone

**Comment by prohto** [comment]
I tried that, but I get the error:
```
connection allowing ikev1 must use authby= of rsasig, secret or never
```
this is my config:
```
conn %default
        ikelifetime=90000s
        lifetime=90000s
        keylife=90000s
        rekeymargin=3m
        keyingtries=1
        keyexchange=ike
        ike=aes192-sha256-sha256-modp3072,aes256-sha1-modp1024,aes-sha256-sha256-modp2048,aes256-sha1-modp1024,aes256-sha1-sha1-modp2048
        mobike=no
        reauth=no
        dpdaction=clear
        left=X.X.X.X
        leftcert="xxxxxxxxxxxx"
        leftid=%any
        right=%any
        rightid=%any
        ikev2=yes
        authby=rsa-sha1
        leftsourceip=X.X.X.X
```
