### ISSUE TITLE
Dropping unexpected ISAKMP_v2_IKE_AUTH message containing v2N_MOBIKE_SUPPORTED notification

### ISSUE THREAD

**Issue by wyw900807** [libreswan/libreswan#424]
Dear sir
       I cannot use windows 7 client to connect VPN. The version of libreswan that I use is 3.31, the config file is shown as follows:
 config setup
    protostack=netkey
    nhelpers=0
    uniqueids=no
    interfaces=%defaultroute
    virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!3.3.3.0/24

conn ikev2-cp
    left=%defaultroute
    leftprotoport=17/1701
    leftid=192.168.171.145
    right=%any
    rightprotoport=17/%any
    dpddelay=40
    dpdtimeout=130
    dpdaction=clear
    auto=add
    ikev2=insist
    rekey=no
    pfs=no
    fragmentation=yes
    ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1,aes256-sha2;modp2048,aes128-sha1;modp2048
    phase2alg=aes256-sha1,aes192-sha1,aes128-sha1
    encapsulation=yes

Furthermore, according to https://libreswan.org/wiki/FAQ#Microsoft_Windows_connection_attempts_fail_with_NO_POROPOSAL_CHOSEN, I have changed the registry by adding a DWORD
HKEY_LOCAL_MACHINE/System/CurrentControlSet/Services/Rasman/Parameters/NegotiateDH2048_AES256.
The log of libreswan is shown as follows:
Mar 15 11:52:40 centos7 pluto[15477]: "ikev2-cp"[2] 10.10.216.194: local IKE proposals (IKE SA responder matching remote proposals):
Mar 15 11:52:40 centos7 pluto[15477]: "ikev2-cp"[2] 10.10.216.194:   1:IKE=AES_CBC_256-HMAC_SHA2_256-HMAC_SHA2_256_128-MODP2048+MODP3072+MODP4096+MODP8192+ECP_256+ECP_384+ECP_521+CURVE25519
Mar 15 11:52:40 centos7 pluto[15477]: "ikev2-cp"[2] 10.10.216.194:   2:IKE=AES_CBC_128-HMAC_SHA2_256-HMAC_SHA2_256_128-MODP2048+MODP3072+MODP4096+MODP8192+ECP_256+ECP_384+ECP_521+CURVE25519
Mar 15 11:52:40 centos7 pluto[15477]: "ikev2-cp"[2] 10.10.216.194:   3:IKE=AES_CBC_256-HMAC_SHA1-HMAC_SHA1_96-MODP2048+MODP3072+MODP4096+MODP8192+ECP_256+ECP_384+ECP_521+CURVE25519
Mar 15 11:52:40 centos7 pluto[15477]: "ikev2-cp"[2] 10.10.216.194:   4:IKE=AES_CBC_128-HMAC_SHA1-HMAC_SHA1_96-MODP2048+MODP3072+MODP4096+MODP8192+ECP_256+ECP_384+ECP_521+CURVE25519
Mar 15 11:52:40 centos7 pluto[15477]: "ikev2-cp"[2] 10.10.216.194:   5:IKE=AES_CBC_256-HMAC_SHA2_256-HMAC_SHA2_256_128-MODP2048
Mar 15 11:52:40 centos7 pluto[15477]: "ikev2-cp"[2] 10.10.216.194:   6:IKE=AES_CBC_128-HMAC_SHA1-HMAC_SHA1_96-MODP2048
Mar 15 11:52:40 centos7 pluto[15477]: "ikev2-cp"[2] 10.10.216.194 #2: proposal 2:IKE=AES_CBC_256-HMAC_SHA2_256-HMAC_SHA2_256_128-MODP2048 chosen from remote proposals 1:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA1_96;PRF=HMAC_SHA1;D
H=MODP2048[first-match] 2:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_256_128;PRF=HMAC_SHA2_256;DH=MODP2048[better-match] 3:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_384_192;PRF=HMAC_SHA2_384;DH=MODP2048Mar 15 11:52:40 centos7 pluto[15477]: "ikev2-cp"[2] 10.10.216.194 #2: STATE_PARENT_R1: received v2I1, sent v2R1 {auth=IKEv2 cipher=AES_CBC_256 integ=HMAC_SHA2_256_128 prf=HMAC_SHA2_256 group=MODP2048}
Mar 15 11:52:40 centos7 pluto[15477]: "ikev2-cp"[2] 10.10.216.194 #2: dropping unexpected ISAKMP_v2_IKE_AUTH message containing v2N_MOBIKE_SUPPORTED notification; message payloads: SK; encrypted payloads: SA,IDi,CERTREQ,N,TS
i,TSr,CP; missing payloads: AUTHMar 15 11:52:40 centos7 pluto[15477]: "ikev2-cp"[2] 10.10.216.194 #2: responding to IKE_AUTH message (ID 1) from 10.10.216.194:500 with encrypted notification INVALID_SYNTAX
Mar 15 11:52:40 centos7 pluto[15477]: "ikev2-cp"[2] 10.10.216.194 #2: encountered fatal error in state STATE_PARENT_R1
Mar 15 11:52:40 centos7 pluto[15477]: "ikev2-cp"[2] 10.10.216.194 #2: deleting state (STATE_PARENT_R1) aged 0.020s and NOT sending notification
Mar 15 11:52:40 centos7 pluto[15477]: #2: deleting connection "ikev2-cp"[2] 10.10.216.194 instance with peer 10.10.216.194 {isakmp=#0/ipsec=#0}

Thank you very much!

**Comment by letoams** [comment]
Your config is setup for LT2P (port 1701) which is only used for IKEv1, and you set ikev2=insist

You need to decide between the two, not try to use both 



>

**Comment by wyw900807** [comment]
Thank you very much!

**Comment by wyw900807** [comment]
Thank you very much
