### ISSUE TITLE
when Multiple TSi/TSr are supported, figure out a ipsec.conf syntax for the asymmetrical case

### ISSUE THREAD

**Issue by letoams** [libreswan/libreswan#425]
The common use case is a daemon that receives on a static port X and sends from an ephemeral port to other nodes on port X.
Currently, without multiple TSi/TSr, you need to specify two conns, both having an unused half conn:

conn service-in
   [...]
   leftprotoport=udp/XXX
  rightprotoport=udp

conn service-out
   [...]
   leftprotoport=udp
   rightprotoport=udp/XXX

We need a way to merge these two conns into a single conn using multple TSi/TSr, but what is the best more readable way to preesnt that to endusers?

We could follow the tcp example by using remote-XXX keywords, but that kind of breaks the paradigm of left/right we are using.
Maybe a keyword where you can specify one conn and we "add a flipped version" ?

**Comment by letoams** [comment]
I think in theory, we could also negotiate this with one set of Traffic Selectors ? Nothing says the TSi and TSr have to be reverse image of each other ?

**Comment by letoams** [comment]
Oh, I guess for TCP that would never work. For UDP it might, but it is kind of weird that you would have only one-directional traffic.

**Comment by cagney** [comment]
see https://github.com/libreswan/libreswan/blob/main/testing/programs/ipcheck/ip_selector_check.c#L204
subnet= accepts: <address>[/<len>[:<protocol>/<port>]], ...
we should mark the syntax experimental in 4.10
