### ISSUE TITLE
Two windows client behind same NAT connet L2TP/IPsec, but only one works

### ISSUE THREAD

**Issue by wyw900807** [libreswan/libreswan#427]
Dear sir:
           There is a nat between the client and server, and only one client can connect to server. The client is windows 7, the server is l2tp/ipsec. The version of libreswan is 3.31 and I set libreswan to tunnel mode, the config file is shown as follows:

version 2.0
config setup
    protostack=netkey
    nhelpers=0
    uniqueids=no
    interfaces=%defaultroute
    virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!3.3.3.0/24

conn l2tp-psk
    rightsubnet=vhost:%priv
    also=l2tp-psk-nonat

conn l2tp-psk-nonat
    authby=secret
    pfs=no
    auto=add
    keyingtries=3
    rekey=no
    ikelifetime=8h
    keylife=1h
    #type=transport
    type=tunnel
    left=%defaultroute
    leftid=192.168.171.145
    leftprotoport=17/1701
    right=%any
    rightprotoport=17/%any
    dpddelay=40
    dpdtimeout=130
    dpdaction=clear
    ikev2=never

I find that the two clients are assigned different IP, but only one can connect the server, could you help me to solve this problem?

**Comment by letoams** [comment]
On Sun, 21 Mar 2021, Hollow Knight wrote:

> There is a nat between the client and server, and only one client can connect to server. The client is windows 7, the server is l2tp/ipsec. The version of libreswan is 3.31 and I set libreswan to tunnel
> mode, the config file is shown as follows:

The git version has some fixes related to this that might fix your
problem. Is it possible for you to test this? You can grab the
latest version in git or use this testing version:

https://download.libreswan.org/development/libreswan-4.4dr1.tar.gz

Paul

**Comment by wyw900807** [comment]
Dear sir:
    Thank you for your reply, I test the version https://download.libreswan.org/development/libreswan-4.4dr1.tar.gz, but there are still problems, only one client can connect the server. The IP of two clients are 10.10.216.194 and 10.10.216.144, the IP of nat is 192.168.171.141, the IP of l2tp/ipsec is 192.168.171.145. The IP assigned to the client is 3.3.3.0/24. The logs are shown as follows:

Mar 22 13:29:21 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #13: responding to Main Mode from unknown peer 192.168.171.141:500
Mar 22 13:29:21 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #13: WARNING: connection l2tp-psk PSK length of 4 bytes is too short for HMAC_SHA1 PRF in FIPS mode (10 bytes required)
Mar 22 13:29:21 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #13: sent Main Mode R1
Mar 22 13:29:21 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #13: sent Main Mode R2
Mar 22 13:29:21 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #13: Peer ID is ID_IPV4_ADDR: '10.10.216.144'
Mar 22 13:29:21 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #13: IKE SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA1 group=DH20}
Mar 22 13:29:21 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #13: Configured DPD (RFC 3706) support not enabled because remote peer did not advertise DPD support
Mar 22 13:29:21 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #13: the peer proposed: 192.168.171.141/32:1701 -UDP-> 10.10.216.144/32:1701
Mar 22 13:29:21 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #13: NAT-Traversal: received 2 NAT-OA. Ignored because peer is not NATed
Mar 22 13:29:21 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #14: responding to Quick Mode proposal {msgid:00000001}
Mar 22 13:29:21 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #14:     us: 192.168.171.145:17/1701  them: 192.168.171.141[10.10.216.144]:17/1701===10.10.216.144/32
Mar 22 13:29:21 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #14: sent Quick Mode reply, inbound IPsec SA installed, expecting confirmation tunnel mode {ESPinUDP=>0xf6c4d2bf <0x4c4b206c xfrm=AES_CBC_128-HMAC_SHA1_96 N
ATOA=none NATD=192.168.171.141:4500 DPD=unsupported}Mar 22 13:29:21 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #14: IPsec SA established tunnel mode {ESPinUDP=>0xf6c4d2bf <0x4c4b206c xfrm=AES_CBC_128-HMAC_SHA1_96 NATOA=none NATD=192.168.171.141:4500 DPD=unsupported}
Mar 22 13:30:28 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #15: responding to Main Mode from unknown peer 192.168.171.141:135
Mar 22 13:30:28 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #15: WARNING: connection l2tp-psk PSK length of 4 bytes is too short for HMAC_SHA1 PRF in FIPS mode (10 bytes required)
Mar 22 13:30:28 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #15: sent Main Mode R1
Mar 22 13:30:28 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #15: sent Main Mode R2
Mar 22 13:30:28 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #15: Peer ID is ID_IPV4_ADDR: '10.10.216.194'
Mar 22 13:30:28 centos7 pluto[12631]: "l2tp-psk"[8] 192.168.171.141 #15: switched from "l2tp-psk"[8] 192.168.171.141 to "l2tp-psk"
Mar 22 13:30:28 centos7 pluto[12631]: "l2tp-psk"[9] 192.168.171.141 #15: Peer ID is ID_IPV4_ADDR: '10.10.216.194'
Mar 22 13:30:28 centos7 pluto[12631]: "l2tp-psk"[9] 192.168.171.141 #15: IKE SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA1 group=DH20}
Mar 22 13:30:28 centos7 pluto[12631]: "l2tp-psk"[9] 192.168.171.141 #15: Configured DPD (RFC 3706) support not enabled because remote peer did not advertise DPD support
Mar 22 13:30:28 centos7 pluto[12631]: "l2tp-psk"[9] 192.168.171.141 #15: the peer proposed: 192.168.171.141/32:1701 -UDP-> 10.10.216.194/32:1701
Mar 22 13:30:28 centos7 pluto[12631]: "l2tp-psk"[9] 192.168.171.141 #15: NAT-Traversal: received 2 NAT-OA. Using first; ignoring others
Mar 22 13:30:28 centos7 pluto[12631]: "l2tp-psk"[9] 192.168.171.141 #16: responding to Quick Mode proposal {msgid:00000001}
Mar 22 13:30:28 centos7 pluto[12631]: "l2tp-psk"[9] 192.168.171.141 #16:     us: 192.168.171.145:17/1701  them: 192.168.171.141[10.10.216.194]:17/1701===10.10.216.194/32
Mar 22 13:30:28 centos7 pluto[12631]: "l2tp-psk"[9] 192.168.171.141 #16: sent Quick Mode reply, inbound IPsec SA installed, expecting confirmation tunnel mode {ESPinUDP=>0x96056081 <0xd6db7b9d xfrm=AES_CBC_128-HMAC_SHA1_96 N
ATOA=10.10.216.194 NATD=192.168.171.141:37767 DPD=unsupported}Mar 22 13:30:28 centos7 pluto[12631]: "l2tp-psk"[9] 192.168.171.141 #16: IPsec SA established tunnel mode {ESPinUDP=>0x96056081 <0xd6db7b9d xfrm=AES_CBC_128-HMAC_SHA1_96 NATOA=10.10.216.194 NATD=192.168.171.141:37767 DPD=uns
upported}Mar 22 13:30:42 centos7 sshd[14201]: Accepted password for root from 3.3.3.3 port 18139 ssh2
Mar 22 13:30:42 centos7 sshd[14201]: pam_unix(sshd:session): session opened for user root by (uid=0)

Thank you very much!

**Comment by bleve** [comment]
Paul missed that you use l2tp-over-ipsec - l2tp-over-ipsec uses ikev1 transport mode and that can only support single host behind nat. If you want multiple clients behind nat you better move to ikev2 config payload mode with certificates which supports multiple clients behind same nat.

**Comment by wyw900807** [comment]
Thank you!

**Comment by letoams** [comment]
General comment for everyone using IKEv1 with L2TP/IPsec: migrate to IKEv2 for proper support of multiple clients behind the same NAT gateway. L2TP with IPsec in Transport Mode is just not a good solution and has been abandoned even by Microsoft in favour of IKEv2 using Tunnel Mode.
