### ISSUE TITLE
XFRM: IPCOMP state not deleted when IPsec SA is deleted

### ISSUE THREAD

**Issue by letoams** [libreswan/libreswan#435]
XFRM: IPCOMP state not deleted when IPsec SA is deleted

this is tested and shows test failure in https://github.com/libreswan/libreswan/tree/main/testing/pluto/ikev2-14-compress

**Comment by cagney** [comment]
Cleaning up the kernel code fixed this - the state is gone. 

Just note that downing the connection installs:
```
[root@west compress-pluto-01-cleanup]# ip xfrm policy
src 192.0.1.0/24 dst 192.0.2.0/24 
	dir out priority 1757393 ptype main 
	tmpl src 0.0.0.0 dst 0.0.0.0
		proto esp reqid 0 mode transport
```
which is then deleted when pluto exits.

**Comment by letoams** [comment]
On Jan 9, 2023, at 16:42, cagney ***@***.***> wrote:
> 
> ﻿
> Cleaning up the kernel code fixed this - the state is gone.
> 

Is it ? Because:

> Just note that downing the connection installs:
> 
> ***@***.*** compress-pluto-01-cleanup]# ip xfrm policy
> src 192.0.1.0/24 dst 192.0.2.0/24 
> 	dir out priority 1757393 ptype main 
> 	tmpl src 0.0.0.0 dst 0.0.0.0
> 		proto esp reqid 0 mode transport
Which should have been deleted with the conn.

> which is then deleted when pluto exits.
> 
Only because we purge hard at shutdown ?

**Comment by cagney** [comment]
The earliest test run I can find is
https://testarchive.libreswan.org/v4.5-v4.6/v4.5-198-g8c9cfb95b7-main/compress-pluto-01-cleanup/OUTPUT/west.console.diff
The bug was that the code forgot to delete the IPCOMP kernel state.
```
 west #
-!! this should not have states !!
  ../../guestbin/ipsec-look.sh
 west NOW
 XFRM state:
-!! this should not have states !!
 XFRM policy:
+src 192.0.1.0/24 dst 192.0.2.0/24
+	dir out priority 2084814 ptype main
+	tmpl src 0.0.0.0 dst 0.0.0.0
+		proto esp reqid 0 mode transport
```

**Comment by letoams** [comment]
> 
> 
> The bug was that the code forgot to delete the IPCOMP kernel state.
> 
>  west #
> -!! this should not have states !!
>   ../../guestbin/ipsec-look.sh
>  west NOW
>  XFRM state:
> -!! this should not have states !!

Yes but your GitHub note said it got deleted when pluto stopped not when the connection was brought down/deleted.

If it only vanished at ipsec stop, that’s a bug. I’ll retest to make sure.

Paul

**Comment by cagney** [comment]
> Yes but your GitHub note said it got deleted when pluto stopped not when the connection was brought down/deleted.

I was referring to the stub policy that replaced the IPsec state+policy.
See  522241336b11c3e3a508497b577b166aac078f19 which updated
https://testing.libreswan.org/v4.9-656-g82fac5b002-main/compress-pluto-01-cleanup/OUTPUT/west.console.txt
The tail looks like this:
```
west #
 ipsec auto --down westnet-eastnet-compress | sed -e 's/=6[0-9][0-9]B/=6nnB/g'
002 "westnet-eastnet-compress": terminating SAs using this connection
002 "westnet-eastnet-compress" #2: deleting state (STATE_QUICK_I2) and sending notification
005 "westnet-eastnet-compress" #2: ESP traffic information: in=6nnB out=6nnB
005 "westnet-eastnet-compress" #2: IPCOMP traffic information: in=0B out=0B
002 "westnet-eastnet-compress" #1: deleting state (STATE_MAIN_I4) and sending notification
west #
 echo ping
ping
west #
 ../../guestbin/ipsec-kernel-state.sh
west #
 ../../guestbin/ipsec-kernel-policy.sh
src 192.0.1.0/24 dst 192.0.2.0/24
	dir out priority PRIORITY ptype main 
	tmpl src 0.0.0.0 dst 0.0.0.0
		proto esp reqid 0 mode transport
west #
```

**Comment by paulwouters** [comment]
this state is wrong. The connection is deleted or down'ed without coming back up, so delete means all xfrm state and policy of the deleted connection should have been removed.

**Comment by cagney** [comment]
> this state is wrong. The connection is deleted or down'ed without coming back up, so delete means all xfrm state and policy of the deleted connection should have been removed.

This bug was about removing the state+policy of the IPsec SA, and these are all gone.

What we've instead got is a policy installed by:
```
                         * This code installs a TRANSPORT mode policy                                                                                                                                 
                         * (the host .{src,dst} provides the family                                                                                                                                   
                         * but the address isn't used).  The actual                                                                                                                                   
                         * connection might be TUNNEL.                                                                                                                                                
                         */
                        enum shunt_policy shunt_policy = (c->config->failure_shunt == SHUNT_NONE ?
                                                          c->config->prospective_shunt :
                                                          c->config->failure_shunt);
```
which, if wrong, is a very different bug.

**Comment by paulwouters** [comment]
east is auto=add and west is being --up'ed and --down'ed, so there should be no shunts left. If east had auto=keep or auto=start then yes there should be a shunt.

I see this is unrelated to compress=yes. It now also happens for compress=no. I will git bisect it and file a new bug.
