### ISSUE TITLE
IKEv1 private key not logged when using "debug private"

### ISSUE THREAD

**Issue by aeko-empt** [libreswan/libreswan#439]
Hello.

I tried debug my issue with s2s vpnc on libreswan 3.27 in wireshark, but I didn't find an encryption key for decrypt ISAKMP.
I used all debug leveling which represents in 'ipsec whack --debug list' (private, crypt, crypt-low etc), but I found  only enc key and auth for decrypt ESP. Also 'ip xfrm state' represents enc key and auth for decrept ESP.

Thank you in advance.

**Comment by cagney** [comment]
The option is «--debug private», however it only dumps stuff when IKEv2 is being used.  In ikev2.c see  ikev2_log_parentSA().
