### ISSUE TITLE
Unexpected state deletion when using labeled IPsec

### ISSUE THREAD

**Issue by kavinda-forcepoint** [libreswan/libreswan#441]
Hi,

While using labeled IPsec, I encountered a situation where parent/IKE and child/IPsec SA state are getting deleted at the Responder when using IKEv2 labeled IPsec.

Assume the following SELinux labels and rules exist:

* `pluto_t`: SELinux domain used to run `pluto`.
* `ipsec_spd_t`: SELinux label assigned to Security Policy Database (SPD) entries.
* `full_perm_t`: SELinux domain used to run the process "ProcFull".
  ** `full_perm_t` has `polmatch` permission against `ipsec_spd_t`.
  ** `pluto_t` has `setcontext` permission against `full_perm_t`.
* `partial_perm_t`: SELinux domain used to run the process "ProcPartial".
  ** `partial_perm_t` has `polmatch` permission against `ipsec_spd_t`.
  ** `pluto_t` does _NOT_ have the `setcontext` permission against `partial_perm_t`.

Also assume that both endpoints of the IPsec tunnel have the above SELinux policy.

This is what I observe:

1. Initiator and Responder: Sets up a tunnel using `ipsec_spd_t` for the initial child/IPsec SA pair.
2. Initiator: ProcFull, running with SELinux domain `full_perm_t`, attempts to send network traffic to Responder.
3. Initiator and Responder: Sets up a child/IPsec SA pair using `full_perm_t`.
4. Initiator: ProcFull successfully sends/receives network traffic to/from Responder.
5. Initiator: ProcPartial, running with SELinux domain `partial_perm_t`, attempts to send network traffic to Responder.
6. Initiator: `pluto` confirms that `partial_perm_t` has `polmatch` permission against `ipsec_spd_t` via `within_label()`.
7. Initiator: `pluto` sends a `CREATE_CHILD_SA` request to Responder with `partial_perm_t` as the `TS_SECLABEL` payload value.
8. Responder: `pluto` confirms that `partial_perm_t` has `polmatch` permission against `ipsec_spd_t` via `within_label()`.
9. Responder: `pluto` attempts to install a child/IPsec SA via `netlink_add_sa()` for `partial_perm_t` and fails.
  ** This is because `pluto_t` does NOT have the `setcontext` permission against `partial_perm_t`.
10. Responder: `handle_helper_answer()` returns `STF_FAIL` due to SA installation failure.
11. Responder: `complete_v2_state_transition()` is invoked with `STF_FAIL`.
12. Responder: `pluto` deletes all child/IPsec SAs and the parent/IKE SA via `delete_ike_family()`.
  ** This includes child/IPsec SA pairs for _both_ `partial_perm_t` and `full_perm_t`.
  ** `pluto` does NOT send delete messages for these SA deletes, i.e. it invokes `delete_ike_family(ike, DONT_SEND_DELETE)`.
  ** Since `full_perm_t` child/IPsec SA is deleted, it disrupts the network communication of ProcFull.
13. Initiator: ProcFull continues to send ESP traffic using `full_perm_t` child/IPsec SA that is ignored by the Responder.

The desired behavior for the Responder is to:

* _Only_ delete the child/IPsec SA for `partial_perm_t`.
* Send a delete message for `partial_perm_t` child/IPsec SA deletion.

**Comment by letoams** [comment]
The deletion for everything is due to the fact that these instances are not full proper instances. The connection is of type CK_PERMANENT, so if that fails, pluto normally removes the failed child.

the proper way out is to properly instantiate child sa's and turn the first --up into a childless IKE SA.

**Comment by cagney** [comment]
sec_lables have been changed to use CK_TEMPLATE and CK_INSTANCE

**Comment by kavinda-forcepoint** [comment]
I still see a state deletion issue with the latest code from mainline though it manifests differently.

In particular:

* Initiator deletes all the IKE + IPsec state instead of the Responder.
  * Responder eventually deletes all the state when it receives the delete messages from the Initiator.
* A retransmit timeout for an IKE SA (in state `ESTABLISHED_IKE_SA`) triggers the deletion at the Initiator.
* According to Initiator's log: the last message sent prior to the retransmit timeout is `CREATE_CHILD_SA` with `partial_perm_t` (see original post for `partial_perm_t` definition).
* I see the following messages in the Initiator's log as well:

```
"<TunnelName>" #1: STATE_V2_ESTABLISHED_IKE_SA: 60 second timeout exceeded after 7 retransmits.  No response (or no acceptable response) to our IKEv2 message

"<TunnelName>" #1: liveness action - putting connection into hold

deleting states for connection - including all other IPsec SA's of this IKE SA

**Comment by cagney** [comment]
Do you know why there was no response to the create-child-sa request?

An IKEv2 initiator, should the responder go MIA, will assume the IKE family is dead.

**Comment by letoams** [comment]
On Mon, 26 Jul 2021, cagney wrote:

> Do you know why there was no response to the create-child-sa request?

There was, just not a happy one due to add_sa() failing on the
responder.

**Comment by cagney** [comment]
Yea, reading off git discussion.

I suspect this is why the rejection comes back (up until now this was assumed to succeed):

```
	/* now install child SAs */
	if (!install_ipsec_sa(&child->sa, TRUE))
		/* This affects/kills the IKE SA? Oops :-( */
		return v2N_INVALID_SYNTAX; /* fatal */
```

should partial_perm_t have been rejected earlier?

It's also not yet clear why the initiator didn't act on the fatal response.

**Comment by letoams** [comment]
On Mon, 26 Jul 2021, cagney wrote:

> I suspect this is why the rejection comes back (up until now this was assumed to succeed):
>
> 	/* now install child SAs */
> 	if (!install_ipsec_sa(&child->sa, TRUE))
> 		/* This affects/kills the IKE SA? Oops :-( */
> 		return v2N_INVALID_SYNTAX; /* fatal */

This is not right though. v2N_INVALID_SYNTAX will kill the IKE SA on
both sides? It should only fail the ipsec sa.

> should partial_perm_t have been rejected earlier?

It was a "bad" security label that did not have permission to get
installed.

> It's also not yet clear why the initiator didn't act on the fatal response.

It went into a weird timeout/retry code path, then killed everything on
timeout ?

**Comment by cagney** [comment]
Just an aside,
- IKE_SA_INIT exchange always has message ID 0
- IKE_AUTH exchange normally has message ID 1 (ignore EAP / IKE_INTERMEDIATE)
- the first CREATE_CHILD_SA normally has Message ID 2
seeing packets with older IDs dropped is most likely due to re-transmits; for instance, the IKE_AUTH initiator getting impatient with the responder taking so long with crypto and retransmitting.

**Comment by cagney** [comment]
Technical not.  I quoted the initiator's code, responder is similar and for this case is found in record_v2_CREATE_CHILD_SA().

> This is not right though. v2N_INVALID_SYNTAX will kill the IKE SA on both sides? It should only fail the ipsec sa.

Right.  Like the comment says, "Oops:-(".

The code's always assumed that failing to insert the SA into the kernel would work.  For instance it:
- it builds the response
- it, er, refreshes newest_ike_sa
before calling install_ipsec_sa() (it does update ipsec_sa after the call).

But now we find the kernel failing to insert the SA is normal so this should be re-ordered.

>> should partial_perm_t have been rejected earlier?
> It was a "bad" security label that did not have permission to get installed.

but it was vetted by the TS code?

-> is there more that can be checked in ikev2_ts.c?
-> I'll disentangle record_v2_CREATE_CHILD_SA(), so that install_ipsec_sa() is called earlier making it easier to return TS_UNACCEPTABLE

>> It's also not yet clear why the initiator didn't act on the fatal response.
> It went into a weird timeout/retry code path, then killed everything on timeout ?

I suspect the responder forgot to send the fatal response.

**Comment by letoams** [comment]
On Jul 26, 2021, at 15:22, cagney ***@***.***> wrote:
> 
> ﻿
> Just an aside,
> 
> IKE_SA_INIT exchange always has message ID 0
> IKE_AUTH exchange normally has message ID 1 (ignore EAP / IKE_INTERMEDIATE)
> the first CREATE_CHILD_SA normally has Message ID 2
> seeing packets with older IDs dropped is most likely due to re-transmits; for instance, the IKE_AUTH initiator getting impatient with the responder taking so long with crypto and retransmitting.

That is only true for the original initiator.
The first CREATE_CHILD_SA request from the responder has msgid 0

**Comment by letoams** [comment]
﻿
﻿
﻿
On Jul 26, 2021, at 15:22, cagney ***@***.***> wrote:
> ﻿
> Just an aside,
> 
> IKE_SA_INIT exchange always has message ID 0
> IKE_AUTH exchange normally has message ID 1 (ignore EAP / IKE_INTERMEDIATE)
> the first CREATE_CHILD_SA normally has Message ID 2
> seeing packets with older IDs dropped is most likely due to re-transmits; for instance, the IKE_AUTH initiator getting impatient with the responder taking so long with crypto and retransmitting.

That is only true for the original initiator.
The first CREATE_CHILD_SA request from the responder has msgid 0

**Comment by kavinda-forcepoint** [comment]
The following SELinux-based fixes resolve this unexpected state deletion bug:
 
- https://github.com/libreswan/libreswan/commit/4b076eaabf35e60f493dcef218ff70c56eabdfd3
- https://github.com/libreswan/libreswan/pull/483

@cagney has worked on an architectural level solution to this problem as well.

@cagney: Could you please add any final comments you think is necessary for this issue and close it?

**Comment by cagney** [comment]
Just that it is fixed.
