### ISSUE TITLE
It doesn't find cert.h

### ISSUE THREAD

**Issue by yurivict** [libreswan/libreswan#447]
pkg-config finds this header:
```
$ pkg-config --cflags nss
-I/usr/local/include -I/usr/local/include/nss -I/usr/local/include/nspr 
```
yet the build fails:
In file included from /disk-samsung/freebsd-ports/net/libreswan/work/libreswan-4.4/lib/libswan/x509dn.c:29:
../../include/x509.h:28:10: fatal error: 'cert.h' file not found

**Comment by cagney** [comment]
Without seeing the full command line, there's little hope of this being debugged.

**Comment by yurivict** [comment]
```
cc -DHAS_SUN_LEN -DNEED_SIN_LEN -DHAVE_NETINET6_IN_H -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -pthread -std=gnu99 -g -Werror -Wall -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wmissing-declarations -Wredundant-decls -Wnested-externs -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-all -fno-strict-aliasing -fPIE -DPIE -DNSS_IPSEC_PROFILE -DXFRM_LIFETIME_DEFAULT=30 -DUSE_IKEv1 -DBSD_KAME -DUSE_DNSSEC -DDEFAULT_DNSSEC_ROOTKEY_FILE=\""/var/lib/unbound/root.key"\" -DLIBCURL -DHAVE_NM -DAUTH_HAVE_PAM -DUSE_3DES -DUSE_AES -DUSE_CAMELLIA -DUSE_CHACHA -DUSE_DH31 -DUSE_MD5 -DUSE_SHA1 -DUSE_SHA2 -DUSE_PRF_AES_XCBC -DUSE_NSS_KDF -DDEFAULT_RUNDIR=\"/var/run/pluto\" -DIPSEC_CONF=\"/usr/local/etc/ipsec.conf\" -DIPSEC_CONFDDIR=\"/usr/local/etc/ipsec.d\" -DIPSEC_NSSDIR=\"/usr/local/etc/ipsec.d\" -DIPSEC_CONFDIR=\"/usr/local/etc\" -DIPSEC_EXECDIR=\"/usr/local/libexec/ipsec\" -DIPSEC_SBINDIR=\"/usr/local/sbin\" -DIPSEC_VARDIR=\"/var\" -DPOLICYGROUPSDIR=\"/usr/local/etc/ipsec.d/policies\" -DIPSEC_SECRETS_FILE=\"/usr/local/etc/ipsec.secrets\" -DFORCE_PR_ASSERT -DUSE_FORK=1 -DUSE_VFORK=0 -DUSE_DAEMON=0 -DUSE_PTHREAD_SETSCHEDPRIO=1 -DGCC_LINT \
	-I/usr/pkg/include -I. -I../../OBJ.freebsd.amd64/lib/libswan -I../../include -I/usr/pkg/include/nspr -I/usr/pkg/include/nss/nss \
	-DHERE_BASENAME=\"initaddr.c\" -O2 -pipe -fno-omit-frame-pointer  -I/disk-samsung/freebsd-ports/net/libreswan/work/libreswan-4.4/include/unbound -fstack-protector-strong -fno-strict-aliasing  \
	-MF ../../OBJ.freebsd.amd64/lib/libswan/initaddr.d \
	-MP -MMD -MT initaddr.o \
	-o ../../OBJ.freebsd.amd64/lib/libswan/initaddr.o \
	-c /disk-samsung/freebsd-ports/net/libreswan/work/libreswan-4.4/lib/libswan/initaddr.c
In file included from /disk-samsung/freebsd-ports/net/libreswan/work/libreswan-4.4/lib/libswan/x509dn.c:29:
../../include/x509.h:28:10: fatal error: 'cert.h' file not found
#include <cert.h>
         ^~~~~~~~
```

**Comment by cagney** [comment]
This is the netbsd line:

cc -DHAS_SUN_LEN -DNEED_SIN_LEN -DHAVE_NETINET6_IN_H -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -pthread -std=gnu99 -g -Werror -Wall -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wmissing-declarations -Wredundant-decls -Wnested-externs -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-all -fno-strict-aliasing -fPIE -DPIE -DNSS_IPSEC_PROFILE -DXFRM_LIFETIME_DEFAULT=30 -DUSE_IKEv1 -DBSD_KAME -DUSE_DNSSEC -DDEFAULT_DNSSEC_ROOTKEY_FILE=\""/var/lib/unbound/root.key"\" -DLIBCURL -DHAVE_NM -DAUTH_HAVE_PAM -DUSE_3DES -DUSE_AES -DUSE_CAMELLIA -DUSE_CHACHA -DUSE_DH31 -DUSE_MD5 -DUSE_SHA1 -DUSE_SHA2 -DUSE_PRF_AES_XCBC -DUSE_NSS_KDF -DDEFAULT_RUNDIR=\"/var/run/pluto\" -DIPSEC_CONF=\"/usr/local/etc/ipsec.conf\" -DIPSEC_CONFDDIR=\"/usr/local/etc/ipsec.d\" -DIPSEC_NSSDIR=\"/usr/local/etc/ipsec.d\" -DIPSEC_CONFDIR=\"/usr/local/etc\" -DIPSEC_EXECDIR=\"/usr/local/libexec/ipsec\" -DIPSEC_SBINDIR=\"/usr/local/sbin\" -DIPSEC_VARDIR=\"/var\" -DPOLICYGROUPSDIR=\"/usr/local/etc/ipsec.d/policies\" -DIPSEC_SECRETS_FILE=\"/usr/local/etc/ipsec.secrets\" -DFORCE_PR_ASSERT -DUSE_FORK=1 -DUSE_VFORK=0 -DUSE_DAEMON=0 -DUSE_PTHREAD_SETSCHEDPRIO=1 -DGCC_LINT \
        -I/usr/pkg/include -I. -I../../OBJ.netbsd.evbarm/lib/libswan -I../../include -I/usr/pkg/include/nspr -I/usr/pkg/include/nss/nss \
        -DHERE_FILENAME=\"lib/libswan/x509dn.c\" \
         \
        -MF ../../OBJ.netbsd.evbarm/lib/libswan/x509dn.d \
        -MP -MMD -MT x509dn.o \
        -o ../../OBJ.netbsd.evbarm/lib/libswan/x509dn.o \
        -c /home/cagney/libreswan/main/lib/libswan/x509dn.c

it looks identical

(the only thing I notice is /usr/pkg/include should be further down the path list but that is the same for both)

**Comment by yurivict** [comment]
I solved this and similar issues by copying the ```netbsd.mk``` file adding this to ports's Makefile:
```
MAKE_ARGS=      PKG_BASE=${LOCALBASE} \
                NSS_CFLAGS="`pkg-config --cflags nss`" NSPR_LDFLAGS="`pkg-config --libs nss`" \
                USE_PTHREAD_SETSCHEDPRIO=false \
                WERROR_CFLAGS=""  \
                PYTHON_BINARY=${PYTHON_CMD}
```

```pkg-config --cflags --libs nss``` knows best what flags ```nss``` needs. Same is true for ```unbound```.

**Comment by cagney** [comment]
FYI, pkg-config things it knows best.   It ends up specifying more dynamic libraries than libreswan needs.

**Comment by yurivict** [comment]
Then this is a bug in the package's .pc file. They return same libraries that the static build needs when dynamic build doesn't need proxy dependencies.

I reported the bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1712418

**Comment by cagney** [comment]
I suspect:
```
pkg-config --cflags nss
```
outputs:
```
-I/usr/pkg/include/nss -I/usr/pkg/include/nspr
```
which is the reverse of the above?
