### ISSUE TITLE
ipsec newhostkey: unknown option `--output'

### ISSUE THREAD

**Issue by yurivict** [libreswan/libreswan#450]
I tried the command from the website https://libreswan.org/wiki/Host_to_host_VPN and it failed:
```
$ sudo ipsec newhostkey --output /usr/local/etc/ipsec.d/west.example.com.secret
ipsec newhostkey: unknown option `--output'
```

**Comment by letoams** [comment]
You can omit the output file as it is no longer needed. I will update the web page

**Comment by paulwouters** [comment]
wiki updated.
