### ISSUE TITLE
IKE_AUTH redirect response contains CHILD SA

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#453]
| **parse ISAKMP Message:
|    initiator SPI: d7 43 4f 0a  b3 b0 a6 15
|    responder SPI: fa bd b8 38  df bb e0 03
|    next payload type: ISAKMP_NEXT_v2SK (0x2e)
|    ISAKMP version: IKEv2 version 2.0 (rfc4306/rfc5996) (0x20)
|    exchange type: ISAKMP_v2_IKE_AUTH (0x23)
|    flags: ISAKMP_FLAG_v2_MSG_RESPONSE (0x20)
|    Message ID: 1 (00 00 00 01)
|    length: 239 (00 00 00 ef)
|  processing version=2.0 packet with exchange type=ISAKMP_v2_IKE_AUTH (35)
| I am the IKE SA Original Initiator receiving an IKEv2 IKE_AUTH response 
| State DB: found IKEv2 state #1 in PARENT_I2 (find_v2_ike_sa)
| #1 is idle
| #1 idle
| unpacking clear payload
| Now let's proceed with payload (ISAKMP_NEXT_v2SK)
| ***parse IKEv2 Encryption Payload:
|    next payload type: ISAKMP_NEXT_v2N (0x29)
|    flags: none (0x0)
|    length: 211 (00 d3)
| processing payload: ISAKMP_NEXT_v2SK (len=207)
| #1 in state PARENT_I2: sent IKE_AUTH request
| stripping 1 octets as pad
| #1 ikev2 ISAKMP_v2_IKE_AUTH decrypt success
| Now let's proceed with payload (ISAKMP_NEXT_v2N)
| **parse IKEv2 Notify Payload:
|    next payload type: ISAKMP_NEXT_v2IDr (0x24)
|    flags: none (0x0)
|    length: 14 (00 0e)
|    Protocol ID: IKEv2_SEC_PROTO_NONE (0x0)
|    SPI size: 0 (00)
|    Notify Message Type: v2N_REDIRECT (0x4017)
| processing payload: ISAKMP_NEXT_v2N (len=6)
| Now let's proceed with payload (ISAKMP_NEXT_v2IDr)
| **parse IKEv2 Identification - Responder - Payload:
|    next payload type: ISAKMP_NEXT_v2AUTH (0x27)
|    flags: none (0x0)
|    length: 12 (00 0c)
|    ID type: ID_FQDN (0x2)
|    reserved: 00 00 00
| processing payload: ISAKMP_NEXT_v2IDr (len=4)
| Now let's proceed with payload (ISAKMP_NEXT_v2AUTH)
| **parse IKEv2 Authentication Payload:
|    next payload type: ISAKMP_NEXT_v2SA (0x21)
|    flags: none (0x0)
|    length: 72 (00 48)
|    auth method: IKEv2_AUTH_SHARED (0x2)
| processing payload: ISAKMP_NEXT_v2AUTH (len=64)
| Now let's proceed with payload (ISAKMP_NEXT_v2SA)
| **parse IKEv2 Security Association Payload:
|    next payload type: ISAKMP_NEXT_v2TSi (0x2c)
|    flags: none (0x0)
|    length: 36 (00 24)
| processing payload: ISAKMP_NEXT_v2SA (len=32)
| Now let's proceed with payload (ISAKMP_NEXT_v2TSi)
| **parse IKEv2 Traffic Selector - Initiator - Payload:
|    next payload type: ISAKMP_NEXT_v2TSr (0x2d)
|    flags: none (0x0)
|    length: 24 (00 18)
|    number of TS: 1 (01)
| processing payload: ISAKMP_NEXT_v2TSi (len=16)
| Now let's proceed with payload (ISAKMP_NEXT_v2TSr)
| **parse IKEv2 Traffic Selector - Responder - Payload:
|    next payload type: ISAKMP_NEXT_v2NONE (0x0)
|    flags: none (0x0)
|    length: 24 (00 18)
|    number of TS: 1 (01)
| processing payload: ISAKMP_NEXT_v2TSr (len=16)
| selected state microcode Initiator: process IKE_AUTH response
| calling processor Initiator: process IKE_AUTH response
|   #1 spent 1.8 (7.17) milliseconds
| received v2N_REDIRECT in IKE_AUTH reply
| ***parse IKEv2 Redirect Notify Data:
|    GW Identity type: GW_IPv4 (0x1)
|    GW Identity length: 4 (04)
| parsing 4 raw bytes of IKEv2 Notify Payload into REDIRECT address
| REDIRECT address
|   c0 01 03 21                                          ...!
|    GW Identity IP: 192.1.3.33

**Comment by vukasink** [comment]
This issue was solved with #467, I think it can be closed (cleaning the backlog...)

**Comment by paulwouters** [comment]
thanks for the note, closing
