### ISSUE TITLE
AES-XCBC Phase 2 Algorithm

### ISSUE THREAD

**Issue by sogyals429** [libreswan/libreswan#457]
Hi, I'm currently in the process of setting up a site-to-site VPN with libreswan, and one of the requirements is to use 
`aes-xcbc` as phase 2 algorithm. Looking at the docs I see that libreswan does support AES-XCBC-MAC as AH. However when I set that in my config I get the following error. `phase2alg=aes256-aesxcbc`. 

The error ```Failed to add connection "NetsEU", esp="aes256-aesxcbcmac" is invalid: ESP integrity algorithm 'aesxcbcmac' is not recognized```.

Any suggestions about what I have done wrong would be appreciated.

**Comment by cagney** [comment]
I'm guessing this is IKEv1?  Did you mean AH or ESP?  Anyway, the name to use is aes_xcbc.
There's a table of supported algorithms and names at the start of the log file.
The test ah-pluto-05 on testing.libreswan.org shows IKEv1 AH working and a number of tests show at least IKEv2 aes-aes_xcbc working .

**Comment by paulwouters** [comment]
There is some confusion on how you used the term AH here. Ancient IPsec allowed AH+ESP where ESP had no authentication, but this mode is long dead. So ESP always has authentication. But if you don't want encryption, you can use AH for authentication-only.

If you really want AH without any encryption:

type=ah
phase2alg=aes_xcbc

If you meant ESP with encryption:

type=esp    (the default, can be omitted)
phase2alg=aes256-aes_xcbc

**Comment by sogyals429** [comment]
@paulwouters thanks yes I had to go with `phase2alg=aes256-aes_xcbc`. Thanks for the information.
