### ISSUE TITLE
Fixup IKEv2 with right=%any and two different subnets

### ISSUE THREAD

**Issue by letoams** [libreswan/libreswan#464]
See test cases:

ikev1-rw-multiple-subnets
ikev2-rw-multiple-subnets
ikev2-rw-multiple-subnets-2
ikev2-rw-multiple-subnets-3

This was the old bug: https://bugs.libreswan.org/show_bug.cgi?id=298
 
the workaround posted there might just be worth pulling in.

**Comment by bleve** [comment]
See also test cases:

ikev1-rw-multiple-subnets
ikev2-rw-multiple-subnets

**Comment by paulwouters** [comment]
This seems to work now from an IKE negotiation point of view. But test causes do show an odd martian packet :/

**Comment by cagney** [comment]
> This seems to work now from an IKE negotiation point of view. But test causes do show an odd martian packet :/

We've martian's throughout the testsuite.
