### ISSUE TITLE
awk: calling undefined function gensub

### ISSUE THREAD

**Issue by yurivict** [libreswan/libreswan#480]
The build prints:
```
awk: calling undefined function gensub
 input record number 11, file ../OBJ.freebsd.amd64/configs/ipsec.secrets.5.tmp
 source line number 7
: ignoring seemingly bogus xmlto exit status
xmlto man ../OBJ.freebsd.amd64/configs/ipsec.secrets.5.tmp -o ../OBJ.freebsd.amd64/configs || true
mv ../OBJ.freebsd.amd64/configs/ipsec.conf.5.tmp.tmp ../OBJ.freebsd.amd64/configs/ipsec.conf.5.tmp
awk: calling undefined function gensub
 input record number 11, file ../OBJ.freebsd.amd64/configs/ipsec.conf.5.tmp
 source line number 7
: ignoring seemingly bogus xmlto exit status
xmlto man ../OBJ.freebsd.amd64/configs/ipsec.conf.5.tmp -o ../OBJ.freebsd.amd64/configs || true
Note: Writing ipsec.secrets.5
test -z ""
```

OS: FreeBSD 13
Version: 4.4

**Comment by cagney** [comment]
packaging/utils/refnames.sh invokes `awk`
FreeBSD awk doesn't include gensub()?  NetBSD's seems to.

**Comment by yurivict** [comment]
On FreeBSD ```awk``` from base doesn't include ```gensub()```.
But ```gawk``` from ports does.
I patched the port to use ```gawk``` in place of ```awk```.

**Comment by cagney** [comment]
(I'm pretty sure it was a GNU extension, but one so useful that it's been added elsewhere)
(I suspect the build will stumble on when gawk isn't installed :-()

Anyway, I need to think about how refnames.sh is invoked.

**Comment by yurivict** [comment]
> (I'm pretty sure it was a GNU extension, but one so useful that it's been added elsewhere)

FreeBSD normally doesn't add GNU extensions. FreeBSD's license is BSD, and they have always kept away from anything GNU.

But there's no problem now when ```libreswan``` is installed from port/package (normal way of installing software) - because the port uses ```awk=gawk```.
