### ISSUE TITLE
Issue with tunnel inside openstack

### ISSUE THREAD

**Issue by ahmedsameh** [libreswan/libreswan#482]
I have configured tunnels inside my test environment successfully, but when moving the same configuration to openstack, TCP handshake is not happening.
In openstack we have a centos machine that acts as the gateway, and only from it I can access the VMs with ipsec configured.
```
conn clear
	auto=ondemand
	type=passthrough
	authby=never
	left=%defaultroute
	right=%group

conn private
	auto=ondemand
	type=transport
	authby=rsasig
	failureshunt=drop
	negotiationshunt=drop
	ikev2=insist
	fragmentation=yes
	mtu=1000
	# left
	left=%defaultroute
	leftcert={{ cert_name_pattern }}
	leftid=%fromcert
        leftrsasigkey=%cert
	# right
	rightrsasigkey=%cert
	rightid=%fromcert
	right=%opportunisticgroup

conn private-or-clear
	auto=ondemand
	type=transport
	authby=rsasig
	failureshunt=passthrough
	negotiationshunt=passthrough
	ikev2=insist
	fragmentation=yes
	mtu=1000
	# left
	left=%defaultroute
	leftcert={{ cert_name_pattern }}
	leftid=%fromcert
        leftrsasigkey=%cert
	# right
	rightrsasigkey=%cert
	rightid=%fromcert
	right=%opportunisticgroup
```
My private-or-clear definitions:
```
10.245.24.0/23
10.245.26.0/24
10.216.0.0/16
10.90.0.0/16
192.168.117.0/24
10.245.29.0/24
192.168.122.0/24
```
ipsec status , note 10.245.25.39 is the second ipsec VM
```
000 Total IPsec connections: loaded 14, active 0
000  
000 State Information: DDoS cookies not required, Accepting new IKE connections
000 IKE SAs: total(2), half-open(2), open(0), authenticated(0), anonymous(0)
000 IPsec SAs: total(0), authenticated(0), anonymous(0)
000  
000 #24: "private-or-clear#10.245.24.0/23"[1] ...10.245.24.6:500 STATE_PARENT_I1 (sent v2I1, expected v2R1); EVENT_v2_RETRANSMIT in 22s; idle; import:local rekey
000 #24: pending CHILD SA for "private-or-clear#10.245.24.0/23"[1] ...10.245.24.6
000 #25: "private-or-clear#10.245.24.0/23"[2] ...10.245.25.39:500 STATE_PARENT_I1 (sent v2I1, expected v2R1); EVENT_v2_RETRANSMIT in 24s; idle; import:local rekey
000 #25: pending CHILD SA for "private-or-clear#10.245.24.0/23"[2] ...10.245.25.39
```

**Comment by letoams** [comment]
On Tue, 27 Jul 2021, Ahmed Sameh Gheith wrote:

> I have configured tunnels inside my test environment successfully, but when moving the same configuration to openstack, TCP
> handshake is not happening.
> In openstack we have a centos machine that acts as the gateway, and only from it I can access the VMs with ipsec configured.

If you don't have direct host to host connectivity, then you cannot use
the configuration below as that assumes you have unfiltered direct
access from all nodes in the group.

If the centos machine NAT's, you cannot deploy like this. If the centos
machine forwards without NAT, perhaps it just needs to be configured to
allow this traffic to be FORWARDed through it.

Paul

**Comment by ahmedsameh** [comment]
@paulwouters thanks for your clarification, I didn't think NAT can be happening as the communication is between 2 VMs at the same subnet.
However after checking routing table before and after starting ipsec, I found the link local route is removed, and all traffic is forwarded to the gateway, is that the default behaviour, and if so, can I have more details about why.
```
[root@test-ipsec1 ~]# ip r
default via 10.245.24.1 dev eth0 
10.245.24.0/23 dev eth0 proto kernel scope link src 10.245.25.39 
169.254.0.0/16 dev eth0 scope link metric 1002 
169.254.32.0/23 dev eth0 proto static scope link 
169.254.169.254 via 10.245.24.110 dev eth0 proto static 
[root@test-ipsec1 ~]# systemctl start ipsec
[root@test-ipsec1 ~]# ip r
default via 10.245.24.1 dev eth0 
10.90.0.0/16 via 10.245.24.1 dev eth0 mtu 1000 
10.216.0.0/16 via 10.245.24.1 dev eth0 mtu 1000 
10.245.24.0/23 via 10.245.24.1 dev eth0 mtu 1000 
10.245.26.0/24 via 10.245.24.1 dev eth0 mtu 1000 
10.245.29.0/24 via 10.245.24.1 dev eth0 mtu 1000 
169.254.0.0/16 dev eth0 scope link metric 1002 
169.254.32.0/23 dev eth0 proto static scope link 
169.254.169.254 via 10.245.24.110 dev eth0 proto static 
192.168.117.0/24 via 10.245.24.1 dev eth0 mtu 1000 
```

**Comment by letoams** [comment]
It looks like you set mtu=1000 which causes those routes to be added. Also 1000 seems very very wrong 

Sent using a virtual keyboard on a phone

**Comment by ahmedsameh** [comment]
@paulwouters The 1000 mtu was for testing, I believe I started with having mtu set to 1400 according to that redhat document https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/securing_networks/configuring-a-vpn-with-ipsec_securing-networks, I removed the mtu record, and now I have a normal routing table, and started to have shunts, thanks to your help :)

I have a request, can you please proof the configuration at https://libreswan.org/wiki/HOWTO:_Opportunistic_IPsec , I see we have `negotiationshunt=drop` in both `clear-or-private` and `private-or-clear`, however `negotiationshunt` at https://libreswan.org/man/ipsec.conf.5.html valid options are hold (the default) or passthrough.

P.S. I still don't know the logic behind why changing mtu affects my routing table, I appreciate if you can point me in the right direction.

**Comment by bleve** [comment]
Reason for that is mtu manipulation.

**Comment by letoams** [comment]
The wiki is wrong, will fix.

To get an MTU activated for a specific IP or subnet only, you cannot set the interface mtu. You can only add a route that contains an mtu xxx value. For some reason for you this seems to cause a wrong route, i.e a wrong “via” or “src” or “dev” ?

Sent using a virtual keyboard on a phone
