### ISSUE TITLE
Build on raspberry pi fails 

### ISSUE THREAD

**Issue by imakiro** [libreswan/libreswan#49]
When trying to compile the programm from source, I get this error on ARM

`cc   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-all -fno-strict-aliasing -fPIE -DPIE -DFORCE_PR_ASSERT -DDNSSEC -DKLIPS -DLIBCURL -DUSE_MD5 -DHAVE_NM -DUSE_SHA2 -DUSE_SHA1 -DFIPSPRODUCTCHECK=\"/etc/system-fips\" -DIPSEC_CONF=\"/etc/ipsec.conf\" -DIPSEC_CONFDDIR=\"/etc/ipsec.d\" -DIPSEC_NSSDIR=\"/etc/ipsec.d\" -DIPSEC_CONFDIR=\"/etc\" -DIPSEC_EXECDIR=\"/usr/local/libexec/ipsec\" -DIPSEC_SBINDIR=\"/usr/local/sbin\" -DIPSEC_VARDIR=\"/var\" -DPOLICYGROUPSDIR=\"/etc/ipsec.d/policies\" -DSHARED_SECRETS_FILE=\"/etc/ipsec.secrets\" -DRETRANSMIT_INTERVAL_DEFAULT="500" -DGCC_LINT -DALLOW_MICROSOFT_BAD_PROPOSAL -Werror -Wall -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wmissing-declarations -Wredundant-decls -Wnested-externs -I/root/libreswan-3.16/ports/linux/include -I/root/libreswan-3.16/ports/linux/include -I/root/libreswan-3.16/ports/linux/include -I/root/libreswan-3.16/ports/linux/include  -I/root/libreswan-3.16/programs/pluto/linux26 -I/root/libreswan-3.16/include -I/root/libreswan-3.16/lib/libcrypto -I/root/libreswan-3.16/linux/include      -DNETKEY_SUPPORT -DKERNEL26_HAS_KAME_DUPLICATES -DPFKEY  -DUSE_TWOFISH -DUSE_SERPENT -DKLIPS -DPFKEY    -DUSE_AES -DUSE_3DES -DUSE_SHA2 -DUSE_SHA1 -DUSE_MD5 -DUSE_CAMELLIA   -DXAUTH_HAVE_PAM -DLIBCURL    -DHAVE_LIBCAP_NG -DHAVE_NM -I/usr/include/nss -I/usr/include/nspr     \

        -MMD -MF ./crypt_dbg.d \

        -o ./crypt_dbg.o \

        -c /root/libreswan-3.16/programs/pluto/crypt_dbg.c

/root/libreswan-3.16/programs/pluto/crypt_dbg.c: In function ‘symkey_bytes’:

/root/libreswan-3.16/programs/pluto/crypt_dbg.c:102:2: error: implicit declaration of function ‘PK11_Decrypt’ [-Werror=implicit-function-declaration]

/root/libreswan-3.16/programs/pluto/crypt_dbg.c:102:2: error: nested extern declaration of ‘PK11_Decrypt’ [-Werror=nested-externs]

cc1: all warnings being treated as errors

../../../mk/depend.mk:28: recipe for target 'crypt_dbg.o' failed

make[3]: *** [crypt_dbg.o] Error 1
make[3]: Leaving directory '/root/libreswan-3.16/OBJ.linux.arm/programs/pluto'
Makefile:426: recipe for target 'local-base' failed
make[2]: *** [local-base] Error 2
make[2]: Leaving directory '/root/libreswan-3.16/programs/pluto'
../mk/subdirs.mk:33: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/libreswan-3.16/programs'
/root/libreswan-3.16/mk/subdirs.mk:33: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by letoams** [comment]
You need a newer NSS version

**Comment by imakiro** [comment]
build on RPI is OK on raspbian 8, but not 7. Noted thanks !
