### ISSUE TITLE
ipsec auto --asynchronous --up <child> isn't async?

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#490]
It should detach after logging:
```
  002 "labeled" #2: initiating Child SA using IKE SA #1 
```
but instead remains attached until the exchange completes (which could be slow).

Looking at the code, submit_v2_CREATE_CHILD_SA_new_child() isn't passed "background".

**Comment by bleve** [comment]
Yes, that's exactly what I found from output.

If IKE SA is not there it works as expected but when only kicking Child SA it works like without --asynchronous.
