### ISSUE TITLE
how to close conn or break client access net by libreswan when deleted client's cert on server

### ISSUE THREAD

**Issue by bugfan** [libreswan/libreswan#493]
any api here?

**Comment by bleve** [comment]
You need crl (certificate revocation list) distribution uri in your certificates and then you can enable crlcheckinterval=6h for example. that will cause automatic loading of certificate revocation list from url provided in certificates...

When libreswan gets new revocation list it stops accepting closed certificates.

This is how certificate revocation works.

There is also support for OCSP checking but that requires more complicated setup on CA side than normal web server.

**Comment by bugfan** [comment]
ok
