### ISSUE TITLE
why username& password can't login ,but certificate can login!

### ISSUE THREAD

**Issue by bugfan** [libreswan/libreswan#495]

**Comment by paulwouters** [comment]
please invest time in writing an issue report if you want us to invest time in helping you

**Comment by bugfan** [comment]
I 'm sorry about that! i mean my  mobile phone（iphone，ios） can only use VPN by configuring. Mobileconfig, and can't log in with account and password

**Comment by letoams** [comment]
On Thu, 19 Aug 2021, Fan wrote:

> I 'm sorry about that! i mean my mobile phone（iphone，ios） can only use VPN by
> configuring. Mobileconfig, and can't log in with account and password

The user/password of iOS is using EAPTLS. libreswan currently not does
support that, but efforts are on the way to get it supported in the next
next version (4.6)

For IKEv1, user/password uses XAUTH/ModeConfig, which is supported by
libreswan.

**Comment by bugfan** [comment]
ok thanks！by the way ,does libreswan support ipv6?

**Comment by letoams** [comment]
On Thu, 19 Aug 2021, Fan wrote:

> ok thanks！by the way ,does libreswan support ipv6?

yes

**Comment by bugfan** [comment]
> On Thu, 19 Aug 2021, Fan wrote: I 'm sorry about that! i mean my mobile phone（iphone，ios） can only use VPN by configuring. Mobileconfig, and can't log in with account and password
> The user/password of iOS is using EAPTLS. libreswan currently not does support that, but efforts are on the way to get it supported in the next next version (4.6) For IKEv1, user/password uses XAUTH/ModeConfig, which is supported by libreswan.

got it!
