### ISSUE TITLE
Linux Libreswan 4.4  IKE  NO_PROPOSAL_CHOSEN

### ISSUE THREAD

**Issue by config103** [libreswan/libreswan#503]
hello i am running libreswan on aws ec2 . the libreswan version is Linux Libreswan 4.4 (netkey) on 4.14.243-185.433.amzn2.x86_64.  The vpn client  is ikuai router. I failed to connect after configuration.  The  last  /var/log/pluto.log Show: responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN.

here is my  ipsec configuration file 
```shell
# more /etc/ipsec.d/test-albt.conf

conn aws-to-local
    auto=start
    type=tunnel
    keyexchange=ike

    ikev2=yes
    ike=aes128-sha1;modp1024
    ikelifetime=86400s
    authby=secret
    rekey=yes

    phase2=esp
    phase2alg=aes256-sha1
    pfs=no
    salifetime=86400s

    left=192.168.88.108
    leftsubnet=192.168.88.0/21
    leftid= vpc server  public network
    leftnexthop=%defaultroute

    right= ikuai public network
    rightsubnet=192.168.66.0/23
    rightid=ikuai public network
    rightnexthop=%defaultroute
```

the last run log on /var/log/pluto.log
```shell
Aug 26 11:27:00.983982: testing HMAC_MD5:
Aug 26 11:27:00.983987:   RFC 2104: MD5_HMAC test 1
Aug 26 11:27:00.984136:   RFC 2104: MD5_HMAC test 2
Aug 26 11:27:00.984269:   RFC 2104: MD5_HMAC test 3
Aug 26 11:27:00.984421: 1 CPU cores online
Aug 26 11:27:00.984427: starting up 1 helper threads
Aug 26 11:27:00.984463: started thread for helper 0
Aug 26 11:27:00.984470: using Linux xfrm kernel support code on #1 SMP Mon Aug 9 05:55:52 UTC 2021
Aug 26 11:27:00.985136: selinux support is NOT enabled.
Aug 26 11:27:00.985156: systemd watchdog for ipsec service configured with timeout of 200000000 usecs
Aug 26 11:27:00.985160: watchdog: sending probes every 100 secs
Aug 26 11:27:00.987637: seccomp security disabled
Aug 26 11:27:00.988795: seccomp security disabled for crypto helper 1
Aug 26 11:27:00.988864: "aws-to-local": failed to add connection: IKE DH algorithm 'modp1024' is not supported
Aug 26 11:27:00.988945: listening for IKE messages
Aug 26 11:27:00.988992: Kernel supports NIC esp-hw-offload
Aug 26 11:27:00.989056: adding UDP interface eth0 192.168.88.108:500
Aug 26 11:27:00.989084: adding UDP interface eth0 192.168.88.108:4500
Aug 26 11:27:00.989101: adding UDP interface lo 127.0.0.1:500
Aug 26 11:27:00.989118: adding UDP interface lo 127.0.0.1:4500
Aug 26 11:27:00.989139: adding UDP interface lo [::1]:500
Aug 26 11:27:00.990219: loading secrets from "/etc/ipsec.secrets"
Aug 26 11:27:00.990268: loading secrets from "/etc/ipsec.d/albt-test.secrets"
Aug 26 11:27:00.990611: initiating all conns with alias='aws-to-local'
Aug 26 11:27:00.990624: no connection named "aws-to-local"
Aug 26 11:27:04.374255: forgetting secrets
Aug 26 11:27:04.374298: loading secrets from "/etc/ipsec.secrets"
Aug 26 11:27:04.374328: loading secrets from "/etc/ipsec.d/albt-test.secrets"
Aug 26 11:30:01.051873: packet from server—public_net:500: ISAKMP_v2_IKE_SA_INIT message received on 192.168.88.108:500 but no suitable connection found with IKEv2 policy
Aug 26 11:30:01.051908: packet from server-public-net: responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN
Aug 26 11:34:22.944317: packet from server-public-net: initial Main Mode message received but no connection has been authorized with policy PSK
Aug 26 11:34:23.939733: packet from server-public-net: initial Main Mode message received but no connection has been authorized with policy PSK
Aug 26 11:34:24.941667: packet from server-public-net: initial Main Mode message received but no connection has been authorized with policy PSK
Aug 26 11:34:27.944334: packet from server-public-net: initial Main Mode message received but no connection has been authorized with policy PSK
Aug 26 11:34:44.431675: packet from server-public-net: ISAKMP_v2_IKE_SA_INIT message received on 192.168.88.108:500 but no suitable connection found with IKEv2 policy
Aug 26 11:34:44.431710: packet from server-public-net: responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN
Aug 26 11:35:23.142349: packet from server-public-net: ISAKMP_v2_IKE_SA_INIT message received on 192.168.88.108:500 but no suitable connection found with IKEv2 policy
Aug 26 11:35:23.142388: packet from server-public-net: responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN
Aug 26 11:36:01.048396: packet from server-public-net: ISAKMP_v2_IKE_SA_INIT message received on 192.168.88.108:500 but no suitable connection found with IKEv2 policy
Aug 26 11:36:01.048435: packet from server-public-net: responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN
Aug 26 11:37:50.188050: packet from server-public-net: ISAKMP_v2_IKE_SA_INIT message received on 192.168.88.108:500 but no suitable connection found with IKEv2 policy
Aug 26 11:37:50.188087: packet from server-public-net: responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN
Aug 26 11:38:17.543758: packet from server-public-net: ISAKMP_v2_IKE_SA_INIT message received on 192.168.88.108:500 but no suitable connection found with IKEv2 policy
Aug 26 11:38:17.543828: packet from server-public-net: responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN
Aug 26 11:42:01.047555: packet from server-public-net: ISAKMP_v2_IKE_SA_INIT message received on 192.168.88.108:500 but no suitable connection found with IKEv2 policy
Aug 26 11:42:01.047593: packet from server-public-net: responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN
Aug 26 11:48:01.048133: packet from server-public-net: ISAKMP_v2_IKE_SA_INIT message received on 192.168.88.108:500 but no suitable connection found with IKEv2 policy
Aug 26 11:48:01.048170: packet from server-public-net: responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN
Aug 26 11:54:01.047112: packet from server-public-net: ISAKMP_v2_IKE_SA_INIT message received on 192.168.88.108:500 but no suitable connection found with IKEv2 policy
Aug 26 11:54:01.047151: packet from server-public-net: responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN
```

The log on vpn client router is
```shell
Aug 26 20:00:01
14[ENC] parsed IKE_SA_INIT response 0 [ N(NO_PROP) ]

Aug 26 20:00:01
14[IKE] received NO_PROPOSAL_CHOSEN notify error
``` 

What caused it ：responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN

**Comment by config103** [comment]
> 
> Your leftid / rightid need to match in both ends. It doesn’t much matter what it is set to as long as both ends agree. Picking no id means it’s picks the default IP which if it is before NAT is unpredictable and this would never match Sent using a virtual keyboard on a phone
> […](#)
> On Aug 27, 2021, at 12:08, config103 ***@***.***> wrote: ﻿ what's mean does it mean i should change the configuration file /etc/ipsec.d/test-albt.conf about hte part of peer id like this ? ``shell right= my public network address rightsubnet=192.168.66.0/23 rightid= 192.168.66.1 rightnexthop=%defaultroute — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Now I have connected the optical modem to the router, and the router uses ADSL dial-up Internet access. After configuration, the pluto.log file does not show the problem of the 192.168.1.2 subnet. 

However，A new problem has arisen ，the server pluto.log
```shell
sent IKE_SA_INIT reply {auth=IKEv2 cipher=AES_CBC_128 integ=HMAC_SHA1_96 prf=HMAC_SHA1 group=MODP2048}
processing decrypted IKE_AUTH request: SK{IDi,N,IDr,AUTH,SA,TSi,TSr,N,N,N,N,N,N,N,N}
authentication failed: computed hash does not match hash received from peer ID_IPV4_ADDR '
``` 
the same time i discover the log from router:
```shell
09[IKE] remote host is behind NAT
Sep 1 15:24:00
09[CFG] no IDi configured, fall back on IP address
Sep 1 15:24:00
09[IKE] authentication of 'router  public ip' (myself) with pre-shared key
Sep 1 15:24:00
09[IKE] establishing CHILD_SA vpn-1{45}
Sep 1 15:24:00
09[ENC] generating IKE_AUTH request 1 [ IDi N(INIT_CONTACT) IDr AUTH SA TSi TSr N(MOBIKE_SUP) N(ADD_4_ADDR) N(ADD_4_ADDR) N(ADD_4_ADDR) N(ADD_4_ADDR) N(ADD_4_ADDR) N(EAP_ONLY) N(MSG_ID_SYN_SUP) ]
Sep 1 15:24:00
09[NET] sending packet: from router  public ip[4500] to  'aws ec2 elastic ip' [4500] (396 bytes)
Sep 1 15:24:00
12[NET] received packet: from 'aws ec2 elastic ip'[4500] to router  public ip[4500] (76 bytes)
Sep 1 15:24:00
12[ENC] parsed IKE_AUTH response 1 [ N(AUTH_FAILED) ]
Sep 1 15:24:00
12[IKE] received AUTHENTICATION_FAILED notify error
```
can you tell me what is the problem cause this and how to solve this ,if you need more log,  please tell me .Thanks

**Comment by config103** [comment]
i also find the Introduction to the router's vpn configuration document ,[https://www.ikuai8.com/index.php?option=com_content&view=article&id=139&Itemid=242](url)   (the page is  written in Chinese  ,sorry )
On this page, i read this ：
> 10. If IPsec passes NAT, you need to pay attention to the following points
> a) The "peer IP/domain name" of the server must be empty, it can only act as a server, and the server is not allowed to pass NAT.
> b) To start the server first, then start the client.

**Comment by letoams** [comment]
On Wed, 1 Sep 2021, config103 wrote:

>       Your leftid / rightid need to match in both ends.

> sent IKE_SA_INIT reply {auth=IKEv2 cipher=AES_CBC_128 integ=HMAC_SHA1_96 prf
> =HMAC_SHA1 group=MODP2048}
> processing decrypted IKE_AUTH request: SK{IDi,N,IDr,AUTH,SA,TSi,TSr,N,N,N,N,
> N,N,N,N}
> authentication failed: computed hash does not match hash received from peer 
> ID_IPV4_ADDR '

This likely means the wrong ID was used in calculating the PSK, assuming
you verified that you are using the right PSK on both ends.

> the same time i discover the log from router:
> 
> 09[IKE] remote host is behind NAT
> Sep 1 15:24:00
> 09[CFG] no IDi configured, fall back on IP address

So it uses its public IP as ID. So your libreswan client must use a
rightid=<ServerpublicIP>

**Comment by config103** [comment]
> 
> On Wed, 1 Sep 2021, config103 wrote: Your leftid / rightid need to match in both ends. sent IKE_SA_INIT reply {auth=IKEv2 cipher=AES_CBC_128 integ=HMAC_SHA1_96 prf =HMAC_SHA1 group=MODP2048} processing decrypted IKE_AUTH request: SK{IDi,N,IDr,AUTH,SA,TSi,TSr,N,N,N,N, N,N,N,N} authentication failed: computed hash does not match hash received from peer ID_IPV4_ADDR '
> This likely means the wrong ID was used in calculating the PSK, assuming you verified that you are using the right PSK on both ends.
> the same time i discover the log from router: 09[IKE] remote host is behind NAT Sep 1 15:24:00 09[CFG] no IDi configured, fall back on IP address
> So it uses its public IP as ID. So your libreswan client must use a rightid=<ServerpublicIP>

Thanks .I finally change the config like this 
```shell
    left=ec2 selfip
    leftsubnet= ec2 Internal subnet 
    leftid=ec2 Elastic IP
    leftnexthop=%defaultroute

    right= router public network
    rightsubnet=router Internal subnet 
    rightid=router public network
    rightnexthop=%dedfaultroute
```
and change the secrets configuration file like this
```shell
0.0.0.0 0.0.0.0 : PSK "psk character production "
```
it works . thank you for you help again. By the way  I have a question: in my client I have two different network segments like 192.168.97.0/23 and 192.168.87.0/24，both of them wants to connect to this ec2 Internal subnet, Most of the online tutorials are about a single network segment, how can I modify the configuration file to support multiple network segment connections？

**Comment by letoams** [comment]
Use subnets=a.b.c.0/24,d.e.f.0/24

Sent using a virtual keyboard on a phone
