### ISSUE TITLE
Cannot route error for different connections with same rightsubnets but different leftsubnets

### ISSUE THREAD

**Issue by avaughn0909** [libreswan/libreswan#504]
I have two connections that use 192.168.10.0/24 as their subnet (rightsubnet) with our side (left) using different subnets. One is ikev1 and the other is ikev2 the ikev1 connection routes fine but the ikev2 connection gets this `cannot route -- route already in use for <conn name>`. Here are snippets from each conn:

Not routing connection

```
type=tunnel
    authby=secret
    left=<our private-ip>
    leftid=<our peer-ip>
    leftsubnets=" 10.253.252.8/30 "
    right=<their peer-ip>
    rightsubnets=" 192.168.10.0/24 "
    auto=start
    ike=aes256-sha1;modp2048
    phase2alg=aes256-sha1;modp2048
    ikelifetime=28800
    salifetime=3600
    dpdaction=restart
    dpddelay=30
    dpdtimeout=120
    pfs=yes
    ikev2=insist 
```

Routed connection

```
type=tunnel
    authby=secret
    left=<our private-ip>
    leftid=<our peer-ip>
    leftsubnets=" 10.253.253.10/31"
    right=<their peer-ip>
    rightsubnets=" 192.168.10.0/24 "
    auto=start
    ike=aes256-sha1;modp1536
    phase2alg=aes256-sha1;modp1536
    ikelifetime=86400
    salifetime=3600
    dpdaction=restart
    dpddelay=30
    dpdtimeout=120
    pfs=yes
    ikev2=no
```

For context I am using version 4.1, these connections are for different tunnels for different orgs, and I am using NETKEY not KLIPS. I don't know if there is a bug in the way ikev1 overlap ips are handled as compared to ikev2 overlapip or if there is something I am missing to make this work because it seems like it should be just fine since our left ips differ in each connection.

**Comment by bleve** [comment]
This is not possible configuration. You can't overlap this way. You can't have two different remote locations with same subnet.

**Comment by avaughn0909** [comment]
So does this actually check if a route is matching exactly i.e. 127.0.0.1/32 == 127.0.0.1/32 or does this check actually look to see if a route is in another encryption domain i.e. 127.0.0.1/32 is in 127.0.0.0/24? I have connections on each of my three ec2 instances used as VPN endpoints that have overlapping amongst subnets but technically aren't they exact same routes so I want to make sure there isn't a bug somewhere.

**Comment by paulwouters** [comment]
You cannot have a remote IP range live at two locations at once.

when you do: ping 192.168.10.1 where would the packet need to go to?

routing is not based on source ip.

if you think you can route it with hacks like ip rule and/or NAT, then you can specify overlapip=yes in both connections. But you get to keep all the pieces if it breaks
