### ISSUE TITLE
libreswan refuses to use my updown script

### ISSUE THREAD

**Issue by davehouser1** [libreswan/libreswan#508]
**Problem** 
I am having two problems:
1. Currently, when trying to run `ipsec auto --up mytunnelroute`, ipsec does not run my up-client section of my script, and I continue to see the following. ipsec does not run the updown script I define in my config.
```
181 "mytunnelroute" #25: initiating IKEv2 connection
181 "mytunnelroute" #25: sent IKE_SA_INIT request
182 "mytunnelroute" #25: sent IKE_AUTH request {auth=IKEv2 cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_512 group=DH19}
010 "mytunnelroute" #26: STATE_PARENT_I2: retransmission; will wait 0.5 seconds for response
010 "mytunnelroute" #26: STATE_PARENT_I2: retransmission; will wait 1 seconds for response
010 "mytunnelroute" #26: STATE_PARENT_I2: retransmission; will wait 2 seconds for response
010 "mytunnelroute" #26: STATE_PARENT_I2: retransmission; will wait 4 seconds for response
010 "mytunnelroute" #26: STATE_PARENT_I2: retransmission; will wait 8 seconds for response
```
Also some times when I run the command above nothing happens...

2. at some point, I dont know when, problem 1, was not a problem. Before this problem I saw up-client run when trying to run `ipsec auto --up mytunnelroute`, however it seemed to fail and I would see " up-client output sh: /etc/myupdown.sh Permission denied" and "up-client command exitied with status 126", or something about a missing command (I don't remember what the exact syntax of the error was and I am having problems trying to recreate it)

**My troubleshooting**
- I tried rebooting both hosts.
- I tried `systemctl restart ipsec`
- I tried `ipsec auto --delete mytunnelroute` then `ipsec auto --add mytunnelroute`
- I made sure the two left (10.0.28.121) and right (10.0.28.122) ips were pingable between hosts.
- I tried turning on and off vti-route and vti-shared in a variety of combinations.
- Below you will notice that the vti01 interface is not built. I tried manually building it by running the commands in the updown script, same problems and errors from above. 
- re: the permissions issue, I made sure ipsec.service is running as root, and confirmed with `ps -aux | grep ipsec`. I made sure the "my_updown.sh" script was owned by root:root, and changed permissions to 777 for testing purposes. 
- **I removed the "mark" and "leftupdown" / "rightupdown" from my configuration, deleted the config, readded, and restarted ipsec, this brings up my interface without problems. The second I add my leftupdown or rightupdown script, nothing works.**

**My system setup**
- Both running rhel 8.4
- Both running kernel "4.18.0-305.3.1.el8_4.x86_64"
- Both running libreswan version "Linux Libreswan 4.3 (netkey) on 4.18.0-305.3.1.el8_4.x86_64"

**My network setup**
`ip -br addr show` output **left**:
```
[root@left /home/admin]# ips
lo               UNKNOWN        127.0.0.1/8
ens161           UP             10.0.28.121/24
ens192           UP             10.104.8.121/24
ens193           UP             10.0.27.121/24
ens224           UP             10.0.26.121/24
ens256           UP             10.0.21.121/24
virbr0           DOWN           192.168.122.1/24
virbr0-nic       DOWN
ip_vti0@NONE     DOWN
```

`ip -br addr show` output **right**:
```
[root@right/home/admin]# ips
lo               UNKNOWN        127.0.0.1/8
ens161           UP             10.0.29.122/24
ens192           UP             10.104.8.122/24
ens193           UP             10.0.27.122/24
ens224           UP             10.0.26.122/24
ens256           UP             10.0.21.122/24
virbr0           DOWN           192.168.122.1/24
virbr0-nic       DOWN
ip_vti0@NONE     DOWN

```

`netstat -rn` output **left**:
```
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
10.0.21.0       0.0.0.0         255.255.255.0   U         0 0          0 ens256
10.0.26.0       0.0.0.0         255.255.255.0   U         0 0          0 ens224
10.0.27.0       0.0.0.0         255.255.255.0   U         0 0          0 ens193
10.0.28.0       0.0.0.0         255.255.255.0   U         0 0          0 ens161
10.0.29.0       10.0.28.1       255.255.255.0   UG        0 0          0 ens161
10.104.8.0      0.0.0.0         255.255.255.0   U         0 0          0 ens192
10.212.134.0    10.104.8.1      255.255.255.0   UG        0 0          0 ens192
192.168.122.0   0.0.0.0         255.255.255.0   U         0 0          0 virbr0
```

`netstat -rn` output **right**:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
10.0.21.0       0.0.0.0         255.255.255.0   U         0 0          0 ens256
10.0.26.0       0.0.0.0         255.255.255.0   U         0 0          0 ens224
10.0.27.0       0.0.0.0         255.255.255.0   U         0 0          0 ens193
10.0.28.0       10.0.29.1       255.255.255.0   UG        0 0          0 ens161
10.0.29.0       0.0.0.0         255.255.255.0   U         0 0          0 ens161
10.104.8.0      0.0.0.0         255.255.255.0   U         0 0          0 ens192
10.212.134.0    10.104.8.1      255.255.255.0   UG        0 0          0 ens192
192.168.122.0   0.0.0.0         255.255.255.0   U         0 0          0 virbr0
```

**My configs**
`cat /etc/ipsec.conf` **same for both left and right**:
```
config setup
    logfile=/var/log/pluto.log    virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:25.0.0.0/8,%v4:100.64.0.0/10,%v6:fd00::/8,%v6:fe80::/10
include /etc/crypto-policies/back-ends/libreswan.config
include /etc/ipsec.d/*.conf
```
`cat /etc/ipsec.d/myipsec.conf` **left**:
```
conn mytunnel
    auto=start
    authby=rsasig
    leftid=@west121
    left=10.0.21.121
    leftrsasigkey=_<long key not including>_
    rightid=@east122
    right=10.0.21.122
    rightrsasigkey=_<long key not including>_

conn mytunnelroute
    auto=start
    authby=rsasig
    mark=5/0xffffffff
    vti-interface=vti01
    vti-routing=yes
    vti-shared=no
    leftupdown=/etc/my_updown.sh
    rightupdown=/etc/my_updown.sh
    leftid=@west121
    left=10.0.28.121
    leftsubnet=192.168.169.120/30
    # leftsubnet=0.0.0.0/0
    leftvti=192.168.169.121/32
    leftrsasigkey=_<long key not including>_
    rightid=@east122
    right=10.0.29.122
    rightsubnet=192.168.169.120/30
    # rightsubnet=0.0.0.0/0
    rightvti=192.168.169.122/32
    rightrsasigkey=_<long key not including>_
```

`cat /etc/ipsec.d/myipsec.conf` **right**:
```
conn mytunnel
    auto=start
    authby=rsasig
    leftid=@west121
    left=10.0.21.121
    leftrsasigkey=_<long key not including>_
    rightid=@east122
    right=10.0.21.122
    rightrsasigkey=_<long key not including>_

conn mytunnelroute
    auto=start
    authby=rsasig
    mark=5/0xffffffff
    vti-interface=vti01
    vti-routing=yes
    vti-shared=no
    leftupdown=/etc/my_updown.sh
    rightupdown=/etc/my_updown.sh
    leftid=@west121
    left=10.0.28.121
    leftsubnet=192.168.169.120/30
    # leftsubnet=0.0.0.0/0
    leftvti=192.168.169.121/32
    leftrsasigkey=_<long key not including>_
    rightid=@east122
    right=10.0.29.122
    rightsubnet=192.168.169.120/30
    # rightsubnet=0.0.0.0/0
    rightvti=192.168.169.122/32
    rightrsasigkey=_<long key not including>_
```

`cat /etc/my_updown.sh` **left**:
```
#!/bin/bash

set -o nounset
set -o errexit

VTI_IF="vti${PLUTO_UNIQUEID}"

case "${PLUTO_VERB}" in
    up-client)
        ip tunnel add vti01 local 192.168.169.121 remote 0.0.0.0 mode vti key "${PLUTO_MARK_OUT%%/*}"
        ip link set vti01 up
        ip addr add  192.168.169.121 dev vti01
        ip route add 192.168.169.120/30 dev vti01
        sysctl -w "net.ipv4.conf.vti01.disable_policy=1"
        ;;
    down-client)
        ip tunnel del vti01
        ;;
esac
```

`cat /etc/my_updown.sh` **right**:
```
#!/bin/bash

set -o nounset
set -o errexit

VTI_IF="vti${PLUTO_UNIQUEID}"

case "${PLUTO_VERB}" in
    up-client)
        ip tunnel add vti01 local 192.168.169.122 remote 0.0.0.0 mode vti key "${PLUTO_MARK_OUT%%/*}"
        ip link set vti01 up
        ip addr add  192.168.169.122 dev vti01
        ip route add 192.168.169.120/30 dev vti01
        sysctl -w "net.ipv4.conf.vti01.disable_policy=1"
        ;;
    down-client)
        ip tunnel del vti01
        ;;
esac
```

`cat /usr/lib/systemd/system/ipsec.service` **Same on left and right**:
```
[Unit]
Description=Internet Key Exchange (IKE) Protocol Daemon for IPsec
Wants=network-online.target
After=network-online.target
Documentation=man:ipsec(8) man:pluto(8) man:ipsec.conf(5)

[Service]
Type=notify
Restart=on-failure
# 12 is the shutdown while leaving kernel state. Restarting would still kill kernel state
RestartPreventExitStatus=12

#RestartPreventExitStatus=137 143 SIGTERM SIGKILL

# Set WatchdogSec to the amount of time (in seconds) that systemd will wait
# before restarting an unresponsive pluto.
# EVENT_SD_WATCHDOG updates the heartbeat every 15 seconds, recommended values
# are 60, 90, 120. WatchdogSec=0 disables the action
NotifyAccess=all
WatchdogSec=200

# Check configuration file
ExecStartPre=/usr/libexec/ipsec/addconn --config /etc/ipsec.conf --checkconfig
# Check for kernel modules
ExecStartPre=/usr/libexec/ipsec/_stackmanager start
# Check for nss database status and migration
ExecStartPre=/usr/sbin/ipsec --checknss
# Check for nflog setup
ExecStartPre=/usr/sbin/ipsec --checknflog
# Start the actual IKE daemon
ExecStart=/usr/libexec/ipsec/pluto --leak-detective --config /etc/ipsec.conf --nofork
# Enable for portexcludes support
# ExecStartPost=/usr/libexec/ipsec/portexcludes
ExecStop=/usr/libexec/ipsec/whack --shutdown
# 12 is the exit code of pluto for shutting down "leaving state"
ExecStopPost=/bin/bash -c 'if test "$EXIT_STATUS" != "12"; then /sbin/ip xfrm policy flush; /sbin/ip xfrm state flush; fi'
ExecStopPost=/usr/sbin/ipsec --stopnflog
ExecReload=/usr/libexec/ipsec/whack --listen

[Install]
WantedBy=multi-user.target
```

If it is not obvious, I am having trouble working with these configurations. I really dont understand what MARK is for. Yes I have read the documentation but its not clear to me. I also dont understand why my configs are getting rejected. 

What am I missing here?

**Comment by paulwouters** [comment]
The updown is not run because your tunnel is not coming up:

```
182 "mytunnelroute" #25: sent IKE_AUTH request {auth=IKEv2 cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_512 group=DH19}
010 "mytunnelroute" #26: STATE_PARENT_I2: retransmission; will wait 0.5 seconds for response
```

You need to fix the configuration so the remote peer responses to your authentication requests and when the tunnel establishes, the updown script will run

**Comment by davehouser1** [comment]
@paulwouters thanks for the reply.
So I manually ran the lines in my_updown.sh to create the tunnel, interfaces, and routes on each host. Then reloaded my scripts with no marks or updown script parameters. After bringing up my ipsec tunnels on each host after the change the interfaces come up and work. I then added `leftupdown=/etc/my_updown.sh` and `rightupdown=/etc/my_updown.sh` to both hosts /etc/ipsec.d/myipsec.conf files. When I tried to run it I get these errors:

```
002 "mytunnelroute" #93: up-client output: vti-interface option ignored because no mark was configured
002 "mytunnelroute" #93: up-client output: vti-interface option ignored because no mark was configured
```

At that point I configured `mark=5/0xffffffff` in both hosts /etc/ipsec.d/myipsec.conf files, deleted the config and re-added it. I tried running it again and now I see the following:

`ipsec auto --up mytunnelroute` **on right**
```
181 "mytunnelroute" #97: initiating IKEv2 connection
181 "mytunnelroute" #97: sent IKE_SA_INIT request
182 "mytunnelroute" #97: sent IKE_AUTH request {auth=IKEv2 cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_512 group=DH19}
002 "mytunnelroute" #97: IKEv2 mode peer ID is ID_FQDN: '@west121'
003 "mytunnelroute" #97: authenticated using RSA with SHA1
002 "mytunnelroute" #98: up-client output: vti interface "vti01" already exists with conflicting setting (perhaps need vti-sharing=yes ?
002 "mytunnelroute" #98: up-client output: Command line is not complete. Try option "help"
002 "mytunnelroute" #98: up-client output: done ip route
002 "mytunnelroute" #98: prepare-client output: vti interface "vti01" already exists with conflicting setting (perhaps need vti-sharing=yes ?
002 "mytunnelroute" #98: route-client output: Command line is not complete. Try option "help"
002 "mytunnelroute" #98: route-client output: done ip route
002 "mytunnelroute" #98: negotiated connection [192.168.169.120-192.168.169.123:0-65535 0] -> [192.168.169.120-192.168.169.123:0-65535 0]
004 "mytunnelroute" #98: IPsec SA established tunnel mode {ESP=>0xf5516966 <0x260d856b xfrm=AES_GCM_16_256-NONE NATOA=none NATD=none DPD=passive}
```

"up-client output: Command line is not complete. Try option "help"" Is interesting. It seems up-client is having trouble processing part of my_updown.sh script. Is there anyway to debug which part? Seems to be inbetween the interface build and the route add.

I have a strong suspicion that my use of "mark" is not correct, and maybe causing problems. 
I really don't understand what "mark", "mark-in", and "mark-out" is used for. After reading [this ](https://unix.stackexchange.com/questions/467076/how-set-mark-option-works-on-netfilter-iptables) and the [manual](https://libreswan.org/man/ipsec.conf.5.html).  MARK is based off CONNMARK, and I think its just used to identify my traffic internally on the host before sending via the tunnel. What I don't understand is:
 
1. The format, it seems to use MARK/MASK (based on documentation). But what is the MARK? is it just an integer to identify the traffic? What is the MASK value? What _should_ I make these? 
2. The mask value I chose was just from following an example I found online. Is this the correct value I should be using? Should (or could) the value be the same in both hosts config files?
3. I also noticed there is a "key" value in my_updown.sh script. The scripts format is based on an example I found online. I stripped out most of the pluto env values and manually put my own for troubleshooting purposes. If you look I did keep one env value for the "key" value  (Here is an example from the right side `ip tunnel add vti01 local 192.168.169.122 remote 0.0.0.0 mode vti key "${PLUTO_MARK_OUT%%/*}"` Is key related to mark? does this value need to be something specific to my config file or does the pluto env value take care of that?

Lastly, I wanted to make sure the errors were consistent after reboots. After a reboot, I try to bring up the tunnel with the changes I made above, and now I get these errors:

```
002 "mytunnelroute" #5: up-client output: /etc/cdap_updown.sh: line 8: PLUTO_UNIQUEID: unbound variable
003 "mytunnelroute" #5: up-client command exited with status 1
```

Then when I try to perform a --down --up again, I get the original problem of retransmission and never connecting. I think this is because the vti was deleted with the down-client, and never rebuilt, and since both sides cant retransmit the interface is never rebuilt. 

Not sure how to proceed from here. Would like to start with a better understanding of MARK parameter and why am I getting the up-client errors?

**Comment by letoams** [comment]
On Tue, 14 Sep 2021, davehouser1 wrote:

> Subject: Re: [libreswan/libreswan] libreswan refuses to use my updown script (#508)

> 002 "mytunnelroute" #93: up-client output: vti-interface option ignored because no mark was configured
> 002 "mytunnelroute" #93: up-client output: vti-interface option ignored because no mark was configured

Why are you trying to use the (obsolete) VTI and not the XFRMi based interface ?

> 181 "mytunnelroute" #97: initiating IKEv2 connection
> 181 "mytunnelroute" #97: sent IKE_SA_INIT request
> 182 "mytunnelroute" #97: sent IKE_AUTH request {auth=IKEv2 cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_512 group=DH19}
> 002 "mytunnelroute" #97: IKEv2 mode peer ID is ID_FQDN: ***@***.***'
> 003 "mytunnelroute" #97: authenticated using RSA with SHA1
> 002 "mytunnelroute" #98: up-client output: vti interface "vti01" already exists with conflicting setting (perhaps need vti-
> sharing=yes ?

It is seeing that you are multiple connections with different options
using the same VTI interface. You then need to enable vti-sharing=yes
but that has a number of limitations as well due to the kernel
implementation architecture. Like it cannot support multiple clients
on different remote IPs (eg two roadwarriors on dynamic IP)

> 002 "mytunnelroute" #5: up-client output: /etc/cdap_updown.sh: line 8: PLUTO_UNIQUEID: unbound variable

I do not see that variable in our source code? Is that something you
created custom?

> Then when I try to perform a --down --up again, I get the original problem of retransmission and never connecting. I think
> this is because the vti was deleted with the down-client, and never rebuilt, and since both sides cant retransmit the
> interface is never rebuilt.

That is very well possible.

**Comment by davehouser1** [comment]
**UPDATE:**

I was able to fix my issue and now my script runs when brining my ipsec interface up and down. 
Her is my script / location:

Location: /opt/_updown_vti01
```
#!/bin/bash

set -o nounset
set -o errexit

VTI_IF="vti01"

case "${PLUTO_VERB}" in
    up-client)
        # Build VTI interface. Note the "key" is important to mark your traffic
        ip tunnel add $VTI_IF local 2.2.0.2 remote 3.3.0.2 mode vti key 42
        # Bring up vti
        ip link set $VTI_IF up
        # Apply IP address to VTI
        ip addr add  172.21.0.2 dev $VTI_IF
        # Add routing
        ip route add 172.21.0.0/29 dev $VTI_IF
        ip route add 10.104.8.0/24 dev $VTI_IF
        sysctl -w "net.ipv4.conf.$VTI_IF.disable_policy=1"
        sysctl -w "net.ipv4.conf.$VTI_IF.rp_filter=0"
        sysctl -w "net.ipv4.conf.$VTI_IF.forwarding=1"
        ;;
    down-client)
        ip tunnel del $VTI_IF
        ;;
esac

```

Here is my configuration file in /etc/ipsec.d/myipsec.conf

```
conn to-vsrx-01
    auto=start
    keyexchange=ike
    authby=secret
    ike=aes256-sha2_256;dh20
    esp=aes256-sha2_256
    left=2.2.0.2
    leftid=2.2.0.2
    leftsubnet=0.0.0.0/0
    leftupdown=/opt/_updown_vti01
    right=3.3.0.2
    rightsubnet=10.10.10.0/24
    keyingtries=0
```

Couple of things I learned, however not sure the exact cause of the variety of problems I had. 

1. Dont try to put your script anywhere in /etc, I kept getting permission denied error for the up-client. Putting the script in /opt seemed to work. 
2. your script MUST have execution priv enabled, `chmod +x /opt/_updown_vti01`
3. It seems any settings you perform in your script's "up-client" section will conflict with some specific settings in your ipsec.conf file. Example, in my script the line `ip tunnel add $VTI_IF local 2.2.0.2 remote 3.3.0.2 mode vti key 42` would conflict with `mark=0x01000201` in your ipsec.conf. I had to remove mark and other vti settings to make sure they did not conflict. I assume there are other settings that could conflict, or specific settings that have priority but I am not clear on which ones they are. 
4. "rightsubnet" is extremely important. I found that even though I enabled routing in my updown script, no traffic will be sent unless your rightsubnet is set up to define subnets that can traverse the VPN. I needed "rightsubnet" in my ipsec config file, as well as include the routing in my updown script.
5. There does not appear to be such a thing as rightupdown, dont try to use it. 
6. Troubleshooting: After performing a `ipsec auto --up your-config-section`, and there was a failure in some way make sure to check the following:
    - Your far end SA, I am using a Juniper srx, I noticed after a failure of bringing up ipsec, there were multiple SAs created, make sure to turn down SA's and IKE on the far end before trying to attempt to rebuild the tunnel.
    - Your near end may have left over vti interface, and routes that were not removed. There is no way for the updown script to remove old vti / routes after a failure. check with `ip -br a` and `route -n`, and remove any leftover vti's and routes, then try to run your updown script again. The problem with these left over configurations is they will conflict with the updown script when it tries to run again. 

I am still having some routing issues, but those are un-related to this problem so I will close and open a new one on those issues. 

**Recommendation:**
- Would recommend adding some type of example for building this updown script, specifically on [this page](https://libreswan.org/wiki/Configuration_examples). I understand the updown script can be used to do anything via bash syntax, however I found it very difficult to find format examples in the libreswan documentation. Reading the man page for ipsec does not give much information either. 
- I also read online somewhere that there is a default _updown script somewhere on a ipsec deployments (Maybe it was for open/strong swan). I was unable to find anything for the libreswan deployment except `/usr/libexec/ipsec/_updown` but its fairly empty. Maybe include more examples in this _updown file besides just the PLUTO env vars?

**Comment by letoams** [comment]
On Tue, 28 Sep 2021, davehouser1 wrote:

> Subject: Re: [libreswan/libreswan] libreswan refuses to use my updown script
>     (#508)
>

> I was able to fix my issue and now my script runs when brining my ipsec interface up and down.
> Her is my script / location:

>  1. Dont try to put your script anywhere in /etc, I kept getting permission denied error for the up-client.
>     Putting the script in /opt seemed to work.

That might be selinux? I would recommend /usr/local/libexec/ipsec/

>  2. your script MUST have execution priv enabled, chmod +x /opt/_updown_vti01

that is generic unix :)

>  3. It seems any settings you perform in your script's "up-client" section will conflict with some specific
>     settings in your ipsec.conf file. Example, in my script the line ip tunnel add $VTI_IF local 2.2.0.2 remote
>     3.3.0.2 mode vti key 42 would conflict with mark=0x01000201 in your ipsec.conf. I had to remove mark and
>     other vti settings to make sure they did not conflict. I assume there are other settings that could
>     conflict, or specific settings that have priority but I am not clear on which ones they are.

The marking done in the conn section should give proper results for the
updown script. If you spot something where that conn part mismatches the
ENV variables passed to _updown, that would be a bug to fix.

but I'm not sure that applies here. Normally the vti options in the conn
do everything exept for 0.0.0.0/0 tunnels, route whatever you want into
it. eg vti-routing=yes.

>  4. "rightsubnet" is extremely important. I found that even though I enabled routing in my updown script, no
>     traffic will be sent unless your rightsubnet is set up to define subnets that can traverse the VPN. I
>     needed "rightsubnet" in my ipsec config file, as well as include the routing in my updown script.

Yes, this is all destination based routing, so you need a subnet. VTI
does not work for single hosts.

>  5. There does not appear to be such a thing as rightupdown, dont try to use it.

right :)

>  *  Would recommend adding some type of example for building this updown script, specifically on this page. I
>     understand the updown script can be used to do anything via bash syntax, however I found it very difficult
>     to find format examples in the libreswan documentation. Reading the man page for ipsec does not give much
>     information either.

Rememebr that you likely want to use our exitsing _updown and _add_ to
it, not fully replace it. You might be removing things we do in regular
updown that you need.

>  *  I also read online somewhere that there is a default _updown script somewhere on a ipsec deployments (Maybe
>     it was for open/strong swan). I was unable to find anything for the libreswan deployment except
>     /usr/libexec/ipsec/_updown but its fairly empty. Maybe include more examples in this _updown file besides
>     just the PLUTO env vars?

Yes, /usr/local/libexec/ipsec/_updown.xfrm (or _updown.netkey on older
ones). The _updown just redirects you to the _updown specific to the
IPsec stack used.

**Comment by davehouser1** [comment]
> Yes, /usr/local/libexec/ipsec/_updown.xfrm (or _updown.netkey on older
> ones). The _updown just redirects you to the _updown specific to the
> IPsec stack used.

Performing a `find / -name "_updown*" -type f 2>/dev/null` located the files in /usr/libexec/ipsec. 
I didn't know "_updown.xfrm" was the default script! Ok cool, thank you @paulwouters.
