### ISSUE TITLE
unable to compile 4.5 on centos8 - ldns-dns missing

### ISSUE THREAD

**Issue by davehouser1** [libreswan/libreswan#510]
When trying to compile 4.5 from source on centos8, I get this error

```
/opt/libreswan-4.5/programs/pluto/ikev2_ipseckey_dnsr.c:28:10: fatal error: ldns/ldns.h: No such file or directory
 #include <ldns/ldns.h> /* from ldns-devel */
          ^~~~~~~~~~~~~
compilation terminated.
```

The libreswan README.md has this section for dependencies to compile from source for centos8:

```
yum install audit-libs-devel bison curl-devel flex \
	gcc ldns-devel libcap-ng-devel libevent-devel \
	libseccomp-devel libselinux-devel make nspr-devel nss-devel \
	pam-devel pkgconfig systemd-devel unbound-devel xmlto
```

When doing a `yum install ldns-devel` I get this error 

```
No match for argument: ldns-devel
Error: Unable to find a match: ldns-devel
```

I also tried dnf install. which has similar results as yum install.
I also tried to install the rpm package from here (https://centos.pkgs.org/8/okey-x86_64/ldns-devel-1.7.0-20.el8.x86_64.rpm.html) 
But I get this error:

```
# yum install ldns-devel-1.7.0-20.el8.x86_64.rpm -y --nobest
Last metadata expiration check: 6:55:03 ago on Fri 24 Sep 2021 06:31:31 PM CEST.
Error:
 Problem: conflicting requests
  - nothing provides ldns(x86-64) = 1.7.0-20.el8 needed by ldns-devel-1.7.0-20.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

Are there any tips on how to get this package installed on centos8 so I can compile from source?
Really, I rather not compile form source, is there a simple way to install the 4.5 version without compiling from source? yum repos only have 4.3.

**Comment by letoams** [comment]
ldns should be in centos8 or epel8. Binaries  (repo) for centos8 can be found on download.libreswan.org/binaries/rhel/8

Sent using a virtual keyboard on a phone

**Comment by davehouser1** [comment]
@letoams thanks for the response. Are you referring to epel-release? I enabled with `yum install epel-release -y`, but that does not help. 
I checked https://download.libreswan.org/binaries/rhel/8/x86_64/ but I do not see any rpm's for ldns-devel. Is there anywhere else I can get this rpm? Maybe I am missing something on how to get ldns-devel installed, sorry for the confusion on my part.

**Comment by davehouser1** [comment]
@letoams, excellent, I just downloaded the libreswan-4.5-1.el8.x86_64.rpm and installed with yum with no problems! Thank you :D
