### ISSUE TITLE
PLUTO_PEER_CLIENT is used without netmask in _updown.xfrm

### ISSUE THREAD

**Issue by paulwouters** [libreswan/libreswan#525]
This can lead to errors, such as:

 pluto[3469]: "conn_XXX": unroute-client output: Error: inet prefix is expected rather than "2001:1024::1"

We need to verify the use of PLUTO_PEER_CLIENT in _updown.xfrm and see if we can add the netmask to this string

**Comment by bleve** [comment]
Nothing to fix in _updown. I checked, correct PLUTO_PEER_CLIENT variable is used and it's problem inside pluto if netmask is not in this variable. PLUTO_PEER_CLIENT_NET is without netmask version.
