### ISSUE TITLE
ikev2-mobike-03: EXPECTATION FAILED: sr->eroute_owner == 0 (delete_states_by_connection() +1456 programs/pluto/state.c)

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#527]
for this test:
- the pexpect() is for the template connection "road-eastnet" (it were deleting a connection instance then it wouldn't reach the pexpect())?
- so it either scribbled something on the template it shouldn't or the check is miss-placed?

```
 "road-eastnet"[1] 192.1.2.23: instantiated connection
 "road-eastnet"[1] 192.1.2.23 #1: initiating IKEv2 connection
 "road-eastnet"[1] 192.1.2.23 #1: sent IKE_SA_INIT request
 "road-eastnet"[1] 192.1.2.23 #1: sent IKE_AUTH request {cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_512 group=MODP2048}
 "road-eastnet"[1] 192.1.2.23 #1: established IKE SA; authenticated using authby=secret and peer ID_IPV4_ADDR '192.1.2.23'
 "road-eastnet"[1] 192.1.2.23 #2: received INTERNAL_IP4_ADDRESS 192.0.3.10
 "road-eastnet"[1] 192.1.2.23 #2: established Child SA using #1; IPsec tunnel [192.0.3.10-192.0.3.10:0-65535 0] -> [192.0.2.0-192.0.2.255:0-65535 0] {ESP/ESN=>0x05b85d92 <0x189f910d xfrm=AES_CBC_256-HMAC_SHA2_256_128 DPD=passive}
 "road-eastnet"[1] 192.1.2.23 #2: unroute-client output: RTNETLINK answers: Network is unreachable
 "road-eastnet"[1] 192.1.2.23 #1:  success MOBIKE update local address 192.1.3.209:500 -> 192.1.33.222:500
 "road-eastnet"[1] 192.1.2.23 #1: MOBIKE response: updating IPsec SA
 netlink_acquire got message with length 68 < 232 bytes; ignore message
 "road-eastnet"[1] 192.1.2.23 #2: unroute-client output: RTNETLINK answers: Network is unreachable
 "road-eastnet"[1] 192.1.2.23 #2: unroute-client output: RTNETLINK answers: Network is unreachable
 shutting down
 "road-eastnet"[1] 192.1.2.23: deleting connection instance with peer 192.1.2.23 {isakmp=#1/ipsec=#2}
| deleting all states for connection "road-eastnet"
 "road-eastnet"[1] 192.1.2.23 #1: deleting state (STATE_V2_ESTABLISHED_IKE_SA) aged 22.620483s and sending notification
 ERROR: "road-eastnet"[1] 192.1.2.23 #1: send on eth0 from 192.1.33.222:500 to 192.1.2.23:500 using UDP failed in delete notification: Network is unreachable (errno 101)
 "road-eastnet"[1] 192.1.2.23 #2: ESP traffic information: in=504B out=504B
 EXPECTATION FAILED: sr->eroute_owner == 0 (delete_states_by_connection() +1456 programs/pluto/state.c)
```
the code is:
```
void delete_states_by_connection(struct connection **cp)
{
[...] 
        case IKEv1: delete_v1_states_by_connection_bottom_up(cp, /*siblings*/false); break;
[...]
        if (c == NULL) {
                pexpect(ck == CK_INSTANCE);
                return;
[...]
        for (const struct spd_route *sr = &c->spd; sr != NULL; sr = sr->spd_next) {
                /*
                 * these passerts are not true currently due to mobike.
                 * Requires some re-implementation. Use pexpect for now.
                 */
                pexpect(sr->eroute_owner == SOS_NOBODY);
                pexpect(sr->routing != RT_ROUTED_TUNNEL);
        }
```

**Comment by letoams** [comment]
On Wed, 20 Oct 2021, cagney wrote:

> 
> for this test:
>
>  *  the pexpect() is for the template connection "road-eastnet" (it were deleting a connection instance then it wouldn't reach the
>     pexpect())?
>  *  so it either scribbled something on the template it shouldn't or the check is miss-placed?

In a way, the check is misplaced. It still assumes there is only one
eroute owner. In other words, two IPsec SA's cannot have the identical
traffic seletors. We know this is not true in all cases we want to
support (although prob should be true for the cases we do support?)

when we get back to the removal of POLICY_OVERLAPIP, we might also need
to think about deleting eroute_owner. At least for IKEv2. It might cause
issues with IKEv1 and transport mode with NAT (L2TP/IPsec) where we
really cannot have multiple clients all claiming the same (pre-NAT)
IP address, and we should throw an error there.


>  "road-eastnet"[1] 192.1.2.23 #1: MOBIKE response: updating IPsec SA netlink_acquire got message with length 68 < 232 bytes; ignore message

Could this be the cause here? Perhaps if we know it is all good MOBIKE,
we would not be deleting the connection, as we would be migrating it?
Perhaps we sort of migrated it already, triggering the pexpect?

>  "road-eastnet"[1] 192.1.2.23 #1: deleting state (STATE_V2_ESTABLISHED_IKE_SA) aged 22.620483s and sending notification
>  ERROR: "road-eastnet"[1] 192.1.2.23 #1: send on eth0 from 192.1.33.222:500 to 192.1.2.23:500 using UDP failed in delete notificatio
> n: Network is unreachable (errno 101)

And for MOBIKE causing a delete, I think there is no point sending a
notify, is there?

> the code is:
> 
> void delete_states_by_connection(struct connection **cp)
> {
> [...]
>         case IKEv1: delete_v1_states_by_connection_bottom_up(cp, /*siblings*/false); break;
> [...]
>         if (c == NULL) {
>                 pexpect(ck == CK_INSTANCE);
>                 return;
> [...]
>         for (const struct spd_route *sr = &c->spd; sr != NULL; sr = sr->spd_next) {
>                 /*
>                  * these passerts are not true currently due to mobike.
>                  * Requires some re-implementation. Use pexpect for now.
>                  */
>                 pexpect(sr->eroute_owner == SOS_NOBODY);
>                 pexpect(sr->routing != RT_ROUTED_TUNNEL);
>         }

Maybe just remove the pexpects? As they were really passerts that are no
longer true?

**Comment by cagney** [comment]
But why does the template even have an eroute_owner?
```
pexpect(sr->eroute_owner == SOS_NOBODY);
```

**Comment by cagney** [comment]
Things establish during IKE exchange:
```
Apr 13 14:49:40.214787: | kernel: spd routing: "road-eastnet"[1] 192.1.2.23 unrouted->erouted
Apr 13 14:49:40.214860: | kernel: spd owner: "road-eastnet"[1] 192.1.2.23 #0->#2
```
and even after some fun and games things are ok:
```
"road-eastnet"[1] 192.1.2.23 #1:  success MOBIKE update local address 192.1.3.209:500 -> 192.1.33.222:500
kernel: spd routing: "road-eastnet"[1] 192.1.2.23 unrouted->erouted
```
But then the ethernet cable is pulled and the connection is unrouted:
```
| XFRM RTM_DELADDR 192.1.33.222 IFA_LOCAL
| kernel: spd routing: "road-eastnet"[1] 192.1.2.23 erouted->unrouted
| kernel: running updown command "ipsec _updown" for verb down 
```
however, the kernel policy / spd owner are left in place.  Next:
```
"road-eastnet"[1] 192.1.2.23: deleting connection instance with peer 192.1.2.23 {isakmp=#1/ipsec=#2}
```
so now it is going to tear down the SA (delete kernel state / policy / zero owner), but because the connection was unrouted above, the policy part is skipped:
```
"road-eastnet"[1] 192.1.2.23 #2: ESP traffic information: in=504B out=504B
| kernel: teardown_ipsec_sa() skipping, routing unrouted isn't TUNNEL
```
leaving policy and owner wrong

Some thoughts:
- teardown will unroute the connection when needed
- both connection and spd are trying to track the latest Child state?

**Comment by cagney** [comment]
Here's more details from current logs:
- ipsec auto --up road-eastnet
```
May  5 12:47:22.997066: | kernel: spd routing: "road-eastnet"[1] 192.1.2.23 unrouted->erouted (route_and_eroute() +2820 programs/pluto/kernel.c)
May  5 12:47:22.997198: | kernel: spd owner: "road-eastnet"[1] 192.1.2.23 #0->#2 (route_and_eroute() +2821 programs/pluto/kernel.c)
May  5 12:47:22.998495: "road-eastnet"[1] 192.1.2.23 #2: initiator established Child SA using #1; IPsec tunnel [192.0.3.10-192.0.3.10:0-65535 0] -> [192.0.2.0-192.0.2.255:0-65535 0] {ESP/ESN=>0xc370d0a3 <0x6509f61c xfrm=AES_CBC_256-HMAC_SHA2_256_128 DPD=passive}
May  5 12:47:23.005104: netlink_expire got XFRM_MSG_EXPIRE message with length 60 < 232 bytes; ignore message
```
Wait 5 seconds and then delete interface which triggers a mobike update:
- ip addr del 192.1.3.209/24 dev eth0
```
May  5 12:47:29.571785: netlink_expire got XFRM_MSG_EXPIRE message with length 52 < 232 bytes; ignore message
May  5 12:47:29.627277: | XFRM RTM_DELADDR 192.1.3.209 IFA_LOCAL
May  5 12:47:29.627622: | kernel: spd routing: "road-eastnet"[1] 192.1.2.23 erouted->unrouted (migration_down() +1344 programs/pluto/kernel.c)
May  5 12:47:29.664684: "road-eastnet"[1] 192.1.2.23 #2: unroute-client output: RTNETLINK answers: Network is unreachable
May  5 12:47:29.670241: | kernel: spd routing: "road-eastnet"[1] 192.1.2.23 unrouted->unrouted (unroute_connection() +1386 programs/pluto/kernel.c)
May  5 12:47:29.708185: "road-eastnet"[1] 192.1.2.23 #1:  success MOBIKE update local address 192.1.3.209:500 -> 192.1.33.222:500
May  5 12:47:29.708966: | kernel: spd routing: "road-eastnet"[1] 192.1.2.23 unrouted->erouted (migration_up() +1327 programs/pluto/kernel.c)
May  5 12:47:29.738964: "road-eastnet"[1] 192.1.2.23 #1: MOBIKE response: updating IPsec SA
May  5 12:47:29.741157: netlink_expire got XFRM_MSG_EXPIRE message with length 68 < 232 bytes; ignore message
```
More sleeping (10s + 4s for pings).  For some reason .222 is deleted (how?):
```
May  5 12:47:44.661244: | XFRM RTM_DELADDR 192.1.33.222 IFA_LOCAL
May  5 12:47:44.661532: | kernel: spd routing: "road-eastnet"[1] 192.1.2.23 erouted->unrouted (migration_down() +1344 programs/pluto/kernel.c)
May  5 12:47:44.695934: "road-eastnet"[1] 192.1.2.23 #2: unroute-client output: RTNETLINK answers: Network is unreachable
May  5 12:47:44.698451: "road-eastnet"[1] 192.1.2.23 #2: unroute-client output: RTNETLINK answers: Network is unreachable
May  5 12:47:44.703111: | kernel: spd routing: "road-eastnet"[1] 192.1.2.23 unrouted->unrouted (unroute_connection() +1386 programs/pluto/kernel.c)
May  5 12:47:44.703229: | event_schedule_where: newref EVENT_v2_ADDR_CHANGE-pe@0x7f2f6775afb8 timeout in 0 seconds for #1
```
at this point "road-eastnet"[1] is in limbo.  Routing is down but kernel policy+state are still installed; and ADDR_CHANGE events keep trying to mobike.

Then pluto is shut down and the limbo connection triggers the pexpect().  Notably, because the connection is unrouted, deleting the kernel policy is skipped (fortunately it gets cleaned up some how).

```
May  5 12:47:45.276612: Pluto is shutting down
May  5 12:47:45.278947: "road-eastnet"[1] 192.1.2.23: deleting connection instance with peer 192.1.2.23 {isakmp=#1/ipsec=#2}
May  5 12:47:45.279454: "road-eastnet"[1] 192.1.2.23 #1: deleting state (STATE_V2_ESTABLISHED_IKE_SA) aged 22.599997s and sending notification
May  5 12:47:45.284622: ERROR: "road-eastnet"[1] 192.1.2.23 #1: send on eth0 from 192.1.33.222:500 to 192.1.2.23:500 using UDP failed in delete notification: Network is unreachable (errno 101)
May  5 12:47:45.292795: "road-eastnet"[1] 192.1.2.23 #2: ESP traffic information: in=504B out=504B
May  5 12:47:45.298746: EXPECTATION FAILED: "road-eastnet"[1] 192.1.2.23: eroute owner #2 should be 0
```

Ideas:
- when routing is deleted, change to RT_UNROUTED_HOLD?  Technically not correct as not a true hold and state is also installed.
- add a new routing value for unrouting+policy+state?
- track these using separate fields?

**Comment by letoams** [comment]
On Thu, 5 May 2022, cagney wrote:

> Ideas:
>
>  *  when routing is deleted, change to RT_UNROUTED_HOLD? Technically not correct as not a true hold and state is also installed.
>  *  add a new routing value for unrouting+policy+state?
>  *  track these using separate fields?

The real problem is that mobike could be bouncing a bit, eg like with
bad wifi. Ideally, we would switch the kernel to use the other IP but
maybe linger this "not working" policy for some time, like 30s? So if
it comes back in time we wouldn't have to re-install it into the kernel?

I think this issue is also why apple sort of gave up on mobike and just
brings up two tunnels, one for each interface.

to answer your question, RT_UNROUTED_HOLD would be false if we are up on
the new IP. Perhaps what we really need is two policies that each can be
up or hold? But that is quite some redesign work.

Perhaps our mechanisms should skip the mechanism of going from up to
hold if we are mobike enabled? After all we should only be updating the
policy with a new src gw ip?

Paul

**Comment by cagney** [comment]
the code is gone
