### ISSUE TITLE
ansible failure in ikev2-systemrole-04-mesh

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#534]
Seems the below ping isn't long enough:
```
--- MASTER/testing/pluto/ikev2-systemrole-04-mesh/nic.console.txt
+++ OUTPUT/testing/pluto/ikev2-systemrole-04-mesh/nic.console.txt
@@ -7,8 +7,10 @@
  ansible-playbook --skip-tags packages -i ansible-inventory.yml test-east-west.yml > OUTPUT/$(hostname).ansible.log 2>&1
 nic #
  sed -n -e '/PLAY RECAP/,$ p' -e '/^failed:/ p' OUTPUT/$(hostname).ansible.log
+failed: [west] (item=east) => {"ansible_loop_var": "item", "changed": true, "cmd": ["ping", "-c", "5", "east"], "delta": "0:00:14.096005", "end": "2021-10-24 01:42:18.063131", "item": "east", "msg": "non-zero return code", "rc": 1, "start": "2021-10-24 01:42:03.967126", "stderr": "", "stderr_lines": [], "stdout": "PING east (192.1.2.23) 56(84) bytes of data.\n\n--- east ping statistics ---\n5 packets transmitted, 0 received, 100% packet loss, time XXXX", "stdout_lines": ["PING east (192.1.2.23) 56(84) bytes of data.", "", "--- east ping statistics ---", "5 packets transmitted, 0 received, 100% packet loss, time 4086ms"]}
+failed: [east] (item=west) => {"ansible_loop_var": "item", "changed": true, "cmd": ["ping", "-c", "5", "west"], "delta": "0:00:14.138909", "end": "2021-10-24 01:42:17.762567", "item": "west", "msg": "non-zero return code", "rc": 1, "start": "2021-10-24 01:42:03.623658", "stderr": "", "stderr_lines": [], "stdout": "PING west (192.1.2.45) 56(84) bytes of data.\n\n--- west ping statistics ---\n5 packets transmitted, 0 received, 100% packet loss, time XXXX", "stdout_lines": ["PING west (192.1.2.45) 56(84) bytes of data.", "", "--- west ping statistics ---", "5 packets transmitted, 0 received, 100% packet loss, time 4121ms"]}
 PLAY RECAP *********************************************************************
-east                       : ok=15   changed=4    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0   
-west                       : ok=18   changed=4    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0   
+east                       : ok=14   changed=3    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0   
+west                       : ok=17   changed=3    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0  
```

**Comment by letoams** [comment]
On Sun, 24 Oct 2021, cagney wrote:

> Seems the below ping isn't long enough:
> 
> --- MASTER/testing/pluto/ikev2-systemrole-04-mesh/nic.console.txt
> +++ OUTPUT/testing/pluto/ikev2-systemrole-04-mesh/nic.console.txt
> @@ -7,8 +7,10 @@
>   ansible-playbook --skip-tags packages -i ansible-inventory.yml test-east-west.yml > OUTPUT/$(hostname).ansible.log 2>&1
>  nic #
>   sed -n -e '/PLAY RECAP/,$ p' -e '/^failed:/ p' OUTPUT/$(hostname).ansible.log
> +failed: [west] (item=east) => {"ansible_loop_var": "item", "changed": true, "cmd": ["ping", "-c", "5", "east"], "delta": "0:00:14.0
> 96005", "end": "2021-10-24 01:42:18.063131", "item": "east", "msg": "non-zero return code", "rc": 1, "start": "2021-10-24 01:42:03.9
> 67126", "stderr": "", "stderr_lines": [], "stdout": "PING east (192.1.2.23) 56(84) bytes of data.\n\n--- east ping statistics ---\n5
>  packets transmitted, 0 received, 100% packet loss, time XXXX", "stdout_lines": ["PING east (192.1.2.23) 56(84) bytes of data.", "",
>  "--- east ping statistics ---", "5 packets transmitted, 0 received, 100% packet loss, time 4086ms"]}
> +failed: [east] (item=west) => {"ansible_loop_var": "item", "changed": true, "cmd": ["ping", "-c", "5", "west"], "delta": "0:00:14.1
> 38909", "end": "2021-10-24 01:42:17.762567", "item": "west", "msg": "non-zero return code", "rc": 1, "start": "2021-10-24 01:42:03.6
> 23658", "stderr": "", "stderr_lines": [], "stdout": "PING west (192.1.2.45) 56(84) bytes of data.\n\n--- west ping statistics ---\n5
>  packets transmitted, 0 received, 100% packet loss, time XXXX", "stdout_lines": ["PING west (192.1.2.45) 56(84) bytes of data.", "",
>  "--- west ping statistics ---", "5 packets transmitted, 0 received, 100% packet loss, time 4121ms"]}

Looks like these just need sanitizing of "delta" and "start" and "time" ?

>  PLAY RECAP *********************************************************************
> -east                       : ok=15   changed=4    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0 
> -west                       : ok=18   changed=4    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0 
> +east                       : ok=14   changed=3    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0 
> +west                       : ok=17   changed=3    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0

These come from updates to the ansible playbook. I asked upstream about
this before, but they requested the ansible log which we didn't have
yet. I think we do now, so I should follow up with them.

**Comment by cagney** [comment]
> Looks like these just need sanitizing of "delta" and "start" and "time" ?

No.  Those failing pings are the reason the test barfed.  This is a full [log](https://testing.libreswan.org/v4.5-392-gaae5939350-main/ikev2-systemrole-04-mesh/OUTPUT/nic.ansible.log.gz) of the ansible fail.

Question is, what are the pings trying to do?  Presumably they are waiting for something?

**Comment by The-Mule** [comment]
Is this a recent failure? We are running this test on RHEL via NS-testsuite and it works fine there. AFAIK pings are there to make sure that nic (ansible controller) configured west/east (controlled nodes) correctly. I am not aware of any relevant recent change in VPN system role (but I guess on F32 libreswan testing role is used).

**Comment by cagney** [comment]
The failure is intermittent, I believe the issue's always been there (the only recent changes was to tweak the test so we can start to see what is going on).  The machine running the tests is also loaded, which tends to expose more problems.

For reference here's a passing [passing log](https://testing.libreswan.org/v4.5-405-g4aadfc961c-main/ikev2-systemrole-04-mesh/OUTPUT/nic.ansible.log.gz) (it unfortunately doesn't tell us the nr of pings that worked).

Looking at the test, it is(?):
1. pushing out config changes
2. running: ssh $HOST ipsec restart
3. running: "ping", "-c", "5", "east"
I've also tried ping -c 15, which failed.
