### ISSUE TITLE
use something simpler than SSH as a TCP endpoint

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#538]
Many tests use `sshd` on east as a TCP endpoint, presumably because it is convenient.

This works fine until you start playing games with packages.  For instance:
1. force the build / install of rawhide NSS
2. but rawhide NSS requires the latest crypto-policies (else crypto breaks in really weird ways), so force that
3. but that conflicts with `sshd` which expects the installed crypto-policies, so remove that (which breaks tests)
Hmm.

What alternatives are there?
- `nc`; once nice feature of `sshd` is the text announcing its presence, can `nc` mimic this (one not-so-nice feature of `sshd` is that the text keeps changing)
- one of the original protocols such as `telnet`, `rsh`, ...
- ...

**Comment by letoams** [comment]
But we need sshd anyway, it is essential for easy logging into guests for debugging 

Sent using a virtual keyboard on a phone

**Comment by cagney** [comment]
> But we need sshd anyway, it is essential for easy logging into guests for debugging
I'm not suggesting `sshd` be disabled on KVMs (namespaces don't run sshd, and `./kvm sh east` works).

A good reason for using sshd in a test is because we need ssh's functionality.  For instance, the ikev2-systemrole-* tests use ssh to push out updates.  If ssh is broken due to NSS hackery then those tests won't work.

However,  for many other tests that isn't true.  For instance, a test needing TCP traffic works just as well, if not better, using netcat:
- the data transfer size and output are more predictable
- both kvm and namespaces are closer
- it works with hacked versions of NSS

**Comment by letoams** [comment]
On Mon, 1 Nov 2021, cagney wrote:

> A good reason for using sshd in a test is because we need ssh's functionality. For instance, the ikev2-systemrole-* tests use ssh to
> push out updates. If ssh is broken due to NSS hackery then those tests won't work.

My point was if ssh is broken, it means I cannot work with _any_ tests
because I completely rely on ssh to get into my KVM nodes.

> However, for many other tests that isn't true. For instance, a test needing TCP traffic works just as well, if not better, using
> netcat:
>
>  *  the data transfer size and output are more predictable
>  *  both kvm and namespaces are closer
>  *  it works with hacked versions of NSS

I agree and have no issues with replacing the tests with socat or
netcat. It would be more stable I am sure. In the past we used sshd
mostly because then we didnt have to start a new daemon, and forking
a daemon in the background was tricky due to [1] output like things
we have since found an answer for.

Paul

**Comment by cagney** [comment]
Per 5ceb03e1e642f05ff780e8e933eb6ce6eb6764be and https://github.com/nmap/nmap/issues/962 we should probably switch any code using ncat to socat as a server (this explains a few mysteries I've encountered when testing TCP).
