### ISSUE TITLE
resolve_defaultroute_one fails when a conn uses %defaultroute and a named peer

### ISSUE THREAD

**Issue by doctaweeks** [libreswan/libreswan#54]
When resolve_defaultroute_one is called for a connection that has left=%defaultroute and right=<dns name>, it determines that it does not have an IP for the peer, source, or gateway. However, under this set of condition it can not populate any of these field and fails to bring up the resulting connection ("We cannot identify ourselves [...]"). If either left or right is replaced with an appropriate IP address the connection will succeed.

**Comment by doctaweeks** [comment]
I believe I have a fix for this I can submit a PR for after some testing.

**Comment by letoams** [comment]
But this issue is rather fundamental. if you have:

conn foo
   left=%defaultroute
   right=%any
   [options that ensure left is a server and right are the clients]

How does this configuration know whether it is supposed to be the client, or the server?

**Comment by doctaweeks** [comment]
This is a case where:
left=%defaultroute
right=vpn.domain.tld

addconn only looks to see if the peer has an IP - it doesn't handle a name lookup.  If at least one side doesn't have an IP in the config it can't proceed successfully.

**Comment by doctaweeks** [comment]
This appears to be fixed for IPv4 connections. However, there is still an issue with IPv6 connections in the same setup.

**Comment by letoams** [comment]
this has been fixed now with merging pull request #58
