### ISSUE TITLE
f35: type=AVC msg=audit(1638227662.185:108): avc:  denied  { watch } 

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#560]
As in:
```
+:
+: checking selinux audit records
+:
+type=AVC msg=audit(1638227662.185:108): avc:  denied  { watch } for  pid=293 comm="systemd-network" path="/run/dbus" dev="tmpfs" ino=980 scontext=system_u:system_r:systemd_networkd_t:s0 tcontext=system_u:object_r:system_dbusd_var_run_t:s0 tclass=dir permissive=1^]
+type=SYSCALL msg=audit(1638227662.185:108): arch=c000003e syscall=254 success=yes exit=3 a0=e a1=5559f4507130 a2=2000d84 a3=5559f4504bc0 items=1 ppid=1 pid=293 auid=4294967295 uid=192 gid=192 euid=192 suid=192 fsuid=192 egid=192 sgid=192 fsgid=192 tty=(none) ses=4294967295 comm="systemd-network" exe="PATH/lib/systemd/systemd-networkd" subj=system_u:system_r:systemd_networkd_t:s0 key=(null)^]ARCH=x86_64 SYSCALL=inotify_add_watch AUID="unset" UID="systemd-network" GID="systemd-network" EUID="systemd-network" SUID="systemd-network" FSUID="systemd-network" EGID="systemd-network" SGID="systemd-network" FSGID="systemd-network"
+type=CWD msg=audit(1638227662.185:108): cwd="/"^]
+type=PATH msg=audit(1638227662.185:108): item=0 name="/run/dbus" inode=980 dev=00:19 mode=040755 ouid=0 ogid=0 rdev=00:00 obj=system_u:object_r:system_dbusd_var_run_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0^]OUID="root" OGID="root"
+type=PROCTITLE msg=audit(1638227662.185:108): proctitle="PATH/lib/systemd/systemd-networkd"^]
```
"wonderful"

**Comment by bleve** [comment]
17:01 < bleve> grift: any idea what causes this on f35 ? 
               https://github.com/libreswan/libreswan/issues/560
17:02 < grift> yes there are i think 3 daemons that are started so early that 
               they want to know exactly when dbus becomes available
17:02 < grift> they do that by watch / /run /run/dbus /run/dbus.socket
17:03 < bleve> so likely this is quite harmless.
17:03 < grift> systemd-networkd, systemd-timesync and systemd-resolved probably
17:03 < grift> yes

**Comment by doverride** [comment]
Basically theyre using inotify to get notified when the /run/dbus/system_bus_socket. Because these daemons do not strictly rely on dbus (but they provide extra functionality if dbus is available) and they're often started very early (potentially before dbus is started and thus before /run/dbus/system_bus_socket exists)

So theyre actually watching not just /run/dbus but also /, /run and /run/dbus/system_bus_socket

**Comment by cagney** [comment]
we'll ignore it

**Comment by cagney** [comment]
it's being ignored
