### ISSUE TITLE
f35: missing /usr/sbin/service

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#563]
Or more specifically the RPM initscripts-service.  Adding the rpm, but I'm pretty sure the tests need an update.

**Comment by cagney** [comment]
For instance:
```
testing/pluto/seccomp-01-enabled/westinit.sh:service auditd stop
```
the test:
```
 testing/pluto/basic-pluto-16-services
```
seems to just test the "services" command so can be deleted?

**Comment by letoams** [comment]
On Tue, 30 Nov 2021, cagney wrote:

> For instance:
> 
> testing/pluto/seccomp-01-enabled/westinit.sh:service auditd stop

Not sure why it needs to stop the audit daemon. But it could do
so with the kill command instead?

> the test:
>
>  testing/pluto/basic-pluto-16-services
> 
> seems to just test the "services" command so can be deleted?

That command is still in rhel/centos 6, and it was added from downstream
redhat to upstream. I guess since those distributions are really EOL,
or on some extended support for security fixes only, we can delete
the test.

**Comment by cagney** [comment]
in seccomp-01-enabled it seems to be scrubbing the log file; presumably the correct way to do that is to force a log rotate

**Comment by cagney** [comment]
Unfortunately 77fd537289cd88e211c99c691bb15e0ac232336c causes this:
```
--- MASTER/testing/pluto/seccomp-01-enabled/west.console.txt
+++ OUTPUT/testing/pluto/seccomp-01-enabled/west.console.txt
@@ -55,10 +55,47 @@
  # one entry of SECCOMP activating should show up in the log
 west #
  grep SECCOMP /var/log/audit/audit.log | sed "s/ip=.*/ip=XXX/"
-type=SECCOMP msg=audit(XXX): auid=AUID uid=0 gid=0 ses=SES subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=PID comm="pluto" exe="PATH/libexec/ipsec/pluto" sig=31 arch=c000003e syscall=124 compat=0 ip=XXX
+grep: /var/log/audit/audit.log: No such file or directory
 west #
  # don't leave post-mortem.sh thinking pluto is running
 west #
  rm /run/pluto/pluto.ctl
 west #
```
(I tried it also)

**Comment by bleve** [comment]
auditd.service has: RefuseManualStop=yes - so it can't be stopped or started manually. There is work-around, that is to create /etc/systemd/auditd.service.d/override.conf with contents:

[Unit]
RefuseManualStop=no

auditd.service also has check for audit=0 in kernel command line - if that exist it won't start. Similar work-round can be done with override.conf

**Comment by cagney** [comment]
That would explain this weird message being hidden by the smoke and mirrors:
```
- systemctl stop auditd > /dev/null 2> /dev/null
-west #
- rm -f /var/log/audit/audit.log
-west #
- systemctl start auditd
+ systemctl stop auditd
+Failed to stop auditd.service: Operation refused, unit auditd.service may be requested by dependency only (it is configured to refuse manual start/stop).
+See system logs and 'systemctl status auditd.service' for details.
```
labeled ipsec and post-mortem.sh have the same problem, tweaking gives:
```
# ausearch -r -ts boot -m seccomp
type=SECCOMP msg=audit(1641566872.719:191): auid=0 uid=0 gid=0 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=513 comm="pluto" exe="/usr/local/libexec/ipsec/pluto" sig=31 arch=c000003e syscall=124 compat=0 ip=0x7f7571d6d7ab code=0x0AUID="root" UID="root" GID="root" ARCH=x86_64 SYSCALL=getsid
```
