### ISSUE TITLE
digsig: print the algorithm name (when known) not just it's number

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#605]
For instance in:
```
negotiate_hash_algo_from_notification()
```
it logs
```
log_state(RC_LOG, &ike->sa, "received and ignored unknown hash algorithm %d", h_value);
```
when it could be looking up the hash algorithm and then logging its name

**Comment by letoams** [comment]
On Jan 7, 2022, at 18:00, cagney ***@***.***> wrote:
> 
> ﻿
> For instance in:
> 
> negotiate_hash_algo_from_notification()
> it logs
> 
> log_state(RC_LOG, &ike->sa, "received and ignored unknown hash algorithm %d", h_value);
> when it could be looking up the hash algorithm and then logging its name
> 

Well, if we knew the name, it wouldn’t be an unknown hash algorithm and a switch case elsewhere would catch it or say FOO is it supported if it’s a real value but we don’t implement it 😜

**Comment by cagney** [comment]
> Well, if we knew the name, it wouldn’t be an unknown hash algorithm and a switch case elsewhere would catch it or say FOO is it supported if it’s a real value but we don’t implement it

I wish.

The function negotiate_hash_algo_from_notification() pulls 16-bit ntohs() values directly from the PBS and then feeds it into a hardwired switch of known algorithms.  default is to log unknown hash algorithm %d.
Minimally it should lookup the hash_desc to see if if it is known and has a blob defined; and when it doesn't try the enum-names for something to print.

**Comment by cagney** [comment]
0ce9a1e9322b9aea5b4555711214ad4bf33016b9 for instance, now prints IDENTITY instead of 5
