### ISSUE TITLE
logging in plutomain happens before log system initialized

### ISSUE THREAD

**Issue by paulwouters** [libreswan/libreswan#607]
It looks like some logging change caused a lot of logging via llog() to be done before logging is initialized with  pluto_init_log()

This means a lot of startup errors are no longer being logged :/

Example call that fails:  llog(RC_LOG_SERIOUS, logger, "ignoring ikev1-policy=......

**Comment by cagney** [comment]
This isn't a new problem.

Logging is enabled after the config file is loaded.  If the config file contains errors then get lost (they do get sent to stderr).

**Comment by letoams** [comment]
On Sat, 8 Jan 2022, cagney wrote:

> Logging is enabled after the config file is loaded. If the config file contains errors then get lost (they do get sent
> to stderr).

I did not see them appear in stderr

**Comment by cagney** [comment]
For instance:
```
# ipsec start
Redirecting to: /usr/local/etc/rc.d/pluto onestart
Starting pluto.
/usr/local/libexec/ipsec/pluto: option --config "/usr/local/etc/ipsec.conf" invalid: /usr/local/etc/ipsec.conf:23: syntax error [ikev1]
```
of course, with systemd, the only way to see this stuff is by invoking pluto directly.

This is how it works:

- parse config file and options; discovering how logging should be configured
- acquire lock and, possibly fork
- enable the real logger

the only recent change was to point the logger at stderr until the real logger was enabled so that code could call llog() instead of fprintf().

**Comment by paulwouters** [comment]
It seems I got bit but /etc/ipsec.conf not being used per default:

[root@thinkpad paul.wouters]# grep dumpdir /etc/ipsec.conf
	dumpdir=/nono/no
[root@thinkpad paul.wouters]# ipsec pluto --stderrlog --nofork --config /etc/ipsec.conf 2>&1  |grep dump
/usr/local/libexec/ipsec/pluto: pluto: warning: chdir("/nono/no") to dumpdir failed (2: No such file or directory)
Jan  9 15:52:13.031749: core dump dir: /nono/no

^C
[root@thinkpad paul.wouters]# ipsec pluto --stderrlog --nofork  2>&1  |grep dump
Jan  9 15:52:27.647970: core dump dir: /run/pluto
