### ISSUE TITLE
IKEv2_AUTH_NONE is not of enum ikev2_auth_method, but defined for enum ikev2_trans_type_integ

### ISSUE THREAD

**Issue by paulwouters** [libreswan/libreswan#610]
while the compiler warns against accidentally using IKEv2_AUTH_NONE as an ike auth method, this is really a bad name. Suggest IKEv2_AUTH_INTEG_NONE ?

**Comment by cagney** [comment]
I see in https://www.iana.org/assignments/ikev2-parameters/ikev2-parameters.xhtml#ikev2-parameters-7 it's called "NONE" where as the others are called "AUTH_...".  Why IETF didn't abandon the IKEv1 names and use INTEG, I don't know.
