### ISSUE TITLE
IKEv1 labeled ipsec broken since 4.5

### ISSUE THREAD

**Issue by The-Mule** [libreswan/libreswan#621]
First of all, labeled ipsec probably never worked correctly for IKEv1. But since 4.5 it is no longer possible to even establish IKE SA when policy label is used. For instance, with the following simple connection `ipsec auto --up test` fails:

```
conn test
	left=<client>
	right=<server>
	authby=secret
	ikev2=no
	policy-label=system_u:object_r:ipsec_spd_t:s0
```

Server side contains the following error in the pluto log:

```
"test" #47: selinux polmatch within_range: sl (system_u:object_r:ipsec_spd_t:s0) - range (system_u:object_r:ipsec_spd_t:s0): Permission denied (errno 13)
Jan 22 14:17:32.408318: | security label 'system_u:object_r:ipsec_spd_t:s0\0' is not within range 'system_u:object_r:ipsec_spd_t:s0\0'
Jan 22 14:17:32.408328: "test" #47: received IPsec Security Label 'system_u:object_r:ipsec_spd_t:s0' not within range of our configured security label 'system_u:object_r:ipsec_spd_t:s0'
Jan 22 14:17:32.408331: | complete v1 state transition with BAD_PROPOSAL_SYNTAX
```

With 4.4 it worked fine (despite the fact that labeled ipsec did not worked correctly). 

I suppose there is not really a valid reason to spent time on fixing IKEv1 issues anymore but maybe it can be "fixed" at least from the documentation perspective, ie. documenting that policy-label is now IKEv2 only? Or perhaps fail to load IKEv1 connection using policy-label option?

**Comment by cagney** [comment]
Are you sure you've set up your test correctly?  The ikev1 wip tests in mainline show a connection loading fine.

**Comment by cagney** [comment]
as part of 5.x should this be officially dropped

**Comment by letoams** [comment]
On Sun, 12 Mar 2023, cagney wrote:

> as part of 5.x should this be officially dropped

That would make migration harder? Ideally we would fix it.
