### ISSUE TITLE
Libreswan tunnel up but not forwarding traffic

### ISSUE THREAD

**Issue by olivernaaris** [libreswan/libreswan#625]
Hi

We are using Libreswan version 3.29-2build1 on Ubuntu 20.04.2 LTS.
We have a problem where the Libreswan process is up and running and the tunnel is reported to be working by `ipsec status` command and we can see no errors in the logs, however, after a while, it's not possible to route traffic through the tunnel anymore. After we restart the Libreswan process, it starts working again.

I've added the output of the `ipsec status` command and logs of before and after restart of the Libreswan process.
[ipsec_log_after_restart.txt](https://github.com/libreswan/libreswan/files/7951511/ipsec_log_after_restart.txt)
[ipsec_log_before_restart.txt](https://github.com/libreswan/libreswan/files/7951512/ipsec_log_before_restart.txt)
[ipsec_status_after_restart.txt](https://github.com/libreswan/libreswan/files/7951513/ipsec_status_after_restart.txt)
[ipsec_status_before_restart.txt](https://github.com/libreswan/libreswan/files/7951514/ipsec_status_before_restart.txt)

I also added the current config that we use (removed the real IP-s).
[ipsec_tunnel_conf.txt](https://github.com/libreswan/libreswan/files/7951539/ipsec_tunnel_conf.txt)

Any feedback or help would be appreciated.

**Comment by paulwouters** [comment]
This could be related to subnets= (plural) keyword. That instantiates the conn and might cause issues. If you only have one rightsubnet, use the singular option. If you really do have multiple ones, you can try and splitting the conns manually if you don't have too many.

Another issue is:

Jan 17 09:57:00 tigo-tzn-vpn-instance pluto[33602]: "tigo-tzn-vpn-tunnel/0x1" #60471: received Delete SA payload: replace IPsec State #60605 now
Jan 17 09:57:00 tigo-tzn-vpn-instance pluto[33602]: "tigo-tzn-vpn-tunnel/0x3" #60611: initiating Quick Mode PSK+ENCRYPT+TUNNEL+UP+IKEV1_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO to replace #60605 {using isakmp#60471 msgid:f11e3bab >
Jan 17 09:57:00 tigo-tzn-vpn-instance pluto[33602]: "tigo-tzn-vpn-tunnel/0x3" #60605: deleting state (STATE_QUICK_I2) aged 1829.958s and sending notification

This looks like a fixed bug where we received a delete, realized the connection must remain up, triggered a new quickmode, but then somehow ended up deleting that request as a part of deleting the old one.

If you could upgrade to a 4.x version that would likely help. You should be able to grab libreswan 4.6 as tar ball and run "make deb" to crate packages for your system for testing.

**Comment by olivernaaris** [comment]
Thank you for the quick and detailed response. I'll try the 4.x version of Libreswan and let you know if it helped.
Thanks again.

**Comment by olivernaaris** [comment]
Hi again! Seems that the upgrade to version 4.6 resolved the issue. Thanks again!
