### ISSUE TITLE
'protoport' narrowing not working as expected (was bugzilla 297)

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#631]
https://bugs.libreswan.org/show_bug.cgi?id=297

Doing some experiments with 'narrowing=yes' (possibly related: [bug 296](https://bugs.libreswan.org/show_bug.cgi?id=296)) and testing with 'protoport' lead to some surprises..

Assume the configuration:
```
    on node A:
	leftprotoport=17/1701
	rightprotoport=17/%any
	narrowing=yes

    on node B:
	leftprotoport=17/5555
	rightprotoport=17/1701
	narrowing=yes
```

What I would expect in this case is for the SA to be established and to allow traffic between 17/1701 <=> 17/5555.
What happens instead is that SA is not established (node A rejects the proposal).
(If config is updated the IKEv1 the SA is established)

A possible use case for the above configuration could be something similar to L2TP: for L2TP (and IKEv1) the server needs to have rightprotoport=17/%any because there are clients that use a fix port (1701) but also clients that use a random UDP port..
I'm not sure if this is a valid use case for IKEv2 and/or if a similar use case exists for IKEv2.

Full configuration:
    node A:
```
	# PSK from_144 
	conn psk_from_144
		authby=secret
		auto=add
		ike=3des-md5;modp1024
		ikelifetime=60m
		ikev2=insist
		keyingtries=1
		keylife=480m
		left=192.168.173.129
		leftid=192.168.173.129
		leftnexthop=192.168.173.2
		leftprotoport=17/1701
		leftsubnet=192.168.250.0/24
		pfs=yes
		phase2=esp
		phase2alg=3des-md5;modp1024
		right=%any
		rightid=%any
		rightprotoport=17/%any
		rightsubnet=172.16.1.0/24
		narrowing=yes
```

    node B:
```
	# PSK to_129 
	conn psk_to_129
		authby=secret
		auto=start
		ike=3des-md5;modp1024
		ikelifetime=60m
		ikev2=insist
		keylife=480m
		left=192.168.173.144
		leftid=192.168.173.144
		leftnexthop=192.168.173.2
		leftprotoport=17/5555
		leftsubnet=172.16.1.0/24
		pfs=yes
		phase2=esp
		phase2alg=3des-md5;modp1024
		right=192.168.173.129
		rightid=192.168.173.129
		rightprotoport=17/1701
		rightsubnet=192.168.250.0/24
		narrowing=yes
```
Initiating tunnel on node B:
```
	$ ipsec auto --up psk_to_129
	002 "psk_to_129"[1] 192.168.173.129 #10: initiating v2 parent SA
	133 "psk_to_129"[1] 192.168.173.129 #10: STATE_PARENT_I1: initiate
	002 "psk_to_129"[1] 192.168.173.129 #10: psk_to_129 IKE proposals for initial initiator (selecting KE): 1:IKE:ENCR=3DES;PRF=HMAC_MD5;INTEG=HMAC_MD5_96;DH=MODP1024
	133 "psk_to_129"[1] 192.168.173.129 #10: STATE_PARENT_I1: sent v2I1, expected v2R1
	010 "psk_to_129"[1] 192.168.173.129 #10: STATE_PARENT_I1: retransmission; will wait 500ms for response
	002 "psk_to_129"[1] 192.168.173.129 #10: psk_to_129 ESP/AH proposals for initiator: 1:ESP:ENCR=3DES;INTEG=HMAC_MD5_96;ESN=DISABLED
	134 "psk_to_129"[1] 192.168.173.129 #11: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=3des_cbc_192 integ=md5_96 prf=md5 group=MODP1024}
	010 "psk_to_129"[1] 192.168.173.129 #11: STATE_PARENT_I2: retransmission; will wait 500ms for response
	010 "psk_to_129"[1] 192.168.173.129 #11: STATE_PARENT_I2: retransmission; will wait 1000ms for response
	010 "psk_to_129"[1] 192.168.173.129 #11: STATE_PARENT_I2: retransmission; will wait 2000ms for response
```
Logging:
    node A:
```
	packet from 192.168.173.144:500: psk_from_144 IKE proposals for initial responder: 1:IKE:ENCR=3DES;PRF=HMAC_MD5;INTEG=HMAC_MD5_96;DH=MODP1024
	packet from 192.168.173.144:500: proposal 1:IKE:ENCR=3DES;PRF=HMAC_MD5;INTEG=HMAC_MD5_96;DH=MODP1024 chosen from: 1:IKE:ENCR=3DES;PRF=HMAC_MD5;INTEG=HMAC_MD5_96;DH=MODP1024[first-match]
	"psk_from_144"[1] 192.168.173.144 #1: STATE_PARENT_R1: received v2I1, sent v2R1 {auth=IKEv2 cipher=3des_cbc_192 integ=md5_96 prf=md5 group=MODP1024}
	"psk_from_144"[1] 192.168.173.144 #1: IKEv2 mode peer ID is ID_IPV4_ADDR: '192.168.173.144'
	| ikev2_parent_inI2outR2_tail returned STF_FAIL with v2N_NO_PROPOSAL_CHOSEN
	"psk_from_144"[1] 192.168.173.144 #1: sending unencrypted notification v2N_NO_PROPOSAL_CHOSEN to 192.168.173.144:500
	packet from 192.168.173.144:500: sending unencrypted notification v2N_INVALID_IKE_SPI to 192.168.173.144:500
```
    node B:
```
	"psk_to_129"[1] 192.168.173.129 #16: initiating v2 parent SA
	"psk_to_129"[1] 192.168.173.129 #16: psk_to_129 IKE proposals for initial initiator (selecting KE): 1:IKE:ENCR=3DES;PRF=HMAC_MD5;INTEG=HMAC_MD5_96;DH=MODP1024
	"psk_to_129"[1] 192.168.173.129 #16: STATE_PARENT_I1: sent v2I1, expected v2R1
	"psk_to_129"[1] 192.168.173.129 #16: psk_to_129 ESP/AH proposals for initiator: 1:ESP:ENCR=3DES;INTEG=HMAC_MD5_96;ESN=DISABLED
	"psk_to_129"[1] 192.168.173.129 #17: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=3des_cbc_192 integ=md5_96 prf=md5 group=MODP1024}
	packet from 192.168.173.129:500: missing payload(s) (ISAKMP_NEXT_v2SK). Message dropped.
	packet from 192.168.173.129:500: Received v2N_NO_PROPOSAL_CHOSEN notify
	packet from 192.168.173.129:500: missing payload(s) (ISAKMP_NEXT_v2SK). Message dropped.
	packet from 192.168.173.129:500: Received v2N_INVALID_IKE_SPI notify
```
(relevant?) debug logging:
```
	|   ikev2_evaluate_connection_fit evaluating our conn="psk_from_144"[1] 192.168.173.144 I=172.16.1.0/24:17/0 R=192.168.250.0/24:17/1701  to their:
	|     tsi[0]=172.16.1.0-172.16.1.255 proto=17 portrange 5555-5555, tsr[0]=192.168.250.0-192.168.250.255 proto=17 portrange 1701-1701
	| ei->port 0 tsi[tsi_ni].startport 5555  tsi[tsi_ni].endport 5555
	|       has ts_range1=8 maskbits1=24 ts_range2=8 maskbits2=24 fitbits=16448 <> -1
	| prefix fitness found a better match c psk_from_144
	|    tsi[0] 5555-5555: no port match with 0.  fitness 0
	|     port_fitness -1
	| port fitness rejected c psk_from_144 c->name
	| find_host_pair: comparing 192.168.173.129:500 to 0.0.0.0:500
	| find_host_pair: comparing 192.168.173.129:500 to 192.168.173.144:500
	|   checking hostpair 192.168.250.0/24 -> 172.16.1.0/24 is found
	|    match_id a=192.168.173.144
	|             b=192.168.173.144
	|    results  matched
	|   ikev2_evaluate_connection_fit evaluating our conn="psk_from_144"[1] 192.168.173.144 I=172.16.1.0/24:17/0 R=192.168.250.0/24:17/1701  to their:
	|     tsi[0]=172.16.1.0-172.16.1.255 proto=17 portrange 5555-5555, tsr[0]=192.168.250.0-192.168.250.255 proto=17 portrange 1701-1701
	| ei->port 0 tsi[tsi_ni].startport 5555  tsi[tsi_ni].endport 5555
	|       has ts_range1=8 maskbits1=24 ts_range2=8 maskbits2=24 fitbits=16448 <> -1
	| prefix fitness found a better match d psk_from_144
	|    tsi[0] 5555-5555: no port match with 0.  fitness 0
	|     port_fitness -1
	| port fitness rejected d psk_from_144 c->name
	| ikev2_child_sa_respond returned STF_FAIL with v2N_NO_PROPOSAL_CHOSEN
	| ikev2_parent_inI2outR2_tail returned STF_FAIL with v2N_NO_PROPOSAL_CHOSEN
	| #1 complete v2 state transition from STATE_PARENT_R2 with v2N_NO_PROPOSAL_CHOSEN
	| sending a notification reply
	"psk_from_144"[1] 192.168.173.144 #1: sending unencrypted notification v2N_NO_PROPOSAL_CHOSEN to 192.168.173.144:500
```

**Comment by letoams** [comment]
On Feb 3, 2022, at 14:54, cagney ***@***.***> wrote:
> 
> ﻿https://bugs.libreswan.org/show_bug.cgi?id=297
> Doing some experiments with 'narrowing=yes' (possibly related: bug 296) and testing with 'protoport' lead to some surprises..
> 
> Assume the configuration:
> 
>     on node A:
> 	leftprotoport=17/1701
> 	rightprotoport=17/%any
> 	narrowing=yes
> 
>     on node B:
> 	leftprotoport=17/5555
> 	rightprotoport=17/1701
> 	narrowing=yes
> What I would expect in this case is for the SA to be established and to allow traffic between 17/1701 <=> 17/5555.
> 

Assuming left is the same peer on both configs, it should fail because the peers disagree on the port for the left peer.
> What happens instead is that SA is not established (node A rejects the proposal).
> (If config is updated the IKEv1 the SA is established)
> 

Good :)

> A possible use case for the above configuration could be something similar to L2TP: for L2TP (and IKEv1) the server needs to have rightprotoport=17/%any because there are clients that use a fix port (1701) but also clients that use a random UDP port..
> I'm not sure if this is a valid use case for IKEv2 and/or if a similar use case exists for IKEv2.
> 
> Full configuration:
> node A:
> 
> 	# PSK from_144 
> 	conn psk_from_144
> 		authby=secret
> 		auto=add
> 		ike=3des-md5;modp1024
> 		ikelifetime=60m
> 		ikev2=insist
> 		keyingtries=1
> 		keylife=480m
> 		left=192.168.173.129
> 		leftid=192.168.173.129
> 		leftnexthop=192.168.173.2
> 		leftprotoport=17/1701
> 		leftsubnet=192.168.250.0/24
> 		pfs=yes
> 		phase2=esp
> 		phase2alg=3des-md5;modp1024
> 		right=%any
> 		rightid=%any
> 		rightprotoport=17/%any
> 		rightsubnet=172.16.1.0/24
> 		narrowing=yes
> node B:
> 	# PSK to_129 
> 	conn psk_to_129
> 		authby=secret
> 		auto=start
> 		ike=3des-md5;modp1024
> 		ikelifetime=60m
> 		ikev2=insist
> 		keylife=480m
> 		left=192.168.173.144
> 		leftid=192.168.173.144
> 		leftnexthop=192.168.173.2
> 		leftprotoport=17/5555
> 		leftsubnet=172.16.1.0/24
> 		pfs=yes
> 		phase2=esp
> 		phase2alg=3des-md5;modp1024
> 		right=192.168.173.129
> 		rightid=192.168.173.129
> 		rightprotoport=17/1701
> 		rightsubnet=192.168.250.0/24
> 		narrowing=yes
Ahh so the config is actually left = local
for both. In that case it should establish and it should be independent of the narrowing flag as %any here really means “any one specific port”.

Paul

**Comment by cagney** [comment]
This was filed against 3.21 which is way different.  In mainline we have:
- first attempt at finding a template connection checks that END is narrower than TS
should probably checking that END is wider than TS
this would prevent the first loop matching the above config
even if it did match #628 (responder doesn't instantiate template) would still be broken
- second attempt at finding a template connection checks that END is wider-than TS (ya)
however, it also insists on the current connection having NARROWING (pretty arbitrary) + selectors overlap (again arbitrary); both of which look like OE checks

**Comment by cagney** [comment]
tests show this working
