### ISSUE TITLE
implement CHILDLESS_IKEV2_SUPPORTED notify

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#632]
that's the notify, the childless exchange already works

**Comment by cagney** [comment]
5fb2da5557fe96f1102067df5aaeb342eb1337e4

should this be a config option?

**Comment by letoams** [comment]
On Feb 9, 2022, at 15:25, cagney ***@***.***> wrote:
> 
> ﻿
> 5fb2da5
> 
> should this be a config option?
> 

It it works for all connections, no? But if we have a “regular” connection that is brought up childless, it should go into auto=ondemand mode so it can still come up if packets are happening. 

So auto=add plus responding to childless IKE SA becomes ondemand. 

Paul
