### ISSUE TITLE
CERTREQ contains the CKAID (sha1) of the Certification Authority's public key and not an ASN.1 DER

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#653]
Ref: https://datatracker.ietf.org/doc/html/rfc7296#section-3.7
_The Certification Authority field contains an indicator of trusted authorities for this certificate type.  The Certification Authority value is a concatenated list of SHA-1 hashes of the public keys of trusted Certification Authorities (CAs).  Each is encoded as the SHA-1 hash of the Subject Public Key Info element (see Section 4.1.2.7 of [[PKIX] (https://datatracker.ietf.org/doc/html/rfc7296#ref-PKIX)]) from each Trust Anchor certificate. The 20-octet hashes are concatenated and included with no other formatting._

**Comment by cagney** [comment]
Example when strongswan is initiator:
| CR
|   44 6a 46 b8  8c 9a 50 87  e5 87 03 b8  c3 2d 76 d4   DjF...P......-v.
|   6e 6b 12 f5                                          nk..
"rw-eap"[2] 192.1.3.209 #2: ignoring CERTREQ payload that is not ASN1: content is not binary ASN.1

**Comment by cagney** [comment]
Fixed emitted CERTREQ.  Use presence of CERTREQ as a hint to send one.

**Comment by letoams** [comment]
On Fri, 19 Aug 2022, cagney wrote:

> Fixed emitted CERTREQ. Use presence of CERTREQ as a hint to send one.

It's a decent reason to sent one, but it should not be the sole/only
reason, as we can have asymmetric auth. In reality, we should check the
rightauth= to see if it requires a cert and by which CA and then if
we have that, sent it ?

**Comment by cagney** [comment]
> It's a decent reason to sent one, but it should not be the sole/only reason, as we can have asymmetric auth.

It's the last of a list of conditions.  ikev2_send_cert_decision() looks at the local config, while the CERTREQ decision code looks at the remote config.
