### ISSUE TITLE
Pluto crashed/restarted by remote side during connection termination (IKEv2). Affected version: >= 3.15

### ISSUE THREAD

**Issue by shurkaxaa** [libreswan/libreswan#67]
If remote side send two (>=2) SA delete payload where IKE SA delete payload is last
pluto crashed.
Libreswan assumes that IKE SA delete payload can be the only one in message.
There are check about multiple delete payload which works when IKE SA is not last - in that case libreswan does not crash but return failure, but if IKE SA delete payload is last in list of payloads pluto crashed with abort.
1. It looks bad that remote side can crash the service via INVALID packet.
2. It seems assumption is wrong - RFCs (4306, 5996) does not state that IKE SA delete payload should be only payload in message, it allows multiple delete payloads for different type of SA's. https://tools.ietf.org/html/rfc5996#section-3.11 From RFC: **It is permitted, however, to  include multiple Delete payloads in a single INFORMATIONAL exchange  where each Delete payload lists SPIs for a different protocol.**

Part of debug log:
Jul 27 17:04:45: | Now let's proceed with payload (ISAKMP_NEXT_v2D)
Jul 27 17:04:45: | *_parse IKEv2 Delete Payload:
Jul 27 17:04:45: |    next payload type: ISAKMP_NEXT_v2D (0x2a)
Jul 27 17:04:45: |    flags: none (0x0)
Jul 27 17:04:45: |    length: 12 (0xc)
Jul 27 17:04:45: |    protocol ID: PROTO_IPSEC_ESP (0x3)
Jul 27 17:04:45: |    SPI size: 4 (0x4)
Jul 27 17:04:45: |    number of SPIs: 1 (0x1)
Jul 27 17:04:45: | processing payload: ISAKMP_NEXT_v2D (len=12)
Jul 27 17:04:45: | Now let's proceed with payload (ISAKMP_NEXT_v2D)
Jul 27 17:04:45: | *_parse IKEv2 Delete Payload:
Jul 27 17:04:45: |    next payload type: ISAKMP_NEXT_v2NONE (0x0)
Jul 27 17:04:45: |    flags: none (0x0)
Jul 27 17:04:45: |    length: 8 (0x8)
Jul 27 17:04:45: |    protocol ID: PROTO_ISAKMP (0x1)
Jul 27 17:04:45: |    SPI size: 0 (0x0)
Jul 27 17:04:45: |    number of SPIs: 0 (0x0)
Jul 27 17:04:45: | processing payload: ISAKMP_NEXT_v2D (len=8)
...
Jul 27 17:04:45: "enb" #1: ASSERTION FAILED at /builddir/build/BUILD/libreswan-3.15/programs/pluto/ikev2_parent.c:4083: p == md->ch
ain[ISAKMP_NEXT_v2D]

Code:
programs/pluto/ikev2_parent.c:process_encrypted_informational_ikev2

```
...
                        switch (v2del->isad_protoid) {
                        case PROTO_ISAKMP:
                                /*
                                 * There can be only one Delete Payload
                                 * if it is ISAKMP
                                 */
                                passert(p == md->chain[ISAKMP_NEXT_v2D]);
                                break;
...
```

**Comment by letoams** [comment]
This is fixed with https://github.com/libreswan/libreswan/commit/f4a2f375b350d59c996762761eb61b062d2391cd

please test, as we do not have a device that sends such odd delete payloads
