### ISSUE TITLE
was authby=secret,rsa or some other combination supported by IKEv1?

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#677]
Based on IKEv1's aggressive and main mode db_sa_tables, it would appear that combinations such as:

| Policy                                  | aggr | main |
| ---                                        | ---    | ---     |
| PSK                                    | Y      | Y      |
| RSA                                    |   Y    |    Y  |
| PSK+RSA                           |   N     | Y     |
| XSERVER+PSK                  | Y      | Y      |
| XSERVER+RSA                  | Y      | Y      |
| XSERVER+PSK+RSA           |   N     | Y     |
| XCLIENT+PSK                   | Y      | Y      |
| XCLIENT+RSA                   | Y      | Y      |
| XCLIENT+PSK+RSA           |   N     | Y     |

were supported at some point but I can't find any evidence of this in the testsuite?

- the default policy, from IKEv1's POV is just RSA (everything else is tossed), at some point it probably included PSK so at that point the "feature" may have worked in main mode
- all IKEv1 tests use authby=foo (my attempt at aggr+authby=secret,rsasig core dumped!)
- support for authby=foo,bar was only a relatively recent addition 5d2283092dc8063b94f2f7c64b991ab9f1321f2e

Should this feature officially be dropped?

**Comment by paulwouters** [comment]
It was supported but has a buggy history and I’ve recommended against trying to use it for at least a decade. It als makes little sense as you either do rsa or psk. Migration can be done with two separate conns 

Sent using a virtual keyboard on a phone

**Comment by cagney** [comment]
Support, what ever there was, dropped.
