### ISSUE TITLE
https://libreswan.org/man/ipsec_pluto.8.html says to see the ipsec_pluto.8.html man page

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#685]
https://libreswan.org/man/ipsec_pluto.8.html

**Comment by jlearman** [comment]
Seriously!  Please fix this.  I can't find any documentation for the `whack` command that corresponds to the released code.  6 months?

**Comment by cagney** [comment]
A solution to #848 would let us fix this.  Patches welcome.
In the mean time see `man ipsec whack`.

**Comment by letoams** [comment]
On Fri, 28 Oct 2022, Jeff Learman wrote:

> Seriously! Please fix this. I can't find any documentation for the whack command that corresponds to the released code. 6 months?

There is always "ipsec whack --help"

Note that whack is supposed to be an internal API, and you are supposed
to use configuration files and not whack commands directly.

If 6 months is too much for you on this issue, please feel free to
donate either time or money to the Libreswan Project :)

**Comment by jlearman** [comment]
I couldn't find the source for the documentation.  Point me to that and I might be able to help.

I'd rather not have to spin up a docker just to use `man whack`.  The instance where I run `whack` doesn't (and won't) support `man`.  I don't want to install Libreswan on my dev box for a number of reasons (mostly, so I don't accidentally add a build dependency, as other teammates won't be installing it.)

For applications like k8s Submariner, the `whack` interface is more appropriate than changing config files and poking a daemon.  The file method is ideal for a host or workstation providing a relatively static set of IPsec tunnels, but it's not ideal for multi-cloud interconnection.

**Comment by cagney** [comment]
currently xmlto is used: https://github.com/libreswan/libreswan/blob/main/mk/manpages.mk
sources: https://github.com/libreswan/libreswan/blob/main/programs/pluto/ipsec_pluto.8.xml

**Comment by cagney** [comment]
https://testing.libreswan.org/latest/documentation/
web pages need update.

**Comment by cagney** [comment]
superseeded by nightly documentation builds and

- [ ] #1354
