### ISSUE TITLE
boot linux kvm directly from the kernel

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#711]
From IRC:
```
<cagney> yea, next testing thing to figure out is probably live snapshots - less than a second to "boot" (restore) the running vm
<antony> cagney: I book KVM image using kernel, instead of BIOS, grub… that is very quick. I think reboot time is about 2 seconds. in the xml point the kernel.
<bleve> kvm bios emulation is quite slow.
<antony>    <kernel>/home/a/git/linux/arch/x86/boot/bzImage</kernel>
<antony>     <cmdline>root=/dev/vda1 rhgb console=tty0 rd_NO_PLYMOUTH console=ttyS0,115200 net.ifnames=0 biosdevname=0 selinux=0</cmdline>
<antony> this is inside <os>
<antony> I think this also cuts off using intrd and speed up.
<cagney> antony, so that would let us "correctly" boot into fips
<antony> I would guess so. Is that cmdline? note "<cmdline> above.
<cagney> I believe so
```
some notes
- the upgrade or transmogrify script could grab the kernel and save it to /pool
- test domains are built using XML
- the build domain is constructed on the flu
- if FIPS is embedded in the VM's boot line there would need to be separate VMs for FIPS and non-FIPS modes; much like we've ended up with for BSD

**Comment by cagney** [comment]
Domains added with f5610fa1aaccaffba34b69cc4e35216076488ce6
but they can't yet boot into fips mode :-/

**Comment by cagney** [comment]
This doesn't inspire confidence:
https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/html/administration_guide/enabling-fips_in_rhv

**Comment by paulwouters** [comment]
They say that only because running in non-FIPS first then switching to FIPS can break some assumptions - eg keys being insecurely imported.

Sent using a virtual keyboard on a phone

**Comment by cagney** [comment]
> They say that only because running in non-FIPS first then switching to FIPS can break some assumptions - eg keys being insecurely imported.

That's the rationale.  We need a way to bypass this.

**Comment by cagney** [comment]
need a way to boot the guest in FIPS mode even though the host is not in FIPS mode

**Comment by cagney** [comment]
splitting bug
