### ISSUE TITLE
opportunistic IPSec doesn't seem to work

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#73]
I've installed libreswan 3.18 and am trying to follow the instructions at https://libreswan.org/wiki/HOWTO:_Opportunistic_IPsec from a machine that has a public IP address and is not behind a NAT.

After copying `oe-upgrade-authnull.conf`  into `/etc/ipsec.d/`, i tried:

```
0 root@machine:~# systemctl restart ipsec
0 root@machine:~# ipsec whack --trafficstatus
000  
000  
0 root@machine:~# ping -c2 oe.libreswan.org
PING oe.libreswan.org (193.110.157.124) 56(84) bytes of data.
64 bytes from oe.libreswan.org (193.110.157.124): icmp_seq=1 ttl=48 time=98.0 ms
64 bytes from oe.libreswan.org (193.110.157.124): icmp_seq=2 ttl=48 time=98.4 ms

--- oe.libreswan.org ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 98.042/98.246/98.451/0.374 ms
0 root@machine:~# ipsec whack --trafficstatus
000  
0 root@machine:~# 
```

It's not clear to me what i should expect to see, but it doesn't look to me like anything useful is happening there.  Maybe the documentation is out of date?  or maybe the test server is down?  or maybe there's a step that's missing?  I don't know how to debug.

**Comment by letoams** [comment]
please retry with libreswan 3.10. See also nohats.ca/LE/ and http://events.linuxfoundation.org/sites/events/files/slides/LinuxSecuritySummit-2016-OE-16x9.pdf

**Comment by letoams** [comment]
this issue was resolved on the test server - not a code issue
