### ISSUE TITLE
[HELP] : Configuration ikev1 with user signed certificate and private key , and company public key 

### ISSUE THREAD

**Issue by jhay06** [libreswan/libreswan#734]
Hi ,
 Would like to request help configuring libreswan to work with our company network

in windows we can easily connect to the network using Forcepoint VPN 6.X , other version doesn't work since linux and mac has 2.X version so technically forcepoint for mac and linux wont work

Please see below scenario 

1. I created .csr file from the forcepoint and send it to our admin
2. The admin send us .crt file and .prv file (signed certificate and private key file)
3. I can find where is our public key file , (.ca file to be specific)

So technically i have 
The IPSEC address of our company for example it is 120.10.10.10
i have .crt file , the .prv file and the public .ca file 
Phase 1 algorithm is using a bit old algo = 3des-sha1-modp1024
same in ESP phase 2  = 3des-sha1-modp1024

For me to connect to our server i should match the libreswan config with below flow
ME -> phase 1 authentication with signed cert , private key file with password -> when ok -> Phase 2 authentication with the public key-> company 

Actually i already had config, i can pass through phase 1 and phase 2 but sadly i'm stuck with possibly  awaiting CFG_SET (phase 2)

below is the sample config, ( I changed the IP for the protection of the privacy of the company )

conn xauth-rsa
    authby=rsasig
    pfs=no
    auto=start
    rekey=no
    left=%defaultroute
    leftcert=me
    leftid=me@InternalDomain
    leftsendcert=always
    leftxauthusername=me@InternalDomain
    rightsubnet=10.0.2.2/20 # company subnet to be give to the left ??
    right=10.0.2.1 #company IP address
    rightid=%fromcert
    rightxauthserver=yes
    leftxauthclient=yes
    rightmodecfgserver=yes
    leftmodecfgclient=yes
    modecfgpull=yes
    xauthby=alwaysok
    fragmentation=no
    xauthfail=soft
    dpdaction=restart
    modecfgdns=192.168.1.15,192.168.1.16,192.168.1.17  #dns of the internal network of the company??
    aggrmode=no  #this is the only working 
    type=tunnel
    ikev2=permit
    ike=3des-sha1;modp1024
    esp=3des-sha1;modp1024
    encapsulation=yes
    fake-strongswan=yes
    keyingtries=%forever
    ikelifetime=86400s
    keylife=28800s
    compress=no
    initial-contact=yes

hope that someone helps me figure this out . thanks

**Comment by letoams** [comment]
modp1024 is not compiled in by default because it is too weak. 

For other issues, we would need to see logs

Sent using a virtual keyboard on a phone

**Comment by jhay06** [comment]
> modp1024 is not compiled in by default because it is too weak. For other issues, we would need to see logs Sent using a virtual keyboard on a phone
> […](#)
> On May 27, 2022, at 01:36, jhay06 ***@***.***> wrote: ﻿ Hi , Would like to request help configuring libreswan to work with our company network in windows we can easily connect to the network using Forcepoint VPN 6.X , other version doesn't work since linux and mac has 2.X version so technically forcepoint for mac and linux wont work Please see below scenario I created .csr file from the forcepoint and send it to our admin The admin send us .crt file and .prv file (signed certificate and private key file) I can find where is our public key file , (.ca file to be specific) So technically i have The IPSEC address of our company for example it is 120.10.10.10 i have .crt file , the .prv file and the public .ca file Phase 1 algorithm is using a bit old algo = 3des-sha1-modp1024 same in ESP phase 2 = 3des-sha1-modp1024 For me to connect to our server i should match the libreswan config with below flow ME -> phase 1 authentication with signed cert , private key file with password -> when ok -> Phase 2 authentication with the public key-> company Actually i already had config, i can pass through phase 1 and phase 2 but sadly i'm stuck with possibly awaiting CFG_SET (phase 2) below is the sample config, ( I changed the IP for the protection of the privacy of the company ) conn xauth-rsa authby=rsasig pfs=no auto=start rekey=no left=%defaultroute leftcert=me ***@***.*** leftsendcert=always ***@***.*** rightsubnet=10.0.2.2/20 # company subnet to be give to the left ?? right=10.0.2.1 #company IP address rightid=%fromcert rightxauthserver=yes leftxauthclient=yes rightmodecfgserver=yes leftmodecfgclient=yes modecfgpull=yes xauthby=alwaysok fragmentation=no xauthfail=soft dpdaction=restart modecfgdns=192.168.1.15,192.168.1.16,192.168.1.17 #dns of the internal network of the company?? aggrmode=no #this is the only working type=tunnel ikev2=permit ike=3des-sha1;modp1024 esp=3des-sha1;modp1024 encapsulation=yes fake-strongswan=yes keyingtries=%forever ikelifetime=86400s keylife=28800s compress=no initial-contact=yes hope that someone helps me figure this out . thanks — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

i forgot to mention that i compiled libreswan with USE_DH2=true option

**Comment by jhay06** [comment]
below is the last log i get  i change the user for the privacy
May 28 13:57:29 ubuntu pluto[55403]: "xauth-rsa" #1: XAUTH client - possibly awaiting CFG_set {auth=RSA_SIG cipher=3DES_CBC_192 int>
May 28 13:57:30 ubuntu pluto[55403]: "xauth-rsa" #1: STATE_XAUTH_I1: retransmission; will wait 0.5 seconds for response
May 28 13:57:30 ubuntu pluto[55403]: "xauth-rsa" #1: STATE_XAUTH_I1: retransmission; will wait 1 seconds for response
May 28 13:57:31 ubuntu pluto[55403]: "xauth-rsa" #1: STATE_XAUTH_I1: retransmission; will wait 2 seconds for response
May 28 13:57:32 ubuntu pluto[55403]: "xauth-rsa" #1: XAUTH: Answering XAUTH challenge with user='me@InternalDomain'
May 28 13:57:32 ubuntu pluto[55403]: "xauth-rsa" #1: XAUTH client - possibly awaiting CFG_set {auth=RSA_SIG cipher=3DES_CBC_192 int>
May 28 13:57:32 ubuntu pluto[55403]: "xauth-rsa" #1: STATE_XAUTH_I1: retransmission; will wait 0.5 seconds for response
May 28 13:57:33 ubuntu pluto[55403]: "xauth-rsa" #1: STATE_XAUTH_I1: retransmission; will wait 1 seconds for response
May 28 13:57:34 ubuntu pluto[55403]: "xauth-rsa" #1: STATE_XAUTH_I1: retransmission; will wait 2 seconds for response
May 28 13:57:36 ubuntu pluto[55403]: "xauth-rsa" #1: STATE_XAUTH_I1: retransmission; will wait 4 seconds for response
May 28 13:57:37 ubuntu pluto[55403]: "xauth-rsa" #1: Received Cisco XAUTH status: FAIL
May 28 13:57:37 ubuntu pluto[55403]: "xauth-rsa" #1: xauth: xauth_client_ackstatus() returned STF_OK
May 28 13:57:37 ubuntu pluto[55403]: "xauth-rsa" #1: XAUTH: aborting entire IKE Exchange
May 28 13:57:37 ubuntu pluto[55403]: "xauth-rsa" #1: encountered fatal error in state STATE_XAUTH_I1
May 28 13:57:37 ubuntu pluto[55403]: "xauth-rsa" #1: deleting state (STATE_XAUTH_I1) aged 9.806106s and sending notification

**Comment by letoams** [comment]
On Fri, 27 May 2022, jhay06 wrote:

> May 28 13:57:32 ubuntu pluto[55403]: "xauth-rsa" #1: XAUTH: Answering XAUTH challenge with ***@***.***'
> May 28 13:57:32 ubuntu pluto[55403]: "xauth-rsa" #1: XAUTH client - possibly awaiting CFG_set {auth=RSA_SIG cipher=3DES_CBC_192
> int>

> May 28 13:57:37 ubuntu pluto[55403]: "xauth-rsa" #1: Received Cisco XAUTH status: FAIL

Looks like the xauth user/password is wrong? If using odd characters,
try using quotes, or try one with only regular letters for testing?

**Comment by jhay06** [comment]
i believe i used the correct password that match with my private key 

please see below example format of my password

@me : XAUTH "1d$!trz1"

**Comment by letoams** [comment]
The “!” Is known to cause problems on some systems. Other systems might try to pose $! as a variable. I recommend trying to remove those.

Sent using a virtual keyboard on a phone

**Comment by bleve** [comment]
jhay06: you have missed something important - xauth has nothing to do with your certificate passphrase - xauth is about username/password authentication with ikev1.

**Comment by jhay06** [comment]
> The “!” Is known to cause problems on some systems. Other systems might try to pose $! as a variable. I recommend trying to remove those. Sent using a virtual keyboard on a phone
> […](#)
> On May 29, 2022, at 00:19, jhay06 ***@***.***> wrote: ﻿ i believe i used the correct password that match with my private key please see below example format of my password @me : XAUTH "1d$!trz1" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

Hi , i already did this i change to mepass123 but error still the same

**Comment by jhay06** [comment]
> jhay06: you have missed something important - xauth has nothing to do with your certificate passphrase - xauth is about username/password authentication with ikev1.

noted, but can you give me ideas why libreswan stuck on posibly await cfg set ? 

or can you give me sample config base on the scenario given 

I tried strongswan but no luck , the only works on strongswan is the charon-cmd  using ikev1-pub as profile and i can login  but charon gave me incorrect subnet ,

in strongswan charon-cmd , below is my config that works upto authentication 
sudo charon-cmd --host my.company.ip --identity me@InternalDomain \
--ike-proposal 3des-sha1-modp1024 --esp-proposal 3des-sha1-modp1024 --xauth-username me@InternalDomain \
 --cert mysigned.crt --rsa mykey.prv --profile ikev1-pub  \
--cert mycompany1pub.ca --cert mycompany2pub.ca

Then once i run that command it will prompt password

so i put 1d$!trz1

then it success but wrong virtual ip subnet that's why i switch to libreswan ,

**Comment by jhay06** [comment]
okay i got different error message now when i set both leftxauthclient and rightxauthserver to no 

May 30 10:37:24 jhayvm pluto[37178]: "xauth-rsa" #2: sent Quick Mode request
May 30 10:37:25 jhayvm pluto[37178]: "xauth-rsa" #2: up-client output: updating resolvconf
May 30 10:37:25 jhayvm pluto[37178]: "xauth-rsa" #2: up-client output: /usr/local/libexec/ipsec/_updown.xfrm: 410: cannot create /etc/resolv>
May 30 10:37:25 jhayvm pluto[37178]: "xauth-rsa" #2: IPsec SA established tunnel mode {ESP=>0x6085b92c <0x346933c8 xfrm=3DES_CBC-HMAC_SHA1_9>
May 30 10:37:25 jhayvm pluto[37178]: netlink_expire got XFRM_MSG_EXPIRE message with length 60 < 232 bytes; ignore message
May 30 10:37:25 jhayvm pluto[37178]: netlink_expire got XFRM_MSG_EXPIRE message with length 68 < 232 bytes; ignore message

**Comment by letoams** [comment]
Means the tunnel is up now

Sent using a virtual keyboard on a phone

**Comment by jhay06** [comment]
yeah i think tunnel was already up . but the problem now is it cannot browse nor ping anything . it cannot ping DNS of the company even if it was added at resolv.conf.

**Comment by paulwouters** [comment]
If you have further information, feel free to re-open this issue
