### ISSUE TITLE
rightsubnets parameter not working

### ISSUE THREAD

**Issue by jhay06** [libreswan/libreswan#752]
Hi , 
    I saw on the documentation that libreswan support multiple subnets using rightsubnets and omit rightsubnet

i tried to use rightsubnets instead of rightsubnet but per checking it is not working

rightsubnets=f.f.f.f/24,x.x.x.x/24   not working 
rightsubnets={f.f.f.f/24,x.x.x.x/24} not working
rightsubnets ={f.f.f.f/24 x.x.x.x/24} not working
rightsubnets="f.f.f.f/24 x.x.x.x/24} not working
rightsubnets=f.f.f.f/24 even this is not working

all of the above falls with the same log output

May 31 15:35:53 jhayvm pluto[18386]: adding UDP interface tun0 10.8.0.1:4500
May 31 15:35:53 jhayvm pluto[18386]: adding UDP interface enp0s3 10.0.2.15:500
May 31 15:35:53 jhayvm pluto[18386]: adding UDP interface enp0s3 10.0.2.15:4500
May 31 15:35:53 jhayvm pluto[18386]: adding UDP interface lo 127.0.0.1:500
May 31 15:35:53 jhayvm pluto[18386]: adding UDP interface lo 127.0.0.1:4500
May 31 15:35:53 jhayvm pluto[18386]: adding UDP interface lo [::1]:500
May 31 15:35:53 jhayvm pluto[18386]: loading secrets from "/etc/ipsec.secrets"
May 31 15:35:53 jhayvm pluto[18386]: no secrets filename matched "/etc/ipsec.d/*.secrets"
May 31 15:35:53 jhayvm pluto[18386]: initiating all conns with alias='mysample'
May 31 15:35:53 jhayvm pluto[18386]: no connection named "mysample"

but removing rightsubnets and use rightsubnet=f.f.f.f/24   is working

this is problematic on some systems that has multiple sites with different subnets like mine 

our company has multiple subnets 

10.XXX.XXX.XXX/16
192.168.XXX.XXX/24

is there anyway that i can add those subnet outside ipsec.conf ? 

what i mean is when i start the libreswan and already connected to the server 
can i add manually those ip's and subnets using the command "ip /ifconfig /route/iptables " ?

thanks

**Comment by jhay06** [comment]
actually there's no other error found except the one that i sent .

but i already found the way that this will work , i dont know why it works but when i add 

leftsubnets = with the same value as rightsubnets , it works 
but unfortunately we have 364 subnets and when i try to add it on rightsubnets and leftsubnets 
starting the ipsec tooks me 3 hours . 
i think because it tunnel all leftsubnet to rightsubnets in cross method, what i mean is when i have 364 right and left it goes like this 364x364 so it will install 132,496 policies in total

**Comment by cagney** [comment]
please use subnet=<list> and mainline
