### ISSUE TITLE
ERROR: netlink response for Add SA esp.aa0d2fb9@172.16.5.91 included errno 22: Invalid argument

### ISSUE THREAD

**Issue by tedx** [libreswan/libreswan#753]
I'm trying to get labeled ipsec working between a rhel8 libreswan-4.4-4 and rhel7 version 3.35-9 but am getting errors. The configs on both sides look the same just flipping the left and right:
conn comms
     auto=start
     authby=secret
     type=transport
     left=172.16.5.92
     right=172.16.5.91
     ike=aes256-sha1
     phase2=esp
     phase2alg=aes256-sha1
     policy_label=system_u:object_r:ipsec_spd_t:s0-s15:c0.c1023
     ikelifetime=24h
     salifetime=24h
     dpddelay=30
     dpdtimeout=120
     dpdaction=restart_by_peer
     replay-window=256
     ikev2=no

Can anyone shed light on what the issue might be?

[pluto.log](https://github.com/libreswan/libreswan/files/8806678/pluto.log)

**Comment by cagney** [comment]
Would you be able to try version 4.7?

Would you be able to try 4.7?

This:
```
May 31 15:35:29.433254: adding UDP interface lo 127.0.0.1:4500
May 31 15:35:29.433268: ERROR: socket() in bind_udp_socket(). Errno 2: No such file or directory
```
has me puzzled, here's what 4.7 looks like:
```
adding UDP interface lo 127.0.0.1:500
| newref struct iface_endpoint@0x7fdc38003f38(0->1) (bind_iface_endpoint() +388 /programs/pluto/iface.c)
| addref struct iface_dev@0x7fdc37ffbfa8(2->3) (bind_iface_endpoint() +388 /programs/pluto/iface.c)
| NAT-Traversal: Trying sockopt style NAT-T
| NAT-Traversal: ESPINUDP(2) setup succeeded for sockopt style NAT-T family IPv4
```

This:
```
May 31 15:35:30.265807: "comms" #5: ERROR: netlink response for Add SA esp.eb6261cf@172.16.5.91 included errno 22: Invalid argument
May 31 15:35:30.265814: "comms" #5: setup_half_ipsec_sa() hit fail:
```
also has me puzzled.  Like the next issue, it may have been fixed.

This:
```
May 31 15:36:30.263676: "comms" #5: ERROR: netlink response for Del SA esp.eb6261cf@... included errno 3: No such process
```
looks like a bug where the SA was deleted twice the first delete succeeded but the second failed (there was no such sa (process_). 4.4 exposed the problem.  4.7 includes the fix.

**Comment by letoams** [comment]
On Wed, 1 Jun 2022, Ted X Toth wrote:

> As I'm connecting a rhel7 to rhel8 or 9 I didn't think I could use
> ikev2 since it wouldn't work for label ipsec on rhel7, right?

We are not sure if the ikev1 version still works as the old version did
in the latest releases.

For ikev2 labeled ipsec on rhel7. you'd have to compile libreswan yourself,
or grab the pre-made binaries from the libreswan project from:

https://downloads.libreswan.org/binaries/rhel/7/

I know Red Hat would no longer pull in any libreswan updates into rhel7
unless it was a serious security issue.

If you get things working with ikev1 or ikev2, I'd be interested to hear that.

Paul

**Comment by tedx** [comment]
The rhel7<->rhel8 ikev1 labeled ipsec (aside from the confusing 'error'
messages) works fine. Next I'm going to try rhel7<->rhel9 and will report
back how it goes. Regarding rhel7 we're sort of in the same place as RH and
don't want to do anything unless absolutely necessary. Eventually all of
our rhel7 installs will be updated.

Ted

**Comment by letoams** [comment]
On Tue, 31 May 2022, Ted X Toth wrote:

> I'm trying to get labeled ipsec working between a rhel8 libreswan-4.4-4 and rhel7 version 3.35-9 but am getting errors. The configs on both sides look the
> same just flipping the left and right:

I would really only use libreswan 4.5+ for labeled ipsec, due to the
changes with properly supporting on-demand SAs and childless IKE SA.

Paul
