### ISSUE TITLE
DEFAULT_DNSSEC_ROOTKEY_FILE is probably wrong

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#755]
mk/config.mk has the default:
  DEFAULT_DNSSEC_ROOTKEY_FILE ?= "/var/lib/unbound/root.key"
which is then passed to unbound_event_init() via the variable pluto_dnssec_rootfile.

Suspect it would be better to provide no default and either let libunbound use something built in, or specify the default per-os.

**Comment by letoams** [comment]
On Fri, 3 Jun 2022, cagney wrote:

> mk/config.mk has the default:
> DEFAULT_DNSSEC_ROOTKEY_FILE ?= "/var/lib/unbound/root.key"
> which is then passed to unbound_event_init() via the variable
> pluto_dnssec_rootfile.
> 
> Suspect it would be better to provide no default and either let libunbound
> use something built in, or specify the default per-os.

libunbound used to have no defaults, where as the unbound daemon would
have this. It might be that libunbound has been extended to read a
config file, but even in that case there might not be an unbound.conf
unless there the daemon package is installed too.

If the file location is known for other OSes and their init systems,
support should be added there to place the right file into our
ipsec.conf.

**Comment by cagney** [comment]
4dac0fdf7f205e0d1fe45e673239e6e7ecfb3d54
