### ISSUE TITLE
Error when Make Program

### ISSUE THREAD

**Issue by saower** [libreswan/libreswan#76]
sr/local/lib/libevent_pthreads.so: undefined reference to `event_mm_malloc_'
/usr/local/lib/libevent_pthreads.so: undefined reference to`event_mm_free_'
/usr/local/lib/libevent_pthreads.so: undefined reference to `evthread_set_id_callback'
/usr/local/lib/libevent_pthreads.so: undefined reference to`evthread_set_lock_callbacks'
collect2: ld returned 1 exit status
make[3]: **\* [pluto] Error 1
make[3]: Leaving directory `/root/libreswan/OBJ.linux.x86_64/programs/pluto'
make[2]: *** [local-base] Error 2
make[2]: Leaving directory`/root/libreswan/programs/pluto'
make[1]: **\* [all] Error 2
make[1]: Leaving directory `/root/libreswan/programs'
make: **\* [all] Error 2

**Comment by letoams** [comment]
Odd, you can try adding "-lpthread -levent" to USERCOMPILE in mk/userland-cflags.mk ?

**Comment by letoams** [comment]
ping ?

**Comment by saower** [comment]
@letoams  thanks , i resolve this problem.
