### ISSUE TITLE
[Error on Ubuntu ] building libreswan

### ISSUE THREAD

**Issue by jhay06** [libreswan/libreswan#764]
Before i had successfully build the 4.7 version from the main branch without error ,  i think it is during May , 
but when i try to build from the main branch i suddenly got this error when using this command "make base"
make[3]: *** [../../mk/rules.mk:63: ike_alg_prf_ikev1_nss_ops.o] Error 1
make[2]: *** [../../mk/targets.mk:69: base] Error 2
make[2]: Leaving directory '/home/xxxx/libreswan/lib/libswan'
make[1]: *** [../mk/targets.mk:69: recursive-base] Error 2
make[1]: Leaving directory '/home/xxxx/libreswan/lib'
make: *** [/home/xxxx/libreswan/mk/targets.mk:69: recursive-base] Error 2

Please take a look with my makefile.inc.local this is the default makefile.inc.local i used in every libreswan build 

WERROR_CFLAGS =
USE_DNSSEC = false
USE_DH31 = false
USE_NSS_AVA_COPY = true
USE_NSS_IPSEC_PROFILE = false
USE_GLIBC_KERN_FLIP_HEADERS = true
USE_DH2 = true

But as off today it doesn't work anymore.

please help

**Comment by jhay06** [comment]
okay for now this was solved , 

i cloned again the libreswan and then i switch the head into commit id ac63cff549a3427e4f9599643ed826cbf388905a   this is the last commit ID from June 8 and confirm that this works . 

will fork the libreswan and create own branch for the working version thanks

**Comment by cagney** [comment]
@antonyantony fixed this with 6a0440d4e6d724dafc57cd0ef9d843f11a90af90
