### ISSUE TITLE
Add libgmp3-dev to dependencies list

### ISSUE THREAD

**Issue by roadriverrail** [libreswan/libreswan#77]
Looks like libgmp3 is now a dependency; it should be added to the package install commands in your README.md.

**Comment by bleve** [comment]
No. libgmp is not build dependency.

**Comment by letoams** [comment]
libgmp is no longer used by libreswan

**Comment by roadriverrail** [comment]
Hunh.  I was getting a build break until I installed it.  My mistake,
clearly.

**Comment by letoams** [comment]
Then you are using an older version of libreswan

**Comment by letoams** [comment]
gmp is no longer used by libreswan
