### ISSUE TITLE
error: conflicting types for 'ttobinary' after sa-expire-20220705 merge

### ISSUE THREAD

**Issue by bleve** [libreswan/libreswan#791]
32bit build fails after sa-expire-20220705 merge

/builddir/build/BUILD/libreswan-4.7/lib/libswan/ttobinary-iec-60027-2.c:31:8: error: conflicting types for 'ttobinary'
 diag_t ttobinary(const char *t, uint64_t *r, bool prefix_B)
        ^~~~~~~~~
In file included from /builddir/build/BUILD/libreswan-4.7/lib/libswan/ttobinary-iec-60027-2.c:23:
../../include/binary-iec-60027-2.h:22:8: note: previous declaration of 'ttobinary' was here
 diag_t ttobinary(const char *t, unsigned long *b, bool prefix_B);
        ^~~~~~~~~
make[3]: *** [../../mk/rules.mk:63: ttobinary-iec-60027-2.o] Error 1

**Comment by letoams** [comment]
On Wed, 6 Jul 2022, bleve wrote:

> /builddir/build/BUILD/libreswan-4.7/lib/libswan/ttobinary-iec-60027-2.c:31:8: error: conflicting types for 'ttobinary'
> diag_t ttobinary(const char *t, uint64_t *r, bool prefix_B)
> ^~~~~~~~~
> In file included from /builddir/build/BUILD/libreswan-4.7/lib/libswan/ttobinary-iec-60027-2.c:23:
> ../../include/binary-iec-60027-2.h:22:8: note: previous declaration of 'ttobinary' was here
> diag_t ttobinary(const char *t, unsigned long *b, bool prefix_B);
> ^~~~~~~~~
> make[3]: *** [../../mk/rules.mk:63: ttobinary-iec-60027-2.o] Error 1

The below patch fixes these, but that does assume 32 bit kernels use
64bit counters? Perhaps Antony can confirm that before I apply the patch
to main.

Paul

diff --git a/include/binary-iec-60027-2.h b/include/binary-iec-60027-2.h
index 6c3b0ba270..a36bd1241e 100644
--- a/include/binary-iec-60027-2.h
+++ b/include/binary-iec-60027-2.h
@@ -19,6 +19,6 @@
 
 #include "diag.h"
 
-diag_t ttobinary(const char *t, unsigned long *b, bool prefix_B);
+diag_t ttobinary(const char *t, uint64_t *b, bool prefix_B);
 
 #endif
diff --git a/lib/libipsecconf/parser.y b/lib/libipsecconf/parser.y
index 10094124b8..8bf23257c4 100644
--- a/lib/libipsecconf/parser.y
+++ b/lib/libipsecconf/parser.y
@@ -340,7 +340,7 @@ statement_kw:
 	| BINARYWORD EQUAL STRING {
 		struct keyword *kw = &$1;
 		const char *const str = $3;
-		unsigned long b;
+		uint64_t b;
 
 		diag_t diag = ttobinary(str, &b, 0 /* no B prefix */);
 		if (diag != NULL) {
@@ -358,7 +358,7 @@ statement_kw:
 	| BYTEWORD EQUAL STRING {
 		struct keyword *kw = &$1;
 		const char *const str = $3;
-		unsigned long b;
+		uint64_t b;
 
 		diag_t diag = ttobinary(str, &b, 1 /* with B prefix */);
 		if (diag != NULL) {
diff --git a/programs/pluto/kernel.c b/programs/pluto/kernel.c
index 93e0a9a05c..f3da29821f 100644
--- a/programs/pluto/kernel.c
+++ b/programs/pluto/kernel.c
@@ -1956,7 +1956,7 @@ static bool setup_half_ipsec_sa(struct state *st, bool inbound)
 						   c->sa_ipsec_max_packets,
 						   margin_packets,
 						   c->sa_rekey_fuzz);
-		dbg("%s %d #%lu ipsec-max-bytes %lu/%lu ipsec-max-packets %lu/%lu margin bytes %lu margin mackets %lu IPSEC_SA_MAX_SOFT_LIMIT_PERCENTAGE %u", __func__, __LINE__,  st->st_serialno,  sa_ipsec_soft_bytes, c->sa_ipsec_max_bytes, sa_ipsec_soft_packets, c->sa_ipsec_max_packets, margin_bytes, margin_packets, IPSEC_SA_MAX_SOFT_LIMIT_PERCENTAGE);
+		dbg("%s %d #%lu ipsec-max-bytes %"PRIu64"/%"PRIu64" ipsec-max-packets %"PRIu64"/%"PRIu64" margin bytes %"PRIu64" margin packets %"PRIu64" IPSEC_SA_MAX_SOFT_LIMIT_PERCENTAGE %u", __func__, __LINE__,  st->st_serialno,  sa_ipsec_soft_bytes, c->sa_ipsec_max_bytes, sa_ipsec_soft_packets, c->sa_ipsec_max_packets, margin_bytes, margin_packets, IPSEC_SA_MAX_SOFT_LIMIT_PERCENTAGE);
 	}
 	const struct kernel_sa said_boilerplate = {
 		.src.address = &kernel_policy.src.host,

**Comment by bleve** [comment]
This got fixed with fee9e621e21ecc54003561142cbc6dbaf6cda997.
