### ISSUE TITLE
The vti interface vanishes when peer goes down and up

### ISSUE THREAD

**Issue by yu-shiba** [libreswan/libreswan#80]
I was build and tested route based vpn(libreswan <-> libreswan) from master branch source. 
```
    left=x.x.x.x
    leftid=y.y.y.y
    leftsubnet=0.0.0.0/0
    right=z.z.z.z
    rightid=z.z.z.z
    rightsubnet=0.0.0.0/0
    mark=1/0xffffffff
    vti-interface=vti01
    vti-routing=no
    vti-shared=no
    leftvti=169.254.252.XXX/30
```
Normal startup is not a problem.
But, when the connection peer goes down and up, the vti interface leave deleted.
This situation is fixed unless it is restarted.

In a little examination, _updown.netkey script receives the **down-client**, script got PLUTO_CONN_KIND was 'CK_PERMANENT'.
I wonder if we do not consider this situation.

**Comment by letoams** [comment]
if the connection goes down because the remote peer stops responding, it is expected that we tear down the tunnel, and the VTI interface.

But once the remote peer comes back again, the tunnel is expected to re-establish and the VTI interface should be re-added again.

So I dont think your patch is correct. When the connection is not shared and the connection is a permanent, then there should not be other users of the VTI device, and so deletion seems right?

But perhaps because we are going down and then up perhaps we are not properly re-adding the VTI device

**Comment by yu-shiba** [comment]
I thought so. But it remained deleted.

I tested it was route based vpn(*subnet=subnet=0.0.0.0/0), it related to it?
The addition of vti is executed at **prepare-host** or **prepare-client**, but will not it be triggered at route based vpn.

**Comment by letoams** [comment]
On Fri, 24 Mar 2017, Yuichiro SHIBAYAMA wrote:

> I tested it was route based vpn(*subnet=subnet=0.0.0.0/0), it related to it?
> The addition of vti is executed at prepare-host or prepare-client, but will not it be triggered at route based
> vpn.

If you have a remote subnet of 0.0.0.0/0 then you are basically setting
up a routing based VPN, so that means you are expected to manually
route anything you want to pass through the VPN (and you cannot set
vti-routing=yes because you cannot route 0.0.0.0/0 over the VTI
device without imploding your connectivity.

Paul

**Comment by yu-shiba** [comment]
Since I want to route dynamically using bgp, and chosed "route based vpn", but are you using the wrong way?

I finally want to make a connection with the following.
- AWS VPC
- Yamaha vpn router (RTX 1200)
- Linux (libreswan)

**Comment by letoams** [comment]
If you want the vti device to stay, you can force it using vti-shared=yes

But that's no substitute for proper BCP38 egress filtering.

**Comment by MorphBonehunter** [comment]
It seems we have an similar behavior.
I've setup 2 Tunnels to AWS as an routed IPSEC (i set vti-interface, vti-routing=no and vti-shared=no (default))
It works if i add the connection and set it up, the interface is added and all seems to work.
If i tear down the connection (--down) the interfaces got deleted.
If i try to establish the connection afterwards the interface doesn't reapear.
The only solution is to delete, re-add the connection and startup so the interface reapears.

**Comment by letoams** [comment]
On Thu, 20 Apr 2017, DWE wrote:

> It seems we have an similar behavior.
> I've setup 2 Tunnels to AWS as an routed IPSEC (i set vti-interface, vti-routing=no and vti-shared=no (default))
> It works if i add the connection and set it up, the interface is added and all seems to work.
> If i tear down the connection (--down) the interfaces got deleted.
> If i try to establish the connection afterwards the interface doesn't reapear.
> The only solution is to delete, re-add the connection and startup so the interface reapears.

Yes I think we need to tune this behaviour better. I guess --down should
not delete the interface. Only --delete should do that.

Paul

**Comment by keelsjd** [comment]
Hi Guys,

Is there any way to stop this from happening? 
I have a multi-vti setup and everytime I reset a tunnel the remote vti is deleted.

Thank You,
Mihai

**Comment by letoams** [comment]
On Wed, 11 Apr 2018, keelsjd wrote:

> Is there any way to stop this from happening?
> I have a multi-vti setup and everytime I reset a tunnel the remote vti is deleted.

Currently, the kernel VTI implementation really only supports one VTI
device with a remote peer unset. So if you are using roadwarriors, and
have multiple connections (eg multi-tenant) then you can only use the
same VTI device.

You can use multiple VTI devices if the remote peer's IP is known and
the VTI device is configured with the remote IP.

But note that currently VTI devices do not work for /32 remote subnets.

If you set vti-shared=yes, the device will not be removed.

Paul

**Comment by keelsjd** [comment]
Hi,

Thanks for your response, actually i need two vti devices.
For vti0  i have a roadwarrior configuration with multiple tunnels and right=%any
For vti1 the peer is a fixed ip address and i tried with vti-shared=yes and it doesn't bring up the vti1 interface(vti0 is there).

Thanks,
Mihai

**Comment by letoams** [comment]
On Thu, 12 Apr 2018, keelsjd wrote:

> Thanks for your response, actually i need two vti devices.
> For vti0 i have a roadwarrior configuration with multiple tunnels and right=%any
> For vti1 the peer is a fixed ip address and i tried with vti-shared=yes and it doesn't bring up the vti1
> interface(vti0 is there).

You still need to set a mark, but in that case since it is a static
tunnel, just set it to something low, eg 1.

Paul

**Comment by keelsjd** [comment]
For the vti0/vti1 i had mark=0xff00/0xff00.
I modified it for vti1 to mark=1xff00/0xff00 and mark=5/0xffffffff, i added vti-shared=yes and the result was : there is no incoming traffic through the vti anymore so i revert back to the original configuration. 
I'm not really familiar with marking. 
Any ideas?

Thank You,

**Comment by vitorhugop** [comment]
Hi.

I had a similiar problem and solved after long times of study.

When de other side of the tunnel goes down and up, replace or restart the ipsec, my vti interface is deleted and when the tunnel goes up the vti interface doesn't create again. 

In the 3.23 version with this was solved but the routes for the other side subnet aren't created. 

I do a change in the "up-client" function in the script: "/usr/libexec/ipsec/_updown.netkey" and this solved my problem.

**LibreSwan 3.20:**

> up-client)
>         # connection to my client subnet coming up
>         # If you are doing a custom version, firewall commands go here.
>         updateresolvconf
>         addcat
>         addsource
>         notifyNM connect
>         ;;

**LibreSwan 3.23:**

> up-client)
>         # connection to my client subnet coming up
>         # If you are doing a custom version, firewall commands go here.
>         addvtiiface
>         updateresolvconf
>         addcat
>         addsource
>         notifyNM connect
>         ;;


**My changes in the script:**

> up-client)
>         # connection to my client subnet coming up
>         # If you are doing a custom version, firewall commands go here.
>         addvtiiface
>         updateresolvconf
>         addcat
>         addsource
>         notifyNM connect
>         addvti
>         ;;


Thanks, Vitor Hugo Pereira.

**Comment by letoams** [comment]
On Mon, 16 Apr 2018, vitorhugop wrote:

this is already fixed in commit 6ae8d5999062ff9864163f4fce2650e8cbc8a94b
and will be released with 3.24.

Paul

**Comment by vitorhugop** [comment]
Paul.

I see this commit but it doesn't solved all my problem. Just with "**addvtiiface**" my interface vti goes up but the route to the otherside subnet wasn't created. Adding the "**addvti**" to the **up-client** the routes are created too and the problem has been fully resolved.

**Comment by keelsjd** [comment]
Hi Victor,

Thanks for your advice. I tried to modify up-client and i can't get the routes to the other side working.
In the end i added the routes manually in the file with ip ro add x.x.x.x/x dev vti1 but this is a workaround.
We have 4 tunnels with 4 subnets.
I'm using  Libreswan 3.23 (netkey) and modified it like so:

1. 1st try:
    # connection to my client subnet coming up
    # If you are doing a custom version, firewall commands go here.
    addvtiiface  <----
    updateresolvconf
    addcat
    addsource
    notifyNM connect
    ;;
===> no routes
2. 2nd try:
 # connection to my client subnet coming up
    # If you are doing a custom version, firewall commands go here.
    addvtiiface <---------
    updateresolvconf
    addcat
    addsource
    notifyNM connect
    addvti <------------
    ;;
===> no routes
3. 3rd try:
 # connection to my client subnet coming up
    # If you are doing a custom version, firewall commands go here.
    addvtiiface <---------
    updateresolvconf
    addcat
    addsource
    notifyNM connect
    uproute <------------
    ;;
===> it adds the route of the last tunnel only.
If i restart the service, all routes are there. When i reset the tunnels from the remote server i only get the last tunnel route.

**Comment by vitorhugop** [comment]
Hi **keelsjd**.

What's your configuration about vti_shared and vti_routing?


Do you can do a simple test? In the "**up-client**" session add a echo like:

>      up-client)
>         # connection to my client subnet coming up
>         # If you are doing a custom version, firewall commands go here.
>         **echo "Testing keelsjd - up-client"**
>         addvtiiface
>         updateresolvconf
>         addcat
>         addsource
>         notifyNM connect
>         addvti


After that do you restart the tunnel from the remote server and look the pluto log's like:

> tail -f /var/log/pluto.log  | grep -i keelsjd

This is a test just to see if the "up-client" is executed when the otherside restart the tunnel.

**Comment by keelsjd** [comment]
It's executed because i added the routes manually there like this:
	ip ro add a.a.a.a/27 dev vti1
	ip ro add b.b.b.b/26 dev vti1 
	ip ro add c.c.c.c/29 dev vti1
	ip ro add d.d.d.d/28 dev vti1 

The interesting thing is that for the vti0 the routes are added as it should.

**Comment by vitorhugop** [comment]
Yes, correctly.

Can you send your ipsec configuration? Subnets, vti options..

**Comment by keelsjd** [comment]
Hi,

The configuration looks like bellow. There are 6-12 tunnels/connection. The only thing that changes for each tunnel is the left/right subnet. For vti0 it's all working as expected.

1. The remote is with %any%:
#VTI0
config setup
	interfaces="%none"

conn peer-peer0-tunnel-0
	left=PUBLIC_IP
	right="%any"
	rightid="@peer0"
	rekey=yes
	leftsubnet=X.X.X.X/24
	rightsubnet=Y.Y.Y.Y/24
	leftsourceip=PUBLIC_IP
	ike=aes256-sha1-modp1024
	ikelifetime=3600s
	dpddelay=30
	dpdtimeout=120
	dpdaction=restart
	keylife=3600s
	rekeymargin=540s
	type=tunnel
	pfs=no
	compress=no
	authby=secret
	auto=start
	keyingtries=%forever
	vti-interface=vti0
	vti-routing=no
	mark=0xff00/0xff00
	nat-keepalive=yes

2. The remote peer has a static IP address:
#VTI1

config setup
	interfaces="%none"

conn peer-REMOTE_PUBLIC_IP-tunnel-0
	left=PUBLIC_IP
	right=REMOTE_PUBLIC_IP
	rightid=REMOTE_PUBLIC_IP
	leftsubnet=A.A.A.A/24
	rightsubnet=B.B.B.B/24
	leftsourceip=PUBLIC_IP
	ike=aes256-sha1-modp1024
	ikelifetime=86400s
	dpddelay=30
	dpdtimeout=120
	dpdaction=restart
	keylife=3600s
	rekeymargin=540s
	type=tunnel
	pfs=no
	compress=no
	authby=secret
	auto=start
	keyingtries=%forever
	vti-interface=vti1
	vti-routing=no
	mark=0xff00/0xff00
	nat-keepalive=yes

**Comment by aston-r** [comment]
@vitorhugop 

I had the two tunnels with VTI configuration(vti_shared=no,vti_routing=yes) and faced the issue, that routes are not restored after the DPD restart:
```
Sep 25 16:13:05.579677: "vpn-1" #13: IKEv1 DPD: action - restarting all connections that share this peer
Sep 25 16:13:05.579708: "vpn-1" #13: terminating SAs using this connection
Sep 25 16:13:05.579717: "vpn-1" #16: deleting state (STATE_QUICK_I1) and NOT sending notification
Sep 25 16:13:05.579816: "vpn-1" #3: deleting state (STATE_QUICK_I2) and sending notification
Sep 25 16:13:05.579845: "vpn-1" #3: ESP traffic information: in=545KB out=1MB
....
Sep 25 16:13:05.592282: "vpn-1" #3: down-client output: + ip route del 172.16.0.0/16 dev vti01 src 10.0.2.15
....
....
Sep 25 16:13:06.224481: "vpn-1" #18: up-client output: + case "${PLUTO_VERB}" in
Sep 25 16:13:06.224528: "vpn-1" #18: up-client output: + addvtiiface
....
Sep 25 16:13:06.226896: "vpn-1" #18: up-client output: + return 0
Sep 25 16:13:06.227569: "vpn-1" #18: STATE_QUICK_I2: sent QI2, IPsec SA established tunnel mode {ESP=>0x06b8a1b5 <0xf19fb5b8 xfrm=AES_CBC_128-HMAC_SHA1_96 NATOA=none NATD=none DPD=active}
```
```
> ipsec status | grep Total
000 Total IPsec connections: loaded 2, active 2
```
```
> ip r s | grep vti
192.168.0.0/16 dev vti02 scope link src 10.0.2.15 
```
```
> sudo systemctl restart ipsec.service
```
```
> ip r s | grep vti
172.16.0.0/16 dev vti01 scope link src 10.0.2.15 
192.168.0.0/16 dev vti02 scope link src 10.0.2.15 
```

I also added the execution of 'addvti' function to 'up-client' block and it fixed the issue with routes. I attached the log with enabled strace in _updown.netkey
[ipsec-vti.zip](https://github.com/libreswan/libreswan/files/2418455/ipsec-vti.zip)

**Comment by aston-r** [comment]
@letoams @vitorhugop 
[pluto-vti-patch.zip](https://github.com/libreswan/libreswan/files/2422918/pluto-vti-patch.zip)


I have performed more tests and the following workaround definitely fixes the issue with absent route after reconnection. You can check the logs in my previous reply where routes are not added and also I added logs with patch. 

I want to use VTI and avoid patching. Is there any chance that this issue will be fixed in the upcoming release or there is alternative way to fix?
```
diff --git a/programs/_updown.netkey/_updown.netkey.in b/programs/_updown.netkey/_updown.netkey.in
index 69c01b8c4..fd7723387 100644
--- a/programs/_updown.netkey/_updown.netkey.in
+++ b/programs/_updown.netkey/_updown.netkey.in
@@ -784,6 +784,7 @@ case "${PLUTO_VERB}" in
        addcat
        addsource
        notifyNM connect
+       addvti
        ;;
     down-client)
        # connection to my client subnet going down

```

Here is part the log with this patch(I can attach the full log if you need):
```
Sep 27 00:10:01.718208: "vpn-1" #71: up-client output: + ip -o route get 10.0.2.15
Sep 27 00:10:01.719384: "vpn-1" #71: up-client output: + return 0
Sep 27 00:10:01.719425: "vpn-1" #71: up-client output: + notifyNM connect
Sep 27 00:10:01.719463: "vpn-1" #71: up-client output: + '[' 00 -eq 1 ']'
Sep 27 00:10:01.719475: "vpn-1" #71: up-client output: + return 0
Sep 27 00:10:01.719495: "vpn-1" #71: up-client output: + addvti
Sep 27 00:10:01.719528: "vpn-1" #71: up-client output: + '[' -n vti01 ']'
Sep 27 00:10:01.719551: "vpn-1" #71: up-client output: + '[' -z 4294967295/0xffffffff -o -z 4294967295/0xffffffff ']'
Sep 27 00:10:01.719563: "vpn-1" #71: up-client output: + '[' yes = yes ']'
Sep 27 00:10:01.719579: "vpn-1" #71: up-client output: + r=add
Sep 27 00:10:01.719900: "vpn-1" #71: up-client output: + ip route list
Sep 27 00:10:01.720013: "vpn-1" #71: up-client output: + grep -q 172.16.0.0
Sep 27 00:10:01.721284: "vpn-1" #71: up-client output: + '[' add = change ']'
Sep 27 00:10:01.721303: "vpn-1" #71: up-client output: + srcip=
Sep 27 00:10:01.721311: "vpn-1" #71: up-client output: + '[' -n 10.0.2.15 ']'
Sep 27 00:10:01.721321: "vpn-1" #71: up-client output: + srcip=' src 10.0.2.15'
Sep 27 00:10:01.721348: "vpn-1" #71: up-client output: + ip route add 172.16.0.0/16 dev vti01 src 10.0.2.15
Sep 27 00:10:01.726085: "vpn-1" #71: up-client output: + echo 'done ip route'
Sep 27 00:10:01.726111: "vpn-1" #71: up-client output: done ip route
Sep 27 00:10:01.726874: "vpn-1" #71: STATE_QUICK_I2: sent QI2, IPsec SA established tunnel mode {ESP=>0x66fcb4c2 <0xaf8f5e87 xfrm=AES_CBC_128-HMAC_SHA1_96 NATOA=none NATD=none DPD=active}
```

**Comment by letoams** [comment]
applied will be in 3.27

**Comment by LiRunqiu** [comment]
> On Wed, 11 Apr 2018, keelsjd wrote: Is there any way to stop this from happening? I have a multi-vti setup and everytime I reset a tunnel the remote vti is deleted.
> Currently, the kernel VTI implementation really only supports one VTI device with a remote peer unset. So if you are using roadwarriors, and have multiple connections (eg multi-tenant) then you can only use the same VTI device. You can use multiple VTI devices if the remote peer's IP is known and the VTI device is configured with the remote IP. But note that currently VTI devices do not work for /32 remote subnets. If you set vti-shared=yes, the device will not be removed. Paul


why vti do not work for /32 remote subnets

**Comment by letoams** [comment]
It’s an implementation limitation that triggered a redesign using xfrmi interfaces. Use those.

>
