### ISSUE TITLE
Libreswan 4.7 doesn't listen on IPv6:4500 port by default

### ISSUE THREAD

**Issue by mtodorov3-69** [libreswan/libreswan#800]
Libreswan 4.7 doesn't appear to listen on port 4500 using IPv6 in the default configuration.
Windows 10 VPN client probes that port on the VPN server.

I was instructed to raise an issue on this problem.
Here is a list of ports it is listening on (edited):

```
root@host:~/libreswan-4.7-dh2# lsof -n -p 3534408 | grep IP
pluto   3534408 root   15u     IPv4           40373142      0t0      UDP 10.0.0.102:isakmp
pluto   3534408 root   16u     IPv4           40373143      0t0      UDP 10.0.0.102:ipsec-nat-t
pluto   3534408 root   17u     IPv4           40373144      0t0      UDP 161.53.nn.3:isakmp
pluto   3534408 root   18u     IPv4           40373145      0t0      UDP 161.53.nn.3:ipsec-nat-t
pluto   3534408 root   19u     IPv4           40373146      0t0      UDP 127.0.0.1:isakmp
pluto   3534408 root   20u     IPv4           40373147      0t0      UDP 127.0.0.1:ipsec-nat-t
pluto   3534408 root   21u     IPv6           40373148      0t0      UDP [::1]:isakmp
pluto   3534408 root   22u     IPv6           40373149      0t0      UDP [2001:dead:beef::3]:isakmp
root@host:~/libreswan-4.7-dh2#

```

The config for the connection is:

```
conn MYCONN-ikev2-ipv6-cp
        # The server's actual IP goes here - not elastic IPs
        left=2001:dead:beef::3
        leftcert=vpn2.domain.hr
        leftid=@vpn2.domain.hr
        leftsendcert=always
        leftsubnet=0::/0
        leftrsasigkey=%cert
        # Clients
        right=%any
        # your addresspool to use - you might need NAT rules if providing full internet to clients
        rightaddresspool=2001:dead:beef:1000::/70
        # optional rightid with restrictions
        # rightid="O=GRF-UNIZG,CN=win7client.domain.hr"
        rightca=%same
        rightrsasigkey=%cert
        #
        # connection configuration
        # DNS servers for clients to use
        modecfgdns=2001:deaf:beef::3,2606:4700:4700::1001
        narrowing=yes
        # recommended dpd/liveness to cleanup vanished clients
        dpddelay=30
        dpdtimeout=120
        dpdaction=clear
        auto=add
        ikev2=insist
        rekey=no
        # Set ikelifetime and keylife to same defaults windows has
        # ikelifetime=8h
        # keylife=2h
        ms-dh-downgrade=yes
        esp=aes_gcm256,aes_gcm128,aes256-sha2_512,aes128-sha2_512,aes256-sha1,aes128-sha1
        # esp=aes_gcm256-null,aes_gcm128-null,aes256-sha2_512,aes128-sha2_512,aes256-sha1,aes128-sha1,aes_gcm256-null;modp1024
        # ikev2 fragmentation support requires libreswan 3.14 or newer
        fragmentation=yes
        # optional PAM username verification (eg to implement bandwidth quota
        # pam-authorize=yes
        authby=rsa-sha1
        hostaddrfamily=ipv6
        clientaddrfamily=ipv6

```

That about covers it.

**Comment by cagney** [comment]
Here's the relevant code.  Note the confusion in the comments:
```
                        /*
                         * From linux's xfrm: right now, we do not support
                         * NAT-T on IPv6, because the kernel did not support
                         * it, and gave an error it one tried to turn it on.
                         *
                         * From bsd's kame: right now, we do not support NAT-T
                         * on IPv6, because the kernel did not support it, and
                         * gave an error it one tried to turn it on.
                         *
                         * XXX: Who should we believe?
                         *
                         * Port 4500 can add the ESP encapsulation prefix.
                         * Let it float to itself - code might rely on it?
                         */
                        if (address_type(&ifd->id_address) == &ipv4_info) {
                                bind_iface_endpoint(ifd, &udp_iface_io,
                                                    ip_hport(NAT_IKE_UDP_PORT),
                                                    true /*esp_encapsulation_enabled*/,
                                                    true /*float_nat_initiator*/,
                                                    logger);
                        }
```

**Comment by letoams** [comment]
Listening and using 4500 is orthogonal to NAT. Without NAT it is still legal to only ever use 4500, even starting from IKE_INIT.

For ikev2 anyway. 

Sent using a virtual keyboard on a phone

**Comment by cagney** [comment]
> Listening and using 4500 is orthogonal to NAT. Without NAT it is still legal to only ever use 4500, even starting from IKE_INIT.  For ikev2 anyway. Sent using a virtual keyboard on a phone

My hunch is that it is referring to the 00000000 prefix.
Given that the comments and code pre-date history. this has presumably been fixed (my assumption is that the original comment was in the Linux code.  Either way we get to test.

**Comment by mtodorov3-69** [comment]
> Listening and using 4500 is orthogonal to NAT. Without NAT it is still legal to only ever use 4500, even starting from IKE_INIT. For ikev2 anyway. Sent using a virtual keyboard on a phone
> […](#)
> On Jul 18, 2022, at 08:20, cagney ***@***.***> wrote: ﻿ Here's the relevant code. Note the confusion in the comments: /* * From linux's xfrm: right now, we do not support * NAT-T on IPv6, because the kernel did not support * it, and gave an error it one tried to turn it on. * * From bsd's kame: right now, we do not support NAT-T * on IPv6, because the kernel did not support it, and * gave an error it one tried to turn it on. * * XXX: Who should we believe? * * Port 4500 can add the ESP encapsulation prefix. * Let it float to itself - code might rely on it? */ if (address_type(&ifd->id_address) == &ipv4_info) { bind_iface_endpoint(ifd, &udp_iface_io, ip_hport(NAT_IKE_UDP_PORT), true /*esp_encapsulation_enabled*/, true /*float_nat_initiator*/, logger); } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

To support his, I can quote RFC 5996, https://datatracker.ietf.org/doc/html/rfc5996#section-2.23

```
o Implementations MUST process received UDP-encapsulated ESP packets
      even when no NAT was detected.

```

**Comment by bleve** [comment]
That's not possible because kernel doesn't support udp encapsulated ESP with ipv6.

**Comment by letoams** [comment]
We can and still should respond to ike on port 4500, even if we do not support NAT for ipv6. It was RFC 7296 also says.

Sent using a virtual keyboard on a phone

**Comment by mtodorov3-69** [comment]
> That's not possible because kernel doesn't support udp encapsulated ESP with ipv6.

Please forgive my rudeness, does this [patch](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0146dca70b877b73c5fd9c67912b8a0ca8a7bac7) mean that this was remedied now?

**Comment by mtodorov3-69** [comment]
After compiling the github code, I can confirm that it connected over VPN IPv6 from my home installation:

`Jul 28 22:06:41.944910: "MYCONN-ikev2-ipv6-cp"[2] 2a05:4f46:31a:7500::2 #2: responder established Child SA using #1; IPsec tunnel [::-ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff:0-65535 0] -> [2001:b68:2:2600:1000::-2001:b68:2:2600:1000:::0-65535 0] {ESP=>0x98cfb898 <0xb11155a2 xfrm=AES_CBC_256-HMAC_SHA1_96 DPD=active}
`

I am afraid to express how happy I am to see libreswan just snapped in so elegant. This fixes our regression in VPN connectivity because of upgrading to the IPv6 protocol :-))))

More testing will show tomorrow from a different IPv6 setup. 

Thank Good Heavens!
