### ISSUE TITLE
dropping unexpected ISAKMP_v2_IKE_AUTH message containing v2N_TS_UNACCEPTABLE notification; message payloads: SK; encrypted payloads: IDr,AUTH,N,V; unexpected payloads: IDr,AUTH

### ISSUE THREAD

**Issue by 3xplisit** [libreswan/libreswan#801]
Background:

I need to connect to A cisco ASA VPN Connection from my Ubuntu Server 22.04

My configuration is as follows

conn cisco-to-them

        left=%defaultroute
        leftid=140.XX.XX.XX
        leftsubnet=10.XX.XX.XX/24

        right=197.XX.XX.XX
        rightid=197.XX.XX.XX
        rightsubnet=10.XX.XX.XX/32

        type=tunnel
        ikev2=yes
        pfs=yes
        encapsulation=yes
        fragmentation=yes
        mobike=no
        dpdaction=hold
        dpddelay=300
        rekey=no
        dpdtimeout=120
        aggressive=yes
        phase2=esp

        phase2alg=aes256-sha1;modp1536
        authby=secret
        ike=aes256-sha1;modp1536
        #esp=aes_cbc_256-sha1;dh5
        ikelifetime=86400
        keylife=86400
        auto=start

The ipsec.secrets file has also been configured with the correct source and destination and the Pre Shared Key

I get the error as shown below

181 "cisco-to-them" #15: initiating IKEv2 IKE SA
181 "cisco-to-them" #15: STATE_PARENT_I1: sent v2I1, expected v2R1
182 "cisco-to-them" #16: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=AES_CBC_256 integ=HMAC_SHA1_96 prf=HMAC_SHA1 group=MODP1536}
003 "cisco-to-them" #16: dropping unexpected ISAKMP_v2_IKE_AUTH message containing v2N_TS_UNACCEPTABLE notification; message payloads: SK; encrypted payloads: IDr,AUTH,N,V; unexpected payloads: IDr,AUTH

I am requesting for assistance on this issue. What could i have been doing wrong.

**Comment by letoams** [comment]
On Tue, 19 Jul 2022, Jesse Kariuki wrote:

> 003 "cisco-to-them" #16: dropping unexpected ISAKMP_v2_IKE_AUTH message containing v2N_TS_UNACCEPTABLE notification; message payloads: SK; encrypted

So v2N_TS_UNACCEPTABLE means the Traffic Selectors don't match between the endpoints.

> My configuration is as follows
> 
> conn cisco-to-them
>
>     left=%defaultroute
>     leftid=140.XX.XX.XX
>     leftsubnet=10.XX.XX.XX/24
>
>     right=197.XX.XX.XX
>     rightid=197.XX.XX.XX
>     rightsubnet=10.XX.XX.XX/32

So 10.XX.XX.XX/24 with 10.XX.XX.XX/32 is not what is configured on that
other endpoint.

Paul

**Comment by 3xplisit** [comment]
Much thanks for your response on this. I will request the other end for the correct details mapped on their side.

**Comment by 3xplisit** [comment]
Update I have changed the subnet on my leftsubnet to /32 and re established the connection details. And I have established a connection but I'm not able to ping the rightsubnet. 

Any assistance on this. Much appreciated.

**Comment by letoams** [comment]
On Tue, 19 Jul 2022, Jesse Kariuki wrote:

> Update I have changed the subnet on my leftsubnet to /32 and re established the connection details. And I have
> established a connection but I'm not able to ping the rightsubnet.

use "ping -s leftsubnetip ipinrightsubnet to ensure you use the proper
src/dst that matches your ipsec policy. You can also add
leftsourceip=YourLeftSubnetIP to let libreswan add a route with src
automatically.

Paul

**Comment by 3xplisit** [comment]
There was an issue with the partner they fixed the problem on their end

**Comment by cagney** [comment]
> There was an issue with the partner they fixed the problem on their end
