### ISSUE TITLE
IPsec/L2TP Windows 11 client behind masquerade do not connect

### ISSUE THREAD

**Issue by muhlpachr** [libreswan/libreswan#802]
I have MSW11 IPsec/L2TP client behind masquerade.

I am able to connect W11 client only sometimes after sucessfull connect of RouterOS client from same LAN (Pluto is able to establish IPsec IKEv1 phase 2 only after some internal cleanup - it seams like timing rare condition).
Random src UDP ports ISAKMP and ESP are not trouble, RouterOS IPsec/L2TP client connects everytime with various src ports.

Attached are Pluto logs for ok and failed connection of W11 client.
[pluto_failed.log](https://github.com/libreswan/libreswan/files/9189092/pluto_failed.log)
[pluto_ok.log](https://github.com/libreswan/libreswan/files/9189091/pluto_ok.log)

My intention is to use IPsec/L2TP because I need way for VPN setup without Admin rights on MSW11.

How can I modify Pluto config to stabilize connection please ?
It seams from log there are more attempts (there are 5x instancies of IKEv1 phase 1 established in OK log with W11 client before IKEv1 phase 2 gets through) - why is that ?

For failed attempt RasClient in MSW11 emit event:
The user MICHAL-NUC\michal dialed a connection named vpn which has failed. The error code returned on failure is 809.
But traffic from W11 client reach Pluto without interfere (it is visible from logs).

Thank you.

Regards,
Michal

```
/etc/ipsec.conf
version 2.0

config setup
  virtual-private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!192.168.16.0/24,%v4:!192.168.43.0/24
  uniqueids=no
  logfile=/var/log/pluto.log
  plutodebug=base

conn shared
  left=%defaultroute
  leftid=159.223.22.103
  right=%any
  encapsulation=yes
  authby=secret
  pfs=no
  rekey=no
  keyingtries=5
  dpddelay=30
  dpdtimeout=300
  dpdaction=clear
  ikev2=never
  ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1,aes256-sha2;modp1024,aes128-sha1;modp1024
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes256-sha2_512,aes128-sha2,aes256-sha2
  ikelifetime=24h
  salifetime=24h
  sha2-truncbug=no

conn l2tp-psk
  auto=add
  leftprotoport=17/1701
  rightprotoport=17/%any
  type=transport
  also=shared
```

**Comment by letoams** [comment]
On Tue, 26 Jul 2022, Michal Mühlpachr wrote:

> My intention is to use IPsec/L2TP because I need way for VPN setup without Admin rights on MSW11.

You can do that with libreswan 4.7 if you use EAPTLS. In fact, that is
the main reason for wanting/needing to support EATPLS with libreswan.

Paul

**Comment by paulwouters** [comment]
you cannot reliably do L2TP IPsec in transport mode from behind the same NAT twice. Please switch to IKEv2 with EAPTLS that uses IPsec tunnel mode.
