### ISSUE TITLE
how to connect multiple clients

### ISSUE THREAD

**Issue by yygyqkhh** [libreswan/libreswan#805]
Hello,Libreswan IKEV2 how to connect multiple clients with multiple certificates? I applied for two certificates with different names and I couldn't connect to the server at the same time.

certutil -z <(head -c 1024 /dev/urandom) \
  -S -c "IKEv2 VPN CA" -n "vpnclient" \
  -s "O=IKEv2 VPN,CN=vpnclient" \
  -k rsa -g 4096 -v 120 \
  -d sql:/etc/ipsec.d -t ",," \
  --keyUsage digitalSignature,keyEncipherment \
  --extKeyUsage serverAuth,clientAuth -8 "vpnclient"

certutil -z <(head -c 1024 /dev/urandom) \
  -S -c "IKEv2 VPN CA" -n "vpnclient2" \
  -s "O=IKEv2 VPN,CN=vpnclient2" \
  -k rsa -g 4096 -v 120 \
  -d sql:/etc/ipsec.d -t ",," \
  --keyUsage digitalSignature,keyEncipherment \
  --extKeyUsage serverAuth,clientAuth -8 "vpnclient2"

**Comment by letoams** [comment]
Many people use it, so it must be something specific to your configuration. Please share configuration and/or logs ?

Sent using a virtual keyboard on a phone

**Comment by yygyqkhh** [comment]
> 



> Many people use it, so it must be something specific to your configuration. Please share configuration and/or logs ? Sent using a virtual keyboard on a phone
> […](#)
> On Jul 28, 2022, at 00:19, yygyqkhh ***@***.***> wrote: ﻿ Hello,Libreswan IKEV2 how to connect multiple clients with multiple certificates? I applied for two certificates with different names and I couldn't connect to the server at the same time. certutil -z <(head -c 1024 /dev/urandom) -S -c "IKEv2 VPN CA" -n "vpnclient" -s "O=IKEv2 VPN,CN=vpnclient" -k rsa -g 4096 -v 120 -d sql:/etc/ipsec.d -t ",," --keyUsage digitalSignature,keyEncipherment --extKeyUsage serverAuth,clientAuth -8 "vpnclient" certutil -z <(head -c 1024 /dev/urandom) -S -c "IKEv2 VPN CA" -n "vpnclient2" -s "O=IKEv2 VPN,CN=vpnclient2" -k rsa -g 4096 -v 120 -d sql:/etc/ipsec.d -t ",," --keyUsage digitalSignature,keyEncipherment --extKeyUsage serverAuth,clientAuth -8 "vpnclient2" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

Thank you for your reply. I first use PC to link to the server, and then I can't link with my iPhone. Here is the code.

conn ikev2
 left=%defaultroute
 leftcert=x.x.x.x
 leftsendcert=always
 leftsubnet=0.0.0.0/0
 leftrsasigkey=%cert
 right=%any
 rightca=%same
 rightrsasigkey=%cert
 narrowing=yes
 dpddelay=30
 dpdtimeout=120
 dpdaction=clear
 auto=add
 ikev2=insist
 rekey=no
 pfs=no
 ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1
 phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
 ikelifetime=24h
 salifetime=24h
 encapsulation=yes
 leftid=x.yx.z.a
 modecfgdns=x.x.x.x

conn vpnclient
 rightid="CH=vpnclient"
 also=ikev2

conn vpnclient2
 rightid="CN=vpnclient2"
 also=ikev2

**Comment by yygyqkhh** [comment]
> Many people use it, so it must be something specific to your configuration. Please share configuration and/or logs ? Sent using a virtual keyboard on a phone
> […](#)
> On Jul 28, 2022, at 00:19, yygyqkhh ***@***.***> wrote: ﻿ Hello,Libreswan IKEV2 how to connect multiple clients with multiple certificates? I applied for two certificates with different names and I couldn't connect to the server at the same time. certutil -z <(head -c 1024 /dev/urandom) -S -c "IKEv2 VPN CA" -n "vpnclient" -s "O=IKEv2 VPN,CN=vpnclient" -k rsa -g 4096 -v 120 -d sql:/etc/ipsec.d -t ",," --keyUsage digitalSignature,keyEncipherment --extKeyUsage serverAuth,clientAuth -8 "vpnclient" certutil -z <(head -c 1024 /dev/urandom) -S -c "IKEv2 VPN CA" -n "vpnclient2" -s "O=IKEv2 VPN,CN=vpnclient2" -k rsa -g 4096 -v 120 -d sql:/etc/ipsec.d -t ",," --keyUsage digitalSignature,keyEncipherment --extKeyUsage serverAuth,clientAuth -8 "vpnclient2" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

Thank you for your reply. I first use PC to link to the server, and then I can't link with my iPhone. Here is the code.

conn ikev2
left=%defaultroute
leftcert=x.x.x.x
leftsendcert=always
leftsubnet=0.0.0.0/0
leftrsasigkey=%cert
right=%any
rightca=%same
rightrsasigkey=%cert
narrowing=yes
dpddelay=30
dpdtimeout=120
dpdaction=clear
auto=add
ikev2=insist
rekey=no
pfs=no
ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1
phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
ikelifetime=24h
salifetime=24h
encapsulation=yes
leftid=x.yx.z.a
modecfgdns=x.x.x.x

conn vpnclient
rightid="CN=vpnclient"
also=ikev2

conn vpnclient2
rightid="CN=vpnclient2"
also=ikev2

**Comment by letoams** [comment]
Try using one conn with rightid=%any

Sent using a virtual keyboard on a phone

**Comment by yygyqkhh** [comment]
> 尝试使用一个带有rightid=%any的conn在手机上使用虚拟键盘发送
> [...](#)
> On Jul 28, 2022, at 23:43, yygyqkhh ***@***.***> wrote: ﻿ Many people use it, so it must be something specific to your configuration. Please share configuration and/or logs ? Sent using a virtual keyboard on a phone … On Jul 28, 2022, at 00:19, yygyqkhh @.***> wrote: ﻿ Hello,Libreswan IKEV2 how to connect multiple clients with multiple certificates? I applied for two certificates with different names and I couldn't connect to the server at the same time. certutil -z <(head -c 1024 /dev/urandom) -S -c "IKEv2 VPN CA" -n "vpnclient" -s "O=IKEv2 VPN,CN=vpnclient" -k rsa -g 4096 -v 120 -d sql:/etc/ipsec.d -t ",," --keyUsage digitalSignature,keyEncipherment --extKeyUsage serverAuth,clientAuth -8 "vpnclient" certutil -z <(head -c 1024 /dev/urandom) -S -c "IKEv2 VPN CA" -n "vpnclient2" -s "O=IKEv2 VPN,CN=vpnclient2" -k rsa -g 4096 -v 120 -d sql:/etc/ipsec.d -t ",," --keyUsage digitalSignature,keyEncipherment --extKeyUsage serverAuth,clientAuth -8 "vpnclient2" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. Thank you for your reply. I first use PC to link to the server, and then I can't link with my iPhone. Here is the code. conn ikev2 left=%defaultroute leftcert=x.x.x.x leftsendcert=always leftsubnet=0.0.0.0/0 leftrsasigkey=%cert right=%any rightca=%same rightrsasigkey=%cert narrowing=yes dpddelay=30 dpdtimeout=120 dpdaction=clear auto=add ikev2=insist rekey=no pfs=no ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1 phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2 ikelifetime=24h salifetime=24h encapsulation=yes leftid=x.yx.z.a modecfgdns=x.x.x.x conn vpnclient rightid="CN=vpnclient" also=ikev2 conn vpnclient2 rightid="CN=vpnclient2" also=ikev2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

Thank you so much for solving the problem perfectly. thank you.

**Comment by yygyqkhh** [comment]
> 尝试使用一个带有rightid=%any的conn在手机上使用虚拟键盘发送
> [...](#)
> On Jul 28, 2022, at 23:43, yygyqkhh ***@***.***> wrote: ﻿ Many people use it, so it must be something specific to your configuration. Please share configuration and/or logs ? Sent using a virtual keyboard on a phone … On Jul 28, 2022, at 00:19, yygyqkhh @.***> wrote: ﻿ Hello,Libreswan IKEV2 how to connect multiple clients with multiple certificates? I applied for two certificates with different names and I couldn't connect to the server at the same time. certutil -z <(head -c 1024 /dev/urandom) -S -c "IKEv2 VPN CA" -n "vpnclient" -s "O=IKEv2 VPN,CN=vpnclient" -k rsa -g 4096 -v 120 -d sql:/etc/ipsec.d -t ",," --keyUsage digitalSignature,keyEncipherment --extKeyUsage serverAuth,clientAuth -8 "vpnclient" certutil -z <(head -c 1024 /dev/urandom) -S -c "IKEv2 VPN CA" -n "vpnclient2" -s "O=IKEv2 VPN,CN=vpnclient2" -k rsa -g 4096 -v 120 -d sql:/etc/ipsec.d -t ",," --keyUsage digitalSignature,keyEncipherment --extKeyUsage serverAuth,clientAuth -8 "vpnclient2" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. Thank you for your reply. I first use PC to link to the server, and then I can't link with my iPhone. Here is the code. conn ikev2 left=%defaultroute leftcert=x.x.x.x leftsendcert=always leftsubnet=0.0.0.0/0 leftrsasigkey=%cert right=%any rightca=%same rightrsasigkey=%cert narrowing=yes dpddelay=30 dpdtimeout=120 dpdaction=clear auto=add ikev2=insist rekey=no pfs=no ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1 phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2 ikelifetime=24h salifetime=24h encapsulation=yes leftid=x.yx.z.a modecfgdns=x.x.x.x conn vpnclient rightid="CN=vpnclient" also=ikev2 conn vpnclient2 rightid="CN=vpnclient2" also=ikev2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

hello，Try your method, two clients are linked at the same time, but you will find that the previous link has lost the network

**Comment by letoams** [comment]
On Jul 29, 2022, at 21:46, yygyqkhh ***@***.***> wrote:
> 
> ﻿
> hello，Try your method, two clients are linked at the same time, but you will find that the previous link has lost the networ
> 

Are you sure the two clients use a different certificate ? If so, please reproduce the issue and when the second client is connected capture the output of “ip xfrm policy” and “ip xfrm state” and “ipsec version”

**Comment by yygyqkhh** [comment]
> conn ikev2
> left=%defaultroute
> leftcert=x.x.x
> leftsendcert=always
> leftsubnet=0.0.0.0/0
> leftrsasigkey=%cert
> right=%any
> rightca=%same
> rightrsasigkey=%cert
> narrowing=yes
> dpddelay=30
> dpdtimeout=120
> dpdaction=clear
> auto=add
> ikev2=insist
> rekey=no
> pfs=no
> ike=aes256-sha2，aes128-sha2，aes256-sha1，aes128-sha1
> phase2alg=aes_gcm-null，aes128-sha1，aes256-sha1，aes128-sha2，aes256-sha2
> ikelifetime=24h
> salifetime=24h
> encapsulation=yes
> leftid=x.yx.z.a
> modecfgdns=x.x.x.x

I'm sure I used two different client certificates to link, but if the PC side has already linked, the iPhone side will not be able to link.

conn ikev2-cp
left=%defaultroute
leftcert=x.x.x
leftsendcert=always
leftsubnet=0.0.0.0/0
leftrsasigkey=%cert
right=%any
rightid=%any
rightca=%same
rightrsasigkey=%cert
narrowing=yes
dpddelay=30
dpdtimeout=120
dpdaction=clear
auto=add
ikev2=insist
rekey=no
pfs=no
ike=aes256-sha2，aes128-sha2，aes256-sha1，aes128-sha1
phase2alg=aes_gcm-null，aes128-sha1，aes256-sha1，aes128-sha2，aes256-sha2
ikelifetime=24h
salifetime=24h
encapsulation=yes
leftid=x.yx.z.a
modecfgdns=x.x.x.x

**Comment by yygyqkhh** [comment]
> 2022年7月29日21：46，yygyqkhh ***@***.***>写道：你好，试试你的方法，两个客户端同时链接，但你会发现之前的链接已经丢失了networ
> 是否确定两个客户端使用不同的证书？如果是这样，请重现问题，并在连接第二个客户端时捕获“ip xfrm策略”和“ip xfrm状态”和“ipsec版本”的输出

I'm sure I used two different client certificates to link, but if the PC side has already linked, the iPhone side will not be able to link.
Ipsec version 4.7

conn ikev2-cp
left=%defaultroute
leftcert=x.x.x
leftsendcert=always
leftsubnet=0.0.0.0/0
leftrsasigkey=%cert
right=%any
rightid=%any
rightca=%same
rightrsasigkey=%cert
narrowing=yes
dpddelay=30
dpdtimeout=120
dpdaction=clear
auto=add
ikev2=insist
rekey=no
pfs=no
ike=aes256-sha2，aes128-sha2，aes256-sha1，aes128-sha1
phase2alg=aes_gcm-null，aes128-sha1，aes256-sha1，aes128-sha2，aes256-sha2
ikelifetime=24h
salifetime=24h
encapsulation=yes
leftid=x.yx.z.a
modecfgdns=x.x.x.x
