### ISSUE TITLE
libreswan refuse to accept conns after upgrade to 4.7

### ISSUE THREAD

**Issue by MyOzCam** [libreswan/libreswan#810]
Using Fedora 35, libreswan refuse to accept conns after upgrade to libreswan-4.7-1.fc35.armv7hl. Sound like certificate problem but the setting worked when 4.6

Suspicious log:
Jul 30 15:46:11 localhost pluto[5827]: "ikev2-cp"[1] <masked host IP> #1: **_ignoring CERTREQ payload that is not ASN1: content is not binary ASN.1_**
Jul 30 15:46:11 localhost pluto[5827]: "ikev2-cp"[1] <masked host IP>  #1: reloaded private key matching left certificate "masked certificate"
Jul 30 15:46:11 localhost pluto[5827]: "ikev2-cp"[1] <masked host IP>  #1: switched to "ikev2-cp"[2] <masked host IP> 
Jul 30 15:46:11 localhost pluto[5827]: "ikev2-cp"[1] <masked host IP> : deleting connection instance with peer <masked host IP>  {isakmp=#0/ipsec=#0}
Jul 30 15:46:11 localhost pluto[5827]: "ikev2-cp"[2] <masked host IP>  #1: responder established IKE SA; authenticated using PKCS#1 1.5 RSA with SHA1 and peer certificate "masked certificate" issued by CA "CN=masked CN, O=masked O, C=masked C, E=masked email address"
Jul 30 15:46:11 localhost pluto[5827]: "ikev2-cp"[2] <masked host IP>  #1: _**NSS: SGN_Digest(SHA-1) function failed: SEC_ERROR_SIGNATURE_ALGORITHM_DISABLED: Could not create or verify a signature using a signature algorithm that is disabled because it is not secure.**_

Any suggest of direction to debug this problem?

**Comment by cagney** [comment]
> Using Fedora 35, libreswan refuse to accept conns after upgrade to libreswan-4.7-1.fc35.armv7hl. Sound like certificate problem but the setting worked when 4.6
> 
> Suspicious log: Jul 30 15:46:11 localhost pluto[5827]: "ikev2-cp"[1] #1: **_ignoring CERTREQ payload that is not ASN1: content is not binary ASN.1

This isn't new https://github.com/libreswan/libreswan/issues/653 

> NSS: SGN_Digest(SHA-1) function failed: SEC_ERROR_SIGNATURE_ALGORITHM_DISABLED: Could not create or verify a signature using a signature algorithm that is disabled because it is not secure.**_
> 
> Any suggest of direction to debug this problem?

How does the private key compare against the m/c's crypto policy?

This likely connected to:
* IKEv2: fix interop with Android 12 + certificates [Andrew]
which overhauled cert verification et.al.

4.6 was using the low level:
```
                SECStatus s = PK11_SignWithMechanism(pks->private_key, CKM_RSA_PKCS_PSS,
                                                     &mech_item, &signature, &data);
```
where as 4.7 uses the high level:
```
        SECStatus s = SGN_Digest(pks->private_key,
                                 hash_algo->nss.oid_tag,
                                 &signature_result, &digest);
```
which DTRT and honours the machine's crypto policy.

**Comment by MyOzCam** [comment]
Thanks for suggesting the direction.

Found temporary fix by adding SHA1 support to system crypto-policy, by:
`update-crypto-policy --set DEFAULT:SHA1`
`reboot`

But in fact the certificate signature algorithm are SHA-256 with RSA Encryption. Don't understand why it was rejected by the SHA1 disallow rule.
<img width="504" alt="Screenshot 2022-07-30 at 9 26 44 PM" src="https://user-images.githubusercontent.com/26063869/181916440-ca5726cb-c351-49c4-ac11-e662c11edce7.png">

**Comment by cagney** [comment]
> responder established IKE SA; authenticated using PKCS#1 1.5 RSA with SHA1 

To clarify one thing, can you confirm that the initiator generated a SHA-1 hash and then signed it using a SHA-1 RSA pubkey?
If it didn't, and it's libreswan, we've another bug.

I believe the pubkey_signer_pkcs1_1_5_rsa code is being used.  Looking at
https://datatracker.ietf.org/doc/html/rfc7427 it's the legacy RSA 1.5 case.

At least this means the initiator is using DIGSIG.

> Don't understand why it was rejected by the SHA1 disallow rule.

The code is using the RSA SHA-2 key to sign a SHA-1 proof-of-identity hash.

The decision is probably caused by:
```
                 * Prefer the HASH and SIGNER algorithms saved when
                 * authenticating the initiator (assuming the
                 * initiator was authenticated using DIGSIG).
                 *
                 * For HASH, both ends negotiated acceptable hash
                 * algorithms during IKE_SA_INIT.  For SIGNER, the
                 * algorithm also needs to be consistent with local
                 * AUTHBY.
                 *
                 * Save the decision so it is available when emitting
                 * the computed hash.
```
(it's the android-be-happy heuristic)

You can force things with either:

    authby=rsa-sha2

on both ends.  Or you could try playing with:

    {left,right}auth=rsa

it looks like we'll need to sharpen the heuristic a bit.

This overlaps #645.

**Comment by MyOzCam** [comment]
Thanks. Looking into the certificate and found the public key is RSAES-PKCS1-v1_5 encryption scheme indeed. 
<img width="320" alt="Screenshot 2022-07-31 at 7 32 52 AM" src="https://user-images.githubusercontent.com/26063869/182003522-421c23b7-af9e-482b-b347-8c325b22daf9.png">

**Comment by letoams** [comment]
On Jul 30, 2022, at 19:34, MyOzCam ***@***.***> wrote:
> 
> ﻿Thanks. Looking into the certificate and found the public key is RSAES-PKCS1-v1_5 encryption scheme indeed.

So the fedora system defaults on the newer fedora to disallow sha1 is what caused your issue, not a libreswan bug.

Paul

**Comment by cagney** [comment]
I take back what I said about "PKCS#1 1.5 RSA" indicating DIGSIG+RSA-1.5, it could also indicate old RSA.

- it should be clear when new style DIGSIG is being used #811 #637

> So the fedora system defaults on the newer fedora to disallow sha1 is what caused your issue, not a libreswan bug.

Fedora didn't change.
I don't believe the keys changed?
Libreswan 4.7 was changed from PK11*() to SGN_Digest() which rejects signing of SHA-1 (proof-of-identity) hash when the private key says to use SHA-2.  The verify path wasn't changed.

- the verify path should be changed to use SGN*() #812
- libreswan should be noticing that the private key is sha-2 and respond accordingly #645 (here that might mean bailing earlier 'cos initiator wants legacy, which we don't support for sha-2)

Finally the configuration needs work:
- the PKCS 1.5 keys should all use SHA-1
- things should switch to RSAPSS or EC

**Comment by MyOzCam** [comment]
> I don't believe the keys changed?

I didn't change any key or the nss key/cert repo.

> the verify path should be changed to use SGN*() https://github.com/libreswan/libreswan/issues/812
> libreswan should be noticing that the private key is sha-2 and respond accordingly https://github.com/libreswan/libreswan/issues/645 (here that might mean bailing earlier 'cos initiator wants legacy, which we don't support for sha-2)

Does it mean the current code does not verify the client certificate with PKCS#1 1.5 and above temporary fix that add SHA1 support to crypto-policy will add risk to the system or Libreswan will accept unauthorized connection?

**Comment by cagney** [comment]
The incoming key is verified.  The verify code could just do with an update.

> Should we raise the PKCS#1 1.5 support (rsasig) to not use only SHA1 but other hashing such as sha[256-512]WithRSAEncryption (OID:1.2.840.113549.1.1.[11-13])?

I believe this is covered.

See https://datatracker.ietf.org/doc/html/rfc8247#section-3.2

SHA-1 can be used with the old RSA Digital Signature Payload per https://datatracker.ietf.org/doc/html/rfc7296#section-3.8 it's full of weasel words about how the two ends magically know the hash being used; reality is it is only ever sha-1

SHA-2 should be used with the new Digital Signature Payload.  It should really be combined with RSASSA-PSS but RSA"1.5" is allowed.

**Comment by MyOzCam** [comment]
I try using authby=rsa-sha2 to enforce not SHA1. Unfortunately 

`Aug 01 16:17:44 localhost pluto[14558]: | verifying auth payload, remote sent v2AUTH=RSA we want auth=rsasig`
`Aug 01 16:17:44 localhost pluto[14558]: | skipping sighash check as PKCS#1 1.5 RSA + SHA1`
`Aug 01 16:17:44 localhost pluto[14558]: "ikev2-cp"[2] <client ip> #1: authentication failed: peer authentication requires policy RSASIG_v1_5`

Is now left or right still enforcing rsasig? If right side then sound like Apple IOS/MacOS native VPN client with IKEv2 default to use **RSA authentication with SHA-1**.

**Comment by cagney** [comment]
The place to start is with the apple generated key.  It should at least use sha2 matching the server's private key.
Currently the apple device is providing a weak proof-identity when compared to what the server wants to send back.
If this is changed things should work.

Looking at {left,right}auth= it's only possible to force an encryption family.  Not a specific auth.
