### ISSUE TITLE
dodgy double accounting of IPCOMP traffic

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#824]
```
                if (st->st_esp.present) {
                        pstats_ipsec_in_bytes += st->st_esp.our_bytes;
                        pstats_ipsec_out_bytes += st->st_esp.peer_bytes;
                if (st->st_ah.present) {
                        pstats_ipsec_in_bytes += st->st_ah.peer_bytes;
                        pstats_ipsec_out_bytes += st->st_ah.our_bytes;
                if (st->st_ipcomp.present) {
                        pstats_ipsec_in_bytes += st->st_ipcomp.peer_bytes;
                        pstats_ipsec_out_bytes += st->st_ipcomp.our_bytes;
```
- it's been counted both for IPCOMP and either of ESP/AH - pick one
- it's flip/flopping what's in and what's out

**Comment by letoams** [comment]
Remember that ipcomp is it’s own SA with traffic. If a packet got compressed smaller it will be ipcomp traffic. If it turned out compression made it bigger, the original ESP packet is sent. So we likely should add the two up since we provide one counter for our users and not separate counters ?

Sent using a virtual keyboard on a phone

**Comment by cagney** [comment]
Right there are two numbers:

1. bytes passing between user-land and the kernel - IPCOMP counter (?)
2. bytes on the wire - ESP/AH counter

Normally they are roughly the same, but with IPCOMP the values can be different.  Adding them doesn't provide anything meaningful.

However, based on the thread [[Swan-dev] Ipcomp and get_sa_info()](https://lists.libreswan.org/pipermail/swan-dev/2022-March/004504.html) we're likely adding zero to the ESP/AH counter - i.e., just printing 2.
