### ISSUE TITLE
Broken .spec file

### ISSUE THREAD

**Issue by davidarnold** [libreswan/libreswan#83]
The spec files just had a bug introduced that causes the build to fail.

```
%global USE_SECCOMP false
```

`false` isn't false.  I think the sketchy use of `true` earlier in the file misleads one to think that there are keywords with those names.  From my experience, they both act as truthy strings.

I switched to this and got the build to succeed:

```
%global USE_SECCOMP 0
```

**Comment by letoams** [comment]
Thanks for spotting the error. I've just changed all the true/false into 1/0
