### ISSUE TITLE
How to determine SK_ei SK_er SK_ai SK_ar from log when plutodebug=private

### ISSUE THREAD

**Issue by MyOzCam** [libreswan/libreswan#830]
I am trying to use Wireshark to debug the IKE_SA_INIT and IKE_AUTH traffic. Need to provide SPI and SK_ to IKEv2 decryption table.

I used plutodebug=private and generate below:

```
| ikev2 I 0xba1143d176e1557b 0xb62a3c712fd1f26a sha256:0x297cbd53dfeca688aa01f6a3b08c7e0766866459bbd68f8b3493d97797624b0b aes256:0x496e8069424209b3029b6d5e4a2b917e9623135a9982ab14677b83477164c35b
| ikev2 R 0xba1143d176e1557b 0xb62a3c712fd1f26a sha256:0x57c5a2e78361c18206ddbbda12998ea77cb1c0824663cc5f06d273bafc23fd6f aes256:0x3f1829726d10f11ba711cc2b572bdc97d871fa83a8bc9ef50298c506b3a52d9b
"ikev2-cp"[8] <CLIENT IP> #8: proposal 1:ESP=AES_CBC_256-HMAC_SHA2_256_128-DISABLED SPI=0c8a8d6d chosen from remote proposals 1:ESP:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_256_128;ESN=DISABLED[first-match]
| our  keymat
|   87 ba a5 46  69 74 1d d0  98 09 72 d0  31 6e 56 66   
|   38 56 18 dd  4e d6 1b 31  17 15 83 07  cf 42 39 bd   
|   06 a5 dd ae  fb f2 a6 4d  40 36 44 d5  11 3d fd a7   
|   f9 49 24 6a  0e bb 1d 41  d5 f8 75 98  fd 67 60 76   
| peer keymat
|   21 72 79 4e  2d 12 28 b7  5e 90 eb 1c  e7 80 e2 4d   
|   81 ac 81 e5  7b 99 6f db  61 bb 4e 8c  95 98 38 64   
|   4c 08 52 16  ef 1d 92 88  27 0f 1b 2e  ac 8f 01 cc   
|   76 7f 9b 6d  4d 3e 63 66  38 44 bc 2b  d0 17 4a 9e   
| ESP enckey:
|   21 72 79 4e  2d 12 28 b7  5e 90 eb 1c  e7 80 e2 4d   
|   81 ac 81 35  7b 99 6f db  61 bb 4e 8c  95 98 38 64   
| ESP authkey:
|   4c 08 52 26  ef 1d 92 88  27 0f 1b 2e  ac 8f 01 cc   
|   76 7f 9b 8d  4d 3e 63 66  38 44 bc 2b  d0 17 4a 9e   
| ESP enckey:
|   87 ba a5 46  19 74 1d d0  98 09 72 d0  31 6e 56 66   
|   38 56 18 dd  4e d6 1b 31  17 15 83 07  cf 41 39 bd   
| ESP authkey:
|   06 a5 dd ae  eb f2 a6 4d  40 36 44 d5  11 3d fd a7   
|   f9 49 24 6a  0e bb 1d 41  d5 f8 75 98  fd 67 60 76   
```

I can only sure:
Initiator SPI = ba1143d176e1557b 
Responder SPI = b62a3c712fd1f26a

But not sure SK_ is referring to the SHA256/AES256 value or ESP enckey/authkey value.

I tried both but still not able to decrypt the payload in IKE_AUTH packet
<img width="1255" alt="Screenshot 2022-08-19 at 2 29 11 PM" src="https://user-images.githubusercontent.com/26063869/185557157-828e5a18-3188-4963-b082-2fa47313aac4.png">

**Comment by letoams** [comment]
On Thu, 18 Aug 2022, MyOzCam wrote:

> I am trying to use Wireshark to debug the IKE_SA_INIT and IKE_AUTH traffic. Need to provide IPI and SK_ to IKEv2 decryption table.

Note it is far better to use plutodebug=all,tmi to get all logging. This
will log all decrypted bytes, what payloads these are and their
contents, etc. wireshark is not a good tool for this, as it also doesn't
know about all payloads and its values and as you see it is harder to
use.

Paul

**Comment by cagney** [comment]
It's the:
```
| ikev2 I IKE-SPI(initiator) IKE-SPI(responder) AUTHALG:KEY ENCRALG:KEY
```
line,  see DBG_tcpdump_ike_sa_keys().  The ESP... dump is for the ESP messages.

One thing to check is that keys are being assigned to the correct message flow:
- I is for messages from the initiator to the responder
- R is for messages from the responder to the initiator
but wireguard is likely showing things from the POV of the current machine.
