### ISSUE TITLE
duplicate public key

### ISSUE THREAD

**Issue by AnatoliChe** [libreswan/libreswan#833]
Hi! 
I noticed strange situation
conf1
conn %default
    rightid=@peer0.local
    rightrsasigkey=key0

conn test1
   left=ip
   leftid=id1

conn test2
   left=ip2
   leftid=id2
I have got error:
ipsec auto --add test1
while loading 'test1': duplicate public key
while loading 'test2': duplicate public key
duplicate public key
addconn, in config '/etc/ipsec.conf', duplicate public key
duplicate public key

conn test1 did not load properly

but with conf:

conn %default
    rightid=@peer0.local

conn test1
   left=ip
   leftid=id1
   rightrsasigkey=key0

conn test2
   left=ip2
   leftid=id2
   rightrsasigkey=key0

everything is ok.

Should I dublicate key for each conn?

**Comment by paulwouters** [comment]
reproduced in test case testing/pluto/libipsecconf-11-default-key

workaround:  place the rightrsasigkey= line into both test1 and test2 conns.

**Comment by cagney** [comment]
It's nice when deleting code fixes bugs.
