### ISSUE TITLE
__builtin_memcpy' specified bound between 18446744073709551576 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]

### ISSUE THREAD

**Issue by paulwouters** [libreswan/libreswan#836]
-c /builddir/build/BUILD/libreswan-4.7/testing/programs/hunkcheck/hunkcheck.c
cd ../../../OBJ.linux.x86_64.buildvm-x86-24/testing/programs/hunkcheck && gcc -DTimeZoneOffset=timezone -pthread -std=gnu99 -g -Werror -Wno-missing-field-initializers -Wno-maybe-uninitialized -Wall -Wextra -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wmissing-declarations -Wredundant-decls -Wnested-externs -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fstack-protector-all -fno-strict-aliasing -fPIE -DPIE -DNSS_IPSEC_PROFILE -DXFRM_LIFETIME_DEFAULT=30 -DUSE_IKEv1 -DKERNEL_XFRM -DUSE_XFRM_INTERFACE -DUSE_DNSSEC -DDEFAULT_DNSSEC_ROOTKEY_FILE=\""/var/lib/unbound/root.key"\" -DHAVE_LABELED_IPSEC -DHAVE_SECCOMP -DLIBCURL -DUSE_LINUX_AUDIT -DUSE_SYSTEMD_WATCHDOG -DLIBLDAP -DHAVE_NM -DUSE_PAM_AUTH -DUSE_3DES -DUSE_AES -DUSE_CAMELLIA -DUSE_CHACHA -DUSE_DH31 -DUSE_MD5 -DUSE_SHA1 -DUSE_SHA2 -DUSE_PRF_AES_XCBC -DUSE_NSS_KDF -DDEFAULT_RUNDIR=\"/run/pluto\" -DIPSEC_CONF=\"/etc/ipsec.conf\" -DIPSEC_CONFDDIR=\"/etc/ipsec.d\" -DIPSEC_NSSDIR=\"/var/lib/ipsec/nss\" -DIPSEC_CONFDIR=\"/etc\" -DIPSEC_EXECDIR=\"/usr/libexec/ipsec\" -DIPSEC_SBINDIR=\"/usr/sbin\" -DIPSEC_VARDIR=\"/var\" -DPOLICYGROUPSDIR=\"/etc/ipsec.d/policies\" -DIPSEC_SECRETS_FILE=\"/etc/ipsec.secrets\" -DFORCE_PR_ASSERT -DUSE_FORK=1 -DUSE_VFORK=0 -DUSE_DAEMON=0 -DUSE_PTHREAD_SETSCHEDPRIO=1 -DGCC_LINT -DHAVE_LIBCAP_NG -I. -I../../../OBJ.linux.x86_64.buildvm-x86-24/testing/programs/hunkcheck -I../../../include -I/usr/include/nss3 -I/usr/include/nspr4  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -o hunkcheck hunkcheck.o /builddir/build/BUILD/libreswan-4.7/OBJ.linux.x86_64.buildvm-x86-24/lib/libswan/libswan.a /builddir/build/BUILD/libreswan-4.7/OBJ.linux.x86_64.buildvm-x86-24/lib/liblswtool/liblswtool.a /builddir/build/BUILD/libreswan-4.7/OBJ.linux.x86_64.buildvm-x86-24/lib/libswan/libswan.a -Wl,--as-needed -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now   -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes
In function 'memcpy',
    inlined from 'clone_bytes' at /builddir/build/BUILD/libreswan-4.7/lib/libswan/alloc.c:241:3,
    inlined from 'clone_bytes_as_chunk' at /builddir/build/BUILD/libreswan-4.7/lib/libswan/chunk.c:55:9,
    inlined from 'check_shunk_clone' at /builddir/build/BUILD/libreswan-4.7/testing/programs/hunkcheck/hunkcheck.c:330:15,
    inlined from 'main' at /builddir/build/BUILD/libreswan-4.7/testing/programs/hunkcheck/hunkcheck.c:840:2:
/usr/include/bits/string_fortified.h:29:10: error: '__builtin_memcpy' specified bound between 18446744073709551576 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ^
lto1: all warnings being treated as errors
make[5]: *** [/tmp/ccyUGM26.mk:2: /tmp/cctiHXdY.ltrans0.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[4]: *** [../../../mk/program.mk:65: hunkcheck] Error 1
make[3]: *** [../../../mk/targets.mk:82: all] Error 2
make[2]: *** [../../mk/targets.mk:82: recursive-all] Error 2
make[1]: *** [../mk/targets.mk:82: recursive-all] Error 2
make: *** [/builddir/build/BUILD/libreswan-4.7/mk/targets.mk:82: recursive-all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.wIVuq7 (%build)
RPM build errors:

**Comment by paulwouters** [comment]
workaround: WERROR_CFLAGS="-Werror -Wno-stringop-overflow"

**Comment by paulwouters** [comment]
This only happens with -flto enabled

**Comment by cagney** [comment]
reproduce with:
```
$ ./kvm sh fedora
# cd /source
# make -j5 CFLAGS='-flto'
```

**Comment by cagney** [comment]
```
   312  static void check_shunk_clone(void)
   313  {
   314          static const struct test {
   315                  const char *s;
   316          } tests[] = {
   317                  /*
   318                   * Like strings, NULL and EMPTY ("") shunks are
   319                   * considered different.
   320                   */
   321                  { NULL, },
   322                  { "", },
   323                  { "a", },
   324          };
   325  
   326          for (size_t ti = 0; ti < elemsof(tests); ti++) {
   327                  const struct test *t = &tests[ti];
   328                  PRINT_S(stdout, "");
   329                  shunk_t s = shunk1(t->s);
   330   /**/           chunk_t c = clone_hunk(s, "c");
```
shunk1(NULL) should be ok, returning, {0, NULL}?
```
    48  chunk_t clone_bytes_as_chunk(const void *bytes, size_t sizeof_bytes, const char *name)
    49  {
    50          /*
    51           * orig=NULL; size=0 -> NULL
    52           * orig=PTR; size=0 -> new PTR (for instance a shunk with PTR = "")
    53           * orig=PTR; size>0 -> new PTR
    54           */
    55          return chunk2(clone_bytes(bytes, sizeof_bytes, name), sizeof_bytes);
    56  }
```
```
   232  void *clone_bytes(const void *orig, size_t size, const char *name)
   233  {
   234          void *p;
   235          if (orig == NULL) {
   236                  passert(size == 0);
   237                  p = NULL;
   238          } else {
   239                  /* even when size is 0, allocate something */
   240                  p = uninitialized_malloc(size, name);
   241  /***/            memcpy(p, orig, size);
   242          }
   243          return p;
   244  }
```

**Comment by cagney** [comment]
So:
```
    32  shunk_t shunk1(const char *ptr)
    33  {
    34          if (ptr == NULL) {
    35                  return null_shunk;
    36          } else {
    37                  return shunk2(ptr, strlen(ptr));
    38          }
    39  }
```
leads to:
```
shunk1(NULL) -> {0,NULL}
shunk1("") -> {0, ""}
shunk1("a") -> {1, "a"}
```
presumably the compiler's got hold of one of the first two and thinks it is passing 0-1 memcpy()

**Comment by cagney** [comment]
I wonder if, to DHR's point, the optimizer is seeing this memcpy():
```
chunk_t clone_bytes_bytes_as_chunk(const void *lhs_ptr, size_t lhs_size,
				   const void *rhs_ptr, size_t rhs_size,
				   const char *name)
{
	size_t size = lhs_size + rhs_size;
	uint8_t *bytes = alloc_things(uint8_t, size, name);
	memcpy(bytes, lhs_ptr, lhs_size);
	memcpy(bytes + lhs_size, rhs_ptr, rhs_size);
	return chunk2(bytes, size);
}
```
and inferring from that that the pointer isn't NULL; even though the optimizer has created a path where it is set to NULL.
