### ISSUE TITLE
Failed to find our PreShared Key libreswan

### ISSUE THREAD

**Issue by elijah0kello** [libreswan/libreswan#838]
I have a configuration for libreswan. I have an `ipsec.conf` and an `ipsec.secrets`. 

When I run `sudo ipsec auto --up conname`

This is what I get

```terminal
181 "conname" #9: initiating IKEv2 IKE SA
181 "conname" #9: STATE_PARENT_I1: sent v2I1, expected v2R1
003 "conname" #9: No matching PSK found for connection: conname
003 "conname" #9: Failed to find our PreShared Key
002 "conname" #10: deleting other state #10 (STATE_CHILDSA_DEL) aged 0.000s and NOT sending notification
036 "conname" #9: encountered fatal error in state STATE_PARENT_I2

```

Please help me figure out what I am doing wrong.

`/etc/ipsec.conf`

```conf
conn conname
    auto=start
    left=%defaultroute
    right=x.x.x.x
    secretsfile=/etc/ipsec.secrets
    leftsourceip=x.x.x.x
    type=tunnel
    authby=secret
    keyexchange=ike
    ike=aes256-sha1;modp1536
    ikelifetime=8h
    esp=aes256-sha1-dh5
    lifetime=1h
    keyingtries=%forever
    leftsubnet=x.x.0.0/x
    rightsubnet=x.x.x.x/x
    dpddelay=100s
    dpdtimeout=30s
    dpdaction=restart
```

`/etc/ipsec.secrets`

```conf
# This file holds shared secrets (PSK) and XAUTH user passwords used for
# authentication.  See pluto(8) manpage or the libreswan website.

# Unlike older openswan, this file does NOT contain any X.509 related
# information such as private key :RSA statements as these now reside
# in the NSS database. See:
#
# https://libreswan.org/wiki/Using_NSS_with_libreswan
# https://libreswan.org/wiki/Migrating_from_Openswan
#
# The preferred method for adding secrets is to create a new file in
# the /etc/ipsec.d/ directory, so it will be included via the include
# line below

x.x.x.x x.x.x.x : PSK "xxxxxxxxxxxxxx"

#include /etc/ipsec.d/*.secrets

```

Please advise accordingly

**Comment by letoams** [comment]
On Thu, 1 Sep 2022, Elijah Okello wrote:

> I have a configuration for libreswan. I have an ipsec.conf and an ipsec.secrets.

> 003 "conname" #9: No matching PSK found for connection: conname
> 003 "conname" #9: Failed to find our PreShared Key

> conn conname
>     auto=start
>     left=%defaultroute
>     right=x.x.x.x
>     secretsfile=/etc/ipsec.secrets
>     leftsourceip=x.x.x.x
>     type=tunnel
>     authby=secret
>     keyexchange=ike
>     ike=aes256-sha1;modp1536
>     ikelifetime=8h
>     esp=aes256-sha1-dh5
>     lifetime=1h
>     keyingtries=%forever
>     leftsubnet=x.x.0.0/x
>     rightsubnet=x.x.x.x/x
>     dpddelay=100s
>     dpdtimeout=30s
>     dpdaction=restart

your left=%defaultroute is a "variable IP address", so you cannot have
it as x.x.x.x in your ipsec.secrets. If it is really static AND it is
not a pre-NAT IP, then it should work as you have it. But since it does
not work, I assume your native IP is not listed in your ipsec.secrets
entry and you probably list the elastic/post-NAT IP there?

You can also instead make up an idea (and tell the remote to use that
id). Eg, if you make "STRING" your idea, specify a ***@***.***

> /etc/ipsec.secrets
> 
> x.x.x.x x.x.x.x : PSK "xxxxxxxxxxxxxx"

Then use:

   @STRING x.x.x.x: PSK "xxxxxxxxxxxxxx"

**Comment by elijah0kello** [comment]
Okay sorry for the x.x.x.x. I just removed the real ip and put that.  I have done what you have advised .

I had actually done exactly what you said.  I had put the elastic/post-NAT IP instead of the native IP of the machine.

I run the same command again and this time I get no output. Is this normal?

`sudo ipsec auto --up conname`

How do I verify that the connection was successful and it is up.

I tried to ping one of the private ips in the other subnet and it was not successful.

**Comment by letoams** [comment]
On Sep 1, 2022, at 16:13, Elijah Okello ***@***.***> wrote:
> 
> ﻿
> I run the same command again and this time I get no output. Is this normal?
> 
> sudo ipsec auto --up conname
> 
> How do I verify that the connection was successful and it is up.
> 

Can you show the output of: ipsec auto —add conname ? And then run the —up?


ipsec trafficstatus shows you if the tunnel is up.

**Comment by elijah0kello** [comment]
```terminal
002 "conname": terminating SAs using this connection
002 "conname" #1: deleting state (STATE_PARENT_I2) aged 55.206s and NOT sending notification
002 added connection description "conname"
```

That is the output from  `sudo ipsec auto —add conname`

`sudo ipsec trafficstatus` Displays nothing

**Comment by elijah0kello** [comment]
```terminal
181 "conname" #3: initiating IKEv2 IKE SA
181 "conname" #3: STATE_PARENT_I1: sent v2I1, expected v2R1
182 "conname" #4: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=AES_CBC_256 integ=HMAC_SHA1_96 prf=HMAC_SHA1 group=MODP1536}
003 "conname" #4: dropping unexpected ISAKMP_v2_IKE_AUTH message containing v2N_NO_PROPOSAL_CHOSEN notification; message payloads: SK; encrypted payloads: IDr,AUTH,N,V; unexpected payloads: IDr,AUTH
036 "conname" #4: encountered fatal error in state STATE_PARENT_I2
```
I run `sudo ipsec auto --up gtbank` after running `sudo ipsec auto —add conname`  and that is the output

**Comment by letoams** [comment]
On Thu, 1 Sep 2022, Elijah Okello wrote:

> 181 "conname" #3: initiating IKEv2 IKE SA
> 181 "conname" #3: STATE_PARENT_I1: sent v2I1, expected v2R1
> 182 "conname" #4: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=AES_CBC_256 integ=HMAC_SHA1_96 prf=HMAC
> _SHA1 group=MODP1536}
> 003 "conname" #4: dropping unexpected ISAKMP_v2_IKE_AUTH message containing v2N_NO_PROPOSAL_CHOSEN notification; messa
> ge payloads: SK; encrypted payloads: IDr,AUTH,N,V; unexpected payloads: IDr,AUTH

The other end did not like your ike= or esp= (most likely ike=)

You need to agree with the other end about your IKE and IPsec
algorithms. Whatever is in the default set for libreswan was
not liked by the remote peer.

Paul

**Comment by elijah0kello** [comment]
Oh okay. That makes sense now. Thanks. Let me harmonize the configuration and post my update

**Comment by elijah0kello** [comment]
Hello Paul,

The other end claims that the configs are right and there's nothing to change. I am trying to understand the error message. This particular line

```terminal
003 "conname" #340: dropping unexpected ISAKMP_v2_IKE_AUTH message containing v2N_NO_PROPOSAL_CHOSEN notification; message payloads: SK; encrypted payloads: IDr,AUTH,N,V; unexpected payloads: IDr,AUTH
```
What is ` IDr` and `AUTH`. ? Is there a way I can set them as expected payloads

Please note that I am connecting to a CISCO Asa remote peer. Are there any specific ways that are required to connect to a CISCO Asa end?

Please advise accordingly. Thank you

**Comment by elijah0kello** [comment]
Hello Paul,

The other end claims that the configs are right and there's nothing to change. I am trying to understand the error message. This particular line

```terminal
003 "conname" #340: dropping unexpected ISAKMP_v2_IKE_AUTH message containing v2N_NO_PROPOSAL_CHOSEN notification; message payloads: SK; encrypted payloads: IDr,AUTH,N,V; unexpected payloads: IDr,AUTH
```
What is ` IDr` and `AUTH`. ? Is there a way I can set them as expected payloads

Please note that I am connecting to a CISCO Asa remote peer. Are there any specific ways that are required to connect to a CISCO Asa end?

Please advise accordingly. Thank you

**Comment by letoams** [comment]
On Fri, 2 Sep 2022, Elijah Okello wrote:

> The other end claims that the configs are right and there's nothing to change. I am trying to understand the error
> message. This particular line

If they don't want to change anything, they should tell you the IKE and
ESP parameters they want you to use so you can configure them. Ask
for encryption/authentication or AEAD algorithm, DH group for both IKE
SA (aka Parent SA aka phase1) and Child SA (aka IPsec SA aka phase2)

> 003 "conname" #340: dropping unexpected ISAKMP_v2_IKE_AUTH message containing v2N_NO_PROPOSAL_CHOSEN notification; mes
> sage payloads: SK; encrypted payloads: IDr,AUTH,N,V; unexpected payloads: IDr,AUTH
> 
> What is IDr and AUTH. ? Is there a way I can set them as expected payloads

Ignore all of that. your issue is v2N_NO_PROPOSAL_CHOSEN.

> Please note that I am connecting to a CISCO Asa remote peer. Are there any specific ways that are required to connect
> to a CISCO Asa end?

Should work fine, once you and them agree on the parameters.

**Comment by elijah0kello** [comment]
I got a solution to the problem. Like you had stated the parameters were not matching. It is all fine now
