### ISSUE TITLE
default rsa keys randomly range from [3072-4096] and use rand()

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#843]
Given there's no cryptographic rationale for the range, and it causes:
```
-003 "hostkey" #1: initiator established IKE SA; authenticated peer '4nnn-bit ...
+003 "hostkey" #1: initiator established IKE SA; authenticated peer '3nnn-bit ...
```
it can presumably be narrowed to perhaps 4096..4096+512 say (but I've no rationale for that range either).

(coverity doesn't like `rand()` in `3072 + 16 * (rand() % (1024 / 16))`; might as well abstract it and use NSS, same code happens elsewhere)

**Comment by letoams** [comment]
On Fri, 2 Sep 2022, cagney wrote:

> Given there's no cryptographic rationale for the range, and it causes:

The rationale was "ensure there is no sweet spot for hardware brute
force design". Eg, hardware cannot be made which optimizes for cracking
2048 or 4096 bits. it goes back all the way to John Gilmore, who
famously had a 2047 bit key :)

> -003 "hostkey" #1: initiator established IKE SA; authenticated peer '4nnn-bit ...
> +003 "hostkey" #1: initiator established IKE SA; authenticated peer '3nnn-bit ...
> 
> it can presumably be narrowed to perhaps 4096..4096+512 say (but I've no rationale for that range either).
> 
> (coverity doesn't like rand() in 3072 + 16 * (rand() % (1024 / 16)); might as well abstract it and use NSS, same code
> happens elsewhere)

Sure we can use a more secure random even if it doesnt really matter.

Our test cases never generated keys before using them, so this never
came up before until you added test cases that generate keys on the fly.
I'm sure we can add a sanitizer for "Xnnn-bit"

**Comment by cagney** [comment]
> Sure we can use a more secure random even if it doesnt really matter.

Right.

> Our test cases never generated keys before using them, so this never came up before until you added test cases that generate keys on the fly. I'm sure we can add a sanitizer for "Xnnn-bit"

It's more that I added logging the KEY strength to the log line.
We've a sanitizer for Xnnn-bit, but it leaves the leading digit alone because I'd like to see the magnitude of the key strength.  Here that leading digit keeps changing, grrr.

Perhaps FIPS sets some minimum key size for RSA and we just start from that.

**Comment by cagney** [comment]
14b3caccfcb6460caf9c1aa4a649faa375d61ccf
