### ISSUE TITLE
lifetime checks between whack and libipseconf are different

### ISSUE THREAD

**Issue by paulwouters** [libreswan/libreswan#847]
eg whack for lifetime of 0 or 1:

whack error: "test3" ipsec-lifetime [0] must be greater than rekeymargin*(100+rekeyfuzz)/100 [540*(100+100)/100 = 1080]

vs libipsecconf for 0

002 "paul": IPsec lifetime set to the maximum allowed 86400s

or when set to 1:

002 "paul": rekeymargin (540s) >= salifetime (1s); reducing rekeymargin to 0s seconds

**Comment by cagney** [comment]
also #1170

**Comment by cagney** [comment]
fixed by 9306fa71ebf4d9e8f6a349e05e6dd7bcda68f65e
