### ISSUE TITLE
move struct connection .sa_{ike,ipsec}_* to struct config

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#859]
Probably all of these:
```
        deltatime_t sa_ike_life_seconds;
        deltatime_t sa_ipsec_life_seconds;
        deltatime_t sa_rekey_margin;
        uintmax_t sa_ipsec_max_bytes;
        uintmax_t sa_ipsec_max_packets;
        unsigned long sa_rekey_fuzz;
        unsigned long sa_keying_tries;
```
since they don't change between a connection template and its instances.

**Comment by letoams** [comment]
On Mon, 19 Sep 2022, cagney wrote:

> Probably all of these:
>
>         deltatime_t sa_ike_life_seconds;
>         deltatime_t sa_ipsec_life_seconds;
>         deltatime_t sa_rekey_margin;
>         uintmax_t sa_ipsec_max_bytes;

technically, max bytes could change depending on the algorithm
negotiated. So if it allows 3DES and AES, we could default to
different max values.

> since they don't change between a connection template and its instances.

Only if we were to pick the lowest value of the limits of the weakest cipher?

**Comment by cagney** [comment]
> technically, max bytes could change depending on the algorithm negotiated. So if it allows 3DES and AES, we could default to different max values.

That sounds like two values:

- max-bytes=... in the config file and capped to 2^32
- SA's max-bytes, stored in struct state, and based on the negotiated algorithms + config's max-bytes (if present)

**Comment by cagney** [comment]
ec7639949512109b0b4cae59eb3cf046cc5a29b6
