### ISSUE TITLE
"make install" should not try to fiddle with the running systemd when targeting a $DESTDIR

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#86]
During a debian package build, "make install" gets run targeting a `$DESTDIR`.  however, `initsystems/systemd/Makefile` thinks that running `make install` means it's a good idea to try to talk to the local systemd services.  This isn't a good idea, and the scripts embedded in the makefile don't cope with failures too cleanly either:

```
make[4]: Entering directory '/home/dkg/src/libreswan/libreswan/OBJ.linux.x86_64/initsystems/systemd'
install --mode=0644 ipsec.service /home/dkg/src/libreswan/libreswan/debian/libreswan//lib/systemd/system
Failed to get unit file state for ipsec.service: Connection reset by peer
Failed to retrieve unit: Connection reset by peer
Failed to retrieve unit: Connection reset by peer
/bin/bash: line 0: test: too many arguments
/bin/bash: line 6: test: =: unary operator expected
/bin/bash: line 10: test: =: unary operator expected
make[4]: Leaving directory '/home/dkg/src/libreswan/libreswan/OBJ.linux.x86_64/initsystems/systemd'
```

I think `systemctl is-enabled ipsec.service` and `systemctl is-active ipsec.service` are both failing and producing no output to stdout.

Is there a recommended way to avoid having `make install` try to do anything with the local systemd instance?

**Comment by letoams** [comment]
fixed. When using DESTDIR, it no longer performs the selinux or systemd service checks.
