### ISSUE TITLE
Logging of Child SA traffic is wrong when maxbytes causes rekeying

### ISSUE THREAD

**Issue by bleve** [libreswan/libreswan#865]
Sep 21 12:32:48 tuomo.foobar.fi pluto[193761]: "foo-v6" #192: ESP traffic information: in=3GiB out=3GiB

3GiB was inbound traffic. Outbound was something much smaller, so logging logs inbound on out=.

**Comment by bleve** [comment]
Sep 21 19:30:33 tuomo.foobar.fi pluto[193761]: "foo-v6": Received soft EXPIRE for SPI 0xf0d9a865 bytes 3581234023 packets 2520372 for the newest SA rekey=yes.. Replace this SA
Sep 21 19:30:33 tuomo.foobar.fi pluto[193761]: "foo-v6" #232: initiating rekey to replace Child SA #228
Sep 21 19:30:33 tuomo.foobar.fi pluto[193761]: "foo-v6" #232: sent CREATE_CHILD_SA request to rekey IPsec SA
Sep 21 19:30:33 tuomo.foobar.fi pluto[193761]: "foo-v6" #232: initiator rekeyed Child SA #228 using #231; IPsec tunnel [2001:998:2e:81::f00-2001:998:2e:81::f00:0-65535 0] -> [::-ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff:0-65535 0] {ESP/ESN=>0xbe1b0ba2 <0x789073a0 xfrm=AES_GCM_16_256-NONE-MODP2048 DPD=active}
Sep 21 19:30:34 tuomo.foobar.fi pluto[193761]: "foo-v6" #228: deleting established Child SA using IKE SA #231
Sep 21 19:30:34 tuomo.foobar.fi pluto[193761]: "foo-v6" #228: ESP traffic information: in=3GiB out=3GiB

**Comment by cagney** [comment]
Is trafficstatus just as confused?

**Comment by cagney** [comment]
The EXPIRE log message has been updated to include the direction.
Can you keep an eye on what it reports vs trafficstatus and <ip ...>, and check that the SPI matches things when establishing.

Assuming trafficstatus is still sane, my guess is that the expire code path (either libreswan or kernel) have confused the polarity (which isn't surprising given {in,out} vs {our,peer} through out the code.

**Comment by cagney** [comment]
this should be fixed
