### ISSUE TITLE
Logics for maxbytes is not acceptable

### ISSUE THREAD

**Issue by bleve** [libreswan/libreswan#866]
Now we have logics to rekey on 2^32 packets or 2^32 bytes. That is not acceptable in reality.

With 500Mbit traffic 2^32 bytes causes rekey every minute which is all too often.

Logics should be: rekey when lower of these is 2^32. I don't think there can be more crypto operations than there is packets.

**Comment by cagney** [comment]
On Wed, 21 Sept 2022 at 05:58, bleve ***@***.***> wrote:

> Now we have logics to rekey on 2^32 packets or 2^32 bytes. That is not
> acceptable in reality.
>


> With 500Mbit traffic 2^32 bytes causes rekey every minute which is all too
> often.
>
> Logics should be: rekey when lower of these is 2^32. I don't think there
> can be more crypto operations than there is packets.
>

AES SHA2 with one byte per packet would be 1:1 (it might even be 2:1 but
with different keys but same raw material).  Who knows what FIPS thinks?
Sounds like we should drop the hard cap.

**Comment by letoams** [comment]
On Sep 21, 2022, at 05:58, bleve ***@***.***> wrote:
> 
> ﻿
> Now we have logics to rekey on 2^32 packets or 2^32 bytes. That is not acceptable in reality.
> 
> With 500Mbit traffic 2^32 bytes causes rekey every minute which is all too often.
> 
> Logics should be: rekey when lower of these is 2^32. I don't think there can be more crypto operations than there is packets.
> 

A crypto operation works on 128 bits, so there is a lot of them in 1500 bytes.

**Comment by cagney** [comment]
Using 500MiBit/s:

- 500MiBit/s / 10(rule of thumb from UART days) = 50MiByte/s
- 2^32(4GiBytes) / 50MiByte/s = 81s
- with 20% margin we'd start re-keying with 16s of headroom

Using 2.5GiBit/s ethernet (I don't think there's hardware out there that can do that, but it can't be far away):

- 2.5GiBit/s / 10(rule of thumb from UART days) = 250MiByte/s
- 2^32(4GiBytes) / 250MiByte/s = 16s
- with 20% margin we'd start re-keying ~3s of head room

- 3s, and even 16s, makes a mockery of the default re-transmit and re-key times
- same with using probes to determine traffic; really relies on the kernel
- 50% margin might be a safer default (either there's no traffic and it doesn't matter, or there is and it really really matters)
- a, sigh, knob to adjust the margin (per DHR, in %)
- permit larger values for anyone that doesn't care

**Comment by cagney** [comment]
Some protocols pre-exchange the next key so that there's no panic when the existing key runs out.

**Comment by cagney** [comment]
aes-gcm gets its own bug
