### ISSUE TITLE
vendorid md5 usage should not depend on USE_MD5

### ISSUE THREAD

**Issue by bleve** [libreswan/libreswan#882]
MD5 is not used for actual crypto operation in vendorid code. It should use md5 functions directly and not rely on pluto being compiled with USE_MD5=true. Currently building with USE_MD5=false causes comple to fail.

```
/builddir/build/BUILD/libreswan-4.8/lib/libswan/vendorid.c: In function 'init_vendorid':
/builddir/build/BUILD/libreswan-4.8/lib/libswan/vendorid.c:627:67: error: 'ike_alg_hash_md5' undeclared (first use in this function); did you mean 'ike_alg_hash_sha1'?
  627 |                                                                  &ike_alg_hash_md5,
      |                                                                   ^~~~~~~~~~~~~~~~
      |                                                                   ike_alg_hash_sha1

```

**Comment by cagney** [comment]
- both USE_SHA1 and USE_MD5's have an overloaded meaning - use SHA1 or use SHA1 in negotiated proposals
- vendor id could use hardwired hashes

**Comment by letoams** [comment]
On Mon, 10 Oct 2022, cagney wrote:

>  *  both USE_SHA1 and USE_MD5's have an overloaded meaning - use SHA1 or use SHA1 in negotiated proposals
>  *  vendor id could use hardwired hashes

Yes, it should allow non-cryptographic use (NAT-T, vendorid calculation, etc)

**Comment by cagney** [comment]
I went with the easy option - make MD5 available to Vendor ID - rather than pre-generate all the hashes.
