### ISSUE TITLE
IPsec does not reconnect on ubuntu

### ISSUE THREAD

**Issue by eastwoof13** [libreswan/libreswan#890]
Hi All,
In order to encrypt data in-transit between NetApp NAS and Linux NFS client, we use IPsec in Transport mode.
I test IPsec on two clients : AWS linux and Ubuntu.
I install libreswan on both Linux server :  
-- on aws linux : 
    ipsec --version : Linux Libreswan 3.25

-- on ubuntu : 18.04.1-Ubuntu
    ipsec --version : Linux Libreswan 3.23 

# On Aws Linux the IPsec connection still UP ( reconnect each 1800s)

Bellow the logs : 

Oct 17 17:28:04.431812: added connection description "awslinuxnfs"
Oct 17 17:28:09.816186: "awslinuxnfs" #1: initiating v2 parent SA
Oct 17 17:28:09.816224: "awslinuxnfs" #1: local IKE proposals for awslinuxnfs (IKE SA initiator selecting KE): 1:IKE:ENCR=AES_CBC_256;PRF=HMAC_SHA2_512;INTEG=HMAC_SHA2_512_256;DH=MODP4096
Oct 17 17:28:09.822827: "awslinuxnfs" #1: STATE_PARENT_I1: sent v2I1, expected v2R1
Oct 17 17:28:09.934341: "awslinuxnfs" #1: local ESP/AH proposals for awslinuxnfs (IKE SA initiator emitting ESP/AH proposals): 1:ESP:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_512_256;DH=NONE;ESN=DISABLED
Oct 17 17:28:09.934404: "awslinuxnfs" #2: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=aes_256 integ=sha512_256 prf=sha2_512 group=MODP4096}
Oct 17 17:28:10.010336: "awslinuxnfs" #2: IKEv2 mode peer ID is ID_IPV4_ADDR: 'IP_right'
Oct 17 17:28:10.010453: "awslinuxnfs" #2: Authenticated using authby=secret
Oct 17 17:28:10.043524: "awslinuxnfs" #2: negotiated connection [IP_left-IP_left:2049-2049 6] -> [IP_right-IP_right:0-65535 0]
Oct 17 17:28:10.043562: "awslinuxnfs" #2: STATE_V2_IPSEC_I: IPsec SA established transport mode {ESP=>0xc181d369 <0x4192ccf0 xfrm=AES_CBC_256-HMAC_SHA2_512_256 NATOA=none NATD=none DPD=passive}
Oct 17 17:58:10.059012: "awslinuxnfs" #2: deleting other state #2 (STATE_CHILDSA_DEL) and NOT sending notification
Oct 17 17:58:10.069402: "awslinuxnfs" #1: deleting state (STATE_IKESA_DEL) and NOT sending notification
Oct 17 17:58:10.069476: "awslinuxnfs" #1: deleting IKE SA for connection 'awslinuxnfs' but connection is supposed to remain up; schedule EVENT_REVIVE_CONNS
Oct 17 17:58:10.069602: Initiating connection awslinuxnfs which received a Delete/Notify but must remain up per local policy
Oct 17 17:58:10.069635: "awslinuxnfs" #3: initiating v2 parent SA
Oct 17 17:58:10.076160: "awslinuxnfs" #3: STATE_PARENT_I1: sent v2I1, expected v2R1
Oct 17 17:58:10.180891: "awslinuxnfs" #3: local ESP/AH proposals for awslinuxnfs (IKE SA initiator emitting ESP/AH proposals): 1:ESP:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_512_256;DH=NONE;ESN=DISABLED
Oct 17 17:58:10.180952: "awslinuxnfs" #4: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=aes_256 integ=sha512_256 prf=sha2_512 group=MODP4096}
Oct 17 17:58:10.247396: "awslinuxnfs" #4: IKEv2 mode peer ID is ID_IPV4_ADDR: 'IP_right'
Oct 17 17:58:10.247501: "awslinuxnfs" #4: Authenticated using authby=secret
Oct 17 17:58:10.258395: "awslinuxnfs" #4: negotiated connection [IP_left-IP_left:2049-2049 6] -> [IP_right-IP_right:0-65535 0]
Oct 17 17:58:10.258419: "awslinuxnfs" #4: STATE_V2_IPSEC_I: IPsec SA established transport mode {ESP=>0xcaeddeef <0x65fb42cb xfrm=AES_CBC_256-HMAC_SHA2_512_256 NATOA=none NATD=none DPD=passive}

# On ubuntu, the IPsec connection id deleted aferter 1800s without reconnection

Bellow the logs :

Oct 17 17:26:15.229136: added connection description "awslinuxnfs"
Oct 17 17:26:46.896396: "awslinuxnfs" #1: initiating v2 parent SA
Oct 17 17:26:46.896449: "awslinuxnfs" #1: awslinuxnfs IKE proposals for initial initiator (selecting KE): 1:IKE:ENCR=AES_CBC_256;PRF=HMAC_SHA2_512;INTEG=HMAC_SHA2_512_256;DH=MODP4096
Oct 17 17:26:46.900273: "awslinuxnfs" #1: STATE_PARENT_I1: sent v2I1, expected v2R1
Oct 17 17:26:47.001603: "awslinuxnfs" #1: awslinuxnfs ESP/AH proposals for initiator: 1:ESP:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_512_256;ESN=DISABLED
Oct 17 17:26:47.001843: "awslinuxnfs" #2: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=aes_256 integ=sha512_256 prf=sha2_512 group=MODP4096}
Oct 17 17:26:47.077769: "awslinuxnfs" #2: IKEv2 mode peer ID is ID_IPV4_ADDR: 'IP_right'
Oct 17 17:26:47.081913: "awslinuxnfs" #2: negotiated connection [IP_left-IP_left:2049-2049 6] -> [IP_right-IP_right:0-65535 0]
Oct 17 17:26:47.082073: "awslinuxnfs" #2: STATE_V2_IPSEC_I: IPsec SA established transport mode {ESP=>0xc662fd53 <0x86f73876 xfrm=AES_CBC_256-HMAC_SHA2_512_256 NATOA=none NATD=none DPD=passive}
Oct 17 17:56:47.120677: "awslinuxnfs" #2: deleting other state #2 (STATE_CHILDSA_DEL)
Oct 17 17:56:47.124379: "awslinuxnfs" #1: deleting state (STATE_IKESA_DEL)

I try de install ans use  the Libreswan 3.25 on ubuntu using source but il got the same issue, 
bellow the logs :

Oct 18 10:08:58.684270: "awslinuxnfs" #1: initiating v2 parent SA
Oct 18 10:08:58.684295: "awslinuxnfs" #1: local IKE proposals for awslinuxnfs (IKE SA initiator selecting KE): 1:IKE:ENCR=AES_CBC_256;PRF=HMAC_SHA2_512;INTEG=HMAC_SHA2_512_256;DH=MODP4096
Oct 18 10:08:58.687798: "awslinuxnfs" #1: STATE_PARENT_I1: sent v2I1, expected v2R1
Oct 18 10:08:58.845204: "awslinuxnfs" #1: local ESP/AH proposals for awslinuxnfs (IKE SA initiator emitting ESP/AH proposals): 1:ESP:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_512_256;DH=NONE;ESN=DISABLED
Oct 18 10:08:58.845346: "awslinuxnfs" #2: STATE_PARENT_I2: sent v2I2, expected v2R2 {auth=IKEv2 cipher=aes_256 integ=sha512_256 prf=sha2_512 group=MODP4096}
Oct 18 10:08:58.919717: "awslinuxnfs" #2: IKEv2 mode peer ID is ID_IPV4_ADDR: 'IP_right'
Oct 18 10:08:58.919825: "awslinuxnfs" #2: Authenticated using authby=secret
Oct 18 10:08:58.931616: "awslinuxnfs" #2: negotiated connection [IP_left-IP_left:2049-2049 6] -> [IP_right-IP_right:0-65535 0]
Oct 18 10:08:58.931640: "awslinuxnfs" #2: STATE_V2_IPSEC_I: IPsec SA established transport mode {ESP=>0xc7d49dd2 <0x555cb259 xfrm=AES_CBC_256-HMAC_SHA2_512_256 NATOA=none NATD=none DPD=passive}
Oct 18 10:38:58.967974: "awslinuxnfs" #2: deleting other state #2 (STATE_CHILDSA_DEL) and NOT sending notification
Oct 18 10:38:58.975227: "awslinuxnfs" #1: deleting state (STATE_IKESA_DEL) and NOT sending notification

# The same configuration file : /etc/ipsec.d/awslinuxnfs.conf
conn awslinuxnfs

    type=transport
    leftid=IP_left
    left=IP_left
    rightid=IP_right
    right=IP_right
    authby=secret
    auto=start
    ikev2=yes
    ike=AES_CBC_256-HMAC_SHA2_512-MODP4096
    esp=AES_CBC_256-HMAC_SHA2_512_256
    leftprotoport=tcp/2049

===

Could you plase help with this.
regards,
Eastwoof

**Comment by letoams** [comment]
On Tue, 18 Oct 2022, eastwoof13 wrote:

>                                                on aws linux :
> ipsec --version : Linux Libreswan 3.25
>                                          on ubuntu : 18.04.1-Ubuntu
> ipsec --version : Linux Libreswan 3.23
> 
> Oct 17 17:58:10.069602: Initiating connection awslinuxnfs which received a Delete/Notify but must remain up
> per local policy

> -- on ubuntu

> Oct 17 17:56:47.120677: "awslinuxnfs" #2: deleting other state #2 (STATE_CHILDSA_DEL)
> Oct 17 17:56:47.124379: "awslinuxnfs" #1: deleting state (STATE_IKESA_DEL)

The difference is visible in the "revive handler" where 3.25 says
"received delete but must remain up".

> I try de install the Libreswan 3.25 on ubuntu using source but il got the same issu, bellow the logs :

> Oct 18 10:08:58.931640: "awslinuxnfs" #2: STATE_V2_IPSEC_I: IPsec SA established transport mode
> {ESP=>0xc7d49dd2 <0x555cb259 xfrm=AES_CBC_256-HMAC_SHA2_512_256 NATOA=none NATD=none DPD=passive}
> Oct 18 10:38:58.967974: "awslinuxnfs" #2: deleting other state #2 (STATE_CHILDSA_DEL) and NOT sending
> notification
> Oct 18 10:38:58.975227: "awslinuxnfs" #1: deleting state (STATE_IKESA_DEL) and NOT sending notification

Is it possible that you didnt restart the ipsec service after upgrading
to 3.25 ?

Paul

**Comment by eastwoof13** [comment]
Thanks Paul for your replay.
I did restart ipsec I even reboot the server, but I got the same message, 

Oct 18 15:45:53.026468: "awslinuxnfs" #2: deleting other state #2 (STATE_CHILDSA_DEL) and NOT sending notification
Oct 18 15:45:53.030680: "awslinuxnfs" #1: deleting state (STATE_IKESA_DEL) and NOT sending notification

**Comment by letoams** [comment]
On Tue, 18 Oct 2022, eastwoof13 wrote:

> Thanks Paul for your replay.
> I did restart ipsec I even reboot the server, but I got the same message,
> 
> Oct 18 15:45:53.026468: "awslinuxnfs" #2: deleting other state #2 (STATE_CHILDSA_DEL) and NOT sending
> notification
> Oct 18 15:45:53.030680: "awslinuxnfs" #1: deleting state (STATE_IKESA_DEL) and NOT sending notification

Did you use auto=start or ensures this end is the initiator with doing
ipsec auto --up awslinuxnfs ?

If the other end initiated to you, and they then send you a delete, and
you have auto=add, then it will not try to keep the connection up.

**Comment by eastwoof13** [comment]
I use auto=start.
==
ype=transport
leftid=IP_left
left=IP_left
rightid=IP_right
right=IP_right
authby=secret
auto=start
ikev2=yes
ike=AES_CBC_256-HMAC_SHA2_512-MODP4096
esp=AES_CBC_256-HMAC_SHA2_512_256
leftprotoport=tcp/2049

**Comment by eastwoof13** [comment]
Hi Paul,
As I say the IPsec is configured between Linux server ( NFS client) as a left side, and a NetApp NAS as a right side.
For Linux aws  it works find without disconnection, but on ubuntu, it disconnets each 1800s.
teh ipsec conf file are the same ( I only change the IP of each server)

The configuration on NetApp side is very basic and simple, as you can see below :
NetApp::> security ipsec policy show -name pol_test_1234 -instance

                                    Vserver: svm_netapp
                                Policy Name: pol_test_1234
                           Local IP Subnets: IP_right_netapp/32
                          Remote IP Subnets: IP_left_aws/32
                                Local Ports: 0-0
                               Remote Ports: 2049-2049
                                  Protocols: any
                                     Action: ESP_TRA
                               Cipher Suite: SUITE_AESCBC
          IKE Security Association Lifetime: 86400
        IPsec Security Association Lifetime: 28800
IPsec Security Association Lifetime (bytes): 0
                          Is Policy Enabled: true
                             Local Identity: IP_right_netapp
                            Remote Identity: IP_left_aws
                      Authentication Method: PSK
             Certificate for Local Identity: -


NetApp::> security ipsec policy show -name pol_test_ubuntu -instance

                                    Vserver: svm_netapp
                                Policy Name: pol_test_ubuntu
                           Local IP Subnets: IP_right_netapp/32
                          Remote IP Subnets: IP_left_ubuntu/32
                                Local Ports: 0-0
                               Remote Ports: 2049-2049
                                  Protocols: any
                                     Action: ESP_TRA
                               Cipher Suite: SUITE_AESCBC
          IKE Security Association Lifetime: 86400
        IPsec Security Association Lifetime: 28800
IPsec Security Association Lifetime (bytes): 0
                          Is Policy Enabled: true
                             Local Identity: IP_right_netapp
                            Remote Identity: IP_left_ubuntu
                      Authentication Method: PSK
             Certificate for Local Identity: -

on the NetApp side, il got this log 
- the ubuntu doesn't initiate a new IKE_SA
- the aws linux initiate a new IKE_SA

Below the logs on netApp side 

Oct 19 12:46:11.084 11[JOB] deleting IKE_SA after 1800 seconds of CHILD_SA inactivity
Oct 19 12:46:11.087 11[IKE] deleting IKE_SA svm_netapp:pol_test_ubuntu[2891] between IP_right_netapp[IP_right_netapp]...IP_left_ubuntu[IP_left_ubuntu]
Oct 19 12:46:11.091 11[IKE] sending DELETE for IKE_SA svm_netapp:pol_test_ubuntu[2891]
Oct 19 12:46:11.094 11[ENC] generating INFORMATIONAL request 59 [ D ] IP_right_netapp[500] <==> IP_left_ubuntu[500]
Oct 19 12:46:11.097 04[NET] socket_default_socket.c: send_msg_v4 sent 96 bytes from IP_right_netapp[500] to IP_left_ubuntu[500] in vserver 2
Oct 19 12:46:11.130 11[ENC] parsed INFORMATIONAL response 59 [ ] IP_left_ubuntu[500] <==> IP_right_netapp[500]
Oct 19 12:46:11.132 11[IKE] IKE_SA deleted


but for the linux aws connection :

Oct 19 06:19:08.482 12[JOB] deleting IKE_SA after 1800 seconds of CHILD_SA inactivity
Oct 19 06:19:08.485 12[IKE] deleting IKE_SA svm_netapp:pol_test_1234[2877] between IP_right_netapp[IP_right_netapp]...IP_left_aws[IP_left_aws]
Oct 19 06:19:08.488 12[IKE] sending DELETE for IKE_SA svm_netapp:pol_test_1234[2877]
Oct 19 06:19:08.491 12[ENC] generating INFORMATIONAL request 59 [ D ] IP_right_netapp[500] <==> IP_left_aws[500]
Oct 19 06:19:08.494 04[NET] socket_default_socket.c: send_msg_v4 sent 96 bytes from IP_right_netapp[500] to IP_left_aws[500] in vserver 2
Oct 19 06:19:08.525 12[ENC] parsed INFORMATIONAL response 59 [ ] IP_left_aws[500] <==> IP_right_netapp[500]
Oct 19 06:19:08.532 12[IKE] IKE_SA deleted

Oct 19 06:19:08.538 12[KNL] kernel_pfkey_ipsec.c:del_policy() deleting policy from vserver(2) IP_right_netapp/32 === IP_left_aws/32[tcp/nfsd] out
Oct 19 06:19:08.541 12[KNL] kernel_pfkey_ipsec.c:del_policy() deleting policy from vserver(2) IP_left_aws/32[tcp/nfsd] === IP_right_netapp/32 in
Oct 19 06:19:08.543 01[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(FRAG_SUP) N(NATD_S_IP) N(NATD_D_IP) ] IP_left_aws[500] <==> IP_right_netapp[500]

Oct 19 06:19:08.547 01[IKE] IP_left_aws is initiating an IKE_SA
Oct 19 06:19:08.549 01[CFG] selected proposal: IKE:AES_CBC_256/HMAC_SHA2_512_256/PRF_HMAC_SHA2_512/MODP_4096
Oct 19 06:19:08.608 01[ENC] generating IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) CERTREQ N(FRAG_SUP) N(CHDLESS_SUP) N(MULT_AUTH) ] IP_right_netapp[500] <==> IP_left_aws[500]
Oct 19 06:19:08.612 04[NET] socket_default_socket.c: send_msg_v4 sent 777 bytes from IP_right_netapp[500] to IP_left_aws[500] in vserver 2
Oct 19 06:19:08.648 01[ENC] parsed IKE_AUTH request 1 [ IDi AUTH SA TSi TSr N(USE_TRANSP) ] IP_left_aws[500] <==> IP_right_netapp[500]
Oct 19 06:19:08.651 01[CFG] looking for peer configs matching IP_right_netapp[%any]...IP_left_aws[IP_left_aws]
Oct 19 06:19:08.654 01[CFG] selected peer config 'svm_netapp:pol_test_1234'
Oct 19 06:19:08.657 01[IKE] authentication of 'IP_left_aws' with pre-shared key successful
Oct 19 06:19:08.659 01[IKE] authentication of 'IP_right_netapp' (myself) with pre-shared key at vserver 2
Oct 19 06:19:08.662 01[IKE] IKE_SA svm_netapp:pol_test_1234[2878] established between IP_right_netapp[IP_right_netapp]...IP_left_aws[IP_left_aws]
Oct 19 06:19:08.664 01[IKE] scheduling rekeying in 85719s
Oct 19 06:19:08.667 01[CFG] selected proposal: ESP:AES_CBC_256/HMAC_SHA2_512_256/NO_EXT_SEQ
Oct 19 06:19:08.671 01[KNL] kernel_pfkey_ipsec.c:add_policy(): Successfully added vserver(2) policy index 1257 IP_left_aws/32[tcp/nfsd] === IP_right_netapp/32 in
Oct 19 06:19:08.675 01[KNL] kernel_pfkey_ipsec.c:add_policy(): Successfully added vserver(2) policy index 1258 IP_right_netapp/32 === IP_left_aws/32[tcp/nfsd] out
Oct 19 06:19:08.678 01[IKE] CHILD_SA svm_netapp:pol_test_1234{655} established with SPIs c5be5978_i a61f83d6_o and TS IP_right_netapp/32 === IP_left_aws/32[tcp/nfsd]
Oct 19 06:19:08.681 01[KNL] PF_ROUTE lookup failed: No such process
Oct 19 06:19:08.687 01[ENC] generating IKE_AUTH response 1 [ IDr AUTH N(USE_TRANSP) N(ESP_TFC_PAD_N) SA TSi TSr ] IP_right_netapp[500] <==> IP_left_aws[500]
Oct 19 06:19:08.692 04[NET] socket_default_socket.c: send_msg_v4 sent 288 bytes from IP_right_netapp[500] to IP_left_aws[500] in vserver 2

**Comment by letoams** [comment]
On Wed, 19 Oct 2022, eastwoof13 wrote:

> As I say the IPsec is configured between Linux server ( NFS client) as a left side, and a NetApp NAS as a right side.
> For Linux aws it works find without disconnection, but on ubuntu, it disconnets each 1800s.
> teh ipsec conf file are the same ( I only change the IP of each server)

But you also made the version of libreswan the same? So how can there be
a difference in behaviour ?

> on the NetApp side, il got this log
>
>  *  the ubuntu doesn't initiate a new IKE_SA
>  *  the aws linux initiate a new IKE_SA
> 
> Below the logs on netApp side
> 
> Oct 19 12:46:11.084 11[JOB] deleting IKE_SA after 1800 seconds of CHILD_SA inactivity
[...]
> Oct 19 12:46:11.130 11[ENC] parsed INFORMATIONAL response 59 [ ] IP_left_ubuntu[500] <==> IP_right_netapp[500]
> Oct 19 12:46:11.132 11[IKE] IKE_SA deleted

I assume no new log entries from here on ?

> but for the linux aws connection :
> 
> Oct 19 06:19:08.482 12[JOB] deleting IKE_SA after 1800 seconds of CHILD_SA inactivity

> Oct 19 06:19:08.532 12[IKE] IKE_SA deleted
> 
> Oct 19 06:19:08.538 12[KNL] kernel_pfkey_ipsec.c:del_policy() deleting policy from vserver(2) IP_right_netapp/32 ===
> IP_left_aws/32[tcp/nfsd] out
> Oct 19 06:19:08.541 12[KNL] kernel_pfkey_ipsec.c:del_policy() deleting policy from vserver(2) IP_left_aws/32[tcp/nfsd] ===
> IP_right_netapp/32 in
> Oct 19 06:19:08.543 01[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(FRAG_SUP) N(NATD_S_IP) N(NATD_D_IP) ] IP_left_aws[500]
> <==> IP_right_netapp[500]

Not sure why those kernel_pfkey_ipsec.c entries were not there on the
above one (or perhaps you didn't paste them in). But those should not
matter anyway. It is the receiving of IKE_SA_INIT request 0 that shows
libreswan initiated in that case.

You can try running both libreswan 3.25 versions with plutodebug=all
and see what the difference is? Especially around the "revive" code.

Paul

**Comment by eastwoof13** [comment]
For Aws linux : I use the pre-built version : 3.25 ( and it's work)
For ubunto : First I use the pre-built version 3.23 ( doesn't work) and after I install the source-based build 3.25
===
As you suggest, I enable debug all pluto logs. and there is no reviv word in the logs on ubuntu .

but in the Aws linux we have the logs below:
Line  223: Oct 19 15:43:30.539803: "awslinuxnfs" #1: deleting IKE SA for connection 'awslinuxnfs' but connection is supposed to remain up; schedule EVENT_REVIVE_CONNS
	Line  224: Oct 19 15:43:30.539807: | add revival: connection 'awslinuxnfs' added to the list and scheduled for 0 seconds
	Line  225: Oct 19 15:43:30.539810: | event_schedule: new EVENT_REVIVE_CONNS-pe@0x55966e99a6e8
	Line  226: Oct 19 15:43:30.539815: | inserting event EVENT_REVIVE_CONNS, timeout in 0.000 seconds
	Line  253: Oct 19 15:43:30.540024: | handling event EVENT_REVIVE_CONNS
	Line  296: Oct 19 15:43:30.540216: | free_event_entry: release EVENT_REVIVE_CONNS-pe@0x55966e99a6e8
================

Now I test with 3.28 source-based build version and it works fine

I'm using ubuntu 18.04. 
Could you please tell me if libreswan 3.28 is compatible with ubuntu 18.04 ?

Eastwoof

**Comment by eastwoof13** [comment]
installing 3.28  has resolved the issue

thanks Paul
