### ISSUE TITLE
test for subnet=${sourceip}

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#897]
For instance, given:
```
conn x
    leftsourceip=1.2.3.4
    #leftsubnet=1.2.3.4/32
```
`leftsubnet` should default to `leftsourceip`; nothing seems to test this (based on code being disabled, and nothing breaking)

**Comment by cagney** [comment]
Probably should not be allowed.

**Comment by bleve** [comment]
source without subnet shouldn't really be allowed.

**Comment by paulwouters** [comment]
this is wrong. No leftsubnet= implies left == leftsubnet, and a leftsourceip != leftsubnet would be bogus.
I'd say rip this code out

**Comment by cagney** [comment]
need to check history

**Comment by paulwouters** [comment]
extract_connection should fail a conn with leftsourceip= without leftsubnet=

**Comment by cagney** [comment]
The original patch is 7d7bdb46d2ffa73528bc315a687b4b44af8d6e6b but cfb763e00952e643abc104971dd08ed0ec07ef67 gets an honourable mention :-)

**Comment by paulwouters** [comment]
2013 me was wrong to do that!  Bad Paul! revert! revert!
