### ISSUE TITLE
sourceip+subnets, we have a problem

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#901]
Curently we're allowed:
```
sourceip=IPv4
subnets=IPv4,...,IPv6,...
```
- do we need a way to specify the IPv6 source address?
- do we need a way to specify the source IP source address for each selector destination?

**Comment by letoams** [comment]
On Mon, 31 Oct 2022, cagney wrote:

> Curently we're allowed:
> 
> sourceip=IPv4
> subnets=IPv4,...,IPv6,...
>  *  do we need a way to specify the IPv6 source address?
>  *  do we need a way to specify the source IP source address for each selector destination?

If sourceip not within subnet{x}, ignore it.

We should already do this for:

leftsourceip=1.2.3.4
leftsubnet=8.8.8.0/24

it is not different for when we have multiple subnets ?

Paul

**Comment by cagney** [comment]
> If sourceip not within subnet{x}, ignore it.

This isn't happening.  So:
- only pass sourceip to updown when it is within the local selector
- consider a list of sourceips to be searched

**Comment by cagney** [comment]
sourceip=dns-name is allowed so need to accommodate the DNS lookup returning a list of IPv4 and IPv6 addresses.

**Comment by letoams** [comment]
On Thu, 10 Nov 2022, cagney wrote:

> sourceip=dns-name is allowed so need to accommodate the DNS lookup returning a list of IPv4 and IPv6
> addresses.

Seems like an artifact. I would say it should take one ipv4 (and/or one
ipv6) address? And not a dns name ?

**Comment by cagney** [comment]
At the time 7d7bdb46d2ffa73528bc315a687b4b44af8d6e6b there was no numeric only alternative so who knows.

Should one sourceip per subnet/selector be allowed?  For instance:
```
sourceip=1.1.1.1,2.2.2.2
subnet=1.1.1.0/24,2.2.2.0/24
```

**Comment by letoams** [comment]
Probably not, the idea was to change the default source ip for one destination but for multiple destinations that might get tricky, eg a ping on the gateway to a remote subnet could use either of the local subnets and we can’t define which 

Sent using a virtual keyboard on a phone

**Comment by cagney** [comment]
the DNS lookup is gone; can look at changing this to a list later
