### ISSUE TITLE
A new feature proposal——bypass traffic through some certain or a range of ports

### ISSUE THREAD

**Issue by Benson666** [libreswan/libreswan#902]
lately，I am designing a IPSec mesh scenario which protect all the east-west traffic excluding some special traffic through  some certain or a range of ports. My purpose is protecting the control-plane ports without authentication and authorization against illegal access and other attacks.But the data-plane traffic has been encypted，we don't want to waste resoure to encypt traffic twice，so we need to bypass them by specifying address,protocol and port.
   One idea is making bypass-policies by "ip xfrm po" command，but it's ugly and difficult to mantain.
   So，Can Libreswan implement this feature?

**Comment by letoams** [comment]
On Mon, 31 Oct 2022, Benson666 wrote:

> Subject: [libreswan/libreswan] A new feature proposal——bypass traffic through
>     some certain or a range of ports (Issue #902)

> illegal access and other attacks.But the data-plane traffic has been encypted，we don't want to
> waste resoure to encypt traffic twice，so we need to bypass them by specifying address,protocol
> and port.

> So，Can Libreswan implement this feature?

See "ipsec portexcludes" that can do this for Opportunistic Encryption,
but you can also just make a special conn:

conn exclude-22in
 	left=0.0.0.0/0
 	right=%any
 	leftprotoport=tcp/22
 	rightprotoport=tcp/%any
 	authby=never
 	auto=route

conn exclude-22out
 	left=0.0.0.0/0
 	right=%any
 	leftprotoport=tcp/%any
 	rightprotoport=tcp/22
 	authby=never
 	auto=route

Paul

**Comment by cagney** [comment]
got thumbs up
