### ISSUE TITLE
libreswan on ubuntu touch

### ISSUE THREAD

**Issue by jhay06** [libreswan/libreswan#904]
hi im trying to compile libreswan using libertine container on my ubuntu touch phone , already installed iall deps. but got error while compiling 
![screenshot20221105_100024060](https://user-images.githubusercontent.com/5191437/200096229-6ba228c3-2a4b-45c6-8cc4-d510e6a4bc12.png)

any ideas?

btw ,y ubport is xenial 16.04 with arm64 arch

**Comment by jhay06** [comment]
anyone?

**Comment by cagney** [comment]
How old is that NSS?
I'd cut/paste this code https://github.com/libreswan/libreswan/issues/892#issuecomment-1286057735 into that file.

**Comment by jhay06** [comment]
unfortunately it doesn't work because of some dependencies of latest nss are not present on 16.04 to download.  what  version of libreswan works on 16.04 ? is there a version that will works on 16.04 maybe an old version ?

**Comment by letoams** [comment]
grep NSS mk/*   and tweak. It will compile if using the right combination.

Sent using a virtual keyboard on a phone

**Comment by cagney** [comment]
16.04 is way old; I guess hacks are still needed

**Comment by cagney** [comment]
version in question is dead
