### ISSUE TITLE
netlink_expire got XFRM_MSG_EXPIRE message in libreswan 4.7

### ISSUE THREAD

**Issue by frostashe** [libreswan/libreswan#910]
Thu Nov 17 16:29:07 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:29:07 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:29:07 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:29:20 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:29:23 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:29:23 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:29:38 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:29:45 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:29:47 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:29:47 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:29:47 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:29:58 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:30:08 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:30:09 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:30:09 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:30:17 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:30:18 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:30:39 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:30:49 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:30:57 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:30:57 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:30:57 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:31:14 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:31:14 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:31:28 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:31:33 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message
Thu Nov 17 16:31:44 2022 authpriv.warn pluto[19120]: netlink_expire got XFRM_MSG_EXPIRE message with length 116 < 232 bytes; ignore message

**Comment by cagney** [comment]
please try 4.9
please provide more context

**Comment by bleve** [comment]
Note, messages are warnings, not errors.These won't cause any problems.

**Comment by cagney** [comment]
#697
