### ISSUE TITLE
on initiator merge initiator=::/0 with response ::1,::2 into SPDs

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#922]
Given:
```
::/0
```
The initiator builds and installs a corresponding kernel policy.  However, when the response is:
```
::1
::2
```
the code pretty much ignores the second and only updates the first.  It gets tricky though:

- presumably the wider policy should be deleted
- presumably replacement SPDs should be generated

Ref #918

**Comment by letoams** [comment]
> On Nov 24, 2022, at 13:02, cagney ***@***.***> wrote:
> 
> ﻿
> Given:
> 
> ::/0
> The initiator builds and installs a corresponding kernel policy. However, when the response is:
> 
> ::1
> ::2
> the code pretty much ignores the second and only updates the first. It gets tricky though:
> 
> presumably the wider policy should be deleted

No it should likely remain there as %hold - or whatever the failureshunt is 
> presumably replacement SPDs should be generated

Not sure what you mean? You have one child with both subnets as selectors right !

Paul

**Comment by cagney** [comment]
> No it should likely remain there as %hold - or whatever the failureshunt is

Might be time to blow away the eclipsed code then.  

> > presumably replacement SPDs should be generated
> Not sure what you mean? You have one child with both subnets as selectors right ! Paul

We need to get to that.  Given ::/0 only one SPD was created, and during connection add.  The pexpect()s we're seeing are from code encountering more selectors than SPDs.

So, in theory:
- route installs the connection's shunts (bare kernel policies)
- create child layers real kernel policies over the top
