### ISSUE TITLE
File-missing

### ISSUE THREAD

**Issue by ABHISHEK2F24** [libreswan/libreswan#93]
in docs/ipsec.html file there is three option on top & bottom of page i.e.
contents
previous
next
which must be the link to new page but these link doesn't work they show
error 404 : page not found

**Comment by letoams** [comment]
On Sun, 2 Apr 2017, Abhishek Kumar Maurya wrote:

> in docs/ipsec.html file there is three option on top & bottom of page i.e.

The docs/*html was left to ensure we copied all information from it
before deleting it. By now the wiki probably contains all of it and
I'll look at removing it altogether.

Paul

**Comment by letoams** [comment]
obsolete file removed.
