### ISSUE TITLE
Strange behavior when Chromebook attempts to connect

### ISSUE THREAD

**Issue by rrothermund** [libreswan/libreswan#95]
Running ChromeOS 57 on a HP Chromebook 13 G1. When attempting to connect, I get the following in the log (using pastebin due to length): [paste](https://pastebin.com/HFXxkmMv)

To my untrained eyes, it seems like the connection is causing something to constantly restart? I am also using a Nexus 6P to connect to the same server, using the same credentials and have no issues connecting.

**Comment by letoams** [comment]
It seems to crash. Can you get a core dump or gdb back trace?

**Comment by rrothermund** [comment]
Sorry, fairly new to all of this. I see a message in auth.log about a pluto dump to /var/run/pluto  when listing that directory, there is an empty pluto.ctl folder and a 6 byte pluto.pid file. Anything else I should try?

**Comment by letoams** [comment]
On Thu, 13 Apr 2017, rrothermund wrote:

> Sorry, fairly new to all of this. I see a message in auth.log about a pluto dump to /var/run/pluto when listing that directory, there is an empty pluto.ctl folder and a 6 byte pluto.pid
> file. Anything else I should try?

If you have installed libreswan via package, and installed the debuginfo
package, you can run:

ipsec start
gdb -p `pidof pluto`

then tell gdb to "cont". Then do what it is that makes pluto crash, You
will see a prompt in gdb. Then type: backtrace

That should provide some information as to where it is crashing. It
might be worth to do "bt full" and capture that somewhere.

Paul

**Comment by letoams** [comment]
not enough information and we have done 2 releases since the original bug report Please re-open if this still happens to you
