### ISSUE TITLE
what does CAT + IPv4+IPv6 leases mean?

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#950]
The CAT code overrides TS values, with two leases it gets worse.

**Comment by cagney** [comment]
By confining CAT to OE (which never asks for more than one address?), then this problem won't occur.
ref #1074

**Comment by letoams** [comment]
On Mon, 10 Apr 2023, cagney wrote:

> By confining CAT to OE (which never asks for more than one address?), then this problem won't occur.

In the future, when we see hosts behind IPv6 NAT, this might need to be
added as a feature. But let's not pre-emptively do this now.
