### ISSUE TITLE
on-demand ping trigger deletes wrong kernel policy

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#952]
It goes something like this:

- acquire reports icmp/8->icmp/0
- a bare shunt with stripped ports aka icmp/0->icmp/0 is created
- raw_policy() is called with protocol/port stripped //->// shunt (it's a no-op but ignore that)
- the bare shunt for icmp/0->icmp/0 is deleted
- the kernel policy for icmp/0->icmp/0 is deleted, which always fails

which is why bare shunts should include ports

**Comment by letoams** [comment]
Bare shunts don’t include ports so it trapped all traffic to the destination /32, since we would be building up full ip tunnels.

Non-oe would just install the wide policy of the matching conn. OE would do the entire /32. Protoport exceptions are done with permanent holes in the shunt (eg our port 22 test cases )

Why do you think keeping the ports is useful ?

Paul

Sent using a virtual keyboard on a phone

**Comment by cagney** [comment]
> Bare shunts don’t include ports so it trapped all traffic to the destination /32, since we would be building up full ip tunnels.

Focus not on the end goal, but on the journey (I'm sure I could find some pithy quote to insert here).

> Non-oe would just install the wide policy of the matching conn. OE would do the entire /32. Protoport exceptions are done with permanent holes in the shunt (eg our port 22 test cases )

> Why do you think keeping the ports is useful ?

The bare shunt table should speak only of the truth (with KLIPS gone this has hopefully got easier):

- if the kernel policy created for the acquire has a port, then so too should the bare shunt
- if the kernel policy replacing it does not have a port, then neither should the bare shunt

Currently, as part of its journey through the acquire code, pluto tries to delete the kernel policy corresponding to the acquire using:

| kernel: delete_kernel_policy() delete narrow old: OUTBOUND IGNORE_KERNEL_POLICY_MISSING client=192.0.1.254/32/ICMP/0->192.0.2.254/32/ICMP/0 xfrm_if_id=-1 id=0 sec_label= (assign_holdpass() +1996 programs/pluto/kernel.c)

which does not exist.  It should be ICMP/8->ICMP/0 but the bare shunt code likes to strip the port.

**Comment by letoams** [comment]
On Mon, 19 Dec 2022, cagney wrote:

>       Why do you think keeping the ports is useful ?
> 
> The bare shunt table should speak only of the truth (with KLIPS gone this has hopefully got easier):
>
>  *  if the kernel policy created for the acquire has a port, then so too should the bare shunt
>  *  if the kernel policy replacing it does not have a port, then neither should the bare shunt

Just install bare shunts with a lifetime expiry an kill pluto's entire bare shunt table.

**Comment by cagney** [comment]
> Just install bare shunts with a lifetime expiry an kill pluto's entire bare shunt table.

The problem is code stripping ports when it shouldn't.
The other problem is that all the kernel policies that are inserted need unique sa_marks.

In many ways the bare shunt table proper is a side show.

**Comment by cagney** [comment]
code removing wrong policy removed
