### ISSUE TITLE
IKEv2 with multiple subnets

### ISSUE THREAD

**Issue by pseudometric** [libreswan/libreswan#96]
Hello,

I have a LibreSWAN connection configuration with one left subnets and two right subnets. With IKEv1, I get what I expect: a single phase 1 (IKE) SA, and two associated phase 2 (IPsec) SAs. With IKEv2, I would similarly expect a single parent SA and two child SAs —but that’s not what I get; instead, pluto performs two complete IKE exchanges from scratch (seen in a packet capture), resulting in multiple parent SAs. The IPsec SAs are created, but confusingly the output of `ipsec status` only mentions `PARENT` SAs, even though the negotiated ESP tunnel SAs are clearly there. Can you comment on what I should expect here and why it’s behaving this way? I’m using `libreswan-3.15-5.el7_1.x86_64` on RHEL7 with NETKEY.

If there’s a better place to post questions like this, please redirect me.

Thanks,

Richard

**Comment by bleve** [comment]
Questions belong to mailinglist, check https://lists.libreswan.org/mailman/listinfo

Also this issue is already addressed in later libreswan versions.

**Comment by bleve** [comment]
Also note software naming, It's Libreswan. No capital letters, please.

**Comment by letoams** [comment]
On Sun, 16 Apr 2017, Richard E. Silverman wrote:

> I have a LibreSWAN connection configuration with one left subnets and two right subnets. With IKEv1, I get what I expect: a
> single phase 1 (IKE) SA, and two associated phase 2 (IPsec) SAs. With IKEv2, I would similarly expect a single parent SA and two
> child SAs -- but that's not what I get; instead, pluto performs two complete IKE exchanges from scratch (seen in a packet
> capture), resulting in multiple parent SAs. The IPsec SAs are created, but confusingly the output of ipsec status only mentions
> PARENT SAs, even though the negotiated ESP tunnel SAs are clearly there. Can you comment on what I should expect here and why
> it's behaving this way? I'm using libreswan-3.15-5.el7_1.x86_64 on RHEL7.

please use libreswan 3.20 or higher. Versions beforethat have a very
limited implementation of CREATE_CHILD_SA.

Also, we prefer the mailinglist for discussions.

Paul

**Comment by pseudometric** [comment]
OK, I'll try it, and use that mailing list in the future. Thanks!
