### ISSUE TITLE
Libreswan 3.20 : make module fails with "implicit declaration of function" error on Debian 9

### ISSUE THREAD

**Issue by francis16** [libreswan/libreswan#97]
Hello,

Here is the errors displayed :
/usr/src/libreswan-3.20/modobj/ipsec_alg_cryptoapi.c: In function 'setup_digest':
/usr/src/libreswan-3.20/modobj/ipsec_alg_cryptoapi.c:564:12: error: implicit declaration of function 'crypto_has_hash' [-Werror=implicit-function-declaration]
     return crypto_has_hash(digestname, 0, 0);
            ^~~~~~~~~~~~~~~
/usr/src/libreswan-3.20/modobj/ipsec_alg_cryptoapi.c: In function '_capi_hmac_new_key':
/usr/src/libreswan-3.20/modobj/ipsec_alg_cryptoapi.c:655:8: error: implicit declaration of function 'crypto_alloc_hash' [-Werror=implicit-function-declaration]
  tfm = crypto_alloc_hash(dptr->digestname, 0, CRYPTO_ALG_ASYNC);
        ^~~~~~~~~~~~~~~~~
/usr/src/libreswan-3.20/modobj/ipsec_alg_cryptoapi.c:655:6: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  tfm = crypto_alloc_hash(dptr->digestname, 0, CRYPTO_ALG_ASYNC);
      ^
/usr/src/libreswan-3.20/modobj/ipsec_alg_cryptoapi.c:662:6: error: implicit declaration of function 'crypto_hash_setkey' [-Werror=implicit-function-declaration]
  if (crypto_hash_setkey(tfm, key, keylen)<0)
      ^~~~~~~~~~~~~~~~~~
/usr/src/libreswan-3.20/modobj/ipsec_alg_cryptoapi.c:667:3: error: implicit declaration of function 'crypto_free_hash' [-Werror=implicit-function-declaration]
   crypto_free_hash(tfm);
   ^~~~~~~~~~~~~~~~
/usr/src/libreswan-3.20/modobj/ipsec_alg_cryptoapi.c: In function '_capi_hmac_hash':
/usr/src/libreswan-3.20/modobj/ipsec_alg_cryptoapi.c:687:19: error: storage size of 'desc' isn't known
  struct hash_desc desc;
                   ^~~~
/usr/src/libreswan-3.20/modobj/ipsec_alg_cryptoapi.c:710:8: error: implicit declaration of function 'crypto_hash_digest' [-Werror=implicit-function-declaration]
  ret = crypto_hash_digest(&desc, &sg, len, hash_buf);
        ^~~~~~~~~~~~~~~~~~
/usr/src/libreswan-3.20/modobj/ipsec_alg_cryptoapi.c:687:19: warning: unused variable 'desc' [-Wunused-variable]
  struct hash_desc desc;

Thanks for help
Francis

**Comment by letoams** [comment]
On Sun, 21 May 2017, Francis wrote:

> Here is the errors displayed :
> /usr/src/libreswan-3.20/modobj/ipsec_alg_cryptoapi.c: In function 'setup_digest':
> /usr/src/libreswan-3.20/modobj/ipsec_alg_cryptoapi.c:564:12: error: implicit declaration of function 'crypto_has_hash'
> [-Werror=implicit-function-declaration]
> return crypto_has_hash(digestname, 0, 0);

That is the new ahash kernel API. A fix for this will be in 3.21 (and
git master) in the next couple of days.

Paul

**Comment by letoams** [comment]
fixed in 3.21
