### ISSUE TITLE
Set libreswan in FIPS mode but got`FIPS HMAC integrity support [disabled]`

### ISSUE THREAD

**Issue by sky9090** [libreswan/libreswan#970]
I have a RHEL8 server, and install the libreswan packages with FIPS mode enabled.
```
# cat /proc/version
Linux version 4.18.0-372.32.1.el8_6.x86_64 (mockbuild@x86-vm-08.build.eng.bos.redhat.com) (gcc version 8.5.0 20210514 (Red Hat 8.5.0-10) (GCC)) #1 SMP Fri Oct 7 12:35:10 EDT 202
```
```
# ipsec version
Linux Libreswan 4.5 (XFRM) on 4.18.0-372.32.1.el8_6.x86_64
```
```
# ipsec whack --fipsstatus
000 FIPS mode enabled
```

When I check the available algorithms in FIPS mode, I saw `FIPS HMAC integrity support [disabled]` information.
```
# ipsec pluto --selftest 2>&1 | head -11
3395
Initializing NSS using read-write database "sql:/etc/ipsec.d"
FIPS Mode: YES
NSS crypto library initialized
FIPS mode enabled for pluto daemon
NSS library is running in FIPS mode
FIPS HMAC integrity support [disabled]
libcap-ng support [enabled]
Linux audit support [enabled]
Starting Pluto (Libreswan Version 4.5 IKEv2 IKEv1 XFRM XFRMI esp-hw-offload FORK PTHREAD_SETSCHEDPRIO GCC_EXCEPTIONS NSS (IPsec profile) (NSS-PRF) DNSSEC SYSTEMD_WATCHDOG LABELED_IPSEC (SELINUX) SECCOMP LIBCAP_NG LINUX_AUDIT AUTH_PAM NETWORKMANAGER CURL(non-NSS) LDAP(non-NSS)) pid:3395
core dump dir: /run/pluto
secrets file: /etc/ipsec.secrets
```

What does `FIPS HMAC integrity support [disabled]` mean? How do I enable it to make `FIPS HMAC integrity support [enabled]`? If I want to deploy a FIPS-compliant IPsec VPN based on libreswan, should I enable it?

**Comment by letoams** [comment]
On Wed, 4 Jan 2023, ppeixiao wrote:

> I have a RHEL8 server, and install the libreswan packages with FIPS mode enabled.

> Linux Libreswan 4.5 (XFRM) on 4.18.0-372.32.1.el8_6.x86_64
> 
> # ipsec whack --fipsstatus
> 000 FIPS mode enabled
> 
> When I check the available algorithms in FIPS mode, I saw FIPS HMAC integrity support [disabled].
> What it mean? How can I enabled it? Should I enable it if I want to deploy a FIPS-compliant IPsec VPN?
> What does that mean? How do I enable it to make FIPS HMAC integrity support [enabled]? If I want to deploy a
> FiPS-compliant IPsec VPN, should I enable it?

That is probably an error in the backport of libreswan FIPS code to 4.5.

With the changes in NSS, there is no more code inside libreswan that
requires a FIPS selftest as all FIPS operations are done by NSS.

> 
> # ipsec pluto --selftest 2>&1 | head -11
> 3395
> Initializing NSS using read-write database "sql:/etc/ipsec.d"
> FIPS Mode: YES
> NSS crypto library initialized
> FIPS mode enabled for pluto daemon
> NSS library is running in FIPS mode
> FIPS HMAC integrity support [disabled]
> libcap-ng support [enabled]
> Linux audit support [enabled]
> Starting Pluto (Libreswan Version 4.5 IKEv2 IKEv1 XFRM XFRMI esp-hw-offload FORK PTHREAD_SETSCHEDPRIO GCC_EXCEPTIO
> NS NSS (IPsec profile) (NSS-PRF) DNSSEC SYSTEMD_WATCHDOG LABELED_IPSEC (SELINUX) SECCOMP LIBCAP_NG LINUX_AUDIT AUT
> H_PAM NETWORKMANAGER CURL(non-NSS) LDAP(non-NSS)) pid:3395
> core dump dir: /run/pluto
> secrets file: /etc/ipsec.secrets

This looks good. Further in the output it will also show which
algorithms are available to libreswan, so you should not see
any of the MD5, SHA1 etc.

CC:ing Daiki and Ondrey in case they want to fix this cosmetic change.

Paul

**Comment by letoams** [comment]
On Jan 5, 2023, at 22:49, ppeixiao ***@***.***> wrote:﻿
Hi @letoams, thank you for your reply.
According to your reply, my understanding is that in the previous libreswan code, FIPS HMAC integrity verification requires a self-test. But with the changes in NSS, all FIPS operations are done by NSS, and there is no requirement for FIPS selftest inside libreswan code.Yes.So the pluto output information of  FIPS HMAC integrity support [disabled] is reasonable because there is no FIPS selftest code to do the HMAC integrity support.

Yes. The code is still there to support older versions of nss, but afaik rhel8 libreswan has the required nss for libreswan to be able to remain out of the FIPS boundary and therefor does not require the integrity self test with the pluto.hmac file.PaulMessage ID: ***@***.***>

**Comment by sky9090** [comment]
Hi @letoams, thanks for the quick answer.
Since there is no FIPS selftest inside the libreswan code to do the HMAC integrity support, whether the HMAC integrity algorithms will be checked within the NSS.

**Comment by cagney** [comment]
Yes, the message is misleading.  Here's the relevant code:
```
#ifdef FIPS_CHECK
	llog(RC_LOG, logger, "FIPS HMAC integrity support [enabled]");
	bool fips_files = FIPSCHECK_verify_files(fips_package_files);
	if (fips_files) {
		llog(RC_LOG, logger, "FIPS HMAC integrity verification self-test passed");
	} else if (libreswan_fipsmode()) {
		fatal(PLUTO_EXIT_FIPS_FAIL, logger, "FIPS HMAC integrity verification self-test FAILED");
	} else {
		llog(RC_LOG_SERIOUS, logger, "FIPS HMAC integrity verification self-test FAILED");
	}
#else
	llog(RC_LOG, logger, "FIPS HMAC integrity support [disabled]");
#endif
```
when enabled libreswan was checking itself (the executable) against an expected hash stored in a file.  It goes back to when libreswan was inside the FIPS boundary (and yes, this is all circular making it silly :-).

Presumably anything FIPS shall use latest NSS making this code dead?

**Comment by letoams** [comment]
On Mon, 9 Jan 2023, cagney wrote:

> Yes, the message is misleading. Here's the relevant code:
> 
> #ifdef FIPS_CHECK
> 	llog(RC_LOG, logger, "FIPS HMAC integrity support [enabled]");
> 	bool fips_files = FIPSCHECK_verify_files(fips_package_files);
> 	if (fips_files) {
> 		llog(RC_LOG, logger, "FIPS HMAC integrity verification self-test passed");
> 	} else if (libreswan_fipsmode()) {
> 		fatal(PLUTO_EXIT_FIPS_FAIL, logger, "FIPS HMAC integrity verification self-test FAILED");
> 	} else {
> 		llog(RC_LOG_SERIOUS, logger, "FIPS HMAC integrity verification self-test FAILED");
> 	}
> #else
> 	llog(RC_LOG, logger, "FIPS HMAC integrity support [disabled]");
> #endif
> 
> when enabled libreswan was checking itself (the executable) against an expected hash stored in a file. It goes back to when
> libreswan was inside the FIPS boundary (and yes, this is all circular making it silly :-).

I fixed the messages.

> Presumably anything FIPS shall use latest NSS making this code dead?

I'd like to leave it in for a little bit :)

Paul

**Comment by cagney** [comment]
96b288bf4ef0cefebf052982c5559dde207745e7
