### ISSUE TITLE
do CATs need a block?

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#972]
When an SPD pair needs to be blocked, should the corresponding client address translation also be blocked?

Hmm, actually, since a CAT kernel policy is LOCAL-HOST -> REMOTE->SELECTOR, it only needs to install one cat per remote selector, if at all.

**Comment by letoams** [comment]
On Wed, 11 Jan 2023, cagney wrote:

> When an SPD pair needs to be blocked, should the corresponding client address translation also be blocked?

No, the CAT IP comes from the server, so if we didnt get anything
functional from the server, nothing needs to be blocked. And if we
tear down, the IP is removed so no need for a block then either.
