### ISSUE TITLE
including hostname in OBJDIR makes builds unreproducible

### ISSUE THREAD

**Issue by dkg** [libreswan/libreswan#989]
As noted over at https://bugs.debian.org/1020736, `mk/objdir.mk` by default makes OBJDIR embed the value of the build hostname, which in turn gets embedded in the resulting executable.

As a result, the executable isn't [reproducible](https://reproducible-builds.org), which is not great practice.

We have a couple workarounds to make the build reproducible -- we can set `HOST` manually, or set `OBJDIR` manually, but it seems to me that the default should be reproducible, and the builder should need to work to make it unreproducible.

Would the libreswan project consider removing `HOST` from the default definition of `OBJDIR`?  What advantage is there for the project in including `HOST` there by default?   Of course this wouldn't rule out leaving the hostname (or anything else) in the `OBJDIR` for people with unusual build practices:  If a builder really does have several different builds happening in the same directory from different hosts (building on NFS?) and they don't want a collision, then that builder can manually set OBJDIR for their own purpose, right?

**Comment by cagney** [comment]
A packaging system trying to be reproducible should just set OBJDIR.  It can be an absolute path.

A typical developer build is KVM host (likely Fedora) + Fedora, FreeBSD, NetBSD, and OpenBSD KVM guests, all from the same tree.  ARCH doesn't cut it, neither does OS.ARCH.  Hence the current value.

However, I'm also experimenting with the KVM OBJDIR being /var/tmp within the guest - there are both advantages and disadvantages (unrelated to this bug) to this.  Depending on how that goes OBJDIR might get simplified.

**Comment by paulwouters** [comment]
We had the default be reproducible builds and anything else by default should be considered a bug.

**Comment by dkg** [comment]
It was changed in 48d4a3daa08c5f678e0f85c3ae591342e5fd1f2a to become non-reproducible, with the justification:

> Adding $(HOST) so that NFS builds have a better chance of working.

I think it would be better to have builds be reproducible by default, and ask NFS builders to manually set OBJDIR.
