### ISSUE TITLE
testing: xauth passwd file (potentially) misplaced

### ISSUE THREAD

**Issue by The-Mule** [libreswan/libreswan#991]
Currently passwd file used for xauth tests is placed in testing/baseconfigs/.../etc/ipsec.d/passwd with policies and NSS DB and copied to nssdir in swan-prep. This only works when ipsecdir is the same as nssdir because this file is expected to be in ipsecdir. It causes 13 failures in xauth bucket on systems using nssdir=/var/lib/ipsec/nss  & ipsecdir=/etc/ipsec.d. The fix is easy and I'll try to add a patch by the end of the week, hopefully.

**Comment by The-Mule** [comment]
This commit https://github.com/The-Mule/libreswan/commit/a658d4c0ff5e5054ff7c497a85aad03e3d42e1de fixed the problem for me. However, it is probably not the cleanest way (it keeps copying xauth 'passwd' to nssdir and only adds additional copy to ipsecdir). The best way would be to move xauth 'passwd' to tests using it and follow the same approach as for 'xl2tpdconf'. It would require more changes since xauth 'passwd' is used in more tests.

**Comment by cagney** [comment]
There's `ipsec --directory` to print the path to ipsec's libexec.  Perhaps there should be similar option for NSS (but note that --nssdir is taken).
Or `ipsec _env` to print useful environment variables.

**Comment by letoams** [comment]
On Mon, 23 Jan 2023, cagney wrote:

> There's ipsec --directory to print the path to ipsec's libexec. Perhaps there should be similar option for
> NSS (but note that --nssdir is taken).
> Or ipsec _env to print useful environment variables.

Like:

***@***.***:~$ sudo ipsec addconn --configsetup
export confreadstatus=''
export configfile='/etc/ipsec.conf'
export ctlsocket='/run/pluto/pluto.ctl'
export logtime='yes'
export logappend='yes'
export logip='yes'
export audit_log='yes'
export dnssec_enable='yes'
export dnssec_rootkey_file='/var/lib/unbound/root.key'
export dumpdir='/run/pluto'
export ipsecdir='/etc/ipsec.d'
export nssdir='/var/lib/ipsec/nss'
export secretsfile='/etc/ipsec.secrets'
export uniqueids='yes'
export shuntlifetime='900'
export crl_strict='no'
export ocsp_strict='no'
export ocsp_enable='no'
export ocsp_timeout='2'
export ocsp_cache_size='1000'
export ocsp_cache_min_age='3600'
export ocsp_cache_max_age='86400'
export ddos_mode='1'
export seccomp='3'
export ddos_ike_threshold='25000'
export max_halfopen_ike='50000'
export ike_socket_errqueue='yes'
export xfrmlifetime='30'
export listen_tcp='no'
export listen_udp='yes'
export nhelpers='-1'
export drop_oppo_null='no'
export ikev1_secctx_attr_type='32001'

Note that the XAUTH passwords go into the "secrets" file, so
/etc/ipsec.secrets or its include files. Tests should not expect
it in /var/lib/ipsec/nss.

The patch is right, I will merge it in.

Paul
