### ISSUE TITLE
revival should put the connection into ROUTED_NEGOTIATION, not ROUTED_PROSPECTIVE

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#992]
See ikev2-revive-through-nat-02-cleanfail which, on detecting that the connection is down transitions ROUTED_TUNNEL -> ROUTED_PROSPECTIVE, but probably should be ROUTED_NEGOTIATION

**Comment by cagney** [comment]
here's what's happening on east:
```
"road-eastnet-ikev2"[1] 192.1.2.254 #2: responder established Child SA using #1; IPsec tunnel [192.0.2.0-192.0.2.255:0-65535 0] -> [192.1.3.209-192.1.3.209:0-65535 0] {ESPinUDP/ESN=>0xbb4c2754 <0xa72603f4 xfrm=AES_GCM_16_256-NONE NATD=192.1.2.254:6666 DPD=passive}
"road-eastnet-ikev2"[1] 192.1.2.254 #2: ESP traffic information: in=84B out=84B
"road-eastnet-ikev2"[1] 192.1.2.254 #1: deleting state (STATE_V2_ESTABLISHED_IKE_SA) aged 0.528005s and NOT sending notification
"road-eastnet-ikev2"[1] 192.1.2.254: deleting connection instance with peer 192.1.2.254 {isakmp=#0/ipsec=#0}
```
it isn't even trying to revive

**Comment by antonyantony** [comment]
On Thu, Feb 16, 2023 at 12:42:36PM -0800, cagney wrote:
> here's what's happening on east:
> ```
> "road-eastnet-ikev2"[1] 192.1.2.254 #2: responder established Child SA using #1; IPsec tunnel [192.0.2.0-192.0.2.255:0-65535 0] -> [192.1.3.209-192.1.3.209:0-65535 0] {ESPinUDP/ESN=>0xbb4c2754 <0xa72603f4 xfrm=AES_GCM_16_256-NONE NATD=192.1.2.254:6666 DPD=passive}
> "road-eastnet-ikev2"[1] 192.1.2.254 #2: ESP traffic information: in=84B out=84B
> "road-eastnet-ikev2"[1] 192.1.2.254 #1: deleting state (STATE_V2_ESTABLISHED_IKE_SA) aged 0.528005s and NOT sending notification
> "road-eastnet-ikev2"[1] 192.1.2.254: deleting connection instance with peer 192.1.2.254 {isakmp=#0/ipsec=#0}
> ```
> it isn't even trying to revive

east is behind NAT? How can east revive? I mean where would east send new 
IKE request to? I would go one step further when east is not the initiator 
and the dpd is not restart east should not revive even for non NAT.

**Comment by cagney** [comment]
see the documentation for auto=keep

**Comment by cagney** [comment]
683e3b7d47c0bca8c1b99237b29f31c19c63e818 misplaced setting the UP bit when adding the template connection.
However, it might be better to delay setting the UP bit until the template is instantiated - when config->autostart==keep.  That way there's less confusion over what UP means.

**Comment by cagney** [comment]
It goes back into ROUTED_ONDEMAND, now that that is added.
