### ISSUE TITLE
IKE_SA_INIT message containing NO_PROPOSAL_CHOSEN notification; message payloads: N; missing payloads: SA,KE,Ni

### ISSUE THREAD

**Issue by BlueAquan** [libreswan/libreswan#999]
Dear all
I am trying to establish a site-to-site VPN between two networks, one at HO and another at a site office. The HO already has established successful connections to multiple site offices, but at one particular site, the public IP is not directly configured on the VPN gateway, but on the ISP's router which does some basic packet filtering and NAT. That has proved to be a problem in this particular case to reach the machine running behind this ISP's router. 

### At the HO Server Linux Libreswan 4.3 (netkey)
The machine has two NIC. 
NIC 1: 192.168.1.1  
NIC 2: A.B.C.D **(Public IP)  The Internet terminates directly on this NIC**
```
conn PLUTOSUBNET
	also=EUROPA-PLUTO
	leftsubnet=10.10.128.0/24
	leftsourceip=10.10.128.100
	rightsubnet=192.168.1.0/24
	rightsourceip=192.168.1.1
	auto=start
conn EUROPA-PLUTO
	type=tunnel
	left=W.X.Y.Z
	right=A.B.C.D
	authby=secret
	ikev2=insist
	pfs=no
	ike=aes256-sha2_512+sha2_256-dh21
	esp=aes256-sha2_512+sha1+sha2_256;dh21
	dpddelay=5
	dpdtimeout=120
	dpdaction=restart
	encapsulation=yes
```

### At the Site Office Linux Libreswan 4.4 (netkey)
**The machine has two NIC. But the Public IP is not configured on either of them**
NIC 1: 192.168.14.129
NIC 2: 10.10.128.100  -> **Default gateway is 10.10.128.1 (Which is the LAN interface of an ISP router)
 			                The Public IP W.X.Y.Z configured on the WAN interface of this ISP router and it masquerades.**	
```
conn PLSUBNET
	also=PLUTO-EUROPA
	leftsubnet=10.10.128.0/24
	leftsourceip=10.10.128.100
	rightsubnet=192.168.1.0/24
	rightsourceip=192.168.1.1
	auto=start
conn PLUTO-EUROPA
	type=tunnel
	left=%defaultroute
	leftid=W.X.Y.Z
	right=A.B.C.D
	authby=secret
	ikev2=insist
	pfs=no
	ike=aes256-sha2_512+sha2_256-dh21
	esp=aes256-sha2_512+sha1+sha2_256;dh21
	dpddelay=5
	dpdtimeout=120
	dpdaction=restart
	encapsulation=yes
```

**The log at HO** repeats this message
"PLUTOSUBNET" #39: STATE_PARENT_I1: retransmission; will wait 32 seconds for response
"PLUTOSUBNET" #39: dropping unexpected IKE_SA_INIT message containing NO_PROPOSAL_CHOSEN notification; message payloads: N; missing payloads: SA,KE,Ni

**The log at Site Office** 
packet from 10.10.128.1:500: ISAKMP_v2_IKE_SA_INIT message received on 10.10.128.100:500 but no suitable connection found with IKEv2 policy
packet from 10.10.128.1:500: responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN

I've been struggling with the issue for a long time now, any help from the community would be greatly appreciated.  Please let me know if you need any further logs or details, will quickly add them as requested.

Thanks, Best
BA

**Comment by BlueAquan** [comment]
Dear friends
There has been an interesting change in status... After revisiting the NAT rules on the ISP router over and over again at the site office and also the nftables, **I sent the Site Office machine for a reboot, all the while checking the logs continuously at the HO machine.**
And suddenly when the Site Office machine comes up after a reboot, the **tunnel gets established and machines on both sides are able to reach each other, but...... only for less than half a minute!**  The tunnel when checked continues to remain established, no change in the log, but machines either side can't reach each other. 
Although I can see both ESPin and ESPout data are increasing quantitatively on both sides, I can't ping after that brief moment of success.
The most worrying factor of all this, is that I haven't made any change in the configuration!  Has it got to do anything to do with the version difference at HO and Site Office...?

```
The logs from the HO machine FYI please

980030: "PLUTOSUBNET" #8: STATE_PARENT_I1: retransmission; will wait 16 seconds for response
984155: "PLUTOSUBNET" #8: STATE_PARENT_I1: retransmission; will wait 32 seconds for response
634277: "PLUTOSUBNET" #9: proposal 1:IKE=AES_CBC_256-HMAC_SHA2_512-HMAC_SHA2_512_256-ECP_521 chosen from remote proposals 1:IKE:ENCR=AES_CBC_256;PRF=HMAC_SHA2_512;PRF=HMAC_SHA2_256;INTEG=HMAC_SHA2_512_256;INTEG=HMAC_SHA2_256_128;DH=ECP_521[first-match]
636046: "PLUTOSUBNET" #9: sent IKE_SA_INIT reply {auth=IKEv2 cipher=AES_CBC_256 integ=HMAC_SHA2_512_256 prf=HMAC_SHA2_512 group=DH21}
"PLUTOSUBNET" #9: processing decrypted IKE_AUTH request: SK{IDi,AUTH,SA,TSi,TSr}
"PLUTOSUBNET" #9: IKEv2 mode peer ID is ID_IPV4_ADDR: 'W.X.Y.Z'
"PLUTOSUBNET" #9: authenticated using authby=secret
"PLUTOSUBNET": local ESP/AH proposals (IKE_AUTH responder matching remote ESP/AH proposals): 
"PLUTOSUBNET":   1:ESP=AES_CBC_256-HMAC_SHA2_512_256+HMAC_SHA1_96+HMAC_SHA2_256_128-NONE-DISABLED
"PLUTOSUBNET" #10: proposal 1:ESP=AES_CBC_256-HMAC_SHA2_512_256-DISABLED SPI=cff38461 chosen from remote proposals 1:ESP:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_512_256;INTEG=HMAC_SHA1_96;INTEG=HMAC_SHA2_256_128;ESN=DISABLED[first-match]
"PLUTOSUBNET" #10: negotiated connection [192.168.1.0-192.168.1.255:0-65535 0] -> [10.10.128.0-10.10.128.255:0-65535 0]
"PLUTOSUBNET" #10: IPsec SA established tunnel mode {ESPinUDP=>0xcff38461 <0x51123a6c xfrm=AES_CBC_256-HMAC_SHA2_512_256 NATOA=none NATD=W.X.Y.Z:4500 DPD=active}
"PLUTOSUBNET" #8: suppressing retransmit because IKE SA was superseded #9 try=4; drop this negotiation
"PLUTOSUBNET" #8: deleting state (STATE_PARENT_I1) aged 64.012686s and NOT sending notification

```

Thanks, BA

**Comment by paulwouters** [comment]
This looks like a misconfiguration since you get NO_PROPOSAL_CHOSEN. Ensure both sides use compatible configurations
